import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter058: ChapterDefinition = {
  id: 'chapter-058',
  number: 58,
  slug: 'verbs-with-fixed-prepositions',
  title: 'Verbs with Fixed Prepositions',
  germanTitle: 'Verben mit festen Präpositionen',
  level: 'B1',
  section: 'verbs-3',
  objective:
    'Learn to treat certain German verbs together with a specific preposition and a specific case as one fixed, memorized unit — such as sich interessieren für, warten auf, sich freuen über/auf, denken an, Angst haben vor, and teilnehmen an — since the correct preposition and case cannot be predicted from the English translation, and use these fixed combinations to build statements and ask questions about people and things.',
  prerequisites: [17, 18, 24, 33, 34],
  estimatedMinutes: 28,
  tags: [
    'verbs with prepositions',
    'verben mit festen präpositionen',
    'fixed prepositions',
    'case government',
    'sich interessieren für',
    'warten auf',
    'sich freuen auf',
    'sich freuen über',
    'denken an',
    'Angst haben vor',
    'teilnehmen an',
    'wen',
    'wem',
    'question words',
  ],
  explanation: {
    introduction: [
      'Many German verbs are always followed by one particular preposition, and that preposition always governs one particular case. Together the three pieces — verb, preposition, and case — function as a single fixed expression that must be learned as a whole, not built up word by word from an English dictionary. Ich interessiere mich für Musik uses für, not the "in" you might expect from "interested in"; Ich warte auf den Bus uses auf, not the "for" you might expect from "wait for". Learners who translate preposition by preposition from English almost always guess wrong.',
      'This chapter builds directly on the case-governing prepositions from Chapters 33 and 34: the seven prepositions that always take the dative and the five that always take the accusative. Many of the fixed combinations here reuse "two-way" prepositions such as an, auf, über, and vor — prepositions that can normally govern either the accusative or the dative depending on whether something is moving or staying put. Fixed verb-plus-preposition phrases short-circuit that general two-way rule: the specific verb decides the case once and for all, regardless of movement or location.',
      'You will also learn to ask questions about the people and things involved in these fixed phrases, extending the wer/wen/wem/was system from Chapter 24: a preposition simply attaches to wen or wem, exactly as it attaches to any other noun phrase (für wen, an wen, auf wen; von wem, vor wem, mit wem). Asking about a thing instead of a person uses a different, fused word such as wofür or woran — those forms appear here just enough to recognize and use in simple questions; the full system of these pronominal-adverb question words is the focus of the next chapter.',
    ],
    rules: [
      {
        id: 'ch58-rule-01',
        heading: 'A fixed unit: verb + preposition + case',
        paragraphs: [
          'A fixed verb-preposition combination behaves like a single piece of vocabulary. You cannot swap in a different, seemingly synonymous preposition, and you cannot guess the case from general rules about the preposition alone — both the preposition and the case belong to the verb, permanently.',
          'Compare warten auf den Bus (to wait for the bus) with the literal English "wait for": German never uses für here. Compare sich interessieren für Kunst (to be interested in art) with the literal English "interested in": German never uses in here. The safest approach is to always learn the whole chunk — verb, preposition, and a sample case-marked noun — together, as if it were one long word.',
          'From this point on, whenever you meet a new verb like this, add it to your vocabulary exactly in this form: verb + preposition + (Akkusativ) or verb + preposition + (Dativ), together with one memorable example sentence.',
        ],
      },
      {
        id: 'ch58-rule-02',
        heading: 'Common combinations with the accusative',
        paragraphs: [
          'A large group of fixed verb-preposition combinations always takes the accusative: sich interessieren für (to be interested in), warten auf (to wait for), sich freuen auf (to look forward to), sich freuen über (to be happy about), denken an (to think of/about), sich erinnern an (to remember), glauben an (to believe in), sich kümmern um (to take care of), sich verlassen auf (to rely on), sich gewöhnen an (to get used to), and sprechen über (to talk about).',
          'Ich interessiere mich für Fremdsprachen. Wir warten auf den Zug. Er kümmert sich um seine kleine Schwester. In every one of these sentences, the noun after the preposition is in the accusative, no matter whether the preposition is normally two-way (an, auf, über) or always accusative on its own.',
        ],
      },
      {
        id: 'ch58-rule-03',
        heading: 'Common combinations with the dative',
        paragraphs: [
          'A smaller but equally important group always takes the dative: Angst haben vor (to be afraid of), träumen von (to dream of), teilnehmen an (to take part in), sich beschäftigen mit (to deal with, to occupy oneself with), gratulieren zu (to congratulate on), sprechen von (to talk about, a near-synonym of sprechen über), and bestehen auf (to insist on).',
          'Ich habe Angst vor Prüfungen. Sie träumt von einer Reise nach Japan. Wir gratulieren dir zu deinem Erfolg. Here the noun after the preposition is in the dative every time, again regardless of whether the preposition (vor, an, mit, auf) is normally two-way.',
        ],
      },
      {
        id: 'ch58-rule-04',
        heading: 'The same preposition, different verb, different case',
        paragraphs: [
          'Because an, auf, über, and vor are two-way prepositions in their ordinary spatial use, it is tempting to think their case can be predicted from a general pattern. Fixed verb phrases prove that this does not work: denken an and sich erinnern an both take the accusative, but teilnehmen an takes the dative. warten auf, sich freuen auf, and sich verlassen auf all take the accusative, but bestehen auf takes the dative.',
          'This is exactly why each combination has to be memorized individually, verb by verb, rather than derived from the preposition. Keep an eye out especially for bestehen auf + Dativ, since it goes against the more common accusative pattern of the other auf-verbs in this chapter.',
        ],
      },
      {
        id: 'ch58-rule-05',
        heading: 'sich freuen auf vs. sich freuen über',
        paragraphs: [
          'Both sich freuen auf and sich freuen über take the accusative, so the case never tells them apart — only the preposition does, and the preposition signals a difference in meaning. sich freuen auf looks ahead to something that has not happened yet: Ich freue mich auf die Ferien (I am looking forward to the holidays, which have not started).',
          'sich freuen über reacts to something that has already happened or is already true: Ich freue mich über dein Geschenk (I am happy about your gift, which you have already given me). If the thing you are happy about lies in the future, use auf; if it already exists or already happened, use über.',
        ],
      },
      {
        id: 'ch58-rule-06',
        heading: 'Asking about people: preposition + wen or wem',
        paragraphs: [
          'To ask about a person inside one of these fixed phrases, simply combine the preposition with wen (if the verb\'s fixed case is accusative) or wem (if it is dative) — exactly as you learned to combine prepositions with question words in Chapter 24.',
          'Für wen interessierst du dich? An wen denkst du? Auf wen wartest du? all use wen because interessieren für, denken an, and warten auf are fixed with the accusative. Von wem träumst du? Vor wem hast du Angst? Mit wem beschäftigst du dich gerade? all use wem because träumen von, Angst haben vor, and sich beschäftigen mit are fixed with the dative.',
        ],
      },
      {
        id: 'ch58-rule-07',
        heading: 'Asking about things: a first look at wofür, woran, worauf',
        paragraphs: [
          'When the thing you are asking about is not a person but a thing or an idea, German usually does not say "für was" or "an was" in careful writing. Instead, the preposition fuses together with wo- (adding an extra -r- before a preposition that starts with a vowel) into a single question word: für → wofür, an → woran, auf → worauf, von → wovon.',
          'Wofür interessierst du dich? (What are you interested in?) Woran denkst du? (What are you thinking of?) Worauf wartest du? (What are you waiting for?) You only need to recognize and use a handful of these forms for now; the complete pattern — including when the plain preposition + was is acceptable in casual speech — is the subject of the next chapter.',
        ],
      },
      {
        id: 'ch58-rule-08',
        heading: 'No shortcuts: learn every combination individually',
        paragraphs: [
          'There is no reliable rule that predicts a verb\'s fixed preposition or case from its English translation, from the preposition\'s "normal" meaning, or from any pattern among similar-sounding verbs. sprechen über and sprechen von both mean roughly "to talk about", yet one takes the accusative and the other the dative; denken an and teilnehmen an share the same preposition but different cases.',
          'The only dependable strategy is to memorize each verb-preposition-case combination as its own fixed chunk, together with a short example sentence, exactly the way you memorize the gender of a noun. Flashcards that show the whole phrase — Angst haben vor + Dativ, not just haben or vor in isolation — make this much easier than trying to reconstruct the pattern later.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch58-table-01',
        title: 'Fixed verb + preposition combinations with the accusative',
        columns: ['Verb + preposition', 'Case', 'Example'],
        columnCases: [null, 'accusative', null],
        rows: [
          ['sich interessieren für', 'Akkusativ', 'Ich interessiere mich für Kunst. (I am interested in art.)'],
          ['warten auf', 'Akkusativ', 'Wir warten auf den Bus. (We are waiting for the bus.)'],
          ['sich freuen auf', 'Akkusativ', 'Ich freue mich auf die Ferien. (I am looking forward to the holidays.)'],
          ['sich freuen über', 'Akkusativ', 'Er freut sich über das Geschenk. (He is happy about the gift.)'],
          ['denken an', 'Akkusativ', 'Sie denkt oft an ihre Familie. (She often thinks of her family.)'],
          ['sich erinnern an', 'Akkusativ', 'Erinnerst du dich an den Film? (Do you remember the movie?)'],
          ['glauben an', 'Akkusativ', 'Ich glaube an das Gute im Menschen. (I believe in the good in people.)'],
          ['sich kümmern um', 'Akkusativ', 'Wer kümmert sich um die Kinder? (Who is taking care of the children?)'],
          ['sich verlassen auf', 'Akkusativ', 'Ich verlasse mich auf dich. (I rely on you.)'],
          ['sich gewöhnen an', 'Akkusativ', 'Wir gewöhnen uns an das Wetter. (We are getting used to the weather.)'],
          ['sprechen über', 'Akkusativ', 'Wir sprechen über das Projekt. (We are talking about the project.)'],
        ],
        note: 'Even though an, auf, and über are normally two-way prepositions, every one of these fixed verb phrases always takes the accusative.',
      },
      {
        id: 'ch58-table-02',
        title: 'Fixed verb + preposition combinations with the dative',
        columns: ['Verb + preposition', 'Case', 'Example'],
        columnCases: [null, 'dative', null],
        rows: [
          ['Angst haben vor', 'Dativ', 'Ich habe Angst vor der Dunkelheit. (I am afraid of the dark.)'],
          ['träumen von', 'Dativ', 'Er träumt von einer Weltreise. (He dreams of a trip around the world.)'],
          ['teilnehmen an', 'Dativ', 'Sie nimmt an dem Kurs teil. (She is taking part in the course.)'],
          ['sich beschäftigen mit', 'Dativ', 'Wir beschäftigen uns mit dem Thema. (We are dealing with the topic.)'],
          ['gratulieren zu', 'Dativ', 'Ich gratuliere dir zum Geburtstag. (I congratulate you on your birthday.)'],
          ['sprechen von', 'Dativ', 'Er spricht von seiner Reise. (He talks about his trip.)'],
          ['bestehen auf', 'Dativ', 'Er besteht auf seinem Recht. (He insists on his right.)'],
        ],
        note: 'bestehen auf is the exception to watch for: unlike warten auf, sich freuen auf, and sich verlassen auf, it takes the dative, not the accusative.',
      },
    ],
    examples: [
      {
        german: 'Ich interessiere mich sehr für klassische Musik.',
        english: 'I am very interested in classical music.',
        highlight: ['interessiere mich für'],
        explanation: 'sich interessieren is always paired with für, and für here takes the accusative (klassische Musik).',
      },
      {
        german: 'Wartest du schon lange auf den Zug?',
        english: 'Have you been waiting for the train long?',
        highlight: ['auf den Zug'],
        explanation: 'warten is fixed with auf + Akkusativ; der Zug becomes den Zug.',
      },
      {
        german: 'Ich freue mich auf das Wochenende.',
        english: 'I am looking forward to the weekend.',
        highlight: ['freue mich auf'],
        explanation: 'The weekend has not happened yet, so the forward-looking preposition auf is used.',
      },
      {
        german: 'Ich freue mich über deine Nachricht.',
        english: 'I am happy about your message.',
        highlight: ['freue mich über'],
        explanation: 'The message has already arrived, so über is used instead of auf, even though the case (accusative) stays the same.',
      },
      {
        german: 'Denkst du manchmal an deine Schulzeit?',
        english: 'Do you sometimes think of your school days?',
        highlight: ['denkst', 'an'],
        explanation: 'denken is fixed with an + Akkusativ, not über, even though English "think about" might suggest über.',
      },
      {
        german: 'Viele Kinder haben Angst vor der Dunkelheit.',
        english: 'Many children are afraid of the dark.',
        highlight: ['Angst vor der Dunkelheit'],
        explanation: 'Angst haben is fixed with vor + Dativ; die Dunkelheit becomes der Dunkelheit.',
      },
      {
        german: 'Sie träumt von einem eigenen Haus.',
        english: 'She dreams of having her own house.',
        highlight: ['träumt von'],
        explanation: 'träumen is fixed with von + Dativ; ein Haus becomes einem Haus.',
      },
      {
        german: 'Nimmst du an der Konferenz teil?',
        english: 'Are you taking part in the conference?',
        highlight: ['an der Konferenz teil'],
        explanation: 'teilnehmen is fixed with an + Dativ; die Konferenz becomes der Konferenz.',
      },
      {
        german: 'Für wen interessierst du dich?',
        english: 'Who are you interested in?',
        highlight: ['Für wen'],
        explanation: 'The preposition für simply attaches to wen because interessieren für is fixed with the accusative and the answer is a person.',
      },
      {
        german: 'Worauf freust du dich am meisten?',
        english: 'What are you looking forward to the most?',
        highlight: ['Worauf'],
        explanation: 'Because the answer is a thing, not a person, the preposition auf fuses with wo- into worauf; the full pattern for these forms follows in the next chapter.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich interessiere mich in Musik.',
        correct: 'Ich interessiere mich für Musik.',
        explanation: 'Wrong preposition: the English "interested in" tempts learners to use in, but sich interessieren is always fixed with für.',
      },
      {
        incorrect: 'Ich warte für den Bus.',
        correct: 'Ich warte auf den Bus.',
        explanation: 'Wrong preposition: the English "wait for" tempts learners to use für, but warten is always fixed with auf.',
      },
      {
        incorrect: 'Ich denke oft über meine Familie.',
        correct: 'Ich denke oft an meine Familie.',
        explanation: 'Wrong preposition: the English "think about" tempts learners to use über, but denken is always fixed with an.',
      },
      {
        incorrect: 'Ich freue mich auf der Party.',
        correct: 'Ich freue mich auf die Party.',
        explanation: 'Wrong case after a correctly chosen preposition: sich freuen auf is fixed with the accusative, so it must be die Party, not the dative der Party — even though auf is normally a two-way preposition.',
      },
      {
        incorrect: 'Er besteht auf seine Meinung.',
        correct: 'Er besteht auf seiner Meinung.',
        explanation: 'Wrong case after a correctly chosen preposition: unlike most other auf-verbs in this chapter, bestehen auf is fixed with the dative, so it must be seiner Meinung, not the accusative seine Meinung.',
      },
    ],
    remember: [
      'Every fixed verb-preposition combination is one unit to memorize together with its case; the English translation of the preposition is not a reliable guide (warten auf, not warten für; denken an, not denken über; sich interessieren für, not sich interessieren in).',
      'Common accusative combinations: sich interessieren für, warten auf, sich freuen auf/über, denken an, sich erinnern an, glauben an, sich kümmern um, sich verlassen auf, sich gewöhnen an, sprechen über.',
      'Common dative combinations: Angst haben vor, träumen von, teilnehmen an, sich beschäftigen mit, gratulieren zu, sprechen von, bestehen auf.',
      'sich freuen auf (+ Akkusativ) looks ahead to something not yet happened; sich freuen über (+ Akkusativ) reacts to something already true or already received — same case, different preposition, different meaning.',
      'Two-way prepositions like an and auf do not reveal the case on their own inside fixed phrases: denken an and sich erinnern an take the accusative, but teilnehmen an takes the dative; warten auf and sich freuen auf take the accusative, but bestehen auf takes the dative.',
      'Questions about a person combine the preposition with wen (accusative) or wem (dative): für wen, auf wen, an wen versus von wem, vor wem, mit wem. Questions about a thing usually fuse the preposition with wo(r)- into one word (wofür, woran, worauf) — covered fully in the next chapter.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 28,
    requiredCorrectTextInputs: 6,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch58-ex-01',
      chapterNumber: 58,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sich interessieren für', 'accusative'],
      instruction: 'Choose the preposition that fixes this verb.',
      prompt: 'Ich interessiere mich ___ Kunst.',
      options: [
        { id: 'a', text: 'für' },
        { id: 'b', text: 'an' },
        { id: 'c', text: 'auf' },
        { id: 'd', text: 'über' },
      ],
      correctOptionId: 'a',
      explanation: 'sich interessieren is always fixed with für, never with an, auf, or über.',
    },
    {
      id: 'ch58-ex-02',
      chapterNumber: 58,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['warten auf', 'accusative'],
      instruction: 'Choose the preposition that fixes this verb.',
      prompt: 'Wartest du schon lange ___ den Bus?',
      options: [
        { id: 'a', text: 'auf' },
        { id: 'b', text: 'für' },
        { id: 'c', text: 'an' },
        { id: 'd', text: 'über' },
      ],
      correctOptionId: 'a',
      explanation: 'warten is always fixed with auf, not with für, even though English says "wait for".',
    },
    {
      id: 'ch58-ex-03',
      chapterNumber: 58,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sich freuen auf', 'future-event'],
      instruction: 'Choose the preposition that fits a future event.',
      prompt: 'Ich freue mich schon sehr ___ die Ferien. (they have not started yet)',
      options: [
        { id: 'a', text: 'auf' },
        { id: 'b', text: 'über' },
        { id: 'c', text: 'an' },
        { id: 'd', text: 'für' },
      ],
      correctOptionId: 'a',
      explanation: 'sich freuen auf looks ahead to something that has not happened yet, like upcoming holidays.',
    },
    {
      id: 'ch58-ex-04',
      chapterNumber: 58,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sich freuen über', 'completed-event'],
      instruction: 'Choose the preposition that fits an event that already happened.',
      prompt: 'Er freut sich ___ das tolle Geschenk. (he already received it)',
      options: [
        { id: 'a', text: 'über' },
        { id: 'b', text: 'auf' },
        { id: 'c', text: 'an' },
        { id: 'd', text: 'für' },
      ],
      correctOptionId: 'a',
      explanation: 'sich freuen über reacts to something that has already happened or already exists, like a gift already received.',
    },
    {
      id: 'ch58-ex-05',
      chapterNumber: 58,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['denken an', 'accusative'],
      instruction: 'Choose the preposition that fixes this verb.',
      prompt: 'Sie denkt oft ___ ihre Kindheit.',
      options: [
        { id: 'a', text: 'an' },
        { id: 'b', text: 'auf' },
        { id: 'c', text: 'für' },
        { id: 'd', text: 'über' },
      ],
      correctOptionId: 'a',
      explanation: 'denken is always fixed with an, not with über, even though English says "think about".',
    },
    {
      id: 'ch58-ex-06',
      chapterNumber: 58,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['Angst haben vor', 'dative'],
      instruction: 'Choose the preposition that fixes this expression.',
      prompt: 'Er hat Angst ___ Spinnen.',
      options: [
        { id: 'a', text: 'vor' },
        { id: 'b', text: 'für' },
        { id: 'c', text: 'an' },
        { id: 'd', text: 'über' },
      ],
      correctOptionId: 'a',
      explanation: 'Angst haben is always fixed with vor + Dativ.',
    },
    {
      id: 'ch58-ex-07',
      chapterNumber: 58,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['träumen von', 'dative'],
      instruction: 'Choose the preposition that fixes this verb.',
      prompt: 'Sie träumt ___ einem Haus am Meer.',
      options: [
        { id: 'a', text: 'von' },
        { id: 'b', text: 'über' },
        { id: 'c', text: 'an' },
        { id: 'd', text: 'für' },
      ],
      correctOptionId: 'a',
      explanation: 'träumen is always fixed with von + Dativ.',
    },
    {
      id: 'ch58-ex-08',
      chapterNumber: 58,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['teilnehmen an', 'dative'],
      instruction: 'Choose the preposition that fixes this verb.',
      prompt: 'Nimmst du auch ___ dem Kurs teil?',
      options: [
        { id: 'a', text: 'an' },
        { id: 'b', text: 'auf' },
        { id: 'c', text: 'für' },
        { id: 'd', text: 'mit' },
      ],
      correctOptionId: 'a',
      explanation: 'teilnehmen is always fixed with an + Dativ.',
    },
    {
      id: 'ch58-ex-09',
      chapterNumber: 58,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sich kümmern um', 'accusative'],
      instruction: 'Choose the preposition that fixes this verb.',
      prompt: 'Ich muss mich mehr ___ das Projekt kümmern.',
      options: [
        { id: 'a', text: 'um' },
        { id: 'b', text: 'für' },
        { id: 'c', text: 'an' },
        { id: 'd', text: 'über' },
      ],
      correctOptionId: 'a',
      explanation: 'sich kümmern is always fixed with um + Akkusativ.',
    },
    {
      id: 'ch58-ex-10',
      chapterNumber: 58,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['bestehen auf', 'dative', 'auf-trap'],
      instruction: 'Choose the preposition that fixes this verb.',
      prompt: 'Er besteht ___ seiner Meinung.',
      options: [
        { id: 'a', text: 'auf' },
        { id: 'b', text: 'für' },
        { id: 'c', text: 'an' },
        { id: 'd', text: 'mit' },
      ],
      correctOptionId: 'a',
      explanation: 'bestehen is fixed with auf, but unlike warten auf or sich freuen auf, it takes the dative: auf seiner Meinung.',
    },
    {
      id: 'ch58-ex-11',
      chapterNumber: 58,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['Angst haben vor', 'dative-article', 'feminine'],
      instruction: 'Choose the correct article form. (die Prüfung, Dativ after vor)',
      prompt: 'Ich habe Angst vor ___ Prüfung.',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'den' },
        { id: 'd', text: 'dem' },
      ],
      correctOptionId: 'a',
      explanation: 'Angst haben vor is fixed with the dative; the feminine article die becomes der in the dative.',
    },
    {
      id: 'ch58-ex-12',
      chapterNumber: 58,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['teilnehmen an', 'dative-article', 'masculine'],
      instruction: 'Choose the correct article form. (der Kurs, Dativ after an)',
      prompt: 'Sie nimmt an ___ Kurs teil.',
      options: [
        { id: 'a', text: 'dem' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'der' },
        { id: 'd', text: 'des' },
      ],
      correctOptionId: 'a',
      explanation: 'teilnehmen an is fixed with the dative; the masculine article der becomes dem in the dative.',
    },
    {
      id: 'ch58-ex-13',
      chapterNumber: 58,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['wen', 'question-word', 'person', 'warten auf'],
      instruction: 'Choose the correct question word for a person.',
      prompt: 'Ich warte auf meinen Freund. → Auf ___ wartest du?',
      options: [
        { id: 'a', text: 'wen' },
        { id: 'b', text: 'wem' },
        { id: 'c', text: 'wer' },
        { id: 'd', text: 'was' },
      ],
      correctOptionId: 'a',
      explanation: 'warten auf is fixed with the accusative; a person asked about with an accusative preposition needs wen.',
    },
    {
      id: 'ch58-ex-14',
      chapterNumber: 58,
      order: 14,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['worauf', 'question-word', 'thing', 'warten auf'],
      instruction: 'Choose the correct question word for a thing.',
      prompt: 'Ich warte auf den Bus. → ___ wartest du?',
      options: [
        { id: 'a', text: 'Worauf' },
        { id: 'b', text: 'Wofür' },
        { id: 'c', text: 'Woran' },
        { id: 'd', text: 'Wen' },
      ],
      correctOptionId: 'a',
      explanation: 'Because the answer is a thing, not a person, auf fuses with wo- into worauf instead of combining with wen.',
    },
    {
      id: 'ch58-ex-15',
      chapterNumber: 58,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['worauf', 'dialogue', 'sich freuen auf'],
      instruction: 'Read the exchange, then choose the question word that fits the reply.',
      prompt: 'Complete: "___ freust du dich am meisten?"',
      dialogue: [
        { speaker: 'Nina', german: 'Nächste Woche beginnt endlich mein Urlaub.', english: 'My vacation finally starts next week.' },
        { speaker: 'Tom', german: '___ freust du dich am meisten?', english: 'What are you looking forward to the most?' },
      ],
      options: [
        { id: 'a', text: 'Worauf' },
        { id: 'b', text: 'Worüber' },
        { id: 'c', text: 'Wovon' },
        { id: 'd', text: 'Woran' },
      ],
      correctOptionId: 'a',
      explanation: 'The vacation has not started yet, so sich freuen auf is the right verb, and its fused thing-question form is worauf.',
    },
    {
      id: 'ch58-ex-16',
      chapterNumber: 58,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sich interessieren für'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Ich interessiere mich sehr ___ Fremdsprachen.',
      acceptedAnswers: ['für'],
      answerMode: 'caseInsensitive',
      placeholder: 'für',
      maxLength: 10,
      explanation: 'sich interessieren is fixed with für + Akkusativ.',
    },
    {
      id: 'ch58-ex-17',
      chapterNumber: 58,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['warten auf'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Wir warten schon eine Stunde ___ den Zug.',
      acceptedAnswers: ['auf'],
      answerMode: 'caseInsensitive',
      placeholder: 'auf',
      maxLength: 10,
      explanation: 'warten is fixed with auf + Akkusativ.',
    },
    {
      id: 'ch58-ex-18',
      chapterNumber: 58,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sich freuen auf', 'future-event'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Ich freue mich schon ___ das Konzert nächste Woche.',
      acceptedAnswers: ['auf'],
      answerMode: 'caseInsensitive',
      placeholder: 'auf',
      maxLength: 10,
      explanation: 'The concert has not happened yet, so sich freuen auf is used.',
    },
    {
      id: 'ch58-ex-19',
      chapterNumber: 58,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sich freuen über', 'completed-event'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Er freut sich sehr ___ die gute Nachricht, die er gerade bekommen hat.',
      acceptedAnswers: ['über'],
      answerMode: 'caseInsensitive',
      placeholder: 'über',
      maxLength: 10,
      explanation: 'The news has already arrived, so sich freuen über is used, not the forward-looking auf.',
    },
    {
      id: 'ch58-ex-20',
      chapterNumber: 58,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['denken an'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Denkst du manchmal ___ deine alte Schule?',
      acceptedAnswers: ['an'],
      answerMode: 'caseInsensitive',
      placeholder: 'an',
      maxLength: 10,
      explanation: 'denken is fixed with an + Akkusativ.',
    },
    {
      id: 'ch58-ex-21',
      chapterNumber: 58,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sich erinnern an'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Ich erinnere mich gut ___ diesen Tag.',
      acceptedAnswers: ['an'],
      answerMode: 'caseInsensitive',
      placeholder: 'an',
      maxLength: 10,
      explanation: 'sich erinnern is fixed with an + Akkusativ.',
    },
    {
      id: 'ch58-ex-22',
      chapterNumber: 58,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['Angst haben vor'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Er hat große Angst ___ Prüfungen.',
      acceptedAnswers: ['vor'],
      answerMode: 'caseInsensitive',
      placeholder: 'vor',
      maxLength: 10,
      explanation: 'Angst haben is fixed with vor + Dativ.',
    },
    {
      id: 'ch58-ex-23',
      chapterNumber: 58,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['träumen von'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Sie träumt oft ___ einer Reise nach Japan.',
      acceptedAnswers: ['von'],
      answerMode: 'caseInsensitive',
      placeholder: 'von',
      maxLength: 10,
      explanation: 'träumen is fixed with von + Dativ.',
    },
    {
      id: 'ch58-ex-24',
      chapterNumber: 58,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['teilnehmen an'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Wir nehmen alle ___ dem Projekt teil.',
      acceptedAnswers: ['an'],
      answerMode: 'caseInsensitive',
      placeholder: 'an',
      maxLength: 10,
      explanation: 'teilnehmen is fixed with an + Dativ.',
    },
    {
      id: 'ch58-ex-25',
      chapterNumber: 58,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sich kümmern um'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Ich muss mich ___ meine kranke Oma kümmern.',
      acceptedAnswers: ['um'],
      answerMode: 'caseInsensitive',
      placeholder: 'um',
      maxLength: 10,
      explanation: 'sich kümmern is fixed with um + Akkusativ.',
    },
    {
      id: 'ch58-ex-26',
      chapterNumber: 58,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['gratulieren zu'],
      instruction: 'Fill in the missing preposition. Capitalisation is not checked.',
      prompt: 'Ich gratuliere dir herzlich ___ deinem Erfolg.',
      acceptedAnswers: ['zu'],
      answerMode: 'caseInsensitive',
      placeholder: 'zu',
      maxLength: 10,
      explanation: 'gratulieren is fixed with zu + Dativ.',
    },
    {
      id: 'ch58-ex-27',
      chapterNumber: 58,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'sich interessieren für', 'wrong-preposition'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich interessiere mich in Musik.',
      acceptedAnswers: ['Ich interessiere mich für Musik.'],
      answerMode: 'normalized',
      placeholder: 'Ich interessiere mich ...',
      maxLength: 60,
      explanation: 'sich interessieren is always fixed with für, never with in, which is a direct but incorrect translation of English.',
    },
    {
      id: 'ch58-ex-28',
      chapterNumber: 58,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'sich freuen auf', 'wrong-case'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich freue mich auf der Party.',
      acceptedAnswers: ['Ich freue mich auf die Party.'],
      answerMode: 'normalized',
      placeholder: 'Ich freue mich auf ...',
      maxLength: 60,
      explanation: 'sich freuen auf is fixed with the accusative, so it must be die Party, not the dative der Party.',
    },
    {
      id: 'ch58-ex-29',
      chapterNumber: 58,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-building', 'warten auf', 'accusative-article'],
      instruction: 'Write a complete sentence from the cues, using the correct case. Capitalisation is checked; no full stop is required.',
      prompt: 'wir – warten – auf – der Bus',
      acceptedAnswers: ['Wir warten auf den Bus.', 'Wir warten auf den Bus'],
      answerMode: 'normalized',
      placeholder: 'Wir warten auf ...',
      maxLength: 60,
      explanation: 'warten auf is fixed with the accusative, so der Bus becomes den Bus: Wir warten auf den Bus.',
    },
    {
      id: 'ch58-ex-30',
      chapterNumber: 58,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['wem', 'question-word', 'gratulieren zu', 'transfer'],
      instruction: 'Write the question that would produce exactly the underlined part of the statement as the answer. Capitalisation and the question mark are checked.',
      prompt: 'Sie gratuliert ihrer Kollegin zum neuen Job. (underlined: ihrer Kollegin)',
      acceptedAnswers: ['Wem gratuliert sie zum neuen Job?'],
      answerMode: 'normalized',
      placeholder: 'Wem ...',
      maxLength: 60,
      explanation: 'gratulieren zu is fixed with the dative, so the matching question about a person uses wem: Wem gratuliert sie zum neuen Job?',
    },
  ],
};
