import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter084: ChapterDefinition = {
  id: 'chapter-084',
  number: 84,
  slug: 'adjective-declension-with-and-without-an-article',
  title: 'Adjective Declension with and without an Article',
  germanTitle: 'Adjektivdeklination mit und ohne Artikel',
  level: 'B1',
  section: 'adjectives-2',
  objective:
    'Synthesize everything you know about attributive adjective endings — the weak endings after der-words and the mixed endings after ein-words from Chapters 40 and 41, plus the genitive case from Chapter 68 — into one complete system covering all four cases and a third pattern, strong declension, used with no article at all or after undeclined quantifiers such as viele and einige; apply a systematic three-step decision process to predict the correct ending in any noun phrase, including full declension tables, quantifier phrases, mixed-case paragraphs, and error correction.',
  prerequisites: [40, 41, 68],
  estimatedMinutes: 35,
  tags: [
    'adjective declension',
    'weak declension',
    'mixed declension',
    'strong declension',
    'der-words',
    'ein-words',
    'quantifiers',
    'nominative',
    'accusative',
    'dative',
    'genitive',
    'synthesis',
    'decision process',
  ],
  explanation: {
    introduction: [
      'You already know two pieces of the German adjective-ending puzzle. Chapters 40 and 41 taught you the endings that appear after der-words (der, die, das) and after ein-words (ein, kein, mein...) across the nominative, accusative, and dative. Chapter 68 added a first look at the genitive. This chapter puts all of those pieces together and adds the one piece that has been missing: what happens when there is no article at all, or only an undeclined quantifier such as viele or einige.',
      'German attributive adjectives actually follow just three declension patterns, not a long list of separate rules to memorize case by case. Weak declension applies after der-words, which already show case, gender, and number clearly, so the adjective itself only needs a minimal marker. Mixed declension applies after ein-words, which behave like der-words almost everywhere — except in three specific slots where ein itself carries no ending, forcing the adjective to step in and do the job. Strong declension applies whenever there is no article in the noun phrase at all, or only an undeclined quantifier; here the adjective alone must carry the full case, gender, and number information, so it mirrors the endings a der-word would have had.',
      'Once you see the three patterns as one connected system rather than three unrelated lists, a short, reliable decision process lets you produce the correct ending almost automatically, in any case, with or without an article. This chapter also introduces the one genuine exception in the whole system: in the masculine and neuter genitive singular of strong declension, the adjective takes -en rather than the -es you would otherwise expect.',
    ],
    rules: [
      {
        id: 'ch84-rule-01',
        heading: 'Three patterns, not three separate topics',
        paragraphs: [
          'Every attributive adjective ending in German belongs to one of three patterns: weak declension (after der-words), mixed declension (after ein-words), and strong declension (with no article, or after an undeclined quantifier). The pattern depends entirely on what — if anything — comes before the adjective, never on the adjective itself.',
          'The three patterns are not equally complex. Weak declension has only two possible endings in the whole system, -e and -en. Mixed declension reuses those same two endings almost everywhere, with three small exceptions. Strong declension has the richest set of endings, because the adjective is doing all the grammatical work that an article would otherwise do.',
        ],
      },
      {
        id: 'ch84-rule-02',
        heading: 'Weak declension: after der-words',
        paragraphs: [
          'Weak declension appears after der, die, das and the other der-words you already use as articles or determiners — dieser, jeder, welcher, mancher, solcher. Because the der-word itself already shows case, gender, and number unambiguously, the adjective only needs to add -e or -en, never anything more distinctive.',
          'The rule is simple: -e appears in the nominative singular of all three genders and in the feminine and neuter accusative singular; -en appears everywhere else — the masculine accusative singular, the entire dative singular, the entire genitive singular, and the entire plural. der gute Wein (nom.), den guten Wein (acc.), dem guten Wein (dat.), des guten Weines (gen.); die guten Weine in every plural case.',
        ],
      },
      {
        id: 'ch84-rule-03',
        heading: 'Mixed declension: after ein-words',
        paragraphs: [
          'Mixed declension appears after ein-words: ein, kein, and the possessives mein, dein, sein, ihr, unser, euer, Ihr. In most slots, mixed declension behaves exactly like weak declension, because ein-words show case and gender just as clearly as der-words do — einen, einem, einer, eines are every bit as informative as den, dem, der, des.',
          'The exception is precisely the three slots where the ein-word itself is endingless and therefore silent about gender: the masculine nominative singular (ein), the neuter nominative singular (ein), and the neuter accusative singular (ein, since neuter accusative always matches neuter nominative). In those three slots, and only those three, the adjective must step in and carry the marking the article failed to supply, taking the strong ending instead: ein guter Mann (not ein gut Mann), ein gutes Kind (nominative and accusative alike).',
          'Everywhere else — masculine accusative, all dative, all genitive, feminine nominative/accusative, and the whole plural after kein/mein and the like — mixed declension is identical to weak declension: einen guten Wein, einem guten Kind, einer guten Frau, meiner guten Freunde.',
        ],
      },
      {
        id: 'ch84-rule-04',
        heading: 'Strong declension: no article at all',
        paragraphs: [
          'When a noun phrase has no article of any kind — no der-word, no ein-word — the adjective alone must show case, gender, and number, because nothing else in the phrase does. Strong declension therefore mirrors the endings a der-word would have had in that exact slot: guter Wein (compare der Wein), gutes Bier (compare das Bier), gute Milch (compare die Milch), mit frischem Obst (compare mit dem Obst).',
          'This pattern is extremely common with mass nouns and plural nouns used in a general, non-specific sense — talking about coffee, bread, wine, or children in general rather than one particular cup, loaf, bottle, or group. Kalter Kaffee schmeckt nicht. Frisches Obst ist gesund.',
        ],
      },
      {
        id: 'ch84-rule-05',
        heading: 'Strong declension after undeclined quantifiers',
        paragraphs: [
          'A group of plural quantifiers — viele (many), wenige (few), einige (some), mehrere (several), ein paar (a couple of), and cardinal numbers such as zwei, drei, zehn — do not behave like articles at all. They do not agree with a specific der-word or ein-word pattern; instead they simply describe a quantity, and any adjective that follows them takes the strong ending, exactly as if no article were present: viele gute Bücher, mit einigen guten Freunden, trotz mehrerer guter Argumente, zwei neue Hemden.',
          'Notice that viele, wenige, einige, and mehrere themselves also inflect for case in parallel with the adjective that follows them (viele/vielen/vieler), while ein paar and cardinal numbers above eins never change form at all. Either way, the adjective after them keeps its strong ending.',
          'By contrast, alle (all), beide (both), and sämtliche (all/every single) decline like der-words themselves, so adjectives following them take the ordinary weak ending, not the strong one: alle guten Freunde, die beiden guten Freunde, sämtliche guten Bücher.',
        ],
      },
      {
        id: 'ch84-rule-06',
        heading: 'The genitive masculine/neuter singular exception',
        paragraphs: [
          'Strong declension mirrors the der-word endings almost perfectly — with one well-known exception. In the masculine and neuter genitive singular, you might expect the strong ending -es, to match des. In practice, German avoids this and uses -en instead: trotz guten Weines, not trotz gutes Weines; wegen starken Regens, not wegen starkes Regens.',
          'The reason is that the noun itself already carries the genitive -(e)s ending in this exact slot (Weines, Regens), so marking the adjective with -es as well would double the same information in an awkward way. The adjective quietly steps aside and takes -en, the same ending it would take almost everywhere else in weak and mixed declension.',
        ],
        notes: [
          'This is the single true exception in the whole three-pattern system: strong masculine/neuter genitive singular = -en, not the expected -es.',
        ],
      },
      {
        id: 'ch84-rule-07',
        heading: 'The systematic decision process',
        paragraphs: [
          'With three patterns and one exception, every adjective ending can be found with a short, repeatable process. First, ask: is there an article or determiner at all? If there is none — or only an undeclined quantifier like viele, wenige, einige, mehrere, ein paar, or a number — the pattern is strong.',
          'If there is an article, ask a second question: does it clearly show case and gender in this exact slot? A der-word (der, die, das, dieser, jeder, welcher...) always does, and so do alle, beide, and sämtliche — so the pattern is weak. An ein-word (ein, kein, mein...) usually does too, except in three specific slots — masculine nominative, neuter nominative, neuter accusative — where it is silent; there the pattern is mixed, with a strong ending on the adjective.',
          'Finally, if the phrase is genitive singular, masculine or neuter, and the pattern is strong, remember the one exception: use -en, not -es. Applying these three checks in order — article present? which type? genitive exception? — covers every noun phrase you will meet.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch84-table-01',
        title: 'Weak Declension — after der-words (der, die, das, dieser, jeder, welcher...)',
        columns: ['Gender / Number', 'Nominative', 'Accusative', 'Dative', 'Genitive'],
        columnCases: [null, 'nominative', 'accusative', 'dative', 'genitive'],
        rows: [
          ['Masculine', 'der gute Mann', 'den guten Mann', 'dem guten Mann', 'des guten Mannes'],
          ['Feminine', 'die gute Frau', 'die gute Frau', 'der guten Frau', 'der guten Frau'],
          ['Neuter', 'das gute Kind', 'das gute Kind', 'dem guten Kind', 'des guten Kindes'],
          ['Plural', 'die guten Kinder', 'die guten Kinder', 'den guten Kindern', 'der guten Kinder'],
        ],
        note: 'Weak declension has only two endings in the whole table: -e in the nominative singular (all genders) and the feminine/neuter accusative singular; -en everywhere else.',
      },
      {
        id: 'ch84-table-02',
        title: 'Mixed Declension — after ein-words (ein, kein, mein, dein, sein, ihr, unser, euer, Ihr)',
        columns: ['Gender / Number', 'Nominative', 'Accusative', 'Dative', 'Genitive'],
        columnCases: [null, 'nominative', 'accusative', 'dative', 'genitive'],
        rows: [
          ['Masculine', 'ein guter Mann', 'einen guten Mann', 'einem guten Mann', 'eines guten Mannes'],
          ['Feminine', 'eine gute Frau', 'eine gute Frau', 'einer guten Frau', 'einer guten Frau'],
          ['Neuter', 'ein gutes Kind', 'ein gutes Kind', 'einem guten Kind', 'eines guten Kindes'],
          ['Plural (kein/mein...)', 'keine guten Kinder', 'keine guten Kinder', 'keinen guten Kindern', 'keiner guten Kinder'],
        ],
        note: 'Mixed declension matches weak declension everywhere except three slots where the ein-word itself carries no ending — masculine nominative, neuter nominative, neuter accusative — where the adjective borrows the strong ending instead: guter, gutes, gutes.',
      },
      {
        id: 'ch84-table-03',
        title: 'Strong Declension — no article, or after undeclined quantifiers (viele, wenige, einige, mehrere, ein paar, zwei...)',
        columns: ['Gender / Number', 'Nominative', 'Accusative', 'Dative', 'Genitive'],
        columnCases: [null, 'nominative', 'accusative', 'dative', 'genitive'],
        rows: [
          ['Masculine', 'guter Wein', 'guten Wein', 'gutem Wein', 'guten Weins'],
          ['Feminine', 'gute Milch', 'gute Milch', 'guter Milch', 'guter Milch'],
          ['Neuter', 'gutes Bier', 'gutes Bier', 'gutem Bier', 'guten Biers'],
          ['Plural', 'gute Kinder', 'gute Kinder', 'guten Kindern', 'guter Kinder'],
        ],
        note: 'Strong endings mirror the der-word endings (der/den/dem/des → -er/-en/-em/-en, and so on), with one exception: masculine and neuter genitive singular takes -en, not the expected -es, because the noun already shows the genitive ending (Weins, Biers).',
      },
      {
        id: 'ch84-table-04',
        title: 'Quick Reference: Choosing the Pattern',
        columns: ['Situation', 'Pattern', 'Example'],
        rows: [
          ['der-word before the noun (der, die, das, dieser, jeder, welcher...)', 'Weak', 'der gute Wein'],
          ['ein-word, in masc. nom. / neut. nom. / neut. acc.', 'Mixed — strong ending on the adjective', 'ein guter Wein'],
          ['ein-word, everywhere else', 'Mixed — weak ending on the adjective', 'einen guten Wein'],
          ['No article at all', 'Strong', 'guter Wein'],
          ['After viele, wenige, einige, mehrere, ein paar, numbers', 'Strong', 'viele gute Weine'],
          ['After alle, beide, sämtliche (these decline like der-words)', 'Weak', 'alle guten Weine'],
        ],
        note: 'alle, beide, and sämtliche are the one trap in this table: they look like quantifiers but grammatically behave like der-words, so the adjective after them stays weak.',
      },
    ],
    examples: [
      {
        german: 'Der gute Wein schmeckt hervorragend.',
        english: 'The good wine tastes excellent.',
        highlight: ['Der', 'gute'],
        explanation: 'Weak declension: der already shows masculine nominative, so the adjective needs only -e.',
      },
      {
        german: 'Das ist der Duft des guten Weines.',
        english: 'That is the aroma of the good wine.',
        highlight: ['des', 'guten'],
        explanation: 'Weak genitive: after des the adjective takes -en, as in every case except the nominative and feminine/neuter accusative singular.',
      },
      {
        german: 'Ein guter Wein muss nicht teuer sein.',
        english: 'A good wine does not have to be expensive.',
        highlight: ['Ein', 'guter'],
        explanation: 'Mixed declension: ein itself carries no masculine marking, so the adjective takes the strong ending -er.',
      },
      {
        german: 'Ich kaufe einen guten Wein.',
        english: 'I am buying a good wine.',
        highlight: ['einen', 'guten'],
        explanation: 'Mixed accusative: einen already marks masculine accusative clearly, so the adjective reverts to the ordinary weak ending -en.',
      },
      {
        german: 'Wir haben kein gutes Bier mehr.',
        english: 'We do not have any good beer left.',
        highlight: ['kein', 'gutes'],
        explanation: 'Neuter accusative matches neuter nominative in form, so kein is again silent about gender and the adjective takes the strong ending -es.',
      },
      {
        german: 'Guter Wein muss reifen.',
        english: 'Good wine has to age.',
        highlight: ['Guter'],
        explanation: 'Strong declension: with no article at all, the adjective alone mirrors the der-word ending, -er.',
      },
      {
        german: 'Ich trinke gern kalte Milch.',
        english: 'I like to drink cold milk.',
        highlight: ['kalte'],
        explanation: 'Strong accusative feminine: with no article, the adjective mirrors die, taking -e.',
      },
      {
        german: 'Er kam nach Hause mit frischem Obst.',
        english: 'He came home with fresh fruit.',
        highlight: ['frischem'],
        explanation: 'Strong dative neuter: with no article, the adjective mirrors dem, taking -em.',
      },
      {
        german: 'Trotz starken Regens gingen wir spazieren.',
        english: 'Despite heavy rain, we went for a walk.',
        highlight: ['starken', 'Regens'],
        explanation: 'The genitive-exception: masculine genitive singular strong adjectives take -en, not -es, because Regens already shows the genitive ending.',
      },
      {
        german: 'Viele gute Bücher stehen im Regal.',
        english: 'Many good books are on the shelf.',
        highlight: ['Viele', 'gute'],
        explanation: 'viele is an undeclined quantifier, not an article, so the following adjective takes the strong nominative plural ending -e.',
      },
      {
        german: 'Ich feiere meinen Geburtstag mit vielen guten Freunden.',
        english: 'I am celebrating my birthday with many good friends.',
        highlight: ['vielen', 'guten'],
        explanation: 'Strong dative plural: both viele and the adjective take -en, mirroring den.',
      },
      {
        german: 'Trotz vieler guter Argumente blieb er skeptisch.',
        english: 'Despite many good arguments, he remained skeptical.',
        highlight: ['vieler', 'guter'],
        explanation: 'Strong genitive plural: both the quantifier and the adjective take -er, mirroring der — this slot has no -en exception, only the singular does.',
      },
      {
        german: 'Ein paar frische Eier liegen im Korb.',
        english: 'A couple of fresh eggs are in the basket.',
        highlight: ['paar', 'frische'],
        explanation: 'ein paar never changes form, so the adjective alone shows the strong nominative plural ending -e.',
      },
      {
        german: 'Alle guten Freunde kamen zur Party.',
        english: 'All good friends came to the party.',
        highlight: ['Alle', 'guten'],
        explanation: 'alle behaves like a der-word, so the following adjective takes the weak plural ending -en, not the strong -e.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ein gut Mann steht vor der Tür.',
        correct: 'Ein guter Mann steht vor der Tür.',
        explanation: 'ein carries no masculine marking in the nominative, so the adjective must supply it itself with the strong ending -er.',
      },
      {
        incorrect: 'Der guter Mann kommt gleich.',
        correct: 'Der gute Mann kommt gleich.',
        explanation: 'After the definite article der, weak declension applies, and the nominative singular ending is the minimal -e, not the strong -er.',
      },
      {
        incorrect: 'Trotz gutes Weines blieben wir noch.',
        correct: 'Trotz guten Weines blieben wir noch.',
        explanation: 'The masculine/neuter genitive singular of strong declension takes -en, not the expected -es, because the noun already carries the genitive ending.',
      },
      {
        incorrect: 'Viele guten Bücher stehen im Regal.',
        correct: 'Viele gute Bücher stehen im Regal.',
        explanation: 'viele is not a der-word or ein-word — it is an undeclined quantifier that triggers strong endings, so the nominative plural ending here is -e, not -en.',
      },
      {
        incorrect: 'Ich kaufe einen guter Wein.',
        correct: 'Ich kaufe einen guten Wein.',
        explanation: 'einen already marks masculine accusative clearly, so mixed declension reverts to the ordinary weak ending -en, not the strong -er.',
      },
      {
        incorrect: 'Alle gute Freunde kamen zur Party.',
        correct: 'Alle guten Freunde kamen zur Party.',
        explanation: 'alle declines like a der-word, so the adjective that follows takes the weak ending -en, not the strong ending -e that would be used after an undeclined quantifier.',
      },
    ],
    remember: [
      'Three patterns, one system: weak (after der-words), mixed (after ein-words), strong (no article, or after undeclined quantifiers like viele, wenige, einige, mehrere, ein paar, numbers).',
      'Decision process: (1) Is there an article/determiner at all? No, or only an undeclined quantifier → strong. (2) If yes, does it clearly show case and gender in this exact slot? Der-word (and alle/beide/sämtliche) → weak. Ein-word in masc. nom. / neut. nom. / neut. acc. → mixed with a strong ending there; ein-word everywhere else → mixed with a weak ending. (3) Genitive singular, masculine or neuter, strong pattern → remember the exception: -en, not -es.',
      'Weak declension has only two endings total: -e (nominative singular, feminine/neuter accusative singular) and -en (everywhere else, including the entire plural).',
      'Strong declension mirrors the der-word endings almost perfectly, with one true exception: masculine/neuter genitive singular takes -en, not -es (trotz guten Weines, wegen starken Regens).',
      'alle, beide, and sämtliche decline like der-words and trigger weak endings; viele, wenige, einige, mehrere, ein paar, and cardinal numbers do not decline like articles and trigger strong endings.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 83,
    requiredCorrectTextInputs: 21,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch84-ex-01',
      chapterNumber: 84,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['weak-declension', 'der-word', 'nominative', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'der gut___ Wein (Nominativ)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'a',
      explanation: 'After the definite article der, weak declension needs only the minimal ending -e in the masculine nominative: der gute Wein.',
    },
    {
      id: 'ch84-ex-02',
      chapterNumber: 84,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['weak-declension', 'der-word', 'genitive', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Das ist der Duft des gut___ Weines. (Genitiv)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'b',
      explanation: 'Weak declension after des is -en in the genitive, as in every case except the nominative singular and the feminine/neuter accusative singular.',
    },
    {
      id: 'ch84-ex-03',
      chapterNumber: 84,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['mixed-declension', 'ein-word', 'nominative', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'ein gut___ Mann (Nominativ)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'c',
      explanation: 'ein itself carries no ending in the masculine nominative, so the adjective must show the case and gender itself: ein guter Mann.',
    },
    {
      id: 'ch84-ex-04',
      chapterNumber: 84,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['mixed-declension', 'ein-word', 'nominative', 'neuter'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'ein gut___ Kind (Nominativ)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'd',
      explanation: 'ein carries no ending in the neuter nominative either, so the adjective takes the strong ending -es: ein gutes Kind.',
    },
    {
      id: 'ch84-ex-05',
      chapterNumber: 84,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['mixed-declension', 'ein-word', 'accusative', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'einen gut___ Mann (Akkusativ)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'b',
      explanation: 'einen already marks masculine accusative clearly, so the adjective takes the ordinary weak ending -en, not the strong -er.',
    },
    {
      id: 'ch84-ex-06',
      chapterNumber: 84,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'no-article', 'nominative', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Gut___ Wein schmeckt hervorragend. (kein Artikel, Nominativ)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'c',
      explanation: 'With no article, strong declension mirrors der: guter Wein.',
    },
    {
      id: 'ch84-ex-07',
      chapterNumber: 84,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'no-article', 'dative', 'feminine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Ich koche gern mit frisch___ Milch. (kein Artikel, Dativ)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'em' },
      ],
      correctOptionId: 'c',
      explanation: 'With no article, strong dative feminine mirrors der: mit frischer Milch.',
    },
    {
      id: 'ch84-ex-08',
      chapterNumber: 84,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'genitive-exception', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Trotz stark___ Regens gingen wir spazieren. (kein Artikel, Genitiv)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'es' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'en' },
      ],
      correctOptionId: 'd',
      explanation: 'The masculine genitive singular of strong declension takes -en, not the expected -es, because Regens already shows the genitive ending.',
    },
    {
      id: 'ch84-ex-09',
      chapterNumber: 84,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'quantifier', 'nominative', 'plural'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Viele gut___ Bücher stehen im Regal. (Nominativ Plural)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'a',
      explanation: 'viele is an undeclined quantifier, not an article, so the adjective takes the strong nominative plural ending -e: viele gute Bücher.',
    },
    {
      id: 'ch84-ex-10',
      chapterNumber: 84,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'quantifier', 'dative', 'plural'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Ich feiere meinen Geburtstag mit vielen gut___ Freunden. (Dativ Plural)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'b',
      explanation: 'Strong dative plural mirrors den, so the ending is -en: mit vielen guten Freunden.',
    },
    {
      id: 'ch84-ex-11',
      chapterNumber: 84,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'alle', 'plural'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Alle gut___ Freunde kamen zur Party.',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'b',
      explanation: 'alle declines like a der-word, so the following adjective takes the weak plural ending -en, not the strong -e.',
    },
    {
      id: 'ch84-ex-12',
      chapterNumber: 84,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['decision-process', 'pattern-identification'],
      instruction: 'Identify which declension pattern applies.',
      prompt: 'Welches Deklinationsmuster gilt in: "gutes Wetter" (kein Artikel)?',
      options: [
        { id: 'a', text: 'Strong (no article)' },
        { id: 'b', text: 'Weak (after a der-word)' },
        { id: 'c', text: 'Mixed (after an ein-word)' },
        { id: 'd', text: 'None — adjectives never take endings here' },
      ],
      correctOptionId: 'a',
      explanation: 'With no article at all, the adjective must carry the full marking itself: strong declension.',
    },
    {
      id: 'ch84-ex-13',
      chapterNumber: 84,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['error-recognition', 'genitive-exception'],
      instruction: 'Choose the correctly formed sentence.',
      prompt: 'Welcher Satz ist korrekt?',
      options: [
        { id: 'a', text: 'Trotz guten Weines blieben wir noch.' },
        { id: 'b', text: 'Trotz gutes Weines blieben wir noch.' },
        { id: 'c', text: 'Trotz gute Weines blieben wir noch.' },
        { id: 'd', text: 'Trotz guter Weines blieben wir noch.' },
      ],
      correctOptionId: 'a',
      explanation: 'The masculine genitive singular exception in strong declension requires -en, not -es, -e, or -er: trotz guten Weines.',
    },
    {
      id: 'ch84-ex-14',
      chapterNumber: 84,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['mixed-declension', 'mixed-case-paragraph'],
      instruction: 'Choose the pair of endings that correctly completes both blanks.',
      prompt: 'Ich habe einen gut___ Wein gekauft. Er stammt aus einem klein___ Weingut.',
      options: [
        { id: 'a', text: 'guten ... kleinen' },
        { id: 'b', text: 'guter ... kleines' },
        { id: 'c', text: 'gute ... kleinen' },
        { id: 'd', text: 'guten ... kleines' },
      ],
      correctOptionId: 'a',
      explanation: 'einen (masc. accusative) and einem (neuter dative) both show case and gender clearly, so mixed declension gives the ordinary weak ending -en in both blanks.',
    },
    {
      id: 'ch84-ex-15',
      chapterNumber: 84,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'undeclined-quantifier', 'plural'],
      instruction: 'Choose the correct ending.',
      prompt: 'Ich habe ein paar frisch___ Eier gekauft. (Nominativ/Akkusativ Plural)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'a',
      explanation: 'ein paar never changes form, so the following adjective alone takes the strong plural ending -e: frische Eier.',
    },
    {
      id: 'ch84-ex-16',
      chapterNumber: 84,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'nominative', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'der gut___ Wein (Nominativ)',
      acceptedAnswers: ['e'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'Weak declension after der needs only -e in the masculine nominative.',
    },
    {
      id: 'ch84-ex-17',
      chapterNumber: 84,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'dative', 'feminine'],
      instruction: 'Write only the missing ending.',
      prompt: 'mit der gut___ Freundin (Dativ)',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'Weak declension in the dative is always -en, in every gender: der guten Freundin.',
    },
    {
      id: 'ch84-ex-18',
      chapterNumber: 84,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'nominative', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'ein gut___ Mann (Nominativ)',
      acceptedAnswers: ['er'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'ein is silent about gender in the masculine nominative, so the adjective takes the strong ending -er.',
    },
    {
      id: 'ch84-ex-19',
      chapterNumber: 84,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'accusative', 'neuter'],
      instruction: 'Write only the missing ending.',
      prompt: 'Wir haben kein gut___ Bier mehr. (Akkusativ)',
      acceptedAnswers: ['es'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'Neuter accusative matches neuter nominative in form, so kein is again silent and the adjective takes the strong ending -es.',
    },
    {
      id: 'ch84-ex-20',
      chapterNumber: 84,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'no-article', 'nominative', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Gut___ Wein muss reifen. (kein Artikel, Nominativ)',
      acceptedAnswers: ['er'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'With no article, strong declension mirrors der: guter Wein.',
    },
    {
      id: 'ch84-ex-21',
      chapterNumber: 84,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'genitive-exception', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'trotz stark___ Regens (kein Artikel, Genitiv)',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'The masculine genitive singular exception in strong declension is -en, not -es: starken Regens.',
    },
    {
      id: 'ch84-ex-22',
      chapterNumber: 84,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'quantifier', 'genitive', 'plural'],
      instruction: 'Write only the missing ending.',
      prompt: 'Trotz vieler gut___ Argumente blieb er skeptisch. (Genitiv Plural)',
      acceptedAnswers: ['er'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'Strong genitive plural mirrors der, so the ending is -er: vieler guter Argumente — this slot has no -en exception, only the masculine/neuter singular does.',
    },
    {
      id: 'ch84-ex-23',
      chapterNumber: 84,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['strong-declension', 'no-article', 'accusative', 'feminine'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Ich trinke gern ___ Milch. (kalt, kein Artikel, Akkusativ)',
      acceptedAnswers: ['kalte'],
      answerMode: 'caseInsensitive',
      placeholder: 'kalte',
      maxLength: 20,
      explanation: 'With no article, strong accusative feminine mirrors die, taking -e: kalte Milch.',
    },
    {
      id: 'ch84-ex-24',
      chapterNumber: 84,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['mixed-declension', 'ein-word', 'accusative', 'masculine'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Ich kaufe einen ___ Wein. (gut)',
      acceptedAnswers: ['guten'],
      answerMode: 'caseInsensitive',
      placeholder: 'guten',
      maxLength: 20,
      explanation: 'einen already marks masculine accusative, so mixed declension gives the ordinary weak ending -en: einen guten Wein.',
    },
    {
      id: 'ch84-ex-25',
      chapterNumber: 84,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['strong-declension', 'quantifier', 'nominative', 'plural'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Viele ___ Bücher stehen im Regal. (gut)',
      acceptedAnswers: ['gute'],
      answerMode: 'caseInsensitive',
      placeholder: 'gute',
      maxLength: 20,
      explanation: 'viele triggers strong declension, so the nominative plural ending is -e: viele gute Bücher.',
    },
    {
      id: 'ch84-ex-26',
      chapterNumber: 84,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['strong-declension', 'quantifier', 'dative', 'plural'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Ich feiere mit vielen ___ Freunden. (gut)',
      acceptedAnswers: ['guten'],
      answerMode: 'caseInsensitive',
      placeholder: 'guten',
      maxLength: 20,
      explanation: 'Strong dative plural mirrors den, so the ending is -en: mit vielen guten Freunden.',
    },
    {
      id: 'ch84-ex-27',
      chapterNumber: 84,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['mixed-declension', 'error-correction', 'nominative', 'masculine'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ein gut Mann steht vor der Tür.',
      acceptedAnswers: ['Ein guter Mann steht vor der Tür.'],
      answerMode: 'normalized',
      placeholder: 'Ein guter Mann ...',
      maxLength: 60,
      explanation: 'ein carries no masculine marking in the nominative, so the adjective needs the strong ending -er: Ein guter Mann.',
    },
    {
      id: 'ch84-ex-28',
      chapterNumber: 84,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'error-correction', 'genitive-exception'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Trotz gutes Weines blieben wir noch.',
      acceptedAnswers: ['Trotz guten Weines blieben wir noch.'],
      answerMode: 'normalized',
      placeholder: 'Trotz guten Weines ...',
      maxLength: 60,
      explanation: 'The masculine genitive singular exception is -en, not -es: Trotz guten Weines.',
    },
    {
      id: 'ch84-ex-29',
      chapterNumber: 84,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'error-correction', 'quantifier', 'plural'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Viele guten Bücher stehen im Regal.',
      acceptedAnswers: ['Viele gute Bücher stehen im Regal.'],
      answerMode: 'normalized',
      placeholder: 'Viele gute Bücher ...',
      maxLength: 60,
      explanation: 'viele is an undeclined quantifier that triggers strong declension, so the nominative plural ending is -e, not -en.',
    },
    {
      id: 'ch84-ex-30',
      chapterNumber: 84,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['weak-declension', 'case-transformation', 'genitive', 'masculine'],
      instruction: 'Change the phrase from the nominative to the genitive, as in the model. Capitalisation is checked; no full stop is required.',
      prompt: 'Nominativ: der gute Wein. Genitiv: der Duft ___.',
      acceptedAnswers: ['des guten Weines', 'des guten Weins'],
      answerMode: 'normalized',
      placeholder: 'des guten Weines',
      maxLength: 30,
      explanation: 'Weak declension gives the genitive adjective ending -en; the noun itself adds -es or -s: des guten Weines / des guten Weins.',
    },
    {
      id: 'ch84-ex-31',
      chapterNumber: 84,
      order: 31,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'nominative', 'feminine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'diese gut___ Idee (Nominativ, feminin)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'a',
      explanation: 'diese is a der-word, and weak declension in the feminine nominative singular is -e: diese gute Idee.',
    },
    {
      id: 'ch84-ex-32',
      chapterNumber: 84,
      order: 32,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['decision-process', 'pattern-identification', 'mixed-declension'],
      instruction: 'Identify which declension pattern applies.',
      prompt: 'Welches Deklinationsmuster gilt in: "mit meiner klugen Schwester"?',
      options: [
        { id: 'a', text: 'Strong (no article)' },
        { id: 'b', text: 'Weak (after a der-word)' },
        { id: 'c', text: 'Mixed (after an ein-word)' },
        { id: 'd', text: 'None — adjectives never take endings here' },
      ],
      correctOptionId: 'c',
      explanation: 'meiner is a possessive ein-word, so mixed declension applies — here it happens to look identical to weak, since the ein-word already shows dative feminine clearly.',
    },
    {
      id: 'ch84-ex-33',
      chapterNumber: 84,
      order: 33,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['decision-process', 'pattern-identification', 'strong-declension', 'quantifier'],
      instruction: 'Identify which declension pattern applies.',
      prompt: 'Welches Deklinationsmuster gilt in: "nach zwei langen Reisen"?',
      options: [
        { id: 'a', text: 'Strong (no article)' },
        { id: 'b', text: 'Weak (after a der-word)' },
        { id: 'c', text: 'Mixed (after an ein-word)' },
        { id: 'd', text: 'None — adjectives never take endings here' },
      ],
      correctOptionId: 'a',
      explanation: 'zwei is a cardinal number and never inflects, so the adjective after it takes the strong ending, exactly as with no article: zwei langen Reisen mirrors den langen Reisen.',
    },
    {
      id: 'ch84-ex-34',
      chapterNumber: 84,
      order: 34,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['decision-process', 'pattern-identification', 'weak-declension', 'saemtliche'],
      instruction: 'Identify which declension pattern applies.',
      prompt: 'Welches Deklinationsmuster gilt in: "sämtliche neuen Regeln"?',
      options: [
        { id: 'a', text: 'Strong (no article)' },
        { id: 'b', text: 'Weak (after a der-word)' },
        { id: 'c', text: 'Mixed (after an ein-word)' },
        { id: 'd', text: 'None — adjectives never take endings here' },
      ],
      correctOptionId: 'b',
      explanation: 'sämtliche declines like a der-word, so the following adjective takes the weak ending, here plural -en: sämtliche neuen Regeln.',
    },
    {
      id: 'ch84-ex-35',
      chapterNumber: 84,
      order: 35,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'genitive', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'eines gut___ Tages (Genitiv, Maskulin, nach einem Ein-Wort)',
      options: [
        { id: 'a', text: 'e' },
        { id: 'b', text: 'en' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'b',
      explanation: 'eines already marks masculine genitive clearly, so mixed declension gives the ordinary weak ending -en — there is no exception here, unlike in strong declension: eines guten Tages.',
    },
    {
      id: 'ch84-ex-36',
      chapterNumber: 84,
      order: 36,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['mixed-declension', 'ein-word', 'dative', 'feminine'],
      instruction: 'Choose the correctly formed sentence.',
      prompt: 'Welcher Satz ist korrekt?',
      options: [
        { id: 'a', text: 'mit einer netten Freundin' },
        { id: 'b', text: 'mit einer nette Freundin' },
        { id: 'c', text: 'mit einer netter Freundin' },
        { id: 'd', text: 'mit einer nettes Freundin' },
      ],
      correctOptionId: 'a',
      explanation: 'einer already shows feminine dative clearly, so mixed declension gives the ordinary weak ending -en: mit einer netten Freundin.',
    },
    {
      id: 'ch84-ex-37',
      chapterNumber: 84,
      order: 37,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['quantifier', 'decision-process', 'weak-declension', 'strong-declension'],
      instruction: 'Choose the correct group of words.',
      prompt: 'Welche Wörter deklinieren wie Der-Wörter und lösen daher schwache Adjektivendungen aus?',
      options: [
        { id: 'a', text: 'alle, beide, sämtliche' },
        { id: 'b', text: 'viele, einige, mehrere' },
        { id: 'c', text: 'ein paar, zwei, drei' },
        { id: 'd', text: 'kein, mein, dein' },
      ],
      correctOptionId: 'a',
      explanation: 'alle, beide, and sämtliche decline like der-words, so adjectives after them stay weak; viele, einige, mehrere, ein paar, and cardinal numbers trigger strong endings instead.',
    },
    {
      id: 'ch84-ex-38',
      chapterNumber: 84,
      order: 38,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'genitive-exception', 'masculine'],
      instruction: 'Choose the correct form.',
      prompt: 'Welche Form ist im Genitiv Singular (maskulin, kein Artikel) korrekt?',
      options: [
        { id: 'a', text: 'starkes Regens' },
        { id: 'b', text: 'starker Regens' },
        { id: 'c', text: 'starken Regens' },
        { id: 'd', text: 'starke Regens' },
      ],
      correctOptionId: 'c',
      explanation: 'The masculine genitive singular exception in strong declension takes -en, not the expected -es: starken Regens.',
    },
    {
      id: 'ch84-ex-39',
      chapterNumber: 84,
      order: 39,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'nominative', 'feminine'],
      instruction: 'Write only the missing ending.',
      prompt: 'diese gut___ Idee (Nominativ, feminin)',
      acceptedAnswers: ['e'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'diese is a der-word; weak declension in the feminine nominative is -e: diese gute Idee.',
    },
    {
      id: 'ch84-ex-40',
      chapterNumber: 84,
      order: 40,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'genitive', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'eines gut___ Tages (Genitiv, Maskulin)',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / en / er / es',
      maxLength: 5,
      explanation: 'eines already marks masculine genitive, so mixed declension gives the ordinary weak ending -en: eines guten Tages.',
    },
    {
      id: 'ch84-ex-41',
      chapterNumber: 84,
      order: 41,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['strong-declension', 'no-article', 'accusative', 'neuter'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Ich esse gern ___ Brot. (frisch, kein Artikel, Akkusativ)',
      acceptedAnswers: ['frisches'],
      answerMode: 'caseInsensitive',
      placeholder: 'frisches',
      maxLength: 20,
      explanation: 'With no article, strong accusative neuter mirrors das, taking -es: frisches Brot.',
    },
    {
      id: 'ch84-ex-42',
      chapterNumber: 84,
      order: 42,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['strong-declension', 'no-article', 'dative', 'feminine'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Er spricht mit ___ Stimme. (laut, kein Artikel, Dativ)',
      acceptedAnswers: ['lauter'],
      answerMode: 'caseInsensitive',
      placeholder: 'lauter',
      maxLength: 20,
      explanation: 'With no article, strong dative feminine mirrors der, taking -er: mit lauter Stimme.',
    },
    {
      id: 'ch84-ex-43',
      chapterNumber: 84,
      order: 43,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'error-correction', 'dative', 'neuter'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Mit frisches Obst wird man gesund.',
      acceptedAnswers: ['Mit frischem Obst wird man gesund.'],
      answerMode: 'normalized',
      placeholder: 'Mit frischem Obst ...',
      maxLength: 60,
      explanation: 'With no article, strong dative neuter mirrors dem, taking -em, not -es: Mit frischem Obst.',
    },
    {
      id: 'ch84-ex-44',
      chapterNumber: 84,
      order: 44,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['mixed-declension', 'case-transformation', 'genitive', 'masculine'],
      instruction: 'Change the phrase from the nominative to the genitive, as in the model. Capitalisation is checked; no full stop is required.',
      prompt: 'Nominativ: ein guter Freund. Genitiv: der Rat ___.',
      acceptedAnswers: ['eines guten Freundes', 'eines guten Freunds'],
      answerMode: 'normalized',
      placeholder: 'eines guten Freundes',
      maxLength: 30,
      explanation: 'Mixed declension gives the genitive adjective ending -en; the noun itself adds -es or -s: eines guten Freundes / eines guten Freunds.',
    },
    {
      id: 'ch84-ex-45',
      chapterNumber: 84,
      order: 45,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'nominative', 'masculine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Der ___ Kaffee ist gut. (Nominativ, maskulin)',
      templateParts: ['Der ', ' Kaffee ist gut.'],
      slots: [{ id: 's1', correctWord: 'starke' }],
      wordBank: ['starke', 'starken', 'starker', 'starkes'],
      explanation: 'After der, weak declension needs -e in the masculine nominative: der starke Kaffee.',
    },
    {
      id: 'ch84-ex-46',
      chapterNumber: 84,
      order: 46,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'accusative', 'feminine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Ich mag die ___ Suppe. (Akkusativ, feminin)',
      templateParts: ['Ich mag die ', ' Suppe.'],
      slots: [{ id: 's1', correctWord: 'heiße' }],
      wordBank: ['heiße', 'heißen', 'heißer', 'heißes'],
      explanation: 'Feminine accusative after die is weak -e: die heiße Suppe.',
    },
    {
      id: 'ch84-ex-47',
      chapterNumber: 84,
      order: 47,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'dative', 'neuter'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Wir spielen mit dem ___ Kind. (Dativ, neutral)',
      templateParts: ['Wir spielen mit dem ', ' Kind.'],
      slots: [{ id: 's1', correctWord: 'kleinen' }],
      wordBank: ['kleine', 'kleinen', 'kleiner', 'kleines'],
      explanation: 'Dative after dem is always weak -en, in every gender: dem kleinen Kind.',
    },
    {
      id: 'ch84-ex-48',
      chapterNumber: 84,
      order: 48,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'genitive', 'feminine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Das ist die Farbe der ___ Wand. (Genitiv, feminin)',
      templateParts: ['Das ist die Farbe der ', ' Wand.'],
      slots: [{ id: 's1', correctWord: 'gelben' }],
      wordBank: ['gelbe', 'gelben', 'gelber', 'gelbes'],
      explanation: 'Genitive after der (feminine) is weak -en: der gelben Wand.',
    },
    {
      id: 'ch84-ex-49',
      chapterNumber: 84,
      order: 49,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'nominative', 'masculine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Heute ist ein ___ Tag. (Nominativ, maskulin)',
      templateParts: ['Heute ist ein ', ' Tag.'],
      slots: [{ id: 's1', correctWord: 'schöner' }],
      wordBank: ['schöne', 'schönen', 'schöner', 'schönes'],
      explanation: 'ein carries no masculine marking, so mixed declension takes the strong ending -er: ein schöner Tag.',
    },
    {
      id: 'ch84-ex-50',
      chapterNumber: 84,
      order: 50,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'nominative', 'neuter'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Sie kauften ein ___ Haus. (Nominativ, neutral)',
      templateParts: ['Sie kauften ein ', ' Haus.'],
      slots: [{ id: 's1', correctWord: 'altes' }],
      wordBank: ['alte', 'alten', 'alter', 'altes'],
      explanation: 'ein carries no neuter marking either, so the adjective takes the strong ending -es: ein altes Haus.',
    },
    {
      id: 'ch84-ex-51',
      chapterNumber: 84,
      order: 51,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'accusative', 'neuter'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Wir kaufen ein ___ Auto. (Akkusativ, neutral)',
      templateParts: ['Wir kaufen ein ', ' Auto.'],
      slots: [{ id: 's1', correctWord: 'neues' }],
      wordBank: ['neue', 'neuen', 'neuer', 'neues'],
      explanation: 'Neuter accusative matches neuter nominative, so ein is again silent and the adjective takes -es: ein neues Auto.',
    },
    {
      id: 'ch84-ex-52',
      chapterNumber: 84,
      order: 52,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'accusative', 'masculine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Ich sehe einen ___ Mann. (Akkusativ, maskulin)',
      templateParts: ['Ich sehe einen ', ' Mann.'],
      slots: [{ id: 's1', correctWord: 'großen' }],
      wordBank: ['große', 'großen', 'großer', 'großes'],
      explanation: 'einen already shows masculine accusative, so mixed declension reverts to the weak ending -en: einen großen Mann.',
    },
    {
      id: 'ch84-ex-53',
      chapterNumber: 84,
      order: 53,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'dative', 'feminine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Sie spricht mit einer ___ Freundin. (Dativ, feminin)',
      templateParts: ['Sie spricht mit einer ', ' Freundin.'],
      slots: [{ id: 's1', correctWord: 'netten' }],
      wordBank: ['nette', 'netten', 'netter', 'nettes'],
      explanation: 'einer already shows feminine dative, so the adjective takes the weak ending -en: mit einer netten Freundin.',
    },
    {
      id: 'ch84-ex-54',
      chapterNumber: 84,
      order: 54,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word', 'genitive', 'neuter'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Das ist die Farbe eines ___ Autos. (Genitiv, neutral)',
      templateParts: ['Das ist die Farbe eines ', ' Autos.'],
      slots: [{ id: 's1', correctWord: 'roten' }],
      wordBank: ['rote', 'roten', 'roter', 'rotes'],
      explanation: 'eines already marks genitive, so mixed declension gives the ordinary weak ending -en — no exception here, unlike strong declension: eines roten Autos.',
    },
    {
      id: 'ch84-ex-55',
      chapterNumber: 84,
      order: 55,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'no-article', 'nominative', 'feminine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: '___ Milch schmeckt gut. (kein Artikel, Nominativ, feminin)',
      templateParts: ['', ' Milch schmeckt gut.'],
      slots: [{ id: 's1', correctWord: 'frische' }],
      wordBank: ['frische', 'frischen', 'frischer', 'frisches'],
      explanation: 'With no article, strong nominative feminine mirrors die, taking -e: Frische Milch.',
    },
    {
      id: 'ch84-ex-56',
      chapterNumber: 84,
      order: 56,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'no-article', 'accusative', 'neuter'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Ich trinke gern ___ Wasser. (kein Artikel, Akkusativ)',
      templateParts: ['Ich trinke gern ', ' Wasser.'],
      slots: [{ id: 's1', correctWord: 'kaltes' }],
      wordBank: ['kalte', 'kalten', 'kaltes', 'kalter'],
      explanation: 'With no article, strong accusative neuter mirrors das, taking -es: kaltes Wasser.',
    },
    {
      id: 'ch84-ex-57',
      chapterNumber: 84,
      order: 57,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'no-article', 'dative', 'masculine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Er kocht mit ___ Kaffee. (kein Artikel, Dativ)',
      templateParts: ['Er kocht mit ', ' Kaffee.'],
      slots: [{ id: 's1', correctWord: 'starkem' }],
      wordBank: ['starke', 'starken', 'starker', 'starkem'],
      explanation: 'With no article, strong dative masculine mirrors dem, taking -em: mit starkem Kaffee.',
    },
    {
      id: 'ch84-ex-58',
      chapterNumber: 84,
      order: 58,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'no-article', 'genitive', 'feminine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Der Geschmack ___ Suppe überzeugt. (kein Artikel, Genitiv)',
      templateParts: ['Der Geschmack ', ' Suppe überzeugt.'],
      slots: [{ id: 's1', correctWord: 'heißer' }],
      wordBank: ['heiße', 'heißen', 'heißer', 'heißes'],
      explanation: 'With no article, strong genitive feminine mirrors der, taking -er: der Geschmack heißer Suppe.',
    },
    {
      id: 'ch84-ex-59',
      chapterNumber: 84,
      order: 59,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'genitive-exception', 'masculine'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Trotz ___ Regens gingen wir spazieren. (kein Artikel, Genitiv)',
      templateParts: ['Trotz ', ' Regens gingen wir spazieren.'],
      slots: [{ id: 's1', correctWord: 'starken' }],
      wordBank: ['starke', 'starker', 'starkes', 'starken'],
      explanation: 'The masculine genitive singular exception in strong declension is -en, not -es: trotz starken Regens.',
    },
    {
      id: 'ch84-ex-60',
      chapterNumber: 84,
      order: 60,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'quantifier', 'nominative', 'plural'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Einige ___ Studenten kamen zur Prüfung. (Nominativ Plural)',
      templateParts: ['Einige ', ' Studenten kamen zur Prüfung.'],
      slots: [{ id: 's1', correctWord: 'kluge' }],
      wordBank: ['kluge', 'klugen', 'kluger', 'kluges'],
      explanation: 'einige is an undeclined quantifier, so the adjective takes the strong nominative plural ending -e: einige kluge Studenten.',
    },
    {
      id: 'ch84-ex-61',
      chapterNumber: 84,
      order: 61,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'dative', 'plural'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Sie liest mit diesen ___ Büchern. (Dativ Plural)',
      templateParts: ['Sie liest mit diesen ', ' Büchern.'],
      slots: [{ id: 's1', correctWord: 'spannenden' }],
      wordBank: ['spannende', 'spannenden', 'spannender', 'spannendes'],
      explanation: 'diese is a der-word; weak dative plural is always -en: mit diesen spannenden Büchern.',
    },
    {
      id: 'ch84-ex-62',
      chapterNumber: 84,
      order: 62,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'der-word', 'nominative', 'plural'],
      instruction: 'Drag the correctly inflected word into the gap.',
      prompt: 'Welche ___ Bücher gefallen dir? (Nominativ Plural)',
      templateParts: ['Welche ', ' Bücher gefallen dir?'],
      slots: [{ id: 's1', correctWord: 'spannenden' }],
      wordBank: ['spannende', 'spannenden', 'spannender', 'spannendes'],
      explanation: 'welche is a der-word; weak nominative plural is -en: welche spannenden Bücher.',
    },
    {
      id: 'ch84-ex-63',
      chapterNumber: 84,
      order: 63,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['decision-process', 'pattern-identification'],
      instruction: 'Match each phrase to the reason its declension pattern applies.',
      prompt: 'Ordne jeder Wendung das passende Deklinationsmuster zu.',
      pairs: [
        { id: 'p1', left: 'der gute Wein', right: 'Schwach – der zeigt bereits alles' },
        { id: 'p2', left: 'ein guter Wein', right: 'Gemischt – ein bleibt hier endungslos' },
        { id: 'p3', left: 'guter Wein', right: 'Stark – kein Artikel vorhanden' },
        { id: 'p4', left: 'viele gute Weine', right: 'Stark – viele dekliniert nicht wie ein Artikel' },
        { id: 'p5', left: 'alle guten Weine', right: 'Schwach – alle dekliniert wie ein Der-Wort' },
      ],
      explanation: 'Weak, mixed, and strong declension are chosen by what precedes the adjective: a der-word, an ein-word (with its three silent slots), or nothing/an undeclined quantifier.',
    },
    {
      id: 'ch84-ex-64',
      chapterNumber: 84,
      order: 64,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'case-gender-mapping'],
      instruction: 'Match each case/gender combination to its strong-declension ending.',
      prompt: 'Ordne jede starke Fallkombination der richtigen Endung zu.',
      pairs: [
        { id: 'p1', left: 'Stark, Maskulin Nominativ', right: '-er' },
        { id: 'p2', left: 'Stark, Feminin Nominativ', right: '-e' },
        { id: 'p3', left: 'Stark, Neutrum Nominativ', right: '-es' },
        { id: 'p4', left: 'Stark, Maskulin Dativ', right: '-em' },
        { id: 'p5', left: 'Stark, Plural Dativ', right: '-en' },
      ],
      explanation: 'Strong declension endings mirror the der-word endings almost exactly: -er, -e, -es, -em, -en depending on case, gender, and number.',
    },
    {
      id: 'ch84-ex-65',
      chapterNumber: 84,
      order: 65,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'ein-word'],
      instruction: 'Match each ein-word situation to the explanation of its ending.',
      prompt: 'Ordne jeder Ein-Wort-Situation die passende Erklärung zu.',
      pairs: [
        { id: 'p1', left: 'ein-Wort, Maskulin Nominativ', right: '-er (stark, da "ein" endungslos ist)' },
        { id: 'p2', left: 'ein-Wort, Neutrum Nominativ', right: '-es (stark, da "ein" endungslos ist)' },
        { id: 'p3', left: 'ein-Wort, Maskulin Akkusativ', right: '-en (schwach, da "einen" schon eindeutig ist)' },
        { id: 'p4', left: 'ein-Wort, Dativ (alle Genera)', right: '-en (schwach, da der Artikel eindeutig ist)' },
      ],
      explanation: 'Mixed declension only uses the strong ending in the three slots where the ein-word itself carries no ending: masculine nominative, neuter nominative, neuter accusative.',
    },
    {
      id: 'ch84-ex-66',
      chapterNumber: 84,
      order: 66,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['quantifiers', 'decision-process'],
      instruction: 'Match each group of words to the pattern it triggers.',
      prompt: 'Ordne jede Wortgruppe dem Muster zu, das sie auslöst.',
      pairs: [
        { id: 'p1', left: 'viele, wenige, einige, mehrere', right: 'Stark: unveränderliche Mengenwörter' },
        { id: 'p2', left: 'ein paar, zwei, drei ...', right: 'Stark: unveränderliche Zahlwörter' },
        { id: 'p3', left: 'alle, beide, sämtliche', right: 'Schwach: deklinieren wie ein Der-Wort' },
        { id: 'p4', left: 'kein Artikel im Satz', right: 'Stark: gar kein Artikel' },
      ],
      explanation: 'viele/wenige/einige/mehrere and numbers never behave like articles, so adjectives after them stay strong; alle/beide/sämtliche decline like der-words, so adjectives after them stay weak.',
    },
    {
      id: 'ch84-ex-67',
      chapterNumber: 84,
      order: 67,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'case-recognition', 'masculine'],
      instruction: 'Match each phrase to its case.',
      prompt: 'Ordne jede Wendung dem passenden Kasus zu.',
      pairs: [
        { id: 'p1', left: 'der gute Wein', right: 'Nominativ' },
        { id: 'p2', left: 'den guten Wein', right: 'Akkusativ' },
        { id: 'p3', left: 'dem guten Wein', right: 'Dativ' },
        { id: 'p4', left: 'des guten Weines', right: 'Genitiv' },
      ],
      explanation: 'These four phrases show weak declension across all four cases for a masculine noun after der.',
    },
    {
      id: 'ch84-ex-68',
      chapterNumber: 84,
      order: 68,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['weak-declension', 'case-recognition', 'plural'],
      instruction: 'Match each plural phrase to its case.',
      prompt: 'Ordne jede Pluralform dem passenden Kasus zu.',
      pairs: [
        { id: 'p1', left: 'die guten Frauen', right: 'Nominativ oder Akkusativ Plural' },
        { id: 'p2', left: 'den guten Frauen', right: 'Dativ Plural' },
        { id: 'p3', left: 'der guten Frauen', right: 'Genitiv Plural' },
      ],
      explanation: 'Weak plural declension keeps the ending -en in every case; only the noun and the der-word itself show which case is meant.',
    },
    {
      id: 'ch84-ex-69',
      chapterNumber: 84,
      order: 69,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['mixed-declension', 'case-recognition', 'masculine'],
      instruction: 'Match each phrase to its case.',
      prompt: 'Ordne jede Wendung dem passenden Kasus zu.',
      pairs: [
        { id: 'p1', left: 'ein guter Mann', right: 'Nominativ' },
        { id: 'p2', left: 'einen guten Mann', right: 'Akkusativ' },
        { id: 'p3', left: 'einem guten Mann', right: 'Dativ' },
        { id: 'p4', left: 'eines guten Mannes', right: 'Genitiv' },
      ],
      explanation: 'Mixed declension for masculine nouns is strong only in the nominative (guter); every other case reverts to the weak ending -en.',
    },
    {
      id: 'ch84-ex-70',
      chapterNumber: 84,
      order: 70,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['strong-declension', 'case-recognition', 'neuter'],
      instruction: 'Match each phrase to its case.',
      prompt: 'Ordne jede Wendung dem passenden Kasus zu.',
      pairs: [
        { id: 'p1', left: 'gutes Bier', right: 'Nominativ oder Akkusativ' },
        { id: 'p2', left: 'gutem Bier', right: 'Dativ' },
        { id: 'p3', left: 'guten Biers', right: 'Genitiv' },
      ],
      explanation: 'Strong neuter declension mirrors das/dem/des: -es in the nominative/accusative, -em in the dative, and -en (not the expected -es) in the genitive, because the noun already shows -s.',
    },
    {
      id: 'ch84-ex-71',
      chapterNumber: 84,
      order: 71,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['decision-process', 'pattern-identification'],
      instruction: 'Match each group of determiners/quantifiers to the pattern it triggers.',
      prompt: 'Ordne jede Wortgruppe dem Deklinationsmuster zu, das sie auslöst.',
      pairs: [
        { id: 'p1', left: 'der, die, das, dieser, jeder, welcher', right: 'Schwache Deklension' },
        { id: 'p2', left: 'ein, kein, mein, dein, sein', right: 'Gemischte Deklension' },
        { id: 'p3', left: 'kein Artikel vorhanden', right: 'Starke Deklension (kein Artikel)' },
        { id: 'p4', left: 'viele, einige, mehrere, zwei, drei', right: 'Starke Deklension (unveränderliche Mengenwörter)' },
        { id: 'p5', left: 'alle, beide, sämtliche', right: 'Schwache Deklension (wie Der-Wörter)' },
      ],
      explanation: 'Every determiner or quantifier maps onto one of the three patterns: der-words and alle/beide/sämtliche trigger weak endings; ein-words trigger mixed; nothing at all, or an undeclined quantifier, triggers strong.',
    },
    {
      id: 'ch84-ex-72',
      chapterNumber: 84,
      order: 72,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['gender-recognition', 'noun-gender'],
      instruction: 'Match each noun to its grammatical gender.',
      prompt: 'Ordne jedes Nomen seinem Genus zu.',
      pairs: [
        { id: 'p1', left: 'der Wein', right: 'Maskulin' },
        { id: 'p2', left: 'die Milch', right: 'Feminin' },
        { id: 'p3', left: 'das Bier', right: 'Neutrum' },
        { id: 'p4', left: 'die Kinder', right: 'Plural' },
      ],
      explanation: 'Knowing the gender and number of the noun is the first step to predicting the correct adjective ending in any of the three declension patterns.',
    },
    {
      id: 'ch84-ex-73',
      chapterNumber: 84,
      order: 73,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['weak-declension', 'error-correction', 'nominative', 'masculine'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Der', 'guter', 'Wein', 'schmeckt', 'hervorragend.'],
      errorTokenIndex: 1,
      correction: 'gute',
      explanation: 'After der, weak declension needs -e in the masculine nominative, not the strong -er: der gute Wein.',
    },
    {
      id: 'ch84-ex-74',
      chapterNumber: 84,
      order: 74,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['mixed-declension', 'error-correction', 'nominative', 'masculine'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Ein', 'gutes', 'Mann', 'steht', 'vor', 'der', 'Tür.'],
      errorTokenIndex: 1,
      correction: 'guter',
      explanation: 'ein carries no masculine marking in the nominative, so the adjective needs the strong ending -er, not -es: ein guter Mann.',
    },
    {
      id: 'ch84-ex-75',
      chapterNumber: 84,
      order: 75,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['mixed-declension', 'error-correction', 'accusative', 'masculine'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Einen', 'guter', 'Wein', 'kaufe', 'ich.'],
      errorTokenIndex: 1,
      correction: 'guten',
      explanation: 'einen already marks masculine accusative, so mixed declension needs the weak ending -en, not the strong -er: einen guten Wein.',
    },
    {
      id: 'ch84-ex-76',
      chapterNumber: 84,
      order: 76,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'error-correction', 'genitive-exception'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Trotz', 'gutes', 'Weines', 'blieben', 'wir', 'noch.'],
      errorTokenIndex: 1,
      correction: 'guten',
      explanation: 'The masculine genitive singular exception in strong declension takes -en, not -es: trotz guten Weines.',
    },
    {
      id: 'ch84-ex-77',
      chapterNumber: 84,
      order: 77,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'error-correction', 'quantifier', 'plural'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Viele', 'guten', 'Bücher', 'stehen', 'im', 'Regal.'],
      errorTokenIndex: 1,
      correction: 'gute',
      explanation: 'viele triggers strong declension, so the nominative plural ending is -e, not -en: viele gute Bücher.',
    },
    {
      id: 'ch84-ex-78',
      chapterNumber: 84,
      order: 78,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['weak-declension', 'error-correction', 'plural'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Alle', 'gute', 'Freunde', 'kamen', 'zur', 'Party.'],
      errorTokenIndex: 1,
      correction: 'guten',
      explanation: 'alle declines like a der-word, so the adjective takes the weak plural ending -en, not the strong -e: alle guten Freunde.',
    },
    {
      id: 'ch84-ex-79',
      chapterNumber: 84,
      order: 79,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'error-correction', 'accusative', 'feminine'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Ich', 'trinke', 'gern', 'kalter', 'Milch.'],
      errorTokenIndex: 3,
      correction: 'kalte',
      explanation: 'With no article, strong accusative feminine mirrors die, taking -e, not -er: kalte Milch.',
    },
    {
      id: 'ch84-ex-80',
      chapterNumber: 84,
      order: 80,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['strong-declension', 'error-correction', 'dative', 'neuter'],
      instruction: 'Find the token with the wrong adjective ending.',
      prompt: 'Finde den Fehler im Satz.',
      tokens: ['Er', 'kam', 'nach', 'Hause', 'mit', 'frisches', 'Obst.'],
      errorTokenIndex: 5,
      correction: 'frischem',
      explanation: 'With no article, strong dative neuter mirrors dem, taking -em, not -es: mit frischem Obst.',
    },
    {
      id: 'ch84-ex-81',
      chapterNumber: 84,
      order: 81,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['weak-declension', 'mixed-declension', 'sentence-formation'],
      instruction: 'Ordne die Wörter zu einem grammatisch korrekten Satz.',
      prompt: 'Bringe die Wörter in die richtige Reihenfolge.',
      segments: [
        { id: 's1', text: 'Der' },
        { id: 's2', text: 'alte' },
        { id: 's3', text: 'Mann' },
        { id: 's4', text: 'liest' },
        { id: 's5', text: 'ein' },
        { id: 's6', text: 'interessantes' },
        { id: 's7', text: 'Buch.' },
      ],
      explanation: 'Der alte Mann (schwach, Nominativ maskulin) liest ein interessantes Buch (gemischt, Akkusativ neutrum, stark, da ein endungslos ist).',
    },
    {
      id: 'ch84-ex-82',
      chapterNumber: 84,
      order: 82,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['strong-declension', 'no-article', 'sentence-formation'],
      instruction: 'Ordne die Wörter zu einem grammatisch korrekten Satz.',
      prompt: 'Bringe die Wörter in die richtige Reihenfolge.',
      segments: [
        { id: 's1', text: 'Ich' },
        { id: 's2', text: 'kaufe' },
        { id: 's3', text: 'frisches' },
        { id: 's4', text: 'Obst' },
        { id: 's5', text: 'und' },
        { id: 's6', text: 'kalte' },
        { id: 's7', text: 'Milch.' },
      ],
      explanation: 'Strong declension with no article: frisches Obst (Akkusativ neutrum, -es) und kalte Milch (Akkusativ feminin, -e).',
    },
    {
      id: 'ch84-ex-83',
      chapterNumber: 84,
      order: 83,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['strong-declension', 'weak-declension', 'quantifier', 'sentence-formation'],
      instruction: 'Ordne die Wörter zu einem grammatisch korrekten Satz.',
      prompt: 'Bringe die Wörter in die richtige Reihenfolge.',
      segments: [
        { id: 's1', text: 'Viele' },
        { id: 's2', text: 'kluge' },
        { id: 's3', text: 'Studenten' },
        { id: 's4', text: 'bestehen' },
        { id: 's5', text: 'die' },
        { id: 's6', text: 'schwere' },
        { id: 's7', text: 'Prüfung.' },
      ],
      explanation: 'Viele kluge Studenten (stark, Nominativ Plural nach einem unveränderlichen Mengenwort) bestehen die schwere Prüfung (schwach, Akkusativ feminin nach dem Der-Wort die).',
    },
  ],
};
