import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter079: ChapterDefinition = {
  id: 'chapter-079',
  number: 79,
  slug: 'purpose-clauses-with-um-zu-and-damit',
  title: 'Purpose Clauses with um ... zu and damit',
  germanTitle: 'Finalsätze mit um ... zu und damit',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Form purpose clauses (Finalsätze) with um ... zu + infinitive when the subject of both clauses is the same, and with damit + a full subordinate clause when the subjects differ; place zu correctly, including with separable and reflexive verbs; punctuate with a comma before um and before damit; and negate purpose clauses correctly with nicht.',
  prerequisites: [46, 73],
  estimatedMinutes: 30,
  tags: [
    'purpose-clauses',
    'finalsatz',
    'um-zu',
    'damit',
    'zu-infinitive',
    'subject-identity',
    'word-order',
    'comma-rules',
    'negation',
    'separable-verbs',
  ],
  explanation: {
    introduction: [
      'A purpose clause answers the question wozu? or zu welchem Zweck? (to what end? / for what purpose?) — it explains the goal behind an action, not its cause. English uses "in order to" or "so that" for this job; German has two competing tools that are not interchangeable: um ... zu + infinitive and damit + a full subordinate clause. Choosing correctly between them is not a matter of style — it depends on a single, checkable fact about the sentence: is the subject of the purpose clause the same person/thing as the subject of the main clause, or different?',
      'If the same person is doing both actions — Ich lerne Deutsch, um in Deutschland zu studieren (I learn German [in order] to study in Germany) — German drops the second subject entirely and uses um ... zu with a bare infinitive at the end. There is no way to name a subject inside an um ... zu phrase; it is simply understood to be identical to the main clause\'s subject. As soon as two different people or things are involved — Ich erkläre es langsam, damit du es verstehst (I explain it slowly so that you understand it) — um ... zu becomes ungrammatical, because it has no slot for a second subject. damit steps in instead, introducing an ordinary subordinate clause with its own subject and its own conjugated verb, built exactly like the weil/wenn/dass clauses from Chapter 46.',
      'This chapter assumes you already know the basic mechanics of zu-infinitives from Chapter 73 (verb + zu + infinitive) and subordinate-clause verb-final order from Chapter 46; here those two skills combine into one decision: same subject → um ... zu (infinitive at the end, zu directly before it); different subjects → damit (finite verb at the end, as in any subordinate clause). Both constructions always take a comma before the connector, and both can be negated to express a purpose of avoiding something.',
    ],
    rules: [
      {
        id: 'ch79-rule-01',
        heading: 'Purpose clauses answer wozu? — the goal behind an action',
        paragraphs: [
          'A purpose clause (Finalsatz) states the goal or intention behind the action of the main clause. It answers wozu? (to what end?) or zu welchem Zweck? (for what purpose?) — a different question from warum? (why?), which is answered by a causal weil-clause. Compare: Warum lernst du Deutsch? — Weil es mir Spaß macht. (cause) versus Wozu lernst du Deutsch? — Um in Deutschland zu studieren. (purpose/goal).',
          'German expresses this goal with one of two constructions, um ... zu + infinitive or damit + clause, and the choice between them is grammatical, not stylistic: it is determined entirely by whether the subject stays the same across both clauses.',
        ],
      },
      {
        id: 'ch79-rule-02',
        heading: 'um ... zu + infinitive: only when the subject is the same',
        paragraphs: [
          'When the person or thing carrying out the purpose is identical to the subject of the main clause, German uses um ... zu followed by an infinitive, with no subject stated inside the um-phrase at all. um opens the clause, any objects or adverbs follow, and zu + the infinitive close it at the very end: Sie lernt jeden Tag, um die Prüfung zu bestehen. (She studies every day [in order] to pass the exam.)',
          'Because um ... zu structurally has no room for its own subject, it is simply impossible to use it when a different subject is meant. Ich lerne Deutsch, um mein Bruder ... zu studieren is not a real sentence — there is no way to insert mein Bruder into an um ... zu phrase.',
        ],
      },
      {
        id: 'ch79-rule-03',
        heading: 'damit: required when the subjects differ',
        paragraphs: [
          'When the purpose is carried out by someone or something other than the main clause\'s subject, damit is required. damit is a subordinating conjunction, so it behaves exactly like weil, wenn, and dass: it introduces a full clause with its own subject and sends the finite (conjugated) verb to the very end. Ich erkläre es langsam, damit du es verstehst. (I explain it slowly so that you understand it.)',
          'damit is also grammatically fine when the subject happens to be the same, but in that case um ... zu is the shorter, more natural choice; damit becomes the only option once the subjects diverge.',
        ],
      },
      {
        id: 'ch79-rule-04',
        heading: 'Where zu goes — including separable and reflexive verbs',
        paragraphs: [
          'Inside um ... zu, the word zu always stands directly in front of the infinitive, and that infinitive is the very last word of the clause: um sich ein neues Auto zu kaufen, um die Prüfung zu bestehen. Everything else — objects, adverbs, the negation nicht — comes before zu.',
          'With separable verbs, zu is inserted between the prefix and the stem, and the result is written as one word at the very end of the clause: einkaufen becomes um einzukaufen, not um zu einkaufen or um ein zu kaufen. With reflexive verbs, the reflexive pronoun must match the subject of the main clause, since the um-clause has no subject of its own: Er spart Geld, um sich ein neues Auto zu kaufen (sich, because the subject is er).',
        ],
      },
      {
        id: 'ch79-rule-05',
        heading: 'A comma always precedes um and damit',
        paragraphs: [
          'Just like weil, wenn, and dass, a purpose clause is always separated from the main clause by a comma, whether it is introduced by um or by damit. The comma stands directly before the connector, regardless of how long either clause is.',
          'Ich stehe früh auf, um pünktlich zu sein. / Ich stehe früh auf, damit ich pünktlich bin. A damit-clause can also open the sentence, in which case the main clause\'s verb follows immediately after the comma, exactly as with a fronted weil- or wenn-clause: Damit du pünktlich ankommst, solltest du früh losfahren.',
        ],
      },
      {
        id: 'ch79-rule-06',
        heading: 'Negating the purpose: um nicht ... zu vs. damit ... nicht',
        paragraphs: [
          'To express a purpose of avoiding something ("so as not to ..."), nicht (or kein, nie, nichts) is placed before the element it negates, and zu still stands directly before the infinitive at the very end: Er nimmt den Regenschirm mit, um nicht nass zu werden. / Ich beeile mich, um den Bus nicht zu verpassen.',
          'In a damit-clause, nicht simply takes its normal position in a subordinate clause — before the final verb (or before a separable prefix that has joined the verb): Die Mutter kocht das Essen, damit die Kinder nicht hungrig sind. / Wir schließen die Tür, damit die Katze nicht rausgeht.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch79-table-01',
        title: 'um ... zu vs. damit at a glance',
        columns: ['Feature', 'um ... zu + infinitive', 'damit + clause'],
        rows: [
          [
            'Subject of the purpose',
            'Must be the same as the main clause',
            'May be the same, but is required when it differs',
          ],
          [
            'Own subject stated?',
            'No — no subject can appear after um',
            'Yes — the clause has its own subject',
          ],
          [
            'Verb form',
            'Bare infinitive, with zu directly before it, at the very end',
            'Finite (conjugated) verb at the very end, like weil/wenn/dass',
          ],
          [
            'Example',
            'Ich lerne, um die Prüfung zu bestehen.',
            'Ich helfe dir, damit du die Prüfung bestehst.',
          ],
        ],
        note: 'When the subjects match, um ... zu is the shorter and more natural choice; when they differ, um ... zu is ungrammatical and damit is the only option.',
      },
      {
        id: 'ch79-table-02',
        title: 'Negating the purpose',
        columns: ['Construction', 'Pattern', 'Example'],
        rows: [
          [
            'um ... zu',
            'nicht/kein/nichts stands before the word it negates; zu stays directly before the infinitive',
            'Er läuft schnell, um den Zug nicht zu verpassen.',
          ],
          [
            'damit',
            'nicht keeps its normal subordinate-clause position, before the final (or separable) verb',
            'Ich flüstere, damit die Kinder nicht aufwachen.',
          ],
        ],
      },
    ],
    examples: [
      {
        german: 'Ich lerne Deutsch, um in Deutschland zu studieren.',
        english: 'I am learning German in order to study in Germany.',
        highlight: ['um in Deutschland zu studieren'],
        explanation: 'Same subject (ich) in both parts, so um ... zu is used; zu studieren closes the clause.',
      },
      {
        german: 'Er spart Geld, um sich ein neues Auto zu kaufen.',
        english: 'He is saving money to buy himself a new car.',
        highlight: ['um sich ein neues Auto zu kaufen'],
        explanation: 'The reflexive pronoun sich matches the main clause\'s subject er, since the um-clause has no subject of its own.',
      },
      {
        german: 'Ich gehe in die Stadt, um einzukaufen.',
        english: 'I am going into town to shop.',
        highlight: ['um einzukaufen'],
        explanation: 'With the separable verb einkaufen, zu is inserted between the prefix and the stem: einzukaufen.',
      },
      {
        german: 'Er nimmt den Regenschirm mit, um nicht nass zu werden.',
        english: 'He takes the umbrella so as not to get wet.',
        highlight: ['um nicht nass zu werden'],
        explanation: 'nicht stands before the word it negates (nass); zu still stands right before the infinitive werden.',
      },
      {
        german: 'Ich beeile mich, um den Bus nicht zu verpassen.',
        english: 'I am hurrying so as not to miss the bus.',
        highlight: ['um den Bus nicht zu verpassen'],
        explanation: 'nicht comes before the whole action it negates (den Bus verpassen); zu still stands directly before verpassen.',
      },
      {
        german: 'Ich erkläre es langsam, damit du es verstehst.',
        english: 'I explain it slowly so that you understand it.',
        highlight: ['damit du es verstehst'],
        explanation: 'Subjects differ (ich vs. du), so damit is required; the finite verb verstehst goes to the end.',
      },
      {
        german: 'Der Lehrer spricht laut, damit alle Schüler ihn hören können.',
        english: 'The teacher speaks loudly so that all the students can hear him.',
        highlight: ['damit alle Schüler ihn hören können'],
        explanation: 'A modal verb (können) in a damit-clause still goes to the very end, after the infinitive hören.',
      },
      {
        german: 'Die Mutter kocht das Essen, damit die Kinder nicht hungrig sind.',
        english: 'The mother cooks the food so that the children are not hungry.',
        highlight: ['damit die Kinder nicht hungrig sind'],
        explanation: 'Negated damit-clause: nicht takes its normal position before the final verb sind.',
      },
      {
        german: 'Wir schließen die Tür, damit die Katze nicht rausgeht.',
        english: 'We close the door so that the cat does not go out.',
        highlight: ['damit die Katze nicht rausgeht'],
        explanation: 'The separable verb rausgehen joins into one word (rausgeht) at the end, with nicht right before it.',
      },
      {
        german: 'Ich gebe dir meine Nummer, damit du mich anrufen kannst.',
        english: 'I am giving you my number so that you can call me.',
        highlight: ['damit du mich anrufen kannst'],
        explanation: 'Different subjects (ich vs. du) force damit; kannst, the modal, sits at the very end.',
      },
      {
        german: 'Damit du pünktlich ankommst, solltest du früh losfahren.',
        english: 'So that you arrive on time, you should leave early.',
        highlight: ['solltest du'],
        explanation: 'When the damit-clause opens the sentence, the main clause\'s verb (solltest) follows immediately after the comma, just like a fronted weil- or wenn-clause.',
      },
      {
        german: 'Ich schreibe mir Notizen, um nichts zu vergessen.',
        english: 'I write myself notes so as not to forget anything.',
        highlight: ['um nichts zu vergessen'],
        explanation: 'nichts (nothing) replaces nicht + etwas as the negated object; zu vergessen still closes the clause.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich lerne Deutsch, um mein Bruder in Deutschland studiert.',
        correct: 'Ich lerne Deutsch, damit mein Bruder in Deutschland studiert.',
        explanation: 'The subjects differ (ich vs. mein Bruder), so um ... zu is ungrammatical here — it has no slot for a second subject. damit introduces a full clause with its own subject and finite verb.',
      },
      {
        incorrect: 'Ich erkläre es langsam, um du es verstehst.',
        correct: 'Ich erkläre es langsam, damit du es verstehst.',
        explanation: 'um ... zu never takes a stated subject or a conjugated verb; only damit can introduce a clause with its own subject (du) and finite verb (verstehst).',
      },
      {
        incorrect: 'Ich gehe in die Stadt, um kaufen ein.',
        correct: 'Ich gehe in die Stadt, um einzukaufen.',
        explanation: 'With separable verbs, zu is inserted between the prefix and the stem, forming one word (einzukaufen) at the end — the prefix cannot be left dangling at the end on its own.',
      },
      {
        incorrect: 'Er nimmt den Schirm mit, um zu nicht nass werden.',
        correct: 'Er nimmt den Schirm mit, um nicht nass zu werden.',
        explanation: 'nicht stands before the word it negates (nass); zu must stay directly in front of the infinitive at the very end of the clause.',
      },
      {
        incorrect: 'Ich lerne jeden Tag, damit die Prüfung zu bestehen.',
        correct: 'Ich lerne jeden Tag, um die Prüfung zu bestehen.',
        explanation: 'damit never combines with a zu-infinitive — it always takes a finite verb. When the subject is the same, um ... zu is the correct (and preferred) construction.',
      },
    ],
    remember: [
      'Same subject in both clauses → um ... zu + infinitive is possible and preferred.',
      'Different subjects → damit + a full clause (its own subject, finite verb) is required; um ... zu is ungrammatical there.',
      'um ... zu never states a subject; the infinitive with zu directly before it stands at the very end of the clause.',
      'damit behaves exactly like weil/wenn/dass: the conjugated verb moves to the end of the clause.',
      'A comma always precedes um and damit, and a fronted damit-clause triggers inversion in the main clause.',
      'Negate um ... zu with nicht/kein/nichts before the negated element (zu stays before the infinitive); negate damit-clauses with nicht in its normal pre-final-verb position.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 28,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch79-ex-01',
      chapterNumber: 79,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['um-zu', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I learn German in order to study in Germany." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich lerne Deutsch, um in Deutschland zu studieren.' },
        { id: 'b', text: 'Ich lerne Deutsch, um in Deutschland studieren zu.' },
        { id: 'c', text: 'Ich lerne Deutsch, um zu in Deutschland studieren.' },
        { id: 'd', text: 'Ich lerne Deutsch, um in Deutschland studieren.' },
      ],
      correctOptionId: 'a',
      explanation: 'zu stands directly before the infinitive, and the whole infinitive phrase closes the clause: um in Deutschland zu studieren.',
    },
    {
      id: 'ch79-ex-02',
      chapterNumber: 79,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['damit', 'verb-final', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I explain it slowly so that you understand it." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich erkläre es langsam, damit du verstehst es.' },
        { id: 'b', text: 'Ich erkläre es langsam, damit du es verstehst.' },
        { id: 'c', text: 'Ich erkläre es langsam, damit verstehst du es.' },
        { id: 'd', text: 'Ich erkläre es langsam, damit es du verstehst.' },
      ],
      correctOptionId: 'b',
      explanation: 'damit introduces a subordinate clause like weil/wenn/dass: the finite verb (verstehst) goes to the very end.',
    },
    {
      id: 'ch79-ex-03',
      chapterNumber: 79,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['um-zu', 'same-subject', 'connector-choice'],
      instruction: 'Choose the connector that fits, given the subject relationship.',
      prompt: 'Er joggt jeden Morgen, ___ fit zu bleiben. (same subject: er / er)',
      options: [
        { id: 'a', text: 'um' },
        { id: 'b', text: 'damit' },
        { id: 'c', text: 'weil' },
        { id: 'd', text: 'wenn' },
      ],
      correctOptionId: 'a',
      explanation: 'The subject of bleiben is the same as the main clause (er), so um ... zu is possible and preferred.',
    },
    {
      id: 'ch79-ex-04',
      chapterNumber: 79,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['damit', 'different-subject', 'connector-choice'],
      instruction: 'Choose the connector that fits, given the subject relationship.',
      prompt: 'Die Lehrerin spricht langsam, ___ die Schüler alles verstehen. (different subjects: die Lehrerin / die Schüler)',
      options: [
        { id: 'a', text: 'um' },
        { id: 'b', text: 'damit' },
        { id: 'c', text: 'weil' },
        { id: 'd', text: 'dass' },
      ],
      correctOptionId: 'b',
      explanation: 'Subjects differ (die Lehrerin vs. die Schüler), so um ... zu is impossible; damit introduces the clause with its own subject.',
    },
    {
      id: 'ch79-ex-05',
      chapterNumber: 79,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['um-zu', 'same-subject', 'word-order'],
      instruction: 'Same subject in both parts. Choose the grammatically correct sentence.',
      prompt: 'Ich spare Geld, ... (Ziel: ich kaufe mir ein neues Fahrrad).',
      options: [
        { id: 'a', text: 'Ich spare Geld, um mir ein neues Fahrrad zu kaufen.' },
        { id: 'b', text: 'Ich spare Geld, um ich mir ein neues Fahrrad kaufe.' },
        { id: 'c', text: 'Ich spare Geld, damit mir ein neues Fahrrad zu kaufen.' },
        { id: 'd', text: 'Ich spare Geld, um mir ein neues Fahrrad kaufen zu.' },
      ],
      correctOptionId: 'a',
      explanation: 'um ... zu never has its own subject (b is impossible) and damit never takes a zu-infinitive (c is impossible); zu must stand directly before kaufen (d is wrong).',
    },
    {
      id: 'ch79-ex-06',
      chapterNumber: 79,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['damit', 'different-subject', 'word-order'],
      instruction: 'Different subjects. Choose the grammatically correct sentence.',
      prompt: 'Die Eltern arbeiten viel, ... (Ziel: die Kinder haben ein gutes Leben).',
      options: [
        { id: 'a', text: 'Die Eltern arbeiten viel, um die Kinder ein gutes Leben haben.' },
        { id: 'b', text: 'Die Eltern arbeiten viel, damit die Kinder ein gutes Leben haben.' },
        { id: 'c', text: 'Die Eltern arbeiten viel, um den Kindern ein gutes Leben zu haben.' },
        { id: 'd', text: 'Die Eltern arbeiten viel, damit die Kinder ein gutes Leben zu haben.' },
      ],
      correctOptionId: 'b',
      explanation: 'Subjects differ (die Eltern vs. die Kinder), so um ... zu is impossible (a, c); damit introduces a full clause with its own subject and finite verb haben (d wrongly uses a zu-infinitive).',
    },
    {
      id: 'ch79-ex-07',
      chapterNumber: 79,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['um-zu', 'comma'],
      instruction: 'Choose the correctly punctuated sentence.',
      prompt: '"He saves money in order to buy a new car." Which sentence has correct punctuation?',
      options: [
        { id: 'a', text: 'Er spart Geld um sich ein neues Auto zu kaufen.' },
        { id: 'b', text: 'Er spart Geld, um sich ein neues Auto zu kaufen.' },
        { id: 'c', text: 'Er spart Geld um, sich ein neues Auto zu kaufen.' },
        { id: 'd', text: 'Er spart, Geld um sich ein neues Auto zu kaufen.' },
      ],
      correctOptionId: 'b',
      explanation: 'A comma always stands directly before um, separating the main clause from the purpose clause.',
    },
    {
      id: 'ch79-ex-08',
      chapterNumber: 79,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['um-zu', 'negation'],
      instruction: 'Choose the sentence with correctly placed negation.',
      prompt: '"He takes the umbrella so as not to get wet." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Er nimmt den Schirm mit, um nicht nass zu werden.' },
        { id: 'b', text: 'Er nimmt den Schirm mit, um nass nicht zu werden.' },
        { id: 'c', text: 'Er nimmt den Schirm mit, um zu nicht nass werden.' },
        { id: 'd', text: 'Er nimmt den Schirm mit, um nicht zu nass werden.' },
      ],
      correctOptionId: 'a',
      explanation: 'nicht stands directly before the word it negates (nass); zu stays immediately before the infinitive at the very end: um nicht nass zu werden.',
    },
    {
      id: 'ch79-ex-09',
      chapterNumber: 79,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['damit', 'negation'],
      instruction: 'Choose the sentence with correctly placed negation.',
      prompt: '"The mother cooks the food so that the children are not hungry." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Die Mutter kocht das Essen, damit die Kinder nicht hungrig sind.' },
        { id: 'b', text: 'Die Mutter kocht das Essen, damit die Kinder sind nicht hungrig.' },
        { id: 'c', text: 'Die Mutter kocht das Essen, damit nicht die Kinder hungrig sind.' },
        { id: 'd', text: 'Die Mutter kocht das Essen, damit die Kinder hungrig nicht sind.' },
      ],
      correctOptionId: 'a',
      explanation: 'In a damit-clause, nicht takes its normal position directly before the final verb: ..., damit die Kinder nicht hungrig sind.',
    },
    {
      id: 'ch79-ex-10',
      chapterNumber: 79,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['um-zu', 'separable-verb'],
      instruction: 'Choose the sentence with correct zu-placement.',
      prompt: '"I go into town (in order) to shop." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich gehe in die Stadt, um zu einkaufen.' },
        { id: 'b', text: 'Ich gehe in die Stadt, um einzukaufen.' },
        { id: 'c', text: 'Ich gehe in die Stadt, um ein zu kaufen.' },
        { id: 'd', text: 'Ich gehe in die Stadt, um einkaufen zu.' },
      ],
      correctOptionId: 'b',
      explanation: 'With separable verbs, zu is inserted between the prefix and the stem, forming one word at the end: einzukaufen.',
    },
    {
      id: 'ch79-ex-11',
      chapterNumber: 79,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['um-zu', 'reflexive-verb'],
      instruction: 'Choose the sentence with the correct reflexive pronoun and word order.',
      prompt: '"He saves money to buy himself a new car." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Er spart Geld, um sich ein neues Auto zu kaufen.' },
        { id: 'b', text: 'Er spart Geld, um ihm ein neues Auto zu kaufen.' },
        { id: 'c', text: 'Er spart Geld, um sich ein neues Auto kaufen zu.' },
        { id: 'd', text: 'Er spart Geld, um zu sich ein neues Auto kaufen.' },
      ],
      correctOptionId: 'a',
      explanation: 'The reflexive pronoun matches the subject of the main clause (er → sich); zu + the infinitive stand at the very end.',
    },
    {
      id: 'ch79-ex-12',
      chapterNumber: 79,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['different-subject', 'error-correction'],
      instruction: 'This sentence is ungrammatical. Choose the correct version.',
      prompt: 'Falsch: "Ich lerne Deutsch, um mein Bruder in Deutschland studiert." Was ist richtig?',
      options: [
        { id: 'a', text: 'Ich lerne Deutsch, um mein Bruder in Deutschland zu studieren.' },
        { id: 'b', text: 'Ich lerne Deutsch, damit mein Bruder in Deutschland studiert.' },
        { id: 'c', text: 'Ich lerne Deutsch, um mein Bruder in Deutschland studieren.' },
        { id: 'd', text: 'Ich lerne Deutsch, damit mein Bruder in Deutschland zu studieren.' },
      ],
      correctOptionId: 'b',
      explanation: 'The subjects differ (ich vs. mein Bruder), so um ... zu is impossible; damit introduces a full clause with its own subject and finite verb studiert.',
    },
    {
      id: 'ch79-ex-13',
      chapterNumber: 79,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['um-zu', 'dialogue', 'same-subject'],
      instruction: "Choose the grammatically correct way for Tom to finish his answer.",
      dialogue: [
        { speaker: 'Anna', german: 'Warum lernst du jeden Tag Vokabeln?', english: 'Why do you learn vocabulary every day?' },
        { speaker: 'Tom', german: 'Ich lerne jeden Tag Vokabeln, ...', english: "I learn vocabulary every day ..." },
      ],
      prompt: "Tom's answer (same subject: er lernt für sich selbst): Ich lerne jeden Tag Vokabeln, ___",
      options: [
        { id: 'a', text: 'um die Prüfung zu bestehen.' },
        { id: 'b', text: 'um ich die Prüfung bestehe.' },
        { id: 'c', text: 'um die Prüfung bestehen zu.' },
        { id: 'd', text: 'damit die Prüfung zu bestehen.' },
      ],
      correctOptionId: 'a',
      explanation: 'Same subject (ich), so um ... zu is used, with zu directly before the infinitive bestehen at the very end.',
    },
    {
      id: 'ch79-ex-14',
      chapterNumber: 79,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['damit', 'clause-combination', 'modal-verb'],
      instruction: 'Choose the correctly combined sentence.',
      prompt: 'Combine: "Ich gebe dir meine Nummer." + "Du kannst mich anrufen."',
      options: [
        { id: 'a', text: 'Ich gebe dir meine Nummer, damit du mich anrufen kannst.' },
        { id: 'b', text: 'Ich gebe dir meine Nummer, um du mich anrufen kannst.' },
        { id: 'c', text: 'Ich gebe dir meine Nummer, damit du kannst mich anrufen.' },
        { id: 'd', text: 'Ich gebe dir meine Nummer, um mich anrufen zu kannst.' },
      ],
      correctOptionId: 'a',
      explanation: 'Subjects differ (ich vs. du), so damit is required; as in any subordinate clause, the modal verb (kannst) goes to the very end.',
    },
    {
      id: 'ch79-ex-15',
      chapterNumber: 79,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['um-zu', 'zu-placement'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich lerne jeden Tag, um die Prüfung zu ___. (bestehen)',
      acceptedAnswers: ['bestehen'],
      answerMode: 'caseInsensitive',
      placeholder: 'bestehen',
      maxLength: 15,
      explanation: 'zu stands directly before the infinitive bestehen, which sits at the very end of the clause.',
    },
    {
      id: 'ch79-ex-16',
      chapterNumber: 79,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['um-zu', 'zu-placement'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Er spart Geld, um sich ein neues Auto ___ kaufen.',
      acceptedAnswers: ['zu'],
      answerMode: 'caseInsensitive',
      placeholder: 'zu',
      maxLength: 5,
      explanation: 'zu goes directly before the infinitive kaufen: um ... zu kaufen.',
    },
    {
      id: 'ch79-ex-17',
      chapterNumber: 79,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['damit', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich erkläre es langsam, damit du es ___. (verstehen, du-Form)',
      acceptedAnswers: ['verstehst'],
      answerMode: 'caseInsensitive',
      placeholder: 'verstehst',
      maxLength: 15,
      explanation: 'damit sends the finite verb to the end; the du-form of verstehen is verstehst.',
    },
    {
      id: 'ch79-ex-18',
      chapterNumber: 79,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['um-zu', 'same-subject', 'connector-choice'],
      instruction: 'Write only the missing connector. Capitalisation is not checked.',
      prompt: 'Wir gehen früh ins Bett, ___ morgen fit zu sein. (same subject: wir / wir)',
      acceptedAnswers: ['um'],
      answerMode: 'caseInsensitive',
      placeholder: 'um',
      maxLength: 5,
      explanation: 'Same subject (wir) in both clauses, so um ... zu is used.',
    },
    {
      id: 'ch79-ex-19',
      chapterNumber: 79,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['damit', 'different-subject', 'connector-choice'],
      instruction: 'Write only the missing connector. Capitalisation is not checked.',
      prompt: 'Die Lehrerin spricht laut, ___ alle Schüler sie hören können. (different subjects)',
      acceptedAnswers: ['damit'],
      answerMode: 'caseInsensitive',
      placeholder: 'damit',
      maxLength: 8,
      explanation: 'Subjects differ (die Lehrerin vs. alle Schüler), so damit is required.',
    },
    {
      id: 'ch79-ex-20',
      chapterNumber: 79,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['um-zu', 'clause-combination'],
      instruction: 'Combine the two sentences with um ... zu. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich rufe dich an. + Ich sage dir Bescheid. (um ... zu)',
      acceptedAnswers: ['Ich rufe dich an, um dir Bescheid zu sagen.'],
      answerMode: 'normalized',
      placeholder: 'Ich rufe dich an, um ...',
      maxLength: 60,
      explanation: 'Same subject (ich); the second clause becomes um dir Bescheid zu sagen, with the infinitive and zu at the end.',
    },
    {
      id: 'ch79-ex-21',
      chapterNumber: 79,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['damit', 'clause-combination', 'negation'],
      instruction: 'Combine the two sentences with damit. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich flüstere. + Die Kinder wachen nicht auf. (damit)',
      acceptedAnswers: ['Ich flüstere, damit die Kinder nicht aufwachen.'],
      answerMode: 'normalized',
      placeholder: 'Ich flüstere, damit ...',
      maxLength: 60,
      explanation: 'Subjects differ (ich vs. die Kinder), so damit is required; the separable verb aufwachen joins into one word at the end.',
    },
    {
      id: 'ch79-ex-22',
      chapterNumber: 79,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['um-zu', 'negation', 'clause-combination'],
      instruction: 'Combine the two sentences with um ... zu, negated. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich beeile mich. + Ich verpasse den Bus nicht. (um ... zu)',
      acceptedAnswers: ['Ich beeile mich, um den Bus nicht zu verpassen.'],
      answerMode: 'normalized',
      placeholder: 'Ich beeile mich, um ...',
      maxLength: 60,
      explanation: 'nicht stands before the element it negates (den Bus ... nicht), and zu stays right before the infinitive verpassen at the end.',
    },
    {
      id: 'ch79-ex-23',
      chapterNumber: 79,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['damit', 'negation', 'clause-combination', 'separable-verb'],
      instruction: 'Combine the two sentences with damit, negated. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Wir schließen die Tür. + Die Katze geht nicht raus. (damit)',
      acceptedAnswers: ['Wir schließen die Tür, damit die Katze nicht rausgeht.'],
      answerMode: 'normalized',
      placeholder: 'Wir schließen die Tür, damit ...',
      maxLength: 60,
      explanation: 'damit introduces the clause; nicht stands before the separable verb, which joins as one word at the end: rausgeht.',
    },
    {
      id: 'ch79-ex-24',
      chapterNumber: 79,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['um-zu', 'separable-verb', 'clause-combination'],
      instruction: 'Combine the two sentences with um ... zu. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich gehe in die Stadt. + Ich kaufe ein. (um ... zu)',
      acceptedAnswers: ['Ich gehe in die Stadt, um einzukaufen.'],
      answerMode: 'normalized',
      placeholder: 'Ich gehe in die Stadt, um ...',
      maxLength: 50,
      explanation: 'einkaufen is separable; zu is inserted between the prefix and the stem, forming one word: einzukaufen.',
    },
    {
      id: 'ch79-ex-25',
      chapterNumber: 79,
      order: 25,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'different-subject', 'damit'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich erkläre es langsam, um du es verstehst.',
      acceptedAnswers: ['Ich erkläre es langsam, damit du es verstehst.'],
      answerMode: 'normalized',
      placeholder: 'Ich erkläre es langsam, damit ...',
      maxLength: 60,
      explanation: 'um ... zu can never take its own subject; since the subjects differ (ich vs. du), damit is required.',
    },
    {
      id: 'ch79-ex-26',
      chapterNumber: 79,
      order: 26,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'um-zu', 'negation'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Er nimmt den Schirm mit, um zu nicht nass werden.',
      acceptedAnswers: ['Er nimmt den Schirm mit, um nicht nass zu werden.'],
      answerMode: 'normalized',
      placeholder: 'Er nimmt den Schirm mit, um ...',
      maxLength: 60,
      explanation: 'nicht comes before the word it negates (nass); zu stays directly before the infinitive at the very end: um nicht nass zu werden.',
    },
    {
      id: 'ch79-ex-27',
      chapterNumber: 79,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['um-zu', 'dialogue', 'same-subject'],
      instruction: "Complete Lea's answer. Write only the missing words. Capitalisation is not checked.",
      dialogue: [
        { speaker: 'Ben', german: 'Warum machst du das Fenster auf?', english: 'Why are you opening the window?' },
        { speaker: 'Lea', german: 'Ich mache das Fenster auf, ___', english: 'I am opening the window ___' },
      ],
      prompt: 'Ich mache das Fenster auf, ___. (frische Luft / bekommen, um ... zu)',
      acceptedAnswers: ['um frische Luft zu bekommen'],
      answerMode: 'caseInsensitive',
      placeholder: 'um frische Luft zu bekommen',
      maxLength: 40,
      explanation: 'Same subject (ich) in both parts, so um ... zu + infinitive is used, with zu directly before bekommen at the end.',
    },
    {
      id: 'ch79-ex-28',
      chapterNumber: 79,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['damit', 'different-subject', 'modal-verb', 'clause-combination'],
      instruction: 'Combine the two sentences with damit. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Der Lehrer spricht laut. + Alle Schüler können ihn hören. (damit)',
      acceptedAnswers: ['Der Lehrer spricht laut, damit alle Schüler ihn hören können.'],
      answerMode: 'normalized',
      placeholder: 'Der Lehrer spricht laut, damit ...',
      maxLength: 70,
      explanation: 'Subjects differ (der Lehrer vs. alle Schüler); damit introduces the clause, and the modal verb können goes to the very end, after the infinitive hören.',
    },
  ],
};
