import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter031: ChapterDefinition = {
  id: 'chapter-031',
  number: 31,
  slug: 'reflexive-and-reciprocal-verbs',
  title: 'Reflexive and Reciprocal Verbs',
  germanTitle: 'Reflexive und reziproke Verben',
  level: 'A2',
  section: 'verbs-2',
  objective:
    'Use the accusative reflexive pronouns (mich, dich, sich, uns, euch, sich) correctly with truly reflexive verbs and with verbs that are only sometimes reflexive, tell reflexive meaning apart from reciprocal ("each other") meaning, and describe a daily routine using verbs such as aufstehen, sich duschen, sich anziehen, sich ausruhen, and sich treffen.',
  prerequisites: [2, 17, 18],
  estimatedMinutes: 22,
  tags: [
    'reflexive verbs',
    'reflexive pronouns',
    'reciprocal verbs',
    'accusative case',
    'daily routine',
  ],
  explanation: {
    introduction: [
      'In a reflexive sentence, the subject and the object of the verb are the same person or thing: the action "reflects back" onto whoever is doing it. Compare Ich wasche das Auto. (I wash the car — the object is the car) with Ich wasche mich. (I wash myself — the object is the same person as the subject). The small word that shows this, mich, is called a reflexive pronoun.',
      'This chapter builds on the present tense (Chapter 2) and the accusative case (Chapter 17): the reflexive pronouns you will meet here are almost all identical to the accusative personal pronouns you already know, used with a special group of verbs. You will also learn how the plural forms uns, euch, and sich can mean "each other" (a reciprocal action between two or more people), and you will meet the everyday verbs of a typical daily routine.',
    ],
    rules: [
      {
        id: 'ch31-rule-01',
        heading: 'Reflexive verbs: when the action reflects back onto the subject',
        paragraphs: [
          'In a reflexive sentence, the subject and the object of the verb are the same person or thing: the action "reflects back" onto whoever is doing it. Compare Ich wasche das Auto. (I wash the car — object is the car) with Ich wasche mich. (I wash myself — object is the same person as the subject).',
          'The word that shows this is the reflexive pronoun, and this chapter focuses on its accusative forms: mich, dich, sich, uns, euch, sich. You already know most of these shapes from the accusative personal pronouns in Chapter 17 — what is new is how they are used with a special group of verbs.',
        ],
      },
      {
        id: 'ch31-rule-02',
        heading: 'The reflexive pronouns: mostly familiar, with one new form',
        paragraphs: [
          'Four of the six reflexive pronouns are identical to accusative personal pronouns you already know: mich (ich), dich (du), uns (wir), euch (ihr). The difference appears in the third person and the formal Sie: instead of ihn, sie, es, sie, Sie, reflexive sentences always use the single form sich, regardless of gender or number.',
          'So er, sie, es, the plural sie, and the formal Sie all take sich: Er wäscht sich., Sie (she) wäscht sich., Sie (they) waschen sich., Waschen Sie sich? — the verb ending changes with the subject, but the reflexive pronoun sich never does.',
        ],
      },
      {
        id: 'ch31-rule-03',
        heading: 'Truly reflexive verbs: sich is not optional',
        paragraphs: [
          'Some German verbs are "truly reflexive": they always appear with a reflexive pronoun, and either have no independent meaning without it or mean something completely different. Common examples are sich beeilen (to hurry), sich erkälten (to catch a cold), sich freuen (auf/über) (to look forward to / to be glad about), sich interessieren (für) (to be interested in), and sich ausruhen (to rest).',
          'You cannot simply drop sich from these verbs: Ich beeile mich. is complete and correct, but Ich beeile. is not a sentence a native speaker would use. With sich interessieren, dropping sich changes the meaning altogether — interessieren without sich means "to interest (someone else)", not "to be interested".',
        ],
      },
      {
        id: 'ch31-rule-04',
        heading: 'Verbs used reflexively with an accusative object',
        paragraphs: [
          'A second group of verbs has a normal, non-reflexive meaning with a different accusative object, and a separate reflexive meaning where the subject acts on itself. sich waschen, sich anziehen, and sich setzen belong here.',
          'Compare Ich wasche das Baby. (I wash the baby — the object is someone else) with Ich wasche mich. (I wash myself — the object is the same person as the subject); or Ich setze die Tasse auf den Tisch. (I put the cup on the table) with Ich setze mich auf den Stuhl. (I sit down on the chair, literally "I set myself").',
        ],
      },
      {
        id: 'ch31-rule-05',
        heading: 'Reciprocal meaning: uns, euch, sich as "each other"',
        paragraphs: [
          'When the subject is plural (wir, ihr, sie, or a formal Sie referring to more than one person), the same reflexive pronouns uns, euch, and sich can express a reciprocal meaning: not "each person to themselves", but "to each other". Verbs commonly used this way include sich treffen (to meet up), sich kennen (to know each other), sich lieben (to love each other), and sich umarmen (to hug each other).',
          'Only the context and the verb tell you whether a plural sentence is reflexive or reciprocal: Wir waschen uns. is naturally reflexive (each person washes themselves), while Wir umarmen uns. is naturally reciprocal (the people hug one another) — very few verbs make sense both ways with the same subject.',
        ],
      },
      {
        id: 'ch31-rule-06',
        heading: 'Reflexive verbs in the daily routine',
        paragraphs: [
          'Reflexive verbs are especially common when describing a daily routine. A typical morning might be described as: Ich stehe auf. Ich dusche mich. Ich ziehe mich an. Am Abend ruhe ich mich aus, und am Wochenende treffe ich mich mit Freunden. Notice that aufstehen (to get up) is not reflexive, while sich duschen, sich anziehen, sich ausruhen, and sich treffen all are.',
          'Learning these verbs together with their pronouns as part of a routine — rather than in isolation — makes it much easier to remember which verbs need sich and which do not.',
        ],
      },
      {
        id: 'ch31-rule-07',
        heading: 'Word order: where the reflexive pronoun goes',
        paragraphs: [
          'In a main clause, the reflexive pronoun stands right after the conjugated verb, just like other pronoun objects: Ich wasche mich schnell. and, inverted in a question, Wäschst du dich schnell?',
          'With separable verbs such as sich anziehen and sich ausruhen, the reflexive pronoun still comes right after the conjugated verb, while the separated prefix (an, aus) moves to the very end of the clause: Er zieht sich an. and Ich ruhe mich aus.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch31-table-01',
        title: 'Accusative reflexive pronouns',
        columns: ['Subject', 'Reflexive pronoun', 'English'],
        columnCases: [null, 'accusative', null],
        rows: [
          ['ich', 'mich', 'myself'],
          ['du', 'dich', 'yourself (informal singular)'],
          ['er/sie/es', 'sich', 'himself/herself/itself'],
          ['wir', 'uns', 'ourselves'],
          ['ihr', 'euch', 'yourselves (informal plural)'],
          ['sie/Sie', 'sich', 'themselves/yourself (formal)'],
        ],
        note: 'Every form in this table happens to be an accusative reflexive pronoun; a separate dative reflexive set is introduced in a later chapter.',
      },
      {
        id: 'ch31-table-02',
        title: 'Truly reflexive verbs vs. verbs also used with a different object',
        columns: ['Truly reflexive (always with sich)', 'Also used with a different object'],
        rows: [
          ['sich beeilen (to hurry)', 'waschen (to wash something) → sich waschen (to wash oneself)'],
          [
            'sich erkälten (to catch a cold)',
            'anziehen (to put clothes on someone) → sich anziehen (to get dressed)',
          ],
          ['sich freuen (to be glad)', 'setzen (to put/place something) → sich setzen (to sit down)'],
          [
            'sich interessieren (to be interested)',
            'vorstellen (to introduce someone) → sich vorstellen (to introduce oneself)',
          ],
          ['sich ausruhen (to rest)', 'duschen (to shower) → sich duschen (to shower oneself)'],
        ],
        note: 'The left column has no meaningful use without sich; the right column keeps the same verb but changes the object.',
      },
    ],
    examples: [
      {
        german: 'Ich beeile mich, weil der Bus gleich kommt.',
        english: 'I am hurrying because the bus is coming soon.',
        highlight: ['mich'],
        explanation: 'sich beeilen is a truly reflexive verb; ich takes the reflexive pronoun mich.',
      },
      {
        german: 'Du wäschst dich jeden Morgen.',
        english: 'You wash yourself every morning.',
        highlight: ['dich'],
        explanation: 'du takes the reflexive pronoun dich, the same form as the accusative personal pronoun you already know.',
      },
      {
        german: 'Er zieht sich schnell an.',
        english: 'He gets dressed quickly.',
        highlight: ['sich'],
        explanation: 'er uses the reflexive pronoun sich, not the accusative personal pronoun ihn.',
      },
      {
        german: 'Wir freuen uns auf die Ferien.',
        english: 'We are looking forward to the holidays.',
        highlight: ['uns'],
        explanation: 'sich freuen auf is a truly reflexive verb; wir takes the reflexive pronoun uns.',
      },
      {
        german: 'Interessiert ihr euch für Kunst?',
        english: 'Are you interested in art?',
        highlight: ['euch'],
        explanation: 'sich interessieren für is truly reflexive; ihr takes the reflexive pronoun euch.',
      },
      {
        german: 'Die Kinder setzen sich auf den Boden.',
        english: 'The children sit down on the floor.',
        highlight: ['sich'],
        explanation: 'third-person plural (die Kinder = sie) uses the reflexive pronoun sich, not the personal pronoun sie.',
      },
      {
        german: 'Ich erkälte mich fast jeden Winter.',
        english: 'I catch a cold almost every winter.',
        highlight: ['mich'],
        explanation: 'sich erkälten has no meaningful use without the reflexive pronoun; ich takes mich.',
      },
      {
        german: 'Ich stehe früh auf und dusche mich sofort.',
        english: 'I get up early and shower right away.',
        highlight: ['dusche mich'],
        explanation: 'the daily-routine verb sich duschen takes the reflexive pronoun mich for ich.',
      },
      {
        german: 'Wir umarmen uns zur Begrüßung.',
        english: 'We hug each other in greeting.',
        highlight: ['uns'],
        explanation: 'here uns has a reciprocal meaning, "each other", describing a mutual action between the people involved, not each person hugging themselves.',
      },
      {
        german: 'Ihr kennt euch schon seit der Schule.',
        english: 'You have known each other since school.',
        highlight: ['euch'],
        explanation: 'euch is reciprocal here: "you know each other", not "you know yourselves".',
      },
      {
        german: 'Sie treffen sich jeden Samstag im Park.',
        english: 'They meet each other every Saturday in the park.',
        highlight: ['sich'],
        explanation: 'sich treffen with a plural subject usually has a reciprocal meaning: the people meet one another.',
      },
      {
        german: 'Ich ruhe mich nach der Arbeit aus.',
        english: 'I rest after work.',
        highlight: ['ruhe mich', 'aus'],
        explanation: 'sich ausruhen is separable and reflexive; the pronoun mich comes right after the conjugated verb, and aus moves to the end.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich beeile.',
        correct: 'Ich beeile mich.',
        explanation: 'sich beeilen always requires the reflexive pronoun; it cannot stand alone.',
      },
      {
        incorrect: 'Er sich zieht schnell an.',
        correct: 'Er zieht sich schnell an.',
        explanation: 'the reflexive pronoun stands right after the conjugated verb, not before it.',
      },
      {
        incorrect: 'Wir freuen sich auf die Party.',
        correct: 'Wir freuen uns auf die Party.',
        explanation: 'the reflexive pronoun must agree with the subject; wir takes uns, not the third-person sich.',
      },
      {
        incorrect: 'Du interessierst dir für Sport.',
        correct: 'Du interessierst dich für Sport.',
        explanation: 'sich interessieren takes the accusative reflexive pronoun dich, not the dative dir.',
      },
      {
        incorrect: 'Wir treffen am Freitag.',
        correct: 'Wir treffen uns am Freitag.',
        explanation: 'treffen used with a reciprocal, "meet up" meaning needs the reflexive/reciprocal pronoun uns; without it, treffen would need a direct-object noun instead.',
      },
    ],
    remember: [
      'Reflexive pronouns: mich, dich, sich, uns, euch, sich — four forms match the accusative personal pronouns you already know, but er/sie/es, plural sie, and formal Sie all use sich.',
      'Truly reflexive verbs (sich beeilen, sich erkälten, sich freuen, sich interessieren, sich ausruhen) always need sich; other verbs like sich waschen, sich anziehen, and sich setzen also have a non-reflexive use with a different object.',
      'With plural subjects, uns/euch/sich can mean "each other" (reciprocal), not just "themselves" — context and the verb tell you which is meant.',
      'Word order: the reflexive pronoun comes right after the conjugated verb; with separable verbs, the prefix still moves to the end of the clause.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 67,
    requiredCorrectTextInputs: 22,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch31-ex-01',
      chapterNumber: 31,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'ich'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ich beeile ___. (sich beeilen)',
      options: [
        { id: 'a', text: 'mich' },
        { id: 'b', text: 'mir' },
        { id: 'c', text: 'ich' },
        { id: 'd', text: 'mein' },
      ],
      correctOptionId: 'a',
      explanation: 'sich beeilen is a truly reflexive verb; ich takes the accusative reflexive pronoun mich.',
    },
    {
      id: 'ch31-ex-02',
      chapterNumber: 31,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'du'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Du wäschst ___ jeden Morgen. (sich waschen)',
      options: [
        { id: 'a', text: 'dich' },
        { id: 'b', text: 'dir' },
        { id: 'c', text: 'du' },
        { id: 'd', text: 'dein' },
      ],
      correctOptionId: 'a',
      explanation: 'du takes the reflexive pronoun dich, the same form as the accusative personal pronoun.',
    },
    {
      id: 'ch31-ex-03',
      chapterNumber: 31,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'er'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Er zieht ___ schnell an. (sich anziehen)',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'ihn' },
        { id: 'c', text: 'ihm' },
        { id: 'd', text: 'er' },
      ],
      correctOptionId: 'a',
      explanation: 'the third person er uses the reflexive pronoun sich, not the accusative personal pronoun ihn.',
    },
    {
      id: 'ch31-ex-04',
      chapterNumber: 31,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'wir'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Wir freuen ___ auf das Wochenende. (sich freuen)',
      options: [
        { id: 'a', text: 'uns' },
        { id: 'b', text: 'euch' },
        { id: 'c', text: 'wir' },
        { id: 'd', text: 'unser' },
      ],
      correctOptionId: 'a',
      explanation: 'wir takes the reflexive pronoun uns.',
    },
    {
      id: 'ch31-ex-05',
      chapterNumber: 31,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'ihr'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Interessiert ___ für Musik? (sich interessieren, ihr)',
      options: [
        { id: 'a', text: 'euch' },
        { id: 'b', text: 'uns' },
        { id: 'c', text: 'ihr' },
        { id: 'd', text: 'euer' },
      ],
      correctOptionId: 'a',
      explanation: 'ihr takes the reflexive pronoun euch.',
    },
    {
      id: 'ch31-ex-06',
      chapterNumber: 31,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'sie-plural'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Die Kinder setzen ___ auf den Boden. (sich setzen)',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'ihnen' },
        { id: 'c', text: 'sie' },
        { id: 'd', text: 'ihr' },
      ],
      correctOptionId: 'a',
      explanation: 'third-person plural (die Kinder = sie) also uses the reflexive pronoun sich, not the personal pronoun sie.',
    },
    {
      id: 'ch31-ex-07',
      chapterNumber: 31,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'Sie-formal'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Können Sie ___ kurz vorstellen? (sich vorstellen, Sie formal)',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'Sie' },
        { id: 'c', text: 'Ihnen' },
        { id: 'd', text: 'Ihre' },
      ],
      correctOptionId: 'a',
      explanation: 'the formal Sie also uses the reflexive pronoun sich, never Sie itself.',
    },
    {
      id: 'ch31-ex-08',
      chapterNumber: 31,
      order: 8,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'ich-vs-dative'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ich interessiere ___ für Geschichte. (sich interessieren, ich)',
      options: [
        { id: 'a', text: 'mich' },
        { id: 'b', text: 'mir' },
        { id: 'c', text: 'ich' },
        { id: 'd', text: 'meiner' },
      ],
      correctOptionId: 'a',
      explanation: 'sich interessieren takes the accusative reflexive pronoun; ich becomes mich, not the dative mir.',
    },
    {
      id: 'ch31-ex-09',
      chapterNumber: 31,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive-vs-reciprocal'],
      instruction: 'Choose the sentence that expresses a reciprocal meaning ("each other").',
      prompt: 'Welcher Satz drückt eine reziproke Bedeutung ("each other") aus?',
      options: [
        { id: 'a', text: 'Wir waschen uns jeden Morgen.' },
        { id: 'b', text: 'Wir umarmen uns zur Begrüßung.' },
        { id: 'c', text: 'Ich dusche mich schnell.' },
        { id: 'd', text: 'Ich stehe früh auf.' },
      ],
      correctOptionId: 'b',
      explanation: 'Wir umarmen uns describes a mutual action between two or more people (they hug each other), which is the reciprocal use of uns; sich waschen and sich duschen describe ordinary reflexive actions performed on oneself, and aufstehen is not reflexive at all.',
    },
    {
      id: 'ch31-ex-10',
      chapterNumber: 31,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['truly-reflexive-vs-object'],
      instruction: 'Choose the verb that always needs a reflexive pronoun.',
      prompt: 'Welches Verb braucht immer ein Reflexivpronomen (kein Satz ohne sich ist möglich)?',
      options: [
        { id: 'a', text: 'waschen' },
        { id: 'b', text: 'sich beeilen' },
        { id: 'c', text: 'anziehen' },
        { id: 'd', text: 'setzen' },
      ],
      correctOptionId: 'b',
      explanation: 'sich beeilen is a truly reflexive verb with no independent, non-reflexive use, unlike waschen, anziehen and setzen, which can also take a different accusative object.',
    },
    {
      id: 'ch31-ex-11',
      chapterNumber: 31,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'separable-verb'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt: 'Welcher Satz hat die richtige Wortstellung?',
      options: [
        { id: 'a', text: 'Er sich zieht schnell an.' },
        { id: 'b', text: 'Er zieht sich schnell an.' },
        { id: 'c', text: 'Er zieht schnell sich an.' },
        { id: 'd', text: 'Sich zieht er schnell an.' },
      ],
      correctOptionId: 'b',
      explanation: 'the reflexive pronoun stands right after the conjugated verb; the separable prefix an moves to the very end of the clause.',
    },
    {
      id: 'ch31-ex-12',
      chapterNumber: 31,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'du', 'case'],
      instruction: 'Choose the correct sentence.',
      prompt: 'Welcher Satz ist richtig?',
      options: [
        { id: 'a', text: 'Du interessierst dich für Musik.' },
        { id: 'b', text: 'Du interessierst dir für Musik.' },
        { id: 'c', text: 'Du interessierst sich für Musik.' },
        { id: 'd', text: 'Du interessierst euch für Musik.' },
      ],
      correctOptionId: 'a',
      explanation: 'sich interessieren takes the accusative reflexive pronoun matching the subject du, which is dich — not the dative dir, the third-person sich, or the plural euch.',
    },
    {
      id: 'ch31-ex-13',
      chapterNumber: 31,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'ich'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ich freue ___ auf den Urlaub. (ich)',
      acceptedAnswers: ['mich'],
      answerMode: 'caseInsensitive',
      placeholder: 'mich',
      maxLength: 10,
      explanation: 'sich freuen auf is reflexive; ich takes the reflexive pronoun mich.',
    },
    {
      id: 'ch31-ex-14',
      chapterNumber: 31,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'du'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wäschst du ___ mit kaltem Wasser? (du)',
      acceptedAnswers: ['dich'],
      answerMode: 'caseInsensitive',
      placeholder: 'dich',
      maxLength: 10,
      explanation: 'du takes the reflexive pronoun dich.',
    },
    {
      id: 'ch31-ex-15',
      chapterNumber: 31,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'sie-plural'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Die Kinder ziehen ___ selbst an. (sie, Plural)',
      acceptedAnswers: ['sich'],
      answerMode: 'caseInsensitive',
      placeholder: 'sich',
      maxLength: 10,
      explanation: 'third-person plural (die Kinder = sie) takes the reflexive pronoun sich.',
    },
    {
      id: 'ch31-ex-16',
      chapterNumber: 31,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'wir'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wir setzen ___ an den Tisch. (wir)',
      acceptedAnswers: ['uns'],
      answerMode: 'caseInsensitive',
      placeholder: 'uns',
      maxLength: 10,
      explanation: 'wir takes the reflexive pronoun uns.',
    },
    {
      id: 'ch31-ex-17',
      chapterNumber: 31,
      order: 17,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'er'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Er erkältet ___ fast jeden Winter.',
      acceptedAnswers: ['sich'],
      answerMode: 'caseInsensitive',
      placeholder: 'sich',
      maxLength: 10,
      explanation: 'sich erkälten is truly reflexive; er takes sich.',
    },
    {
      id: 'ch31-ex-18',
      chapterNumber: 31,
      order: 18,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'ihr'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ihr müsst ___ beeilen, der Zug fährt gleich.',
      acceptedAnswers: ['euch'],
      answerMode: 'caseInsensitive',
      placeholder: 'euch',
      maxLength: 10,
      explanation: 'ihr takes the reflexive pronoun euch; sich beeilen is truly reflexive.',
    },
    {
      id: 'ch31-ex-19',
      chapterNumber: 31,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'daily-routine'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ich stehe früh auf und dusche ___ sofort.',
      acceptedAnswers: ['mich'],
      answerMode: 'caseInsensitive',
      placeholder: 'mich',
      maxLength: 10,
      explanation: 'the daily-routine verb sich duschen takes the reflexive pronoun mich for ich.',
    },
    {
      id: 'ch31-ex-20',
      chapterNumber: 31,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'reciprocal', 'wir'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wann treffen wir ___ am Samstag?',
      acceptedAnswers: ['uns'],
      answerMode: 'caseInsensitive',
      placeholder: 'uns',
      maxLength: 10,
      explanation: 'sich treffen with wir has a reciprocal meaning ("when are we meeting up"), and wir takes the reflexive pronoun uns.',
    },
    {
      id: 'ch31-ex-21',
      chapterNumber: 31,
      order: 21,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['truly-reflexive', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich beeile.',
      acceptedAnswers: ['Ich beeile mich.'],
      answerMode: 'normalized',
      placeholder: 'Ich beeile ...',
      maxLength: 40,
      explanation: 'sich beeilen always needs the reflexive pronoun; ich requires mich.',
    },
    {
      id: 'ch31-ex-22',
      chapterNumber: 31,
      order: 22,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['reflexive-agreement', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Wir freuen sich auf die Party.',
      acceptedAnswers: ['Wir freuen uns auf die Party.'],
      answerMode: 'normalized',
      placeholder: 'Wir freuen ...',
      maxLength: 40,
      explanation: 'the reflexive pronoun must agree with the subject; wir takes uns, not the third-person sich.',
    },
    {
      id: 'ch31-ex-23',
      chapterNumber: 31,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['word-order', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Sich er beeilt, weil er spät dran ist.',
      acceptedAnswers: ['Er beeilt sich, weil er spät dran ist.'],
      answerMode: 'normalized',
      placeholder: 'Er beeilt sich, ...',
      maxLength: 60,
      explanation: 'the reflexive pronoun sich comes right after the conjugated verb (beeilt), not before the subject.',
    },
    {
      id: 'ch31-ex-24',
      chapterNumber: 31,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['reciprocal', 'sentence-building'],
      instruction: 'Write a complete sentence using the cues. The pronoun expresses a reciprocal meaning ("each other"). Capitalisation is checked; no full stop is required.',
      prompt: 'ihr – sich treffen – am Freitag',
      acceptedAnswers: ['Ihr trefft euch am Freitag.', 'Ihr trefft euch am Freitag'],
      answerMode: 'normalized',
      placeholder: 'Ihr trefft ...',
      maxLength: 60,
      explanation: 'sich treffen with ihr takes the reflexive/reciprocal pronoun euch: "you are meeting (each other) on Friday."',
    },
    {
      id: 'ch31-ex-25',
      chapterNumber: 31,
      order: 25,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'es'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Das Baby freut ___ über das Spielzeug. (sich freuen, es)',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'es' },
        { id: 'c', text: 'ihm' },
        { id: 'd', text: 'ihn' },
      ],
      correctOptionId: 'a',
      explanation: 'the third person es also takes the reflexive pronoun sich, just like er and sie.',
    },
    {
      id: 'ch31-ex-26',
      chapterNumber: 31,
      order: 26,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'Sie-formal'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Setzen Sie ___ bitte hierhin. (Sie, formal)',
      acceptedAnswers: ['sich'],
      answerMode: 'caseInsensitive',
      placeholder: 'sich',
      maxLength: 10,
      explanation: 'the formal Sie also uses the reflexive pronoun sich, never Ihnen.',
    },
    {
      id: 'ch31-ex-27',
      chapterNumber: 31,
      order: 27,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'wir'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Wir beeilen ___, der Film beginnt gleich.',
      templateParts: ['Wir beeilen ', ', der Film beginnt gleich.'],
      slots: [{ id: 's1', correctWord: 'uns' }],
      wordBank: ['uns', 'sich', 'euch', 'mich'],
      explanation: 'wir takes the reflexive pronoun uns; sich beeilen is truly reflexive.',
    },
    {
      id: 'ch31-ex-28',
      chapterNumber: 31,
      order: 28,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'subject-agreement'],
      instruction: 'Match each subject pronoun to its correct reflexive pronoun.',
      prompt: 'Ordne jedes Subjektpronomen dem passenden Reflexivpronomen zu.',
      pairs: [
        { id: 'p1', left: 'ich', right: 'mich' },
        { id: 'p2', left: 'du', right: 'dich' },
        { id: 'p3', left: 'wir', right: 'uns' },
        { id: 'p4', left: 'ihr', right: 'euch' },
        { id: 'p5', left: 'er/sie/es/sie (Pl.)/Sie', right: 'sich' },
      ],
      explanation: 'four reflexive pronouns match the accusative personal pronouns you already know (mich, dich, uns, euch), while every third-person form and the formal Sie use sich.',
    },
    {
      id: 'ch31-ex-29',
      chapterNumber: 31,
      order: 29,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['reflexive-agreement', 'error-correction'],
      instruction: 'Find the token with the reflexive-pronoun error.',
      prompt: 'Ich wasche dich jeden Tag.',
      tokens: ['Ich', 'wasche', 'dich', 'jeden', 'Tag', '.'],
      errorTokenIndex: 2,
      correction: 'mich',
      explanation: 'ich requires the reflexive pronoun mich; dich would wrongly refer to a different person (du) instead of the subject itself.',
    },
    {
      id: 'ch31-ex-30',
      chapterNumber: 31,
      order: 30,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'body-part-verb'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ich putze ___ die Zähne. (sich die Zähne putzen, ich)',
      options: [
        { id: 'a', text: 'mir' },
        { id: 'b', text: 'mich' },
        { id: 'c', text: 'mein' },
        { id: 'd', text: 'ich' },
      ],
      correctOptionId: 'a',
      explanation: 'with sich die Zähne putzen, die Zähne is already the accusative object, so the reflexive pronoun takes the dative form mir instead of the accusative mich.',
    },
    {
      id: 'ch31-ex-31',
      chapterNumber: 31,
      order: 31,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'du', 'body-part-verb'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Du putzt ___ die Zähne vor dem Schlafen. (du)',
      acceptedAnswers: ['dir'],
      answerMode: 'caseInsensitive',
      placeholder: 'dir',
      maxLength: 10,
      explanation: 'die Zähne is the accusative object here, so du takes the dative reflexive pronoun dir, not the accusative dich.',
    },
    {
      id: 'ch31-ex-32',
      chapterNumber: 31,
      order: 32,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'wir', 'body-part-verb'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Wir waschen ___ die Hände vor dem Essen.',
      templateParts: ['Wir waschen ', ' die Hände vor dem Essen.'],
      slots: [{ id: 's1', correctWord: 'uns' }],
      wordBank: ['uns', 'sich', 'euch', 'ihnen'],
      explanation: 'die Hände is the accusative object, so wir takes the dative reflexive pronoun, which happens to have the same form as the accusative: uns.',
    },
    {
      id: 'ch31-ex-33',
      chapterNumber: 31,
      order: 33,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['truly-reflexive-verbs', 'meaning'],
      instruction: 'Match each reflexive verb to its English meaning.',
      prompt: 'Ordne jedes reflexive Verb der passenden Bedeutung zu.',
      pairs: [
        { id: 'p1', left: 'sich beeilen', right: 'to hurry' },
        { id: 'p2', left: 'sich erkälten', right: 'to catch a cold' },
        { id: 'p3', left: 'sich freuen', right: 'to be glad / look forward to' },
        { id: 'p4', left: 'sich interessieren', right: 'to be interested' },
        { id: 'p5', left: 'sich ausruhen', right: 'to rest' },
        { id: 'p6', left: 'sich vorstellen', right: 'to introduce oneself' },
      ],
      explanation: 'these verbs always appear with a reflexive pronoun, and each has a fixed English meaning built around that reflexive use.',
    },
    {
      id: 'ch31-ex-34',
      chapterNumber: 31,
      order: 34,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['reflexive pronoun', 'dative', 'error-correction', 'body-part-verb'],
      instruction: 'Find the token with the reflexive-pronoun error.',
      prompt: 'Ich putze mich die Zähne.',
      tokens: ['Ich', 'putze', 'mich', 'die', 'Zähne', '.'],
      errorTokenIndex: 2,
      correction: 'mir',
      explanation: 'die Zähne is already the accusative object, so the reflexive pronoun must be the dative mir, not the accusative mich.',
    },
    {
      id: 'ch31-ex-35',
      chapterNumber: 31,
      order: 35,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'er'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Er tut ___ weh. (sich weh tun, er)',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'ihm' },
        { id: 'c', text: 'ihn' },
        { id: 'd', text: 'er' },
      ],
      correctOptionId: 'a',
      explanation: 'sich weh tun governs the dative, but the third-person reflexive pronoun sich is identical for accusative and dative, so er still takes sich, not the personal dative pronoun ihm.',
    },
    {
      id: 'ch31-ex-36',
      chapterNumber: 31,
      order: 36,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'ich', 'body-part-verb'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ich kämme ___ die Haare vor dem Ausgehen. (ich)',
      acceptedAnswers: ['mir'],
      answerMode: 'caseInsensitive',
      placeholder: 'mir',
      maxLength: 10,
      explanation: 'die Haare is the accusative object, so ich takes the dative reflexive pronoun mir, not the accusative mich.',
    },
    {
      id: 'ch31-ex-37',
      chapterNumber: 31,
      order: 37,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'ihr', 'body-part-verb'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Wäscht ihr ___ die Hände?',
      templateParts: ['Wäscht ihr ', ' die Hände?'],
      slots: [{ id: 's1', correctWord: 'euch' }],
      wordBank: ['euch', 'uns', 'sich', 'dir'],
      explanation: 'die Hände is the accusative object, so ihr takes the dative reflexive pronoun, which has the same form as the accusative: euch.',
    },
    {
      id: 'ch31-ex-38',
      chapterNumber: 31,
      order: 38,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['reciprocal-verbs', 'meaning'],
      instruction: 'Match each reciprocal verb to its English meaning.',
      prompt: 'Ordne jedes reziproke Verb der passenden Bedeutung zu.',
      pairs: [
        { id: 'p1', left: 'sich treffen', right: 'to meet up' },
        { id: 'p2', left: 'sich kennen', right: 'to know each other' },
        { id: 'p3', left: 'sich lieben', right: 'to love each other' },
        { id: 'p4', left: 'sich umarmen', right: 'to hug each other' },
        { id: 'p5', left: 'sich verstehen', right: 'to understand each other' },
      ],
      explanation: 'with a plural subject, these verbs commonly express a reciprocal, "each other" meaning rather than a strictly reflexive one.',
    },
    {
      id: 'ch31-ex-39',
      chapterNumber: 31,
      order: 39,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['reflexive-agreement', 'error-correction'],
      instruction: 'Find the token with the reflexive-pronoun error.',
      prompt: 'Ich freue dich auf die Ferien.',
      tokens: ['Ich', 'freue', 'dich', 'auf', 'die', 'Ferien', '.'],
      errorTokenIndex: 2,
      correction: 'mich',
      explanation: 'sich freuen auf is reflexive and must agree with the subject; ich requires mich, not dich.',
    },
    {
      id: 'ch31-ex-40',
      chapterNumber: 31,
      order: 40,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive-vs-reciprocal'],
      instruction: 'Choose the sentence that expresses a reflexive (not reciprocal) meaning.',
      prompt: 'Welcher Satz drückt eine reflexive (nicht reziproke) Bedeutung aus?',
      options: [
        { id: 'a', text: 'Sie kennen sich seit der Schule.' },
        { id: 'b', text: 'Sie waschen sich jeden Abend.' },
        { id: 'c', text: 'Sie umarmen sich zur Begrüßung.' },
        { id: 'd', text: 'Sie lieben sich sehr.' },
      ],
      correctOptionId: 'b',
      explanation: 'Sie waschen sich describes each person washing themselves, a plain reflexive action, while kennen, umarmen, and lieben with a plural subject naturally describe a mutual, reciprocal action.',
    },
    {
      id: 'ch31-ex-41',
      chapterNumber: 31,
      order: 41,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['reflexive pronoun', 'dative', 'error-correction', 'body-part-verb'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich putze mich die Zähne.',
      acceptedAnswers: ['Ich putze mir die Zähne.'],
      answerMode: 'normalized',
      placeholder: 'Ich putze ...',
      maxLength: 40,
      explanation: 'die Zähne is the accusative object, so the reflexive pronoun must be dative: Ich putze mir die Zähne.',
    },
    {
      id: 'ch31-ex-42',
      chapterNumber: 31,
      order: 42,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'Sie-formal'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Möchten Sie ___ kurz vorstellen?',
      templateParts: ['Möchten Sie ', ' kurz vorstellen?'],
      slots: [{ id: 's1', correctWord: 'sich' }],
      wordBank: ['sich', 'Ihnen', 'euch', 'uns'],
      explanation: 'the formal Sie always uses the reflexive pronoun sich, never the personal dative pronoun Ihnen.',
    },
    {
      id: 'ch31-ex-43',
      chapterNumber: 31,
      order: 43,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'subject-agreement'],
      instruction: 'Match each subject-and-verb cue to its correct reflexive pronoun.',
      prompt: 'Ordne jeden Hinweis dem passenden Reflexivpronomen zu.',
      pairs: [
        { id: 'p1', left: 'ich (sich freuen)', right: 'mich' },
        { id: 'p2', left: 'du (sich interessieren)', right: 'dich' },
        { id: 'p3', left: 'wir (sich treffen)', right: 'uns' },
        { id: 'p4', left: 'ihr (sich beeilen)', right: 'euch' },
        { id: 'p5', left: 'er (sich ausruhen)', right: 'sich' },
      ],
      explanation: 'the reflexive pronoun always agrees with the subject, regardless of which reflexive verb is used.',
    },
    {
      id: 'ch31-ex-44',
      chapterNumber: 31,
      order: 44,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['reflexive pronoun', 'dative', 'error-correction', 'body-part-verb'],
      instruction: 'Find the token with the reflexive-pronoun error.',
      prompt: 'Du putzt dich die Zähne.',
      tokens: ['Du', 'putzt', 'dich', 'die', 'Zähne', '.'],
      errorTokenIndex: 2,
      correction: 'dir',
      explanation: 'die Zähne is already the accusative object, so du needs the dative reflexive pronoun dir, not the accusative dich.',
    },
    {
      id: 'ch31-ex-45',
      chapterNumber: 31,
      order: 45,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'reciprocal', 'sie-plural'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Die Freunde treffen ___ jeden Freitag. (sich treffen, sie Pl.)',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'ihnen' },
        { id: 'c', text: 'ihre' },
        { id: 'd', text: 'sie' },
      ],
      correctOptionId: 'a',
      explanation: 'die Freunde = sie (Plural); the reflexive/reciprocal pronoun for third-person plural is always sich.',
    },
    {
      id: 'ch31-ex-46',
      chapterNumber: 31,
      order: 46,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'reciprocal', 'wir'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wir verstehen ___ ohne Worte. (wir)',
      acceptedAnswers: ['uns'],
      answerMode: 'caseInsensitive',
      placeholder: 'uns',
      maxLength: 10,
      explanation: 'sich verstehen with wir has a reciprocal meaning ("we understand each other"), and wir takes uns.',
    },
    {
      id: 'ch31-ex-47',
      chapterNumber: 31,
      order: 47,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'reciprocal', 'ihr'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Ihr liebt ___ schon seit Jahren.',
      templateParts: ['Ihr liebt ', ' schon seit Jahren.'],
      slots: [{ id: 's1', correctWord: 'euch' }],
      wordBank: ['euch', 'uns', 'sich', 'dich'],
      explanation: 'ihr takes the reflexive/reciprocal pronoun euch: "you love each other."',
    },
    {
      id: 'ch31-ex-48',
      chapterNumber: 31,
      order: 48,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['truly-reflexive-vs-object', 'meaning'],
      instruction: 'Match each verb to how it is used in this chapter.',
      prompt: 'Ordne jedes Verb der passenden Verwendung zu.',
      pairs: [
        { id: 'p1', left: 'sich beeilen', right: 'to hurry (always reflexive)' },
        { id: 'p2', left: 'sich erkälten', right: 'to catch a cold (always reflexive)' },
        { id: 'p3', left: 'sich setzen', right: 'to sit down (reflexive use of setzen)' },
        { id: 'p4', left: 'sich vorstellen', right: 'to introduce oneself (reflexive use of vorstellen)' },
        { id: 'p5', left: 'sich anziehen', right: 'to get dressed (reflexive use of anziehen)' },
      ],
      explanation: 'some verbs are truly reflexive with no other use, while others share a verb with a non-reflexive meaning and add a reflexive one.',
    },
    {
      id: 'ch31-ex-49',
      chapterNumber: 31,
      order: 49,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['reflexive-agreement', 'error-correction'],
      instruction: 'Find the token with the reflexive-pronoun error.',
      prompt: 'Wir interessieren sich für Kunst.',
      tokens: ['Wir', 'interessieren', 'sich', 'für', 'Kunst', '.'],
      errorTokenIndex: 2,
      correction: 'uns',
      explanation: 'the reflexive pronoun must agree with the subject; wir takes uns, not the third-person sich.',
    },
    {
      id: 'ch31-ex-50',
      chapterNumber: 31,
      order: 50,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'er', 'sentence-choice'],
      instruction: 'Choose the grammatically correct sentence.',
      prompt: 'Welcher Satz ist grammatisch richtig?',
      options: [
        { id: 'a', text: 'Er interessiert sich für Sport.' },
        { id: 'b', text: 'Er interessiert dich für Sport.' },
        { id: 'c', text: 'Er interessieren sich für Sport.' },
        { id: 'd', text: 'Er interessiert ihn für Sport.' },
      ],
      correctOptionId: 'a',
      explanation: 'er requires the third-person singular verb form interessiert and the reflexive pronoun sich; dich and ihn belong to other persons, and interessieren is the wrong verb form for er.',
    },
    {
      id: 'ch31-ex-51',
      chapterNumber: 31,
      order: 51,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'wir', 'body-part-verb'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wir putzen ___ die Zähne nach dem Essen. (wir)',
      acceptedAnswers: ['uns'],
      answerMode: 'caseInsensitive',
      placeholder: 'uns',
      maxLength: 10,
      explanation: 'die Zähne is the accusative object, so wir takes the dative reflexive pronoun, which has the same form as the accusative: uns.',
    },
    {
      id: 'ch31-ex-52',
      chapterNumber: 31,
      order: 52,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'er'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Er tut ___ beim Fußball oft weh.',
      templateParts: ['Er tut ', ' beim Fußball oft weh.'],
      slots: [{ id: 's1', correctWord: 'sich' }],
      wordBank: ['sich', 'ihm', 'ihn', 'er'],
      explanation: 'sich weh tun governs the dative, but the third-person reflexive pronoun is sich for both cases, not the personal dative pronoun ihm.',
    },
    {
      id: 'ch31-ex-53',
      chapterNumber: 31,
      order: 53,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'body-part-verb'],
      instruction: 'Match each subject-and-verb cue to its correct dative reflexive pronoun.',
      prompt: 'Ordne jeden Hinweis dem passenden Reflexivpronomen (Dativ) zu.',
      pairs: [
        { id: 'p1', left: 'ich (die Zähne putzen)', right: 'mir' },
        { id: 'p2', left: 'du (die Hände waschen)', right: 'dir' },
        { id: 'p3', left: 'wir (die Haare kämmen)', right: 'uns' },
        { id: 'p4', left: 'ihr (weh tun)', right: 'euch' },
        { id: 'p5', left: 'er/sie/es/sie (Pl.)/Sie', right: 'sich' },
      ],
      explanation: 'the dative reflexive pronouns are identical to the accusative ones except for ich (mir, not mich) and du (dir, not dich).',
    },
    {
      id: 'ch31-ex-54',
      chapterNumber: 31,
      order: 54,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['reflexive pronoun', 'dative', 'error-correction', 'body-part-verb'],
      instruction: 'Find the token with the reflexive-pronoun error.',
      prompt: 'Er wäscht ihm die Hände.',
      tokens: ['Er', 'wäscht', 'ihm', 'die', 'Hände', '.'],
      errorTokenIndex: 2,
      correction: 'sich',
      explanation: 'the dative reflexive pronoun for the third person is sich, not the personal dative pronoun ihm.',
    },
    {
      id: 'ch31-ex-55',
      chapterNumber: 31,
      order: 55,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['daily-routine', 'sentence-choice'],
      instruction: 'Choose the sentence that correctly describes the daily routine.',
      prompt: 'Welcher Satz beschreibt richtig die Alltagsroutine?',
      options: [
        { id: 'a', text: 'Ich stehe auf, dusche mich und ziehe mich an.' },
        { id: 'b', text: 'Ich stehe mich auf, dusche und ziehe an.' },
        { id: 'c', text: 'Ich stehe auf, dusche sich und ziehe mich an.' },
        { id: 'd', text: 'Ich stehe auf, dusche mir und ziehe dich an.' },
      ],
      correctOptionId: 'a',
      explanation: 'aufstehen is not reflexive, while sich duschen and sich anziehen both need the reflexive pronoun mich for ich.',
    },
    {
      id: 'ch31-ex-56',
      chapterNumber: 31,
      order: 56,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'reciprocal', 'dative', 'wir'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wir helfen ___ immer gegenseitig. (wir)',
      acceptedAnswers: ['uns'],
      answerMode: 'caseInsensitive',
      placeholder: 'uns',
      maxLength: 10,
      explanation: 'sich helfen governs the dative and has a reciprocal meaning here ("we always help each other"); for wir the dative reflexive form is uns, same as the accusative.',
    },
    {
      id: 'ch31-ex-57',
      chapterNumber: 31,
      order: 57,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'Sie-formal'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Möchten Sie ___ kurz vorstellen, bevor wir anfangen?',
      templateParts: ['Möchten Sie ', ' kurz vorstellen, bevor wir anfangen?'],
      slots: [{ id: 's1', correctWord: 'sich' }],
      wordBank: ['sich', 'Ihnen', 'euch', 'uns'],
      explanation: 'the formal Sie always takes the reflexive pronoun sich, whether accusative or dative.',
    },
    {
      id: 'ch31-ex-58',
      chapterNumber: 31,
      order: 58,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['reflexive-vs-reciprocal', 'translation'],
      instruction: 'Match each German sentence to its correct English translation.',
      prompt: 'Ordne jeden deutschen Satz der passenden englischen Übersetzung zu.',
      pairs: [
        { id: 'p1', left: 'Wir waschen uns.', right: 'We wash ourselves.' },
        { id: 'p2', left: 'Wir umarmen uns.', right: 'We hug each other.' },
        { id: 'p3', left: 'Ihr kennt euch.', right: 'You know each other.' },
        { id: 'p4', left: 'Ihr wascht euch.', right: 'You wash yourselves.' },
        { id: 'p5', left: 'Sie treffen sich.', right: 'They meet each other.' },
      ],
      explanation: 'the same reflexive pronoun forms can be reflexive ("themselves") or reciprocal ("each other") depending on the verb and context.',
    },
    {
      id: 'ch31-ex-59',
      chapterNumber: 31,
      order: 59,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['reflexive-agreement', 'error-correction'],
      instruction: 'Find the token with the reflexive-pronoun error.',
      prompt: 'Ihr wascht sich jeden Tag.',
      tokens: ['Ihr', 'wascht', 'sich', 'jeden', 'Tag', '.'],
      errorTokenIndex: 2,
      correction: 'euch',
      explanation: 'the reflexive pronoun must agree with the subject; ihr takes euch, not the third-person sich.',
    },
    {
      id: 'ch31-ex-60',
      chapterNumber: 31,
      order: 60,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'man'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Man freut ___ über gutes Wetter. (man)',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'man' },
        { id: 'c', text: 'ihm' },
        { id: 'd', text: 'ihn' },
      ],
      correctOptionId: 'a',
      explanation: 'the indefinite pronoun man also takes the third-person reflexive pronoun sich.',
    },
    {
      id: 'ch31-ex-61',
      chapterNumber: 31,
      order: 61,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'accusative-vs-dative', 'sentence-choice'],
      instruction: 'Choose the grammatically correct sentence.',
      prompt: 'Welcher Satz ist richtig?',
      options: [
        { id: 'a', text: 'Ich dusche mich und putze mir die Zähne.' },
        { id: 'b', text: 'Ich dusche mir und putze mich die Zähne.' },
        { id: 'c', text: 'Ich dusche mich und putze mich die Zähne.' },
        { id: 'd', text: 'Ich dusche mir und putze mir die Zähne.' },
      ],
      correctOptionId: 'a',
      explanation: 'sich duschen has no other object, so it takes the accusative mich; sich die Zähne putzen already has die Zähne as its accusative object, so the reflexive pronoun there must be the dative mir.',
    },
    {
      id: 'ch31-ex-62',
      chapterNumber: 31,
      order: 62,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['truly-reflexive-vs-object', 'sich setzen'],
      instruction: 'Choose the sentence in which "setzen" is NOT used reflexively.',
      prompt: 'Welcher Satz benutzt "setzen" NICHT reflexiv?',
      options: [
        { id: 'a', text: 'Ich setze mich auf den Stuhl.' },
        { id: 'b', text: 'Ich setze die Tasse auf den Tisch.' },
        { id: 'c', text: 'Wir setzen uns an den Tisch.' },
        { id: 'd', text: 'Setzt euch bitte!' },
      ],
      correctOptionId: 'b',
      explanation: 'Ich setze die Tasse auf den Tisch has a different accusative object (die Tasse), so setzen is used non-reflexively there; the other sentences all use the reflexive sich setzen (to sit down).',
    },
    {
      id: 'ch31-ex-63',
      chapterNumber: 31,
      order: 63,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['truly-reflexive-vs-object', 'sich vorstellen'],
      instruction: 'Choose the sentence that means "to introduce oneself".',
      prompt: 'Welcher Satz bedeutet "to introduce oneself"?',
      options: [
        { id: 'a', text: 'Ich stelle meinen Freund vor.' },
        { id: 'b', text: 'Ich stelle mich vor.' },
        { id: 'c', text: 'Ich stelle dich vor.' },
        { id: 'd', text: 'Ich stelle es vor.' },
      ],
      correctOptionId: 'b',
      explanation: 'Ich stelle mich vor uses the reflexive pronoun mich, meaning the subject introduces itself; the other options introduce someone or something else and are not reflexive.',
    },
    {
      id: 'ch31-ex-64',
      chapterNumber: 31,
      order: 64,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'reciprocal', 'ihr'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ruft ihr ___ jeden Abend an? (ihr, reziprok)',
      acceptedAnswers: ['euch'],
      answerMode: 'caseInsensitive',
      placeholder: 'euch',
      maxLength: 10,
      explanation: 'sich anrufen with ihr has a reciprocal meaning ("do you call each other"), and ihr takes euch.',
    },
    {
      id: 'ch31-ex-65',
      chapterNumber: 31,
      order: 65,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['reflexive-vs-personal-pronoun', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Er zieht ihn schnell an.',
      acceptedAnswers: ['Er zieht sich schnell an.'],
      answerMode: 'normalized',
      placeholder: 'Er zieht ...',
      maxLength: 40,
      explanation: 'a reflexive meaning ("he gets dressed") needs the reflexive pronoun sich, not the personal accusative pronoun ihn, which would wrongly refer to someone else.',
    },
    {
      id: 'ch31-ex-66',
      chapterNumber: 31,
      order: 66,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['reflexive pronoun', 'dative', 'error-correction', 'body-part-verb'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Du putzt dich die Zähne.',
      acceptedAnswers: ['Du putzt dir die Zähne.'],
      answerMode: 'normalized',
      placeholder: 'Du putzt ...',
      maxLength: 40,
      explanation: 'die Zähne is the accusative object, so du needs the dative reflexive pronoun dir, not the accusative dich.',
    },
    {
      id: 'ch31-ex-67',
      chapterNumber: 31,
      order: 67,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'sie-plural', 'body-part-verb'],
      instruction: 'Drag the correct reflexive pronoun into the slot.',
      prompt: 'Die Kinder kämmen ___ die Haare vor der Schule.',
      templateParts: ['Die Kinder kämmen ', ' die Haare vor der Schule.'],
      slots: [{ id: 's1', correctWord: 'sich' }],
      wordBank: ['sich', 'ihnen', 'ihre', 'euch'],
      explanation: 'die Kinder = sie (Plural); the third-person dative reflexive pronoun is sich (same as accusative), not the personal dative pronoun ihnen.',
    },
  ],
};
