import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter074: ChapterDefinition = {
  id: 'chapter-074',
  number: 74,
  slug: 'infinitive-constructions-without-zu',
  title: 'Infinitive Constructions without zu',
  germanTitle: 'Infinitivsätze ohne zu',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Recognize the closed group of German verbs — modal verbs, lassen, the movement verbs gehen/kommen/fahren in fixed activity combinations, the perception verbs sehen/hören/fühlen, and the verbs lernen/lehren — that send a bare infinitive (no zu) to the end of the clause, and reliably tell these apart from the much larger group of verbs (versuchen, hoffen, beginnen, and the like) that require a zu-infinitive.',
  prerequisites: [5, 66],
  estimatedMinutes: 30,
  tags: [
    'infinitive-constructions',
    'bare-infinitive',
    'modal-verbs',
    'lassen',
    'movement-verbs',
    'perception-verbs',
    'accusative-with-infinitive',
    'lernen-lehren',
    'zu-infinitive-contrast',
    'b1-syntax',
  ],
  explanation: {
    introduction: [
      'German has two completely different ways of attaching a second verb to a sentence. Most verbs that introduce another action — versuchen (to try), hoffen (to hope), beginnen (to begin), vergessen (to forget), planen (to plan) — require that second verb to appear as a zu-infinitive: Ich versuche, früh aufzustehen (I am trying to get up early). But a small, closed group of verbs does the opposite: they send a bare infinitive, with no zu at all, straight to the end of the clause, forming the same verb bracket (Satzklammer) you already know from the modal verbs.',
      'You met the first two members of this group already. Chapter 5 introduced können, müssen, wollen, sollen, dürfen, and mögen, all of which conjugate in position 2 and push a bare infinitive to the end: Ich kann schwimmen. Chapter 66 introduced lassen, which behaves exactly like a modal verb even though it is not one: Ich lasse mein Auto reparieren. This chapter completes the picture by adding three more verb categories that follow the same bare-infinitive pattern: the movement verbs gehen, kommen, and fahren in fixed activity combinations (Ich gehe einkaufen), the perception verbs sehen, hören, and fühlen describing something you directly perceive happening (Ich höre ihn singen), and the verbs lernen and lehren when they name a skill directly (Sie lernt schwimmen).',
      'The key skill in this chapter is not producing any single sentence correctly — you likely can already — but reliably sorting a governing verb into the right bucket. If the verb in front of the infinitive is one of this closed list, the infinitive stays bare and moves to the end. If it is anything else, you almost certainly need zu. Confusing the two directions produces some of the most common intermediate-level mistakes in German: adding zu after a modal verb or lassen, or dropping zu after versuchen or hoffen.',
    ],
    rules: [
      {
        id: 'ch74-rule-01',
        heading: 'Modal verbs: bare infinitive at the end (recap)',
        paragraphs: [
          'können, müssen, wollen, sollen, dürfen, and mögen conjugate for person and occupy position 2, while the accompanying infinitive — never marked with zu — is sent all the way to the end of the clause: Ich kann schwimmen. Wir müssen jetzt gehen. Sie will Ärztin werden.',
          'This is the pattern all the other bare-infinitive verbs in this chapter imitate. If you remember the modal-verb word order from chapter 5, you already know the shape of every construction covered here: conjugated verb in position 2, bare infinitive at the very end.',
        ],
      },
      {
        id: 'ch74-rule-02',
        heading: 'lassen + bare infinitive (recap)',
        paragraphs: [
          'lassen is not one of the six true modal verbs, but it behaves identically in the sentence: it conjugates in position 2 and sends a bare infinitive to the end, expressing allowing, causing/arranging for something to be done, or leaving something as it is. Ich lasse mein Auto reparieren (I am having my car repaired). Er lässt mich fahren (He lets me drive).',
          'As with the modal verbs, zu never appears before the infinitive that follows lassen: Ich lasse mein Auto reparieren, never "...zu reparieren." See chapter 66 for the full range of meanings and the perfect-tense double-infinitive pattern.',
        ],
      },
      {
        id: 'ch74-rule-03',
        heading: 'Movement verbs + bare infinitive: gehen, kommen, fahren',
        paragraphs: [
          'When gehen, kommen, or fahren are combined with an activity that describes the purpose of the movement, the activity appears as a bare infinitive directly before the movement verb\'s final position — with no zu and no "um...zu": Ich gehe einkaufen (I\'m going shopping). Wir gehen schwimmen (We\'re going swimming). Er kommt mich besuchen (He\'s coming to visit me). Wir fahren einkaufen (We\'re driving to go shopping).',
          'This pattern is limited to a fairly fixed, everyday set of activity combinations — einkaufen gehen, schwimmen gehen, essen gehen, spazieren gehen, tanzen gehen, besuchen kommen, abholen kommen, and similar pairs. It is not a fully open pattern the way modal verbs are; you are essentially learning set expressions built on this bare-infinitive template.',
          'Do not confuse this with the um...zu construction, which expresses purpose with a full subordinate-clause-like structure (Ich gehe in die Stadt, um einzukaufen). The gehen/kommen/fahren + bare infinitive pattern is more compact and only works with this small set of activity verbs directly attached to the movement verb.',
        ],
      },
      {
        id: 'ch74-rule-04',
        heading: 'Perception verbs + bare infinitive: sehen, hören, fühlen',
        paragraphs: [
          'sehen, hören, and fühlen can take an accusative object plus a bare infinitive to describe something you directly perceive happening — a pattern sometimes called the accusative-with-infinitive (AcI) construction. Ich höre ihn singen (I hear him sing / singing). Ich sehe sie kommen (I see her coming). Ich fühle mein Herz schlagen (I feel my heart beating).',
          'The accusative object (ihn, sie, mein Herz) is the person or thing performing the perceived action, and the bare infinitive at the end names that action. English sometimes uses "-ing" here and sometimes "to," but German always uses the plain infinitive — never zu.',
        ],
      },
      {
        id: 'ch74-rule-05',
        heading: 'Learning and teaching verbs + bare infinitive: lernen, lehren',
        paragraphs: [
          'lernen and lehren also take a bare infinitive when they name a skill directly, without any further elaboration: Sie lernt schwimmen (She is learning to swim). Er lehrt mich schwimmen (He teaches me to swim, or: He is teaching me how to swim).',
          'Like sehen and hören, lehren can take an accusative object (mich) that identifies who is being taught, with the bare infinitive following at the end. If lernen or lehren is followed by a more complex idea rather than a single named skill, a zu-infinitive clause is often used instead (Er lehrt mich, geduldig zu sein) — but for a directly named skill, the bare infinitive is standard.',
        ],
      },
      {
        id: 'ch74-rule-06',
        heading: 'With zu vs. without zu: the key contrast',
        paragraphs: [
          'German infinitive constructions split into two groups. A small, closed group of governing verbs — the modal verbs, lassen, gehen/kommen/fahren in fixed activity combinations, sehen/hören/fühlen, and lernen/lehren — take a bare infinitive sent to the end of the clause, exactly like a modal verb. Every other verb that introduces a following infinitive — versuchen, hoffen, beginnen, vergessen, planen, vorhaben, and the vast majority of German verbs — requires a zu-infinitive: Ich versuche zu schwimmen (I am trying to swim), never "Ich versuche schwimmen."',
          'A reliable strategy: if you are not sure whether a governing verb needs zu, check whether it belongs to this short, closed list from chapter 74. If it does, use the bare infinitive. If it does not, default to zu — the zu-infinitive group is by far the larger and more general pattern in German.',
          'The two patterns are never mixed: a governing verb either always takes zu or never does. Ich kann zu schwimmen and Ich versuche schwimmen are both ungrammatical for the same reason in opposite directions — each governing verb belongs to only one of the two groups.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch74-table-01',
        title: 'Verbs that take a bare infinitive (no zu)',
        columns: ['Category', 'Verbs', 'Example', 'English'],
        rows: [
          ['Modal verbs', 'können, müssen, wollen, sollen, dürfen, mögen', 'Ich kann schwimmen.', 'I can swim.'],
          ['Causative', 'lassen', 'Ich lasse mein Auto reparieren.', 'I am having my car repaired.'],
          ['Movement + activity', 'gehen, kommen, fahren', 'Ich gehe einkaufen.', "I'm going shopping."],
          ['Perception', 'sehen, hören, fühlen', 'Ich höre ihn singen.', 'I hear him sing / singing.'],
          ['Learning / teaching', 'lernen, lehren', 'Sie lernt schwimmen.', 'She is learning to swim.'],
        ],
        note: 'This is a closed, memorizable list — unlike the open-ended group of verbs that require zu.',
      },
      {
        id: 'ch74-table-02',
        title: 'zu-infinitive vs. bare infinitive: side-by-side contrast',
        columns: ['Governing verb', 'Construction', 'Example', 'English'],
        rows: [
          ['versuchen (to try)', 'zu + infinitive', 'Ich versuche zu schwimmen.', 'I am trying to swim.'],
          ['können (modal)', 'bare infinitive', 'Ich kann schwimmen.', 'I can swim.'],
          ['hoffen (to hope)', 'zu + infinitive', 'Er hofft, mich bald zu besuchen.', 'He hopes to visit me soon.'],
          ['lassen (causative)', 'bare infinitive', 'Ich lasse ihn schwimmen.', 'I let him swim.'],
          ['beginnen (to begin)', 'zu + infinitive', 'Er beginnt zu schwimmen.', 'He starts to swim.'],
          ['sehen (perception)', 'bare infinitive', 'Ich sehe ihn schwimmen.', 'I see him swim / swimming.'],
        ],
        note: 'The governing verb decides the whole pattern: it either always requires zu or never allows it.',
      },
      {
        id: 'ch74-table-03',
        title: 'Common movement + bare-infinitive combinations',
        columns: ['Combination', 'Example sentence', 'English'],
        rows: [
          ['einkaufen gehen', 'Ich gehe einkaufen.', "I'm going shopping."],
          ['schwimmen gehen', 'Wir gehen schwimmen.', 'We are going swimming.'],
          ['essen gehen', 'Gehst du heute essen?', 'Are you going out to eat today?'],
          ['spazieren gehen', 'Sie geht spazieren.', 'She is going for a walk.'],
          ['besuchen kommen', 'Er kommt mich besuchen.', 'He is coming to visit me.'],
          ['abholen kommen', 'Meine Mutter kommt mich abholen.', 'My mother is coming to pick me up.'],
          ['einkaufen fahren', 'Wir fahren einkaufen.', "We're driving to go shopping."],
        ],
      },
    ],
    examples: [
      {
        german: 'Ich kann gut schwimmen.',
        english: 'I can swim well.',
        highlight: ['kann', 'schwimmen'],
        explanation: 'Modal verb kann in position 2, bare infinitive schwimmen at the end — no zu.',
      },
      {
        german: 'Er muss früh aufstehen.',
        english: 'He has to get up early.',
        highlight: ['muss', 'aufstehen'],
        explanation: 'Modal verb muss with the bare infinitive aufstehen at the end.',
      },
      {
        german: 'Ich lasse mein Auto reparieren.',
        english: 'I am having my car repaired.',
        highlight: ['lasse', 'reparieren'],
        explanation: 'lassen behaves like a modal verb: bare infinitive, no zu.',
      },
      {
        german: 'Er lässt mich fahren.',
        english: 'He lets me drive.',
        highlight: ['lässt', 'fahren'],
        explanation: 'Another lassen example: the bare infinitive fahren at the end of the clause.',
      },
      {
        german: 'Ich gehe einkaufen.',
        english: "I'm going shopping.",
        highlight: ['gehe', 'einkaufen'],
        explanation: 'Movement verb gehen + bare infinitive einkaufen, a fixed activity combination.',
      },
      {
        german: 'Er kommt mich besuchen.',
        english: 'He is coming to visit me.',
        highlight: ['kommt', 'besuchen'],
        explanation: 'Movement verb kommen + bare infinitive besuchen, with the accusative object mich in between.',
      },
      {
        german: 'Wir fahren einkaufen.',
        english: "We're driving to go shopping.",
        highlight: ['fahren', 'einkaufen'],
        explanation: 'Movement verb fahren + bare infinitive einkaufen, the same fixed pattern as gehen and kommen.',
      },
      {
        german: 'Ich höre ihn singen.',
        english: 'I hear him sing / singing.',
        highlight: ['höre', 'ihn', 'singen'],
        explanation: 'Perception verb hören + accusative object ihn + bare infinitive singen (accusative-with-infinitive).',
      },
      {
        german: 'Ich sehe sie kommen.',
        english: 'I see her coming.',
        highlight: ['sehe', 'sie', 'kommen'],
        explanation: 'Perception verb sehen + accusative object sie + bare infinitive kommen.',
      },
      {
        german: 'Ich fühle mein Herz klopfen.',
        english: 'I feel my heart pounding.',
        highlight: ['fühle', 'mein Herz', 'klopfen'],
        explanation: 'Perception verb fühlen + accusative object mein Herz + bare infinitive klopfen.',
      },
      {
        german: 'Sie lernt schwimmen.',
        english: 'She is learning to swim.',
        highlight: ['lernt', 'schwimmen'],
        explanation: 'lernen + bare infinitive naming a skill directly, with no zu.',
      },
      {
        german: 'Er lehrt mich schwimmen.',
        english: 'He teaches me to swim.',
        highlight: ['lehrt', 'mich', 'schwimmen'],
        explanation: 'lehren + accusative object mich + bare infinitive schwimmen.',
      },
      {
        german: 'Ich versuche zu schwimmen.',
        english: 'I am trying to swim.',
        highlight: ['versuche', 'zu', 'schwimmen'],
        explanation: 'Contrast: versuchen is not part of the closed bare-infinitive list, so it requires zu.',
      },
      {
        german: 'Er hofft, mich bald zu besuchen.',
        english: 'He hopes to visit me soon.',
        highlight: ['hofft', 'zu', 'besuchen'],
        explanation: 'Contrast: hoffen also requires a zu-infinitive, unlike the verbs covered in this chapter.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich kann zu schwimmen.',
        correct: 'Ich kann schwimmen.',
        explanation: 'Modal verbs always take a bare infinitive — zu must never appear after können, müssen, wollen, sollen, dürfen, or mögen.',
      },
      {
        incorrect: 'Ich lasse mein Auto zu reparieren.',
        correct: 'Ich lasse mein Auto reparieren.',
        explanation: 'lassen behaves exactly like a modal verb and never allows zu before its infinitive.',
      },
      {
        incorrect: 'Ich höre ihn zu singen.',
        correct: 'Ich höre ihn singen.',
        explanation: 'Perception verbs (sehen, hören, fühlen) take a bare infinitive in the accusative-with-infinitive construction — no zu.',
      },
      {
        incorrect: 'Ich gehe zu einkaufen.',
        correct: 'Ich gehe einkaufen.',
        explanation: 'Movement verbs (gehen, kommen, fahren) combine with a bare infinitive in fixed activity expressions like einkaufen gehen — never with zu.',
      },
      {
        incorrect: 'Ich versuche schwimmen.',
        correct: 'Ich versuche zu schwimmen.',
        explanation: 'versuchen is not part of the closed bare-infinitive group; like most German verbs, it requires a zu-infinitive.',
      },
    ],
    remember: [
      'Modal verbs (können, müssen, wollen, sollen, dürfen, mögen) always take a bare infinitive at the end of the clause — never zu.',
      'lassen behaves exactly like a modal verb: bare infinitive, no zu.',
      'gehen, kommen, and fahren combine with a bare infinitive in fixed activity expressions: einkaufen gehen, schwimmen gehen, besuchen kommen.',
      'sehen, hören, and fühlen take a bare infinitive (with an accusative object) to describe something directly perceived happening.',
      'lernen and lehren take a bare infinitive when directly naming the skill being learned or taught: Sie lernt schwimmen.',
      'Every other infinitive-governing verb (versuchen, hoffen, beginnen, vergessen, planen, vorhaben, ...) requires zu — if the governing verb is not in this closed list, default to a zu-infinitive.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 30,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch74-ex-01',
      chapterNumber: 74,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['modal-verbs', 'bare-infinitive'],
      instruction: 'Choose the correct completion.',
      prompt: 'Ich ___ gut schwimmen.',
      options: [
        { id: 'a', text: 'kann' },
        { id: 'b', text: 'kann zu' },
        { id: 'c', text: 'zu können' },
        { id: 'd', text: 'kannst' },
      ],
      correctOptionId: 'a',
      explanation: 'The modal verb kann takes a bare infinitive (schwimmen) — never zu.',
    },
    {
      id: 'ch74-ex-02',
      chapterNumber: 74,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['lassen', 'bare-infinitive'],
      instruction: 'Choose the correct completion.',
      prompt: 'Ich lasse mein Auto ___.',
      options: [
        { id: 'a', text: 'reparieren' },
        { id: 'b', text: 'zu reparieren' },
        { id: 'c', text: 'repariert' },
        { id: 'd', text: 'reparieren zu' },
      ],
      correctOptionId: 'a',
      explanation: 'lassen sends a bare infinitive to the end of the clause, exactly like a modal verb.',
    },
    {
      id: 'ch74-ex-03',
      chapterNumber: 74,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['movement-verbs', 'bare-infinitive'],
      instruction: 'Choose the correct completion.',
      prompt: 'Wir gehen heute Abend ___.',
      options: [
        { id: 'a', text: 'essen' },
        { id: 'b', text: 'zu essen' },
        { id: 'c', text: 'isst' },
        { id: 'd', text: 'gegessen' },
      ],
      correctOptionId: 'a',
      explanation: 'gehen + bare infinitive forms the fixed activity combination essen gehen — no zu.',
    },
    {
      id: 'ch74-ex-04',
      chapterNumber: 74,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['perception-verbs', 'bare-infinitive'],
      instruction: 'Choose the correct completion.',
      prompt: 'Ich höre ihn ___.',
      options: [
        { id: 'a', text: 'singen' },
        { id: 'b', text: 'zu singen' },
        { id: 'c', text: 'singt' },
        { id: 'd', text: 'gesungen' },
      ],
      correctOptionId: 'a',
      explanation: 'hören + accusative object + bare infinitive: Ich höre ihn singen.',
    },
    {
      id: 'ch74-ex-05',
      chapterNumber: 74,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['learning-teaching-verbs', 'bare-infinitive'],
      instruction: 'Choose the correct completion.',
      prompt: 'Sie lernt ___.',
      options: [
        { id: 'a', text: 'schwimmen' },
        { id: 'b', text: 'zu schwimmen' },
        { id: 'c', text: 'schwimmt' },
        { id: 'd', text: 'geschwommen' },
      ],
      correctOptionId: 'a',
      explanation: 'lernen takes a bare infinitive when naming a skill directly: Sie lernt schwimmen.',
    },
    {
      id: 'ch74-ex-06',
      chapterNumber: 74,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-or-no-zu', 'modal-verbs'],
      instruction: 'Choose the sentence with correct zu-usage.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich muss jetzt gehen.' },
        { id: 'b', text: 'Ich muss jetzt zu gehen.' },
        { id: 'c', text: 'Ich muss zu jetzt gehen.' },
        { id: 'd', text: 'Ich muss gehen zu.' },
      ],
      correctOptionId: 'a',
      explanation: 'The modal verb muss takes a bare infinitive at the end — no zu anywhere in the clause.',
    },
    {
      id: 'ch74-ex-07',
      chapterNumber: 74,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-or-no-zu', 'lassen'],
      instruction: 'Choose the sentence with correct zu-usage.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Er lässt mich fahren.' },
        { id: 'b', text: 'Er lässt mich zu fahren.' },
        { id: 'c', text: 'Er lässt zu mich fahren.' },
        { id: 'd', text: 'Er lässt fahren mich.' },
      ],
      correctOptionId: 'a',
      explanation: 'lassen takes a bare infinitive, and the object mich comes before the infinitive at the end.',
    },
    {
      id: 'ch74-ex-08',
      chapterNumber: 74,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-or-no-zu', 'versuchen', 'contrast'],
      instruction: 'Choose the sentence with correct zu-usage.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich versuche zu schwimmen.' },
        { id: 'b', text: 'Ich versuche schwimmen.' },
        { id: 'c', text: 'Ich zu versuche schwimmen.' },
        { id: 'd', text: 'Ich versuche schwimmen zu.' },
      ],
      correctOptionId: 'a',
      explanation: 'versuchen is not in the closed bare-infinitive class, so it requires a zu-infinitive.',
    },
    {
      id: 'ch74-ex-09',
      chapterNumber: 74,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-or-no-zu', 'perception-verbs'],
      instruction: 'Choose the sentence with correct zu-usage.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich sehe sie kommen.' },
        { id: 'b', text: 'Ich sehe sie zu kommen.' },
        { id: 'c', text: 'Ich sehe zu sie kommen.' },
        { id: 'd', text: 'Ich sehe kommen sie.' },
      ],
      correctOptionId: 'a',
      explanation: 'sehen + accusative object + bare infinitive at the end — no zu, and the infinitive stays last.',
    },
    {
      id: 'ch74-ex-10',
      chapterNumber: 74,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['identify-governing-verb', 'movement-verbs'],
      instruction: 'Identify the verb that governs the infinitive construction.',
      prompt: 'In "Er kommt mich morgen besuchen," which verb governs the bare infinitive besuchen?',
      options: [
        { id: 'a', text: 'kommt' },
        { id: 'b', text: 'besuchen' },
        { id: 'c', text: 'morgen' },
        { id: 'd', text: 'mich' },
      ],
      correctOptionId: 'a',
      explanation: 'kommt is the conjugated movement verb in position 2; it governs the bare infinitive besuchen at the end.',
    },
    {
      id: 'ch74-ex-11',
      chapterNumber: 74,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['identify-governing-verb', 'perception-verbs'],
      instruction: 'Identify the verb that governs the infinitive construction.',
      prompt: 'In "Ich höre die Vögel singen," which verb governs the bare infinitive singen?',
      options: [
        { id: 'a', text: 'höre' },
        { id: 'b', text: 'singen' },
        { id: 'c', text: 'Vögel' },
        { id: 'd', text: 'Ich' },
      ],
      correctOptionId: 'a',
      explanation: 'höre is the conjugated perception verb; it governs the accusative-with-infinitive construction die Vögel singen.',
    },
    {
      id: 'ch74-ex-12',
      chapterNumber: 74,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['correcting-errors', 'modal-verbs'],
      instruction: 'Choose the corrected version of the sentence.',
      prompt: 'Incorrect: "Ich will zu reisen." Correct version?',
      options: [
        { id: 'a', text: 'Ich will reisen.' },
        { id: 'b', text: 'Ich will zu reisen.' },
        { id: 'c', text: 'Ich zu will reisen.' },
        { id: 'd', text: 'Ich reisen will zu.' },
      ],
      correctOptionId: 'a',
      explanation: 'The modal verb will never takes zu before its infinitive: Ich will reisen.',
    },
    {
      id: 'ch74-ex-13',
      chapterNumber: 74,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['correcting-errors', 'perception-verbs'],
      instruction: 'Choose the corrected version of the sentence.',
      prompt: 'Incorrect: "Ich höre ihn zu singen." Correct version?',
      options: [
        { id: 'a', text: 'Ich höre ihn singen.' },
        { id: 'b', text: 'Ich höre zu ihn singen.' },
        { id: 'c', text: 'Ich höre ihn singen zu.' },
        { id: 'd', text: 'Ich zu höre ihn singen.' },
      ],
      correctOptionId: 'a',
      explanation: 'hören takes a bare infinitive in the accusative-with-infinitive construction: Ich höre ihn singen.',
    },
    {
      id: 'ch74-ex-14',
      chapterNumber: 74,
      order: 14,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['correcting-errors', 'contrast', 'hoffen'],
      instruction: 'Choose the corrected version of the sentence.',
      prompt: 'Incorrect: "Er hofft mich bald besuchen." Correct version?',
      options: [
        { id: 'a', text: 'Er hofft, mich bald zu besuchen.' },
        { id: 'b', text: 'Er hofft mich bald besuchen.' },
        { id: 'c', text: 'Er hofft zu mich bald besuchen.' },
        { id: 'd', text: 'Er hofft mich bald zu besuchen zu.' },
      ],
      correctOptionId: 'a',
      explanation: 'hoffen requires a zu-infinitive, unlike the closed group of bare-infinitive verbs.',
    },
    {
      id: 'ch74-ex-15',
      chapterNumber: 74,
      order: 15,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['movement-verbs', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'He is coming to visit me.',
      options: [
        { id: 'a', text: 'Er kommt mich besuchen.' },
        { id: 'b', text: 'Er kommt zu mich besuchen.' },
        { id: 'c', text: 'Er kommt besuchen mich.' },
        { id: 'd', text: 'Er mich kommt besuchen.' },
      ],
      correctOptionId: 'a',
      explanation: 'kommt occupies position 2, the accusative object mich follows, and the bare infinitive besuchen ends the clause.',
    },
    {
      id: 'ch74-ex-16',
      chapterNumber: 74,
      order: 16,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['zu-or-no-zu', 'overview'],
      instruction: 'Choose the correct general rule.',
      prompt: 'Which group of verbs always takes a bare infinitive (no zu)?',
      options: [
        { id: 'a', text: 'Modal verbs, lassen, gehen/kommen/fahren in fixed combinations, sehen/hören/fühlen, lernen/lehren' },
        { id: 'b', text: 'versuchen, hoffen, beginnen, vergessen' },
        { id: 'c', text: 'All German verbs that are followed by another verb' },
        { id: 'd', text: 'Only strong verbs' },
      ],
      correctOptionId: 'a',
      explanation: 'This closed list — modals, lassen, gehen/kommen/fahren, sehen/hören/fühlen, lernen/lehren — is exactly the group covered in this chapter; every other verb requires zu.',
    },
    {
      id: 'ch74-ex-17',
      chapterNumber: 74,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['modal-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Er muss jeden Tag früh ___. (aufstehen)',
      acceptedAnswers: ['aufstehen'],
      answerMode: 'caseInsensitive',
      placeholder: 'aufstehen',
      maxLength: 20,
      explanation: 'The modal verb muss governs the bare infinitive aufstehen at the end of the clause.',
    },
    {
      id: 'ch74-ex-18',
      chapterNumber: 74,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['lassen', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Ich lasse mein Fahrrad ___. (reparieren)',
      acceptedAnswers: ['reparieren'],
      answerMode: 'caseInsensitive',
      placeholder: 'reparieren',
      maxLength: 20,
      explanation: 'lassen governs the bare infinitive reparieren — the causative meaning of lassen.',
    },
    {
      id: 'ch74-ex-19',
      chapterNumber: 74,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['movement-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Wir gehen heute Nachmittag ___. (schwimmen)',
      acceptedAnswers: ['schwimmen'],
      answerMode: 'caseInsensitive',
      placeholder: 'schwimmen',
      maxLength: 20,
      explanation: 'gehen + bare infinitive forms the fixed activity combination schwimmen gehen.',
    },
    {
      id: 'ch74-ex-20',
      chapterNumber: 74,
      order: 20,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['movement-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Meine Oma kommt mich am Sonntag ___. (besuchen)',
      acceptedAnswers: ['besuchen'],
      answerMode: 'caseInsensitive',
      placeholder: 'besuchen',
      maxLength: 20,
      explanation: 'kommen + bare infinitive: besuchen kommen, expressing the purpose of coming.',
    },
    {
      id: 'ch74-ex-21',
      chapterNumber: 74,
      order: 21,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['movement-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Wir fahren am Samstag ___. (einkaufen)',
      acceptedAnswers: ['einkaufen'],
      answerMode: 'caseInsensitive',
      placeholder: 'einkaufen',
      maxLength: 20,
      explanation: 'fahren + bare infinitive: einkaufen fahren, the same fixed pattern as gehen and kommen.',
    },
    {
      id: 'ch74-ex-22',
      chapterNumber: 74,
      order: 22,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['perception-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Ich höre die Kinder im Garten ___. (spielen)',
      acceptedAnswers: ['spielen'],
      answerMode: 'caseInsensitive',
      placeholder: 'spielen',
      maxLength: 20,
      explanation: 'hören + accusative object (die Kinder) + bare infinitive spielen.',
    },
    {
      id: 'ch74-ex-23',
      chapterNumber: 74,
      order: 23,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['perception-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Ich sehe ihn jeden Morgen zur Arbeit ___. (gehen)',
      acceptedAnswers: ['gehen'],
      answerMode: 'caseInsensitive',
      placeholder: 'gehen',
      maxLength: 20,
      explanation: 'sehen + accusative object (ihn) + bare infinitive gehen.',
    },
    {
      id: 'ch74-ex-24',
      chapterNumber: 74,
      order: 24,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['perception-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Ich fühle mein Herz schnell ___. (schlagen)',
      acceptedAnswers: ['schlagen'],
      answerMode: 'caseInsensitive',
      placeholder: 'schlagen',
      maxLength: 20,
      explanation: 'fühlen + accusative object (mein Herz) + bare infinitive schlagen.',
    },
    {
      id: 'ch74-ex-25',
      chapterNumber: 74,
      order: 25,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['learning-teaching-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Mein kleiner Bruder lernt gerade ___. (lesen)',
      acceptedAnswers: ['lesen'],
      answerMode: 'caseInsensitive',
      placeholder: 'lesen',
      maxLength: 20,
      explanation: 'lernen + bare infinitive names the skill being learned directly: lesen lernen.',
    },
    {
      id: 'ch74-ex-26',
      chapterNumber: 74,
      order: 26,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['learning-teaching-verbs', 'fill-in'],
      instruction: 'Complete the sentence with the correct bare infinitive. Capitalisation is not checked.',
      prompt: 'Meine Mutter lehrt mich ___. (kochen)',
      acceptedAnswers: ['kochen'],
      answerMode: 'caseInsensitive',
      placeholder: 'kochen',
      maxLength: 20,
      explanation: 'lehren + accusative object (mich) + bare infinitive kochen.',
    },
    {
      id: 'ch74-ex-27',
      chapterNumber: 74,
      order: 27,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-building', 'modal-verbs'],
      instruction: 'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'ich – müssen (Präsens) – jetzt – gehen',
      acceptedAnswers: ['Ich muss jetzt gehen.', 'Ich muss jetzt gehen'],
      answerMode: 'normalized',
      placeholder: 'Ich muss jetzt gehen.',
      maxLength: 30,
      explanation: 'müssen conjugates to muss for ich, and the bare infinitive gehen goes to the end: Ich muss jetzt gehen.',
    },
    {
      id: 'ch74-ex-28',
      chapterNumber: 74,
      order: 28,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-building', 'lassen'],
      instruction: 'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'er – lassen (Präsens) – sein Auto – reparieren',
      acceptedAnswers: ['Er lässt sein Auto reparieren.', 'Er lässt sein Auto reparieren'],
      answerMode: 'normalized',
      placeholder: 'Er lässt sein Auto reparieren.',
      maxLength: 40,
      explanation: 'lassen conjugates to lässt for er, and the bare infinitive reparieren goes to the end.',
    },
    {
      id: 'ch74-ex-29',
      chapterNumber: 74,
      order: 29,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['translation', 'movement-verbs'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: "I'm going shopping.",
      acceptedAnswers: ['Ich gehe einkaufen.', 'Ich gehe einkaufen'],
      answerMode: 'normalized',
      placeholder: 'Ich gehe einkaufen.',
      maxLength: 30,
      explanation: 'gehen + bare infinitive einkaufen: the fixed activity combination einkaufen gehen.',
    },
    {
      id: 'ch74-ex-30',
      chapterNumber: 74,
      order: 30,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['translation', 'perception-verbs'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: 'I hear him singing.',
      acceptedAnswers: ['Ich höre ihn singen.', 'Ich höre ihn singen'],
      answerMode: 'normalized',
      placeholder: 'Ich höre ihn singen.',
      maxLength: 30,
      explanation: 'hören + accusative object ihn + bare infinitive singen at the end.',
    },
    {
      id: 'ch74-ex-31',
      chapterNumber: 74,
      order: 31,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['correcting-errors', 'contrast', 'modal-verbs'],
      instruction: 'Rewrite the sentence correctly, fixing the zu-error. Capitalisation and punctuation are checked.',
      prompt: 'Fix: "Ich kann zu schwimmen."',
      acceptedAnswers: ['Ich kann schwimmen.', 'Ich kann schwimmen'],
      answerMode: 'normalized',
      placeholder: 'Ich kann schwimmen.',
      maxLength: 25,
      explanation: 'Modal verbs never take zu before the infinitive: Ich kann schwimmen.',
    },
    {
      id: 'ch74-ex-32',
      chapterNumber: 74,
      order: 32,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['correcting-errors', 'contrast', 'versuchen'],
      instruction: 'Rewrite the sentence correctly, adding zu where needed. Capitalisation and punctuation are checked.',
      prompt: 'Fix: "Ich versuche schwimmen."',
      acceptedAnswers: ['Ich versuche zu schwimmen.', 'Ich versuche zu schwimmen'],
      answerMode: 'normalized',
      placeholder: 'Ich versuche zu schwimmen.',
      maxLength: 30,
      explanation: 'versuchen is not part of the closed bare-infinitive list, so it requires a zu-infinitive: Ich versuche zu schwimmen.',
    },
  ],
};
