import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter072: ChapterDefinition = {
  id: 'chapter-072',
  number: 72,
  slug: 'indirect-questions',
  title: 'Indirect Questions',
  germanTitle: 'Indirekte Fragesätze',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Embed a question inside a larger sentence by keeping the question word (wer, was, wann, wo, wie, warum...) and sending the finite verb to the end, or by supplying ob when the original question has no question word, punctuating correctly depending on whether the whole sentence is a statement or a question, and using indirect questions as a strategy for polite requests for information.',
  prerequisites: [10, 11, 46],
  estimatedMinutes: 30,
  tags: [
    'indirect-questions',
    'indirekte-fragesaetze',
    'ob',
    'question-words',
    'verb-final-word-order',
    'subordinate-clauses',
    'politeness',
    'reported-questions',
    'w-questions',
    'punctuation',
  ],
  explanation: {
    introduction: [
      "A direct question stands on its own, with the verb either in position 2 after a question word (Wo wohnst du?) or in position 1 for a yes/no question (Kommst du mit?). An indirect question is different: it is not asked on its own but embedded inside a larger sentence, introduced by a phrase like Ich weiß nicht, ..., Können Sie mir sagen, ..., or Ich frage mich, .... Once a question is folded into a sentence this way, it behaves exactly like the subordinate clauses you already know from weil, wenn, and dass (Chapter 46): the finite verb moves all the way to the end of its own clause, and a comma separates it from the introductory clause.",
      'Indirect questions come in two shapes, depending on the original direct question. If the direct question has a question word (wer, was, wann, wo, wie, warum, wohin, woher, wie viel, wie lange, welche...), that same question word is kept and now also functions as the subordinating conjunction: Wo wohnst du? becomes ..., wo du wohnst. If the direct question has no question word — a yes/no question like Kommst du mit? — German cannot simply drop the question and leave nothing behind, so it inserts ob (whether/if) to do the job a question word would otherwise do: ..., ob du mitkommst. In both cases the verb-final rule applies exactly as it did for weil, wenn, and dass.',
      "Punctuation follows the sentence as a whole, not the embedded question. Ich weiß nicht, wo der Bahnhof ist. ends with a period, because Ich weiß nicht is a statement — even though it contains a question inside it, that inner question no longer has its own question mark. But Können Sie mir sagen, wo der Bahnhof ist? ends with a question mark, because the introductory clause Können Sie mir sagen ...? is itself a genuine question. This last pattern — wrapping a blunt direct question inside a polite introductory phrase — is one of the most common and useful jobs indirect questions do in everyday German: Wo ist der Bahnhof? sounds abrupt to a stranger, while Können Sie mir sagen, wo der Bahnhof ist? sounds like a courteous request.",
    ],
    rules: [
      {
        id: 'ch72-rule-01',
        heading: 'What an indirect question is, and how it is introduced',
        paragraphs: [
          'An indirect question embeds a question inside a larger sentence instead of asking it directly. It is introduced by a main clause — a statement, a request, or a question of its own — followed by a comma and the embedded question: Ich weiß nicht, wo er wohnt. Common introductory phrases include Ich weiß (nicht), ..., Ich frage mich, ... (I wonder ...), Ich möchte wissen, ..., Weißt du, ...?, Können Sie mir sagen, ...?, and Er/Sie hat gefragt, ... for reporting a question someone else asked.',
          'Grammatically, the embedded question is a subordinate clause, just like the weil-, wenn-, and dass-clauses from Chapter 46. The only difference is what introduces it: instead of a subordinating conjunction such as weil, an indirect question is introduced either by the original question word itself or by ob.',
        ],
      },
      {
        id: 'ch72-rule-02',
        heading: 'Question words are retained — and send the verb to the end',
        paragraphs: [
          'When the direct question has a question word (wer, was, wann, wo, wie, warum, wohin, woher, wie viel, wie lange, welche...), the indirect question keeps that same word. It now sits at the start of the subordinate clause and doubles as the subordinating conjunction, so the finite verb moves to the very end of the clause, exactly as it does after weil or dass.',
          'Wer kommt heute? → Ich weiß nicht, wer heute kommt. Wo ist der Bahnhof? → Können Sie mir sagen, wo der Bahnhof ist? The word order inside the embedded clause changes completely (subject and other elements move in front of the verb), but the question word itself never changes and never moves from the front of its clause.',
        ],
      },
      {
        id: 'ch72-rule-03',
        heading: 'ob replaces a missing question word for yes/no questions',
        paragraphs: [
          'A direct question with no question word — one that expects a yes or no answer, formed by putting the verb first (Kommst du mit? Ist er zu Hause? Hat sie angerufen?) — has nothing to keep at the front of the embedded clause. German fills that empty slot with ob (whether, if), which then works exactly like a question word: it starts the clause and sends the finite verb to the end.',
          'Kommst du mit? → Ich frage mich, ob du mitkommst. Ist der Laden geöffnet? → Weißt du, ob der Laden geöffnet ist? Note that English if in this sense corresponds to German ob, not to the conditional wenn from Chapter 46 — do not confuse the two.',
        ],
      },
      {
        id: 'ch72-rule-04',
        heading: 'Verb-final order applies to every tense and verb type',
        paragraphs: [
          'Just as in weil-, wenn-, and dass-clauses, the verb-final rule holds no matter how complex the verb is. With a modal verb, the modal itself goes last, after the infinitive: ob du mir helfen kannst. With the perfect tense, the past participle comes first and the conjugated auxiliary (haben or sein) comes last: ob er die Prüfung bestanden hat. With a separable verb, the prefix rejoins the verb into a single word at the end: wann der Bus ankommt (from Der Bus kommt an).',
          'Everything that is not the finite verb — objects, adverbs, negation, the separable prefix — keeps its normal relative order and simply shifts in front of the final verb, the same pattern you already practiced with subordinate clauses.',
        ],
      },
      {
        id: 'ch72-rule-05',
        heading: 'Punctuation: the question mark belongs to the whole sentence, not the embedded question',
        paragraphs: [
          'An indirect question never has its own question mark, because it is not asked on its own — it is part of a larger sentence, and that sentence\'s own type decides the final punctuation. If the introductory clause is a statement (Ich weiß nicht, ... / Ich frage mich, ... / Er hat gefragt, ...), the whole sentence ends with a period, even though a question sits inside it: Ich weiß nicht, wer das ist.',
          'If the introductory clause is itself phrased as a question (Können Sie mir sagen, ...? / Weißt du, ...? / Kannst du mir erklären, ...?), the whole sentence ends with a question mark, because you really are asking something — you are just asking it indirectly: Können Sie mir sagen, wo der Bahnhof ist?',
        ],
      },
      {
        id: 'ch72-rule-06',
        heading: 'Indirect questions as a politeness strategy',
        paragraphs: [
          'Asking a stranger a blunt direct question — Wo ist der Bahnhof? Wie viel kostet das? — is not rude in German, but wrapping the same question inside a polite introductory phrase softens it into a courteous request, similar to English "Could you tell me where the train station is?" instead of "Where is the train station?". Common polite frames include Können Sie mir sagen, ...?, Wissen Sie, ...?, and Könnten Sie mir sagen, ...?.',
          'This politeness effect is exactly why indirect questions are so frequent in service situations, formal requests, and polite conversation: the introductory phrase gives the listener a moment to register that a request for information is coming, and the embedded question itself keeps its ordinary verb-final subordinate-clause shape.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch72-table-01',
        title: 'Direct vs. Indirect Questions with a Question Word',
        columns: ['Question word', 'Direct question', 'Indirect question'],
        rows: [
          ['wer', 'Wer kommt heute?', 'Ich weiß nicht, wer heute kommt.'],
          ['was', 'Was machst du?', 'Er fragt, was du machst.'],
          ['wann', 'Wann beginnt der Film?', 'Weißt du, wann der Film beginnt?'],
          ['wo', 'Wo ist der Bahnhof?', 'Können Sie mir sagen, wo der Bahnhof ist?'],
          ['wie', 'Wie funktioniert das?', 'Ich verstehe nicht, wie das funktioniert.'],
          ['warum', 'Warum weint sie?', 'Ich frage mich, warum sie weint.'],
          ['wohin', 'Wohin fährst du?', 'Sag mir, wohin du fährst.'],
          ['woher', 'Woher kommst du?', 'Ich möchte wissen, woher du kommst.'],
        ],
        note: 'The question word is kept exactly as it was and now doubles as the subordinating conjunction; the finite verb moves to the end of its clause.',
      },
      {
        id: 'ch72-table-02',
        title: 'Yes/No Questions: ob Replaces the Missing Question Word',
        columns: ['Direct yes/no question', 'Indirect question with ob'],
        rows: [
          ['Kommst du morgen?', 'Ich weiß nicht, ob du morgen kommst.'],
          ['Ist der Laden geöffnet?', 'Können Sie mir sagen, ob der Laden geöffnet ist?'],
          ['Hat er die Prüfung bestanden?', 'Ich frage mich, ob er die Prüfung bestanden hat.'],
          ['Regnet es?', 'Weißt du, ob es regnet?'],
          ['Kannst du mir helfen?', 'Ich möchte wissen, ob du mir helfen kannst.'],
        ],
        note: 'A direct yes/no question has no question word to keep, so ob fills that position and sends the verb to the end, just like a question word would.',
      },
      {
        id: 'ch72-table-03',
        title: 'Common Introductory Phrases',
        columns: ['Phrase', 'English', 'Note'],
        rows: [
          ['Ich weiß nicht, ...', "I don't know ...", 'statement — sentence ends with a period'],
          ['Ich frage mich, ...', 'I wonder ...', 'reflexive sich fragen — statement, period'],
          ['Ich möchte wissen, ...', 'I would like to know ...', 'statement, period'],
          ['Können Sie mir sagen, ...?', 'Can you tell me ...?', 'polite request — question mark'],
          ['Weißt du, ...?', 'Do you know ...?', 'informal question — question mark'],
          ['Er/Sie hat gefragt, ...', 'He/She asked ...', 'reported question — statement, period'],
          ['Es ist unklar, ob ...', "It's unclear whether ...", 'impersonal statement, period'],
        ],
        note: 'Whether the final sentence ends in a period or a question mark depends entirely on the introductory phrase, never on the embedded question.',
      },
      {
        id: 'ch72-table-04',
        title: 'Punctuation: Statement vs. Question Introductions',
        columns: ['Sentence', 'Introductory clause is a...', 'Punctuation'],
        rows: [
          ['Ich weiß nicht, wo der Bahnhof ist.', 'statement', 'period'],
          ['Können Sie mir sagen, wo der Bahnhof ist?', 'question', 'question mark'],
          ['Weißt du, ob er kommt?', 'question', 'question mark'],
          ['Er hat mich gefragt, ob ich komme.', 'statement (reported)', 'period'],
          ['Ich frage mich, ob es morgen regnet.', 'statement', 'period'],
        ],
        note: '"Ich frage mich" (I wonder / I ask myself) looks like it involves asking, but grammatically it is a plain statement about what the speaker is doing — so it takes a period, not a question mark.',
      },
    ],
    examples: [
      {
        german: 'Ich weiß nicht, wo er wohnt.',
        english: "I don't know where he lives.",
        highlight: ['wo er wohnt'],
        explanation: 'The question word wo is kept; the verb wohnt moves to the end of its clause.',
      },
      {
        german: 'Können Sie mir sagen, wo der Bahnhof ist?',
        english: 'Can you tell me where the train station is?',
        highlight: ['Können Sie mir sagen', 'wo der Bahnhof ist'],
        explanation:
          'A polite alternative to the blunt Wo ist der Bahnhof?; the introductory clause is itself a question, so the sentence ends with a question mark.',
      },
      {
        german: 'Ich frage mich, ob du mitkommst.',
        english: "I wonder whether you're coming along.",
        highlight: ['ob du mitkommst'],
        explanation:
          'No question word exists in Kommst du mit?, so ob fills that role; the separable verb mitkommst rejoins as one word at the end.',
      },
      {
        german: 'Weißt du, wann der Zug abfährt?',
        english: 'Do you know when the train departs?',
        highlight: ['wann der Zug abfährt'],
        explanation:
          'The separable verb abfahren joins into one word (abfährt) at the end of the embedded clause; the whole sentence is a question, so it ends with a question mark.',
      },
      {
        german: 'Ich verstehe nicht, warum sie so still ist.',
        english: "I don't understand why she is so quiet.",
        highlight: ['warum sie so still ist'],
        explanation: 'warum is kept as the introducing word; the verb ist moves to the very end.',
      },
      {
        german: 'Ich weiß nicht, ob er die Prüfung bestanden hat.',
        english: "I don't know whether he passed the exam.",
        highlight: ['bestanden hat'],
        explanation:
          'In the perfect tense, the participle (bestanden) and the auxiliary (hat) both move to the end, with the auxiliary last.',
      },
      {
        german: 'Ich möchte wissen, ob du mir helfen kannst.',
        english: 'I would like to know whether you can help me.',
        highlight: ['helfen kannst'],
        explanation: 'The modal verb kannst goes to the very end, after the infinitive helfen.',
      },
      {
        german: 'Sag mir, wie viel das Ticket kostet.',
        english: 'Tell me how much the ticket costs.',
        highlight: ['wie viel das Ticket kostet'],
        explanation: 'The two-word question phrase wie viel stays together at the front of the clause; the verb kostet goes to the end.',
      },
      {
        german: 'Er hat mich gefragt, ob ich Zeit habe.',
        english: 'He asked me whether I have time.',
        highlight: ['ob ich Zeit habe'],
        explanation: 'Reporting someone else\'s yes/no question also uses ob; the sentence is a statement about what he asked, so it ends with a period.',
      },
      {
        german: 'Wo ist der Bahnhof?',
        english: 'Where is the train station?',
        explanation: 'The direct version: blunt and perfectly grammatical, but less courteous toward a stranger than the indirect version below.',
      },
      {
        german: 'Entschuldigung, können Sie mir sagen, wo der Bahnhof ist?',
        english: 'Excuse me, could you tell me where the train station is?',
        highlight: ['können Sie mir sagen'],
        explanation: 'The same question wrapped in a polite introductory phrase — a typical use of indirect questions as a politeness strategy.',
      },
      {
        german: 'Ich weiß nicht, wer das ist.',
        english: "I don't know who that is.",
        highlight: ['wer das ist'],
        explanation: 'Even though a question is embedded, the whole sentence is a statement, so it ends with a period, not a question mark.',
      },
      {
        german: 'Es ist unklar, ob das Geschäft heute geöffnet ist.',
        english: "It's unclear whether the shop is open today.",
        highlight: ['ob das Geschäft heute geöffnet ist'],
        explanation: 'An impersonal introductory phrase (Es ist unklar, ...) still triggers the same ob + verb-final pattern.',
      },
      {
        german: 'Kannst du mir erklären, warum der Zug Verspätung hat?',
        english: 'Can you explain to me why the train is delayed?',
        highlight: ['warum der Zug Verspätung hat'],
        explanation: 'The introductory clause is a question, so the whole sentence ends with a question mark, even though warum sits inside it.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich weiß nicht, wo ist der Bahnhof.',
        correct: 'Ich weiß nicht, wo der Bahnhof ist.',
        explanation:
          'The question word wo sends the finite verb to the end of its clause, just like weil or dass; it cannot stay in position 2 as in a direct question.',
      },
      {
        incorrect: 'Ich frage mich, kommt er morgen.',
        correct: 'Ich frage mich, ob er morgen kommt.',
        explanation:
          'A yes/no question has no question word to embed, so ob must be inserted; simply dropping the question word entirely is not correct.',
      },
      {
        incorrect: 'Können Sie mir sagen, wo ist der Bahnhof?',
        correct: 'Können Sie mir sagen, wo der Bahnhof ist?',
        explanation:
          'Even inside a polite question, the embedded clause still needs verb-final order: der Bahnhof ist, not ist der Bahnhof.',
      },
      {
        incorrect: 'Ich weiß nicht, wer ist das?',
        correct: 'Ich weiß nicht, wer das ist.',
        explanation:
          'Ich weiß nicht is a statement, so the whole sentence takes a period, not a question mark, and the embedded verb still goes to the end.',
      },
      {
        incorrect: 'Ich frage mich ob er kommt.',
        correct: 'Ich frage mich, ob er kommt.',
        explanation: 'A comma always separates the introductory clause from the embedded question, exactly as with weil-, wenn-, and dass-clauses.',
      },
      {
        incorrect: 'Ich weiß nicht, ob er hat die Prüfung bestanden.',
        correct: 'Ich weiß nicht, ob er die Prüfung bestanden hat.',
        explanation:
          'In the perfect tense, both the participle and the auxiliary move to the end of the clause, with the auxiliary (hat) last, not right after the subject.',
      },
    ],
    remember: [
      'An indirect question embeds a question inside a larger sentence, introduced by phrases like Ich weiß nicht, ..., Können Sie mir sagen, ..., or Ich frage mich, ....',
      'When a question word is present (wer, was, wann, wo, wie, warum...), keep it and send the finite verb to the end of its clause.',
      'When there is no question word (a yes/no question), use ob to introduce the clause; ob also sends the verb to the end.',
      'A comma always separates the introductory clause from the embedded question, just like weil-, wenn-, and dass-clauses.',
      'Punctuation follows the whole sentence: a period if the introductory clause is a statement, a question mark if the introductory clause is itself phrased as a question.',
      'Wrapping a direct question inside an indirect one is a common way to sound more polite, especially with strangers or in formal requests.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 28,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch72-ex-01',
      chapterNumber: 72,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['indirect-question', 'question-word', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I don\'t know where he lives." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich weiß nicht, wo er wohnt.' },
        { id: 'b', text: 'Ich weiß nicht, wo wohnt er.' },
        { id: 'c', text: 'Ich weiß nicht, er wo wohnt.' },
        { id: 'd', text: 'Ich weiß nicht, wohnt er wo.' },
      ],
      correctOptionId: 'a',
      explanation: 'The question word wo is kept, and the finite verb wohnt moves to the end of its clause.',
    },
    {
      id: 'ch72-ex-02',
      chapterNumber: 72,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['indirect-question', 'ob', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I don\'t know if he is coming tomorrow." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich weiß nicht, ob er morgen kommt.' },
        { id: 'b', text: 'Ich weiß nicht, kommt er morgen.' },
        { id: 'c', text: 'Ich weiß nicht, ob kommt er morgen.' },
        { id: 'd', text: 'Ich weiß nicht, er ob morgen kommt.' },
      ],
      correctOptionId: 'a',
      explanation: 'ob replaces the missing question word and sends the finite verb kommt to the end of its clause.',
    },
    {
      id: 'ch72-ex-03',
      chapterNumber: 72,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['question-word-choice', 'wie-viel'],
      instruction: 'Choose the word that fits.',
      prompt: 'Ich frage mich, ___ das Ticket kostet. (how much)',
      options: [
        { id: 'a', text: 'wie viel' },
        { id: 'b', text: 'ob' },
        { id: 'c', text: 'was' },
        { id: 'd', text: 'wer' },
      ],
      correctOptionId: 'a',
      explanation: 'wie viel (how much) is the question word from the original direct question Wie viel kostet das Ticket?',
    },
    {
      id: 'ch72-ex-04',
      chapterNumber: 72,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['ob', 'yes-no-question'],
      instruction: 'Choose the word that fits.',
      prompt: 'Weißt du, ___ der Laden heute geöffnet ist?',
      options: [
        { id: 'a', text: 'ob' },
        { id: 'b', text: 'wo' },
        { id: 'c', text: 'wann' },
        { id: 'd', text: 'wie' },
      ],
      correctOptionId: 'a',
      explanation: 'Ist der Laden geöffnet? has no question word, so ob introduces the indirect yes/no question.',
    },
    {
      id: 'ch72-ex-05',
      chapterNumber: 72,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['indirect-question', 'separable-verb', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"Do you know when the bus arrives?" Which sentence is correct?',
      options: [
        { id: 'a', text: 'Weißt du, wann der Bus ankommt?' },
        { id: 'b', text: 'Weißt du, wann kommt der Bus an?' },
        { id: 'c', text: 'Weißt du, wann der Bus an kommt?' },
        { id: 'd', text: 'Weißt du, wann ankommt der Bus?' },
      ],
      correctOptionId: 'a',
      explanation: 'The separable verb ankommen rejoins as one word (ankommt) at the end of the embedded clause.',
    },
    {
      id: 'ch72-ex-06',
      chapterNumber: 72,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['indirect-question', 'ob', 'modal-verb', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I wonder whether you can help me." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich frage mich, ob du mir helfen kannst.' },
        { id: 'b', text: 'Ich frage mich, ob du kannst mir helfen.' },
        { id: 'c', text: 'Ich frage mich, ob kannst du mir helfen.' },
        { id: 'd', text: 'Ich frage mich, ob du mir kannst helfen.' },
      ],
      correctOptionId: 'a',
      explanation: 'The modal verb kannst goes to the very end of the clause, after the infinitive helfen.',
    },
    {
      id: 'ch72-ex-07',
      chapterNumber: 72,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['indirect-question', 'ob', 'perfect-tense', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I don\'t know whether he passed the exam." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich weiß nicht, ob er die Prüfung bestanden hat.' },
        { id: 'b', text: 'Ich weiß nicht, ob er hat die Prüfung bestanden.' },
        { id: 'c', text: 'Ich weiß nicht, ob er die Prüfung hat bestanden.' },
        { id: 'd', text: 'Ich weiß nicht, ob hat er die Prüfung bestanden.' },
      ],
      correctOptionId: 'a',
      explanation: 'In the perfect tense, the participle (bestanden) comes first and the auxiliary (hat) comes last, at the very end.',
    },
    {
      id: 'ch72-ex-08',
      chapterNumber: 72,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['comma', 'indirect-question'],
      instruction: 'Choose the correctly punctuated sentence.',
      prompt: 'Choose the correctly punctuated sentence.',
      options: [
        { id: 'a', text: 'Ich weiß nicht, wo der Bahnhof ist.' },
        { id: 'b', text: 'Ich weiß nicht wo, der Bahnhof ist.' },
        { id: 'c', text: 'Ich weiß, nicht wo der Bahnhof ist.' },
        { id: 'd', text: 'Ich weiß nicht wo der Bahnhof, ist.' },
      ],
      correctOptionId: 'a',
      explanation: 'The comma goes directly before the question word that introduces the embedded clause.',
    },
    {
      id: 'ch72-ex-09',
      chapterNumber: 72,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['punctuation', 'indirect-question'],
      instruction: 'Choose the correctly punctuated sentence.',
      prompt: '"I don\'t know who that is." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich weiß nicht, wer das ist.' },
        { id: 'b', text: 'Ich weiß nicht, wer das ist?' },
        { id: 'c', text: 'Ich weiß nicht, wer ist das.' },
        { id: 'd', text: 'Ich weiß nicht, wer ist das?' },
      ],
      correctOptionId: 'a',
      explanation:
        'Ich weiß nicht is a statement, so the whole sentence ends with a period, even though a question is embedded inside it; the verb also stays at the end.',
    },
    {
      id: 'ch72-ex-10',
      chapterNumber: 72,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['punctuation', 'indirect-question', 'politeness'],
      instruction: 'Choose the correctly punctuated sentence.',
      prompt: '"Can you tell me where the train station is?" Which sentence is correct?',
      options: [
        { id: 'a', text: 'Können Sie mir sagen, wo der Bahnhof ist?' },
        { id: 'b', text: 'Können Sie mir sagen, wo der Bahnhof ist.' },
        { id: 'c', text: 'Können Sie mir sagen, wo ist der Bahnhof?' },
        { id: 'd', text: 'Können Sie mir sagen, wo der Bahnhof, ist?' },
      ],
      correctOptionId: 'a',
      explanation: 'The introductory clause Können Sie mir sagen ...? is itself a question, so the whole sentence ends with a question mark.',
    },
    {
      id: 'ch72-ex-11',
      chapterNumber: 72,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['indirect-question', 'politeness', 'dialogue'],
      instruction: 'Choose the more polite way to ask the same question.',
      dialogue: [
        { speaker: 'Tourist', german: 'Wo ist der Bahnhof?', english: 'Where is the train station?' },
        { speaker: 'Freund', german: 'Frag doch höflicher, du redest mit einer fremden Person!', english: "Ask more politely, you're talking to a stranger!" },
      ],
      prompt: 'Rephrase the tourist\'s question more politely, addressing a stranger with Sie.',
      options: [
        { id: 'a', text: 'Können Sie mir sagen, wo der Bahnhof ist?' },
        { id: 'b', text: 'Wo ist der Bahnhof, können Sie mir sagen?' },
        { id: 'c', text: 'Sagen Sie mir wo ist der Bahnhof?' },
        { id: 'd', text: 'Können Sie mir sagen wo ist der Bahnhof?' },
      ],
      correctOptionId: 'a',
      explanation: 'Wrapping the question inside Können Sie mir sagen, ...? with verb-final order softens the direct question into a polite request.',
    },
    {
      id: 'ch72-ex-12',
      chapterNumber: 72,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['indirect-question', 'ob', 'conversion'],
      instruction: 'Choose the correct conversion.',
      prompt: '"Ist das Geschäft heute geöffnet?" → indirect, beginning with "Weißt du, ...?"',
      options: [
        { id: 'a', text: 'Weißt du, ob das Geschäft heute geöffnet ist?' },
        { id: 'b', text: 'Weißt du, ist das Geschäft heute geöffnet?' },
        { id: 'c', text: 'Weißt du, ob ist das Geschäft heute geöffnet?' },
        { id: 'd', text: 'Weißt du, das Geschäft heute geöffnet ist?' },
      ],
      correctOptionId: 'a',
      explanation: 'ob replaces the missing question word, and the verb ist moves to the end: ob das Geschäft heute geöffnet ist.',
    },
    {
      id: 'ch72-ex-13',
      chapterNumber: 72,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['indirect-question', 'question-word', 'conversion'],
      instruction: 'Choose the correct conversion.',
      prompt: '"Warum ist sie so still?" → indirect, beginning with "Ich verstehe nicht, ..."',
      options: [
        { id: 'a', text: 'Ich verstehe nicht, warum sie so still ist.' },
        { id: 'b', text: 'Ich verstehe nicht, warum ist sie so still.' },
        { id: 'c', text: 'Ich verstehe nicht, sie warum so still ist.' },
        { id: 'd', text: 'Ich verstehe nicht, warum sie ist so still.' },
      ],
      correctOptionId: 'a',
      explanation: 'warum is kept, and the verb ist moves all the way to the end of the clause: warum sie so still ist.',
    },
    {
      id: 'ch72-ex-14',
      chapterNumber: 72,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['error-correction', 'verb-final'],
      instruction: 'Choose the sentence that contains a mistake.',
      prompt: 'Which of these sentences is grammatically wrong?',
      options: [
        { id: 'a', text: 'Ich weiß nicht, wo er wohnt.' },
        { id: 'b', text: 'Er hat gefragt, ob ich Zeit habe.' },
        { id: 'c', text: 'Ich frage mich, ob kommt sie morgen.' },
        { id: 'd', text: 'Kannst du mir sagen, wann der Film beginnt?' },
      ],
      correctOptionId: 'c',
      explanation: 'ob must send the finite verb to the end of its clause: it should be ob sie morgen kommt, not ob kommt sie morgen.',
    },
    {
      id: 'ch72-ex-15',
      chapterNumber: 72,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['indirect-question', 'ob', 'dialogue'],
      instruction: "Complete Ben's answer.",
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Kommt Tom heute Abend zur Party?',
          english: 'Is Tom coming to the party tonight?',
        },
        { speaker: 'Ben', german: 'Ich weiß nicht, ___', english: "I don't know ___" },
      ],
      prompt: 'Ich weiß nicht, ___',
      options: [
        { id: 'a', text: 'ob Tom heute Abend zur Party kommt.' },
        { id: 'b', text: 'kommt Tom heute Abend zur Party.' },
        { id: 'c', text: 'Tom ob heute Abend zur Party kommt.' },
        { id: 'd', text: 'ob kommt Tom heute Abend zur Party.' },
      ],
      correctOptionId: 'a',
      explanation: "Anna's question has no question word, so ob introduces the indirect question, with the verb kommt at the end.",
    },
    {
      id: 'ch72-ex-16',
      chapterNumber: 72,
      order: 16,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['indirect-question', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich weiß nicht, wo er ___. (wohnen, er-Form)',
      acceptedAnswers: ['wohnt'],
      answerMode: 'caseInsensitive',
      placeholder: 'wohnt',
      maxLength: 10,
      explanation: 'The verb moves to the end of the clause; the er-form of wohnen is wohnt.',
    },
    {
      id: 'ch72-ex-17',
      chapterNumber: 72,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['ob', 'yes-no-question'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich weiß nicht, ___ er kommt. (no question word in the original question)',
      acceptedAnswers: ['ob'],
      answerMode: 'caseInsensitive',
      placeholder: 'ob',
      maxLength: 5,
      explanation: 'ob introduces an indirect yes/no question when there is no question word to keep.',
    },
    {
      id: 'ch72-ex-18',
      chapterNumber: 72,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['ob', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich frage mich, ob sie die Wahrheit ___. (sagen, sie-Form)',
      acceptedAnswers: ['sagt'],
      answerMode: 'caseInsensitive',
      placeholder: 'sagt',
      maxLength: 10,
      explanation: 'The finite verb goes to the end of the ob-clause; the sie-form of sagen is sagt.',
    },
    {
      id: 'ch72-ex-19',
      chapterNumber: 72,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['indirect-question', 'separable-verb', 'verb-final'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Weißt du, wann der Zug ___? (abfahren, er-Form)',
      acceptedAnswers: ['abfährt'],
      answerMode: 'caseInsensitive',
      placeholder: 'abfährt',
      maxLength: 15,
      explanation: 'The separable verb abfahren rejoins as one word (abfährt) at the end of the embedded clause.',
    },
    {
      id: 'ch72-ex-20',
      chapterNumber: 72,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['ob', 'modal-verb', 'verb-final'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich weiß nicht, ob ich morgen arbeiten ___. (müssen, ich-Form)',
      acceptedAnswers: ['muss'],
      answerMode: 'caseInsensitive',
      placeholder: 'muss',
      maxLength: 10,
      explanation: 'The modal verb goes to the very end, after the infinitive arbeiten: ob ich morgen arbeiten muss.',
    },
    {
      id: 'ch72-ex-21',
      chapterNumber: 72,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['ob', 'perfect-tense', 'verb-final'],
      instruction: 'Write only the missing words (two words). Capitalisation is not checked.',
      prompt: 'Ich weiß nicht, ob er die Prüfung ___. (bestehen, Perfekt mit haben, er-Form)',
      acceptedAnswers: ['bestanden hat'],
      answerMode: 'caseInsensitive',
      placeholder: 'bestanden hat',
      maxLength: 20,
      explanation: 'In the perfect tense, the participle (bestanden) comes first and the auxiliary (hat) comes last, at the end of the clause.',
    },
    {
      id: 'ch72-ex-22',
      chapterNumber: 72,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['indirect-question', 'question-word', 'conversion'],
      instruction: 'Convert the direct question into an indirect question starting with the given phrase. Capitalisation and punctuation are checked.',
      prompt: 'Wo wohnst du? → Ich weiß nicht, ...',
      acceptedAnswers: ['Ich weiß nicht, wo du wohnst.'],
      answerMode: 'normalized',
      placeholder: 'Ich weiß nicht, wo du wohnst.',
      maxLength: 40,
      explanation: 'The question word wo is kept, and the verb wohnst moves to the end: Ich weiß nicht, wo du wohnst.',
    },
    {
      id: 'ch72-ex-23',
      chapterNumber: 72,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['indirect-question', 'ob', 'conversion'],
      instruction: 'Convert the direct question into an indirect question starting with the given phrase. Capitalisation and punctuation are checked.',
      prompt: 'Kommst du morgen? → Ich weiß nicht, ...',
      acceptedAnswers: ['Ich weiß nicht, ob du morgen kommst.'],
      answerMode: 'normalized',
      placeholder: 'Ich weiß nicht, ob du morgen kommst.',
      maxLength: 45,
      explanation: 'The direct question has no question word, so ob introduces the clause: Ich weiß nicht, ob du morgen kommst.',
    },
    {
      id: 'ch72-ex-24',
      chapterNumber: 72,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['indirect-question', 'politeness', 'punctuation', 'conversion'],
      instruction: 'Convert the direct question into a polite indirect question starting with the given phrase. Capitalisation and punctuation are checked.',
      prompt: 'Wo ist der Bahnhof? → Können Sie mir sagen, ...?',
      acceptedAnswers: ['Können Sie mir sagen, wo der Bahnhof ist?'],
      answerMode: 'normalized',
      placeholder: 'Können Sie mir sagen, wo der Bahnhof ist?',
      maxLength: 45,
      explanation:
        'The introductory clause Können Sie mir sagen ...? is itself a question, so the whole sentence keeps the question mark: Können Sie mir sagen, wo der Bahnhof ist?',
    },
    {
      id: 'ch72-ex-25',
      chapterNumber: 72,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['indirect-question', 'ob', 'conversion'],
      instruction: 'Convert the direct question into an indirect question starting with the given phrase. Capitalisation and punctuation are checked.',
      prompt: 'Regnet es morgen? → Ich frage mich, ...',
      acceptedAnswers: ['Ich frage mich, ob es morgen regnet.'],
      answerMode: 'normalized',
      placeholder: 'Ich frage mich, ob es morgen regnet.',
      maxLength: 45,
      explanation: 'Ich frage mich is a statement, so the sentence ends with a period; ob introduces the embedded yes/no question.',
    },
    {
      id: 'ch72-ex-26',
      chapterNumber: 72,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['indirect-question', 'ob', 'punctuation', 'conversion'],
      instruction: 'Convert the direct question into an indirect question starting with the given phrase. Capitalisation and punctuation are checked.',
      prompt: 'Ist der Laden heute geöffnet? → Weißt du, ...?',
      acceptedAnswers: ['Weißt du, ob der Laden heute geöffnet ist?'],
      answerMode: 'normalized',
      placeholder: 'Weißt du, ob der Laden heute geöffnet ist?',
      maxLength: 50,
      explanation: 'Weißt du ...? is itself a question, so the sentence keeps its question mark; ob introduces the embedded yes/no question.',
    },
    {
      id: 'ch72-ex-27',
      chapterNumber: 72,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'verb-final'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich weiß nicht, wo ist der Bahnhof.',
      acceptedAnswers: ['Ich weiß nicht, wo der Bahnhof ist.'],
      answerMode: 'normalized',
      placeholder: 'Ich weiß nicht, wo der Bahnhof ist.',
      maxLength: 40,
      explanation: 'The question word wo sends the finite verb to the end of its clause: wo der Bahnhof ist, not wo ist der Bahnhof.',
    },
    {
      id: 'ch72-ex-28',
      chapterNumber: 72,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'ob'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich frage mich, kommt er morgen.',
      acceptedAnswers: ['Ich frage mich, ob er morgen kommt.'],
      answerMode: 'normalized',
      placeholder: 'Ich frage mich, ob er morgen kommt.',
      maxLength: 45,
      explanation: 'A yes/no question with no question word needs ob to introduce the embedded clause: ob er morgen kommt.',
    },
    {
      id: 'ch72-ex-29',
      chapterNumber: 72,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['indirect-question', 'ob', 'dialogue', 'verb-final'],
      instruction: 'Complete the reply. Write only the missing words. Capitalisation is not checked.',
      dialogue: [
        {
          speaker: 'Chef',
          german: 'Weiß jemand, wann Frau Meier zurückkommt?',
          english: 'Does anyone know when Ms. Meier is coming back?',
        },
        {
          speaker: 'Kollege',
          german: 'Sie hat gesagt, dass sie am Montag zurückkommt. Aber ich weiß nicht, ___.',
          english: "She said she's coming back on Monday. But I don't know ___.",
        },
      ],
      prompt: 'Aber ich weiß nicht, ___. (ob / pünktlich / sie / kommen, Präsens)',
      acceptedAnswers: ['ob sie pünktlich kommt'],
      answerMode: 'caseInsensitive',
      placeholder: 'ob sie pünktlich kommt',
      maxLength: 30,
      explanation: 'The original question (Kommt sie pünktlich?) has no question word, so ob introduces the clause with the verb kommt at the end.',
    },
    {
      id: 'ch72-ex-30',
      chapterNumber: 72,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['indirect-question', 'ob', 'modal-verb', 'conversion', 'politeness'],
      instruction: 'Convert the direct question into a polite indirect question starting with the given phrase. Capitalisation and punctuation are checked.',
      prompt: 'Kannst du mir helfen? → Ich möchte wissen, ...',
      acceptedAnswers: ['Ich möchte wissen, ob du mir helfen kannst.'],
      answerMode: 'normalized',
      placeholder: 'Ich möchte wissen, ob du mir helfen kannst.',
      maxLength: 45,
      explanation: 'ob introduces the clause, and the modal kannst moves to the very end, after the infinitive helfen.',
    },
  ],
};
