import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter083: ChapterDefinition = {
  id: 'chapter-083',
  number: 83,
  slug: 'advanced-temporal-prepositions-and-expressions',
  title: 'Advanced Temporal Prepositions and Expressions',
  germanTitle: 'Erweiterte temporale Präpositionen und Ausdrücke',
  level: 'B1',
  section: 'prepositions-2',
  objective:
    'Choose correctly among innerhalb, außerhalb, während, seit, ab, bis zu, and von ... an to express duration, deadlines, starting points, and endpoints on a timeline, apply their case government (genitive for innerhalb/außerhalb/während, dative for seit/ab/bis zu/von ... an), and use the resulting nuance to interpret and rewrite schedules and notices.',
  prerequisites: [32, 82],
  estimatedMinutes: 30,
  tags: [
    'prepositions',
    'temporal-expressions',
    'innerhalb',
    'außerhalb',
    'während',
    'seit',
    'ab',
    'bis-zu',
    'von-an',
    'genitive-case',
    'dative-case',
    'timeline',
    'deadlines',
  ],
  explanation: {
    introduction: [
      'You already know the everyday temporal prepositions um, am, im, von ... bis, and ab from Chapter 32, and you have met während, wegen, trotz, and statt as genitive prepositions in Chapter 82. This chapter brings those two threads together and adds a set of more precise expressions for talking about deadlines, durations, and open-ended starting or ending points: innerhalb (within), außerhalb (outside of), während (during), seit (since), ab (from ... on), bis zu (up until), and von ... an (from ... onward).',
      'Three of these — innerhalb, außerhalb, and während — govern the genitive, the same case you practised with trotz and wegen. The other four — seit, ab, bis zu, and von ... an — govern the dative. Knowing the case is only half the job, though: the real skill this chapter builds is choosing the right expression for the right shape of time. Some of these expressions name a bounded window (innerhalb, außerhalb), some name a duration that fills an entire period (während), some name a starting point (seit, ab, von ... an), and some name a closing endpoint (bis zu). Mixing these nuances up produces sentences that are grammatically fine but say something different from what you meant.',
      'A recurring theme is the difference between looking backward and looking forward on a timeline. seit looks back from now to a point in the past where something began and is still going on. ab and von ... an look forward from a starting point, with no end in sight. bis and bis zu look forward only as far as a named endpoint. innerhalb frames a closed window inside which something must happen at some point; außerhalb marks everything lying outside that window. Keeping these five directions straight — backward-and-ongoing, forward-and-open, forward-to-an-endpoint, inside-a-window, outside-a-window — is the heart of this chapter.',
    ],
    rules: [
      {
        id: 'ch83-rule-01',
        heading: 'innerhalb — within a bounded window (+ genitive)',
        paragraphs: [
          'innerhalb means "within" and marks a bounded period during which something must happen, without saying exactly when inside that period it happens. It takes the genitive: innerhalb einer Woche (within a week), innerhalb eines Jahres (within a year), innerhalb der Frist (within the deadline).',
          'Ich muss die Unterlagen innerhalb einer Woche einreichen. (I have to submit the documents within a week.) The deadline can be met on day one, day four, or day seven — innerhalb only fixes the outer boundary, not the moment of action. In everyday spoken German you will also meet innerhalb von + dative (innerhalb von drei Tagen) when the genitive form would be unclear, for example with an unmarked plural — but the genitive form taught here is the standard, and always correct, choice.',
        ],
      },
      {
        id: 'ch83-rule-02',
        heading: 'außerhalb — outside a bounded window (+ genitive)',
        paragraphs: [
          'außerhalb means "outside of" and is the mirror image of innerhalb: it marks everything that falls outside a named period. It also takes the genitive: außerhalb der Geschäftszeiten (outside business hours), außerhalb der Saison (out of season).',
          'Das Büro ist außerhalb der Geschäftszeiten nicht erreichbar. (The office cannot be reached outside business hours.) Because innerhalb and außerhalb name opposite sides of the same boundary, they are easy to keep straight once you remember that innerhalb points inward, into the window, and außerhalb points outward, away from it.',
        ],
      },
      {
        id: 'ch83-rule-03',
        heading: 'während — duration that fills the whole period (+ genitive)',
        paragraphs: [
          'während means "during" and, unlike innerhalb, describes an action that spans the entire named period rather than a deadline that can be met at any single point inside it. It also takes the genitive: während des Sommers (during the summer), während der Woche (during the week), während meines Studiums (during my studies).',
          'Während des Sommers arbeite ich in einem Café. (During the summer, I work in a café.) The job runs continuously through the whole summer — that is what während signals. Compare Innerhalb eines Sommers habe ich das Buch gelesen (I read the book within one summer), where innerhalb only guarantees the reading finished sometime before the summer ended, not that it took the whole season.',
        ],
      },
      {
        id: 'ch83-rule-04',
        heading: 'seit — a starting point in the past that still continues (+ dative)',
        paragraphs: [
          'seit means "since" or "for" and names a point in the past where something began and that is still true or ongoing now. It takes the dative: seit einem Jahr (for a year), seit einer Woche (for a week), seit letztem Montag (since last Monday).',
          'Ich wohne seit einem Jahr in Berlin. (I have been living in Berlin for a year.) German uses the present tense wohne here, not a perfect tense, because the living arrangement is still current — this is the same pattern you met with the seit-clauses in Chapter 78, just with a noun phrase instead of a whole clause.',
        ],
      },
      {
        id: 'ch83-rule-05',
        heading: 'ab — a starting point in the present or future, open-ended (+ dative)',
        paragraphs: [
          'ab means "from ... on" and names a starting point in the present or future after which something begins and continues, with no end mentioned. It takes the dative: ab nächstem Montag (from next Monday on), ab dem 1. Januar (from 1 January on), ab sofort (effective immediately).',
          'Ab nächstem Montag arbeite ich im neuen Büro. (From next Monday, I will be working in the new office.) The key contrast with seit is direction: seit looks backward from now to a past start, while ab looks forward from a present or future start, with the end left open.',
        ],
      },
      {
        id: 'ch83-rule-06',
        heading: 'bis zu — the closing endpoint of a span (+ dative), and bare bis',
        paragraphs: [
          'bis zu means "up until" and names the closing endpoint of a span. It takes the dative: bis zu den Ferien (up until the holidays), bis zum Wochenende (zu + dem contracts to zum), bis zu meinem Geburtstag (up until my birthday).',
          'Die Anmeldung ist bis zu den Ferien möglich. (Registration is possible up until the holidays.) When the following noun has no article — a bare day, date, or time — bis alone is normally used instead, without zu, and the noun is traditionally treated as accusative: bis Montag, bis nächste Woche, bis Ende des Monats. As soon as an article or possessive appears, insert zu and switch to the dative: bis zu den Ferien, not bis den Ferien.',
        ],
      },
      {
        id: 'ch83-rule-07',
        heading: 'von ... an — from ... onward (+ dative)',
        paragraphs: [
          'von ... an also means "from ... onward" and, like ab, marks an open-ended starting point. Unlike ab, it wraps around the noun phrase as a two-part frame: von opens it, an closes it, and the dative noun phrase sits in between. von diesem Tag an (from this day onward), von nächster Woche an (from next week onward).',
          'Von diesem Tag an gilt die neue Regel. (From this day onward, the new rule applies.) von ... an is somewhat more formal and emphatic than ab, and it is common in official announcements and written notices. The an cannot be dropped — von diesem Tag alone just means "from this day" without the same forward-looking emphasis, and is grammatically incomplete as the fixed pair.',
        ],
      },
      {
        id: 'ch83-rule-08',
        heading: 'The timeline at a glance: choosing among seven expressions',
        paragraphs: [
          'When you meet a temporal expression to translate or complete, ask five questions in order. Does the action start in the past and continue to now? Use seit. Does it start in the present or future with no end named? Use ab or, more formally, von ... an. Does the sentence name a closing endpoint? Use bis (bare, before an article-less noun) or bis zu (before an article or possessive). Is there a deadline that can be met anywhere inside a bounded window? Use innerhalb. Does something lie outside that bounded window instead? Use außerhalb. Does the action fill the entire named period rather than just needing to happen sometime within it? Use während.',
          'These five directions — backward-and-ongoing (seit), forward-and-open (ab, von ... an), forward-to-an-endpoint (bis, bis zu), inside-a-window (innerhalb), spanning-the-whole-period (während), and outside-a-window (außerhalb) — cover almost every nuanced timeline statement you will need at this level. Case is a useful secondary check: if you have chosen a genitive form (innerhalb, außerhalb, während) but the noun phrase looks dative, or a dative expression (seit, ab, bis zu, von ... an) but the noun phrase looks genitive, you have very likely picked the wrong preposition, not just the wrong ending.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch83-table-01',
        title: 'Seven temporal expressions at a glance',
        columns: ['Expression', 'Case', 'Core meaning', 'Example'],
        rows: [
          ['innerhalb', 'genitive', 'within a bounded window (deadline)', 'innerhalb einer Woche (within a week)'],
          ['außerhalb', 'genitive', 'outside a bounded window', 'außerhalb der Geschäftszeiten (outside business hours)'],
          ['während', 'genitive', 'during, filling the whole period', 'während des Sommers (during the summer)'],
          ['seit', 'dative', 'starting point in the past, still ongoing', 'seit einem Jahr (for a year, since a year ago)'],
          ['ab', 'dative', 'starting point now/future, open-ended', 'ab nächstem Montag (from next Monday on)'],
          ['bis zu', 'dative', 'closing endpoint, up until', 'bis zu den Ferien (up until the holidays)'],
          ['von ... an', 'dative', 'starting point, open-ended', 'von diesem Tag an (from this day onward)'],
        ],
      },
      {
        id: 'ch83-table-02',
        title: 'Genitive group — bounded windows and duration',
        columns: ['Preposition', 'Meaning', 'Genitive example'],
        rows: [
          ['innerhalb', 'within (a deadline inside the window)', 'innerhalb eines Jahres'],
          ['außerhalb', 'outside of (outside the window)', 'außerhalb der Saison'],
          ['während', 'during (filling the whole window)', 'während des Sommers'],
        ],
        columnCases: [null, null, 'genitive'],
      },
      {
        id: 'ch83-table-03',
        title: 'Dative group — starting points and deadlines',
        columns: ['Preposition', 'Meaning', 'Dative example'],
        rows: [
          ['seit', 'since (past start, ongoing)', 'seit einem Jahr'],
          ['ab', 'from ... on (present/future start)', 'ab nächstem Montag'],
          ['bis zu', 'up until (endpoint)', 'bis zu den Ferien'],
          ['von ... an', 'from ... onward (open-ended start)', 'von diesem Tag an'],
        ],
        columnCases: [null, null, 'dative'],
      },
      {
        id: 'ch83-table-04',
        title: 'Timeline decision guide',
        columns: ['Question about the timeline', 'Preposition to use', 'Example'],
        rows: [
          ['Does it start in the past and continue to now?', 'seit', 'seit einem Jahr'],
          ['Does it start now/in the future, with no end named?', 'ab or von ... an', 'ab nächstem Montag / von diesem Tag an'],
          ['Does the sentence name a closing endpoint?', 'bis or bis zu', 'bis zu den Ferien'],
          ['Is there a deadline met anywhere inside a window?', 'innerhalb', 'innerhalb einer Woche'],
          ['Does the action span the entire period?', 'während', 'während des Sommers'],
          ['Does something lie outside the bounded window?', 'außerhalb', 'außerhalb der Geschäftszeiten'],
        ],
      },
    ],
    examples: [
      {
        german: 'Ich muss die Unterlagen innerhalb einer Woche einreichen.',
        english: 'I have to submit the documents within a week.',
        highlight: ['innerhalb einer Woche'],
        explanation: 'innerhalb + genitive names a bounded window; the deadline can be met at any point inside that week.',
      },
      {
        german: 'Innerhalb eines Jahres hat sich vieles verändert.',
        english: 'Within a year, a lot has changed.',
        highlight: ['Innerhalb eines Jahres'],
        explanation: 'Neuter genitive singular: das Jahr becomes eines Jahres.',
      },
      {
        german: 'Das Büro ist außerhalb der Geschäftszeiten nicht erreichbar.',
        english: 'The office cannot be reached outside business hours.',
        highlight: ['außerhalb der Geschäftszeiten'],
        explanation: 'außerhalb + genitive plural marks everything lying outside that window.',
      },
      {
        german: 'Außerhalb der Saison sind die Hotels günstiger.',
        english: 'Outside the season, hotels are cheaper.',
        highlight: ['Außerhalb der Saison'],
        explanation: 'außerhalb is the mirror image of innerhalb, naming what lies outside the bounded period.',
      },
      {
        german: 'Während des Sommers arbeite ich in einem Café.',
        english: 'During the summer, I work in a café.',
        highlight: ['Während des Sommers'],
        explanation: 'während + genitive here marks duration: the job runs through the whole summer, not just at one point inside it.',
      },
      {
        german: 'Während der Woche habe ich wenig Zeit.',
        english: 'During the week, I have little time.',
        highlight: ['Während der Woche'],
        explanation: 'Feminine genitive singular: die Woche becomes der Woche.',
      },
      {
        german: 'Ich wohne seit einem Jahr in Berlin.',
        english: 'I have been living in Berlin for a year.',
        highlight: ['seit einem Jahr'],
        explanation: 'seit + dative marks a starting point in the past that continues up to now; German uses the present tense wohne, not a perfect tense.',
      },
      {
        german: 'Seit letztem Montag ist die neue Regel in Kraft.',
        english: 'Since last Monday, the new rule has been in force.',
        highlight: ['Seit letztem Montag'],
        explanation: 'Masculine dative singular strong ending: letztem Montag.',
      },
      {
        german: 'Ab nächstem Montag arbeite ich im neuen Büro.',
        english: 'From next Monday, I will be working in the new office.',
        highlight: ['Ab nächstem Montag'],
        explanation: 'ab + dative names a starting point in the present or future, with no end mentioned.',
      },
      {
        german: 'Ab sofort gilt die neue Hausordnung.',
        english: 'Effective immediately, the new house rules apply.',
        highlight: ['Ab sofort'],
        explanation: 'ab sofort is a fixed idiom meaning "effective immediately", built on the same open-ended ab.',
      },
      {
        german: 'Die Anmeldung ist bis zu den Ferien möglich.',
        english: 'Registration is possible up until the holidays.',
        highlight: ['bis zu den Ferien'],
        explanation: 'bis zu + dative names the closing endpoint of a span; den Ferien is dative plural.',
      },
      {
        german: 'Das Geschäft hat bis zum Wochenende geöffnet.',
        english: 'The shop is open until the weekend.',
        highlight: ['bis zum Wochenende'],
        explanation: 'zu + dem contracts to zum, just as an + dem contracts to am.',
      },
      {
        german: 'Von diesem Tag an gilt die neue Regel.',
        english: 'From this day onward, the new rule applies.',
        highlight: ['Von diesem Tag an'],
        explanation: 'von ... an is a fixed two-part frame around the dative noun phrase, marking an open-ended starting point.',
      },
      {
        german: 'Von nächster Woche an arbeite ich nur noch vier Tage.',
        english: 'From next week onward, I will only work four days.',
        highlight: ['Von nächster Woche an'],
        explanation: 'Feminine dative singular strong ending: nächster Woche, framed by von ... an.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Innerhalb einem Jahr melde ich mich.',
        correct: 'Innerhalb eines Jahres melde ich mich.',
        explanation: 'innerhalb governs the genitive, not the dative; einem Jahr is dative and must become the genitive eines Jahres.',
      },
      {
        incorrect: 'Seit einen Monat lerne ich Deutsch.',
        correct: 'Seit einem Monat lerne ich Deutsch.',
        explanation: 'seit governs the dative; einen Monat is accusative and must become the dative einem Monat.',
      },
      {
        incorrect: 'Ab nächsten Montag gilt die neue Regel.',
        correct: 'Ab nächstem Montag gilt die neue Regel.',
        explanation: 'ab governs the dative; nächsten Montag is accusative and must become the dative nächstem Montag.',
      },
      {
        incorrect: 'Die Bewerbung ist bis der Ferien möglich.',
        correct: 'Die Bewerbung ist bis zu den Ferien möglich.',
        explanation: 'Before an article-bearing noun phrase, bis needs the added zu and the dative case; bare bis before an article is ungrammatical.',
      },
      {
        incorrect: 'Ich muss die Aufgabe während einer Woche abgeben.',
        correct: 'Ich muss die Aufgabe innerhalb einer Woche abgeben.',
        explanation: 'A deadline that can be met at any point inside the window uses innerhalb, not während, which implies the action fills the entire period.',
      },
      {
        incorrect: 'Von diesem Tag gilt die neue Regel.',
        correct: 'Von diesem Tag an gilt die neue Regel.',
        explanation: 'von ... an is a fixed two-part expression; dropping the closing an leaves the "from ... onward" meaning incomplete.',
      },
    ],
    remember: [
      'innerhalb (within, a deadline inside a window), außerhalb (outside a window), and während (during, filling the whole period) all take the genitive.',
      'seit (since, a past starting point that is still ongoing), ab (from ... on, a present/future starting point), bis zu (up until, an endpoint), and von ... an (from ... onward) all take the dative.',
      'seit looks backward from now to a past start; ab and von ... an look forward from a starting point with no end named; bis and bis zu name the closing endpoint of a span.',
      'innerhalb frames a deadline you can meet at any moment inside the window; während frames an action that fills the entire period; außerhalb names everything outside that same window.',
      'bis alone commonly precedes a bare date or day with no article (bis Montag); once an article or possessive appears, insert zu and switch to the dative (bis zu den Ferien, bis zum Wochenende).',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 26,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch83-ex-01',
      chapterNumber: 83,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['innerhalb', 'meaning'],
      instruction: 'Choose the meaning of the preposition.',
      prompt: 'What does innerhalb mean?',
      options: [
        { id: 'a', text: 'within, inside a bounded period' },
        { id: 'b', text: 'outside of a period' },
        { id: 'c', text: 'during the whole period' },
        { id: 'd', text: 'since a point in the past' },
      ],
      correctOptionId: 'a',
      explanation: 'innerhalb marks a bounded window inside which something must happen — "within".',
    },
    {
      id: 'ch83-ex-02',
      chapterNumber: 83,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['innerhalb', 'case-government', 'genitive'],
      instruction: 'Choose the case that this preposition governs.',
      prompt: 'Which case does innerhalb govern?',
      options: [
        { id: 'a', text: 'nominative' },
        { id: 'b', text: 'accusative' },
        { id: 'c', text: 'dative' },
        { id: 'd', text: 'genitive' },
      ],
      correctOptionId: 'd',
      explanation: 'innerhalb governs the genitive, like the other bounded-window and duration prepositions außerhalb and während.',
    },
    {
      id: 'ch83-ex-03',
      chapterNumber: 83,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['seit', 'case-government', 'dative'],
      instruction: 'Choose the case that this preposition governs.',
      prompt: 'Which case does seit govern?',
      options: [
        { id: 'a', text: 'genitive' },
        { id: 'b', text: 'accusative' },
        { id: 'c', text: 'dative' },
        { id: 'd', text: 'nominative' },
      ],
      correctOptionId: 'c',
      explanation: 'seit governs the dative, like the other starting-point and endpoint prepositions ab, bis zu, and von ... an.',
    },
    {
      id: 'ch83-ex-04',
      chapterNumber: 83,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['außerhalb', 'meaning'],
      instruction: 'Choose the meaning of the preposition.',
      prompt: 'What does außerhalb mean?',
      options: [
        { id: 'a', text: 'outside of a bounded period' },
        { id: 'b', text: 'within a bounded period' },
        { id: 'c', text: 'before a point in time' },
        { id: 'd', text: 'after a point in time' },
      ],
      correctOptionId: 'a',
      explanation: 'außerhalb is the mirror image of innerhalb: it marks everything lying outside a named window.',
    },
    {
      id: 'ch83-ex-05',
      chapterNumber: 83,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['innerhalb', 'preposition-choice'],
      instruction: 'Choose the phrase that means "within a week".',
      prompt: 'Which phrase means "within a week"?',
      options: [
        { id: 'a', text: 'innerhalb einer Woche' },
        { id: 'b', text: 'während einer Woche' },
        { id: 'c', text: 'seit einer Woche' },
        { id: 'd', text: 'bis zu einer Woche' },
      ],
      correctOptionId: 'a',
      explanation: 'innerhalb + genitive is the expression for a bounded deadline: "within a week".',
    },
    {
      id: 'ch83-ex-06',
      chapterNumber: 83,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['seit', 'preposition-choice'],
      instruction: 'Choose the correct preposition.',
      prompt: 'Ich wohne ___ einem Jahr in Berlin.',
      options: [
        { id: 'a', text: 'seit' },
        { id: 'b', text: 'ab' },
        { id: 'c', text: 'bis zu' },
        { id: 'd', text: 'während' },
      ],
      correctOptionId: 'a',
      explanation: 'The living arrangement began in the past and is still ongoing now, which is exactly the meaning of seit.',
    },
    {
      id: 'ch83-ex-07',
      chapterNumber: 83,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['innerhalb', 'genitive', 'inflection'],
      instruction: 'Choose the correctly inflected phrase.',
      prompt: 'Choose the correctly inflected phrase for "within a week".',
      options: [
        { id: 'a', text: 'innerhalb einer Woche' },
        { id: 'b', text: 'innerhalb eine Woche' },
        { id: 'c', text: 'innerhalb einem Woche' },
        { id: 'd', text: 'innerhalb eines Woche' },
      ],
      correctOptionId: 'a',
      explanation: 'die Woche is feminine; its genitive singular with the indefinite article is einer Woche.',
    },
    {
      id: 'ch83-ex-08',
      chapterNumber: 83,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['seit', 'dative', 'inflection'],
      instruction: 'Choose the correctly inflected phrase.',
      prompt: 'Choose the correctly inflected phrase for "for a year" / "since a year ago".',
      options: [
        { id: 'a', text: 'seit einem Jahr' },
        { id: 'b', text: 'seit einer Jahr' },
        { id: 'c', text: 'seit eines Jahres' },
        { id: 'd', text: 'seit ein Jahr' },
      ],
      correctOptionId: 'a',
      explanation: 'das Jahr is neuter; its dative singular with the indefinite article is einem Jahr.',
    },
    {
      id: 'ch83-ex-09',
      chapterNumber: 83,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ab', 'preposition-choice'],
      instruction: 'Choose the correct preposition.',
      prompt: '___ nächstem Montag arbeite ich in Berlin.',
      options: [
        { id: 'a', text: 'Ab' },
        { id: 'b', text: 'Seit' },
        { id: 'c', text: 'Bis' },
        { id: 'd', text: 'Während' },
      ],
      correctOptionId: 'a',
      explanation: 'A starting point in the future with no end named takes ab.',
    },
    {
      id: 'ch83-ex-10',
      chapterNumber: 83,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['bis-zu', 'preposition-choice'],
      instruction: 'Choose the correct preposition for the blank.',
      prompt: 'Die Bewerbung ist ___ den Ferien möglich.',
      options: [
        { id: 'a', text: 'bis zu' },
        { id: 'b', text: 'bis' },
        { id: 'c', text: 'seit' },
        { id: 'd', text: 'ab' },
      ],
      correctOptionId: 'a',
      explanation: 'Before an article-bearing noun phrase like den Ferien, bis needs the added zu and the dative case.',
    },
    {
      id: 'ch83-ex-11',
      chapterNumber: 83,
      order: 11,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['seit', 'ab', 'timeline-contrast', 'pragmatics'],
      instruction: 'Choose the preposition that fits the context of the dialogue.',
      dialogue: [
        {
          speaker: 'Interviewer',
          german: 'Seit wann arbeiten Sie schon bei dieser Firma?',
          english: 'Since when have you been working at this company?',
        },
        {
          speaker: 'Bewerberin',
          german: 'Ich arbeite ___ zwei Jahren bei dieser Firma, und ich möchte gerne bleiben.',
          english: "I've been working at this company for two years, and I'd like to stay.",
        },
      ],
      prompt: 'Ich arbeite ___ zwei Jahren bei dieser Firma.',
      options: [
        { id: 'a', text: 'seit' },
        { id: 'b', text: 'ab' },
        { id: 'c', text: 'bis zu' },
        { id: 'd', text: 'von ... an' },
      ],
      correctOptionId: 'a',
      explanation: 'The job began two years ago and is still ongoing now, which is the backward-looking, still-continuing meaning of seit, not the forward-looking ab.',
    },
    {
      id: 'ch83-ex-12',
      chapterNumber: 83,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['von-an', 'sentence-completion'],
      instruction: 'Choose the word that completes the fixed expression.',
      prompt: 'Von diesem Tag ___ gilt die neue Regel.',
      options: [
        { id: 'a', text: 'an' },
        { id: 'b', text: 'ab' },
        { id: 'c', text: 'zu' },
        { id: 'd', text: 'bis' },
      ],
      correctOptionId: 'a',
      explanation: 'von ... an is a fixed two-part frame; an closes the expression and cannot be replaced or dropped.',
    },
    {
      id: 'ch83-ex-13',
      chapterNumber: 83,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['innerhalb', 'während', 'deadline-interpretation'],
      instruction: 'Choose the sentence describing a deadline that can be met at any point inside the window.',
      prompt: 'Welcher Satz beschreibt eine Frist, die man jederzeit innerhalb des Zeitraums erfüllen kann?',
      options: [
        { id: 'a', text: 'Ich muss die Aufgabe innerhalb einer Woche abgeben.' },
        { id: 'b', text: 'Ich arbeite während der ganzen Woche an der Aufgabe.' },
        { id: 'c', text: 'Ich arbeite seit einer Woche an der Aufgabe.' },
        { id: 'd', text: 'Ich arbeite bis zu einer Woche an der Aufgabe.' },
      ],
      correctOptionId: 'a',
      explanation: 'innerhalb names a bounded window inside which the deadline can be met at any moment; während would mean the work fills the entire week.',
    },
    {
      id: 'ch83-ex-14',
      chapterNumber: 83,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['außerhalb', 'notice-rewriting'],
      instruction: 'Choose the sentence that correctly rewrites the notice with the same meaning.',
      prompt: 'Welcher Satz drückt denselben Sinn aus wie: "Das Büro ist am Wochenende nicht erreichbar."?',
      options: [
        { id: 'a', text: 'Das Büro ist außerhalb der Geschäftszeiten nicht erreichbar.' },
        { id: 'b', text: 'Das Büro ist innerhalb der Geschäftszeiten nicht erreichbar.' },
        { id: 'c', text: 'Das Büro ist seit den Geschäftszeiten nicht erreichbar.' },
        { id: 'd', text: 'Das Büro ist bis zu den Geschäftszeiten nicht erreichbar.' },
      ],
      correctOptionId: 'a',
      explanation: 'The weekend falls outside normal business hours, so außerhalb der Geschäftszeiten is the correct paraphrase; innerhalb would wrongly claim the office is unreachable during business hours.',
    },
    {
      id: 'ch83-ex-15',
      chapterNumber: 83,
      order: 15,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['innerhalb', 'fill-in'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: '___ einer Woche muss ich antworten. (within)',
      acceptedAnswers: ['innerhalb'],
      answerMode: 'caseInsensitive',
      placeholder: 'innerhalb',
      maxLength: 15,
      explanation: 'innerhalb marks the bounded window within which a response is due.',
    },
    {
      id: 'ch83-ex-16',
      chapterNumber: 83,
      order: 16,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['außerhalb', 'fill-in'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: 'Das Geschäft ist ___ der Geschäftszeiten geschlossen. (outside of)',
      acceptedAnswers: ['außerhalb'],
      answerMode: 'caseInsensitive',
      placeholder: 'außerhalb',
      maxLength: 15,
      explanation: 'außerhalb marks everything lying outside the named business hours.',
    },
    {
      id: 'ch83-ex-17',
      chapterNumber: 83,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['während', 'fill-in'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: '___ des Sommers arbeite ich in einem Café. (during)',
      acceptedAnswers: ['während'],
      answerMode: 'caseInsensitive',
      placeholder: 'während',
      maxLength: 15,
      explanation: 'während marks a duration that fills the entire named period, here the whole summer.',
    },
    {
      id: 'ch83-ex-18',
      chapterNumber: 83,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['seit', 'fill-in'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: 'Ich wohne ___ einem Jahr in Berlin. (since)',
      acceptedAnswers: ['seit'],
      answerMode: 'caseInsensitive',
      placeholder: 'seit',
      maxLength: 15,
      explanation: 'seit marks a starting point in the past that is still ongoing now.',
    },
    {
      id: 'ch83-ex-19',
      chapterNumber: 83,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['ab', 'fill-in'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: '___ nächstem Montag gilt die neue Regel. (from ... on)',
      acceptedAnswers: ['ab'],
      answerMode: 'caseInsensitive',
      placeholder: 'ab',
      maxLength: 15,
      explanation: 'ab marks an open-ended starting point in the present or future.',
    },
    {
      id: 'ch83-ex-20',
      chapterNumber: 83,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['bis-zu', 'fill-in'],
      instruction: 'Write the two missing words. Capitalisation is not checked.',
      prompt: 'Die Schule ist ___ ___ den Ferien geöffnet. (up until)',
      acceptedAnswers: ['bis zu'],
      answerMode: 'caseInsensitive',
      placeholder: 'bis zu',
      maxLength: 15,
      explanation: 'Before an article-bearing noun phrase, the endpoint is expressed with bis zu + dative.',
    },
    {
      id: 'ch83-ex-21',
      chapterNumber: 83,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['von-an', 'fill-in'],
      instruction: 'Write the missing word that closes the expression. Capitalisation is not checked.',
      prompt: 'Von diesem Tag ___ gilt die neue Regel.',
      acceptedAnswers: ['an'],
      answerMode: 'caseInsensitive',
      placeholder: 'an',
      maxLength: 15,
      explanation: 'von ... an is a fixed two-part frame; an closes it and marks the open-ended starting point.',
    },
    {
      id: 'ch83-ex-22',
      chapterNumber: 83,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['innerhalb', 'genitive', 'article-ending'],
      instruction: 'Complete the genitive article. Capitalisation is not checked.',
      prompt: 'Complete: innerhalb ___ Woche (genitive of eine)',
      acceptedAnswers: ['einer'],
      answerMode: 'caseInsensitive',
      placeholder: 'einer',
      maxLength: 15,
      explanation: 'die Woche is feminine; its genitive singular indefinite article is einer.',
    },
    {
      id: 'ch83-ex-23',
      chapterNumber: 83,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['während', 'genitive', 'article-ending'],
      instruction: 'Complete the genitive article. Capitalisation is not checked.',
      prompt: 'Complete: während ___ Sommers (der/des/dem)',
      acceptedAnswers: ['des'],
      answerMode: 'caseInsensitive',
      placeholder: 'des',
      maxLength: 15,
      explanation: 'der Sommer is masculine; its genitive singular definite article is des, and the noun itself adds -s: des Sommers.',
    },
    {
      id: 'ch83-ex-24',
      chapterNumber: 83,
      order: 24,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['seit', 'dative', 'article-ending'],
      instruction: 'Complete the dative article. Capitalisation is not checked.',
      prompt: 'Complete: seit ___ Jahr (dative of ein)',
      acceptedAnswers: ['einem'],
      answerMode: 'caseInsensitive',
      placeholder: 'einem',
      maxLength: 15,
      explanation: 'das Jahr is neuter; its dative singular indefinite article is einem.',
    },
    {
      id: 'ch83-ex-25',
      chapterNumber: 83,
      order: 25,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['ab', 'dative', 'adjective-ending'],
      instruction: 'Complete the strong dative ending. Capitalisation is not checked.',
      prompt: 'Complete: ab nächst___ Montag (dative strong ending)',
      acceptedAnswers: ['nächstem'],
      answerMode: 'caseInsensitive',
      placeholder: 'nächstem',
      maxLength: 15,
      explanation: 'With no article present, the adjective before a masculine dative singular noun takes the strong ending -em: nächstem Montag.',
    },
    {
      id: 'ch83-ex-26',
      chapterNumber: 83,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['innerhalb', 'genitive', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Innerhalb einem Jahr melde ich mich.',
      acceptedAnswers: ['Innerhalb eines Jahres melde ich mich.'],
      answerMode: 'normalized',
      placeholder: 'Innerhalb eines Jahres ...',
      maxLength: 60,
      explanation: 'innerhalb governs the genitive, not the dative; einem Jahr must become eines Jahres.',
    },
    {
      id: 'ch83-ex-27',
      chapterNumber: 83,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['seit', 'dative', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Seit einen Monat lerne ich Deutsch.',
      acceptedAnswers: ['Seit einem Monat lerne ich Deutsch.'],
      answerMode: 'normalized',
      placeholder: 'Seit einem Monat ...',
      maxLength: 60,
      explanation: 'seit governs the dative, not the accusative; einen Monat must become einem Monat.',
    },
    {
      id: 'ch83-ex-28',
      chapterNumber: 83,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['bis-zu', 'sentence-formation', 'notice-rewriting'],
      instruction:
        'Write a complete notice sentence using the cues and the correct preposition. Capitalisation is checked; no full stop is required.',
      prompt: 'die Bewerbung – möglich sein – bis zu – die Ferien',
      acceptedAnswers: ['Die Bewerbung ist bis zu den Ferien möglich.', 'Die Bewerbung ist bis zu den Ferien möglich'],
      answerMode: 'normalized',
      placeholder: 'Die Bewerbung ist bis zu ...',
      maxLength: 60,
      explanation: 'bis zu + dative names the closing endpoint of the registration window: bis zu den Ferien.',
    },
  ],
};
