import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter017: ChapterDefinition = {
  id: 'chapter-017',
  number: 17,
  slug: 'the-accusative-case',
  title: 'The Accusative Case',
  germanTitle: 'Der Akkusativ',
  level: 'A1',
  section: 'pronouns-nouns-articles',
  objective:
    'Recognise the direct object of a sentence and put its article into the correct accusative form, especially the masculine changes der → den and ein → einen.',
  prerequisites: [15],
  estimatedMinutes: 25,
  tags: ['accusative-case', 'direct-object', 'articles', 'wen-was'],
  explanation: {
    introduction: [
      'Every German noun phrase has a case that shows what job it does in the sentence. So far you have used the nominative case for the subject — the person or thing doing the action. This chapter introduces the accusative case, which marks the direct object: the person or thing that the action is directly done to.',
      'In Ich kaufe einen Apfel (I am buying an apple), Ich is the subject (nominative) and einen Apfel is the direct object (accusative). The noun Apfel does not change, but its article does — ein becomes einen. Learning exactly which articles change, and which stay the same, is the main goal of this chapter.',
    ],
    rules: [
      {
        id: 'ch17-rule-01',
        heading: 'What the accusative case marks',
        paragraphs: [
          'The accusative case marks the direct object of a sentence — the person or thing that directly receives the action of the verb. In Ich kaufe einen Apfel (I am buying an apple), einen Apfel is the direct object: it is the thing being bought.',
          'German nouns themselves almost never change their spelling for the accusative. What changes is the article or determiner standing in front of the noun — and that article change is what this chapter focuses on.',
        ],
      },
      {
        id: 'ch17-rule-02',
        heading: 'The definite article: der becomes den',
        paragraphs: [
          'When a masculine noun is the direct object, its definite article der changes to den. Feminine die, neuter das and plural die stay exactly as they are in the nominative.',
          'Der Hund is fine in the nominative (Der Hund ist müde), but as a direct object it becomes den Hund (Ich sehe den Hund).',
        ],
        notes: [
          'Only masculine singular nouns are affected — this is the single most important article change to memorise for the accusative.',
        ],
      },
      {
        id: 'ch17-rule-03',
        heading: 'The indefinite article: ein becomes einen',
        paragraphs: [
          'The same pattern applies to the indefinite article: masculine ein becomes einen in the accusative, while feminine eine and neuter ein stay unchanged.',
          'Ich brauche einen Regenschirm (I need an umbrella) — Regenschirm is masculine, so ein becomes einen.',
        ],
        notes: [
          'Possessive determiners such as mein and dein, and the negative article kein, follow the same masculine pattern: mein Bruder → meinen Bruder.',
        ],
      },
      {
        id: 'ch17-rule-04',
        heading: 'A first look at accusative personal pronouns',
        paragraphs: [
          'Personal pronouns also have their own accusative forms: ich becomes mich, du becomes dich, er becomes ihn, and so on. Sie (she) and es (it) look the same in the accusative as in the nominative.',
          'Kennst du Peter? – Ja, ich kenne ihn. (Do you know Peter? – Yes, I know him.) You will meet the complete set of accusative pronouns in a later chapter; for now, just recognise that these forms exist and that ihn is a very common one.',
        ],
      },
      {
        id: 'ch17-rule-05',
        heading: 'Verbs that take an accusative object',
        paragraphs: [
          'Many everyday verbs are followed directly by an accusative object, with no preposition in between: haben, kaufen, sehen, suchen, brauchen, essen, trinken, lesen, kennen and lieben are some of the most common.',
          'Ich habe einen Hund. Wir essen das Brot. Sie liest ein Buch. — in each sentence, the noun phrase right after the verb is the accusative direct object.',
        ],
      },
      {
        id: 'ch17-rule-06',
        heading: 'Asking about the direct object: wen and was',
        paragraphs: [
          'To ask about a direct object, German uses wen for people and was for things — just as English uses whom (or who) for people and what for things.',
          'Wen siehst du? – Ich sehe meinen Lehrer. Was kaufst du? – Ich kaufe einen Tisch.',
        ],
        notes: [
          'wen is the accusative form of wer; compare Wer ist das? (nominative, subject) with Wen siehst du? (accusative, object).',
        ],
      },
    ],
    tables: [
      {
        id: 'ch17-table-01',
        title: 'Articles: nominative vs accusative',
        columns: ['Gender', 'Nominative', 'Accusative', 'Example'],
        rows: [
          ['masculine', 'der / ein', 'den / einen', 'den Mann / einen Mann'],
          ['feminine', 'die / eine', 'die / eine', 'die Frau / eine Frau'],
          ['neuter', 'das / ein', 'das / ein', 'das Kind / ein Kind'],
          ['plural', 'die / –', 'die / –', 'die Kinder'],
        ],
        note: 'The masculine singular is the only form that changes between nominative and accusative.',
      },
      {
        id: 'ch17-table-02',
        title: 'Preview: accusative personal pronouns',
        columns: ['Nominative', 'Accusative'],
        rows: [
          ['ich', 'mich'],
          ['du', 'dich'],
          ['er', 'ihn'],
          ['sie (she)', 'sie'],
          ['es', 'es'],
          ['wir', 'uns'],
          ['ihr', 'euch'],
          ['sie / Sie (they / you formal)', 'sie / Sie'],
        ],
        note: 'A full chapter on personal pronouns follows later — for now, just get used to seeing these forms.',
      },
    ],
    examples: [
      {
        german: 'Ich kaufe einen Apfel.',
        english: 'I am buying an apple.',
        highlight: ['einen Apfel'],
        explanation: 'Apfel is masculine, so the indefinite article ein becomes einen as the direct object.',
      },
      {
        german: 'Er sieht den Hund.',
        english: 'He sees the dog.',
        highlight: ['den Hund'],
        explanation: 'Hund is masculine, so the definite article der becomes den as the direct object.',
      },
      {
        german: 'Wir brauchen einen Regenschirm.',
        english: 'We need an umbrella.',
        highlight: ['einen Regenschirm'],
      },
      {
        german: 'Sie sucht die Tasche.',
        english: 'She is looking for the bag.',
        highlight: ['die Tasche'],
        explanation: 'Tasche is feminine, so die stays die in the accusative.',
      },
      {
        german: 'Ich esse das Brot.',
        english: 'I am eating the bread.',
        highlight: ['das Brot'],
        explanation: 'Brot is neuter, so das stays das in the accusative.',
      },
      {
        german: 'Trinkst du den Kaffee?',
        english: 'Are you drinking the coffee?',
        highlight: ['den Kaffee'],
      },
      {
        german: 'Hast du einen Bruder?',
        english: 'Do you have a brother?',
        highlight: ['einen Bruder'],
      },
      {
        german: 'Wen siehst du? – Ich sehe den Lehrer.',
        english: 'Whom do you see? – I see the teacher.',
        highlight: ['Wen', 'den Lehrer'],
        explanation: 'The answer names a person, so the question about the direct object uses wen.',
      },
      {
        german: 'Was kaufst du? – Ich kaufe einen Tisch.',
        english: 'What are you buying? – I am buying a table.',
        highlight: ['Was', 'einen Tisch'],
        explanation: 'The answer names a thing, so the question about the direct object uses was.',
      },
      {
        german: 'Kennst du meine Schwester? – Ja, ich kenne sie.',
        english: 'Do you know my sister? – Yes, I know her.',
        highlight: ['sie'],
        explanation: 'sie (her) is the accusative form used here — for feminine nouns it looks the same as the nominative.',
      },
      {
        german: 'Die Kinder essen die Äpfel.',
        english: 'The children are eating the apples.',
        highlight: ['die Äpfel'],
        explanation: 'Äpfel is plural, so die stays die in the accusative, just as it does in the nominative.',
      },
      {
        german: 'Ich liebe dich.',
        english: 'I love you.',
        highlight: ['dich'],
        explanation: 'dich is the accusative form of du, used here as the direct object of lieben.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich sehe der Hund.',
        correct: 'Ich sehe den Hund.',
        explanation:
          'Hund is masculine and is the direct object of sehen, so the definite article der must change to den in the accusative.',
      },
      {
        incorrect: 'Ich habe ein Bruder.',
        correct: 'Ich habe einen Bruder.',
        explanation:
          'Bruder is masculine, and as the direct object of haben the indefinite article ein must become einen.',
      },
      {
        incorrect: 'Ich sehe den Frau.',
        correct: 'Ich sehe die Frau.',
        explanation:
          'Frau is feminine. Only the masculine article changes in the accusative (der → den); feminine die stays die.',
      },
      {
        incorrect: 'Was siehst du? – Ich sehe meinen Lehrer.',
        correct: 'Wen siehst du? – Ich sehe meinen Lehrer.',
        explanation:
          'Because the answer names a person (Lehrer), the question about the direct object must use wen, not was.',
      },
    ],
    remember: [
      'The accusative case marks the direct object — the person or thing directly affected by the verb.',
      'Only the masculine article changes: der → den, ein → einen. Feminine, neuter and plural articles stay the same as in the nominative.',
      'wen asks about a person in the accusative; was asks about a thing.',
      'Common accusative verbs: haben, kaufen, sehen, suchen, brauchen, essen, trinken.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch17-ex-01',
      chapterNumber: 17,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['accusative-case', 'direct-object'],
      instruction: 'Identify the direct object in the sentence.',
      prompt: 'Ich kaufe einen Apfel.',
      options: [
        { id: 'a', text: 'Ich' },
        { id: 'b', text: 'kaufe' },
        { id: 'c', text: 'einen Apfel' },
      ],
      correctOptionId: 'c',
      explanation:
        'einen Apfel is the direct object — the thing directly affected by the action of buying. It answers the question was kaufst du?',
    },
    {
      id: 'ch17-ex-02',
      chapterNumber: 17,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['accusative-case', 'definite-article', 'masculine'],
      instruction: 'Choose the correct article for the direct object.',
      prompt: 'Der Mann sieht ___ Hund.',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'die' },
        { id: 'd', text: 'das' },
      ],
      correctOptionId: 'b',
      explanation:
        'Hund is masculine and is the direct object of sehen, so the definite article der becomes den in the accusative.',
    },
    {
      id: 'ch17-ex-03',
      chapterNumber: 17,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['accusative-case', 'indefinite-article', 'masculine'],
      instruction: 'Choose the correct article for the direct object.',
      prompt: 'Ich brauche ___ Regenschirm.',
      options: [
        { id: 'a', text: 'ein' },
        { id: 'b', text: 'eine' },
        { id: 'c', text: 'einen' },
        { id: 'd', text: 'der' },
      ],
      correctOptionId: 'c',
      explanation:
        'Regenschirm is masculine and is the direct object of brauchen, so the indefinite article ein becomes einen in the accusative.',
    },
    {
      id: 'ch17-ex-04',
      chapterNumber: 17,
      order: 4,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'definite-article', 'feminine'],
      instruction: 'Choose the correct article for the direct object.',
      prompt: 'Er sucht ___ Tasche.',
      options: [
        { id: 'a', text: 'die' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'der' },
        { id: 'd', text: 'das' },
      ],
      correctOptionId: 'a',
      explanation:
        'Tasche is feminine; feminine articles are identical in the nominative and accusative, so die stays die.',
    },
    {
      id: 'ch17-ex-05',
      chapterNumber: 17,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'definite-article', 'neuter'],
      instruction: 'Choose the correct article for the direct object.',
      prompt: 'Wir essen ___ Brot.',
      options: [
        { id: 'a', text: 'das' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'die' },
        { id: 'd', text: 'dem' },
      ],
      correctOptionId: 'a',
      explanation: 'Brot is neuter; neuter das does not change in the accusative.',
    },
    {
      id: 'ch17-ex-06',
      chapterNumber: 17,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'definite-article', 'plural'],
      instruction: 'Choose the correct article for the direct object.',
      prompt: 'Ich sehe ___ Kinder.',
      options: [
        { id: 'a', text: 'die' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'das' },
        { id: 'd', text: 'der' },
      ],
      correctOptionId: 'a',
      explanation: 'Plural direct objects use die, exactly as in the nominative plural.',
    },
    {
      id: 'ch17-ex-07',
      chapterNumber: 17,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'masculine', 'verb-object'],
      instruction: 'Which sentence is grammatically correct?',
      prompt: 'sehen + der Hund',
      options: [
        { id: 'a', text: 'Ich sehe der Hund.' },
        { id: 'b', text: 'Ich sehe den Hund.' },
        { id: 'c', text: 'Ich sehe das Hund.' },
      ],
      correctOptionId: 'b',
      explanation:
        'Hund is masculine, and as the direct object of sehen the article der must become den.',
    },
    {
      id: 'ch17-ex-08',
      chapterNumber: 17,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wen', 'question-words'],
      instruction: 'Choose the correct question word.',
      prompt: '___ siehst du? – Ich sehe meinen Lehrer.',
      options: [
        { id: 'a', text: 'Wen' },
        { id: 'b', text: 'Was' },
        { id: 'c', text: 'Wer' },
        { id: 'd', text: 'Wo' },
      ],
      correctOptionId: 'a',
      explanation:
        'The answer names a person (Lehrer), so the question about the direct object uses wen, not was.',
    },
    {
      id: 'ch17-ex-09',
      chapterNumber: 17,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['was', 'question-words'],
      instruction: 'Choose the correct question word.',
      prompt: '___ kaufst du? – Ich kaufe einen Tisch.',
      options: [
        { id: 'a', text: 'Was' },
        { id: 'b', text: 'Wen' },
        { id: 'c', text: 'Wo' },
        { id: 'd', text: 'Wie' },
      ],
      correctOptionId: 'a',
      explanation: 'The answer is a thing (Tisch), so was is used to ask about the direct object, not wen.',
    },
    {
      id: 'ch17-ex-10',
      chapterNumber: 17,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['accusative-pronouns', 'preview'],
      instruction: 'Choose the correct pronoun.',
      prompt: 'Kennst du Peter? – Ja, ich kenne ___.',
      options: [
        { id: 'a', text: 'er' },
        { id: 'b', text: 'ihn' },
        { id: 'c', text: 'ihm' },
        { id: 'd', text: 'es' },
      ],
      correctOptionId: 'b',
      explanation:
        'er changes to ihn in the accusative when replacing a masculine direct object like Peter; the full pronoun system follows in a later chapter.',
    },
    {
      id: 'ch17-ex-11',
      chapterNumber: 17,
      order: 11,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['accusative-case', 'word-order', 'subject-object'],
      instruction: 'Choose the sentence that correctly says: The woman sees the man.',
      prompt: '"The woman sees the man."',
      options: [
        { id: 'a', text: 'Der Mann sieht die Frau.' },
        { id: 'b', text: 'Die Frau sieht den Mann.' },
        { id: 'c', text: 'Die Frau sieht der Mann.' },
        { id: 'd', text: 'Den Frau sieht der Mann.' },
      ],
      correctOptionId: 'b',
      explanation:
        'Die Frau is the subject (nominative, unchanged for feminine) and den Mann is the direct object (masculine der becomes den).',
    },
    {
      id: 'ch17-ex-12',
      chapterNumber: 17,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['accusative-case', 'neuter', 'indefinite-article'],
      instruction: 'Choose the sentence that correctly says: The child has a book.',
      prompt: '"The child has a book."',
      options: [
        { id: 'a', text: 'Das Kind hat ein Buch.' },
        { id: 'b', text: 'Das Kind hat einen Buch.' },
        { id: 'c', text: 'Der Kind hat ein Buch.' },
        { id: 'd', text: 'Das Kind hat eine Buch.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Buch is neuter, so the indefinite article ein does not change in the accusative; the correct object form is ein Buch.',
    },
    {
      id: 'ch17-ex-13',
      chapterNumber: 17,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'definite-article', 'masculine'],
      instruction: 'Complete the sentence with the correct accusative article. Capitalisation is not checked.',
      prompt: 'Ich sehe ___ Hund. (der Hund)',
      acceptedAnswers: ['den'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 5,
      explanation: 'Hund is masculine; as the direct object of sehen, der becomes den.',
    },
    {
      id: 'ch17-ex-14',
      chapterNumber: 17,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'indefinite-article', 'masculine'],
      instruction: 'Complete the sentence with the correct accusative article. Capitalisation is not checked.',
      prompt: 'Ich habe ___ Bruder. (ein Bruder)',
      acceptedAnswers: ['einen'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 10,
      explanation: 'Bruder is masculine; the indefinite article ein becomes einen in the accusative.',
    },
    {
      id: 'ch17-ex-15',
      chapterNumber: 17,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'definite-article', 'feminine'],
      instruction: 'Complete the sentence with the correct accusative article. Capitalisation is not checked.',
      prompt: 'Ich suche ___ Schwester. (die Schwester)',
      acceptedAnswers: ['die'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 5,
      explanation: 'Schwester is feminine; die stays die in the accusative.',
    },
    {
      id: 'ch17-ex-16',
      chapterNumber: 17,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'definite-article', 'neuter'],
      instruction: 'Complete the sentence with the correct accusative article. Capitalisation is not checked.',
      prompt: 'Wir trinken ___ Wasser. (das Wasser)',
      acceptedAnswers: ['das'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 5,
      explanation: 'Wasser is neuter; das stays das in the accusative.',
    },
    {
      id: 'ch17-ex-17',
      chapterNumber: 17,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'definite-article', 'plural'],
      instruction: 'Complete the sentence with the correct accusative article. Capitalisation is not checked.',
      prompt: 'Ich kaufe ___ Äpfel. (die Äpfel)',
      acceptedAnswers: ['die'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 5,
      explanation: 'Plural nouns use die in both the nominative and the accusative.',
    },
    {
      id: 'ch17-ex-18',
      chapterNumber: 17,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['accusative-case', 'masculine', 'nominative-to-accusative'],
      instruction: 'Change the nominative phrase into its accusative form. Capitalisation is not checked.',
      prompt: 'der Tisch → Ich kaufe ___.',
      acceptedAnswers: ['den Tisch'],
      answerMode: 'caseInsensitive',
      placeholder: 'den ...',
      maxLength: 20,
      explanation: 'Tisch is masculine, so der becomes den in the accusative: den Tisch.',
    },
    {
      id: 'ch17-ex-19',
      chapterNumber: 17,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wen', 'question-words'],
      instruction: 'Write the missing question word. Capitalisation is not checked.',
      prompt: '___ siehst du? – Ich sehe meine Mutter.',
      acceptedAnswers: ['wen'],
      answerMode: 'caseInsensitive',
      placeholder: 'question word',
      maxLength: 10,
      explanation: 'The answer is a person, so wen is used to ask about the accusative direct object.',
    },
    {
      id: 'ch17-ex-20',
      chapterNumber: 17,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['accusative-case', 'masculine', 'verb-object'],
      instruction:
        'Write a complete sentence using the cue words. Capitalisation and punctuation are checked.',
      prompt: 'ich – kaufen – ein Regenschirm',
      acceptedAnswers: ['Ich kaufe einen Regenschirm.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'Regenschirm is masculine, so the indefinite article ein becomes einen as the direct object of kaufen: Ich kaufe einen Regenschirm.',
    },
    {
      id: 'ch17-ex-21',
      chapterNumber: 17,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['accusative-case', 'masculine', 'verb-object'],
      instruction:
        'Write a complete sentence using the cue words. Capitalisation and punctuation are checked.',
      prompt: 'wir – brauchen – ein Tisch',
      acceptedAnswers: ['Wir brauchen einen Tisch.'],
      answerMode: 'normalized',
      placeholder: 'Wir ...',
      maxLength: 60,
      explanation:
        'Tisch is masculine, so the direct object of brauchen takes the accusative form einen Tisch.',
    },
    {
      id: 'ch17-ex-22',
      chapterNumber: 17,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['accusative-case', 'neuter', 'verb-object'],
      instruction:
        'Write a complete sentence using the cue words. Capitalisation and punctuation are checked.',
      prompt: 'er – essen – das Brot',
      acceptedAnswers: ['Er isst das Brot.'],
      answerMode: 'normalized',
      placeholder: 'Er ...',
      maxLength: 60,
      explanation:
        'essen has a stem-vowel change in the er-form (isst); Brot is neuter, so its article das stays das in the accusative.',
    },
    {
      id: 'ch17-ex-23',
      chapterNumber: 17,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['wen', 'question-words', 'word-order'],
      instruction:
        'Write the question (using wen) that this sentence answers. Capitalisation and the question mark are checked.',
      prompt: 'Answer: Ich sehe den Lehrer.',
      acceptedAnswers: ['Wen siehst du?'],
      answerMode: 'normalized',
      placeholder: 'Wen ...',
      maxLength: 40,
      explanation:
        'den Lehrer is a person, so the question uses wen; the finite verb siehst stands in position two, right after the question word.',
    },
    {
      id: 'ch17-ex-24',
      chapterNumber: 17,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['was', 'question-words', 'word-order'],
      instruction:
        'Write the question (using was) that this sentence answers. Capitalisation and the question mark are checked.',
      prompt: 'Answer: Ich kaufe einen Tisch.',
      acceptedAnswers: ['Was kaufst du?'],
      answerMode: 'normalized',
      placeholder: 'Was ...',
      maxLength: 40,
      explanation:
        'einen Tisch is a thing, so the question uses was; the finite verb kaufst stands in position two, right after the question word.',
    },
  ],
};
