import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter046: ChapterDefinition = {
  id: 'chapter-046',
  number: 46,
  slug: 'subordinate-clauses-with-weil-wenn-and-dass',
  title: 'Subordinate Clauses with weil, wenn, and dass',
  germanTitle: 'Nebensätze mit weil, wenn und dass',
  level: 'A2',
  section: 'sentence-connections-1',
  objective:
    'Form subordinate clauses with weil, wenn, and dass by moving the finite verb to the end of the clause, punctuate correctly with a comma between clauses, choose the right connector for a causal, conditional/temporal, or content clause, and apply inversion (verb immediately after the comma) when the subordinate clause opens the sentence.',
  prerequisites: [13, 44, 45],
  estimatedMinutes: 30,
  tags: [
    'subordinate clauses',
    'weil',
    'wenn',
    'dass',
    'verb-final word order',
    'nebensatz',
    'connectors',
    'inversion',
    'comma rules',
  ],
  explanation: {
    introduction: [
      'So far, connectors like und, aber, denn, and deshalb have joined two independent main clauses, each with its own verb in position 2 (Chapters 44–45). This chapter introduces a different kind of connector: subordinating conjunctions. weil (because), wenn (if/when), and dass (that) attach a subordinate clause to a main clause, and that subordinate clause cannot stand alone — its finite verb no longer sits in position 2 but moves all the way to the end of the clause.',
      "The three connectors cover three common jobs: weil gives a reason (answering warum?), wenn states a condition or a repeated/future time, and dass reports a fact, thought, or statement. In every case the rules are the same: put the finite verb last, put a comma between the clauses, and remember that either clause can come first — but if the subordinate clause comes first, the main clause's verb jumps to the position right after the comma.",
    ],
    rules: [
      {
        id: 'ch46-rule-01',
        heading: 'Subordinating conjunctions send the verb to the end',
        paragraphs: [
          'weil, wenn, and dass are subordinating conjunctions: they introduce a subordinate clause that cannot stand alone as a full sentence. Unlike coordinating conjunctions such as und, aber, or denn (Chapter 44), a subordinating conjunction pushes the finite (conjugated) verb all the way to the end of its clause.',
          'Compare the main clause Ich bleibe zu Hause (verb in position 2) with the subordinate clause weil ich krank bin (verb bin at the very end). The subject follows the conjunction directly, and everything else — objects, adverbs, negation — comes before the final verb.',
        ],
      },
      {
        id: 'ch46-rule-02',
        heading: 'weil — giving a reason (causal clauses)',
        paragraphs: [
          "weil answers the question warum? (why?) and introduces a reason or cause. It corresponds to English 'because'.",
          'Warum lernst du Deutsch? — Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.',
        ],
      },
      {
        id: 'ch46-rule-03',
        heading: 'wenn — conditions and repeated or future time',
        paragraphs: [
          "wenn introduces a condition ('if') or a repeated, habitual, or future point in time ('when(ever)'). It corresponds to both English 'if' and 'when' for repeated or future events; for a single completed event in the past, German uses als instead (a later chapter), so wenn is safe for present, future, and repeated situations.",
          "Wenn es regnet, bleiben wir zu Hause. (If it rains, we stay home — a general condition.) Wenn ich Zeit habe, rufe ich dich an. (When(ever) I have time, I'll call you.)",
        ],
      },
      {
        id: 'ch46-rule-04',
        heading: 'dass — reporting a fact, thought, or statement (content clauses)',
        paragraphs: [
          "dass introduces a content clause that reports what someone thinks, says, knows, hopes, or believes. It corresponds to English 'that' and is common after verbs like sagen, glauben, denken, wissen, hoffen, meinen, and after expressions like es ist schade, dass ....",
          'Ich glaube, dass er recht hat. Er hat gesagt, dass er heute keine Zeit hat.',
        ],
      },
      {
        id: 'ch46-rule-05',
        heading: 'A comma always separates the two clauses',
        paragraphs: [
          'German always places a comma between a main clause and a subordinate clause, no matter which order they appear in. The comma is not optional and does not depend on clause length.',
          'Ich bleibe zu Hause, weil ich krank bin. / Weil ich krank bin, bleibe ich zu Hause.',
        ],
      },
      {
        id: 'ch46-rule-06',
        heading: 'The subordinate clause can come first or second',
        paragraphs: [
          'A subordinate clause with weil, wenn, or dass can either follow the main clause (the more common, neutral order) or precede it for emphasis. Both orders are grammatical.',
          'Note that dass-clauses almost always follow the main clause, since a content clause reporting what someone said or thinks naturally comes after the verb it depends on (sagen, glauben, ...); weil- and wenn-clauses front more freely.',
        ],
      },
      {
        id: 'ch46-rule-07',
        heading:
          "Inversion: when the subordinate clause comes first, the main-clause verb comes right after the comma",
        paragraphs: [
          "In a German sentence, the finite verb of the main clause always occupies position 2 — but position 2 counts clause elements, not words. When an entire subordinate clause opens the sentence, it fills position 1 by itself, so the main clause's finite verb must immediately follow the comma, before its own subject.",
          'Weil ich krank bin, bleibe ich zu Hause. (subordinate clause = position 1; bleibe = position 2, right after the comma; ich = subject, now after the verb.) Compare the everyday order Ich bleibe zu Hause, weil ich krank bin, where bleibe already sits in position 2 of the main clause.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch46-table-01',
        title: 'Main-clause vs. subordinate-clause word order',
        columns: ['Connector', 'Main clause (verb = position 2)', 'Subordinate clause (verb = final)'],
        rows: [
          ['weil (because)', 'Ich bleibe zu Hause.', 'weil ich krank bin.'],
          ['wenn (if / when(ever))', 'Wir gehen spazieren.', 'wenn das Wetter schön ist.'],
          ['dass (that)', 'Er hat recht.', 'dass er recht hat.'],
        ],
        note: 'In each subordinate clause the finite verb (bin, ist, hat) moves from position 2 to the very end of the clause; everything else keeps its normal order in front of it.',
      },
      {
        id: 'ch46-table-02',
        title: 'Inversion: verb position when the subordinate clause comes first',
        columns: ['Normal order (main clause first)', 'Subordinate clause first (inversion)'],
        rows: [
          ['Ich bleibe zu Hause, weil ich krank bin.', 'Weil ich krank bin, bleibe ich zu Hause.'],
          [
            'Wir gehen spazieren, wenn das Wetter schön ist.',
            'Wenn das Wetter schön ist, gehen wir spazieren.',
          ],
          ['Ich rufe dich an, wenn ich Zeit habe.', 'Wenn ich Zeit habe, rufe ich dich an.'],
        ],
        note: 'dass-clauses are rarely fronted this way, because a content clause naturally follows the verb it depends on (sagen, glauben, ...).',
      },
    ],
    examples: [
      {
        german: 'Ich bleibe zu Hause, weil ich krank bin.',
        english: "I'm staying home because I'm sick.",
        highlight: ['weil ich krank bin'],
        explanation: 'weil sends the finite verb bin to the end of its clause.',
      },
      {
        german: 'Wir gehen spazieren, wenn das Wetter schön ist.',
        english: 'We go for a walk when/if the weather is nice.',
        highlight: ['wenn das Wetter schön ist'],
        explanation: 'wenn introduces a condition; the verb ist stands at the end.',
      },
      {
        german: 'Ich glaube, dass er recht hat.',
        english: 'I believe that he is right.',
        highlight: ['dass er recht hat'],
        explanation: 'dass introduces what ich glaube reports; the verb hat moves to the end.',
      },
      {
        german: 'Er ist nie müde, weil er früh aufsteht.',
        english: 'He is never tired because he gets up early.',
        highlight: ['aufsteht'],
        explanation:
          'The separable verb aufstehen stays joined as a single word (aufsteht) at the end of the subordinate clause.',
      },
      {
        german: 'Ich kann nicht kommen, weil ich arbeiten muss.',
        english: "I can't come because I have to work.",
        highlight: ['arbeiten muss'],
        explanation: 'The modal verb muss goes to the very end; the infinitive arbeiten comes right before it.',
      },
      {
        german: 'Sie ist glücklich, weil sie die Prüfung bestanden hat.',
        english: 'She is happy because she passed the exam.',
        highlight: ['bestanden hat'],
        explanation:
          'In the perfect tense, the past participle (bestanden) and the auxiliary (hat) both move to the end, with hat last.',
      },
      {
        german: 'Immer wenn es regnet, nehme ich einen Regenschirm mit.',
        english: 'Whenever it rains, I take an umbrella.',
        highlight: ['Immer wenn es regnet'],
        explanation: 'wenn also introduces repeated or habitual situations, often signalled by immer (always).',
      },
      {
        german: 'Ich hoffe, dass du bald wieder gesund bist.',
        english: 'I hope that you get well again soon.',
        highlight: ['dass du bald wieder gesund bist'],
        explanation: 'dass introduces the content of what ich hoffe; the verb bist stands at the end.',
      },
      {
        german: 'Weil ich krank bin, bleibe ich zu Hause.',
        english: 'Because I am sick, I am staying home.',
        highlight: ['bleibe ich'],
        explanation:
          'The subordinate clause fills position 1, so the main-clause verb bleibe follows immediately after the comma.',
      },
      {
        german: 'Wenn ich Zeit habe, rufe ich dich an.',
        english: "When I have time, I'll call you.",
        highlight: ['rufe ich'],
        explanation:
          'The wenn-clause fills position 1, so the verb rufe comes right after the comma, before its subject ich.',
      },
      {
        german: 'Wir bleiben im Garten, wenn es nicht regnet.',
        english: "We'll stay in the garden if it doesn't rain.",
        highlight: ['wenn es nicht regnet'],
        explanation: 'A comma always separates the main clause from the subordinate clause, regardless of order.',
      },
      {
        german: 'Er sagt, dass er heute keine Zeit hat.',
        english: 'He says that he has no time today.',
        highlight: ['dass er heute keine Zeit hat'],
        explanation: 'Negation (keine) stays in its normal place before the final verb hat.',
      },
      {
        german: 'Warum weinst du? — Ich weine, weil der Film so traurig ist.',
        english: "Why are you crying? — I'm crying because the film is so sad.",
        highlight: ['weil der Film so traurig ist'],
        explanation: 'weil directly answers a warum-question; the verb ist stands at the end of the reason clause.',
      },
      {
        german: 'Die Wettervorhersage sagt, dass es morgen schneit.',
        english: 'The weather forecast says that it will snow tomorrow.',
        highlight: ['dass es morgen schneit'],
        explanation: 'dass reports the content of the forecast; the verb schneit moves to the end.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich bleibe zu Hause, weil ich bin krank.',
        correct: 'Ich bleibe zu Hause, weil ich krank bin.',
        explanation:
          'weil sends the finite verb to the very end of its clause; bin cannot stay in position 2 as it would in a main clause.',
      },
      {
        incorrect: 'Weil es regnet, wir bleiben zu Hause.',
        correct: 'Weil es regnet, bleiben wir zu Hause.',
        explanation:
          'When the subordinate clause comes first, the main-clause verb must come immediately after the comma (position 2), before its subject.',
      },
      {
        incorrect: 'Ich glaube, dass er hat recht.',
        correct: 'Ich glaube, dass er recht hat.',
        explanation:
          'dass also sends the finite verb to the end of its clause; hat cannot appear directly after the subject as it would in a main clause.',
      },
      {
        incorrect: 'Ich bin müde, weil ich habe die ganze Nacht gelernt.',
        correct: 'Ich bin müde, weil ich die ganze Nacht gelernt habe.',
        explanation:
          'In the perfect tense inside a subordinate clause, both the participle (gelernt) and the auxiliary (habe) move to the end, with the auxiliary last.',
      },
      {
        incorrect: 'Ich weiß, das er recht hat.',
        correct: 'Ich weiß, dass er recht hat.',
        explanation:
          'dass (with two s, the conjunction "that") is often confused with das (the article/pronoun "the/that"); only dass introduces this kind of subordinate clause.',
      },
    ],
    remember: [
      'weil, wenn, and dass are subordinating conjunctions: they push the finite verb to the very end of their clause.',
      'weil = because (reason), wenn = if/when(ever) (condition or repeated time), dass = that (reporting a fact, thought, or statement).',
      'A comma always separates the main clause from the subordinate clause, whichever order they appear in.',
      'The subordinate clause can come before or after the main clause; both orders are grammatical.',
      'When the subordinate clause comes first, it fills position 1 by itself, so the main-clause verb must come immediately after the comma, before its subject.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 28,
    requiredCorrectTextInputs: 5,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch46-ex-01',
      chapterNumber: 46,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['weil', 'verb-final', 'subordinate-clause'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I\'m staying home because I\'m sick." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich bleibe zu Hause, weil ich bin krank.' },
        { id: 'b', text: 'Ich bleibe zu Hause, weil ich krank bin.' },
        { id: 'c', text: 'Ich bleibe zu Hause, weil krank ich bin.' },
        { id: 'd', text: 'Ich bleibe zu Hause, weil bin ich krank.' },
      ],
      correctOptionId: 'b',
      explanation: 'weil sends the finite verb to the very end of its clause: ..., weil ich krank bin.',
    },
    {
      id: 'ch46-ex-02',
      chapterNumber: 46,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn', 'verb-final', 'subordinate-clause'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"We go for a walk when the weather is nice." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Wir gehen spazieren, wenn ist das Wetter schön.' },
        { id: 'b', text: 'Wir gehen spazieren, wenn das Wetter ist schön.' },
        { id: 'c', text: 'Wir gehen spazieren, wenn das Wetter schön ist.' },
        { id: 'd', text: 'Wir gehen spazieren, wenn schön das Wetter ist.' },
      ],
      correctOptionId: 'c',
      explanation: 'wenn sends the finite verb ist to the end of its clause: ..., wenn das Wetter schön ist.',
    },
    {
      id: 'ch46-ex-03',
      chapterNumber: 46,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dass', 'verb-final', 'subordinate-clause'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"I believe that he is right." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich glaube, dass er hat recht.' },
        { id: 'b', text: 'Ich glaube, dass er recht hat.' },
        { id: 'c', text: 'Ich glaube, dass hat er recht.' },
        { id: 'd', text: 'Ich glaube, dass recht er hat.' },
      ],
      correctOptionId: 'b',
      explanation: 'dass sends the finite verb hat to the end of its clause: ..., dass er recht hat.',
    },
    {
      id: 'ch46-ex-04',
      chapterNumber: 46,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['connector-choice', 'weil'],
      instruction: 'Choose the connector that fits.',
      prompt: 'Er bleibt im Bett, ___ er Fieber hat. (because)',
      options: [
        { id: 'a', text: 'weil' },
        { id: 'b', text: 'wenn' },
        { id: 'c', text: 'dass' },
        { id: 'd', text: 'und' },
      ],
      correctOptionId: 'a',
      explanation: 'weil = because, introducing a reason; it answers the question warum?',
    },
    {
      id: 'ch46-ex-05',
      chapterNumber: 46,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['connector-choice', 'wenn'],
      instruction: 'Choose the connector that fits.',
      prompt: 'Wir gehen ins Kino, ___ wir Zeit haben. (if/when(ever))',
      options: [
        { id: 'a', text: 'dass' },
        { id: 'b', text: 'weil' },
        { id: 'c', text: 'wenn' },
        { id: 'd', text: 'aber' },
      ],
      correctOptionId: 'c',
      explanation: 'wenn = if/when(ever), introducing a condition or a repeated/future time.',
    },
    {
      id: 'ch46-ex-06',
      chapterNumber: 46,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['connector-choice', 'dass'],
      instruction: 'Choose the connector that fits.',
      prompt: 'Ich weiß, ___ du recht hast. (that)',
      options: [
        { id: 'a', text: 'weil' },
        { id: 'b', text: 'dass' },
        { id: 'c', text: 'wenn' },
        { id: 'd', text: 'oder' },
      ],
      correctOptionId: 'b',
      explanation: 'dass = that, introducing what someone knows, thinks, says, or hopes.',
    },
    {
      id: 'ch46-ex-07',
      chapterNumber: 46,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['weil', 'separable-verb', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"He is never tired because he gets up early." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Weil er früh aufsteht, ist er nie müde.' },
        { id: 'b', text: 'Weil er früh auf steht, ist er nie müde.' },
        { id: 'c', text: 'Weil er aufsteht früh, ist er nie müde.' },
        { id: 'd', text: 'Weil er früh steht auf, ist er nie müde.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The separable verb aufstehen stays joined as one word (aufsteht) at the very end of the subordinate clause; it does not split as it does in a main clause.',
    },
    {
      id: 'ch46-ex-08',
      chapterNumber: 46,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wenn', 'modal-verb', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"If you want to come, call me." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Wenn du willst kommen, ruf mich an.' },
        { id: 'b', text: 'Wenn du kommen willst, ruf mich an.' },
        { id: 'c', text: 'Wenn willst du kommen, ruf mich an.' },
        { id: 'd', text: 'Wenn du kommst wollen, ruf mich an.' },
      ],
      correctOptionId: 'b',
      explanation:
        'The modal verb (willst) goes to the very end of the subordinate clause, after the infinitive (kommen).',
    },
    {
      id: 'ch46-ex-09',
      chapterNumber: 46,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dass', 'modal-verb', 'verb-final'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"She says that she can\'t come." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Sie sagt, dass sie nicht kommen kann.' },
        { id: 'b', text: 'Sie sagt, dass sie kann nicht kommen.' },
        { id: 'c', text: 'Sie sagt, dass sie nicht kann kommen.' },
        { id: 'd', text: 'Sie sagt, dass kann sie nicht kommen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The modal verb (kann) goes to the very end; the infinitive (kommen) comes right before it: ..., dass sie nicht kommen kann.',
    },
    {
      id: 'ch46-ex-10',
      chapterNumber: 46,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['comma', 'weil'],
      instruction: 'Choose the correctly punctuated sentence.',
      prompt: '"I\'m tired because I slept badly." Which sentence is correctly punctuated?',
      options: [
        { id: 'a', text: 'Ich bin müde, weil ich schlecht geschlafen habe.' },
        { id: 'b', text: 'Ich bin müde weil, ich schlecht geschlafen habe.' },
        { id: 'c', text: 'Ich bin, müde weil ich schlecht geschlafen habe.' },
        { id: 'd', text: 'Ich bin müde weil ich schlecht, geschlafen habe.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The comma always goes directly before the subordinating conjunction (weil), separating the main clause from the subordinate clause.',
    },
    {
      id: 'ch46-ex-11',
      chapterNumber: 46,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['comma', 'weil', 'inversion'],
      instruction: 'Choose the correctly punctuated sentence.',
      prompt: '"Because I slept badly, I am tired." Which sentence is correctly punctuated?',
      options: [
        { id: 'a', text: 'Weil ich schlecht geschlafen habe, bin ich müde.' },
        { id: 'b', text: 'Weil ich schlecht geschlafen habe bin, ich müde.' },
        { id: 'c', text: 'Weil, ich schlecht geschlafen habe bin ich müde.' },
        { id: 'd', text: 'Weil ich schlecht geschlafen, habe bin ich müde.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The comma marks the end of the whole subordinate clause, right before the main clause begins: Weil ..., bin ich müde.',
    },
    {
      id: 'ch46-ex-12',
      chapterNumber: 46,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inversion', 'weil', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"Because it is raining, we are staying home." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Weil es regnet, wir bleiben zu Hause.' },
        { id: 'b', text: 'Weil es regnet, bleiben wir zu Hause.' },
        { id: 'c', text: 'Weil es regnet, wir zu Hause bleiben.' },
        { id: 'd', text: 'Weil es regnet, zu Hause bleiben wir.' },
      ],
      correctOptionId: 'b',
      explanation:
        'The subordinate clause fills position 1, so the main-clause verb bleiben comes immediately after the comma (position 2), before the subject wir.',
    },
    {
      id: 'ch46-ex-13',
      chapterNumber: 46,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inversion', 'wenn', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"When you have time, please call me." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Wenn du Zeit hast, ruf mich bitte an.' },
        { id: 'b', text: 'Wenn du Zeit hast, du ruf mich bitte an.' },
        { id: 'c', text: 'Wenn du Zeit hast, mich ruf bitte an du.' },
        { id: 'd', text: 'Wenn du Zeit hast, bitte du ruf mich an.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The wenn-clause fills position 1 of the sentence, so the imperative verb ruf comes immediately after the comma.',
    },
    {
      id: 'ch46-ex-14',
      chapterNumber: 46,
      order: 14,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['weil', 'dialogue', 'verb-final', 'modal-verb'],
      instruction: 'Choose the grammatically correct way for Tom to finish his answer.',
      dialogue: [
        { speaker: 'Anna', german: 'Warum lernst du Deutsch?', english: 'Why are you learning German?' },
        {
          speaker: 'Tom',
          german: 'Ich lerne Deutsch, weil ...',
          english: "I'm learning German because ...",
        },
      ],
      prompt: 'Tom\'s answer: Ich lerne Deutsch, weil ___',
      options: [
        { id: 'a', text: 'ich in Berlin arbeiten möchte.' },
        { id: 'b', text: 'ich möchte in Berlin arbeiten.' },
        { id: 'c', text: 'ich arbeiten möchte in Berlin.' },
        { id: 'd', text: 'ich in Berlin möchte arbeiten.' },
      ],
      correctOptionId: 'a',
      explanation:
        'In a weil-clause the finite verb (möchte) moves to the very end, after the infinitive arbeiten: ..., weil ich in Berlin arbeiten möchte.',
    },
    {
      id: 'ch46-ex-15',
      chapterNumber: 46,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weil', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich bleibe im Bett, weil ich krank ___. (sein, ich-form)',
      acceptedAnswers: ['bin'],
      answerMode: 'caseInsensitive',
      placeholder: 'bin',
      maxLength: 10,
      explanation: 'weil sends the finite verb to the end; the ich-form of sein is bin: ..., weil ich krank bin.',
    },
    {
      id: 'ch46-ex-16',
      chapterNumber: 46,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Wir feiern eine Party, wenn er die Prüfung ___. (bestehen, er-form)',
      acceptedAnswers: ['besteht'],
      answerMode: 'caseInsensitive',
      placeholder: 'besteht',
      maxLength: 12,
      explanation:
        'wenn sends the finite verb to the end; the er-form of bestehen is besteht: ..., wenn er die Prüfung besteht.',
    },
    {
      id: 'ch46-ex-17',
      chapterNumber: 46,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dass', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich hoffe, dass du bald wieder gesund ___. (sein, du-form)',
      acceptedAnswers: ['bist'],
      answerMode: 'caseInsensitive',
      placeholder: 'bist',
      maxLength: 10,
      explanation: 'dass sends the finite verb to the end; the du-form of sein is bist: ..., dass du bald wieder gesund bist.',
    },
    {
      id: 'ch46-ex-18',
      chapterNumber: 46,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weil', 'separable-verb', 'verb-final'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Er ist immer pünktlich, weil er früh ___. (aufstehen, er-form)',
      acceptedAnswers: ['aufsteht'],
      answerMode: 'caseInsensitive',
      placeholder: 'aufsteht',
      maxLength: 15,
      explanation:
        'The separable verb aufstehen joins into one word at the end of the subordinate clause: ..., weil er früh aufsteht.',
    },
    {
      id: 'ch46-ex-19',
      chapterNumber: 46,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weil', 'modal-verb', 'verb-final'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Ich kann nicht kommen, weil ich arbeiten ___. (müssen, ich-form)',
      acceptedAnswers: ['muss'],
      answerMode: 'caseInsensitive',
      placeholder: 'muss',
      maxLength: 10,
      explanation:
        'The modal verb goes to the very end, after the infinitive arbeiten; the ich-form of müssen is muss: ..., weil ich arbeiten muss.',
    },
    {
      id: 'ch46-ex-20',
      chapterNumber: 46,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['weil', 'clause-combination'],
      instruction: 'Combine the two sentences with weil. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich bin froh. + Die Sonne scheint. (weil)',
      acceptedAnswers: ['Ich bin froh, weil die Sonne scheint.'],
      answerMode: 'normalized',
      placeholder: 'Ich bin froh, weil ...',
      maxLength: 60,
      explanation: 'weil introduces the reason; its verb scheint moves to the end of the clause: Ich bin froh, weil die Sonne scheint.',
    },
    {
      id: 'ch46-ex-21',
      chapterNumber: 46,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['wenn', 'clause-combination'],
      instruction: 'Combine the two sentences with wenn. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Wir gehen schwimmen. + Es ist warm. (wenn)',
      acceptedAnswers: ['Wir gehen schwimmen, wenn es warm ist.'],
      answerMode: 'normalized',
      placeholder: 'Wir gehen schwimmen, wenn ...',
      maxLength: 60,
      explanation: 'wenn introduces the condition; its verb ist moves to the end of the clause: Wir gehen schwimmen, wenn es warm ist.',
    },
    {
      id: 'ch46-ex-22',
      chapterNumber: 46,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dass', 'clause-combination'],
      instruction: 'Combine the two sentences with dass. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Er sagt. + Er hat keine Zeit. (dass)',
      acceptedAnswers: ['Er sagt, dass er keine Zeit hat.'],
      answerMode: 'normalized',
      placeholder: 'Er sagt, dass ...',
      maxLength: 60,
      explanation: 'dass introduces what er sagt; its verb hat moves to the end of the clause: Er sagt, dass er keine Zeit hat.',
    },
    {
      id: 'ch46-ex-23',
      chapterNumber: 46,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['inversion', 'weil', 'word-order'],
      instruction: 'Rewrite the sentence starting with the weil-clause. Capitalisation and punctuation are checked.',
      prompt: 'Ich bin müde, weil ich lange gearbeitet habe.',
      acceptedAnswers: ['Weil ich lange gearbeitet habe, bin ich müde.'],
      answerMode: 'normalized',
      placeholder: 'Weil ich lange gearbeitet habe, ...',
      maxLength: 70,
      explanation: 'When the weil-clause opens the sentence, the main-clause verb bin comes immediately after the comma, before its subject ich.',
    },
    {
      id: 'ch46-ex-24',
      chapterNumber: 46,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['inversion', 'wenn', 'word-order'],
      instruction: 'Rewrite the sentence starting with the wenn-clause. Capitalisation and punctuation are checked.',
      prompt: 'Ich rufe dich an, wenn ich Zeit habe.',
      acceptedAnswers: ['Wenn ich Zeit habe, rufe ich dich an.'],
      answerMode: 'normalized',
      placeholder: 'Wenn ich Zeit habe, ...',
      maxLength: 70,
      explanation: 'When the wenn-clause opens the sentence, the main-clause verb rufe comes immediately after the comma, before its subject ich.',
    },
    {
      id: 'ch46-ex-25',
      chapterNumber: 46,
      order: 25,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'weil', 'verb-final'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich bleibe zu Hause, weil ich bin krank.',
      acceptedAnswers: ['Ich bleibe zu Hause, weil ich krank bin.'],
      answerMode: 'normalized',
      placeholder: 'Ich bleibe zu Hause, weil ...',
      maxLength: 60,
      explanation: 'weil sends the finite verb to the very end of its clause, so bin belongs after krank, not after ich.',
    },
    {
      id: 'ch46-ex-26',
      chapterNumber: 46,
      order: 26,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'inversion', 'word-order'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Weil es regnet, wir bleiben zu Hause.',
      acceptedAnswers: ['Weil es regnet, bleiben wir zu Hause.'],
      answerMode: 'normalized',
      placeholder: 'Weil es regnet, ...',
      maxLength: 60,
      explanation:
        'When the subordinate clause comes first, the main-clause verb bleiben must come immediately after the comma, before the subject wir.',
    },
    {
      id: 'ch46-ex-27',
      chapterNumber: 46,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['dass', 'dialogue', 'reported-speech', 'verb-final'],
      instruction: "Complete Mia's report. Write only the missing words. Capitalisation is not checked.",
      dialogue: [
        {
          speaker: 'Lehrerin',
          german: 'Weiß jemand, wo Paul heute ist?',
          english: 'Does anyone know where Paul is today?',
        },
        { speaker: 'Mia', german: 'Seine Mutter hat angerufen.', english: 'His mother called.' },
        { speaker: 'Mia', german: 'Sie hat gesagt, dass ___', english: 'She said that ___' },
      ],
      prompt: 'Sie hat gesagt, dass ___. (Paul / krank / sein, Präsens)',
      acceptedAnswers: ['Paul krank ist'],
      answerMode: 'caseInsensitive',
      placeholder: 'Paul krank ist',
      maxLength: 30,
      explanation: "dass reports what Paul's mother said; the verb ist moves to the end of the clause: ..., dass Paul krank ist.",
    },
    {
      id: 'ch46-ex-28',
      chapterNumber: 46,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['weil', 'dialogue', 'perfect-tense', 'verb-final'],
      instruction: "Complete Lea's answer. Write only the missing words. Capitalisation is not checked.",
      dialogue: [
        { speaker: 'Ben', german: 'Warum bist du so müde?', english: 'Why are you so tired?' },
        {
          speaker: 'Lea',
          german: 'Ich bin müde, weil ich die ganze Nacht ___.',
          english: "I'm tired because I studied all night.",
        },
      ],
      prompt: 'Ich bin müde, weil ich die ganze Nacht ___. (lernen, Perfekt mit haben)',
      acceptedAnswers: ['gelernt habe'],
      answerMode: 'caseInsensitive',
      placeholder: 'gelernt habe',
      maxLength: 20,
      explanation:
        'In the perfect tense inside a weil-clause, the participle (gelernt) and the auxiliary (habe) both move to the end, with habe last.',
    },
  ],
};
