import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter019: ChapterDefinition = {
  id: 'chapter-019',
  number: 19,
  slug: 'possessive-articles',
  title: 'Possessive Articles',
  germanTitle: 'Possessivartikel',
  level: 'A1',
  section: 'pronouns-nouns-articles',
  objective:
    'Select the correct possessive article stem for a given owner (mein, dein, sein, ihr, unser, euer, Ihr) and give it the ending required by the gender, number, and case of the noun it introduces.',
  prerequisites: [1, 17],
  estimatedMinutes: 25,
  tags: ['possessive-articles', 'possessivartikel', 'agreement', 'ihr-vs-Ihr'],
  explanation: {
    introduction: [
      'A possessive article (Possessivartikel) shows who owns or is connected to a noun: mein Buch (my book), deine Familie (your family), unser Auto (our car). German has one possessive stem for every personal pronoun — ich, du, er, es, sie, wir, ihr, sie (plural), and Sie — and each stem behaves exactly like the article ein: it changes its ending depending on the noun that follows.',
      'This chapter shows you how to pick the right stem for the owner, how to give it the right ending for the noun, and how to tell apart two easily confused forms: lowercase ihr, which can mean "her" or "their", and capitalized Ihr, the polite form for "your" used with Sie.',
    ],
    rules: [
      {
        id: 'ch19-rule-01',
        heading: 'The possessive stems: one for each owner',
        paragraphs: [
          'A possessive article tells you who owns something. Its stem depends only on the owner — the possessor — never on the thing that is owned.',
          'ich → mein-, du → dein-, er → sein-, es → sein-, sie (singular, "she") → ihr-, wir → unser-, ihr (plural "you") → euer-, sie (plural, "they") → ihr-, Sie (formal "you") → Ihr-.',
        ],
        notes: [
          'sein- serves both er and es: sein Auto can mean "his car" or "its car", depending on what er or es refers to back in the text.',
        ],
      },
      {
        id: 'ch19-rule-02',
        heading: 'Agreement: the owner picks the stem, the noun picks the ending',
        paragraphs: [
          'Once you have the right stem for the owner, the possessive article still needs an ending — and that ending has nothing to do with the owner. It depends only on the gender, number, and case of the noun that follows, exactly as with the indefinite article ein.',
          'Compare unser Sohn (our son, masculine, no ending) with unsere Tochter (our daughter, feminine, -e ending): the owner (wir) is identical, but the ending changes because the nouns have different genders.',
        ],
      },
      {
        id: 'ch19-rule-03',
        heading: 'Endings in the nominative, modeled on ein',
        paragraphs: [
          'In the nominative, possessive articles take exactly the endings of ein: no ending for masculine and neuter nouns, and -e for feminine and plural nouns.',
          'mein Bruder (masc.), mein Kind (neut.), meine Schwester (fem.), meine Eltern (plural) — same stem mein-, four different endings.',
        ],
        notes: [
          'euer loses its middle e as soon as an ending is added: euer becomes eure, not euere.',
        ],
      },
      {
        id: 'ch19-rule-04',
        heading: 'A preview of the accusative: -en on masculine nouns',
        paragraphs: [
          'You already know that masculine nouns change their article in the accusative case (ein → einen). Possessive articles follow the same pattern: a masculine noun used as a direct object adds -en to the possessive stem.',
          'Ich sehe meinen Bruder — not mein Bruder — because Bruder is the accusative object of sehen. Feminine, neuter, and plural nouns keep the same ending as in the nominative.',
        ],
      },
      {
        id: 'ch19-rule-05',
        heading: 'ihr can mean "her" or "their" — and Ihr means formal "your"',
        paragraphs: [
          'The word ihr is ambiguous in writing: it is the possessive article both for sie (singular, "she") and for sie (plural, "they"). Only the surrounding context tells you which meaning is intended.',
          'Ihr, capitalized, is a different word altogether: the possessive article for the formal Sie ("you"), used with people addressed politely. Like Sie itself, Ihr is always capitalized — in the middle of a sentence, not only at its start.',
        ],
        notes: [
          'At the very start of a sentence every word is capitalized anyway, so capitalization alone cannot distinguish ihr from Ihr there — only context can.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch19-table-01',
        title: 'Possessive stems by owner',
        columns: ['Owner (pronoun)', 'Possessive stem', 'Example'],
        rows: [
          ['ich', 'mein-', 'mein Buch'],
          ['du', 'dein-', 'dein Buch'],
          ['er', 'sein-', 'sein Buch'],
          ['es', 'sein-', 'sein Buch'],
          ['sie (singular, "she")', 'ihr-', 'ihr Buch'],
          ['wir', 'unser-', 'unser Buch'],
          ['ihr (plural "you")', 'euer-', 'euer Buch'],
          ['sie (plural, "they")', 'ihr-', 'ihr Buch'],
          ['Sie (formal "you")', 'Ihr-', 'Ihr Buch'],
        ],
      },
      {
        id: 'ch19-table-02',
        title: 'Endings by gender and number (mein as the model)',
        columns: ['Gender / number (example noun)', 'Nominative', 'Accusative'],
        rows: [
          ['masculine (der Vater)', 'mein Vater', 'meinen Vater'],
          ['feminine (die Mutter)', 'meine Mutter', 'meine Mutter'],
          ['neuter (das Kind)', 'mein Kind', 'mein Kind'],
          ['plural (die Eltern)', 'meine Eltern', 'meine Eltern'],
        ],
        note: 'Only the masculine form changes between nominative and accusative — feminine, neuter, and plural stay the same.',
      },
    ],
    examples: [
      {
        german: 'Das ist mein Vater.',
        english: 'This is my father.',
        highlight: ['mein'],
        explanation: 'der Vater is masculine nominative, so mein has no ending, like ein.',
      },
      {
        german: 'Meine Schwester wohnt in Berlin.',
        english: 'My sister lives in Berlin.',
        highlight: ['Meine'],
        explanation: 'die Schwester is feminine nominative, so mein takes the -e ending.',
      },
      {
        german: 'Ist das dein Buch?',
        english: 'Is that your book?',
        highlight: ['dein'],
        explanation: 'das Buch is neuter nominative, so dein has no ending.',
      },
      {
        german: 'Er sucht seinen Schlüssel.',
        english: 'He is looking for his key.',
        highlight: ['seinen'],
        explanation: 'der Schlüssel is masculine accusative (object of suchen), so sein takes -en.',
      },
      {
        german: 'Das Kind sucht seine Mutter.',
        english: 'The child is looking for its mother.',
        highlight: ['seine'],
        explanation: 'The owner is das Kind, referred to as es, so the stem is sein-; die Mutter is feminine accusative, so it takes -e.',
      },
      {
        german: 'Sie liebt ihren Bruder.',
        english: 'She loves her brother.',
        highlight: ['ihren'],
        explanation: 'The owner is sie ("she"), so the stem is ihr-; der Bruder is masculine accusative, so it takes -en.',
      },
      {
        german: 'Die Familie besucht ihre Großeltern.',
        english: 'The family is visiting their grandparents.',
        highlight: ['ihre'],
        explanation: 'Here ihr- refers back to die Familie ("they"), not to a single woman; die Großeltern is plural, so it takes -e.',
      },
      {
        german: 'Wir besuchen unsere Großeltern.',
        english: 'We are visiting our grandparents.',
        highlight: ['unsere'],
        explanation: 'die Großeltern is plural accusative, so unser takes the -e ending.',
      },
      {
        german: 'Habt ihr euren Hund dabei?',
        english: 'Do you (plural) have your dog with you?',
        highlight: ['euren'],
        explanation: 'der Hund is masculine accusative, so euer takes -en, giving euren, not eueren.',
      },
      {
        german: 'Frau Klein, ist das Ihr Auto?',
        english: 'Mrs. Klein, is that your car?',
        highlight: ['Ihr'],
        explanation: 'This is a polite question to Frau Klein, so the formal, capitalized Ihr is used; das Auto is neuter nominative, so it has no ending.',
      },
      {
        german: 'Herr Braun, wie heißt Ihre Tochter?',
        english: 'Mr. Braun, what is your daughter’s name?',
        highlight: ['Ihre'],
        explanation: 'Formal address again requires capitalized Ihr; die Tochter is feminine nominative, so it takes -e.',
      },
      {
        german: 'Lena mag ihren Job, und Paul mag ihren Chef nicht.',
        english: 'Lena likes her job, and Paul does not like her/their boss.',
        highlight: ['ihren'],
        explanation: 'Without more context, ihren Chef could mean Lena’s boss (her) or a boss the two of them share (their) — only the surrounding text can decide.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Er sucht sein Schlüssel.',
        correct: 'Er sucht seinen Schlüssel.',
        explanation: 'der Schlüssel is masculine and here is the accusative object of suchen, so the possessive article needs the -en ending: seinen.',
      },
      {
        incorrect: 'Das ist meine Vater.',
        correct: 'Das ist mein Vater.',
        explanation: 'der Vater is masculine nominative, so, like ein, mein takes no ending at all.',
      },
      {
        incorrect: 'Wir besuchen unser Großeltern.',
        correct: 'Wir besuchen unsere Großeltern.',
        explanation: 'die Großeltern is plural, and plural nouns always take the -e ending, regardless of case: unsere.',
      },
      {
        incorrect: 'Habt ihr euer Hund dabei?',
        correct: 'Habt ihr euren Hund dabei?',
        explanation: 'der Hund is the masculine accusative object of habt ... dabei, so euer needs the -en ending: euren.',
      },
      {
        incorrect: 'Frau Meier, ist das ihr Auto?',
        correct: 'Frau Meier, ist das Ihr Auto?',
        explanation: 'Addressing Frau Meier politely requires the formal, capitalized Ihr — lowercase ihr would instead mean "her" or "their".',
      },
    ],
    remember: [
      'The owner chooses the stem: mein, dein, sein, ihr, unser, euer, Ihr — sein covers both er and es.',
      'The noun chooses the ending: no ending for masculine/neuter, -e for feminine and plural, -en for masculine in the accusative — exactly like ein.',
      'euer drops its middle e before an ending: euer → eure, euren, not euere, eueren.',
      'ihr is ambiguous ("her" or "their"); Ihr, always capitalized, is the separate formal "your" that goes with Sie.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 50,
    requiredCorrectTextInputs: 17,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch19-ex-01',
      chapterNumber: 19,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['possessive-articles', 'owner-stem'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: 'Das ist ___ Hund. (ich)',
      options: [
        { id: 'a', text: 'mein' },
        { id: 'b', text: 'dein' },
        { id: 'c', text: 'sein' },
        { id: 'd', text: 'ihr' },
      ],
      correctOptionId: 'a',
      explanation: 'The owner is ich, so the stem is mein-; der Hund is masculine nominative, so it takes no ending.',
    },
    {
      id: 'ch19-ex-02',
      chapterNumber: 19,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: '___ Tasche ist rot. (du)',
      options: [
        { id: 'a', text: 'deine' },
        { id: 'b', text: 'dein' },
        { id: 'c', text: 'deinen' },
        { id: 'd', text: 'sein' },
      ],
      correctOptionId: 'a',
      explanation: 'die Tasche is feminine nominative, so dein takes the -e ending: deine.',
    },
    {
      id: 'ch19-ex-03',
      chapterNumber: 19,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: '___ Auto ist neu. (er)',
      options: [
        { id: 'a', text: 'sein' },
        { id: 'b', text: 'seine' },
        { id: 'c', text: 'seinen' },
        { id: 'd', text: 'ihr' },
      ],
      correctOptionId: 'a',
      explanation: 'das Auto is neuter nominative, so sein takes no ending.',
    },
    {
      id: 'ch19-ex-04',
      chapterNumber: 19,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: '___ Eltern wohnen in München. (wir)',
      options: [
        { id: 'a', text: 'unsere' },
        { id: 'b', text: 'unser' },
        { id: 'c', text: 'unseren' },
        { id: 'd', text: 'eure' },
      ],
      correctOptionId: 'a',
      explanation: 'die Eltern is plural nominative, so unser takes the -e ending: unsere.',
    },
    {
      id: 'ch19-ex-05',
      chapterNumber: 19,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'accusative-ending', 'owner-stem'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Anna sucht ___ Schlüssel.',
      options: [
        { id: 'a', text: 'ihren' },
        { id: 'b', text: 'ihr' },
        { id: 'c', text: 'ihre' },
        { id: 'd', text: 'seinen' },
      ],
      correctOptionId: 'a',
      explanation: 'Anna is "she", so the stem is ihr-; der Schlüssel is masculine accusative (object of suchen), so it takes -en: ihren.',
    },
    {
      id: 'ch19-ex-06',
      chapterNumber: 19,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ihr-ambiguity'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Die Kinder lieben ___ Lehrerin.',
      options: [
        { id: 'a', text: 'ihre' },
        { id: 'b', text: 'ihr' },
        { id: 'c', text: 'seine' },
        { id: 'd', text: 'unsere' },
      ],
      correctOptionId: 'a',
      explanation: 'Die Kinder ("they") is the owner, so the stem is ihr-; die Lehrerin is feminine accusative, so it takes -e: ihre.',
    },
    {
      id: 'ch19-ex-07',
      chapterNumber: 19,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'formal-ihr'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Herr Fischer, ist das ___ Koffer?',
      options: [
        { id: 'a', text: 'Ihr' },
        { id: 'b', text: 'ihr' },
        { id: 'c', text: 'Ihre' },
        { id: 'd', text: 'euer' },
      ],
      correctOptionId: 'a',
      explanation: 'Herr Fischer is addressed politely with Sie, so the formal, capitalized Ihr is needed; der Koffer is masculine nominative, so it has no ending.',
    },
    {
      id: 'ch19-ex-08',
      chapterNumber: 19,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'euer-contraction'],
      instruction: 'Choose the correct possessive article.',
      prompt: '___ Freunde kommen heute.',
      options: [
        { id: 'a', text: 'eure' },
        { id: 'b', text: 'euere' },
        { id: 'c', text: 'euer' },
        { id: 'd', text: 'ihre' },
      ],
      correctOptionId: 'a',
      explanation: 'die Freunde is plural nominative, so euer needs the -e ending; the middle e is dropped, giving eure, not euere.',
    },
    {
      id: 'ch19-ex-09',
      chapterNumber: 19,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'accusative-ending'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Ich sehe ___ Bruder.',
      options: [
        { id: 'a', text: 'deinen' },
        { id: 'b', text: 'dein' },
        { id: 'c', text: 'deine' },
        { id: 'd', text: 'seinen' },
      ],
      correctOptionId: 'a',
      explanation: 'der Bruder is masculine accusative (object of sehen), so dein takes the -en ending: deinen.',
    },
    {
      id: 'ch19-ex-10',
      chapterNumber: 19,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ihr-vs-Ihr'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Tom kennt seine Nachbarn gut. Er mag ___ Garten.',
      options: [
        { id: 'a', text: 'ihren' },
        { id: 'b', text: 'Ihren' },
        { id: 'c', text: 'seinen' },
        { id: 'd', text: 'unseren' },
      ],
      correctOptionId: 'a',
      explanation: 'The owner is die Nachbarn ("they"), not a formal Sie, so lowercase ihren is correct; der Garten is masculine accusative, so it takes -en.',
    },
    {
      id: 'ch19-ex-11',
      chapterNumber: 19,
      order: 11,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['possessive-articles', 'formal-ihr'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Guten Tag! Wie heißen ___ Kinder?',
      options: [
        { id: 'a', text: 'Ihre' },
        { id: 'b', text: 'ihre' },
        { id: 'c', text: 'eure' },
        { id: 'd', text: 'seine' },
      ],
      correctOptionId: 'a',
      explanation: 'This is a polite greeting to someone addressed with Sie, so the formal Ihre is needed; die Kinder is plural, so it takes -e.',
    },
    {
      id: 'ch19-ex-12',
      chapterNumber: 19,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['possessive-articles', 'ihr-ambiguity'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Die Studentinnen besuchen ___ Professorin.',
      options: [
        { id: 'a', text: 'ihre' },
        { id: 'b', text: 'Ihre' },
        { id: 'c', text: 'seine' },
        { id: 'd', text: 'deine' },
      ],
      correctOptionId: 'a',
      explanation: 'Die Studentinnen ("they") is the owner, so the stem is ihr-, lowercase since no one is being addressed formally; die Professorin is feminine accusative, so it takes -e.',
    },
    {
      id: 'ch19-ex-13',
      chapterNumber: 19,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: '___ Katze schläft viel. (ich)',
      acceptedAnswers: ['meine'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'die Katze is feminine nominative, so mein takes the -e ending: meine.',
    },
    {
      id: 'ch19-ex-14',
      chapterNumber: 19,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'owner-stem'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: 'Ich habe einen Hund. ___ Hund ist braun. (ich)',
      acceptedAnswers: ['mein'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 10,
      explanation: 'der Hund is masculine nominative, so mein has no ending, exactly like ein.',
    },
    {
      id: 'ch19-ex-15',
      chapterNumber: 19,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'accusative-ending'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: 'Ich mag ___ Idee. (du)',
      acceptedAnswers: ['deine'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'die Idee is feminine accusative (object of mögen), so dein takes the -e ending: deine.',
    },
    {
      id: 'ch19-ex-16',
      chapterNumber: 19,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: '___ Freunde sind nett. (er)',
      acceptedAnswers: ['seine'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'die Freunde is plural, and plural nouns always take -e, so sein becomes seine.',
    },
    {
      id: 'ch19-ex-17',
      chapterNumber: 19,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'accusative-ending'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: 'Wir suchen ___ Schlüssel. (wir)',
      acceptedAnswers: ['unseren'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 14,
      explanation: 'der Schlüssel is masculine accusative (object of suchen), so unser takes the -en ending: unseren.',
    },
    {
      id: 'ch19-ex-18',
      chapterNumber: 19,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'euer-contraction'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: 'Ist das ___ Wohnung? (ihr, plural "you")',
      acceptedAnswers: ['eure'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'die Wohnung is feminine nominative, so euer takes -e; the middle e drops, giving eure, not euere.',
    },
    {
      id: 'ch19-ex-19',
      chapterNumber: 19,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['possessive-articles', 'formal-ihr'],
      instruction: 'Fill in the correct possessive article. Capitalization is checked here because it is the point of the exercise.',
      prompt: 'Entschuldigung, ist das ___ Regenschirm? (You are politely addressing a stranger.)',
      acceptedAnswers: ['Ihr'],
      answerMode: 'exact',
      placeholder: 'Ihr / ihr',
      maxLength: 5,
      explanation: 'Addressing a stranger politely uses the formal Sie-form; its possessive article Ihr is always capitalized, just like Sie.',
    },
    {
      id: 'ch19-ex-20',
      chapterNumber: 19,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['possessive-articles', 'ihr-vs-Ihr'],
      instruction: 'Fill in the correct possessive article. Capitalization is checked here because it is the point of the exercise.',
      prompt: 'Frau Bauer hat zwei Kinder. Jeden Morgen bringt sie ___ Kinder zur Schule. (her)',
      acceptedAnswers: ['ihre'],
      answerMode: 'exact',
      placeholder: 'ihre / Ihre',
      maxLength: 12,
      explanation: 'The owner is sie (Frau Bauer, "she"), so the stem is ihr-; die Kinder is plural, so it takes -e: ihre. This is not the formal Sie-form, so it stays lowercase.',
    },
    {
      id: 'ch19-ex-21',
      chapterNumber: 19,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['possessive-articles', 'owner-stem', 'accusative-ending'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: 'Das Kind hat einen Ball verloren. Es sucht ___ Ball. (es)',
      acceptedAnswers: ['seinen'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'The owner is es (das Kind), so the stem is sein-, the same stem used for er; der Ball is masculine accusative, so it takes -en: seinen.',
    },
    {
      id: 'ch19-ex-22',
      chapterNumber: 19,
      order: 22,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['possessive-articles', 'sentence-writing'],
      instruction: 'Write a complete German sentence with the cues. Capitalization and punctuation are checked.',
      prompt: 'Say: This is my brother. (das ist – mein – Bruder)',
      acceptedAnswers: ['Das ist mein Bruder.'],
      answerMode: 'normalized',
      placeholder: 'Das ist ...',
      maxLength: 40,
      explanation: 'der Bruder is masculine nominative, so mein takes no ending: Das ist mein Bruder.',
    },
    {
      id: 'ch19-ex-23',
      chapterNumber: 19,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['possessive-articles', 'sentence-writing', 'accusative-ending'],
      instruction: 'Write a complete German sentence with the cues. Capitalization and punctuation are checked.',
      prompt: 'Say: We love our children. (wir – lieben – unser – Kinder)',
      acceptedAnswers: ['Wir lieben unsere Kinder.'],
      answerMode: 'normalized',
      placeholder: 'Wir lieben ...',
      maxLength: 40,
      explanation: 'die Kinder is plural accusative (object of lieben), so unser takes the -e ending: Wir lieben unsere Kinder.',
    },
    {
      id: 'ch19-ex-24',
      chapterNumber: 19,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['possessive-articles', 'sentence-writing', 'formal-ihr'],
      instruction: 'Write a complete, polite German question with the cues. Capitalization and punctuation are checked.',
      prompt: 'Politely ask a stranger: Is this your suitcase? (formal Sie-form; ist – das – Ihr – Koffer)',
      acceptedAnswers: ['Ist das Ihr Koffer?'],
      answerMode: 'normalized',
      placeholder: 'Ist das ...?',
      maxLength: 40,
      explanation: 'This is a formal question, so the possessive article is the capitalized Ihr; der Koffer is masculine nominative, so it takes no ending: Ist das Ihr Koffer?',
    },
    {
      id: 'ch19-ex-25',
      chapterNumber: 19,
      order: 25,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['possessive-articles', 'ihr-ambiguity'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: '___ Kinder spielen im Garten. (sie, plural "they")',
      options: [
        { id: 'a', text: 'ihre' },
        { id: 'b', text: 'ihr' },
        { id: 'c', text: 'unsere' },
        { id: 'd', text: 'Ihre' },
      ],
      correctOptionId: 'a',
      explanation: 'Die Kinder ("they") is the owner, so the stem is ihr-; die Kinder is plural, so it takes -e: ihre.',
    },
    {
      id: 'ch19-ex-26',
      chapterNumber: 19,
      order: 26,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: 'Ich brauche ___ Handy. (du)',
      options: [
        { id: 'a', text: 'dein' },
        { id: 'b', text: 'deine' },
        { id: 'c', text: 'deinen' },
        { id: 'd', text: 'sein' },
      ],
      correctOptionId: 'a',
      explanation: 'das Handy is neuter, and neuter nouns keep the same no-ending form in nominative and accusative, so dein has no ending.',
    },
    {
      id: 'ch19-ex-27',
      chapterNumber: 19,
      order: 27,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'accusative-ending'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Wir laden ___ Nachbarn ein.',
      options: [
        { id: 'a', text: 'unseren' },
        { id: 'b', text: 'unser' },
        { id: 'c', text: 'unsere' },
        { id: 'd', text: 'euren' },
      ],
      correctOptionId: 'a',
      explanation: 'der Nachbar is masculine accusative (object of einladen), so unser takes the -en ending: unseren.',
    },
    {
      id: 'ch19-ex-28',
      chapterNumber: 19,
      order: 28,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'euer-contraction'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: '___ Wohnung ist groß. (ihr, plural "you")',
      options: [
        { id: 'a', text: 'eure' },
        { id: 'b', text: 'euer' },
        { id: 'c', text: 'euere' },
        { id: 'd', text: 'ihre' },
      ],
      correctOptionId: 'a',
      explanation: 'die Wohnung is feminine nominative, so euer takes -e; the middle e drops, giving eure, not euere.',
    },
    {
      id: 'ch19-ex-29',
      chapterNumber: 19,
      order: 29,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['possessive-articles', 'formal-ihr', 'accusative-ending'],
      instruction: 'Choose the correct possessive article.',
      prompt: 'Frau Lang, ich habe ___ Schlüssel gefunden.',
      options: [
        { id: 'a', text: 'Ihren' },
        { id: 'b', text: 'Ihr' },
        { id: 'c', text: 'Ihre' },
        { id: 'd', text: 'ihren' },
      ],
      correctOptionId: 'a',
      explanation: 'Frau Lang is addressed formally, so the stem is Ihr-; der Schlüssel is masculine accusative (object of finden), so it takes -en: Ihren.',
    },
    {
      id: 'ch19-ex-30',
      chapterNumber: 19,
      order: 30,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['possessive-articles', 'owner-stem'],
      instruction: 'Choose the correct possessive article for the owner given in brackets.',
      prompt: 'Das Baby hat ___ Spielzeug verloren. (es)',
      options: [
        { id: 'a', text: 'sein' },
        { id: 'b', text: 'seine' },
        { id: 'c', text: 'seinen' },
        { id: 'd', text: 'ihr' },
      ],
      correctOptionId: 'a',
      explanation: 'The owner is es (das Baby), so the stem is sein-; das Spielzeug is neuter, so it keeps the no-ending form in both nominative and accusative.',
    },
    {
      id: 'ch19-ex-31',
      chapterNumber: 19,
      order: 31,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: '___ Schwester heißt Lisa. (ich)',
      acceptedAnswers: ['meine'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'die Schwester is feminine nominative, so mein takes the -e ending: meine.',
    },
    {
      id: 'ch19-ex-32',
      chapterNumber: 19,
      order: 32,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'accusative-ending'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: 'Ich rufe ___ Vater an. (ich)',
      acceptedAnswers: ['meinen'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'der Vater is masculine accusative (object of anrufen), so mein takes the -en ending: meinen.',
    },
    {
      id: 'ch19-ex-33',
      chapterNumber: 19,
      order: 33,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: '___ Freunde sind laut. (er)',
      acceptedAnswers: ['seine'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'die Freunde is plural, and plural nouns always take -e, so sein becomes seine.',
    },
    {
      id: 'ch19-ex-34',
      chapterNumber: 19,
      order: 34,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'euer-contraction', 'accusative-ending'],
      instruction: 'Fill in the correct possessive article for the owner in brackets. Capitalization is not checked.',
      prompt: 'Habt ihr ___ Koffer dabei? (ihr, plural "you")',
      acceptedAnswers: ['euren'],
      answerMode: 'caseInsensitive',
      placeholder: 'possessive article',
      maxLength: 12,
      explanation: 'der Koffer is masculine accusative, so euer takes -en; the middle e drops, giving euren, not eueren.',
    },
    {
      id: 'ch19-ex-35',
      chapterNumber: 19,
      order: 35,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['possessive-articles', 'formal-ihr'],
      instruction: 'Fill in the correct possessive article. Capitalization is checked here because it is the point of the exercise.',
      prompt: 'Herr Weber, wie heißt ___ Firma? (formal Sie-form)',
      acceptedAnswers: ['Ihre'],
      answerMode: 'exact',
      placeholder: 'Ihre / ihre',
      maxLength: 6,
      explanation: 'Herr Weber is addressed formally, so the capitalized Ihre is needed; die Firma is feminine nominative, so it takes -e.',
    },
    {
      id: 'ch19-ex-36',
      chapterNumber: 19,
      order: 36,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['possessive-articles', 'ihr-vs-Ihr'],
      instruction: 'Fill in the correct possessive article. Capitalization is checked here because it is the point of the exercise.',
      prompt: 'Die Nachbarn renovieren ___ Küche. (their)',
      acceptedAnswers: ['ihre'],
      answerMode: 'exact',
      placeholder: 'ihre / Ihre',
      maxLength: 12,
      explanation: 'The owner is die Nachbarn ("they"), not the formal Sie, so the stem stays lowercase ihr-; die Küche is feminine accusative, so it takes -e: ihre.',
    },
    {
      id: 'ch19-ex-37',
      chapterNumber: 19,
      order: 37,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['possessive-articles', 'sentence-writing', 'accusative-ending'],
      instruction: 'Write a complete German sentence with the cues. Capitalization and punctuation are checked.',
      prompt: 'Say: My parents love their garden. (meine Eltern – lieben – ihr – Garten)',
      acceptedAnswers: ['Meine Eltern lieben ihren Garten.'],
      answerMode: 'normalized',
      placeholder: 'Meine Eltern ...',
      maxLength: 40,
      explanation: 'der Garten is masculine accusative (object of lieben), so ihr takes the -en ending: Meine Eltern lieben ihren Garten.',
    },
    {
      id: 'ch19-ex-38',
      chapterNumber: 19,
      order: 38,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Drag the correctly declined possessive article into the gap.',
      prompt: 'Vervollständige den Satz: "___ Mutter kocht heute." (ich)',
      templateParts: ['', ' Mutter kocht heute.'],
      slots: [{ id: 'ch19-ex38-slot1', correctWord: 'meine' }],
      wordBank: ['meine', 'mein', 'meinen', 'meiner'],
      explanation: 'die Mutter is feminine nominative, so mein takes the -e ending: meine.',
    },
    {
      id: 'ch19-ex-39',
      chapterNumber: 19,
      order: 39,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'accusative-ending'],
      instruction: 'Drag the correctly declined possessive article into the gap.',
      prompt: 'Vervollständige den Satz: "Kennst du ___ Freund?"',
      templateParts: ['Kennst du ', ' Freund?'],
      slots: [{ id: 'ch19-ex39-slot1', correctWord: 'deinen' }],
      wordBank: ['deinen', 'dein', 'deine', 'deiner'],
      explanation: 'der Freund is masculine accusative (object of kennen), so dein takes the -en ending: deinen.',
    },
    {
      id: 'ch19-ex-40',
      chapterNumber: 19,
      order: 40,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'owner-stem'],
      instruction: 'Drag the correctly declined possessive article into the gap.',
      prompt: 'Vervollständige den Satz: "Er mag ___ Auto."',
      templateParts: ['Er mag ', ' Auto.'],
      slots: [{ id: 'ch19-ex40-slot1', correctWord: 'sein' }],
      wordBank: ['sein', 'seine', 'seinen', 'seiner'],
      explanation: 'das Auto is neuter accusative, so sein has no ending.',
    },
    {
      id: 'ch19-ex-41',
      chapterNumber: 19,
      order: 41,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement'],
      instruction: 'Drag the correctly declined possessive article into the gap.',
      prompt: 'Vervollständige den Satz: "Wir lieben ___ Großeltern."',
      templateParts: ['Wir lieben ', ' Großeltern.'],
      slots: [{ id: 'ch19-ex41-slot1', correctWord: 'unsere' }],
      wordBank: ['unsere', 'unser', 'unseren', 'unserer'],
      explanation: 'die Großeltern is plural accusative, so unser takes the -e ending: unsere.',
    },
    {
      id: 'ch19-ex-42',
      chapterNumber: 19,
      order: 42,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['possessive-articles', 'euer-contraction'],
      instruction: 'Drag the correctly declined possessive article into the gap.',
      prompt: 'Vervollständige den Satz: "___ Idee ist gut." (ihr, plural "you")',
      templateParts: ['', ' Idee ist gut.'],
      slots: [{ id: 'ch19-ex42-slot1', correctWord: 'eure' }],
      wordBank: ['eure', 'euer', 'euere', 'euren'],
      explanation: 'die Idee is feminine nominative, so euer takes -e; the middle e drops, giving eure, not euere.',
    },
    {
      id: 'ch19-ex-43',
      chapterNumber: 19,
      order: 43,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['possessive-articles', 'formal-ihr', 'accusative-ending'],
      instruction: 'Drag the correctly declined possessive article into the gap.',
      prompt: 'Vervollständige den Satz: "Herr Klein, ich bringe ___ Koffer."',
      templateParts: ['Herr Klein, ich bringe ', ' Koffer.'],
      slots: [{ id: 'ch19-ex43-slot1', correctWord: 'Ihren' }],
      wordBank: ['Ihren', 'Ihr', 'Ihre', 'ihren'],
      explanation: 'Herr Klein is addressed formally, so the stem is Ihr-; der Koffer is masculine accusative, so it takes -en: Ihren.',
    },
    {
      id: 'ch19-ex-44',
      chapterNumber: 19,
      order: 44,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['possessive-articles', 'ihr-ambiguity'],
      instruction: 'Drag the correctly declined possessive article into the gap.',
      prompt: 'Vervollständige den Satz: "___ Kinder sind süß." (sie, plural "they")',
      templateParts: ['', ' Kinder sind süß.'],
      slots: [{ id: 'ch19-ex44-slot1', correctWord: 'ihre' }],
      wordBank: ['ihre', 'ihr', 'ihren', 'unsere'],
      explanation: 'Die Kinder ("they") is the owner, so the stem is ihr-; die Kinder is plural, so it takes -e: ihre.',
    },
    {
      id: 'ch19-ex-45',
      chapterNumber: 19,
      order: 45,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['possessive-articles', 'owner-stem'],
      instruction: 'Match each subject pronoun to its possessive stem.',
      prompt: 'Match the owner with the correct possessive stem.',
      pairs: [
        { id: 'ch19-ex45-p1', left: 'ich', right: 'mein-' },
        { id: 'ch19-ex45-p2', left: 'du', right: 'dein-' },
        { id: 'ch19-ex45-p3', left: 'er / es', right: 'sein-' },
        { id: 'ch19-ex45-p4', left: 'wir', right: 'unser-' },
        { id: 'ch19-ex45-p5', left: 'sie (plural, "they")', right: 'ihr-' },
      ],
      explanation: 'Each personal pronoun has its own possessive stem: ich → mein-, du → dein-, er/es → sein-, wir → unser-, sie (plural) → ihr-.',
    },
    {
      id: 'ch19-ex-46',
      chapterNumber: 19,
      order: 46,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement', 'accusative-ending'],
      instruction: 'Match each owner and noun to the correctly declined possessive article.',
      prompt: 'Match the situation with the correctly declined possessive article.',
      pairs: [
        { id: 'ch19-ex46-p1', left: 'ich + der Vater (Nominativ)', right: 'mein' },
        { id: 'ch19-ex46-p2', left: 'du + die Tasche (Nominativ)', right: 'deine' },
        { id: 'ch19-ex46-p3', left: 'wir + der Schlüssel (Akkusativ)', right: 'unseren' },
        { id: 'ch19-ex46-p4', left: 'ihr (plural "you") + die Wohnung (Nominativ)', right: 'eure' },
        { id: 'ch19-ex46-p5', left: 'Sie (formal) + der Koffer (Nominativ)', right: 'Ihr' },
      ],
      explanation: 'The owner picks the stem, and the gender, number, and case of the noun pick the ending: mein Vater, deine Tasche, unseren Schlüssel, eure Wohnung, Ihr Koffer.',
    },
    {
      id: 'ch19-ex-47',
      chapterNumber: 19,
      order: 47,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['possessive-articles', 'ending-agreement', 'accusative-ending'],
      instruction: 'Match each owner and noun to the correctly declined possessive article.',
      prompt: 'Match the situation with the correctly declined possessive article.',
      pairs: [
        { id: 'ch19-ex47-p1', left: 'er + der Hund (Akkusativ)', right: 'seinen' },
        { id: 'ch19-ex47-p2', left: 'sie (singular, "she") + die Katze (Nominativ)', right: 'ihre' },
        { id: 'ch19-ex47-p3', left: 'es + das Spielzeug (Nominativ)', right: 'sein' },
        { id: 'ch19-ex47-p4', left: 'wir + die Großeltern (Akkusativ, Plural)', right: 'unsere' },
        { id: 'ch19-ex47-p5', left: 'ihr (plural "you") + der Freund (Akkusativ)', right: 'euren' },
      ],
      explanation: 'seinen Hund (masc. accusative), ihre Katze (fem. nominative), sein Spielzeug (neut., no ending), unsere Großeltern (plural), euren Freund (masc. accusative, contracted euer).',
    },
    {
      id: 'ch19-ex-48',
      chapterNumber: 19,
      order: 48,
      type: 'matching',
      level: 'production',
      grammarFocus: ['possessive-articles', 'formal-ihr', 'ending-agreement'],
      instruction: 'Match each owner and noun to the correctly declined possessive article.',
      prompt: 'Match the situation with the correctly declined possessive article.',
      pairs: [
        { id: 'ch19-ex48-p1', left: 'Frau Meier (formal, Sie) + der Regenschirm (Nominativ)', right: 'Ihr' },
        { id: 'ch19-ex48-p2', left: 'ich + die Idee (Akkusativ)', right: 'meine' },
        { id: 'ch19-ex48-p3', left: 'wir + der Sohn (Nominativ)', right: 'unser' },
        { id: 'ch19-ex48-p4', left: 'du + der Bruder (Akkusativ)', right: 'deinen' },
        { id: 'ch19-ex48-p5', left: 'ihr (plural "you") + die Freunde (Nominativ, Plural)', right: 'eure' },
      ],
      explanation: 'Ihr Regenschirm (formal, no ending), meine Idee (fem. accusative), unser Sohn (masc., no ending), deinen Bruder (masc. accusative), eure Freunde (plural, contracted euer).',
    },
    {
      id: 'ch19-ex-49',
      chapterNumber: 19,
      order: 49,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['possessive-articles', 'accusative-ending', 'error-correction'],
      instruction: 'Find the token with the wrong possessive ending, and correct it.',
      prompt: 'Ein Kind erzählt, was es sucht. Etwas stimmt nicht.',
      tokens: ['Das', 'Kind', 'sucht', 'sein', 'Ball.'],
      errorTokenIndex: 3,
      correction: 'seinen',
      explanation: 'der Ball is masculine accusative (object of suchen), so sein needs the -en ending: seinen, not sein.',
    },
    {
      id: 'ch19-ex-50',
      chapterNumber: 19,
      order: 50,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['possessive-articles', 'formal-ihr', 'error-correction'],
      instruction: 'Find the token that uses the wrong form of the possessive article, and correct it.',
      prompt: 'Jemand fragt eine fremde Frau höflich nach ihrem Auto. Etwas stimmt nicht.',
      tokens: ['Frau', 'Klar,', 'ist', 'das', 'ihr', 'Auto?'],
      errorTokenIndex: 4,
      correction: 'Ihr',
      explanation: 'Addressing Frau Klar politely requires the formal, capitalized Ihr — lowercase ihr would instead mean "her" or "their".',
    },
  ],
};
