import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter070: ChapterDefinition = {
  id: 'chapter-070',
  number: 70,
  slug: 'adjectives-used-as-nouns-for-people',
  title: 'Adjectives Used as Nouns for People',
  germanTitle: 'Substantivierte Adjektive für Personen',
  level: 'B1',
  section: 'nouns-2',
  objective:
    "Recognize and correctly capitalize and decline German adjectives that function as nouns for people (der Deutsche, eine Bekannte, die Erwachsenen), applying the same weak, strong, and mixed adjective-ending patterns from Chapter 41 as if a noun still followed the adjective, and infer the missing word's gender and number entirely from its article and context.",
  prerequisites: [41],
  estimatedMinutes: 28,
  tags: [
    'substantivized-adjectives',
    'nominalized-adjectives',
    'capitalization',
    'adjective-endings',
    'der-deutsche',
    'weak-declension',
    'strong-declension',
    'gender-agreement',
    'nouns-from-adjectives',
  ],
  explanation: {
    introduction: [
      'German lets many adjectives step into the role of a noun when they describe a person, without ever becoming a genuinely new word: deutsch (German) can become der Deutsche (the German man), bekannt (known, acquainted) can become eine Bekannte (a female acquaintance). Because every German noun is capitalized, these words are capitalized too — but that is the only thing that changes about them. Grammatically, they are still adjectives through and through, and they keep taking exactly the ending an ordinary attributive adjective would take if a noun such as Mann, Frau, or Person still stood right after them.',
      'This is the central, slightly counterintuitive idea of this chapter: der Deutsche declines the same way der gute Mann would, because German treats it as if there were an invisible Mann after Deutsche the whole time. Change the article, and the ending changes exactly as it would for any adjective before a real noun — den Deutschen, dem Deutschen, des Deutschen — while the word itself, its capital D, never moves. Get comfortable with this "phantom noun" idea and the whole pattern becomes a direct application of the endings you already learned in Chapter 41, rather than a new set of rules to memorize.',
      'Because the underlying noun is only implied, nothing in the word itself tells you whether it means a man, a woman, or several people — der Deutsche, die Deutsche, and die Deutschen are, in a sense, the "same word" wearing three different sets of clothes. The article (or the ending, when there is no article) is what carries the gender and number information. This chapter works through the weak endings that appear after der-words, the strong and mixed endings that appear after ein-words or with no article at all, and the special, very common case of using these words with no article whatsoever — Ich bin Deutscher, Deutsche reisen gern.',
    ],
    rules: [
      {
        id: 'ch70-rule-01',
        heading: 'What a substantivized adjective is, and why it is capitalized',
        paragraphs: [
          'A substantivized (or "nominalized") adjective is an ordinary adjective used on its own, without an accompanying noun, to refer to a person who has that quality: bekannt (known) → der/die Bekannte (the acquaintance), erwachsen (grown up) → der/die Erwachsene (the adult), verwandt (related) → der/die Verwandte (the relative), angestellt (employed) → der/die Angestellte (the employee), arbeitslos (unemployed) → der/die Arbeitslose (the unemployed person), obdachlos (homeless) → der/die Obdachlose (the homeless person), fremd (foreign, unfamiliar) → der/die Fremde (the stranger).',
          'German capitalizes every noun, and a substantivized adjective is functioning as a noun — so it gets the capital letter a real noun would get: der Deutsche, not der deutsche. This is purely a spelling convention that signals "this word is doing a noun\'s job right now." It does not turn the word into a different kind of word grammatically: it is still declined exactly like the adjective it always was.',
          'Do not confuse these with genuine nouns that happen to describe nationality or profession, such as der Amerikaner or der Lehrer — those are ordinary nouns with their own noun declension (mostly unchanging, sometimes adding -n only in the weak-masculine pattern). A substantivized adjective like der Deutsche is different: its ending changes with every case, exactly like an adjective, because grammatically that is exactly what it still is.',
        ],
      },
      {
        id: 'ch70-rule-02',
        heading: 'After der-words: the weak endings from Chapter 41',
        paragraphs: [
          'When a substantivized adjective follows a der-word (der, die, das, dieser, jeder, welcher...), it takes exactly the weak endings from Chapter 41, as if the phantom noun were still there. In the masculine singular: der Deutsche (nominative), den Deutschen (accusative), dem Deutschen (dative), des Deutschen (genitive) — only the nominative keeps -e; everything else switches to -en, the familiar "-en pattern" from Chapter 41.',
          'In the feminine singular the ending is even more uniform: die Deutsche (nominative and accusative both use -e), der Deutschen (dative), der Deutschen (genitive) — again, exactly the ending an ordinary feminine adjective would take in the same position. Ich kenne die Bekannte. Ich helfe der Bekannten. Wegen der Bekannten kam sie zu spät. (Because of the acquaintance, she arrived late.)',
          'The plural after die works the same way as any plural adjective: -en in every case. Die Erwachsenen entscheiden das. Ich sehe die Erwachsenen. Ich helfe den Erwachsenen. Wegen der Erwachsenen. The declension is not a special rule for these words — it is simply the Chapter 41 adjective-ending table, applied to a word that happens to also serve as the noun.',
        ],
      },
      {
        id: 'ch70-rule-03',
        heading: 'After ein-words or with no article: strong and mixed endings',
        paragraphs: [
          'Ein, kein, and the possessives (mein, dein, sein...) do not always show gender as clearly as der/die/das does, so — exactly as with ordinary adjectives — the masculine nominative singular has to carry that information itself, with the strong ending -er: ein Deutscher, ein Fremder, ein Bekannter. Compare this with the feminine, which still takes the familiar -e: eine Deutsche, eine Fremde, eine Bekannte — ein and eine already mark the feminine clearly enough that no extra signal is needed there.',
          "Outside the masculine nominative singular, ein-words behave just like der-words: einen Deutschen (accusative), einem Deutschen (dative), eines Deutschen (genitive); einer Deutschen (feminine dative and genitive). Only that one cell of the whole paradigm — masculine, nominative, singular, after ein — is different, and it is different for the same reason ein guter Mann has -er instead of der gute Mann's -e.",
          'Two adjectives can stack in front of the same phantom noun without any conflict: an ordinary, lowercase adjective plus the substantivized one, each taking its own normal ending — ein guter Bekannter (a good acquaintance), eine nette Fremde (a nice stranger). The ordinary adjective and the substantivized one simply agree with each other, exactly as two adjectives before any real noun would.',
        ],
      },
      {
        id: 'ch70-rule-04',
        heading: 'Plural without an article, and keine/meine',
        paragraphs: [
          'After keine or a possessive plural (meine, seine, unsere...), the plural still takes -en in every case, just like after die: keine Deutschen, meine Verwandten, unseren Angestellten. The plural collapses onto -en almost everywhere, exactly as Chapter 41 already showed for ordinary adjectives.',
          'With no article at all, the plural instead takes the strong ending -e in the nominative and accusative, and -en in the dative — again, the same strong-plural pattern an ordinary adjective would take with no article: Deutsche reisen gern. (Germans like to travel.) Ich habe mit Angestellten gesprochen. (I spoke with employees.) This bare plural is used for general statements about a group, not one particular, already-identified set of people.',
        ],
      },
      {
        id: 'ch70-rule-05',
        heading: 'Gender and number live in the article, not in the word',
        paragraphs: [
          'The base form of a substantivized adjective — Deutsche, Bekannte, Erwachsene — carries no built-in gender or number by itself; only the article (or, without one, the ending) tells you whether a man, a woman, or several people are meant. Der Deutsche and die Deutsche are spelled identically apart from the article; die Deutschen (plural) also looks the same as die Deutsche (feminine singular) apart from the final -n. Always read the article and the ending together, never the word in isolation.',
          'This is exactly why the "phantom noun" idea from the introduction is worth keeping in mind: der Bekannte, die Bekannte, and die Bekannten are the masculine, feminine, and plural forms of one underlying idea ("[known person]"), just as der gute Mann, die gute Frau, and die guten Leute are three forms built from one adjective, gut.',
        ],
      },
      {
        id: 'ch70-rule-06',
        heading: 'No article at all: predicate nominative — Ich bin Deutscher / Deutsche',
        paragraphs: [
          'A very common everyday use of these words has no article whatsoever: stating someone\'s identity after sein (to be) or werden (to become), the way English says "I am German." German instead uses the substantivized noun with the appropriate strong ending and no article: Ich bin Deutscher. (said by a man) Sie ist Deutsche. (said about a woman) Er ist Erwachsener. Wird sie Angestellte bei dieser Firma?',
          'The ending here follows the same strong pattern as the ein-word masculine nominative (-er) and the ordinary feminine (-e), just with the article dropped entirely — because there is no article left to carry any grammatical information, the adjective ending has to do that job on its own, exactly as in the bare-plural pattern from the previous rule.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch70-table-01',
        title: 'Substantivized Adjectives for People — Vocabulary',
        columns: ['Adjective', 'Masculine', 'Feminine', 'English'],
        rows: [
          ['deutsch', 'der Deutsche', 'die Deutsche', 'German (person)'],
          ['bekannt', 'der Bekannte', 'die Bekannte', 'acquaintance'],
          ['erwachsen', 'der Erwachsene', 'die Erwachsene', 'adult'],
          ['verwandt', 'der Verwandte', 'die Verwandte', 'relative'],
          ['angestellt', 'der Angestellte', 'die Angestellte', 'employee'],
          ['arbeitslos', 'der Arbeitslose', 'die Arbeitslose', 'unemployed person'],
          ['obdachlos', 'der Obdachlose', 'die Obdachlose', 'homeless person'],
          ['fremd', 'der Fremde', 'die Fremde', 'stranger, foreigner'],
        ],
        note: "Each word is still, grammatically, the plain adjective on the left — it simply appears without a following noun and is capitalized because it is doing a noun's job.",
      },
      {
        id: 'ch70-table-02',
        title: 'Weak Declension After der-words (der Deutsche)',
        columns: [
          'Case',
          'Masculine — der Deutsche',
          'Feminine — die Deutsche',
          'Plural — die Deutschen',
        ],
        rows: [
          ['Nominative', 'der Deutsche', 'die Deutsche', 'die Deutschen'],
          ['Accusative', 'den Deutschen', 'die Deutsche', 'die Deutschen'],
          ['Dative', 'dem Deutschen', 'der Deutschen', 'den Deutschen'],
          ['Genitive', 'des Deutschen', 'der Deutschen', 'der Deutschen'],
        ],
        note: 'This is exactly the Chapter 41 weak-adjective table: only the masculine nominative keeps -e; every other cell is -en.',
      },
      {
        id: 'ch70-table-03',
        title: 'Strong/Mixed Declension After ein-words (ein Deutscher)',
        columns: [
          'Case',
          'Masculine — ein Deutscher',
          'Feminine — eine Deutsche',
          'Plural — keine Deutschen',
        ],
        rows: [
          ['Nominative', 'ein Deutscher', 'eine Deutsche', 'keine Deutschen'],
          ['Accusative', 'einen Deutschen', 'eine Deutsche', 'keine Deutschen'],
          ['Dative', 'einem Deutschen', 'einer Deutschen', 'keinen Deutschen'],
          ['Genitive', 'eines Deutschen', 'einer Deutschen', 'keiner Deutschen'],
        ],
        note: 'Only the masculine nominative singular differs from the der-word table (-er instead of -e), because ein itself does not mark gender the way der does.',
      },
      {
        id: 'ch70-table-04',
        title: 'Genitive Side by Side',
        columns: ['Article type', 'Masculine', 'Feminine', 'Plural'],
        columnCases: [null, 'genitive', 'genitive', 'genitive'],
        rows: [
          ['des/der/der (definite)', 'des Deutschen', 'der Deutschen', 'der Deutschen'],
          [
            'eines/einer/keiner (indefinite)',
            'eines Deutschen',
            'einer Deutschen',
            'keiner Deutschen',
          ],
        ],
        note: 'In the genitive, masculine and feminine forms already look alike after both article types — only the article itself distinguishes them.',
      },
      {
        id: 'ch70-table-05',
        title: 'With No Article at All (Nominative)',
        columns: ['Context', 'Example', 'English'],
        columnCases: [null, 'nominative', null],
        rows: [
          [
            'Predicate, masculine (Ich bin ...)',
            'Ich bin Deutscher.',
            'I am German (a German man).',
          ],
          [
            'Predicate, feminine (Sie ist ...)',
            'Sie ist Deutsche.',
            'She is German (a German woman).',
          ],
          [
            'Bare plural, general statement',
            'Deutsche reisen gern.',
            'Germans like to travel.',
          ],
          [
            'Bare plural, general statement',
            'Erwachsene müssen das entscheiden.',
            'Adults have to decide that.',
          ],
        ],
        note: 'With no article, the strong endings appear (-er masculine, -e feminine and plural) because the ending alone must carry the grammatical information.',
      },
    ],
    examples: [
      {
        german: 'Der Deutsche wohnt seit zehn Jahren in Spanien.',
        english: 'The German man has lived in Spain for ten years.',
        highlight: ['Der Deutsche'],
        explanation:
          "Masculine nominative singular after der: the weak ending -e, capitalized because Deutsche is doing a noun's job.",
      },
      {
        german: 'Ich kenne eine Bekannte aus meinem Deutschkurs.',
        english: 'I know a (female) acquaintance from my German course.',
        highlight: ['eine Bekannte'],
        explanation:
          'Feminine accusative singular after eine: the ending -e, the same shape it would have in the nominative.',
      },
      {
        german: 'Wir haben mit dem Angestellten gesprochen.',
        english: 'We spoke with the employee.',
        highlight: ['dem Angestellten'],
        explanation:
          'Dative masculine singular after dem: the ending switches to -en, exactly like an ordinary adjective in the dative.',
      },
      {
        german: 'Die Erwachsenen müssen für die Kinder ein Vorbild sein.',
        english: 'The adults have to be a role model for the children.',
        highlight: ['Die Erwachsenen'],
        explanation:
          'Plural after die: -en in every case, regardless of the gender the word would have in the singular.',
      },
      {
        german: 'Er hilft einem Obdachlosen jeden Tag.',
        english: 'He helps a homeless person every day.',
        highlight: ['einem Obdachlosen'],
        explanation:
          'Dative masculine singular after einem: -en, matching the der-word dative exactly.',
      },
      {
        german: 'Meine Verwandte aus Hamburg besucht uns morgen.',
        english: 'My relative from Hamburg is visiting us tomorrow.',
        highlight: ['Meine Verwandte'],
        explanation:
          'meine behaves like a der-word here; feminine nominative singular takes -e.',
      },
      {
        german: 'Die Firma hat drei neue Angestellte eingestellt.',
        english: 'The company has hired three new employees.',
        highlight: ['neue Angestellte'],
        explanation:
          'A number with no article: bare plural, strong accusative ending -e, just like an ordinary adjective would take here.',
      },
      {
        german: 'Ich bin Deutscher, aber ich wohne in Frankreich.',
        english: 'I am German (a German man), but I live in France.',
        highlight: ['Deutscher'],
        explanation:
          'Predicate nominative with no article: masculine strong ending -er, the same ending that appears after ein.',
      },
      {
        german: 'Sie ist Deutsche und spricht drei Sprachen.',
        english: 'She is German (a German woman) and speaks three languages.',
        highlight: ['Deutsche'],
        explanation:
          'Feminine predicate nominative with no article: -e, identical in shape to the feminine ending everywhere else.',
      },
      {
        german: 'Das Schicksal der Arbeitslosen beschäftigt die Politik.',
        english: 'The fate of the unemployed concerns politics.',
        highlight: ['der Arbeitslosen'],
        explanation:
          'Genitive plural after der: -en, following the ordinary Chapter 41 plural pattern.',
      },
      {
        german: 'Kennst du den Bekannten von Julia?',
        english: "Do you know Julia's (male) acquaintance?",
        highlight: ['den Bekannten'],
        explanation:
          'Accusative masculine singular after den: -en, exactly like den guten Mann.',
      },
      {
        german: 'Ein Fremder fragte mich nach dem Weg.',
        english: 'A stranger asked me for directions.',
        highlight: ['Ein Fremder'],
        explanation:
          'Nominative masculine singular after ein: the strong ending -er, since ein does not mark gender on its own.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'der deutsche',
        correct: 'der Deutsche',
        explanation:
          'A substantivized adjective is capitalized like the noun it stands in for, even though it still declines like an adjective — do not leave it lowercase.',
      },
      {
        incorrect: 'der Deutsche Mann',
        correct: 'der deutsche Mann (or simply: der Deutsche)',
        explanation:
          'Do not combine both patterns: either keep deutsch lowercase as an ordinary adjective in front of the real noun Mann, or drop Mann and let Deutsche carry the meaning alone, capitalized.',
      },
      {
        incorrect: 'der Deutscher',
        correct: 'der Deutsche',
        explanation:
          'After a der-word, the nominative ending is always -e, not -er; -er only appears after ein or with no article, where nothing else marks the masculine gender.',
      },
      {
        incorrect: 'ein Deutsche',
        correct: 'ein Deutscher',
        explanation:
          'After ein, the masculine nominative singular needs the strong ending -er, because ein alone does not show that the noun is masculine; -e is reserved for the feminine.',
      },
      {
        incorrect: 'Ich spreche mit der Deutsche.',
        correct: 'Ich spreche mit der Deutschen.',
        explanation:
          'mit takes the dative; the feminine dative singular ending is -en, not the nominative/accusative -e.',
      },
      {
        incorrect: 'Die Erwachsene sind hier verantwortlich.',
        correct: 'Die Erwachsenen sind hier verantwortlich.',
        explanation:
          'After the plural article die, the ending is always -en, not the bare strong -e used only when there is no article at all.',
      },
    ],
    remember: [
      'Adjectives describing a person can be used on their own as nouns; they are capitalized like nouns but keep declining exactly like ordinary attributive adjectives, as if an invisible noun still followed them.',
      'After der-words, the pattern is the weak Chapter 41 ending: -e in the masculine nominative singular, -en everywhere else in the singular and throughout the plural (der Deutsche, den/dem/des Deutschen).',
      'After ein-words or with no article, the masculine nominative singular needs the strong ending -er (ein Deutscher), since nothing else marks the gender; the feminine still takes -e (eine Deutsche) in every one of these contexts.',
      'The word itself carries no fixed gender or number — der Deutsche, die Deutsche, and die Deutschen are the same underlying idea wearing three different articles and endings.',
      'The plural takes -en after die/keine/possessives, and the strong -e (nominative/accusative) or -en (dative) with no article at all, for general statements like Deutsche reisen gern.',
      "With no article, stating someone's nationality, age group, or role after sein/werden uses the strong ending directly: Ich bin Deutscher. Sie ist Deutsche.",
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 96,
    requiredCorrectTextInputs: 30,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch70-ex-01',
      chapterNumber: 70,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['substantivized-adjectives', 'capitalization'],
      instruction: 'Choose the correctly capitalized and spelled form.',
      prompt:
        'Which is correct? "___ wohnt seit zehn Jahren in Spanien." (the German man)',
      options: [
        { id: 'a', text: 'Der Deutsche' },
        { id: 'b', text: 'der deutsche' },
        { id: 'c', text: 'Der deutsche' },
        { id: 'd', text: 'Der Deutsche Mann' },
      ],
      correctOptionId: 'a',
      explanation:
        'Der Deutsche is the correctly capitalized substantivized adjective; "Mann" is redundant once Deutsche is capitalized and stands for the noun itself.',
    },
    {
      id: 'ch70-ex-02',
      chapterNumber: 70,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['substantivized-adjectives', 'capitalization', 'stacked-adjectives'],
      instruction: 'Choose the correctly written sentence.',
      prompt: 'Which sentence is correctly written?',
      options: [
        { id: 'a', text: 'Er ist ein guter Bekannter von mir.' },
        { id: 'b', text: 'Er ist ein guter bekannter von mir.' },
        { id: 'c', text: 'Er ist ein guter Bekannte von mir.' },
        { id: 'd', text: 'er ist ein guter Bekannter von mir.' },
      ],
      correctOptionId: 'a',
      explanation:
        'guter is an ordinary adjective agreeing with Bekannter, which is capitalized (it is the substantivized noun) and takes the masculine -er ending after ein.',
    },
    {
      id: 'ch70-ex-03',
      chapterNumber: 70,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'nominative'],
      instruction: 'Choose the correct form for the masculine nominative after der.',
      prompt: '___ kommt aus Berlin und arbeitet hier seit fünf Jahren.',
      options: [
        { id: 'a', text: 'Der Deutsche' },
        { id: 'b', text: 'Der Deutscher' },
        { id: 'c', text: 'Der Deutschen' },
        { id: 'd', text: 'Die Deutsche' },
      ],
      correctOptionId: 'a',
      explanation:
        'After der, the masculine nominative singular ending is -e: Der Deutsche.',
    },
    {
      id: 'ch70-ex-04',
      chapterNumber: 70,
      order: 4,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'nominative'],
      instruction: 'Choose the correct form for the masculine nominative after ein.',
      prompt: 'Vor der Tür stand ___ und fragte nach dem Weg.',
      options: [
        { id: 'a', text: 'ein Fremder' },
        { id: 'b', text: 'ein Fremde' },
        { id: 'c', text: 'ein Fremden' },
        { id: 'd', text: 'einen Fremden' },
      ],
      correctOptionId: 'a',
      explanation:
        'After ein, the masculine nominative singular takes the strong ending -er, since ein does not mark gender on its own.',
    },
    {
      id: 'ch70-ex-05',
      chapterNumber: 70,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'accusative'],
      instruction: 'Choose the correct accusative form.',
      prompt: 'Kennst du ___ von Julia?',
      options: [
        { id: 'a', text: 'den Bekannten' },
        { id: 'b', text: 'den Bekannte' },
        { id: 'c', text: 'der Bekannte' },
        { id: 'd', text: 'dem Bekannten' },
      ],
      correctOptionId: 'a',
      explanation:
        'Masculine accusative singular after den: -en, exactly like den guten Mann.',
    },
    {
      id: 'ch70-ex-06',
      chapterNumber: 70,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative'],
      instruction: 'Choose the correct dative form.',
      prompt: 'Wir haben mit ___ gesprochen.',
      options: [
        { id: 'a', text: 'dem Angestellten' },
        { id: 'b', text: 'dem Angestellte' },
        { id: 'c', text: 'den Angestellte' },
        { id: 'd', text: 'des Angestellten' },
      ],
      correctOptionId: 'a',
      explanation: 'Masculine dative singular after dem: -en. mit takes the dative.',
    },
    {
      id: 'ch70-ex-07',
      chapterNumber: 70,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative', 'feminine'],
      instruction: 'Choose the correct dative form.',
      prompt: 'Ich helfe ___ gern.',
      options: [
        { id: 'a', text: 'der Verwandten' },
        { id: 'b', text: 'der Verwandte' },
        { id: 'c', text: 'die Verwandte' },
        { id: 'd', text: 'den Verwandten' },
      ],
      correctOptionId: 'a',
      explanation:
        'helfen takes the dative; the feminine dative singular ending is -en, not the nominative/accusative -e.',
    },
    {
      id: 'ch70-ex-08',
      chapterNumber: 70,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'genitive'],
      instruction: 'Choose the correct genitive form.',
      prompt: 'Das Auto ___ steht vor dem Haus.',
      options: [
        { id: 'a', text: 'des Bekannten' },
        { id: 'b', text: 'der Bekannte' },
        { id: 'c', text: 'des Bekannte' },
        { id: 'd', text: 'dem Bekannten' },
      ],
      correctOptionId: 'a',
      explanation:
        'Masculine genitive singular after des: -en, exactly like des guten Mannes would use -en on the adjective.',
    },
    {
      id: 'ch70-ex-09',
      chapterNumber: 70,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'plural', 'nominative'],
      instruction: 'Choose the correct plural form.',
      prompt: '___ dürfen an der Wahl teilnehmen.',
      options: [
        { id: 'a', text: 'Die Erwachsenen' },
        { id: 'b', text: 'Die Erwachsene' },
        { id: 'c', text: 'Den Erwachsenen' },
        { id: 'd', text: 'Die Erwachsener' },
      ],
      correctOptionId: 'a',
      explanation: 'After die, the plural ending is -en in every case: Die Erwachsenen.',
    },
    {
      id: 'ch70-ex-10',
      chapterNumber: 70,
      order: 10,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'dative'],
      instruction: 'Choose the correct plural dative form.',
      prompt: 'Der Staat hilft ___ finanziell.',
      options: [
        { id: 'a', text: 'den Arbeitslosen' },
        { id: 'b', text: 'die Arbeitslosen' },
        { id: 'c', text: 'den Arbeitslose' },
        { id: 'd', text: 'der Arbeitslosen' },
      ],
      correctOptionId: 'a',
      explanation:
        'helfen takes the dative; the plural dative article is den, and the adjective ending is -en: den Arbeitslosen.',
    },
    {
      id: 'ch70-ex-11',
      chapterNumber: 70,
      order: 11,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'bare-plural', 'no-article'],
      instruction: 'Choose the correct form for a general statement with no article.',
      prompt: '___ reisen gern ins Ausland.',
      options: [
        { id: 'a', text: 'Deutsche' },
        { id: 'b', text: 'Die Deutschen' },
        { id: 'c', text: 'Deutschen' },
        { id: 'd', text: 'Der Deutsche' },
      ],
      correctOptionId: 'a',
      explanation:
        'With no article, a general statement about the group takes the bare strong plural ending -e: Deutsche reisen gern.',
    },
    {
      id: 'ch70-ex-12',
      chapterNumber: 70,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'predicate-nominative', 'no-article'],
      instruction: 'Choose the correct predicate form with no article.',
      prompt: 'Ich bin ___, aber ich wohne in Frankreich.',
      options: [
        { id: 'a', text: 'Deutscher' },
        { id: 'b', text: 'Deutsche' },
        { id: 'c', text: 'der Deutsche' },
        { id: 'd', text: 'Deutschen' },
      ],
      correctOptionId: 'a',
      explanation:
        'A man stating his nationality with sein and no article uses the strong masculine ending: Ich bin Deutscher.',
    },
    {
      id: 'ch70-ex-13',
      chapterNumber: 70,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: [
        'substantivized-adjectives',
        'predicate-nominative',
        'no-article',
        'feminine',
      ],
      instruction: 'Choose the correct predicate form with no article.',
      prompt: 'Sie ist ___, kommt aber ursprünglich aus Polen.',
      options: [
        { id: 'a', text: 'Deutsche' },
        { id: 'b', text: 'Deutscher' },
        { id: 'c', text: 'die Deutsche' },
        { id: 'd', text: 'Deutschen' },
      ],
      correctOptionId: 'a',
      explanation:
        'A woman stating her nationality with sein and no article uses the ending -e: Sie ist Deutsche.',
    },
    {
      id: 'ch70-ex-14',
      chapterNumber: 70,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'noun-vs-adjective-declension'],
      instruction:
        'Choose the word that declines like an adjective, not like a regular noun.',
      prompt:
        'Which of these words changes its ending with every case, exactly like an attributive adjective?',
      options: [
        { id: 'a', text: 'der Deutsche' },
        { id: 'b', text: 'der Amerikaner' },
        { id: 'c', text: 'der Lehrer' },
        { id: 'd', text: 'der Student' },
      ],
      correctOptionId: 'a',
      explanation:
        'der Deutsche is a substantivized adjective and declines like one (den/dem/des Deutschen); der Amerikaner and der Lehrer barely change, and der Student is a regular weak-masculine noun with its own separate pattern.',
    },
    {
      id: 'ch70-ex-15',
      chapterNumber: 70,
      order: 15,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'feminine', 'nominative'],
      instruction: 'Choose the correct feminine form after eine.',
      prompt: 'Sie ist ___ von mir.',
      options: [
        { id: 'a', text: 'eine Bekannte' },
        { id: 'b', text: 'eine Bekannter' },
        { id: 'c', text: 'eine Bekannten' },
        { id: 'd', text: 'die Bekannte' },
      ],
      correctOptionId: 'a',
      explanation:
        'The feminine nominative singular ending after eine is -e, exactly as after der: eine Bekannte.',
    },
    {
      id: 'ch70-ex-16',
      chapterNumber: 70,
      order: 16,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'bare-plural', 'translation'],
      instruction: 'Choose the best translation.',
      prompt: 'Choose the best translation of: "Employees need more support."',
      options: [
        { id: 'a', text: 'Angestellte brauchen mehr Unterstützung.' },
        { id: 'b', text: 'Die Angestellte brauchen mehr Unterstützung.' },
        { id: 'c', text: 'Angestellten brauchen mehr Unterstützung.' },
        { id: 'd', text: 'Der Angestellte brauchen mehr Unterstützung.' },
      ],
      correctOptionId: 'a',
      explanation:
        'A general statement with no article about a plural group uses the bare strong plural ending -e: Angestellte brauchen mehr Unterstützung.',
    },
    {
      id: 'ch70-ex-17',
      chapterNumber: 70,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: [
        'substantivized-adjectives',
        'capitalization',
        'der-words',
        'nominative',
      ],
      instruction:
        'Write the correctly capitalized and declined form. Capitalisation is checked.',
      prompt: 'der + deutsch (person, masculine, nominative)',
      acceptedAnswers: ['der Deutsche'],
      answerMode: 'normalized',
      placeholder: 'der Deutsche',
      maxLength: 20,
      explanation:
        'After der, the masculine nominative singular ending is -e: der Deutsche.',
    },
    {
      id: 'ch70-ex-18',
      chapterNumber: 70,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: [
        'substantivized-adjectives',
        'capitalization',
        'ein-words',
        'feminine',
        'nominative',
      ],
      instruction:
        'Write the correctly capitalized and declined form. Capitalisation is checked.',
      prompt: 'eine + bekannt (person, feminine, nominative)',
      acceptedAnswers: ['eine Bekannte'],
      answerMode: 'normalized',
      placeholder: 'eine Bekannte',
      maxLength: 20,
      explanation:
        'The feminine nominative singular ending after eine is -e: eine Bekannte.',
    },
    {
      id: 'ch70-ex-19',
      chapterNumber: 70,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'accusative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'den + bekannt (masculine, accusative)',
      acceptedAnswers: ['den Bekannten'],
      answerMode: 'normalized',
      placeholder: 'den Bekannten',
      maxLength: 20,
      explanation: 'Masculine accusative singular after den takes -en: den Bekannten.',
    },
    {
      id: 'ch70-ex-20',
      chapterNumber: 70,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'dem + angestellt (masculine, dative)',
      acceptedAnswers: ['dem Angestellten'],
      answerMode: 'normalized',
      placeholder: 'dem Angestellten',
      maxLength: 20,
      explanation: 'Masculine dative singular after dem takes -en: dem Angestellten.',
    },
    {
      id: 'ch70-ex-21',
      chapterNumber: 70,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative', 'feminine'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'der + verwandt (feminine, dative)',
      acceptedAnswers: ['der Verwandten'],
      answerMode: 'normalized',
      placeholder: 'der Verwandten',
      maxLength: 20,
      explanation: 'Feminine dative singular after der takes -en: der Verwandten.',
    },
    {
      id: 'ch70-ex-22',
      chapterNumber: 70,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'genitive'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'des + bekannt (masculine, genitive)',
      acceptedAnswers: ['des Bekannten'],
      answerMode: 'normalized',
      placeholder: 'des Bekannten',
      maxLength: 20,
      explanation: 'Masculine genitive singular after des takes -en: des Bekannten.',
    },
    {
      id: 'ch70-ex-23',
      chapterNumber: 70,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'nominative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'die + erwachsen (plural, nominative)',
      acceptedAnswers: ['die Erwachsenen'],
      answerMode: 'normalized',
      placeholder: 'die Erwachsenen',
      maxLength: 20,
      explanation: 'Plural after die takes -en in every case: die Erwachsenen.',
    },
    {
      id: 'ch70-ex-24',
      chapterNumber: 70,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'dative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'den + arbeitslos (plural, dative)',
      acceptedAnswers: ['den Arbeitslosen'],
      answerMode: 'normalized',
      placeholder: 'den Arbeitslosen',
      maxLength: 20,
      explanation: 'Plural dative after den takes -en: den Arbeitslosen.',
    },
    {
      id: 'ch70-ex-25',
      chapterNumber: 70,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'nominative'],
      instruction:
        'Write the correctly declined form (masculine, no der-word). Capitalisation is checked.',
      prompt: 'ein + fremd (masculine, nominative)',
      acceptedAnswers: ['ein Fremder'],
      answerMode: 'normalized',
      placeholder: 'ein Fremder',
      maxLength: 20,
      explanation:
        'After ein, the masculine nominative singular needs the strong ending -er: ein Fremder.',
    },
    {
      id: 'ch70-ex-26',
      chapterNumber: 70,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'feminine', 'nominative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'eine + obdachlos (feminine, nominative)',
      acceptedAnswers: ['eine Obdachlose'],
      answerMode: 'normalized',
      placeholder: 'eine Obdachlose',
      maxLength: 20,
      explanation:
        'The feminine nominative singular ending after eine is -e: eine Obdachlose.',
    },
    {
      id: 'ch70-ex-27',
      chapterNumber: 70,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'conversion', 'nominative'],
      instruction:
        'Rewrite the sentence using a substantivized adjective instead of the adjective + noun phrase. Capitalisation and punctuation are checked.',
      prompt: 'Der deutsche Mann wohnt in Spanien. → substantivized',
      acceptedAnswers: [
        'Der Deutsche wohnt in Spanien.',
        'Der Deutsche wohnt in Spanien',
      ],
      answerMode: 'normalized',
      placeholder: 'Der Deutsche wohnt in Spanien.',
      maxLength: 40,
      explanation:
        'Dropping Mann and capitalizing deutsch keeps the same nominative ending -e: Der Deutsche wohnt in Spanien.',
    },
    {
      id: 'ch70-ex-28',
      chapterNumber: 70,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'conversion', 'nominative', 'feminine'],
      instruction:
        'Rewrite the sentence using a substantivized adjective instead of the adjective + noun phrase. Capitalisation and punctuation are checked.',
      prompt: 'Die deutsche Frau spricht drei Sprachen. → substantivized',
      acceptedAnswers: [
        'Die Deutsche spricht drei Sprachen.',
        'Die Deutsche spricht drei Sprachen',
      ],
      answerMode: 'normalized',
      placeholder: 'Die Deutsche spricht drei Sprachen.',
      maxLength: 45,
      explanation:
        'Dropping Frau and capitalizing deutsch keeps the feminine nominative ending -e: Die Deutsche spricht drei Sprachen.',
    },
    {
      id: 'ch70-ex-29',
      chapterNumber: 70,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'conversion', 'dative'],
      instruction:
        'Rewrite the sentence using a substantivized adjective instead of the adjective + noun phrase. Capitalisation and punctuation are checked.',
      prompt: 'Er hilft der bekannten Frau. → substantivized',
      acceptedAnswers: ['Er hilft der Bekannten.', 'Er hilft der Bekannten'],
      answerMode: 'normalized',
      placeholder: 'Er hilft der Bekannten.',
      maxLength: 35,
      explanation:
        'Dropping Frau and capitalizing bekannten keeps the feminine dative ending -en, unchanged: Er hilft der Bekannten.',
    },
    {
      id: 'ch70-ex-30',
      chapterNumber: 70,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'conversion', 'plural', 'accusative'],
      instruction:
        'Rewrite the sentence using a substantivized adjective instead of the adjective + noun phrase. Capitalisation and punctuation are checked.',
      prompt: 'Wir kennen die erwachsenen Kinder. → substantivized',
      acceptedAnswers: ['Wir kennen die Erwachsenen.', 'Wir kennen die Erwachsenen'],
      answerMode: 'normalized',
      placeholder: 'Wir kennen die Erwachsenen.',
      maxLength: 35,
      explanation:
        'Dropping Kinder and capitalizing erwachsenen keeps the plural ending -en, unchanged: Wir kennen die Erwachsenen.',
    },
    {
      id: 'ch70-ex-31',
      chapterNumber: 70,
      order: 31,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'predicate-nominative', 'no-article'],
      instruction:
        'Complete the sentence with the correct form (masculine, no article). Capitalisation is checked.',
      prompt: 'Ich bin ___ (deutsch, masculine, predicate, no article).',
      acceptedAnswers: ['Deutscher'],
      answerMode: 'normalized',
      placeholder: 'Deutscher',
      maxLength: 15,
      explanation:
        'A man stating his nationality with sein and no article uses the strong ending -er: Deutscher.',
    },
    {
      id: 'ch70-ex-32',
      chapterNumber: 70,
      order: 32,
      type: 'textInput',
      level: 'production',
      grammarFocus: [
        'substantivized-adjectives',
        'predicate-nominative',
        'no-article',
        'feminine',
      ],
      instruction:
        'Complete the sentence with the correct form (feminine, no article). Capitalisation is checked.',
      prompt: 'Sie ist ___ (deutsch, feminine, predicate, no article).',
      acceptedAnswers: ['Deutsche'],
      answerMode: 'normalized',
      placeholder: 'Deutsche',
      maxLength: 15,
      explanation:
        'A woman stating her nationality with sein and no article uses the ending -e: Deutsche.',
    },
    {
      id: 'ch70-ex-33',
      chapterNumber: 70,
      order: 33,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'nominative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Der Arzt sagt, dass der Patient Ruhe braucht.',
      templateParts: ['Der ', ' hat Fieber.'],
      slots: [{ id: 'slot-1', correctWord: 'Kranke' }],
      wordBank: ['Kranke', 'Kranken', 'Kranker', 'Reisende'],
      explanation: 'Masculine nominative singular after der: -e. Der Kranke hat Fieber.',
    },
    {
      id: 'ch70-ex-34',
      chapterNumber: 70,
      order: 34,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'accusative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct accusative form.',
      templateParts: ['Der Arzt untersucht den ', '.'],
      slots: [{ id: 'slot-1', correctWord: 'Kranken' }],
      wordBank: ['Kranken', 'Kranke', 'Kranker', 'Bekannten'],
      explanation:
        'Masculine accusative singular after den: -en. Der Arzt untersucht den Kranken.',
    },
    {
      id: 'ch70-ex-35',
      chapterNumber: 70,
      order: 35,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct dative form.',
      templateParts: ['Die Schwester hilft dem ', '.'],
      slots: [{ id: 'slot-1', correctWord: 'Kranken' }],
      wordBank: ['Kranken', 'Kranke', 'Kranker', 'Angestellten'],
      explanation: 'helfen takes the dative; masculine dative singular after dem: -en.',
    },
    {
      id: 'ch70-ex-36',
      chapterNumber: 70,
      order: 36,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'genitive'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct genitive form.',
      templateParts: ['Die Akte des ', ' liegt hier.'],
      slots: [{ id: 'slot-1', correctWord: 'Kranken' }],
      wordBank: ['Kranken', 'Kranke', 'Kranker', 'Arbeitslosen'],
      explanation:
        'Masculine genitive singular after des: -en. Die Akte des Kranken liegt hier.',
    },
    {
      id: 'ch70-ex-37',
      chapterNumber: 70,
      order: 37,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'nominative', 'feminine'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct feminine nominative form.',
      templateParts: ['Die ', ' wartet im Flur.'],
      slots: [{ id: 'slot-1', correctWord: 'Reisende' }],
      wordBank: ['Reisende', 'Reisenden', 'Reisender', 'Kranke'],
      explanation:
        'Feminine nominative singular after die: -e. Die Reisende wartet im Flur.',
    },
    {
      id: 'ch70-ex-38',
      chapterNumber: 70,
      order: 38,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative', 'feminine'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct feminine dative form.',
      templateParts: ['Der Schaffner hilft der ', '.'],
      slots: [{ id: 'slot-1', correctWord: 'Reisenden' }],
      wordBank: ['Reisenden', 'Reisende', 'Reisender', 'Bekannten'],
      explanation: 'helfen takes the dative; feminine dative singular after der: -en.',
    },
    {
      id: 'ch70-ex-39',
      chapterNumber: 70,
      order: 39,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'nominative'],
      instruction: 'Drag the correct form into the slot.',
      prompt:
        'Complete the sentence with the correct masculine nominative form after ein.',
      templateParts: ['Ein ', ' betrat den Warteraum.'],
      slots: [{ id: 'slot-1', correctWord: 'Reisender' }],
      wordBank: ['Reisender', 'Reisende', 'Reisenden', 'Fremder'],
      explanation:
        'After ein, the masculine nominative singular needs the strong ending -er: ein Reisender.',
    },
    {
      id: 'ch70-ex-40',
      chapterNumber: 70,
      order: 40,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'accusative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct accusative form after einen.',
      templateParts: ['Ich sehe einen ', ' am Bahnsteig.'],
      slots: [{ id: 'slot-1', correctWord: 'Reisenden' }],
      wordBank: ['Reisenden', 'Reisende', 'Reisender', 'Kranken'],
      explanation: 'After einen, the masculine accusative singular ending is -en.',
    },
    {
      id: 'ch70-ex-41',
      chapterNumber: 70,
      order: 41,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'dative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct dative form after einem.',
      templateParts: ['Ich spreche mit einem ', '.'],
      slots: [{ id: 'slot-1', correctWord: 'Reisenden' }],
      wordBank: ['Reisenden', 'Reisende', 'Reisender', 'Angestellten'],
      explanation: 'After einem, the masculine dative singular ending is -en.',
    },
    {
      id: 'ch70-ex-42',
      chapterNumber: 70,
      order: 42,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'genitive'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct genitive form after eines.',
      templateParts: ['Der Koffer eines ', ' steht hier.'],
      slots: [{ id: 'slot-1', correctWord: 'Reisenden' }],
      wordBank: ['Reisenden', 'Reisende', 'Reisender', 'Bekannten'],
      explanation: 'After eines, the masculine genitive singular ending is -en.',
    },
    {
      id: 'ch70-ex-43',
      chapterNumber: 70,
      order: 43,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'nominative', 'feminine'],
      instruction: 'Drag the correct form into the slot.',
      prompt:
        'Complete the sentence with the correct feminine nominative form after eine.',
      templateParts: ['Sie ist eine ', ' aus Berlin.'],
      slots: [{ id: 'slot-1', correctWord: 'Bekannte' }],
      wordBank: ['Bekannte', 'Bekannten', 'Bekannter', 'Fremde'],
      explanation:
        'Feminine nominative singular after eine: -e, the same shape as after die.',
    },
    {
      id: 'ch70-ex-44',
      chapterNumber: 70,
      order: 44,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'dative', 'feminine'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct feminine dative form after einer.',
      templateParts: ['Ich helfe einer ', '.'],
      slots: [{ id: 'slot-1', correctWord: 'Bekannten' }],
      wordBank: ['Bekannten', 'Bekannte', 'Bekannter', 'Verwandten'],
      explanation: 'helfen takes the dative; feminine dative singular after einer: -en.',
    },
    {
      id: 'ch70-ex-45',
      chapterNumber: 70,
      order: 45,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'plural', 'nominative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct plural nominative form.',
      templateParts: ['Die ', ' verstehen sich gut.'],
      slots: [{ id: 'slot-1', correctWord: 'Jugendlichen' }],
      wordBank: ['Jugendlichen', 'Jugendliche', 'Jugendlicher', 'Erwachsenen'],
      explanation: 'Plural after die takes -en in every case: die Jugendlichen.',
    },
    {
      id: 'ch70-ex-46',
      chapterNumber: 70,
      order: 46,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'plural', 'accusative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct plural accusative form.',
      templateParts: ['Wir sehen die ', ' im Park.'],
      slots: [{ id: 'slot-1', correctWord: 'Jugendlichen' }],
      wordBank: ['Jugendlichen', 'Jugendliche', 'Jugendlicher', 'Kranken'],
      explanation: 'Plural accusative after die takes -en: die Jugendlichen.',
    },
    {
      id: 'ch70-ex-47',
      chapterNumber: 70,
      order: 47,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'dative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct plural dative form.',
      templateParts: ['Die Stadt bietet den ', ' ein Freizeitzentrum.'],
      slots: [{ id: 'slot-1', correctWord: 'Jugendlichen' }],
      wordBank: ['Jugendlichen', 'Jugendliche', 'Jugendlicher', 'Arbeitslosen'],
      explanation: 'Plural dative after den takes -en: den Jugendlichen.',
    },
    {
      id: 'ch70-ex-48',
      chapterNumber: 70,
      order: 48,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'genitive'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence with the correct plural genitive form.',
      templateParts: ['Die Probleme der ', ' sind vielfältig.'],
      slots: [{ id: 'slot-1', correctWord: 'Jugendlichen' }],
      wordBank: ['Jugendlichen', 'Jugendliche', 'Jugendlicher', 'Reisenden'],
      explanation: 'Plural genitive after der takes -en: der Jugendlichen.',
    },
    {
      id: 'ch70-ex-49',
      chapterNumber: 70,
      order: 49,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'bare-plural', 'no-article'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the general statement with no article.',
      templateParts: ['', ' brauchen oft mehr Freiheit.'],
      slots: [{ id: 'slot-1', correctWord: 'Jugendliche' }],
      wordBank: ['Jugendliche', 'Jugendlichen', 'Jugendlicher', 'Erwachsene'],
      explanation:
        'With no article, the bare plural nominative takes the strong ending -e: Jugendliche brauchen oft mehr Freiheit.',
    },
    {
      id: 'ch70-ex-50',
      chapterNumber: 70,
      order: 50,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'bare-plural', 'no-article', 'dative'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the general statement with no article.',
      templateParts: ['Der Staat hilft ', ' finanziell.'],
      slots: [{ id: 'slot-1', correctWord: 'Arbeitslosen' }],
      wordBank: ['Arbeitslosen', 'Arbeitslose', 'Arbeitsloser', 'Kranken'],
      explanation:
        'With no article, the bare plural dative takes the strong ending -en: Arbeitslosen.',
    },
    {
      id: 'ch70-ex-51',
      chapterNumber: 70,
      order: 51,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'predicate-nominative', 'no-article'],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence stating his job with no article.',
      templateParts: ['Er ist ', ' bei dieser Firma.'],
      slots: [{ id: 'slot-1', correctWord: 'Angestellter' }],
      wordBank: ['Angestellter', 'Angestellte', 'Angestellten', 'Reisender'],
      explanation:
        'A man stating his role with sein and no article uses the strong masculine ending -er: Angestellter.',
    },
    {
      id: 'ch70-ex-52',
      chapterNumber: 70,
      order: 52,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: [
        'substantivized-adjectives',
        'predicate-nominative',
        'no-article',
        'feminine',
      ],
      instruction: 'Drag the correct form into the slot.',
      prompt: 'Complete the sentence stating her job with no article.',
      templateParts: ['Sie wird ', ' bei der neuen Firma.'],
      slots: [{ id: 'slot-1', correctWord: 'Angestellte' }],
      wordBank: ['Angestellte', 'Angestellter', 'Angestellten', 'Bekannte'],
      explanation:
        'A woman stating her role with werden and no article uses the ending -e: Angestellte.',
    },
    {
      id: 'ch70-ex-53',
      chapterNumber: 70,
      order: 53,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'nominative'],
      instruction:
        'Write the correctly capitalized and declined form. Capitalisation is checked.',
      prompt: 'der + verwandt (person, masculine, nominative)',
      acceptedAnswers: ['der Verwandte'],
      answerMode: 'normalized',
      placeholder: 'der Verwandte',
      maxLength: 20,
      explanation:
        'After der, the masculine nominative singular ending is -e: der Verwandte.',
    },
    {
      id: 'ch70-ex-54',
      chapterNumber: 70,
      order: 54,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'accusative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'den + fremd (masculine, accusative)',
      acceptedAnswers: ['den Fremden'],
      answerMode: 'normalized',
      placeholder: 'den Fremden',
      maxLength: 20,
      explanation: 'Masculine accusative singular after den takes -en: den Fremden.',
    },
    {
      id: 'ch70-ex-55',
      chapterNumber: 70,
      order: 55,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'dem + krank (masculine, dative)',
      acceptedAnswers: ['dem Kranken'],
      answerMode: 'normalized',
      placeholder: 'dem Kranken',
      maxLength: 20,
      explanation: 'Masculine dative singular after dem takes -en: dem Kranken.',
    },
    {
      id: 'ch70-ex-56',
      chapterNumber: 70,
      order: 56,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'genitive'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'des + reisend (masculine, genitive)',
      acceptedAnswers: ['des Reisenden'],
      answerMode: 'normalized',
      placeholder: 'des Reisenden',
      maxLength: 20,
      explanation: 'Masculine genitive singular after des takes -en: des Reisenden.',
    },
    {
      id: 'ch70-ex-57',
      chapterNumber: 70,
      order: 57,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'nominative', 'feminine'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'die + jugendlich (feminine, nominative)',
      acceptedAnswers: ['die Jugendliche'],
      answerMode: 'normalized',
      placeholder: 'die Jugendliche',
      maxLength: 20,
      explanation: 'Feminine nominative singular after die takes -e: die Jugendliche.',
    },
    {
      id: 'ch70-ex-58',
      chapterNumber: 70,
      order: 58,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative', 'feminine'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'der + jugendlich (feminine, dative)',
      acceptedAnswers: ['der Jugendlichen'],
      answerMode: 'normalized',
      placeholder: 'der Jugendlichen',
      maxLength: 20,
      explanation: 'Feminine dative singular after der takes -en: der Jugendlichen.',
    },
    {
      id: 'ch70-ex-59',
      chapterNumber: 70,
      order: 59,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'nominative'],
      instruction:
        'Write the correctly declined form (masculine, no der-word). Capitalisation is checked.',
      prompt: 'ein + verwandt (masculine, nominative)',
      acceptedAnswers: ['ein Verwandter'],
      answerMode: 'normalized',
      placeholder: 'ein Verwandter',
      maxLength: 20,
      explanation:
        'After ein, the masculine nominative singular needs the strong ending -er: ein Verwandter.',
    },
    {
      id: 'ch70-ex-60',
      chapterNumber: 70,
      order: 60,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'feminine', 'nominative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'eine + fremd (feminine, nominative)',
      acceptedAnswers: ['eine Fremde'],
      answerMode: 'normalized',
      placeholder: 'eine Fremde',
      maxLength: 20,
      explanation:
        'The feminine nominative singular ending after eine is -e: eine Fremde.',
    },
    {
      id: 'ch70-ex-61',
      chapterNumber: 70,
      order: 61,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'accusative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'einen + krank (masculine, accusative)',
      acceptedAnswers: ['einen Kranken'],
      answerMode: 'normalized',
      placeholder: 'einen Kranken',
      maxLength: 20,
      explanation:
        'After einen, the masculine accusative singular ending is -en: einen Kranken.',
    },
    {
      id: 'ch70-ex-62',
      chapterNumber: 70,
      order: 62,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'dative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'einem + reisend (masculine, dative)',
      acceptedAnswers: ['einem Reisenden'],
      answerMode: 'normalized',
      placeholder: 'einem Reisenden',
      maxLength: 20,
      explanation:
        'After einem, the masculine dative singular ending is -en: einem Reisenden.',
    },
    {
      id: 'ch70-ex-63',
      chapterNumber: 70,
      order: 63,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'accusative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'die + erwachsen (plural, accusative)',
      acceptedAnswers: ['die Erwachsenen'],
      answerMode: 'normalized',
      placeholder: 'die Erwachsenen',
      maxLength: 20,
      explanation: 'Plural accusative after die takes -en: die Erwachsenen.',
    },
    {
      id: 'ch70-ex-64',
      chapterNumber: 70,
      order: 64,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'dative'],
      instruction: 'Write the correctly declined form. Capitalisation is checked.',
      prompt: 'den + verwandt (plural, dative)',
      acceptedAnswers: ['den Verwandten'],
      answerMode: 'normalized',
      placeholder: 'den Verwandten',
      maxLength: 20,
      explanation: 'Plural dative after den takes -en: den Verwandten.',
    },
    {
      id: 'ch70-ex-65',
      chapterNumber: 70,
      order: 65,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'predicate-nominative', 'no-article'],
      instruction:
        'Complete the sentence with the correct form (masculine, no article). Capitalisation is checked.',
      prompt: 'Ich bin ___ (angestellt, masculine, predicate, no article).',
      acceptedAnswers: ['Angestellter'],
      answerMode: 'normalized',
      placeholder: 'Angestellter',
      maxLength: 15,
      explanation:
        'A man stating his role with sein and no article uses the strong ending -er: Angestellter.',
    },
    {
      id: 'ch70-ex-66',
      chapterNumber: 70,
      order: 66,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'bare-plural', 'no-article'],
      instruction:
        'Complete the sentence with the correct form (plural, no article). Capitalisation is checked.',
      prompt: 'Wir sind ___ (verwandt, plural, predicate, no article).',
      acceptedAnswers: ['Verwandte'],
      answerMode: 'normalized',
      placeholder: 'Verwandte',
      maxLength: 15,
      explanation:
        'A plural predicate with no article uses the strong ending -e: Wir sind Verwandte.',
    },
    {
      id: 'ch70-ex-67',
      chapterNumber: 70,
      order: 67,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'conversion', 'nominative'],
      instruction:
        'Rewrite the sentence using a substantivized adjective instead of the adjective + noun phrase. Capitalisation and punctuation are checked.',
      prompt: 'Der kranke Mann liegt im Bett. → substantivized',
      acceptedAnswers: ['Der Kranke liegt im Bett.', 'Der Kranke liegt im Bett'],
      answerMode: 'normalized',
      placeholder: 'Der Kranke liegt im Bett.',
      maxLength: 35,
      explanation:
        'Dropping Mann and capitalizing krank keeps the same nominative ending -e: Der Kranke liegt im Bett.',
    },
    {
      id: 'ch70-ex-68',
      chapterNumber: 70,
      order: 68,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'conversion', 'nominative', 'feminine'],
      instruction:
        'Rewrite the sentence using a substantivized adjective instead of the adjective + noun phrase. Capitalisation and punctuation are checked.',
      prompt: 'Die fremde Frau kam näher. → substantivized',
      acceptedAnswers: ['Die Fremde kam näher.', 'Die Fremde kam näher'],
      answerMode: 'normalized',
      placeholder: 'Die Fremde kam näher.',
      maxLength: 35,
      explanation:
        'Dropping Frau and capitalizing fremde keeps the feminine nominative ending -e: Die Fremde kam näher.',
    },
    {
      id: 'ch70-ex-69',
      chapterNumber: 70,
      order: 69,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'stacked-adjectives', 'capitalization'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Der', 'Deutsche', 'Mann', 'wohnt', 'hier.'],
      errorTokenIndex: 1,
      correction: 'deutsche',
      explanation:
        'Do not combine both patterns: either keep deutsche lowercase before the real noun Mann, or drop Mann and capitalize Deutsche alone.',
    },
    {
      id: 'ch70-ex-70',
      chapterNumber: 70,
      order: 70,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Ich', 'spreche', 'mit', 'der', 'Deutsche.'],
      errorTokenIndex: 4,
      correction: 'Deutschen.',
      explanation:
        'mit takes the dative; the feminine dative singular ending is -en, not the nominative/accusative -e.',
    },
    {
      id: 'ch70-ex-71',
      chapterNumber: 70,
      order: 71,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'nominative'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Der', 'Deutscher', 'kommt', 'aus', 'Berlin.'],
      errorTokenIndex: 1,
      correction: 'Deutsche',
      explanation:
        'After a der-word, the nominative ending is always -e, not -er; -er only appears after ein or with no article.',
    },
    {
      id: 'ch70-ex-72',
      chapterNumber: 70,
      order: 72,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'nominative'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Ein', 'Deutsche', 'steht', 'vor', 'der', 'Tür.'],
      errorTokenIndex: 1,
      correction: 'Deutscher',
      explanation:
        'After ein, the masculine nominative singular needs the strong ending -er, because ein alone does not show gender.',
    },
    {
      id: 'ch70-ex-73',
      chapterNumber: 70,
      order: 73,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'plural', 'nominative'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Die', 'Erwachsene', 'sind', 'hier', 'verantwortlich.'],
      errorTokenIndex: 1,
      correction: 'Erwachsenen',
      explanation:
        'After the plural article die, the ending is always -en, not the bare strong -e used only when there is no article.',
    },
    {
      id: 'ch70-ex-74',
      chapterNumber: 70,
      order: 74,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'dative', 'verb-case'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Ich', 'helfe', 'die', 'Kranken.'],
      errorTokenIndex: 2,
      correction: 'den',
      explanation:
        'helfen takes the dative, not the accusative; it should be den Kranken.',
    },
    {
      id: 'ch70-ex-75',
      chapterNumber: 70,
      order: 75,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'accusative'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Wir', 'kennen', 'den', 'Bekannte.'],
      errorTokenIndex: 3,
      correction: 'Bekannten.',
      explanation:
        'Masculine accusative singular after den takes -en, not -e: den Bekannten.',
    },
    {
      id: 'ch70-ex-76',
      chapterNumber: 70,
      order: 76,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'predicate-nominative'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Er', 'ist', 'ein', 'Angestellte', 'bei', 'der', 'Firma.'],
      errorTokenIndex: 3,
      correction: 'Angestellter',
      explanation:
        'After ein, the masculine nominative singular needs the strong ending -er: ein Angestellter.',
    },
    {
      id: 'ch70-ex-77',
      chapterNumber: 70,
      order: 77,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'genitive'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Das', 'Auto', 'des', 'Bekannte', 'steht', 'hier.'],
      errorTokenIndex: 3,
      correction: 'Bekannten',
      explanation:
        'Masculine genitive singular after des takes -en, not -e: des Bekannten.',
    },
    {
      id: 'ch70-ex-78',
      chapterNumber: 70,
      order: 78,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'plural', 'nominative'],
      instruction: 'Find the token with the error.',
      prompt: 'One word in this sentence is wrong. Find it.',
      tokens: ['Die', 'Jugendliche', 'reisen', 'gern.'],
      errorTokenIndex: 1,
      correction: 'Jugendlichen',
      explanation:
        'After the plural article die, the ending is always -en: Die Jugendlichen reisen gern.',
    },
    {
      id: 'ch70-ex-79',
      chapterNumber: 70,
      order: 79,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'ein-words', 'nominative'],
      instruction: 'Match the der-word form to its ein-word counterpart.',
      prompt:
        'Match each definite masculine nominative form to the matching indefinite form.',
      pairs: [
        { id: 'p1', left: 'der Deutsche', right: 'ein Deutscher' },
        { id: 'p2', left: 'der Kranke', right: 'ein Kranker' },
        { id: 'p3', left: 'der Reisende', right: 'ein Reisender' },
        { id: 'p4', left: 'der Fremde', right: 'ein Fremder' },
      ],
      explanation:
        'After der the masculine nominative ending is -e; after ein it is the strong ending -er, since ein does not mark gender on its own.',
    },
    {
      id: 'ch70-ex-80',
      chapterNumber: 70,
      order: 80,
      type: 'matching',
      level: 'controlled',
      grammarFocus: [
        'substantivized-adjectives',
        'der-words',
        'ein-words',
        'nominative',
        'feminine',
      ],
      instruction: 'Match the der-word form to its ein-word counterpart.',
      prompt:
        'Match each definite feminine nominative form to the matching indefinite form.',
      pairs: [
        { id: 'p1', left: 'die Bekannte', right: 'eine Bekannte' },
        { id: 'p2', left: 'die Verwandte', right: 'eine Verwandte' },
        { id: 'p3', left: 'die Angestellte', right: 'eine Angestellte' },
        { id: 'p4', left: 'die Fremde', right: 'eine Fremde' },
      ],
      explanation:
        'The feminine nominative singular ending is -e both after die and after eine.',
    },
    {
      id: 'ch70-ex-81',
      chapterNumber: 70,
      order: 81,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'singular-plural', 'nominative'],
      instruction: 'Match each singular form to its plural form.',
      prompt: 'Match each singular nominative form to the corresponding plural.',
      pairs: [
        { id: 'p1', left: 'die Deutsche', right: 'die Deutschen' },
        { id: 'p2', left: 'der Kranke', right: 'die Kranken' },
        { id: 'p3', left: 'die Reisende', right: 'die Reisenden' },
        { id: 'p4', left: 'der Jugendliche', right: 'die Jugendlichen' },
      ],
      explanation: 'Whatever the singular gender, the plural always takes -en after die.',
    },
    {
      id: 'ch70-ex-82',
      chapterNumber: 70,
      order: 82,
      type: 'matching',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'ein-words', 'dative'],
      instruction: 'Match the der-word form to its ein-word counterpart.',
      prompt:
        'Match each definite masculine dative form to the matching indefinite form.',
      pairs: [
        { id: 'p1', left: 'dem Deutschen', right: 'einem Deutschen' },
        { id: 'p2', left: 'dem Kranken', right: 'einem Kranken' },
        { id: 'p3', left: 'dem Reisenden', right: 'einem Reisenden' },
        { id: 'p4', left: 'dem Bekannten', right: 'einem Bekannten' },
      ],
      explanation:
        'Outside the masculine nominative singular, ein-words take exactly the same endings as der-words: -en in the dative.',
    },
    {
      id: 'ch70-ex-83',
      chapterNumber: 70,
      order: 83,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'predicate-nominative', 'no-article'],
      instruction: 'Match each masculine predicate form to its feminine counterpart.',
      prompt:
        'Match each masculine no-article predicate form to the matching feminine form.',
      pairs: [
        { id: 'p1', left: 'Deutscher', right: 'Deutsche' },
        { id: 'p2', left: 'Angestellter', right: 'Angestellte' },
        { id: 'p3', left: 'Reisender', right: 'Reisende' },
        { id: 'p4', left: 'Verwandter', right: 'Verwandte' },
      ],
      explanation:
        'With no article, the masculine predicate ending is -er and the feminine is -e.',
    },
    {
      id: 'ch70-ex-84',
      chapterNumber: 70,
      order: 84,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['substantivized-adjectives', 'vocabulary', 'translation'],
      instruction: 'Match each German form to its English meaning.',
      prompt: 'Match each substantivized adjective to its English translation.',
      pairs: [
        { id: 'p1', left: 'der Kranke', right: 'the sick person' },
        { id: 'p2', left: 'der Reisende', right: 'the traveler' },
        { id: 'p3', left: 'der Jugendliche', right: 'the teenager' },
        { id: 'p4', left: 'der Arbeitslose', right: 'the unemployed person' },
      ],
      explanation:
        'Each substantivized adjective describes a person who has that quality.',
    },
    {
      id: 'ch70-ex-85',
      chapterNumber: 70,
      order: 85,
      type: 'matching',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'ein-words', 'genitive'],
      instruction: 'Match the der-word form to its ein-word counterpart.',
      prompt:
        'Match each definite masculine genitive form to the matching indefinite form.',
      pairs: [
        { id: 'p1', left: 'des Deutschen', right: 'eines Deutschen' },
        { id: 'p2', left: 'des Kranken', right: 'eines Kranken' },
        { id: 'p3', left: 'des Bekannten', right: 'eines Bekannten' },
        { id: 'p4', left: 'des Reisenden', right: 'eines Reisenden' },
      ],
      explanation: 'The genitive masculine ending is -en both after des and after eines.',
    },
    {
      id: 'ch70-ex-86',
      chapterNumber: 70,
      order: 86,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'base-adjective'],
      instruction: 'Match each plain adjective to the corresponding substantivized noun.',
      prompt: 'Match each base adjective to its nominalized masculine nominative form.',
      pairs: [
        { id: 'p1', left: 'krank', right: 'der Kranke' },
        { id: 'p2', left: 'reisend', right: 'der Reisende' },
        { id: 'p3', left: 'jugendlich', right: 'der Jugendliche' },
        { id: 'p4', left: 'arbeitslos', right: 'der Arbeitslose' },
      ],
      explanation:
        'Every substantivized adjective is grammatically still the plain adjective on the left, capitalized and standing alone.',
    },
    {
      id: 'ch70-ex-87',
      chapterNumber: 70,
      order: 87,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'nominative'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Order the words to form a correct sentence.',
      segments: [
        { id: 's1', text: 'Der' },
        { id: 's2', text: 'Kranke' },
        { id: 's3', text: 'braucht' },
        { id: 's4', text: 'Ruhe.' },
      ],
      explanation:
        'Der Kranke braucht Ruhe. Masculine nominative singular after der: -e.',
    },
    {
      id: 'ch70-ex-88',
      chapterNumber: 70,
      order: 88,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'der-words', 'dative'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Order the words to form a correct sentence.',
      segments: [
        { id: 's1', text: 'Ich' },
        { id: 's2', text: 'helfe' },
        { id: 's3', text: 'dem' },
        { id: 's4', text: 'Reisenden' },
        { id: 's5', text: 'gern.' },
      ],
      explanation:
        'Ich helfe dem Reisenden gern. helfen takes the dative; masculine dative ending after dem is -en.',
    },
    {
      id: 'ch70-ex-89',
      chapterNumber: 70,
      order: 89,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'plural'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Order the words to form a correct sentence.',
      segments: [
        { id: 's1', text: 'Die' },
        { id: 's2', text: 'Jugendlichen' },
        { id: 's3', text: 'spielen' },
        { id: 's4', text: 'im' },
        { id: 's5', text: 'Park.' },
      ],
      explanation: 'Die Jugendlichen spielen im Park. Plural after die takes -en.',
    },
    {
      id: 'ch70-ex-90',
      chapterNumber: 70,
      order: 90,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'nominative'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Order the words to form a correct sentence.',
      segments: [
        { id: 's1', text: 'Ein' },
        { id: 's2', text: 'Fremder' },
        { id: 's3', text: 'fragte' },
        { id: 's4', text: 'mich' },
        { id: 's5', text: 'nach' },
        { id: 's6', text: 'dem' },
        { id: 's7', text: 'Weg.' },
      ],
      explanation:
        'Ein Fremder fragte mich nach dem Weg. After ein, masculine nominative singular needs the strong ending -er.',
    },
    {
      id: 'ch70-ex-91',
      chapterNumber: 70,
      order: 91,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['substantivized-adjectives', 'predicate-nominative', 'no-article'],
      instruction: 'Choose the correct sentence.',
      prompt: "Which sentence correctly states a man's nationality with no article?",
      options: [
        { id: 'a', text: 'Ich bin Deutscher.' },
        { id: 'b', text: 'Ich bin Deutsche.' },
        { id: 'c', text: 'Ich bin der Deutsche.' },
        { id: 'd', text: 'Ich bin Deutschen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'A man stating his nationality with sein and no article uses the strong masculine ending -er: Ich bin Deutscher.',
    },
    {
      id: 'ch70-ex-92',
      chapterNumber: 70,
      order: 92,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'dative'],
      instruction: 'Choose the correct plural dative form.',
      prompt: 'Der Staat hilft ___ finanziell.',
      options: [
        { id: 'a', text: 'den Obdachlosen' },
        { id: 'b', text: 'die Obdachlosen' },
        { id: 'c', text: 'der Obdachlosen' },
        { id: 'd', text: 'den Obdachlose' },
      ],
      correctOptionId: 'a',
      explanation:
        'helfen takes the dative; the plural dative article is den, and the ending is -en: den Obdachlosen.',
    },
    {
      id: 'ch70-ex-93',
      chapterNumber: 70,
      order: 93,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['substantivized-adjectives', 'plural', 'genitive'],
      instruction: 'Choose the correct genitive plural form.',
      prompt: 'Die Sorgen ___ interessieren die Politik.',
      options: [
        { id: 'a', text: 'der Arbeitslosen' },
        { id: 'b', text: 'die Arbeitslosen' },
        { id: 'c', text: 'den Arbeitslosen' },
        { id: 'd', text: 'der Arbeitslose' },
      ],
      correctOptionId: 'a',
      explanation: 'Genitive plural after der takes -en: der Arbeitslosen.',
    },
    {
      id: 'ch70-ex-94',
      chapterNumber: 70,
      order: 94,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'translation'],
      instruction: 'Choose the best translation.',
      prompt: 'Choose the best translation of: "A stranger helped me."',
      options: [
        { id: 'a', text: 'Ein Fremder half mir.' },
        { id: 'b', text: 'Eine Fremde half mir.' },
        { id: 'c', text: 'Der Fremde half mir.' },
        { id: 'd', text: 'Einen Fremden half mir.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Ein Fremder is the masculine nominative subject form after ein: the strong ending -er, since ein does not mark gender.',
    },
    {
      id: 'ch70-ex-95',
      chapterNumber: 70,
      order: 95,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['substantivized-adjectives', 'noun-vs-adjective-declension'],
      instruction:
        'Choose the word that is a genuine noun, not a substantivized adjective.',
      prompt: 'Which of these words does NOT decline like an attributive adjective?',
      options: [
        { id: 'a', text: 'der Lehrer' },
        { id: 'b', text: 'der Kranke' },
        { id: 'c', text: 'der Reisende' },
        { id: 'd', text: 'der Deutsche' },
      ],
      correctOptionId: 'a',
      explanation:
        'der Lehrer is an ordinary noun and barely changes across cases; der Kranke, der Reisende, and der Deutsche are all substantivized adjectives that decline like adjectives.',
    },
    {
      id: 'ch70-ex-96',
      chapterNumber: 70,
      order: 96,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['substantivized-adjectives', 'ein-words', 'feminine', 'nominative'],
      instruction: 'Choose the correct feminine form after eine.',
      prompt: 'Sie ist ___ von mir.',
      options: [
        { id: 'a', text: 'eine Verwandte' },
        { id: 'b', text: 'eine Verwandter' },
        { id: 'c', text: 'eine Verwandten' },
        { id: 'd', text: 'die Verwandte' },
      ],
      correctOptionId: 'a',
      explanation:
        'The feminine nominative singular ending after eine is -e: eine Verwandte.',
    },
  ],
};
