import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter013: ChapterDefinition = {
  id: 'chapter-013',
  number: 13,
  slug: 'sentences-with-two-fixed-verb-positions',
  title: 'Sentences with Two Fixed Verb Positions',
  germanTitle: 'Die Satzklammer',
  level: 'A1',
  section: 'sentences-and-questions',
  objective:
    'Recognise the German verb bracket (Satzklammer) — a finite verb part in position 2 and a non-finite or separated part at the very end of the clause — and build correct sentences with modal verbs, separable verbs, and a first preview of the perfect tense.',
  prerequisites: [5, 8, 12],
  estimatedMinutes: 25,
  tags: ['word-order', 'satzklammer', 'verb-bracket', 'modal-verbs', 'separable-verbs'],
  explanation: {
    introduction: [
      'Many German main clauses do not have just one verb — they have two verb-related parts that occupy two fixed places in the sentence. The first, finite part is conjugated for the subject and stands in position 2. The second part is non-finite (or a piece that has separated from the verb) and is sent all the way to the very end of the clause.',
      'This chapter shows you this pattern in three familiar situations — a modal verb with an infinitive, a separable verb with its prefix, and a first look at the perfect tense — and how they all share the same underlying shape: one fixed piece in position 2, one fixed piece at the end, and everything else packed in between.',
    ],
    rules: [
      {
        id: 'ch13-rule-01',
        heading: 'The verb bracket (Satzklammer): two fixed positions',
        paragraphs: [
          'Many German main clauses have two verb-related parts that occupy two fixed places in the sentence. The first, finite part is conjugated for the subject and stands in position 2. The second part is non-finite (or a separated piece of the verb) and is sent all the way to the very end of the clause.',
          'Together these two fixed points form a "verb bracket" (Satzklammer): picture them as two clamps holding the sentence together, with everything else — objects, time expressions, negation words like nicht — packed into the space between them, called the Mittelfeld (middle field).',
        ],
        notes: [
          'Position 2 always holds exactly one finite (conjugated) verb form. The end of the clause holds the second part, whatever kind it is.',
          'Not every sentence has a bracket — see the note on one-part predicates below.',
        ],
      },
      {
        id: 'ch13-rule-02',
        heading: 'Modal verb + infinitive',
        paragraphs: [
          'When a modal verb (können, müssen, dürfen, wollen, sollen, mögen) is used, the modal is conjugated and takes position 2. The main verb is not conjugated at all: it stays in its infinitive form and moves to the very end of the clause.',
          'Ich kann heute nicht kommen. Wir müssen jetzt gehen. Du musst das Formular ausfüllen. Notice that nicht, heute, jetzt and das Formular all sit in the Mittelfeld, between the two fixed verb parts.',
        ],
      },
      {
        id: 'ch13-rule-03',
        heading: 'Separable verbs: prefix at the end',
        paragraphs: [
          'A separable verb (like anrufen, aufräumen, einkaufen, ausfüllen) is one word in the infinitive, but in a normal main clause it splits: the base verb is conjugated and stays in position 2, and the separable prefix travels alone to the very end of the clause.',
          'Ich rufe dich morgen an. Er räumt sein Zimmer auf. Wir kaufen im Supermarkt ein. This is exactly the same bracket pattern as with modal verbs — one fixed piece in position 2, one fixed piece at the end — except here both pieces come from the same verb.',
          'If a separable verb appears together with a modal verb, it is not split at all: it stays whole, in the infinitive, and that whole infinitive goes to the end. Du musst das Formular ausfüllen. Ich darf heute nicht fernsehen.',
        ],
      },
      {
        id: 'ch13-rule-04',
        heading: 'A preview: the perfect tense uses the same bracket',
        paragraphs: [
          'The perfect tense (Perfekt), which you will study in full detail in a later chapter, follows the very same bracket pattern. The helper verb haben or sein is conjugated and takes position 2; the past participle (Partizip II, such as gelesen, gemacht, gefahren) goes to the very end of the clause.',
          'Ich habe das Buch gelesen. Sie ist gestern nach Berlin gefahren. For now, just notice the shape: finite helper in position 2, non-finite participle at the end — the same bracket you already know from modal verbs and separable verbs.',
        ],
      },
      {
        id: 'ch13-rule-05',
        heading: 'One-part vs. two-part predicates',
        paragraphs: [
          'Not every clause has a bracket. When the sentence contains only a single, ordinary verb — no modal, no separable verb, no perfect tense — that one verb is conjugated and stands in position 2, and there is nothing fixed at the end. This is called a one-part predicate.',
          'Compare: Ich esse gern Pizza. (one-part — only esse, nothing at the end) with Ich möchte gern Pizza essen. (two-part — möchte in position 2, essen closing the bracket at the end).',
        ],
        notes: [
          'A useful check: if you can point to a word at the very end of the clause that belongs to the verb (an infinitive, a prefix, or a participle), the clause has a bracket. If the last word is an object, a time expression or similar, the predicate is one-part.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch13-table-01',
        title: 'Four predicate patterns',
        columns: ['Pattern', 'Position 2 (finite)', 'End of the clause (non-finite)', 'Example'],
        rows: [
          [
            'Modal + infinitive',
            'modal verb (kann, muss, darf …)',
            'infinitive',
            'Ich kann heute nicht kommen.',
          ],
          ['Separable verb', 'conjugated stem', 'separable prefix', 'Ich rufe dich morgen an.'],
          [
            'Perfect tense (preview)',
            'haben or sein',
            'past participle',
            'Ich habe das Buch gelesen.',
          ],
          [
            'One-part predicate',
            'the only finite verb',
            '— (nothing fixed at the end)',
            'Ich esse gern Pizza.',
          ],
        ],
        note: 'In the first three patterns, two fixed verb-related parts form a bracket; in the fourth pattern there is only one verb part and no bracket.',
      },
      {
        id: 'ch13-table-02',
        title: 'Anatomy of a two-part predicate',
        columns: ['Position 1', 'Position 2 (finite)', 'Mittelfeld (middle field)', 'End (non-finite)'],
        rows: [
          ['Ich', 'kann', 'heute nicht', 'kommen.'],
          ['Ich', 'rufe', 'dich morgen', 'an.'],
          ['Ich', 'habe', 'das Buch', 'gelesen.'],
        ],
        note: 'Position 1 and position 2 never move relative to each other in a statement; the Mittelfeld can hold many different words, but the final, non-finite part always closes the clause.',
      },
    ],
    examples: [
      {
        german: 'Ich kann heute nicht kommen.',
        english: "I can't come today.",
        highlight: ['kann', 'kommen'],
        explanation: 'The modal kann is in position 2, and the infinitive kommen closes the bracket at the end.',
      },
      {
        german: 'Wir müssen jetzt gehen.',
        english: 'We have to go now.',
        highlight: ['müssen', 'gehen'],
      },
      {
        german: 'Du musst das Formular ausfüllen.',
        english: 'You have to fill out the form.',
        highlight: ['musst', 'ausfüllen'],
        explanation: 'The separable verb ausfüllen stays whole, as one infinitive, at the end after a modal.',
      },
      {
        german: 'Ich rufe dich morgen an.',
        english: 'I will call you tomorrow.',
        highlight: ['rufe', 'an'],
        explanation: 'The separable prefix an moves to the end; the stem rufe stays in position 2.',
      },
      {
        german: 'Er räumt sein Zimmer auf.',
        english: 'He tidies up his room.',
        highlight: ['räumt', 'auf'],
      },
      {
        german: 'Wir kaufen im Supermarkt ein.',
        english: 'We shop at the supermarket.',
        highlight: ['kaufen', 'ein'],
      },
      {
        german: 'Ich habe das Buch gelesen.',
        english: 'I have read the book.',
        highlight: ['habe', 'gelesen'],
        explanation:
          'A preview of the perfect tense: habe in position 2, the participle gelesen at the end — the same bracket pattern, covered fully in a later chapter.',
      },
      {
        german: 'Sie ist gestern nach Berlin gefahren.',
        english: 'She traveled to Berlin yesterday.',
        highlight: ['ist', 'gefahren'],
      },
      {
        german: 'Ich darf heute nicht fernsehen.',
        english: 'I am not allowed to watch TV today.',
        highlight: ['darf', 'fernsehen'],
        explanation: 'Modal and separable verb combine: fernsehen stays one word at the very end.',
      },
      {
        german: 'Ich esse gern Pizza.',
        english: 'I like eating pizza.',
        highlight: ['esse'],
        explanation: 'Only one verb part (esse) — a one-part predicate with nothing fixed at the end.',
      },
      {
        german: 'Meine Mutter kocht heute Abend.',
        english: 'My mother is cooking tonight.',
        highlight: ['kocht'],
        explanation: 'A single finite verb only; no second bracket position at the end.',
      },
      {
        german: 'Kannst du mir bitte helfen?',
        english: 'Can you help me, please?',
        highlight: ['Kannst', 'helfen'],
        explanation:
          'Even in a yes/no question the modal moves to the very front, but the infinitive helfen still closes the bracket at the end.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich kann kommen heute nicht.',
        correct: 'Ich kann heute nicht kommen.',
        explanation:
          'The infinitive must stand at the very end of the clause, after nicht and every other Mittelfeld element — it cannot appear right after the modal.',
      },
      {
        incorrect: 'Ich rufe an dich morgen.',
        correct: 'Ich rufe dich morgen an.',
        explanation:
          'The separable prefix an belongs at the very end of the clause, not directly after the conjugated stem.',
      },
      {
        incorrect: 'Ich habe gelesen das Buch.',
        correct: 'Ich habe das Buch gelesen.',
        explanation:
          'The past participle gelesen closes the bracket at the end; the object das Buch belongs in the Mittelfeld, before it.',
      },
      {
        incorrect: 'Ich muss aufstehen früh.',
        correct: 'Ich muss früh aufstehen.',
        explanation:
          'The non-finite element — here the whole separable verb aufstehen — must be the very last word of the clause; früh belongs in the middle.',
      },
    ],
    remember: [
      'A verb bracket (Satzklammer) has two fixed positions: the finite verb in position 2 and a non-finite or separated part at the very end.',
      'Modal + infinitive: the modal is conjugated in position 2, the infinitive stays whole at the end.',
      'Separable verbs: the conjugated stem stays in position 2, the prefix moves to the end — unless a modal is present, in which case the whole separable verb stays together as an infinitive at the end.',
      'Perfect tense preview: haben or sein takes position 2, the past participle closes the bracket at the end — you will study this fully later.',
      'Not every clause has a bracket: a one-part predicate has just one finite verb and nothing fixed at the end.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch13-ex-01',
      chapterNumber: 13,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['verb-bracket', 'satzklammer', 'modal-verbs'],
      instruction: 'Which word is the finite (conjugated) verb in position 2?',
      prompt: 'Ich kann heute nicht kommen.',
      options: [
        { id: 'a', text: 'kann' },
        { id: 'b', text: 'heute' },
        { id: 'c', text: 'nicht' },
        { id: 'd', text: 'kommen' },
      ],
      correctOptionId: 'a',
      explanation:
        'kann is the conjugated modal verb and stands in position 2; kommen is the infinitive at the end of the clause.',
    },
    {
      id: 'ch13-ex-02',
      chapterNumber: 13,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['verb-bracket', 'satzklammer', 'modal-verbs'],
      instruction: 'Which word closes the verb bracket at the very end of the clause?',
      prompt: 'Ich kann heute nicht kommen.',
      options: [
        { id: 'a', text: 'kann' },
        { id: 'b', text: 'heute' },
        { id: 'c', text: 'nicht' },
        { id: 'd', text: 'kommen' },
      ],
      correctOptionId: 'd',
      explanation:
        'The infinitive kommen is the second, non-finite part of the bracket and stands at the very end of the clause.',
    },
    {
      id: 'ch13-ex-03',
      chapterNumber: 13,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['separable-verbs', 'verb-bracket'],
      instruction: 'Which word is the separable prefix at the end of the clause?',
      prompt: 'Ich rufe dich morgen an.',
      options: [
        { id: 'a', text: 'rufe' },
        { id: 'b', text: 'dich' },
        { id: 'c', text: 'morgen' },
        { id: 'd', text: 'an' },
      ],
      correctOptionId: 'd',
      explanation:
        'anrufen splits: the stem rufe stays in position 2, and the prefix an is sent to the very end.',
    },
    {
      id: 'ch13-ex-04',
      chapterNumber: 13,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['perfect-tense-preview', 'verb-bracket'],
      instruction: 'Which word is the finite (conjugated) verb in position 2?',
      prompt: 'Ich habe das Buch gelesen.',
      options: [
        { id: 'a', text: 'habe' },
        { id: 'b', text: 'das' },
        { id: 'c', text: 'Buch' },
        { id: 'd', text: 'gelesen' },
      ],
      correctOptionId: 'a',
      explanation:
        'habe is the conjugated helper verb in position 2; gelesen, the past participle, closes the bracket at the end.',
    },
    {
      id: 'ch13-ex-05',
      chapterNumber: 13,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['modal-verbs', 'word-order'],
      instruction: 'Choose the sentence with the correct verb bracket.',
      prompt: 'ich – können – heute – nicht – kommen',
      options: [
        { id: 'a', text: 'Ich kann heute nicht kommen.' },
        { id: 'b', text: 'Ich kann kommen heute nicht.' },
        { id: 'c', text: 'Ich komme heute nicht kann.' },
        { id: 'd', text: 'Kann ich heute nicht kommen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'kann takes position 2; heute nicht sits in the Mittelfeld; the infinitive kommen closes the bracket at the very end.',
    },
    {
      id: 'ch13-ex-06',
      chapterNumber: 13,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['separable-verbs', 'word-order'],
      instruction: 'Choose the sentence with the correct verb bracket.',
      prompt: 'ich – dich – morgen – anrufen',
      options: [
        { id: 'a', text: 'Ich rufe dich morgen an.' },
        { id: 'b', text: 'Ich anrufe dich morgen.' },
        { id: 'c', text: 'Ich rufe an dich morgen.' },
        { id: 'd', text: 'Ich rufe dich an morgen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'rufe stays in position 2 while the separable prefix an moves all the way to the end of the clause.',
    },
    {
      id: 'ch13-ex-07',
      chapterNumber: 13,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['perfect-tense-preview', 'word-order'],
      instruction: 'Choose the sentence with the correct verb bracket.',
      prompt: 'ich – gestern – einen Kaffee – trinken (habe … getrunken)',
      options: [
        { id: 'a', text: 'Ich habe gestern einen Kaffee getrunken.' },
        { id: 'b', text: 'Ich habe getrunken gestern einen Kaffee.' },
        { id: 'c', text: 'Ich getrunken habe gestern einen Kaffee.' },
        { id: 'd', text: 'Ich habe gestern getrunken einen Kaffee.' },
      ],
      correctOptionId: 'a',
      explanation:
        'habe stands in position 2, and the past participle getrunken closes the bracket at the very end, after the Mittelfeld gestern einen Kaffee.',
    },
    {
      id: 'ch13-ex-08',
      chapterNumber: 13,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['one-part-predicate', 'verb-bracket'],
      instruction: 'Choose the sentence without a verb bracket.',
      prompt: 'Which sentence has only one verb part, with nothing fixed at the end?',
      options: [
        { id: 'a', text: 'Ich esse gern Pizza.' },
        { id: 'b', text: 'Ich kann gern Pizza essen.' },
        { id: 'c', text: 'Ich habe gern Pizza gegessen.' },
        { id: 'd', text: 'Ich möchte gern Pizza essen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Ich esse gern Pizza has just one finite verb (esse) and nothing fixed at the end — a one-part predicate. The other three all have a bracket: modal + infinitive, perfect helper + participle, or möchte + infinitive.',
    },
    {
      id: 'ch13-ex-09',
      chapterNumber: 13,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['separable-verbs', 'mittelfeld'],
      instruction: 'Choose the pair of words that correctly completes the bracket (aufräumen).',
      prompt: 'Wir ___ das Zimmer jeden Samstag ___.',
      options: [
        { id: 'a', text: 'räumen / auf' },
        { id: 'b', text: 'aufräumen / —' },
        { id: 'c', text: 'auf / räumen' },
        { id: 'd', text: 'räumen auf / —' },
      ],
      correctOptionId: 'a',
      explanation:
        'The stem räumen stays in position 2 and the prefix auf closes the bracket at the end: Wir räumen das Zimmer jeden Samstag auf.',
    },
    {
      id: 'ch13-ex-10',
      chapterNumber: 13,
      order: 10,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['modal-verbs', 'separable-verbs', 'verb-bracket'],
      instruction: 'Choose the correct sentence. (fernsehen is separable; with a modal it stays whole.)',
      prompt: 'du – heute – nicht – fernsehen – dürfen',
      options: [
        { id: 'a', text: 'Du darfst heute nicht fernsehen.' },
        { id: 'b', text: 'Du darfst heute nicht siehst fern.' },
        { id: 'c', text: 'Du fernsehen darfst heute nicht.' },
        { id: 'd', text: 'Du darfst heute nicht fern sehen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'With the modal darfst in position 2, the separable verb fernsehen is not split — it stays whole, as one infinitive, at the very end.',
    },
    {
      id: 'ch13-ex-11',
      chapterNumber: 13,
      order: 11,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['perfect-tense-preview', 'word-order'],
      instruction: 'Choose the correct sentence.',
      prompt: 'sie – gestern – nach Berlin – fahren (ist … gefahren)',
      options: [
        { id: 'a', text: 'Sie ist gestern nach Berlin gefahren.' },
        { id: 'b', text: 'Sie ist gefahren gestern nach Berlin.' },
        { id: 'c', text: 'Sie gefahren ist gestern nach Berlin.' },
        { id: 'd', text: 'Sie ist gestern gefahren nach Berlin.' },
      ],
      correctOptionId: 'a',
      explanation:
        'ist takes position 2 and the participle gefahren closes the bracket at the very end, after the Mittelfeld gestern nach Berlin.',
    },
    {
      id: 'ch13-ex-12',
      chapterNumber: 13,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['verb-bracket', 'modal-verbs', 'separable-verbs'],
      instruction: 'Choose the sentence with the correct verb bracket.',
      prompt: 'Which German sentence correctly means "I can call you tomorrow"?',
      options: [
        { id: 'a', text: 'Ich kann dich morgen anrufen.' },
        { id: 'b', text: 'Ich kann dich morgen rufe an.' },
        { id: 'c', text: 'Ich rufe dich morgen ankönnen.' },
        { id: 'd', text: 'Ich kann anrufen dich morgen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'With the modal kann in position 2, the separable verb anrufen stays whole, in the infinitive, at the very end of the clause.',
    },
    {
      id: 'ch13-ex-13',
      chapterNumber: 13,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['verb-bracket', 'modal-verbs'],
      instruction: 'Write only the finite (conjugated) verb that stands in position 2. Capitalisation does not matter here.',
      prompt: 'Wir müssen jetzt gehen.',
      acceptedAnswers: ['müssen'],
      answerMode: 'caseInsensitive',
      placeholder: 'verb',
      maxLength: 15,
      explanation:
        'müssen is the conjugated modal verb and stands in position 2; gehen is the infinitive that closes the bracket at the end.',
    },
    {
      id: 'ch13-ex-14',
      chapterNumber: 13,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['verb-bracket', 'separable-verbs'],
      instruction: 'Write only the word that stands at the very end of the clause. Capitalisation does not matter here.',
      prompt: 'Er räumt sein Zimmer auf.',
      acceptedAnswers: ['auf'],
      answerMode: 'caseInsensitive',
      placeholder: 'word',
      maxLength: 15,
      explanation:
        'räumt stays in position 2; the separable prefix auf is sent to the very end of the clause.',
    },
    {
      id: 'ch13-ex-15',
      chapterNumber: 13,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['modal-verbs', 'verb-bracket'],
      instruction: 'Write only the missing infinitive. Capitalisation does not matter here.',
      prompt: 'Ich kann das Auto nicht ___. (reparieren)',
      acceptedAnswers: ['reparieren'],
      answerMode: 'caseInsensitive',
      placeholder: 'infinitive',
      maxLength: 20,
      explanation:
        'kann is conjugated in position 2, so reparieren stays in its infinitive form and moves to the very end.',
    },
    {
      id: 'ch13-ex-16',
      chapterNumber: 13,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['separable-verbs', 'verb-bracket'],
      instruction: 'Write only the missing separable prefix. Capitalisation does not matter here.',
      prompt: 'Sie macht das Fenster ___. (zumachen)',
      acceptedAnswers: ['zu'],
      answerMode: 'caseInsensitive',
      placeholder: 'prefix',
      maxLength: 10,
      explanation:
        'zumachen splits: macht stays in position 2, and the prefix zu closes the bracket at the end.',
    },
    {
      id: 'ch13-ex-17',
      chapterNumber: 13,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['perfect-tense-preview', 'verb-bracket'],
      instruction: 'Write only the missing past participle. Capitalisation does not matter here.',
      prompt: 'Ich habe einen Kaffee ___. (trinken → getrunken)',
      acceptedAnswers: ['getrunken'],
      answerMode: 'caseInsensitive',
      placeholder: 'participle',
      maxLength: 20,
      explanation:
        'habe stands in position 2; the past participle getrunken closes the bracket at the very end — the same pattern you will study fully in the perfect tense chapter.',
    },
    {
      id: 'ch13-ex-18',
      chapterNumber: 13,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['one-part-predicate', 'verb-bracket'],
      instruction: 'Does this sentence have a verb bracket (two fixed verb positions)? Write ja or nein.',
      prompt: 'Meine Mutter kocht heute Abend.',
      acceptedAnswers: ['nein'],
      answerMode: 'caseInsensitive',
      placeholder: 'ja / nein',
      maxLength: 10,
      explanation:
        'kocht is the only verb, and there is nothing fixed at the end of the clause, so this is a one-part predicate with no bracket.',
    },
    {
      id: 'ch13-ex-19',
      chapterNumber: 13,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['verb-bracket', 'modal-verbs'],
      instruction: 'Does this sentence have a verb bracket (two fixed verb positions)? Write ja or nein.',
      prompt: 'Ich möchte gern Pizza essen.',
      acceptedAnswers: ['ja'],
      answerMode: 'caseInsensitive',
      placeholder: 'ja / nein',
      maxLength: 10,
      explanation:
        'möchte stands in position 2 and the infinitive essen closes the bracket at the end, so this sentence does have a bracket.',
    },
    {
      id: 'ch13-ex-20',
      chapterNumber: 13,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['modal-verbs', 'separable-verbs', 'word-order'],
      instruction: 'Write the complete sentence. Capitalisation and the full stop are checked.',
      prompt: 'ich – dürfen – heute – nicht – fernsehen',
      acceptedAnswers: ['Ich darf heute nicht fernsehen.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'darf takes position 2; the separable verb fernsehen stays whole, as one infinitive, at the very end: Ich darf heute nicht fernsehen.',
    },
    {
      id: 'ch13-ex-21',
      chapterNumber: 13,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['separable-verbs', 'word-order'],
      instruction: 'Write the complete sentence. Capitalisation and the full stop are checked.',
      prompt: 'wir – das Zimmer – jeden Samstag – aufräumen',
      acceptedAnswers: ['Wir räumen das Zimmer jeden Samstag auf.'],
      answerMode: 'normalized',
      placeholder: 'Wir ...',
      maxLength: 70,
      explanation:
        'räumen stays in position 2, and the prefix auf closes the bracket at the very end: Wir räumen das Zimmer jeden Samstag auf.',
    },
    {
      id: 'ch13-ex-22',
      chapterNumber: 13,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['perfect-tense-preview', 'word-order'],
      instruction: 'Write the complete sentence using habe … gesehen. Capitalisation and the full stop are checked.',
      prompt: 'ich – gestern – einen Film – sehen (habe … gesehen)',
      acceptedAnswers: ['Ich habe gestern einen Film gesehen.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe ...',
      maxLength: 70,
      explanation:
        'habe stands in position 2 and the participle gesehen closes the bracket at the very end: Ich habe gestern einen Film gesehen.',
    },
    {
      id: 'ch13-ex-23',
      chapterNumber: 13,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['verb-bracket', 'word-order'],
      instruction: 'Unscramble the words into a correct sentence. Capitalisation and the full stop are checked.',
      prompt: 'kann / ich / morgen / nicht / kommen',
      acceptedAnswers: ['Ich kann morgen nicht kommen.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'kann belongs in position 2 and the infinitive kommen closes the bracket at the very end: Ich kann morgen nicht kommen.',
    },
    {
      id: 'ch13-ex-24',
      chapterNumber: 13,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['verb-bracket', 'error-correction'],
      instruction: 'Correct the sentence and write it out completely. Capitalisation and the full stop are checked.',
      prompt: 'Ich kann kommen heute nicht.',
      acceptedAnswers: ['Ich kann heute nicht kommen.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'The infinitive must stand at the very end of the clause, after the Mittelfeld heute nicht, not right after the modal: Ich kann heute nicht kommen.',
    },
  ],
};
