import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter056: ChapterDefinition = {
  id: 'chapter-056',
  number: 56,
  slug: 'reflexive-pronouns-in-the-accusative-and-dative',
  title: 'Reflexive Pronouns in the Accusative and Dative',
  germanTitle: 'Reflexivpronomen im Akkusativ und im Dativ',
  level: 'B1',
  section: 'verbs-3',
  objective:
    'Choose correctly between the accusative reflexive pronouns (mich, dich, sich, uns, euch, sich) and the dative reflexive pronouns (mir, dir, sich, uns, euch, sich) by recognising whether the sentence already has a separate accusative object — especially in body-part and personal-item constructions such as sich die Zähne putzen and sich die Hände waschen — and use verbs like sich (Dat.) etwas kaufen, wünschen, überlegen, and vorstellen correctly.',
  prerequisites: [17, 18, 31],
  estimatedMinutes: 25,
  tags: [
    'reflexive pronouns',
    'dative case',
    'accusative case',
    'body parts',
    'daily routine',
    'case distinction',
  ],
  explanation: {
    introduction: [
      'Chapter 31 introduced the accusative reflexive pronouns mich, dich, sich, uns, euch, sich, used with verbs like sich duschen, sich anziehen, and sich beeilen, where the reflexive pronoun is the only object in the sentence. But German also has a second set of reflexive pronouns, in the dative: mir, dir, sich, uns, euch, sich. You need these whenever the sentence already has a separate accusative object — most often a body part or a personal item.',
      'Compare Ich wasche mich. (I wash myself — mich is the only object, so it is accusative) with Ich wasche mir die Hände. (I wash my hands — die Hände is now the accusative object, so the reflexive pronoun shifts to the dative, mir). Literally, the dative sentence says "I wash to myself the hands" — the dative reflexive pronoun shows who the hands belong to and who benefits from the washing, exactly like the indirect object you met in Chapter 18.',
      'This chapter teaches you the dative reflexive forms, the simple rule that decides which set to use, and a group of everyday verbs — sich die Zähne putzen, sich die Hände waschen, sich das Gesicht waschen, sich die Haare kämmen, and sich etwas kaufen/wünschen/überlegen/vorstellen — where getting the case right is essential.',
    ],
    rules: [
      {
        id: 'ch56-rule-01',
        heading: 'Recap: the accusative reflexive pronouns',
        paragraphs: [
          'As Chapter 31 explained, the accusative reflexive pronouns are mich, dich, sich, uns, euch, sich. Four forms match the accusative personal pronouns you already know (mich, dich, uns, euch); the third person (er/sie/es, plural sie) and the formal Sie all use the single form sich instead of ihn/sie/es/sie/Sie.',
          'These accusative forms are used whenever the reflexive pronoun is the only object of the verb: Ich dusche mich. Er zieht sich an. Wir beeilen uns. In every one of these sentences, nothing else in the clause could be the direct object — the reflexive pronoun itself is.',
        ],
      },
      {
        id: 'ch56-rule-02',
        heading: 'The new set: dative reflexive pronouns',
        paragraphs: [
          'The dative reflexive pronouns are mir, dir, sich, uns, euch, sich. Only two forms actually change shape compared to the accusative set: mich becomes mir (ich), and dich becomes dir (du) — exactly parallel to the personal pronouns mich/mir and dich/dir that you already know from the dative case.',
          'The other four persons look identical in both cases: er/sie/es and plural sie/Sie still use sich, and wir and ihr still use uns and euch. This means that for most subjects, you cannot tell from the pronoun alone whether it is accusative or dative — but for ich and du, the choice between mich/mir and dich/dir matters, and that is where most learners make mistakes.',
        ],
      },
      {
        id: 'ch56-rule-03',
        heading: 'The core rule: is there already an accusative object?',
        paragraphs: [
          'The choice between the two sets follows one simple rule: if the reflexive pronoun is the only object in the sentence, it is accusative. If the sentence already has a separate accusative object, the reflexive pronoun moves into the dative instead — because a verb normally cannot have two accusative objects at once.',
          'Compare Ich wasche mich. (no other object — mich is accusative) with Ich wasche mir die Hände. (die Hände is now the accusative object, so the reflexive pronoun becomes dative — mir). The same pair of verb forms, waschen and mich/mir, changes case purely because a second object has appeared.',
          'A useful check: ask "what is being washed/brushed/combed?" If the answer is "myself" (no separate thing), use the accusative. If the answer is a specific thing — teeth, hands, a face, hair — that thing is the accusative object, and the reflexive pronoun must be dative.',
        ],
      },
      {
        id: 'ch56-rule-04',
        heading: 'Body parts and personal items: the definite article, not a possessive',
        paragraphs: [
          'German has a whole family of everyday expressions built on this pattern: sich die Zähne putzen (to brush one\'s teeth), sich die Hände waschen (to wash one\'s hands), sich das Gesicht waschen (to wash one\'s face), and sich die Haare kämmen (to comb one\'s hair). In every case, the body part takes the accusative case with the definite article, not a possessive article.',
          'Ich putze mir die Zähne. — not Ich putze meine Zähne mir, and not (usually) Ich putze mir meine Zähne. The dative reflexive pronoun mir already shows whose teeth are being brushed, so adding a possessive on top of it is redundant; German simply uses die Zähne, dem Kontext nach clearly "my" teeth.',
          'This pattern is extremely common in daily-routine descriptions: Sie wäscht sich das Gesicht. Wir putzen uns die Zähne vor dem Schlafen. Kämmst du dir die Haare? — the article stays definite in every person.',
        ],
      },
      {
        id: 'ch56-rule-05',
        heading: 'Other verbs that take a dative reflexive pronoun',
        paragraphs: [
          'The same case logic extends beyond body parts to a group of verbs meaning roughly "for oneself" or "to oneself": sich (Dat.) etwas kaufen (to buy oneself something), sich (Dat.) etwas wünschen (to wish for something), sich (Dat.) etwas überlegen (to think something over, to consider), and sich (Dat.) etwas vorstellen (to imagine something).',
          'Wir kaufen uns ein neues Sofa. (We are buying ourselves a new sofa.) Ich wünsche mir ein Fahrrad zum Geburtstag. (I wish for a bike for my birthday.) Überleg dir gut, was du sagst. (Think carefully about what you say.) In each sentence, etwas — a sofa, a bike, what you say — is the accusative object, so the reflexive pronoun is dative.',
          'sich vorstellen is a particularly instructive example because it exists in both patterns with different meanings. Ich stelle mich vor. uses the accusative — no other object, and the meaning is "I introduce myself." Ich stelle mir das vor. or Stell dir das mal vor! uses the dative — das is now the accusative object, and the meaning shifts to "I imagine it / Just imagine that!"',
        ],
      },
      {
        id: 'ch56-rule-06',
        heading: 'Word order: pronoun before the accusative object',
        paragraphs: [
          'Just like the accusative reflexive pronoun, the dative reflexive pronoun stands right after the conjugated verb — and it comes before the accusative object noun phrase that follows it: Ich putze mir die Zähne., not Ich putze die Zähne mir.',
          'In a question with inversion, the same order holds after the verb and subject: Putzt du dir die Zähne? Wäschst du dir die Hände? The reflexive pronoun always slots in immediately, before the thing that is being washed, brushed, bought, or imagined.',
        ],
      },
      {
        id: 'ch56-rule-07',
        heading: 'Quick decision guide',
        paragraphs: [
          'When you are not sure which pronoun to use, ask two questions in order. First: does the verb already have (or clearly imply) a separate accusative object — a body part, an item, or a clause like "was du kochen sollst"? If no, use the accusative reflexive pronoun (mich, dich, sich, uns, euch, sich).',
          'If yes, use the dative reflexive pronoun (mir, dir, sich, uns, euch, sich) instead, and put the accusative object right after it. Since sich, uns, and euch look the same in both cases, this decision only changes the actual word you write when the subject is ich or du.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch56-table-01',
        title: 'Accusative vs. dative reflexive pronouns',
        columns: ['Subject', 'Accusative reflexive', 'Dative reflexive', 'English'],
        columnCases: [null, 'accusative', 'dative', null],
        rows: [
          ['ich', 'mich', 'mir', 'myself / to myself'],
          ['du', 'dich', 'dir', 'yourself / to yourself'],
          ['er/sie/es', 'sich', 'sich', 'himself/herself/itself'],
          ['wir', 'uns', 'uns', 'ourselves'],
          ['ihr', 'euch', 'euch', 'yourselves'],
          ['sie/Sie', 'sich', 'sich', 'themselves / yourself (formal)'],
        ],
        note: 'Only ich and du actually change shape (mich→mir, dich→dir); the other four persons look identical in both cases, so the choice mostly matters for ich and du.',
      },
      {
        id: 'ch56-table-02',
        title: 'Dative reflexive + accusative object: common constructions',
        columns: ['Reflexive verb phrase', 'Example sentence', 'English'],
        rows: [
          ['sich die Zähne putzen', 'Ich putze mir die Zähne.', 'I brush my teeth.'],
          ['sich die Hände waschen', 'Du wäschst dir die Hände.', 'You wash your hands.'],
          ['sich das Gesicht waschen', 'Sie wäscht sich das Gesicht.', 'She washes her face.'],
          ['sich die Haare kämmen', 'Er kämmt sich die Haare.', 'He combs his hair.'],
          ['sich etwas kaufen', 'Wir kaufen uns ein neues Sofa.', 'We buy ourselves a new sofa.'],
          ['sich etwas wünschen', 'Ich wünsche mir Frieden.', 'I wish for peace.'],
          ['sich etwas überlegen', 'Überleg dir das gut!', 'Think it over carefully!'],
          ['sich etwas vorstellen', 'Kannst du dir das vorstellen?', 'Can you imagine that?'],
        ],
        note: 'In every row, the noun after the reflexive pronoun (die Zähne, die Hände, ein neues Sofa, das) is the accusative object — that is exactly why the reflexive pronoun itself must be dative.',
      },
    ],
    examples: [
      {
        german: 'Ich putze mir die Zähne.',
        english: 'I brush my teeth.',
        highlight: ['mir'],
        explanation: 'die Zähne is already the accusative object, so ich needs the dative reflexive pronoun mir.',
      },
      {
        german: 'Ich wasche mich.',
        english: 'I wash (myself).',
        highlight: ['mich'],
        explanation: 'there is no separate accusative object here — mich itself is the object, so it stays accusative.',
      },
      {
        german: 'Ich wasche mir die Hände.',
        english: 'I wash my hands.',
        highlight: ['mir', 'die Hände'],
        explanation: 'once die Hände appears as the accusative object, the reflexive pronoun for ich switches from mich to mir.',
      },
      {
        german: 'Du kämmst dir die Haare.',
        english: 'You comb your hair.',
        highlight: ['dir'],
        explanation: 'die Haare is the accusative object, so du takes the dative reflexive pronoun dir, not dich.',
      },
      {
        german: 'Er kämmt sich die Haare.',
        english: 'He combs his hair.',
        highlight: ['sich'],
        explanation: 'er also uses sich for the dative reflexive — the same form as the accusative, but here required by the object die Haare.',
      },
      {
        german: 'Wir kaufen uns ein neues Sofa.',
        english: 'We are buying ourselves a new sofa.',
        highlight: ['uns'],
        explanation: 'ein neues Sofa is the accusative object of kaufen, so uns is a dative reflexive pronoun here.',
      },
      {
        german: 'Ich wünsche mir ein Fahrrad zum Geburtstag.',
        english: 'I wish for a bike for my birthday.',
        highlight: ['mir'],
        explanation: 'ein Fahrrad is the accusative object of wünschen, so ich takes the dative reflexive pronoun mir.',
      },
      {
        german: 'Stell dir das mal vor!',
        english: 'Just imagine that!',
        highlight: ['dir'],
        explanation: 'das is the accusative object here; sich (Dat.) etwas vorstellen means "to imagine something", unlike sich vorstellen "to introduce oneself".',
      },
      {
        german: 'Ich stelle mich kurz vor.',
        english: 'I introduce myself briefly.',
        highlight: ['mich'],
        explanation: 'with no separate object, vorstellen here means "to introduce oneself" and takes the accusative reflexive pronoun mich.',
      },
      {
        german: 'Überleg dir gut, was du sagst.',
        english: 'Think carefully about what you say.',
        highlight: ['dir'],
        explanation: 'sich überlegen always takes the dative reflexive pronoun; the clause was du sagst functions like the accusative object.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich putze mich die Zähne.',
        correct: 'Ich putze mir die Zähne.',
        explanation: 'die Zähne is already the accusative object of the sentence, so the reflexive pronoun for ich must be the dative mir, not the accusative mich.',
      },
      {
        incorrect: 'Ich wasche mir.',
        correct: 'Ich wasche mich.',
        explanation: 'with no separate accusative object, the reflexive pronoun is itself the direct object and must be accusative (mich), not dative (mir).',
      },
      {
        incorrect: 'Er kämmt ihm die Haare.',
        correct: 'Er kämmt sich die Haare.',
        explanation: 'a reflexive action always uses the reflexive pronoun sich, never the ordinary personal pronoun ihm/ihn — even when there is also an accusative object.',
      },
      {
        incorrect: 'Ich überlege mich, ob ich mitkomme.',
        correct: 'Ich überlege mir, ob ich mitkomme.',
        explanation: 'sich überlegen is always used with the dative reflexive pronoun (mir), because the ob-clause functions as its accusative object.',
      },
    ],
    remember: [
      'Two sets of reflexive pronouns: accusative (mich, dich, sich, uns, euch, sich, from Chapter 31) and dative (mir, dir, sich, uns, euch, sich, new here). Only ich and du actually change shape.',
      'Rule: if the reflexive pronoun is the only object, it is accusative. If the sentence already has a separate accusative object — often a body part or item — the reflexive pronoun becomes dative.',
      'With body parts and personal items, German uses the definite article (die Zähne, die Hände), not a possessive — the dative reflexive pronoun already shows whose they are.',
      'Verbs like sich (Dat.) etwas kaufen, wünschen, überlegen, and vorstellen always take the dative reflexive pronoun, because etwas is the accusative object.',
      'Word order: the reflexive pronoun comes right after the conjugated verb, before the accusative object — Ich putze mir die Zähne, not Ich putze die Zähne mir.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 26,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch56-ex-01',
      chapterNumber: 56,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'ich'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ich putze ___ die Zähne.',
      options: [
        { id: 'a', text: 'mir' },
        { id: 'b', text: 'mich' },
        { id: 'c', text: 'dir' },
        { id: 'd', text: 'sich' },
      ],
      correctOptionId: 'a',
      explanation: 'die Zähne is already the accusative object, so ich needs the dative reflexive pronoun mir.',
    },
    {
      id: 'ch56-ex-02',
      chapterNumber: 56,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'du'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Du kämmst ___ die Haare.',
      options: [
        { id: 'a', text: 'dir' },
        { id: 'b', text: 'dich' },
        { id: 'c', text: 'mir' },
        { id: 'd', text: 'sich' },
      ],
      correctOptionId: 'a',
      explanation: 'die Haare is the accusative object, so du needs the dative reflexive pronoun dir, not dich.',
    },
    {
      id: 'ch56-ex-03',
      chapterNumber: 56,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'wir'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Wir waschen ___ die Hände vor dem Essen.',
      options: [
        { id: 'a', text: 'uns' },
        { id: 'b', text: 'euch' },
        { id: 'c', text: 'sich' },
        { id: 'd', text: 'mir' },
      ],
      correctOptionId: 'a',
      explanation: 'die Hände is the accusative object, so wir takes the dative reflexive pronoun uns (identical in shape to the accusative here).',
    },
    {
      id: 'ch56-ex-04',
      chapterNumber: 56,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'ihr'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ihr kauft ___ ein Eis.',
      options: [
        { id: 'a', text: 'euch' },
        { id: 'b', text: 'uns' },
        { id: 'c', text: 'sich' },
        { id: 'd', text: 'ihr' },
      ],
      correctOptionId: 'a',
      explanation: 'ein Eis is the accusative object of kaufen, so ihr takes the dative reflexive pronoun euch.',
    },
    {
      id: 'ch56-ex-05',
      chapterNumber: 56,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'accusative', 'ich'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ich wasche ___.',
      options: [
        { id: 'a', text: 'mich' },
        { id: 'b', text: 'mir' },
        { id: 'c', text: 'dich' },
        { id: 'd', text: 'dir' },
      ],
      correctOptionId: 'a',
      explanation: 'there is no separate accusative object here, so ich takes the accusative reflexive pronoun mich.',
    },
    {
      id: 'ch56-ex-06',
      chapterNumber: 56,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'ich'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ich wasche ___ das Gesicht.',
      options: [
        { id: 'a', text: 'mir' },
        { id: 'b', text: 'mich' },
        { id: 'c', text: 'dir' },
        { id: 'd', text: 'dich' },
      ],
      correctOptionId: 'a',
      explanation: 'das Gesicht is now the accusative object, so ich switches to the dative reflexive pronoun mir.',
    },
    {
      id: 'ch56-ex-07',
      chapterNumber: 56,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'accusative', 'du'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Du interessierst ___ für Musik.',
      options: [
        { id: 'a', text: 'dich' },
        { id: 'b', text: 'dir' },
        { id: 'c', text: 'sich' },
        { id: 'd', text: 'euch' },
      ],
      correctOptionId: 'a',
      explanation: 'sich interessieren für is a truly reflexive verb that always takes the accusative; für Musik is a prepositional phrase, not a second accusative object.',
    },
    {
      id: 'ch56-ex-08',
      chapterNumber: 56,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'du', 'sich-überlegen'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Du überlegst ___, was du kochen sollst.',
      options: [
        { id: 'a', text: 'dir' },
        { id: 'b', text: 'dich' },
        { id: 'c', text: 'sich' },
        { id: 'd', text: 'euch' },
      ],
      correctOptionId: 'a',
      explanation: 'sich überlegen always takes the dative reflexive pronoun; the clause was du kochen sollst functions like its accusative object.',
    },
    {
      id: 'ch56-ex-09',
      chapterNumber: 56,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'er', 'sich-wünschen'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Er wünscht ___ ein neues Fahrrad zum Geburtstag.',
      options: [
        { id: 'a', text: 'sich' },
        { id: 'b', text: 'ihm' },
        { id: 'c', text: 'ihn' },
        { id: 'd', text: 'er' },
      ],
      correctOptionId: 'a',
      explanation: 'reflexive actions always use the reflexive pronoun sich, never the ordinary personal pronoun ihm/ihn — here required by the accusative object ein neues Fahrrad.',
    },
    {
      id: 'ch56-ex-10',
      chapterNumber: 56,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['case-choice', 'accusative-object-recognition'],
      instruction: 'Choose the sentence that has a separate accusative object and therefore needs the dative reflexive pronoun.',
      prompt: 'Welcher Satz hat ein zusätzliches Akkusativobjekt und braucht deshalb das Dativ-Reflexivpronomen?',
      options: [
        { id: 'a', text: 'Ich dusche mich.' },
        { id: 'b', text: 'Ich putze mir die Zähne.' },
        { id: 'c', text: 'Er beeilt sich.' },
        { id: 'd', text: 'Wir treffen uns.' },
      ],
      correctOptionId: 'b',
      explanation: 'die Zähne is a separate accusative object, so the reflexive pronoun in that sentence is dative; the other sentences have no other object, so their reflexive pronouns are accusative.',
    },
    {
      id: 'ch56-ex-11',
      chapterNumber: 56,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['case-choice', 'accusative-object-recognition'],
      instruction: 'Choose the sentence that needs the accusative reflexive pronoun, because there is no separate object.',
      prompt: 'Welcher Satz braucht das Akkusativ-Reflexivpronomen, weil kein zusätzliches Objekt vorhanden ist?',
      options: [
        { id: 'a', text: 'Sie kämmt sich die Haare.' },
        { id: 'b', text: 'Ich setze mich.' },
        { id: 'c', text: 'Wir kaufen uns ein Auto.' },
        { id: 'd', text: 'Ihr wünscht euch Glück.' },
      ],
      correctOptionId: 'b',
      explanation: 'Ich setze mich. has no separate accusative object — mich is the only object — so it stays accusative, unlike the other sentences, which each have an accusative object (die Haare, ein Auto, Glück) and therefore a dative reflexive pronoun.',
    },
    {
      id: 'ch56-ex-12',
      chapterNumber: 56,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'ich', 'sich-vorstellen'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Ich stelle ___ vor, dass wir am Meer sind.',
      options: [
        { id: 'a', text: 'mir' },
        { id: 'b', text: 'mich' },
        { id: 'c', text: 'dir' },
        { id: 'd', text: 'sich' },
      ],
      correctOptionId: 'a',
      explanation: 'sich (Dat.) etwas vorstellen means "to imagine something"; the dass-clause acts like the accusative object, so ich takes the dative reflexive pronoun mir.',
    },
    {
      id: 'ch56-ex-13',
      chapterNumber: 56,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'du', 'sich-vorstellen'],
      instruction: 'Choose the correct reflexive pronoun.',
      prompt: 'Kannst du ___ vorstellen, wie schön das wäre?',
      options: [
        { id: 'a', text: 'dir' },
        { id: 'b', text: 'dich' },
        { id: 'c', text: 'sich' },
        { id: 'd', text: 'euch' },
      ],
      correctOptionId: 'a',
      explanation: 'this is "to imagine", not "to introduce oneself", so du takes the dative reflexive pronoun dir; the wie-clause functions as the accusative object.',
    },
    {
      id: 'ch56-ex-14',
      chapterNumber: 56,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['case-choice', 'error-recognition'],
      instruction: 'Choose the grammatically correct sentence.',
      prompt: 'Welcher Satz ist richtig?',
      options: [
        { id: 'a', text: 'Ich putze mich die Zähne.' },
        { id: 'b', text: 'Ich putze mir die Zähne.' },
        { id: 'c', text: 'Mir ich putze die Zähne.' },
        { id: 'd', text: 'Ich putze die Zähne mich.' },
      ],
      correctOptionId: 'b',
      explanation: 'die Zähne is the accusative object, so the reflexive pronoun must be dative (mir), and it must stand right after the conjugated verb, before die Zähne.',
    },
    {
      id: 'ch56-ex-15',
      chapterNumber: 56,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['case-choice', 'error-recognition'],
      instruction: 'Choose the grammatically correct sentence.',
      prompt: 'Welcher Satz ist richtig?',
      options: [
        { id: 'a', text: 'Er kämmt ihm die Haare.' },
        { id: 'b', text: 'Er kämmt ihn die Haare.' },
        { id: 'c', text: 'Er kämmt sich die Haare.' },
        { id: 'd', text: 'Er kämmt sein die Haare.' },
      ],
      correctOptionId: 'c',
      explanation: 'a reflexive action needs the reflexive pronoun sich, never the personal pronoun ihm/ihn or the possessive sein.',
    },
    {
      id: 'ch56-ex-16',
      chapterNumber: 56,
      order: 16,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'ich'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ich putze ___ die Zähne.',
      acceptedAnswers: ['mir'],
      answerMode: 'caseInsensitive',
      placeholder: 'mir',
      maxLength: 10,
      explanation: 'die Zähne is the accusative object, so ich needs the dative reflexive pronoun mir.',
    },
    {
      id: 'ch56-ex-17',
      chapterNumber: 56,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'du'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Du wäschst ___ die Hände.',
      acceptedAnswers: ['dir'],
      answerMode: 'caseInsensitive',
      placeholder: 'dir',
      maxLength: 10,
      explanation: 'die Hände is the accusative object, so du needs the dative reflexive pronoun dir.',
    },
    {
      id: 'ch56-ex-18',
      chapterNumber: 56,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'wir'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wir kämmen ___ die Haare.',
      acceptedAnswers: ['uns'],
      answerMode: 'caseInsensitive',
      placeholder: 'uns',
      maxLength: 10,
      explanation: 'die Haare is the accusative object, so wir takes the dative reflexive pronoun uns.',
    },
    {
      id: 'ch56-ex-19',
      chapterNumber: 56,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['reflexive pronoun', 'dative', 'ihr'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ihr kauft ___ neue Schuhe.',
      acceptedAnswers: ['euch'],
      answerMode: 'caseInsensitive',
      placeholder: 'euch',
      maxLength: 10,
      explanation: 'neue Schuhe is the accusative object of kaufen, so ihr takes the dative reflexive pronoun euch.',
    },
    {
      id: 'ch56-ex-20',
      chapterNumber: 56,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'accusative', 'ich'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ich wasche ___.',
      acceptedAnswers: ['mich'],
      answerMode: 'caseInsensitive',
      placeholder: 'mich',
      maxLength: 10,
      explanation: 'there is no separate accusative object here, so ich takes the accusative reflexive pronoun mich.',
    },
    {
      id: 'ch56-ex-21',
      chapterNumber: 56,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'ich'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ich wasche ___ das Gesicht.',
      acceptedAnswers: ['mir'],
      answerMode: 'caseInsensitive',
      placeholder: 'mir',
      maxLength: 10,
      explanation: 'das Gesicht is now the accusative object, so ich switches to the dative reflexive pronoun mir.',
    },
    {
      id: 'ch56-ex-22',
      chapterNumber: 56,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'accusative', 'er'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Er setzt ___ auf den Stuhl.',
      acceptedAnswers: ['sich'],
      answerMode: 'caseInsensitive',
      placeholder: 'sich',
      maxLength: 10,
      explanation: 'there is no separate accusative object, so er takes the accusative reflexive pronoun sich.',
    },
    {
      id: 'ch56-ex-23',
      chapterNumber: 56,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['reflexive pronoun', 'dative', 'er', 'sich-kaufen'],
      instruction: 'Write the missing reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Er kauft ___ ein neues Handy.',
      acceptedAnswers: ['sich'],
      answerMode: 'caseInsensitive',
      placeholder: 'sich',
      maxLength: 10,
      explanation: 'ein neues Handy is the accusative object, so er needs the dative reflexive pronoun sich (identical in shape to the accusative here).',
    },
    {
      id: 'ch56-ex-24',
      chapterNumber: 56,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'accusative', 'daily-routine'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ich dusche ___ und putze mir danach die Zähne.',
      acceptedAnswers: ['mich'],
      answerMode: 'caseInsensitive',
      placeholder: 'mich',
      maxLength: 10,
      explanation: 'sich duschen has no separate accusative object, so ich takes the accusative reflexive pronoun mich, unlike putze mir die Zähne right after it.',
    },
    {
      id: 'ch56-ex-25',
      chapterNumber: 56,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'wir', 'sich-überlegen'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Wir überlegen ___, ob wir mitkommen.',
      acceptedAnswers: ['uns'],
      answerMode: 'caseInsensitive',
      placeholder: 'uns',
      maxLength: 10,
      explanation: 'sich überlegen always takes the dative reflexive pronoun; the ob-clause functions as its accusative object, so wir takes uns.',
    },
    {
      id: 'ch56-ex-26',
      chapterNumber: 56,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['reflexive pronoun', 'dative', 'ihr', 'sich-wünschen'],
      instruction: 'Complete the sentence with the correct reflexive pronoun. Capitalisation is not checked.',
      prompt: 'Ihr wünscht ___ ein schönes neues Jahr.',
      acceptedAnswers: ['euch'],
      answerMode: 'caseInsensitive',
      placeholder: 'euch',
      maxLength: 10,
      explanation: 'ein schönes neues Jahr is the accusative object of wünschen, so ihr takes the dative reflexive pronoun euch.',
    },
    {
      id: 'ch56-ex-27',
      chapterNumber: 56,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['case-choice', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich putze mich die Zähne.',
      acceptedAnswers: ['Ich putze mir die Zähne.'],
      answerMode: 'normalized',
      placeholder: 'Ich putze ...',
      maxLength: 40,
      explanation: 'die Zähne is already the accusative object, so the reflexive pronoun for ich must be the dative mir, not the accusative mich.',
    },
    {
      id: 'ch56-ex-28',
      chapterNumber: 56,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['reflexive-vs-personal-pronoun', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Er kämmt ihm die Haare.',
      acceptedAnswers: ['Er kämmt sich die Haare.'],
      answerMode: 'normalized',
      placeholder: 'Er kämmt ...',
      maxLength: 40,
      explanation: 'a reflexive action always uses the reflexive pronoun sich, never the ordinary personal pronoun ihm.',
    },
    {
      id: 'ch56-ex-29',
      chapterNumber: 56,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['reflexive-agreement', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Wir waschen sich die Hände.',
      acceptedAnswers: ['Wir waschen uns die Hände.'],
      answerMode: 'normalized',
      placeholder: 'Wir waschen ...',
      maxLength: 40,
      explanation: 'the reflexive pronoun must agree with the subject; wir takes uns, not the third-person sich.',
    },
    {
      id: 'ch56-ex-30',
      chapterNumber: 56,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['dative-reflexive', 'sich-vorstellen', 'sentence-building'],
      instruction: 'Write a complete sentence using the cues. Capitalisation and punctuation are checked; no full stop is required at the end unless shown.',
      prompt: 'ich – sich vorstellen – eine Reise nach Berlin',
      acceptedAnswers: ['Ich stelle mir eine Reise nach Berlin vor.', 'Ich stelle mir eine Reise nach Berlin vor'],
      answerMode: 'normalized',
      placeholder: 'Ich stelle mir ...',
      maxLength: 60,
      explanation: 'sich (Dat.) etwas vorstellen means "to imagine something"; eine Reise nach Berlin is the accusative object, so ich takes the dative reflexive pronoun mir.',
    },
  ],
};
