import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter080: ChapterDefinition = {
  id: 'chapter-080',
  number: 80,
  slug: 'paired-conjunctions',
  title: 'Paired Conjunctions',
  germanTitle: 'Zweiteilige Konjunktionen',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Choose and correctly complete the four German paired conjunctions — entweder ... oder, weder ... noch, sowohl ... als auch, and nicht nur ... sondern auch — connecting grammatically parallel elements in each half, and apply the word-order rules that govern them: normal verb-second order within each clause, plus the position-1 inversion triggered when entweder, weder, noch, or nicht nur opens a clause.',
  prerequisites: [44],
  estimatedMinutes: 30,
  tags: [
    'paired-conjunctions',
    'entweder-oder',
    'weder-noch',
    'sowohl-als-auch',
    'nicht-nur-sondern-auch',
    'parallel-structure',
    'word-order',
    'coordinating-conjunctions',
  ],
  explanation: {
    introduction: [
      'German pairs up several conjunctions into fixed two-part teams that must always appear together: entweder ... oder (either ... or), weder ... noch (neither ... nor), sowohl ... als auch (both ... and), and nicht nur ... sondern auch (not only ... but also). Like the coordinating conjunctions from Chapter 44, they connect elements of equal rank — two subjects, two verbs, two objects, or two full clauses — without changing the internal word order of what they connect.',
      'The main challenge with paired conjunctions is keeping both halves matched: each pair is a fixed unit (entweder always needs oder, never noch; weder always needs noch, never oder), and both halves must connect the same type of grammatical element, a property called parallel structure. A sentence where one half joins a full clause and the other half joins only a bare noun feels broken even if every individual word is correct.',
      'A second, more subtle point concerns word order. Und, aber, oder, denn, and sondern never occupy a position in the sentence — they sit in what grammarians call "position 0" and never trigger inversion. But entweder, weder, noch, and nicht nur behave differently: when one of them is the very first word of its own clause, it fills position 1 and pushes the verb ahead of the subject, exactly like any other word that opens a German main clause. This chapter shows exactly when that inversion happens and when it does not.',
    ],
    rules: [
      {
        id: 'ch80-rule-01',
        heading: 'entweder ... oder — two exclusive alternatives',
        paragraphs: [
          'Entweder ... oder presents two possibilities of which only one applies or is chosen; the two options exclude each other. It can join two full clauses, two verbs, two objects, or any other pair of parallel elements.',
          'Er kommt entweder heute oder morgen. (He is coming either today or tomorrow.) Only one of the two days will actually happen — entweder ... oder frames them as alternatives, not as things that are both true at once.',
        ],
      },
      {
        id: 'ch80-rule-02',
        heading: 'weder ... noch — negating both alternatives',
        paragraphs: [
          'Weder ... noch states that neither of the two alternatives is true; it already contains its own negation, so it is never combined with an additional nicht or kein on the same element.',
          'Sie mag weder Fisch noch Fleisch. (She likes neither fish nor meat.) Both possibilities are ruled out at once. Unlike oder in the entweder ... oder pair, noch behaves like an adverb rather than a true coordinating conjunction: when weder ... noch links two full clauses, both weder and noch can independently open their own clause and trigger inversion there (see Rule 6).',
        ],
      },
      {
        id: 'ch80-rule-03',
        heading: 'sowohl ... als auch — both apply',
        paragraphs: [
          'Sowohl ... als auch states that both alternatives are true or included; nothing is excluded, unlike with entweder ... oder. It most commonly joins two elements inside a single clause — two subjects, two objects, two adjectives — rather than two separate clauses.',
          'Sowohl mein Bruder als auch meine Schwester kommen zur Party. (Both my brother and my sister are coming to the party.) When sowohl ... als auch joins two subjects like this, the verb still agrees with the combined plural subject, since two people together are always plural: kommen, not kommt.',
        ],
      },
      {
        id: 'ch80-rule-04',
        heading: 'nicht nur ... sondern auch — an additional, often surprising, fact',
        paragraphs: [
          'Nicht nur ... sondern auch adds a second true fact on top of the first, often to emphasise that the second fact might be unexpected. It can join words, phrases, or two full clauses.',
          'Er spricht nicht nur Deutsch, sondern auch Französisch. (He speaks not only German, but also French.) This is the same sondern taught in Chapter 44 — it always follows a negation. Here nicht nur itself supplies that negation (nicht negates nur, "only"), and sondern auch then adds the further fact that replaces the implied restriction to just one thing.',
        ],
      },
      {
        id: 'ch80-rule-05',
        heading: 'Parallel structure: match what each half connects',
        paragraphs: [
          'Both halves of a paired conjunction must connect grammatically equivalent elements: two subjects with two subjects, two verbs with two verbs, two objects with two objects, or two full clauses with two full clauses. Mixing element types across the two halves breaks the parallel structure, even if every individual word is correct German.',
          'Sowohl er als auch seine Schwester kommen morgen. (Both he and his sister are coming tomorrow.) — two parallel subjects sharing one verb. Compare the faulty *Sowohl er kommt morgen als auch seine Schwester, where the first half already contains a full clause (er kommt morgen) while the second half is only a bare noun phrase (seine Schwester); the two halves no longer match.',
        ],
      },
      {
        id: 'ch80-rule-06',
        heading: 'Word order: verb-second inside each clause, with one inversion twist',
        paragraphs: [
          'When a paired conjunction links two independent clauses, each clause keeps its own normal verb-second word order — exactly like the coordinating conjunctions from Chapter 44. The interesting cases are entweder, weder, noch, and nicht nur: unlike the true coordinating conjunctions (und, aber, oder, denn, sondern), which never occupy a sentence position, these four words behave like adverbs. When one of them is the very first word of its clause, it fills position 1 and forces the verb ahead of the subject in that clause.',
          'Entweder komme ich, oder ich rufe an. (Either I will come, or I will call.) Entweder triggers inversion (komme ich); oder is a true coordinating conjunction, so the second clause keeps normal order (ich rufe an). Weder ... noch behaves differently from entweder ... oder: Weder hat er angerufen, noch hat er geschrieben. (He neither called nor wrote.) Here both weder and noch trigger inversion, because noch — unlike oder — is not one of the five true coordinating conjunctions.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch80-table-01',
        title: 'The four paired conjunctions',
        columns: ['Pair', 'Meaning', 'Example'],
        rows: [
          ['entweder ... oder', 'either ... or', 'Ich trinke entweder Kaffee oder Tee.'],
          ['weder ... noch', 'neither ... nor', 'Sie mag weder Fisch noch Fleisch.'],
          [
            'sowohl ... als auch',
            'both ... and',
            'Sie spielt sowohl Klavier als auch Gitarre.',
          ],
          [
            'nicht nur ... sondern auch',
            'not only ... but also',
            'Er spricht nicht nur Deutsch, sondern auch Französisch.',
          ],
        ],
        note: 'Never mix halves from different pairs: entweder only pairs with oder, weder only with noch, sowohl only with als auch, nicht nur only with sondern auch.',
      },
      {
        id: 'ch80-table-02',
        title: 'Word order when a pair opens a clause',
        columns: [
          'Pair',
          'Does it open the clause and trigger inversion?',
          'Effect on word order',
          'Example',
        ],
        rows: [
          [
            'entweder ... oder',
            'yes, but only entweder',
            'entweder occupies position 1 → inversion in the first clause only; oder is a true coordinating conjunction (position 0) → normal order in the second clause',
            'Entweder komme ich, oder ich rufe an.',
          ],
          [
            'weder ... noch',
            'yes, both weder and noch',
            'weder and noch each occupy position 1 in their own clause → inversion in both clauses',
            'Weder hat er angerufen, noch hat er geschrieben.',
          ],
          [
            'nicht nur ... sondern auch',
            'yes, but only nicht nur',
            'nicht nur occupies position 1 → inversion in the first clause only; sondern is a true coordinating conjunction (position 0) → normal order in the second clause, with auch inserted as an adverb',
            'Nicht nur kocht sie gut, sondern sie backt auch hervorragend.',
          ],
          [
            'sowohl ... als auch',
            'usually not',
            'sowohl ... als auch normally joins two elements within one clause rather than opening two separate clauses; the whole phrase fills one sentence slot and the verb stays in its normal second position',
            'Sowohl mein Bruder als auch meine Schwester kommen zur Party.',
          ],
        ],
      },
    ],
    examples: [
      {
        german: 'Entweder gehen wir ins Kino, oder wir bleiben zu Hause.',
        english: 'Either we go to the movies, or we stay home.',
        highlight: ['Entweder', 'oder'],
        explanation:
          'entweder triggers inversion (gehen wir); oder is a true coordinating conjunction, so the second clause has normal order (wir bleiben).',
      },
      {
        german: 'Ich trinke entweder Kaffee oder Tee.',
        english: 'I drink either coffee or tea.',
        highlight: ['entweder', 'oder'],
        explanation:
          'Here entweder ... oder joins two objects within a single clause, not two full clauses, so there is no inversion at all.',
      },
      {
        german: 'Weder hat er angerufen, noch hat er geschrieben.',
        english: 'He neither called nor wrote.',
        highlight: ['Weder', 'noch'],
        explanation:
          'Both weder and noch open their own clause and trigger inversion, unlike oder after entweder.',
      },
      {
        german: 'Sie mag weder Fisch noch Fleisch.',
        english: 'She likes neither fish nor meat.',
        highlight: ['weder', 'noch'],
        explanation:
          'weder ... noch already carries the negation, so no additional nicht or kein is needed.',
      },
      {
        german: 'Sowohl mein Bruder als auch meine Schwester kommen zur Party.',
        english: 'Both my brother and my sister are coming to the party.',
        highlight: ['Sowohl', 'als auch'],
        explanation:
          'Two parallel subjects joined by sowohl ... als auch take a plural verb, kommen.',
      },
      {
        german: 'Sie spielt sowohl Klavier als auch Gitarre.',
        english: 'She plays both piano and guitar.',
        highlight: ['sowohl', 'als auch'],
        explanation:
          'sowohl ... als auch joins two parallel objects inside a single clause.',
      },
      {
        german: 'Nicht nur kocht sie gut, sondern sie backt auch hervorragend.',
        english: 'Not only does she cook well, but she also bakes excellently.',
        highlight: ['Nicht nur', 'sondern auch'],
        explanation:
          'nicht nur opens the clause and triggers inversion (kocht sie); sondern is a true coordinating conjunction, so the next clause has normal order, with auch placed after the subject.',
      },
      {
        german: 'Er spricht nicht nur Deutsch, sondern auch Französisch.',
        english: 'He speaks not only German, but also French.',
        highlight: ['nicht nur', 'sondern auch'],
        explanation:
          'nicht nur ... sondern auch joins two objects; nicht supplies the negation that sondern requires, and auch marks the added fact.',
      },
      {
        german: 'Entweder kannst du mitkommen, oder du wartest hier.',
        english: 'Either you can come along, or you wait here.',
        highlight: ['Entweder', 'oder'],
        explanation:
          'entweder triggers inversion of the modal verb (kannst du); the second clause keeps normal order after oder.',
      },
      {
        german: 'Weder Tim noch Lisa mag das Konzert.',
        english: 'Neither Tim nor Lisa likes the concert.',
        highlight: ['Weder', 'noch'],
        explanation:
          'When weder ... noch joins two subjects, the verb typically stays singular, agreeing with the nearer subject.',
      },
      {
        german: 'Das Restaurant ist sowohl günstig als auch lecker.',
        english: 'The restaurant is both affordable and delicious.',
        highlight: ['sowohl', 'als auch'],
        explanation:
          'sowohl ... als auch joins two parallel adjectives describing the same subject.',
      },
      {
        german: 'Sie lernt nicht nur fleißig, sondern hilft auch anderen Studenten.',
        english: 'She not only studies diligently, but also helps other students.',
        highlight: ['nicht nur', 'sondern'],
        explanation:
          'The two halves connect parallel verb phrases (lernt fleißig / hilft anderen Studenten); the shared subject sie is dropped after sondern because it would otherwise be the first word there, so the verb hilft comes right after sondern.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Entweder komme ich, noch ich rufe an.',
        correct: 'Entweder komme ich, oder ich rufe an.',
        explanation:
          'entweder always pairs with oder, never with noch — noch belongs only to the weder ... noch pair.',
      },
      {
        incorrect: 'Weder mag ich Fisch, oder Fleisch.',
        correct: 'Weder mag ich Fisch, noch Fleisch.',
        explanation:
          'weder must be completed with noch, not oder — oder belongs only to the entweder ... oder pair.',
      },
      {
        incorrect: 'Er spricht nicht nur Deutsch.',
        correct: 'Er spricht nicht nur Deutsch, sondern auch Französisch.',
        explanation:
          'nicht nur cannot stand alone; it must be completed with sondern auch and the additional fact, or the sentence sounds unfinished.',
      },
      {
        incorrect: 'Sowohl er kommt als auch seine Schwester.',
        correct: 'Sowohl er als auch seine Schwester kommen.',
        explanation:
          'Both halves must connect the same type of element — here two subjects — not a full clause in one half and a bare noun phrase in the other.',
      },
      {
        incorrect: 'Er hat weder nicht angerufen noch geschrieben.',
        correct: 'Er hat weder angerufen noch geschrieben.',
        explanation:
          'weder ... noch already negates both actions; adding nicht as well creates a double negation and is ungrammatical.',
      },
    ],
    remember: [
      'entweder ... oder = either ... or (exclusive choice); weder ... noch = neither ... nor (built-in double negation); sowohl ... als auch = both ... and (nothing excluded); nicht nur ... sondern auch = not only ... but also (adds an extra, often surprising, fact).',
      'Never mix halves from different pairs — entweder only pairs with oder, weder only with noch, sowohl only with als auch, nicht nur only with sondern auch.',
      'Both halves must connect grammatically parallel elements: two subjects, two verbs, two objects, or two full clauses — never a mismatch of types.',
      'weder ... noch already contains its own negation; do not add another nicht or kein.',
      'Each clause keeps normal verb-second order, but entweder, weder, noch, and nicht nur can each open their own clause and trigger inversion, while oder and sondern (true coordinating conjunctions) never do.',
      'Never drop the second half of a pair — an unfinished nicht nur or entweder leaves the sentence incomplete.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 72,
    requiredCorrectTextInputs: 20,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch80-ex-01',
      chapterNumber: 80,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-meaning', 'entweder-oder'],
      instruction: 'Choose the conjunction pair that matches the English meaning.',
      prompt: "Which pair means 'either ... or'?",
      options: [
        { id: 'a', text: 'entweder ... oder' },
        { id: 'b', text: 'weder ... noch' },
        { id: 'c', text: 'sowohl ... als auch' },
        { id: 'd', text: 'nicht nur ... sondern auch' },
      ],
      correctOptionId: 'a',
      explanation:
        'entweder ... oder presents two mutually exclusive alternatives — exactly "either ... or".',
    },
    {
      id: 'ch80-ex-02',
      chapterNumber: 80,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-meaning', 'weder-noch'],
      instruction: 'Choose the conjunction pair that matches the English meaning.',
      prompt: "Which pair means 'neither ... nor'?",
      options: [
        { id: 'a', text: 'weder ... noch' },
        { id: 'b', text: 'entweder ... oder' },
        { id: 'c', text: 'sowohl ... als auch' },
        { id: 'd', text: 'nicht nur ... sondern auch' },
      ],
      correctOptionId: 'a',
      explanation:
        'weder ... noch negates both alternatives at once — "neither ... nor".',
    },
    {
      id: 'ch80-ex-03',
      chapterNumber: 80,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-meaning', 'sowohl-als-auch'],
      instruction: 'Choose the conjunction pair that matches the English meaning.',
      prompt: "Which pair means 'both ... and'?",
      options: [
        { id: 'a', text: 'sowohl ... als auch' },
        { id: 'b', text: 'entweder ... oder' },
        { id: 'c', text: 'weder ... noch' },
        { id: 'd', text: 'nicht nur ... sondern auch' },
      ],
      correctOptionId: 'a',
      explanation:
        'sowohl ... als auch states that both alternatives are true — "both ... and".',
    },
    {
      id: 'ch80-ex-04',
      chapterNumber: 80,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-meaning', 'nicht-nur-sondern-auch'],
      instruction: 'Choose the conjunction pair that matches the English meaning.',
      prompt: "Which pair means 'not only ... but also'?",
      options: [
        { id: 'a', text: 'nicht nur ... sondern auch' },
        { id: 'b', text: 'sowohl ... als auch' },
        { id: 'c', text: 'entweder ... oder' },
        { id: 'd', text: 'weder ... noch' },
      ],
      correctOptionId: 'a',
      explanation:
        'nicht nur ... sondern auch adds a second, often surprising, fact — "not only ... but also".',
    },
    {
      id: 'ch80-ex-05',
      chapterNumber: 80,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'entweder-oder'],
      instruction: 'Choose the word that correctly completes the pair.',
      prompt: 'Entweder komm ich mit, ___ ich bleibe hier.',
      options: [
        { id: 'a', text: 'oder' },
        { id: 'b', text: 'noch' },
        { id: 'c', text: 'als auch' },
        { id: 'd', text: 'sondern auch' },
      ],
      correctOptionId: 'a',
      explanation: 'entweder only ever pairs with oder.',
    },
    {
      id: 'ch80-ex-06',
      chapterNumber: 80,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'weder-noch'],
      instruction: 'Choose the word that correctly completes the pair.',
      prompt: 'Weder Tim ___ Lisa mag das Konzert.',
      options: [
        { id: 'a', text: 'noch' },
        { id: 'b', text: 'oder' },
        { id: 'c', text: 'als auch' },
        { id: 'd', text: 'sondern auch' },
      ],
      correctOptionId: 'a',
      explanation: 'weder only ever pairs with noch.',
    },
    {
      id: 'ch80-ex-07',
      chapterNumber: 80,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'sowohl-als-auch'],
      instruction: 'Choose the word(s) that correctly complete the pair.',
      prompt: 'Er ist sowohl klug ___ fleißig.',
      options: [
        { id: 'a', text: 'als auch' },
        { id: 'b', text: 'oder' },
        { id: 'c', text: 'noch' },
        { id: 'd', text: 'sondern auch' },
      ],
      correctOptionId: 'a',
      explanation: 'sowohl only ever pairs with als auch.',
    },
    {
      id: 'ch80-ex-08',
      chapterNumber: 80,
      order: 8,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'nicht-nur-sondern-auch'],
      instruction: 'Choose the word(s) that correctly complete the pair.',
      prompt: 'Sie ist nicht nur nett, ___ hilfsbereit.',
      options: [
        { id: 'a', text: 'sondern auch' },
        { id: 'b', text: 'oder' },
        { id: 'c', text: 'noch' },
        { id: 'd', text: 'als auch' },
      ],
      correctOptionId: 'a',
      explanation: 'nicht nur only ever pairs with sondern auch.',
    },
    {
      id: 'ch80-ex-09',
      chapterNumber: 80,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'entweder-oder'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Welcher Satz hat die richtige Wortstellung?',
      options: [
        { id: 'a', text: 'Entweder komme ich, oder ich rufe an.' },
        { id: 'b', text: 'Entweder ich komme, oder ich rufe an.' },
        { id: 'c', text: 'Entweder komme ich, oder rufe ich an.' },
      ],
      correctOptionId: 'a',
      explanation:
        'entweder occupies position 1 and triggers inversion (komme ich); oder is a true coordinating conjunction, so the second clause keeps normal order (ich rufe an), not inverted.',
    },
    {
      id: 'ch80-ex-10',
      chapterNumber: 80,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'weder-noch'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Welcher Satz hat die richtige Wortstellung?',
      options: [
        { id: 'a', text: 'Weder hat er angerufen, noch hat er geschrieben.' },
        { id: 'b', text: 'Weder er hat angerufen, noch er hat geschrieben.' },
        { id: 'c', text: 'Weder hat er angerufen, noch er hat geschrieben.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Unlike oder, noch is not a true coordinating conjunction — it behaves like an adverb and can also occupy position 1, so both clauses show inversion (hat er / hat er).',
    },
    {
      id: 'ch80-ex-11',
      chapterNumber: 80,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['parallel-structure', 'sowohl-als-auch'],
      instruction: 'Choose the sentence with correct parallel structure.',
      prompt: 'Welcher Satz hat eine korrekte parallele Struktur?',
      options: [
        { id: 'a', text: 'Sowohl Anna als auch Ben lernen Deutsch.' },
        { id: 'b', text: 'Sowohl Anna lernt Deutsch als auch Ben.' },
        { id: 'c', text: 'Sowohl lernt Anna Deutsch als auch Ben lernt Englisch.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Both halves connect the same type of element — two subjects, Anna and Ben — sharing the same verb lernen; option b and c mix a full clause with a bare noun phrase or use two different verbs.',
    },
    {
      id: 'ch80-ex-12',
      chapterNumber: 80,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['error-correction', 'entweder-oder'],
      instruction: 'Choose the corrected sentence.',
      prompt: 'Falsch: Entweder gehen wir ins Kino, noch wir bleiben zu Hause.',
      options: [
        { id: 'a', text: 'Entweder gehen wir ins Kino, oder wir bleiben zu Hause.' },
        { id: 'b', text: 'Entweder gehen wir ins Kino, weder wir bleiben zu Hause.' },
        { id: 'c', text: 'Weder gehen wir ins Kino, oder wir bleiben zu Hause.' },
      ],
      correctOptionId: 'a',
      explanation: 'entweder only pairs with oder; noch belongs only to weder ... noch.',
    },
    {
      id: 'ch80-ex-13',
      chapterNumber: 80,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['pair-selection', 'entweder-oder', 'pragmatics'],
      instruction: "Choose the pair that fits Paul's uncertainty between two options.",
      dialogue: [
        {
          speaker: 'Mia',
          german: 'Kommst du heute Abend mit ins Kino?',
          english: 'Are you coming to the movies with us tonight?',
        },
        {
          speaker: 'Paul',
          german:
            'Das weiß ich noch nicht. ___ komme ich mit, ___ ich bleibe zu Hause und lerne.',
          english: "I don't know yet. ... I'll come along, ... I'll stay home and study.",
        },
      ],
      prompt: '___ komme ich mit, ___ ich bleibe zu Hause und lerne.',
      options: [
        { id: 'a', text: 'Entweder ... oder' },
        { id: 'b', text: 'Weder ... noch' },
        { id: 'c', text: 'Sowohl ... als auch' },
        { id: 'd', text: 'Nicht nur ... sondern auch' },
      ],
      correctOptionId: 'a',
      explanation:
        "Paul names two options and hasn't decided between them yet, which is exactly the exclusive-alternative meaning of entweder ... oder; weder ... noch would deny both, sowohl ... als auch would claim both happen, and nicht nur ... sondern auch would add a second fact rather than present an unresolved choice.",
    },
    {
      id: 'ch80-ex-14',
      chapterNumber: 80,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['pair-selection', 'nicht-nur-sondern-auch'],
      instruction: 'Choose the pair that best expresses the intended emphasis.',
      prompt:
        'Der Satz soll ausdrücken: Er ist Arzt UND obendrein, überraschenderweise, auch noch Musiker. Welches Wortpaar passt am besten?',
      options: [
        { id: 'a', text: 'nicht nur ... sondern auch' },
        { id: 'b', text: 'entweder ... oder' },
        { id: 'c', text: 'weder ... noch' },
        { id: 'd', text: 'sowohl ... als auch' },
      ],
      correctOptionId: 'a',
      explanation:
        'nicht nur ... sondern auch is the pair that specifically frames the second fact as an additional, often surprising, piece of information — exactly the nuance described here; sowohl ... als auch would state both facts neutrally without that emphasis.',
    },
    {
      id: 'ch80-ex-15',
      chapterNumber: 80,
      order: 15,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'entweder-oder'],
      instruction:
        'Fill in the missing first word of the pair. Capitalisation is not checked.',
      prompt: '___ regnet es, oder es schneit.',
      acceptedAnswers: ['entweder'],
      answerMode: 'caseInsensitive',
      placeholder: 'entweder/weder/sowohl',
      maxLength: 15,
      explanation:
        'oder signals the entweder ... oder pair, so the missing first word is entweder.',
    },
    {
      id: 'ch80-ex-16',
      chapterNumber: 80,
      order: 16,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'weder-noch'],
      instruction:
        'Fill in the missing second word of the pair. Capitalisation is not checked.',
      prompt: 'Weder Tim ___ Lisa mag das Konzert.',
      acceptedAnswers: ['noch'],
      answerMode: 'caseInsensitive',
      placeholder: 'noch/oder/als auch',
      maxLength: 15,
      explanation: 'weder only ever pairs with noch.',
    },
    {
      id: 'ch80-ex-17',
      chapterNumber: 80,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'sowohl-als-auch'],
      instruction:
        'Fill in the missing words to complete the pair. Capitalisation is not checked.',
      prompt: 'Er ist sowohl klug ___ ___ fleißig.',
      acceptedAnswers: ['als auch'],
      answerMode: 'caseInsensitive',
      placeholder: 'als auch',
      maxLength: 15,
      explanation: 'sowohl only ever pairs with als auch.',
    },
    {
      id: 'ch80-ex-18',
      chapterNumber: 80,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'nicht-nur-sondern-auch'],
      instruction:
        'Fill in the missing words to complete the pair. Capitalisation is not checked.',
      prompt: 'Sie ist nicht nur nett, ___ ___ hilfsbereit.',
      acceptedAnswers: ['sondern auch'],
      answerMode: 'caseInsensitive',
      placeholder: 'sondern auch',
      maxLength: 20,
      explanation: 'nicht nur only ever pairs with sondern auch.',
    },
    {
      id: 'ch80-ex-19',
      chapterNumber: 80,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'entweder-oder'],
      instruction:
        'Combine the two sentences into one, joining the two objects with entweder ... oder. Capitalisation and punctuation are checked.',
      prompt: 'Sie mag Pizza. Sie mag Pasta.',
      acceptedAnswers: ['Sie mag entweder Pizza oder Pasta.'],
      answerMode: 'normalized',
      placeholder: 'Sie mag entweder ... oder ...',
      maxLength: 50,
      explanation:
        'entweder ... oder joins the two objects Pizza and Pasta as alternatives within a single clause; no comma or inversion is needed since only one clause is involved.',
    },
    {
      id: 'ch80-ex-20',
      chapterNumber: 80,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'weder-noch', 'word-order'],
      instruction:
        'Combine the two sentences into one with weder ... noch, remembering that both halves trigger inversion. Capitalisation and punctuation are checked.',
      prompt: 'Er ruft an. Er schreibt.',
      acceptedAnswers: ['Weder ruft er an, noch schreibt er.'],
      answerMode: 'normalized',
      placeholder: 'Weder ruft er an, noch ...',
      maxLength: 60,
      explanation:
        'Both weder and noch occupy position 1 in their own clause, so both clauses show inversion: ruft er an / schreibt er.',
    },
    {
      id: 'ch80-ex-21',
      chapterNumber: 80,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'sowohl-als-auch'],
      instruction:
        'Combine the two sentences into one, joining the two objects with sowohl ... als auch. Capitalisation and punctuation are checked.',
      prompt: 'Er mag Äpfel. Er mag Birnen.',
      acceptedAnswers: ['Er mag sowohl Äpfel als auch Birnen.'],
      answerMode: 'normalized',
      placeholder: 'Er mag sowohl ... als auch ...',
      maxLength: 50,
      explanation:
        'sowohl ... als auch joins the two parallel objects Äpfel and Birnen within a single clause.',
    },
    {
      id: 'ch80-ex-22',
      chapterNumber: 80,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'nicht-nur-sondern-auch', 'word-order'],
      instruction:
        'Combine the two sentences into one with nicht nur ... sondern auch, remembering that only nicht nur triggers inversion. Capitalisation and punctuation are checked.',
      prompt: 'Er kocht gut. Er backt hervorragend.',
      acceptedAnswers: ['Nicht nur kocht er gut, sondern er backt auch hervorragend.'],
      answerMode: 'normalized',
      placeholder: 'Nicht nur kocht er gut, sondern ...',
      maxLength: 70,
      explanation:
        'nicht nur opens the sentence and triggers inversion (kocht er); sondern keeps normal order in the second clause, with auch placed after the subject.',
    },
    {
      id: 'ch80-ex-23',
      chapterNumber: 80,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'entweder-oder'],
      instruction:
        'Correct the mismatched pair. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Entweder komme ich, noch ich rufe an.',
      acceptedAnswers: ['Entweder komme ich, oder ich rufe an.'],
      answerMode: 'normalized',
      placeholder: 'Entweder komme ich, oder ...',
      maxLength: 60,
      explanation:
        'entweder only pairs with oder; noch belongs to weder ... noch. Word order stays as in the original: normal order after oder (ich rufe an).',
    },
    {
      id: 'ch80-ex-24',
      chapterNumber: 80,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'weder-noch'],
      instruction:
        'Correct the mismatched pair. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Weder mag ich Fisch, oder Fleisch.',
      acceptedAnswers: ['Weder mag ich Fisch, noch Fleisch.'],
      answerMode: 'normalized',
      placeholder: 'Weder mag ich Fisch, noch ...',
      maxLength: 60,
      explanation: 'weder only pairs with noch; oder belongs to entweder ... oder.',
    },
    {
      id: 'ch80-ex-25',
      chapterNumber: 80,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'nicht-nur-sondern-auch'],
      instruction:
        'Complete the sentence by adding the missing second half with sondern auch and the fact in parentheses. Capitalisation and punctuation are checked.',
      prompt: 'Unvollständig: Er spricht nicht nur Deutsch. (ergänze: Französisch)',
      acceptedAnswers: ['Er spricht nicht nur Deutsch, sondern auch Französisch.'],
      answerMode: 'normalized',
      placeholder: 'Er spricht nicht nur Deutsch, sondern auch ...',
      maxLength: 70,
      explanation:
        'nicht nur cannot stand alone; the sentence needs its second half, sondern auch plus the added fact.',
    },
    {
      id: 'ch80-ex-26',
      chapterNumber: 80,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['parallel-structure', 'sowohl-als-auch', 'error-correction'],
      instruction:
        'Fix the broken parallel structure. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Sowohl er kommt als auch seine Schwester.',
      acceptedAnswers: ['Sowohl er als auch seine Schwester kommen.'],
      answerMode: 'normalized',
      placeholder: 'Sowohl er als auch seine Schwester ...',
      maxLength: 60,
      explanation:
        'Both halves must connect the same type of element — two parallel subjects, er and seine Schwester — sharing one plural verb, kommen, instead of a full clause paired with a bare noun phrase.',
    },
    {
      id: 'ch80-ex-27',
      chapterNumber: 80,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'entweder-oder', 'word-order'],
      instruction:
        'Combine the two sentences into one with entweder ... oder, using correct word order in both clauses. Capitalisation and punctuation are checked.',
      prompt: 'Wir bleiben zu Hause. Wir gehen spazieren.',
      acceptedAnswers: ['Entweder bleiben wir zu Hause, oder wir gehen spazieren.'],
      answerMode: 'normalized',
      placeholder: 'Entweder bleiben wir zu Hause, oder ...',
      maxLength: 70,
      explanation:
        'entweder triggers inversion (bleiben wir); oder is a true coordinating conjunction, so the second clause keeps normal order (wir gehen spazieren).',
    },
    {
      id: 'ch80-ex-28',
      chapterNumber: 80,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'weder-noch', 'word-order'],
      instruction:
        'Combine the two sentences into one with weder ... noch, remembering that both halves trigger inversion. Capitalisation and punctuation are checked.',
      prompt: 'Er kennt die Stadt. Er spricht die Sprache.',
      acceptedAnswers: ['Weder kennt er die Stadt, noch spricht er die Sprache.'],
      answerMode: 'normalized',
      placeholder: 'Weder kennt er die Stadt, noch ...',
      maxLength: 70,
      explanation:
        'Both weder and noch occupy position 1 in their own clause, so both clauses show inversion: kennt er die Stadt / spricht er die Sprache.',
    },
    {
      id: 'ch80-ex-29',
      chapterNumber: 80,
      order: 29,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'entweder-oder'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Ich fahre entweder mit dem Auto ___ mit dem Zug.',
      templateParts: ['Ich fahre entweder mit dem Auto ', ' mit dem Zug.'],
      slots: [{ id: 's1', correctWord: 'oder' }],
      wordBank: ['oder', 'noch', 'als auch', 'sondern auch'],
      explanation: 'entweder only ever pairs with oder.',
    },
    {
      id: 'ch80-ex-30',
      chapterNumber: 80,
      order: 30,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'weder-noch'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Er hat weder angerufen, ___ geschrieben.',
      templateParts: ['Er hat weder angerufen, ', ' geschrieben.'],
      slots: [{ id: 's1', correctWord: 'noch' }],
      wordBank: ['noch', 'oder', 'als auch', 'sondern auch'],
      explanation: 'weder only ever pairs with noch.',
    },
    {
      id: 'ch80-ex-31',
      chapterNumber: 80,
      order: 31,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'sowohl-als-auch'],
      instruction: 'Drag the correct word(s) into the blank.',
      prompt: 'Sie kann sowohl Deutsch ___ Englisch.',
      templateParts: ['Sie kann sowohl Deutsch ', ' Englisch.'],
      slots: [{ id: 's1', correctWord: 'als auch' }],
      wordBank: ['als auch', 'oder', 'noch', 'sondern auch'],
      explanation: 'sowohl only ever pairs with als auch.',
    },
    {
      id: 'ch80-ex-32',
      chapterNumber: 80,
      order: 32,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'nicht-nur-sondern-auch'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Er ist nicht nur intelligent, ___ auch charmant.',
      templateParts: ['Er ist nicht nur intelligent, ', ' auch charmant.'],
      slots: [{ id: 's1', correctWord: 'sondern' }],
      wordBank: ['sondern', 'oder', 'noch', 'als'],
      explanation: 'nicht nur only ever pairs with sondern (auch).',
    },
    {
      id: 'ch80-ex-33',
      chapterNumber: 80,
      order: 33,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['pair-completion', 'entweder-oder', 'word-order'],
      instruction: 'Drag the correct words into both blanks.',
      prompt: '___ komme ich mit, ___ ich bleibe zu Hause.',
      templateParts: ['', ' komme ich mit, ', ' ich bleibe zu Hause.'],
      slots: [
        { id: 's1', correctWord: 'Entweder' },
        { id: 's2', correctWord: 'oder' },
      ],
      wordBank: ['Entweder', 'oder', 'Weder', 'noch', 'Sowohl', 'als auch'],
      explanation:
        'Entweder opens the clause and triggers inversion (komme ich); oder is a true coordinating conjunction, so the second clause keeps normal order.',
    },
    {
      id: 'ch80-ex-34',
      chapterNumber: 80,
      order: 34,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['pair-completion', 'weder-noch', 'word-order'],
      instruction: 'Drag the correct words into both blanks.',
      prompt: '___ hat sie angerufen, ___ hat sie geschrieben.',
      templateParts: ['', ' hat sie angerufen, ', ' hat sie geschrieben.'],
      slots: [
        { id: 's1', correctWord: 'Weder' },
        { id: 's2', correctWord: 'noch' },
      ],
      wordBank: ['Weder', 'noch', 'Entweder', 'oder', 'Nicht nur', 'sondern auch'],
      explanation:
        'Unlike oder, noch is not a true coordinating conjunction, so both weder and noch trigger inversion in their own clause.',
    },
    {
      id: 'ch80-ex-35',
      chapterNumber: 80,
      order: 35,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['pair-completion', 'sowohl-als-auch'],
      instruction: 'Drag the correct words into both blanks.',
      prompt: 'Er ist ___ klug ___ fleißig.',
      templateParts: ['Er ist ', ' klug ', ' fleißig.'],
      slots: [
        { id: 's1', correctWord: 'sowohl' },
        { id: 's2', correctWord: 'als auch' },
      ],
      wordBank: ['sowohl', 'als auch', 'entweder', 'oder', 'weder', 'noch'],
      explanation:
        'sowohl only ever pairs with als auch, joining the two parallel adjectives.',
    },
    {
      id: 'ch80-ex-36',
      chapterNumber: 80,
      order: 36,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['pair-completion', 'nicht-nur-sondern-auch', 'word-order'],
      instruction: 'Drag the correct words into both blanks.',
      prompt: '___ kocht sie gut, ___ backt sie hervorragend.',
      templateParts: ['', ' kocht sie gut, ', ' backt sie hervorragend.'],
      slots: [
        { id: 's1', correctWord: 'Nicht nur' },
        { id: 's2', correctWord: 'sondern auch' },
      ],
      wordBank: ['Nicht nur', 'sondern auch', 'Entweder', 'oder', 'Weder', 'noch'],
      explanation:
        'Nicht nur opens the clause and triggers inversion (kocht sie); sondern auch keeps normal order after it.',
    },
    {
      id: 'ch80-ex-37',
      chapterNumber: 80,
      order: 37,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'entweder-oder'],
      instruction: 'Drag the correct word into the blank.',
      prompt: '___ regnet es heute, oder die Sonne scheint.',
      templateParts: ['', ' regnet es heute, oder die Sonne scheint.'],
      slots: [{ id: 's1', correctWord: 'Entweder' }],
      wordBank: ['Entweder', 'Weder', 'Sowohl', 'Nicht nur'],
      explanation: 'oder in the second half signals the entweder ... oder pair.',
    },
    {
      id: 'ch80-ex-38',
      chapterNumber: 80,
      order: 38,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['pair-completion', 'weder-noch'],
      instruction: 'Drag the correct word into the blank.',
      prompt: '___ mag ich Fisch, noch Fleisch.',
      templateParts: ['', ' mag ich Fisch, noch Fleisch.'],
      slots: [{ id: 's1', correctWord: 'Weder' }],
      wordBank: ['Weder', 'Entweder', 'Sowohl', 'Nicht nur'],
      explanation: 'noch in the second half signals the weder ... noch pair.',
    },
    {
      id: 'ch80-ex-39',
      chapterNumber: 80,
      order: 39,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['pair-completion'],
      instruction: 'Match each first half to its correct second half.',
      prompt: 'Welche zwei Hälften gehören zusammen?',
      pairs: [
        { id: 'p1', left: 'entweder', right: 'oder' },
        { id: 'p2', left: 'weder', right: 'noch' },
        { id: 'p3', left: 'sowohl', right: 'als auch' },
        { id: 'p4', left: 'nicht nur', right: 'sondern auch' },
      ],
      explanation:
        'Each paired conjunction is a fixed unit: entweder/oder, weder/noch, sowohl/als auch, nicht nur/sondern auch.',
    },
    {
      id: 'ch80-ex-40',
      chapterNumber: 80,
      order: 40,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['pair-meaning'],
      instruction: 'Match each pair to its English meaning.',
      prompt: 'Welches Wortpaar bedeutet was?',
      pairs: [
        { id: 'p1', left: 'entweder ... oder', right: 'either ... or' },
        { id: 'p2', left: 'weder ... noch', right: 'neither ... nor' },
        { id: 'p3', left: 'sowohl ... als auch', right: 'both ... and' },
        { id: 'p4', left: 'nicht nur ... sondern auch', right: 'not only ... but also' },
      ],
      explanation:
        'entweder ... oder is exclusive, weder ... noch negates both, sowohl ... als auch includes both, and nicht nur ... sondern auch adds an extra fact.',
    },
    {
      id: 'ch80-ex-41',
      chapterNumber: 80,
      order: 41,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['sentence-formation'],
      instruction: 'Match each sentence opening to its correct continuation.',
      prompt: 'Welcher Satzanfang passt zu welcher Fortsetzung?',
      pairs: [
        {
          id: 'p1',
          left: 'Er spricht nicht nur Deutsch,',
          right: 'sondern auch Französisch.',
        },
        { id: 'p2', left: 'Sie mag weder Fisch', right: 'noch Fleisch.' },
        { id: 'p3', left: 'Ich trinke entweder Kaffee', right: 'oder Tee.' },
        { id: 'p4', left: 'Sie spielt sowohl Klavier', right: 'als auch Gitarre.' },
      ],
      explanation: 'Each pair only accepts its own matching second half.',
    },
    {
      id: 'ch80-ex-42',
      chapterNumber: 80,
      order: 42,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['word-order'],
      instruction: 'Match each word-order effect to the pair that causes it.',
      prompt: 'Welcher Effekt gehört zu welchem Wortpaar?',
      pairs: [
        {
          id: 'p1',
          left: 'Inversion in both clauses when each half opens its own clause',
          right: 'weder ... noch',
        },
        {
          id: 'p2',
          left: 'Inversion only in the first clause (the second stays normal after oder)',
          right: 'entweder ... oder',
        },
        {
          id: 'p3',
          left: 'Inversion only in the first clause (the second stays normal after sondern)',
          right: 'nicht nur ... sondern auch',
        },
        {
          id: 'p4',
          left: 'Usually no clause-opening inversion at all',
          right: 'sowohl ... als auch',
        },
      ],
      explanation:
        'oder and sondern are true coordinating conjunctions and never trigger inversion, while entweder, weder, noch, and nicht nur can each occupy position 1.',
    },
    {
      id: 'ch80-ex-43',
      chapterNumber: 80,
      order: 43,
      type: 'matching',
      level: 'production',
      grammarFocus: ['error-correction'],
      instruction: 'Match each incorrect sentence to its corrected version.',
      prompt: 'Welcher falsche Satz gehört zu welcher Korrektur?',
      pairs: [
        {
          id: 'p1',
          left: 'Entweder komme ich, noch ich rufe an.',
          right: 'Entweder komme ich, oder ich rufe an.',
        },
        {
          id: 'p2',
          left: 'Weder mag ich Fisch, oder Fleisch.',
          right: 'Weder mag ich Fisch, noch Fleisch.',
        },
        {
          id: 'p3',
          left: 'Sowohl er kommt als auch seine Schwester.',
          right: 'Sowohl er als auch seine Schwester kommen.',
        },
        {
          id: 'p4',
          left: 'Er hat weder nicht angerufen noch geschrieben.',
          right: 'Er hat weder angerufen noch geschrieben.',
        },
      ],
      explanation:
        'Each incorrect sentence either mixes halves from different pairs, breaks parallel structure, or adds a redundant negation.',
    },
    {
      id: 'ch80-ex-44',
      chapterNumber: 80,
      order: 44,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['pair-meaning'],
      instruction: 'Match each German sentence to its English translation.',
      prompt: 'Welcher deutsche Satz gehört zu welcher englischen Übersetzung?',
      pairs: [
        {
          id: 'p1',
          left: 'Er kommt entweder heute oder morgen.',
          right: 'He is coming either today or tomorrow.',
        },
        {
          id: 'p2',
          left: 'Sie mag weder Fisch noch Fleisch.',
          right: 'She likes neither fish nor meat.',
        },
        {
          id: 'p3',
          left: 'Das Restaurant ist sowohl günstig als auch lecker.',
          right: 'The restaurant is both affordable and delicious.',
        },
        {
          id: 'p4',
          left: 'Er spricht nicht nur Deutsch, sondern auch Französisch.',
          right: 'He speaks not only German, but also French.',
        },
      ],
      explanation:
        'Each sentence uses one paired conjunction with its characteristic meaning.',
    },
    {
      id: 'ch80-ex-45',
      chapterNumber: 80,
      order: 45,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['pair-selection'],
      instruction: 'Match each situation to the pair that fits it best.',
      prompt: 'Welches Wortpaar passt zu welcher Situation?',
      pairs: [
        {
          id: 'p1',
          left: 'You want to state two exclusive options; only one will happen',
          right: 'entweder ... oder',
        },
        {
          id: 'p2',
          left: 'You want to rule out both options at once',
          right: 'weder ... noch',
        },
        {
          id: 'p3',
          left: 'You want to say both things are true, nothing excluded',
          right: 'sowohl ... als auch',
        },
        {
          id: 'p4',
          left: 'You want to add a second, often surprising, fact',
          right: 'nicht nur ... sondern auch',
        },
      ],
      explanation:
        'Each pair carries a distinct logical relationship between its two halves.',
    },
    {
      id: 'ch80-ex-46',
      chapterNumber: 80,
      order: 46,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['sentence-formation'],
      instruction: 'Match each pair to a sentence that uses it correctly.',
      prompt: 'Welches Wortpaar gehört zu welchem Beispielsatz?',
      pairs: [
        {
          id: 'p1',
          left: 'entweder ... oder',
          right: 'Entweder komme ich, oder ich rufe an.',
        },
        {
          id: 'p2',
          left: 'weder ... noch',
          right: 'Weder hat er angerufen, noch hat er geschrieben.',
        },
        {
          id: 'p3',
          left: 'sowohl ... als auch',
          right: 'Sowohl mein Bruder als auch meine Schwester kommen zur Party.',
        },
        {
          id: 'p4',
          left: 'nicht nur ... sondern auch',
          right: 'Nicht nur kocht sie gut, sondern sie backt auch hervorragend.',
        },
      ],
      explanation:
        'Each pair is illustrated by one of the chapter’s core example sentences.',
    },
    {
      id: 'ch80-ex-47',
      chapterNumber: 80,
      order: 47,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['error-correction', 'entweder-oder'],
      instruction: 'Find the token that breaks the pair and give its correction.',
      prompt: 'Entweder komme ich, noch ich rufe an.',
      tokens: ['Entweder', 'komme', 'ich,', 'noch', 'ich', 'rufe', 'an.'],
      errorTokenIndex: 3,
      correction: 'oder',
      explanation: 'entweder only pairs with oder; noch belongs only to weder ... noch.',
    },
    {
      id: 'ch80-ex-48',
      chapterNumber: 80,
      order: 48,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['error-correction', 'weder-noch'],
      instruction: 'Find the token that breaks the pair and give its correction.',
      prompt: 'Weder mag ich Fisch, oder Fleisch.',
      tokens: ['Weder', 'mag', 'ich', 'Fisch,', 'oder', 'Fleisch.'],
      errorTokenIndex: 4,
      correction: 'noch',
      explanation: 'weder only pairs with noch; oder belongs only to entweder ... oder.',
    },
    {
      id: 'ch80-ex-49',
      chapterNumber: 80,
      order: 49,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['error-correction', 'sowohl-als-auch'],
      instruction: 'Find the token that breaks the pair and give its correction.',
      prompt: 'Sie ist sowohl klug oder fleißig.',
      tokens: ['Sie', 'ist', 'sowohl', 'klug', 'oder', 'fleißig.'],
      errorTokenIndex: 4,
      correction: 'als auch',
      explanation:
        'sowohl only pairs with als auch; oder belongs only to entweder ... oder.',
    },
    {
      id: 'ch80-ex-50',
      chapterNumber: 80,
      order: 50,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['error-correction', 'nicht-nur-sondern-auch'],
      instruction: 'Find the token that breaks the pair and give its correction.',
      prompt: 'Er ist nicht nur nett, oder hilfsbereit.',
      tokens: ['Er', 'ist', 'nicht', 'nur', 'nett,', 'oder', 'hilfsbereit.'],
      errorTokenIndex: 5,
      correction: 'sondern auch',
      explanation:
        'nicht nur only pairs with sondern auch; oder belongs only to entweder ... oder.',
    },
    {
      id: 'ch80-ex-51',
      chapterNumber: 80,
      order: 51,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'weder-noch'],
      instruction: 'Find the token that breaks the pair and give its correction.',
      prompt: 'Weder Tim oder Lisa mag das Konzert.',
      tokens: ['Weder', 'Tim', 'oder', 'Lisa', 'mag', 'das', 'Konzert.'],
      errorTokenIndex: 2,
      correction: 'noch',
      explanation: 'weder only pairs with noch, even when joining two subjects.',
    },
    {
      id: 'ch80-ex-52',
      chapterNumber: 80,
      order: 52,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'entweder-oder'],
      instruction: 'Find the token that breaks the pair and give its correction.',
      prompt: 'Entweder bleiben wir zu Hause, noch wir gehen spazieren.',
      tokens: [
        'Entweder',
        'bleiben',
        'wir',
        'zu',
        'Hause,',
        'noch',
        'wir',
        'gehen',
        'spazieren.',
      ],
      errorTokenIndex: 5,
      correction: 'oder',
      explanation:
        'entweder only pairs with oder; the second clause keeps normal order after oder.',
    },
    {
      id: 'ch80-ex-53',
      chapterNumber: 80,
      order: 53,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'nicht-nur-sondern-auch'],
      instruction: 'Find the token that breaks the pair and give its correction.',
      prompt: 'Sie lernt nicht nur fleißig, noch hilft sie auch anderen.',
      tokens: [
        'Sie',
        'lernt',
        'nicht',
        'nur',
        'fleißig,',
        'noch',
        'hilft',
        'sie',
        'auch',
        'anderen.',
      ],
      errorTokenIndex: 5,
      correction: 'sondern',
      explanation:
        'nicht nur only pairs with sondern (auch); noch belongs only to weder ... noch.',
    },
    {
      id: 'ch80-ex-54',
      chapterNumber: 80,
      order: 54,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['word-order', 'entweder-oder'],
      instruction: 'Arrange the segments into the correct sentence.',
      prompt: 'Bilde den Satz: entweder ... oder mit Inversion im ersten Teilsatz.',
      segments: [
        { id: 's1', text: 'Entweder' },
        { id: 's2', text: 'komme' },
        { id: 's3', text: 'ich,' },
        { id: 's4', text: 'oder' },
        { id: 's5', text: 'ich' },
        { id: 's6', text: 'rufe' },
        { id: 's7', text: 'an.' },
      ],
      explanation:
        'Entweder occupies position 1 and triggers inversion (komme ich); oder is a true coordinating conjunction, so the second clause keeps normal order (ich rufe an).',
    },
    {
      id: 'ch80-ex-55',
      chapterNumber: 80,
      order: 55,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['word-order', 'weder-noch'],
      instruction: 'Arrange the segments into the correct sentence.',
      prompt: 'Bilde den Satz: weder ... noch mit Inversion in beiden Teilsätzen.',
      segments: [
        { id: 's1', text: 'Weder' },
        { id: 's2', text: 'ruft' },
        { id: 's3', text: 'er' },
        { id: 's4', text: 'an,' },
        { id: 's5', text: 'noch' },
        { id: 's6', text: 'schreibt' },
        { id: 's7', text: 'er.' },
      ],
      explanation:
        'Both weder and noch occupy position 1 in their own clause, so both clauses show inversion: ruft er / schreibt er.',
    },
    {
      id: 'ch80-ex-56',
      chapterNumber: 80,
      order: 56,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['sowohl-als-auch', 'parallel-structure'],
      instruction: 'Arrange the segments into the correct sentence.',
      prompt: 'Bilde den Satz: sowohl ... als auch mit zwei parallelen Subjekten.',
      segments: [
        { id: 's1', text: 'Sowohl' },
        { id: 's2', text: 'mein' },
        { id: 's3', text: 'Bruder' },
        { id: 's4', text: 'als' },
        { id: 's5', text: 'auch' },
        { id: 's6', text: 'meine' },
        { id: 's7', text: 'Schwester' },
        { id: 's8', text: 'kommen' },
        { id: 's9', text: 'zur' },
        { id: 's10', text: 'Party.' },
      ],
      explanation:
        'sowohl ... als auch joins two parallel subjects sharing one plural verb, kommen, and does not open two separate clauses.',
    },
    {
      id: 'ch80-ex-57',
      chapterNumber: 80,
      order: 57,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['nicht-nur-sondern-auch', 'parallel-structure'],
      instruction: 'Arrange the segments into the correct sentence.',
      prompt: 'Bilde den Satz: nicht nur ... sondern auch mit zwei parallelen Objekten.',
      segments: [
        { id: 's1', text: 'Er' },
        { id: 's2', text: 'spricht' },
        { id: 's3', text: 'nicht' },
        { id: 's4', text: 'nur' },
        { id: 's5', text: 'Deutsch,' },
        { id: 's6', text: 'sondern' },
        { id: 's7', text: 'auch' },
        { id: 's8', text: 'Französisch.' },
      ],
      explanation:
        'nicht nur ... sondern auch joins two parallel objects within a single clause, so there is no inversion here.',
    },
    {
      id: 'ch80-ex-58',
      chapterNumber: 80,
      order: 58,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'entweder-oder'],
      instruction: 'Arrange the segments into the correct sentence.',
      prompt: 'Bilde den Satz: entweder ... oder mit einem Modalverb.',
      segments: [
        { id: 's1', text: 'Entweder' },
        { id: 's2', text: 'kannst' },
        { id: 's3', text: 'du' },
        { id: 's4', text: 'mitkommen,' },
        { id: 's5', text: 'oder' },
        { id: 's6', text: 'wir' },
        { id: 's7', text: 'bleiben' },
        { id: 's8', text: 'hier.' },
      ],
      explanation:
        'entweder triggers inversion of the modal verb (kannst du); the second clause keeps normal order after oder.',
    },
    {
      id: 'ch80-ex-59',
      chapterNumber: 80,
      order: 59,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['weder-noch', 'parallel-structure'],
      instruction: 'Arrange the segments into the correct sentence.',
      prompt: 'Bilde den Satz: weder ... noch mit zwei parallelen Subjekten.',
      segments: [
        { id: 's1', text: 'Weder' },
        { id: 's2', text: 'Tim' },
        { id: 's3', text: 'noch' },
        { id: 's4', text: 'Lisa' },
        { id: 's5', text: 'mag' },
        { id: 's6', text: 'das' },
        { id: 's7', text: 'Konzert.' },
      ],
      explanation:
        'When weder ... noch joins two subjects within one clause, the verb stays in normal position and typically agrees with the nearer subject.',
    },
    {
      id: 'ch80-ex-60',
      chapterNumber: 80,
      order: 60,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['sowohl-als-auch', 'parallel-structure'],
      instruction: 'Arrange the segments into the correct sentence.',
      prompt: 'Bilde den Satz: sowohl ... als auch mit zwei parallelen Adjektiven.',
      segments: [
        { id: 's1', text: 'Das' },
        { id: 's2', text: 'Restaurant' },
        { id: 's3', text: 'ist' },
        { id: 's4', text: 'sowohl' },
        { id: 's5', text: 'günstig' },
        { id: 's6', text: 'als' },
        { id: 's7', text: 'auch' },
        { id: 's8', text: 'lecker.' },
      ],
      explanation:
        'sowohl ... als auch joins two parallel adjectives describing the same subject.',
    },
    {
      id: 'ch80-ex-61',
      chapterNumber: 80,
      order: 61,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['subject-verb-agreement', 'sowohl-als-auch'],
      instruction: 'Choose the correct verb form.',
      prompt: 'Sowohl der Lehrer als auch die Schüler ___ zufrieden.',
      options: [
        { id: 'a', text: 'sind' },
        { id: 'b', text: 'ist' },
        { id: 'c', text: 'war' },
      ],
      correctOptionId: 'a',
      explanation:
        'Two subjects joined by sowohl ... als auch count as plural together, so the verb is sind, not the singular ist.',
    },
    {
      id: 'ch80-ex-62',
      chapterNumber: 80,
      order: 62,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['subject-verb-agreement', 'weder-noch'],
      instruction: 'Choose the correct verb form.',
      prompt: 'Weder Tim noch Lisa ___ das Konzert.',
      options: [
        { id: 'a', text: 'mag' },
        { id: 'b', text: 'mögen' },
        { id: 'c', text: 'magst' },
      ],
      correctOptionId: 'a',
      explanation:
        'When weder ... noch joins two singular subjects, the verb typically stays singular, agreeing with the nearer subject: mag.',
    },
    {
      id: 'ch80-ex-63',
      chapterNumber: 80,
      order: 63,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['pair-completion', 'weder-noch'],
      instruction: 'Choose the word that correctly completes the pair.',
      prompt: 'Der Film war weder spannend ___ lustig.',
      options: [
        { id: 'a', text: 'noch' },
        { id: 'b', text: 'oder' },
        { id: 'c', text: 'als auch' },
        { id: 'd', text: 'sondern auch' },
      ],
      correctOptionId: 'a',
      explanation: 'weder only ever pairs with noch, ruling out both adjectives at once.',
    },
    {
      id: 'ch80-ex-64',
      chapterNumber: 80,
      order: 64,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['pair-selection', 'weder-noch', 'pragmatics'],
      instruction: 'Choose the pair that fits Ben rejecting both options.',
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Gehst du heute joggen oder ins Fitnessstudio?',
          english: 'Are you going jogging or to the gym today?',
        },
        {
          speaker: 'Ben',
          german:
            'Ich habe keine Lust auf Sport. Ich gehe ___ joggen ___ ins Fitnessstudio.',
          english:
            "I don't feel like exercising. I'm going neither jogging nor to the gym.",
        },
      ],
      prompt: 'Ich gehe ___ joggen ___ ins Fitnessstudio.',
      options: [
        { id: 'a', text: 'weder ... noch' },
        { id: 'b', text: 'entweder ... oder' },
        { id: 'c', text: 'sowohl ... als auch' },
        { id: 'd', text: 'nicht nur ... sondern auch' },
      ],
      correctOptionId: 'a',
      explanation:
        'Ben rejects both activities at once, which is exactly the built-in double negation of weder ... noch; the other pairs would present a choice, claim both, or add a fact.',
    },
    {
      id: 'ch80-ex-65',
      chapterNumber: 80,
      order: 65,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['pair-selection', 'sowohl-als-auch', 'pragmatics'],
      instruction: 'Choose the pair that fits everyone coming along.',
      dialogue: [
        {
          speaker: 'Lehrer',
          german: 'Wer kommt zur Exkursion, die Jungen oder die Mädchen?',
          english: 'Who is coming on the excursion, the boys or the girls?',
        },
        {
          speaker: 'Schülerin',
          german:
            'Eigentlich kommen alle mit! ___ die Jungen ___ die Mädchen kommen mit.',
          english: 'Actually everyone is coming! Both the boys and the girls are coming.',
        },
      ],
      prompt: '___ die Jungen ___ die Mädchen kommen mit.',
      options: [
        { id: 'a', text: 'Sowohl ... als auch' },
        { id: 'b', text: 'Entweder ... oder' },
        { id: 'c', text: 'Weder ... noch' },
        { id: 'd', text: 'Nicht nur ... sondern auch' },
      ],
      correctOptionId: 'a',
      explanation:
        'Both groups are coming, nothing is excluded, so sowohl ... als auch fits; entweder ... oder would frame them as alternatives, and weder ... noch would exclude both.',
    },
    {
      id: 'ch80-ex-66',
      chapterNumber: 80,
      order: 66,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'nicht-nur-sondern-auch'],
      instruction: 'Choose the grammatically correct sentence.',
      prompt: 'Welcher Satz ist grammatisch korrekt?',
      options: [
        {
          id: 'a',
          text: 'Nicht nur kocht sie gut, sondern sie backt auch hervorragend.',
        },
        {
          id: 'b',
          text: 'Nicht nur sie kocht gut, sondern sie backt auch hervorragend.',
        },
        {
          id: 'c',
          text: 'Nicht nur kocht sie gut, sondern auch sie backt hervorragend.',
        },
      ],
      correctOptionId: 'a',
      explanation:
        'nicht nur must trigger inversion (kocht sie), not option b; in the second clause auch is placed right after the subject (sie backt auch), not directly after sondern as in option c.',
    },
    {
      id: 'ch80-ex-67',
      chapterNumber: 80,
      order: 67,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['subject-verb-agreement', 'sowohl-als-auch'],
      instruction: 'Fill in the correct verb form. Capitalisation is not checked.',
      prompt:
        'Sowohl der Lehrer als auch die Schüler ___ zufrieden. (Verbform von "sein")',
      acceptedAnswers: ['sind'],
      answerMode: 'caseInsensitive',
      placeholder: 'sind/ist',
      maxLength: 10,
      explanation:
        'Two subjects joined by sowohl ... als auch count as plural together, so the verb is sind.',
    },
    {
      id: 'ch80-ex-68',
      chapterNumber: 80,
      order: 68,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['subject-verb-agreement', 'weder-noch'],
      instruction: 'Fill in the correct verb form. Capitalisation is not checked.',
      prompt: 'Weder Tim noch Lisa ___ das Konzert. (Verbform von "mögen")',
      acceptedAnswers: ['mag'],
      answerMode: 'caseInsensitive',
      placeholder: 'mag/mögen',
      maxLength: 10,
      explanation:
        'When weder ... noch joins two singular subjects, the verb typically agrees with the nearer subject and stays singular: mag.',
    },
    {
      id: 'ch80-ex-69',
      chapterNumber: 80,
      order: 69,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sentence-formation', 'weder-noch'],
      instruction:
        'Combine the two sentences into one, joining the two adjectives with weder ... noch. Capitalisation and punctuation are checked.',
      prompt: 'Der Film war nicht spannend. Der Film war nicht lustig.',
      acceptedAnswers: ['Der Film war weder spannend noch lustig.'],
      answerMode: 'normalized',
      placeholder: 'Der Film war weder ... noch ...',
      maxLength: 60,
      explanation:
        'weder ... noch already supplies the negation, so the two separate nicht sentences become one clause without any additional nicht.',
    },
    {
      id: 'ch80-ex-70',
      chapterNumber: 80,
      order: 70,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'nicht-nur-sondern-auch', 'word-order'],
      instruction:
        'Combine the two sentences into one with nicht nur ... sondern auch, keeping the shared subject only once. Capitalisation and punctuation are checked.',
      prompt: 'Sie lernt fleißig. Sie hilft anderen Studenten.',
      acceptedAnswers: [
        'Sie lernt nicht nur fleißig, sondern hilft auch anderen Studenten.',
      ],
      answerMode: 'normalized',
      placeholder: 'Sie lernt nicht nur fleißig, sondern ...',
      maxLength: 80,
      explanation:
        'The two halves connect parallel verb phrases; the shared subject sie is dropped after sondern because it would otherwise be the first word there, so hilft comes right after sondern.',
    },
    {
      id: 'ch80-ex-71',
      chapterNumber: 80,
      order: 71,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'sowohl-als-auch'],
      instruction:
        'Correct the mismatched pair. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Sie ist sowohl klug, oder fleißig.',
      acceptedAnswers: ['Sie ist sowohl klug als auch fleißig.'],
      answerMode: 'normalized',
      placeholder: 'Sie ist sowohl klug als auch ...',
      maxLength: 50,
      explanation:
        'sowohl only pairs with als auch; oder belongs only to entweder ... oder.',
    },
    {
      id: 'ch80-ex-72',
      chapterNumber: 80,
      order: 72,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'entweder-oder', 'word-order'],
      instruction:
        'Combine the two sentences into one with entweder ... oder, using correct word order in both clauses. Capitalisation and punctuation are checked.',
      prompt: 'Wir gehen ins Kino. Wir bleiben zu Hause.',
      acceptedAnswers: ['Entweder gehen wir ins Kino, oder wir bleiben zu Hause.'],
      answerMode: 'normalized',
      placeholder: 'Entweder gehen wir ins Kino, oder ...',
      maxLength: 70,
      explanation:
        'entweder triggers inversion (gehen wir); oder is a true coordinating conjunction, so the second clause keeps normal order (wir bleiben zu Hause).',
    },
  ],
};
