import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter028: ChapterDefinition = {
  id: 'chapter-028',
  number: 28,
  slug: 'formation-of-the-past-participle',
  title: 'Formation of the Past Participle',
  germanTitle: 'Bildung des Partizip II',
  level: 'A2',
  section: 'verbs-2',
  objective:
    'Form the past participle (Partizip II) correctly for weak, strong, separable, inseparable, -ieren, and mixed verbs, so that the present perfect tense from Chapters 26-27 can be built accurately for any verb.',
  prerequisites: [8, 26, 27],
  estimatedMinutes: 25,
  tags: [
    'past-participle',
    'partizip-ii',
    'weak-verbs',
    'strong-verbs',
    'separable-verbs',
    'inseparable-prefixes',
    'ieren-verbs',
    'mixed-verbs',
    'present-perfect',
  ],
  explanation: {
    introduction: [
      'In Chapters 26 and 27 you learned to build the present perfect tense with haben or sein plus a past participle: gemacht, gegangen, eingekauft. Those chapters treated the participle as a given fact. This chapter looks at where that word form actually comes from, so you can build the correct participle for any verb, not just the ones you have already memorized.',
      'German verbs fall into a small number of participle-formation patterns: weak (regular) verbs, strong (irregular) verbs, separable verbs, verbs with inseparable prefixes, verbs ending in -ieren, and a small "mixed" group. Recognizing which pattern a verb belongs to is the key skill — once you know the pattern, most participles almost build themselves.',
    ],
    rules: [
      {
        id: 'ch28-rule-01',
        heading: 'Weak (regular) verbs: ge- + stem + -t',
        paragraphs: [
          'Most German verbs are "weak" verbs: their past participle is formed by putting ge- in front of the stem and adding -t at the end. machen becomes gemacht, kaufen becomes gekauft, and spielen becomes gespielt. The stem is simply the infinitive minus its -en (or -n) ending.',
          'When the stem itself ends in -t, -d, or a consonant cluster that would be hard to pronounce before another -t (such as -chn, -ffn, -gn, -dn), an extra -e- is inserted before the final -t. arbeiten becomes gearbeitet, warten becomes gewartet, and öffnen becomes geöffnet. Say the forms aloud — the -e- is what makes them pronounceable.',
        ],
        notes: [
          'This is the same -e- you already use in the present tense: du arbeitest, er arbeitet.',
        ],
      },
      {
        id: 'ch28-rule-02',
        heading: 'Strong (irregular) verbs: ge- + stem (often changed) + -en',
        paragraphs: [
          'A smaller but very frequent group of verbs is "strong": their past participle ends in -en instead of -t, and the stem vowel very often changes as well. gehen becomes gegangen, essen becomes gegessen, and sprechen becomes gesprochen.',
          'There is no rule that predicts which verbs are strong or how their vowel changes — each one has to be learned individually, the same way you already memorized irregular present-tense forms like ich spreche, du sprichst. Learning a strong verb\'s participle together with its infinitive, as a fixed pair, is the most reliable method.',
        ],
      },
      {
        id: 'ch28-rule-03',
        heading: 'Separable verbs: ge- moves inside the word',
        paragraphs: [
          'Separable verbs consist of a stressed prefix (auf-, ein-, mit-, an-, fern-, and many others) plus a base verb. To form the participle, first form the participle of the base verb alone, then attach the prefix in front of it — the ge- ends up sandwiched between the prefix and the base participle. stehen becomes gestanden, so aufstehen becomes aufgestanden. kaufen becomes gekauft, so einkaufen becomes eingekauft.',
          'This works the same way whether the base verb is weak or strong: kommen is strong and becomes gekommen, so mitkommen becomes mitgekommen; rufen is strong and becomes gerufen, so anrufen becomes angerufen.',
        ],
      },
      {
        id: 'ch28-rule-04',
        heading: 'Inseparable prefixes: no ge- at all',
        paragraphs: [
          'A fixed set of unstressed prefixes — be-, ge-, er-, ver-, zer-, ent-, emp-, and miss- — never separate from the verb and never allow a ge- in the participle. besuchen becomes besucht, verstehen becomes verstanden, and erklären becomes erklärt: the participle looks almost like a weak participle, just without the ge-.',
          'This holds even when the base verb is strong: kommen is strong and becomes gekommen, but with the inseparable prefix be- it becomes bekommen — the ge- of gekommen simply disappears, leaving only the -en ending.',
        ],
        notes: [
          'The eight inseparable prefixes to remember: be-, ge-, er-, ver-, zer-, ent-, emp-, miss-.',
        ],
      },
      {
        id: 'ch28-rule-05',
        heading: '-ieren verbs: no ge-, always end in -t',
        paragraphs: [
          'Verbs ending in -ieren (often borrowed from other languages) never take ge- and always end in -t: studieren becomes studiert, telefonieren becomes telefoniert, and fotografieren becomes fotografiert. Because the stress in these verbs falls on -ieren rather than on the first syllable, German treats them like an inseparable-prefix verb and simply drops the ge-.',
        ],
      },
      {
        id: 'ch28-rule-06',
        heading: 'Mixed verbs: a weak ending with a strong-style change',
        paragraphs: [
          'A small group of verbs is "mixed": they take the weak ending -t, like regular verbs, but also change their stem vowel, like strong verbs. bringen becomes gebracht, denken becomes gedacht, kennen becomes gekannt, and wissen becomes gewusst.',
          'Like strong verbs, mixed verbs have to be memorized individually — there is no rule that predicts the vowel change, only the fact that the ending stays -t.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch28-table-01',
        title: 'Weak verbs: forming the participle',
        columns: ['Infinitive', 'Stem', 'Past participle', 'Note'],
        rows: [
          ['machen', 'mach-', 'gemacht', 'regular: ge- + stem + -t'],
          ['kaufen', 'kauf-', 'gekauft', 'regular: ge- + stem + -t'],
          ['spielen', 'spiel-', 'gespielt', 'regular: ge- + stem + -t'],
          ['arbeiten', 'arbeit-', 'gearbeitet', 'stem ends in -t: extra -e- before -t'],
          ['warten', 'wart-', 'gewartet', 'stem ends in -t: extra -e- before -t'],
          ['öffnen', 'öffn-', 'geöffnet', 'stem ends in a hard cluster: extra -e- before -t'],
        ],
      },
      {
        id: 'ch28-table-02',
        title: 'Strong verbs: memorize infinitive and participle together',
        columns: ['Infinitive', 'Past participle', 'English'],
        rows: [
          ['gehen', 'gegangen', 'to go / gone'],
          ['essen', 'gegessen', 'to eat / eaten'],
          ['sehen', 'gesehen', 'to see / seen'],
          ['lesen', 'gelesen', 'to read / read'],
          ['sprechen', 'gesprochen', 'to speak / spoken'],
          ['trinken', 'getrunken', 'to drink / drunk'],
          ['nehmen', 'genommen', 'to take / taken'],
          ['finden', 'gefunden', 'to find / found'],
        ],
      },
      {
        id: 'ch28-table-03',
        title: 'Separable vs. inseparable prefixes',
        columns: ['Type', 'Prefixes', 'Example infinitive', 'Past participle'],
        rows: [
          ['Separable (stressed, ge- goes inside)', 'auf-, ein-, mit-, an-, fern-, ...', 'aufstehen', 'aufgestanden'],
          ['Separable', 'auf-, ein-, mit-, an-, fern-, ...', 'einkaufen', 'eingekauft'],
          ['Inseparable (unstressed, blocks ge-)', 'be-, ge-, er-, ver-, zer-, ent-, emp-, miss-', 'besuchen', 'besucht'],
          ['Inseparable', 'be-, ge-, er-, ver-, zer-, ent-, emp-, miss-', 'verstehen', 'verstanden'],
        ],
      },
      {
        id: 'ch28-table-04',
        title: 'Mixed verbs',
        columns: ['Infinitive', 'Past participle', 'English'],
        rows: [
          ['bringen', 'gebracht', 'to bring / brought'],
          ['denken', 'gedacht', 'to think / thought'],
          ['kennen', 'gekannt', 'to know (a person) / known'],
          ['wissen', 'gewusst', 'to know (a fact) / known'],
          ['nennen', 'genannt', 'to name / named'],
        ],
      },
    ],
    examples: [
      {
        german: 'Ich habe das Abendessen gemacht.',
        english: 'I made dinner.',
        highlight: ['gemacht'],
        explanation: 'machen is weak: ge- + stem + -t gives gemacht.',
      },
      {
        german: 'Wir haben ein neues Auto gekauft.',
        english: 'We bought a new car.',
        highlight: ['gekauft'],
        explanation: 'kaufen is weak: ge- + stem + -t gives gekauft.',
      },
      {
        german: 'Sie hat den ganzen Tag gearbeitet.',
        english: 'She worked all day.',
        highlight: ['gearbeitet'],
        explanation: 'The stem arbeit- ends in -t, so an extra -e- is inserted before the final -t: gearbeitet.',
      },
      {
        german: 'Er ist gestern nach Hause gegangen.',
        english: 'He went home yesterday.',
        highlight: ['gegangen'],
        explanation: 'gehen is strong; its participle gegangen must be memorized, not derived by a rule.',
      },
      {
        german: 'Wir haben zusammen Pizza gegessen.',
        english: 'We ate pizza together.',
        highlight: ['gegessen'],
        explanation: 'essen is strong: gegessen changes both the stem and takes the -en ending.',
      },
      {
        german: 'Hast du den Film schon gesehen?',
        english: 'Have you already seen the movie?',
        highlight: ['gesehen'],
        explanation: 'sehen is strong: the participle is gesehen.',
      },
      {
        german: 'Ich bin heute früh aufgestanden.',
        english: 'I got up early today.',
        highlight: ['aufgestanden'],
        explanation: 'aufstehen is separable: stehen becomes gestanden, and the prefix auf- goes in front, giving aufgestanden.',
      },
      {
        german: 'Habt ihr gestern eingekauft?',
        english: 'Did you go shopping yesterday?',
        highlight: ['eingekauft'],
        explanation: 'einkaufen is separable: kaufen becomes gekauft, and ein- goes in front, giving eingekauft.',
      },
      {
        german: 'Meine Schwester hat ihre Oma besucht.',
        english: 'My sister visited her grandmother.',
        highlight: ['besucht'],
        explanation: 'be- is an inseparable prefix that blocks ge- completely: besucht, not gebesucht.',
      },
      {
        german: 'Wir haben den Text gut verstanden.',
        english: 'We understood the text well.',
        highlight: ['verstanden'],
        explanation: 'ver- is inseparable and blocks ge-; the participle is verstanden.',
      },
      {
        german: 'Er hat drei Jahre in Berlin studiert.',
        english: 'He studied in Berlin for three years.',
        highlight: ['studiert'],
        explanation: '-ieren verbs never take ge- and always end in -t: studiert.',
      },
      {
        german: 'Habt ihr schon mit euren Eltern telefoniert?',
        english: 'Have you already called your parents?',
        highlight: ['telefoniert'],
        explanation: 'telefonieren is an -ieren verb: no ge-, ending -t.',
      },
      {
        german: 'Ich habe nicht an das Meeting gedacht.',
        english: 'I did not think about the meeting.',
        highlight: ['gedacht'],
        explanation: 'denken is mixed: the weak -t ending combines with a stem-vowel change, giving gedacht.',
      },
      {
        german: 'Sie hat die Antwort nicht gewusst.',
        english: 'She did not know the answer.',
        highlight: ['gewusst'],
        explanation: 'wissen is mixed: the weak -t ending combines with a stem-vowel change, giving gewusst.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich habe mit ihm gesprecht.',
        correct: 'Ich habe mit ihm gesprochen.',
        explanation: 'sprechen is strong; the participle changes the stem vowel to gesprochen, it does not simply add -t like a weak verb.',
      },
      {
        incorrect: 'Ich bin heute früh geaufgestanden.',
        correct: 'Ich bin heute früh aufgestanden.',
        explanation: 'aufstehen is separable: ge- is inserted between the prefix auf- and the base participle gestanden (aufgestanden), never in front of the whole word.',
      },
      {
        incorrect: 'Meine Schwester hat ihre Oma gebesucht.',
        correct: 'Meine Schwester hat ihre Oma besucht.',
        explanation: 'besuchen begins with the inseparable prefix be-, which blocks ge- completely; the participle is besucht, not gebesucht.',
      },
      {
        incorrect: 'Er hat drei Jahre in Berlin gestudiert.',
        correct: 'Er hat drei Jahre in Berlin studiert.',
        explanation: 'Verbs ending in -ieren never take ge-; the participle is simply stem + -t: studiert.',
      },
      {
        incorrect: 'Sie hat den ganzen Tag gearbet.',
        correct: 'Sie hat den ganzen Tag gearbeitet.',
        explanation: 'The stem arbeit- already ends in -t, so an extra -e- is inserted before the final -t to keep the word pronounceable: gearbeitet.',
      },
      {
        incorrect: 'Sie hat die Antwort nicht gewisst.',
        correct: 'Sie hat die Antwort nicht gewusst.',
        explanation: 'wissen is a mixed verb: it takes the weak -t ending but changes its stem vowel to u, giving gewusst, not a regular gewisst.',
      },
    ],
    remember: [
      'Weak verbs: ge- + stem + -t (gemacht, gekauft); insert an extra -e- before -t if the stem ends in -t, -d, or a hard consonant cluster (gearbeitet, geöffnet).',
      'Strong verbs: ge- + stem (often vowel-changed) + -en; there is no reliable rule, so memorize each one as a fixed pair with its infinitive (gegangen, gegessen, gesprochen).',
      'Separable verbs: ge- goes between the prefix and the base participle (aufgestanden, eingekauft, mitgekommen).',
      'Inseparable prefixes (be-, ge-, er-, ver-, zer-, ent-, emp-, miss-) and all -ieren verbs never take ge- at all (besucht, verstanden, studiert, telefoniert).',
      'Mixed verbs combine the weak -t ending with a strong-style vowel change; these must also be memorized (gebracht, gedacht, gekannt, gewusst).',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch28-ex-01',
      chapterNumber: 28,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['weak-verbs', 'partizip-ii'],
      instruction: 'Choose the correct past participle.',
      prompt: 'machen → ___',
      options: [
        { id: 'a', text: 'gemachen' },
        { id: 'b', text: 'gemacht' },
        { id: 'c', text: 'machte' },
        { id: 'd', text: 'gemachte' },
      ],
      correctOptionId: 'b',
      explanation: 'machen is a weak verb: ge- + stem + -t gives gemacht.',
    },
    {
      id: 'ch28-ex-02',
      chapterNumber: 28,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['weak-verbs', 'partizip-ii'],
      instruction: 'Choose the correct past participle.',
      prompt: 'kaufen → ___',
      options: [
        { id: 'a', text: 'kaufte' },
        { id: 'b', text: 'gekauften' },
        { id: 'c', text: 'gekauft' },
        { id: 'd', text: 'kauft' },
      ],
      correctOptionId: 'c',
      explanation: 'kaufen is weak: ge- + stem + -t gives gekauft, not the simple past kaufte.',
    },
    {
      id: 'ch28-ex-03',
      chapterNumber: 28,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['weak-verbs', 'extra-e'],
      instruction: 'Choose the correct past participle.',
      prompt: 'arbeiten → ___',
      options: [
        { id: 'a', text: 'gearbeit' },
        { id: 'b', text: 'gearbeitet' },
        { id: 'c', text: 'gearbetet' },
        { id: 'd', text: 'arbeitet' },
      ],
      correctOptionId: 'b',
      explanation: 'The stem arbeit- already ends in -t, so an extra -e- is inserted before the final -t: gearbeitet.',
    },
    {
      id: 'ch28-ex-04',
      chapterNumber: 28,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['strong-verbs', 'partizip-ii'],
      instruction: 'Choose the correct past participle.',
      prompt: 'gehen → ___',
      options: [
        { id: 'a', text: 'gegeht' },
        { id: 'b', text: 'geganget' },
        { id: 'c', text: 'gegangen' },
        { id: 'd', text: 'gegehen' },
      ],
      correctOptionId: 'c',
      explanation: 'gehen is a strong verb with an irregular participle that must be memorized: gegangen.',
    },
    {
      id: 'ch28-ex-05',
      chapterNumber: 28,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-verbs', 'pattern-recognition'],
      instruction: 'Which pattern does this verb follow?',
      prompt: 'sehen (Partizip II: gesehen)',
      options: [
        { id: 'a', text: 'weak verb (ge-...-t)' },
        { id: 'b', text: 'strong verb (ge-...-en, vowel may change)' },
        { id: 'c', text: 'separable verb' },
        { id: 'd', text: '-ieren verb (no ge-)' },
      ],
      correctOptionId: 'b',
      explanation: 'sehen forms its participle with ge- and the ending -en, typical of strong verbs, though here the vowel happens to stay the same.',
    },
    {
      id: 'ch28-ex-06',
      chapterNumber: 28,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ieren-verbs', 'pattern-recognition'],
      instruction: 'Which pattern does this verb follow?',
      prompt: 'studieren (Partizip II: studiert)',
      options: [
        { id: 'a', text: 'weak verb (ge-...-t)' },
        { id: 'b', text: 'strong verb (ge-...-en)' },
        { id: 'c', text: '-ieren verb (no ge-, ends in -t)' },
        { id: 'd', text: 'mixed verb' },
      ],
      correctOptionId: 'c',
      explanation: 'Verbs ending in -ieren never take ge- and always end in -t: studiert.',
    },
    {
      id: 'ch28-ex-07',
      chapterNumber: 28,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['separable-verbs', 'pattern-recognition'],
      instruction: 'Which pattern does this verb follow?',
      prompt: 'aufstehen (Partizip II: aufgestanden)',
      options: [
        { id: 'a', text: 'inseparable verb (no ge-)' },
        { id: 'b', text: '-ieren verb (no ge-)' },
        { id: 'c', text: 'separable verb (ge- goes inside, after the prefix)' },
        { id: 'd', text: 'weak verb (ge-...-t)' },
      ],
      correctOptionId: 'c',
      explanation: 'aufstehen is separable: the ge- of the base participle gestanden is inserted after the prefix auf-, giving aufgestanden.',
    },
    {
      id: 'ch28-ex-08',
      chapterNumber: 28,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inseparable-prefixes', 'pattern-recognition'],
      instruction: 'Which pattern does this verb follow?',
      prompt: 'verstehen (Partizip II: verstanden)',
      options: [
        { id: 'a', text: 'separable verb (ge- goes inside)' },
        { id: 'b', text: '-ieren verb (no ge-)' },
        { id: 'c', text: 'mixed verb' },
        { id: 'd', text: 'inseparable verb (prefix blocks ge-)' },
      ],
      correctOptionId: 'd',
      explanation: 'ver- is one of the inseparable prefixes; it blocks ge- completely, so the participle is simply verstanden.',
    },
    {
      id: 'ch28-ex-09',
      chapterNumber: 28,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['strong-verbs', 'partizip-ii'],
      instruction: 'Choose the correct past participle.',
      prompt: 'trinken → ___',
      options: [
        { id: 'a', text: 'getrinkt' },
        { id: 'b', text: 'trinkt' },
        { id: 'c', text: 'getrunken' },
        { id: 'd', text: 'getrinken' },
      ],
      correctOptionId: 'c',
      explanation: 'trinken is strong; the stem vowel changes from i to u and the ending is -en: getrunken.',
    },
    {
      id: 'ch28-ex-10',
      chapterNumber: 28,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inseparable-prefixes', 'partizip-ii'],
      instruction: 'Choose the correct past participle.',
      prompt: 'besuchen → ___',
      options: [
        { id: 'a', text: 'gebesucht' },
        { id: 'b', text: 'besuchen' },
        { id: 'c', text: 'besucht' },
        { id: 'd', text: 'besuchte' },
      ],
      correctOptionId: 'c',
      explanation: 'be- is inseparable and blocks ge-; the participle is besucht.',
    },
    {
      id: 'ch28-ex-11',
      chapterNumber: 28,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['mixed-verbs', 'partizip-ii'],
      instruction: 'Choose the correct past participle.',
      prompt: 'bringen → ___',
      options: [
        { id: 'a', text: 'gebringt' },
        { id: 'b', text: 'gebrungen' },
        { id: 'c', text: 'bringte' },
        { id: 'd', text: 'gebracht' },
      ],
      correctOptionId: 'd',
      explanation: 'bringen is a mixed verb: the weak ending -t combines with a stem-vowel change: gebracht.',
    },
    {
      id: 'ch28-ex-12',
      chapterNumber: 28,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inseparable-prefixes'],
      instruction: 'Which of these prefixes is inseparable and blocks ge-?',
      prompt: 'auf-, mit-, ein-, ver- — which one is inseparable?',
      options: [
        { id: 'a', text: 'auf-' },
        { id: 'b', text: 'mit-' },
        { id: 'c', text: 'ein-' },
        { id: 'd', text: 'ver-' },
      ],
      correctOptionId: 'd',
      explanation: 'ver- belongs to the fixed set of inseparable prefixes (be-, ge-, er-, ver-, zer-, ent-, emp-, miss-); auf-, mit-, and ein- are all separable.',
    },
    {
      id: 'ch28-ex-13',
      chapterNumber: 28,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weak-verbs', 'partizip-ii'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'spielen → ___',
      acceptedAnswers: ['gespielt'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...t',
      maxLength: 20,
      explanation: 'spielen is weak: ge- + stem + -t gives gespielt.',
    },
    {
      id: 'ch28-ex-14',
      chapterNumber: 28,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['weak-verbs', 'extra-e'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'warten → ___',
      acceptedAnswers: ['gewartet'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...t',
      maxLength: 20,
      explanation: 'The stem wart- ends in -t, so an -e- is inserted before the final -t: gewartet.',
    },
    {
      id: 'ch28-ex-15',
      chapterNumber: 28,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['strong-verbs', 'partizip-ii'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'essen → ___',
      acceptedAnswers: ['gegessen'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...en',
      maxLength: 20,
      explanation: 'essen is strong: gegessen must be memorized as a fixed pair with the infinitive.',
    },
    {
      id: 'ch28-ex-16',
      chapterNumber: 28,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['strong-verbs', 'partizip-ii'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'lesen → ___',
      acceptedAnswers: ['gelesen'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...en',
      maxLength: 20,
      explanation: 'lesen is strong: the participle is gelesen.',
    },
    {
      id: 'ch28-ex-17',
      chapterNumber: 28,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['strong-verbs', 'partizip-ii'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'sprechen → ___',
      acceptedAnswers: ['gesprochen'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...en',
      maxLength: 20,
      explanation: 'sprechen is strong; the stem vowel changes from e to o: gesprochen.',
    },
    {
      id: 'ch28-ex-18',
      chapterNumber: 28,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['separable-verbs', 'partizip-ii'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'einkaufen → ___',
      acceptedAnswers: ['eingekauft'],
      answerMode: 'caseInsensitive',
      placeholder: 'ein...t',
      maxLength: 20,
      explanation: 'einkaufen is separable: kaufen becomes gekauft, and the prefix ein- goes in front, giving eingekauft.',
    },
    {
      id: 'ch28-ex-19',
      chapterNumber: 28,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['separable-verbs', 'strong-verbs'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'mitkommen → ___',
      acceptedAnswers: ['mitgekommen'],
      answerMode: 'caseInsensitive',
      placeholder: 'mit...en',
      maxLength: 20,
      explanation: 'kommen is strong (gekommen); with the separable prefix mit-, the ge- moves inside: mitgekommen.',
    },
    {
      id: 'ch28-ex-20',
      chapterNumber: 28,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['inseparable-prefixes', 'partizip-ii'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'erklären → ___',
      acceptedAnswers: ['erklärt'],
      answerMode: 'caseInsensitive',
      placeholder: 'er...t',
      maxLength: 20,
      explanation: 'er- is inseparable and blocks ge-; the participle is erklärt.',
    },
    {
      id: 'ch28-ex-21',
      chapterNumber: 28,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['ieren-verbs', 'sentence-completion'],
      instruction: 'Complete the sentence with the correct past participle. Capitalisation is not checked.',
      prompt: 'Ich habe gestern mit meiner Mutter ___. (telefonieren)',
      acceptedAnswers: ['telefoniert'],
      answerMode: 'caseInsensitive',
      placeholder: 'telefoniert',
      maxLength: 20,
      explanation: '-ieren verbs never take ge- and end in -t: telefoniert.',
    },
    {
      id: 'ch28-ex-22',
      chapterNumber: 28,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['mixed-verbs', 'sentence-completion'],
      instruction: 'Complete the sentence with the correct past participle. Capitalisation is not checked.',
      prompt: 'Ich habe die ganze Zeit an dich ___. (denken)',
      acceptedAnswers: ['gedacht'],
      answerMode: 'caseInsensitive',
      placeholder: 'gedacht',
      maxLength: 20,
      explanation: 'denken is mixed: the weak -t ending combines with a stem-vowel change, giving gedacht.',
    },
    {
      id: 'ch28-ex-23',
      chapterNumber: 28,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['strong-verbs', 'error-correction'],
      instruction: 'This participle has a spelling error. Write the correct form. Capitalisation is not checked.',
      prompt: 'Fehler: gesprecht (sprechen) → richtig: ___',
      acceptedAnswers: ['gesprochen'],
      answerMode: 'caseInsensitive',
      placeholder: 'gesprochen',
      maxLength: 20,
      explanation: 'sprechen is strong and changes its stem vowel to o; the weak-style ending used in "gesprecht" is wrong. The correct form is gesprochen.',
    },
    {
      id: 'ch28-ex-24',
      chapterNumber: 28,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['separable-verbs', 'error-correction'],
      instruction: 'This participle has a spelling error. Write the correct form. Capitalisation is not checked.',
      prompt: 'Fehler: geaufgestanden (aufstehen) → richtig: ___',
      acceptedAnswers: ['aufgestanden'],
      answerMode: 'caseInsensitive',
      placeholder: 'aufgestanden',
      maxLength: 20,
      explanation: 'aufstehen is separable: ge- belongs between the prefix and the base participle (aufgestanden), never in front of the whole word.',
    },
  ],
};
