import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter014: ChapterDefinition = {
  id: 'chapter-014',
  number: 14,
  slug: 'plural-forms-of-nouns',
  title: 'Plural Forms of Nouns',
  germanTitle: 'Pluralformen der Nomen',
  level: 'A1',
  section: 'pronouns-nouns-articles',
  objective:
    'Recognise and form the plural of German nouns using the five plural patterns (-e, -er, -(e)n, -s, no ending, sometimes with an umlaut), and use die as the article for every plural noun.',
  prerequisites: [1],
  estimatedMinutes: 25,
  tags: ['nouns', 'plural', 'umlaut', 'articles', 'die'],
  explanation: {
    introduction: [
      'Every German noun has a singular form and a plural form, and the two are often quite different: der Tisch becomes die Tische, das Kind becomes die Kinder, and die Frau becomes die Frauen. Unlike English, where most plurals simply add -s, German plurals are built with a small set of endings, and sometimes with a change to the stem vowel called an umlaut (a → ä, o → ö, u → ü, au → äu).',
      'The good news is that the article makes plurals simple in one respect: no matter whether a noun is der, die, or das in the singular, its plural article is always die. The harder part is that there is no single rule that tells you in advance which of the plural endings a particular noun will take — plurals have to be learned together with each noun, ideally as part of the vocabulary itself, though some patterns and tendencies do help.',
    ],
    rules: [
      {
        id: 'ch14-rule-01',
        heading: 'The five plural patterns',
        paragraphs: [
          'German nouns form their plural in one of five ways: by adding -e (der Tisch → die Tische), by adding -er (das Kind → die Kinder), by adding -(e)n (die Frau → die Frauen, die Lampe → die Lampen), by adding -s (das Auto → die Autos), or by adding no ending at all (der Lehrer → die Lehrer).',
          'The -(e)n ending is the most common plural for feminine nouns; almost all nouns ending in -e, -heit, -keit, -ung, or -in take -(e)n in the plural.',
          'The -s ending mainly appears with nouns borrowed from other languages, especially English and French, and with nouns ending in a vowel other than -e, such as das Auto, das Hotel, and das Sofa (die Autos, die Hotels, die Sofas).',
          'The no-ending pattern is typical of masculine and neuter nouns that already end in -er, -el, or -en in the singular, such as der Lehrer, der Onkel, and das Fenster — these look identical in the singular and the plural, and only the article die and the sentence context show that they are plural.',
        ],
      },
      {
        id: 'ch14-rule-02',
        heading: 'The umlaut: a, o, u, au → ä, ö, ü, äu',
        paragraphs: [
          'Many nouns that add -e, -er, or no ending also change their stem vowel to an umlaut in the plural: a becomes ä, o becomes ö, u becomes ü, and the diphthong au becomes äu.',
          'Compare der Gast → die Gäste, das Buch → die Bücher, der Fuß → die Füße, and das Haus → die Häuser: the ending changes and the vowel changes at the same time.',
          'The umlaut is not automatic — many nouns with a, o, u, or au keep the vowel unchanged in the plural, for example der Tag → die Tage and der Schuh → die Schuhe. Whether a noun takes an umlaut has to be learned along with its plural ending.',
          'Nouns that take -(e)n or -s in the plural never add an umlaut: die Frau → die Frauen (not "Fräuen"), das Auto → die Autos (not "Äutos").',
        ],
      },
      {
        id: 'ch14-rule-03',
        heading: 'Unchanged plurals',
        paragraphs: [
          'A small but frequent group of masculine and neuter nouns has a plural that looks exactly like the singular: der Lehrer → die Lehrer, der Computer → die Computer, das Fenster → die Fenster, das Mädchen → die Mädchen.',
          'These are nouns that already end in an unstressed -er, -el, or -en (and diminutives in -chen or -lein). Since the word form does not change, the plural article die and the sentence context — for example a plural verb form or a number — are the only signals that the noun is plural.',
          'A few of these nouns do add an umlaut without any other ending, such as der Vater → die Väter and der Garten → die Gärten, so "unchanged" refers to the ending, not necessarily to the vowel.',
        ],
      },
      {
        id: 'ch14-rule-04',
        heading: 'The article die for every plural',
        paragraphs: [
          'In the singular, German nouns are grouped into three genders with three different definite articles: der (masculine), die (feminine), and das (neuter).',
          'In the plural, this distinction disappears completely: every plural noun, regardless of its singular gender, takes the article die. Der Tisch (masculine) becomes die Tische, das Kind (neuter) becomes die Kinder, and die Frau (feminine, already die) becomes die Frauen.',
          'This makes the plural article the easiest part of the plural system: you never need to know a noun\'s gender to choose its plural article, because it is always die.',
        ],
      },
      {
        id: 'ch14-rule-05',
        heading: 'Dictionary notation: how plurals are listed',
        paragraphs: [
          'Because there is no single rule for predicting a noun\'s plural, German dictionaries and vocabulary lists give the plural ending directly after the noun, usually in a shortened form: der Tisch, -e means the plural is Tische; das Kind, -er means the plural is Kinder; die Lampe, -n means the plural is Lampen.',
          'An umlaut in the listed ending is often shown with a small mark before the ending, such as der Gast, ¨-e (plural: Gäste) or das Buch, ¨-er (plural: Bücher); some dictionaries instead simply spell out the whole plural form after a comma, e.g. der Gast, die Gäste.',
          'When a noun has no ending in the plural, dictionaries mark this with a dash or with the umlaut symbol alone, e.g. der Lehrer, - (plural: Lehrer, unchanged) or der Vater, ¨- (plural: Väter, umlaut only).',
          'Learning to read this notation is a practical study habit: whenever you learn a new noun, learn its plural form (or its dictionary abbreviation) at the same time, the way you would learn an irregular verb form.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch14-table-01',
        title: 'Plural endings overview',
        columns: ['Ending', 'Example (singular)', 'Plural', 'Typical nouns'],
        rows: [
          ['-e (often + umlaut)', 'der Tisch', 'die Tische', 'many masculine nouns'],
          ['-er (often + umlaut)', 'das Kind', 'die Kinder', 'many neuter nouns'],
          ['-(e)n (no umlaut)', 'die Lampe', 'die Lampen', 'most feminine nouns'],
          ['-s (no umlaut)', 'das Auto', 'die Autos', 'loanwords, vowel endings'],
          ['no ending (sometimes + umlaut)', 'der Lehrer', 'die Lehrer', 'nouns already in -er, -el, -en'],
        ],
        note: 'The umlaut, where it occurs, always appears together with one of these endings (or with no ending at all) — it is never a plural pattern by itself.',
      },
      {
        id: 'ch14-table-02',
        title: 'Dictionary abbreviations for plurals',
        columns: ['Dictionary entry', 'Meaning', 'Full plural'],
        rows: [
          ['der Tisch, -e', 'add -e, no umlaut', 'die Tische'],
          ['der Gast, ¨-e', 'add -e, with umlaut', 'die Gäste'],
          ['das Kind, -er', 'add -er, no umlaut', 'die Kinder'],
          ['das Buch, ¨-er', 'add -er, with umlaut', 'die Bücher'],
          ['die Lampe, -n', 'add -n', 'die Lampen'],
          ['der Lehrer, -', 'no ending at all', 'die Lehrer'],
          ['der Vater, ¨-', 'no ending, but umlaut', 'die Väter'],
        ],
      },
    ],
    examples: [
      {
        german: 'der Tisch → die Tische',
        english: 'the table → the tables',
        highlight: ['die Tische'],
        explanation: 'A masculine noun adding -e, with no umlaut.',
      },
      {
        german: 'der Gast → die Gäste',
        english: 'the guest → the guests',
        highlight: ['die Gäste'],
        explanation: 'A masculine noun adding -e together with an umlaut: a → ä.',
      },
      {
        german: 'das Kind → die Kinder',
        english: 'the child → the children',
        highlight: ['die Kinder'],
        explanation: 'A neuter noun adding -er, with no umlaut.',
      },
      {
        german: 'das Buch → die Bücher',
        english: 'the book → the books',
        highlight: ['die Bücher'],
        explanation: 'A neuter noun adding -er together with an umlaut: u → ü.',
      },
      {
        german: 'die Frau → die Frauen',
        english: 'the woman → the women',
        highlight: ['die Frauen'],
        explanation: 'A feminine noun adding -en; nouns with -(e)n never take an umlaut.',
      },
      {
        german: 'die Lampe → die Lampen',
        english: 'the lamp → the lamps',
        highlight: ['die Lampen'],
        explanation: 'A feminine noun ending in -e simply adds -n.',
      },
      {
        german: 'das Hotel → die Hotels',
        english: 'the hotel → the hotels',
        highlight: ['die Hotels'],
        explanation: 'A loanword taking the -s plural, with no umlaut.',
      },
      {
        german: 'der Lehrer → die Lehrer',
        english: 'the teacher → the teachers',
        highlight: ['die Lehrer'],
        explanation: 'A masculine noun ending in -er stays unchanged in the plural.',
      },
      {
        german: 'der Vater → die Väter',
        english: 'the father → the fathers',
        highlight: ['die Väter'],
        explanation: 'No ending is added, but the stem vowel still changes: a → ä.',
      },
      {
        german: 'das Haus → die Häuser',
        english: 'the house → the houses',
        highlight: ['die Häuser'],
        explanation: 'A neuter noun adding -er with the diphthong change au → äu.',
      },
      {
        german: 'Die Kinder spielen im Garten.',
        english: 'The children are playing in the garden.',
        highlight: ['Die Kinder'],
        explanation: 'Even though Kind is neuter (das Kind), the plural article is die.',
      },
      {
        german: 'Die Tische in diesem Café sind sehr klein.',
        english: 'The tables in this café are very small.',
        highlight: ['Die Tische'],
        explanation: 'Even though Tisch is masculine (der Tisch), the plural article is die.',
      },
      {
        german: 'Im Wörterbuch steht: der Stuhl, ¨-e.',
        english: 'In the dictionary it says: der Stuhl, ¨-e.',
        explanation: 'This dictionary notation tells you the plural is die Stühle: add -e and change u to ü.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'der Tische',
        correct: 'die Tische',
        explanation:
          'Every plural noun takes the article die, regardless of the singular gender of the noun (der Tisch is masculine, but its plural is die Tische).',
      },
      {
        incorrect: 'die Frauen → die Fräuen',
        correct: 'die Frau → die Frauen',
        explanation:
          'Nouns that take the -(e)n plural ending never add an umlaut; the vowel of Frau stays unchanged in Frauen.',
      },
      {
        incorrect: 'das Kind → die Kinden',
        correct: 'das Kind → die Kinder',
        explanation: 'Kind belongs to the -er group, not the -(e)n group, so its plural is Kinder, not Kinden.',
      },
      {
        incorrect: 'der Lehrer → die Lehrere',
        correct: 'der Lehrer → die Lehrer',
        explanation:
          'Nouns already ending in -er, -el, or -en usually take no plural ending at all; adding -e to Lehrer is incorrect.',
      },
      {
        incorrect: 'das Auto → die Autoen',
        correct: 'das Auto → die Autos',
        explanation: 'Loanwords like Auto typically take the -s plural, not -(e)n.',
      },
      {
        incorrect: 'der Vater → die Vater',
        correct: 'der Vater → die Väter',
        explanation:
          'Vater takes no plural ending, but it does take an umlaut, so the plural vowel changes from a to ä even though no letters are added.',
      },
    ],
    remember: [
      'German plurals are formed with one of five patterns: -e, -er, -(e)n, -s, or no ending — sometimes combined with an umlaut (a → ä, o → ö, u → ü, au → äu).',
      'The -(e)n and -s plurals never take an umlaut; only the -e, -er, and no-ending patterns can.',
      'Every plural noun uses the article die, no matter what article the singular noun has.',
      'There is no single rule that predicts a noun\'s plural ending — learn each noun\'s plural (or its dictionary abbreviation, e.g. der Tisch, -e) together with the noun itself.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch14-ex-01',
      chapterNumber: 14,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural', 'article-die'],
      instruction: 'Choose the correct plural article for the German noun in bold.',
      prompt: 'Was ist der richtige Artikel für den Plural von "Tisch" (Tische)?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
        { id: 'd', text: 'den' },
      ],
      correctOptionId: 'b',
      explanation:
        'Every plural noun takes the article die, no matter what gender the singular noun has.',
    },
    {
      id: 'ch14-ex-02',
      chapterNumber: 14,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural', 'article-die'],
      instruction: 'Choose the correct plural article.',
      prompt: 'Was ist der richtige Artikel für den Plural von "Kind" (Kinder)?',
      options: [
        { id: 'a', text: 'das' },
        { id: 'b', text: 'der' },
        { id: 'c', text: 'die' },
      ],
      correctOptionId: 'c',
      explanation:
        'Although das Kind is neuter in the singular, its plural die Kinder always takes the article die.',
    },
    {
      id: 'ch14-ex-03',
      chapterNumber: 14,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural-endings'],
      instruction: 'Choose the correct plural form.',
      prompt: 'der Tisch → ?',
      options: [
        { id: 'a', text: 'die Tischer' },
        { id: 'b', text: 'die Tische' },
        { id: 'c', text: 'die Tischen' },
        { id: 'd', text: 'die Tischs' },
      ],
      correctOptionId: 'b',
      explanation: 'Tisch is a masculine noun that forms its plural by adding -e: die Tische.',
    },
    {
      id: 'ch14-ex-04',
      chapterNumber: 14,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural-endings'],
      instruction: 'Choose the correct plural form.',
      prompt: 'das Kind → ?',
      options: [
        { id: 'a', text: 'die Kinde' },
        { id: 'b', text: 'die Kinden' },
        { id: 'c', text: 'die Kinder' },
        { id: 'd', text: 'die Kinds' },
      ],
      correctOptionId: 'c',
      explanation: 'Kind forms its plural by adding -er: die Kinder.',
    },
    {
      id: 'ch14-ex-05',
      chapterNumber: 14,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural-endings'],
      instruction: 'Choose the correct plural form.',
      prompt: 'die Frau → ?',
      options: [
        { id: 'a', text: 'die Fraue' },
        { id: 'b', text: 'die Frauen' },
        { id: 'c', text: 'die Fräuen' },
        { id: 'd', text: 'die Fraus' },
      ],
      correctOptionId: 'b',
      explanation: 'Frau is feminine and forms its plural by adding -en, with no umlaut: die Frauen.',
    },
    {
      id: 'ch14-ex-06',
      chapterNumber: 14,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural-endings', 's-plural'],
      instruction: 'Choose the correct plural form.',
      prompt: 'das Auto → ?',
      options: [
        { id: 'a', text: 'die Autos' },
        { id: 'b', text: 'die Autoen' },
        { id: 'c', text: 'die Autos e' },
        { id: 'd', text: 'die Autoer' },
      ],
      correctOptionId: 'a',
      explanation: 'Loanwords ending in a vowel like Auto typically take the -s plural: die Autos.',
    },
    {
      id: 'ch14-ex-07',
      chapterNumber: 14,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural-endings', 'unchanged-plural'],
      instruction: 'Choose the correct plural form.',
      prompt: 'der Lehrer → ?',
      options: [
        { id: 'a', text: 'die Lehrere' },
        { id: 'b', text: 'die Lehrern' },
        { id: 'c', text: 'die Lehrer' },
        { id: 'd', text: 'die Lehrers' },
      ],
      correctOptionId: 'c',
      explanation:
        'Nouns already ending in -er, like Lehrer, usually take no plural ending: die Lehrer.',
    },
    {
      id: 'ch14-ex-08',
      chapterNumber: 14,
      order: 8,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['plural-endings', 'umlaut'],
      instruction: 'Choose the correct plural form.',
      prompt: 'der Vater → ?',
      options: [
        { id: 'a', text: 'die Vater' },
        { id: 'b', text: 'die Vaters' },
        { id: 'c', text: 'die Väter' },
        { id: 'd', text: 'die Vaterer' },
      ],
      correctOptionId: 'c',
      explanation: 'Vater takes no plural ending, but its stem vowel changes: a becomes ä, giving die Väter.',
    },
    {
      id: 'ch14-ex-09',
      chapterNumber: 14,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'umlaut'],
      instruction: 'Choose the correct plural form.',
      prompt: 'das Buch → ?',
      options: [
        { id: 'a', text: 'die Buche' },
        { id: 'b', text: 'die Bucher' },
        { id: 'c', text: 'die Bücher' },
        { id: 'd', text: 'die Büche' },
      ],
      correctOptionId: 'c',
      explanation: 'Buch adds -er and changes u to ü: die Bücher.',
    },
    {
      id: 'ch14-ex-10',
      chapterNumber: 14,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'umlaut'],
      instruction: 'Choose the correct plural form.',
      prompt: 'das Haus → ?',
      options: [
        { id: 'a', text: 'die Hause' },
        { id: 'b', text: 'die Häuser' },
        { id: 'c', text: 'die Hauser' },
        { id: 'd', text: 'die Häusen' },
      ],
      correctOptionId: 'b',
      explanation: 'Haus adds -er and changes the diphthong au to äu: die Häuser.',
    },
    {
      id: 'ch14-ex-11',
      chapterNumber: 14,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'identify-ending'],
      instruction: 'Which plural ending was used to form this plural noun?',
      prompt: 'die Lampen (from: die Lampe)',
      options: [
        { id: 'a', text: '-e' },
        { id: 'b', text: '-er' },
        { id: 'c', text: '-(e)n' },
        { id: 'd', text: '-s' },
      ],
      correctOptionId: 'c',
      explanation: 'Lampe adds -n to form Lampen, an example of the -(e)n plural ending.',
    },
    {
      id: 'ch14-ex-12',
      chapterNumber: 14,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'identify-ending'],
      instruction: 'Which plural ending was used to form this plural noun?',
      prompt: 'die Hotels (from: das Hotel)',
      options: [
        { id: 'a', text: '-e' },
        { id: 'b', text: '-er' },
        { id: 'c', text: '-(e)n' },
        { id: 'd', text: '-s' },
      ],
      correctOptionId: 'd',
      explanation: 'Hotel is a loanword that adds -s to form Hotels.',
    },
    {
      id: 'ch14-ex-13',
      chapterNumber: 14,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'identify-ending', 'no-ending'],
      instruction: 'Which plural ending was used to form this plural noun?',
      prompt: 'die Mädchen (from: das Mädchen)',
      options: [
        { id: 'a', text: '-e' },
        { id: 'b', text: 'no ending' },
        { id: 'c', text: '-(e)n' },
        { id: 'd', text: '-s' },
      ],
      correctOptionId: 'b',
      explanation: 'Mädchen already ends in -chen, so it takes no additional plural ending.',
    },
    {
      id: 'ch14-ex-14',
      chapterNumber: 14,
      order: 14,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'spot-the-error'],
      instruction: 'One of these plural forms is incorrect. Which one?',
      prompt: 'Welche Pluralform ist falsch?',
      options: [
        { id: 'a', text: 'die Bücher' },
        { id: 'b', text: 'die Kinder' },
        { id: 'c', text: 'die Fräuen' },
        { id: 'd', text: 'die Häuser' },
      ],
      correctOptionId: 'c',
      explanation:
        'The -(e)n plural never takes an umlaut, so "Fräuen" is wrong; the correct plural of Frau is Frauen.',
    },
    {
      id: 'ch14-ex-15',
      chapterNumber: 14,
      order: 15,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'spot-the-error'],
      instruction: 'One of these plural forms is incorrect. Which one?',
      prompt: 'Welche Pluralform ist falsch?',
      options: [
        { id: 'a', text: 'die Autos' },
        { id: 'b', text: 'die Lehrere' },
        { id: 'c', text: 'die Lampen' },
        { id: 'd', text: 'die Tische' },
      ],
      correctOptionId: 'b',
      explanation:
        'Nouns already ending in -er, like Lehrer, take no plural ending, so "Lehrere" is wrong; the correct plural is Lehrer.',
    },
    {
      id: 'ch14-ex-16',
      chapterNumber: 14,
      order: 16,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural', 'article-die', 'sentence-context'],
      instruction: 'Choose the correct article to complete the sentence.',
      prompt: '___ Bücher liegen auf dem Tisch.',
      options: [
        { id: 'a', text: 'Der' },
        { id: 'b', text: 'Das' },
        { id: 'c', text: 'Die' },
        { id: 'd', text: 'Den' },
      ],
      correctOptionId: 'c',
      explanation: 'Bücher is a plural noun, and every plural noun takes the article die.',
    },
    {
      id: 'ch14-ex-17',
      chapterNumber: 14,
      order: 17,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural', 'article-die', 'sentence-context'],
      instruction: 'Choose the correct article to complete the sentence.',
      prompt: '___ Häuser in dieser Straße sind sehr alt.',
      options: [
        { id: 'a', text: 'Das' },
        { id: 'b', text: 'Die' },
        { id: 'c', text: 'Der' },
      ],
      correctOptionId: 'b',
      explanation: 'Häuser is the plural of das Haus, but the plural article is always die.',
    },
    {
      id: 'ch14-ex-18',
      chapterNumber: 14,
      order: 18,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dictionary-notation'],
      instruction: 'This dictionary entry shows a noun with its plural notation. What is the correct plural?',
      prompt: 'der Stuhl, ¨-e → ?',
      options: [
        { id: 'a', text: 'die Stuhle' },
        { id: 'b', text: 'die Stühle' },
        { id: 'c', text: 'die Stühler' },
        { id: 'd', text: 'die Stuhlen' },
      ],
      correctOptionId: 'b',
      explanation:
        'The notation ¨-e means: add -e and change the stem vowel with an umlaut, so u becomes ü: die Stühle.',
    },
    {
      id: 'ch14-ex-19',
      chapterNumber: 14,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['plural-endings'],
      instruction: 'Write the plural form of the noun. Capitalisation is not checked.',
      prompt: 'der Tisch → ___',
      acceptedAnswers: ['Tische', 'die Tische'],
      answerMode: 'caseInsensitive',
      placeholder: 'plural form',
      maxLength: 20,
      explanation: 'Tisch forms its plural by adding -e: Tische.',
    },
    {
      id: 'ch14-ex-20',
      chapterNumber: 14,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['plural-endings'],
      instruction: 'Write the plural form of the noun. Capitalisation is not checked.',
      prompt: 'das Kind → ___',
      acceptedAnswers: ['Kinder', 'die Kinder'],
      answerMode: 'caseInsensitive',
      placeholder: 'plural form',
      maxLength: 20,
      explanation: 'Kind forms its plural by adding -er: Kinder.',
    },
    {
      id: 'ch14-ex-21',
      chapterNumber: 14,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['plural-endings'],
      instruction: 'Write the plural form of the noun. Capitalisation is not checked.',
      prompt: 'die Frau → ___',
      acceptedAnswers: ['Frauen', 'die Frauen'],
      answerMode: 'caseInsensitive',
      placeholder: 'plural form',
      maxLength: 20,
      explanation: 'Frau forms its plural by adding -en, with no umlaut: Frauen.',
    },
    {
      id: 'ch14-ex-22',
      chapterNumber: 14,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'umlaut'],
      instruction: 'Write the plural form of the noun. Capitalisation is not checked.',
      prompt: 'der Gast → ___',
      acceptedAnswers: ['Gäste', 'die Gäste'],
      answerMode: 'caseInsensitive',
      placeholder: 'plural form',
      maxLength: 20,
      explanation: 'Gast adds -e together with an umlaut: a becomes ä, giving Gäste.',
    },
    {
      id: 'ch14-ex-23',
      chapterNumber: 14,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['plural-endings', 'unchanged-plural'],
      instruction: 'Write the plural form of the noun. Capitalisation is not checked.',
      prompt: 'der Onkel → ___',
      acceptedAnswers: ['Onkel', 'die Onkel'],
      answerMode: 'caseInsensitive',
      placeholder: 'plural form',
      maxLength: 20,
      explanation: 'Onkel already ends in -el, so it takes no plural ending; the plural is Onkel, unchanged.',
    },
    {
      id: 'ch14-ex-24',
      chapterNumber: 14,
      order: 24,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['plural-endings', 's-plural'],
      instruction: 'Write the plural form of the noun. Capitalisation is not checked.',
      prompt: 'das Sofa → ___',
      acceptedAnswers: ['Sofas', 'die Sofas'],
      answerMode: 'caseInsensitive',
      placeholder: 'plural form',
      maxLength: 20,
      explanation: 'Sofa ends in a vowel and forms its plural with -s: Sofas.',
    },
    {
      id: 'ch14-ex-25',
      chapterNumber: 14,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['plural-endings', 'umlaut'],
      instruction: 'Write the plural form of the noun. Capitalisation is not checked.',
      prompt: 'das Land → ___',
      acceptedAnswers: ['Länder', 'die Länder'],
      answerMode: 'caseInsensitive',
      placeholder: 'plural form',
      maxLength: 20,
      explanation: 'Land adds -er together with an umlaut: a becomes ä, giving Länder.',
    },
    {
      id: 'ch14-ex-26',
      chapterNumber: 14,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['plural', 'article-die', 'sentence-writing'],
      instruction:
        'Complete the sentence with the correct plural article and the plural of the noun in brackets. Capitalisation and punctuation are checked.',
      prompt: '___ ___ sind heute im Park. (das Kind)',
      acceptedAnswers: ['Die Kinder sind heute im Park.'],
      answerMode: 'normalized',
      placeholder: 'Die ...',
      maxLength: 50,
      explanation:
        'Kind forms its plural as Kinder, and every plural noun takes the article die: Die Kinder sind heute im Park.',
    },
    {
      id: 'ch14-ex-27',
      chapterNumber: 14,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['plural', 'article-die', 'sentence-writing'],
      instruction:
        'Complete the sentence with the correct plural article and the plural of the noun in brackets. Capitalisation and punctuation are checked.',
      prompt: '___ ___ in diesem Haus sind sehr modern. (der Tisch)',
      acceptedAnswers: ['Die Tische in diesem Haus sind sehr modern.'],
      answerMode: 'normalized',
      placeholder: 'Die ...',
      maxLength: 60,
      explanation:
        'Tisch forms its plural as Tische, and the plural article is die regardless of the singular gender: Die Tische in diesem Haus sind sehr modern.',
    },
    {
      id: 'ch14-ex-28',
      chapterNumber: 14,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['plural', 'article-die', 'sentence-writing'],
      instruction:
        'Write a complete German sentence using the plural of the given noun and the correct plural article. Capitalisation and punctuation are checked.',
      prompt: 'Write: "The books are on the table." (das Buch – auf dem Tisch)',
      acceptedAnswers: ['Die Bücher sind auf dem Tisch.'],
      answerMode: 'normalized',
      placeholder: 'Die ...',
      maxLength: 50,
      explanation:
        'Buch forms its plural as Bücher (adding -er and an umlaut), and the plural article is die: Die Bücher sind auf dem Tisch.',
    },
    {
      id: 'ch14-ex-29',
      chapterNumber: 14,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['plural', 'article-die', 'sentence-writing'],
      instruction:
        'Write a complete German sentence using the plural of the given noun and the correct plural article. Capitalisation and punctuation are checked.',
      prompt: 'Write: "The houses are very old." (das Haus – sehr alt)',
      acceptedAnswers: ['Die Häuser sind sehr alt.'],
      answerMode: 'normalized',
      placeholder: 'Die ...',
      maxLength: 40,
      explanation:
        'Haus forms its plural as Häuser (adding -er and changing au to äu), and the plural article is die: Die Häuser sind sehr alt.',
    },
    {
      id: 'ch14-ex-30',
      chapterNumber: 14,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['plural', 'article-die', 'sentence-writing'],
      instruction:
        'Write a complete German sentence using the plural of the given noun and the correct plural article. Capitalisation and punctuation are checked.',
      prompt: 'Write: "The teachers are in the room." (der Lehrer – im Zimmer)',
      acceptedAnswers: ['Die Lehrer sind im Zimmer.'],
      answerMode: 'normalized',
      placeholder: 'Die ...',
      maxLength: 40,
      explanation:
        'Lehrer already ends in -er and takes no plural ending, but the plural article is still die: Die Lehrer sind im Zimmer.',
    },
  ],
};
