import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter077: ChapterDefinition = {
  id: 'chapter-077',
  number: 77,
  slug: 'temporal-clauses-with-wenn-and-als',
  title: 'Temporal Clauses with wenn and als',
  germanTitle: 'Temporalsätze mit wenn und als',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Choose correctly between wenn and als for temporal clauses — als for a single, unrepeated event or period in the past, wenn for everything else, including repeated past events, present habits, future events, and conditions — while keeping the finite verb at the end of the subordinate clause and applying inversion correctly when that clause comes first.',
  prerequisites: [30, 46],
  estimatedMinutes: 30,
  tags: [
    'wenn',
    'als',
    'temporal-clauses',
    'subordinate-clauses',
    'verb-final-word-order',
    'past-tense',
    'connectors',
    'clause-order',
    'nebensatz',
  ],
  explanation: {
    introduction: [
      'Chapter 46 introduced wenn as a subordinating conjunction meaning both "if" (a condition) and "when(ever)" (a repeated or future point in time). This chapter zooms in on that second, temporal meaning of wenn and puts it side by side with a connector that looks similar but works very differently: als. Both wenn and als can be translated "when" in English, and both send the finite verb to the end of their clause, but German speakers do not choose between them freely — the choice depends entirely on whether the event being described happened once, in the past, or not.',
      'The decisive question is always the same: is this a single, unrepeated event or period that took place in the past? If the answer is yes, German uses als — Als ich acht Jahre alt war, zogen wir nach Hamburg. (When I was eight, we moved to Hamburg — that childhood age happened exactly once.) For every other case — a habit repeated any number of times, even entirely in the past, a present situation, a future event, or a general condition — German uses wenn: Immer wenn er kam, freute sich der Hund. (Whenever he came, the dog was happy — this happened over and over, so wenn is required even though it is all in the past.)',
      'This single-event-versus-everything-else rule trips up learners because English "when" does not draw this line at all, and because it is tempting to assume "als = past" and "wenn = present/future." That shortcut fails for repeated past actions, which are extremely common (childhood habits, routines, "every time X happened"). The rest of this chapter works through the rule in detail, reviews the familiar verb-final and clause-order patterns from Chapter 46, and briefly notes — without re-teaching it — that wenn can also mean "if," a meaning that context, not grammar, resolves.',
    ],
    rules: [
      {
        id: 'ch77-rule-01',
        heading:
          'The core decision: als for one single past event, wenn for everything else',
        paragraphs: [
          'als is used exclusively for a single, unrepeated event or stretch of time that took place in the past. It does not matter whether that event was an instant (Als es klingelte, ... — when the doorbell rang) or an extended period (Als ich in München wohnte, ... — when I lived in Munich); what matters is that it happened once, not repeatedly.',
          'wenn covers every other situation: repeated events (in the past, present, or future), habitual or general statements, single events in the present or future, and conditions. In short: als is the narrow, one-time-past specialist; wenn is the flexible default that handles everything else, including repetition inside the past.',
        ],
      },
      {
        id: 'ch77-rule-02',
        heading: 'wenn — repeated events, even entirely in the past',
        paragraphs: [
          'When an action happened more than once — signalled by words like immer (always), jedes Mal (every time), oft (often), or jeden Tag (every day) — wenn is required, even if every single occurrence lies in the past. This is the case learners most often get wrong, because it feels like "the past" should automatically mean als.',
          'Immer wenn er kam, freute sich der Hund. Jedes Mal, wenn es regnete, blieben wir zu Hause. Wenn wir Kinder waren, spielten wir jeden Tag draußen. In all three sentences, the events are past but repeated, so wenn — not als — is correct.',
        ],
      },
      {
        id: 'ch77-rule-03',
        heading: 'wenn — present and future events',
        paragraphs: [
          'wenn also introduces temporal clauses about the present (habitual or ongoing situations) and the future (a single upcoming event). als never appears in these contexts, because als is reserved exclusively for the past.',
          'Wenn ich Zeit habe, gehe ich schwimmen. (present habit) Wenn ich in Berlin ankomme, rufe ich dich an. (a single future event — still wenn, because it has not happened yet).',
        ],
      },
      {
        id: 'ch77-rule-04',
        heading: 'als — a single, unrepeated event or period in the past',
        paragraphs: [
          'als introduces exactly one occurrence in the past: a specific moment (Als es klingelte, öffnete sie die Tür), a specific past experience (Als ich die Prüfung bestanden hatte, war ich glücklich), or an entire but singular life period (Als ich in München wohnte, habe ich oft im Park gejoggt).',
          'That last example shows an important subtlety: the period itself ("living in Munich") only happened once, even though an activity inside it (jogging) happened repeatedly. The connector tracks the outer, defining event — the one-time period — not the frequency of what happened during it.',
        ],
      },
      {
        id: 'ch77-rule-05',
        heading: 'Verb-final order in the subordinate clause',
        paragraphs: [
          'Like weil, wenn, and dass in Chapter 46, als is a subordinating conjunction: it pushes the finite verb of its clause all the way to the end. This holds for every tense — present, Präteritum, Perfekt, or Plusquamperfekt — and for modal verbs and separable verbs, exactly as you already practiced with weil and dass.',
          'Als ich acht Jahre alt war, ... (war at the end) Als ich die Prüfung bestanden hatte, ... (the auxiliary hatte at the very end, after the participle bestanden).',
        ],
      },
      {
        id: 'ch77-rule-06',
        heading: 'Clause order and inversion; wenn can still mean "if"',
        paragraphs: [
          "As with any subordinate clause, the wenn- or als-clause can come first or second, and a comma always separates the two clauses. When the subordinate clause opens the sentence, it occupies position 1 by itself, so the main clause's finite verb must follow immediately after the comma, before its own subject: Als ich acht Jahre alt war, zogen wir nach Hamburg. (zogen right after the comma, subject wir after that).",
          'Finally, remember that wenn has not stopped meaning "if" — Chapter 46 covered that conditional use, and it has not gone away. Wenn es regnet, bleibe ich zu Hause could mean "if it rains" (a condition) or "whenever it rains" (a repeated time); only the surrounding context tells you which. This chapter does not re-teach the conditional use — it simply asks you to keep it in mind so you are not surprised to see wenn outside of strictly temporal sentences.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch77-table-01',
        title: 'Deciding between wenn and als',
        columns: ['Type of event', 'Connector', 'Example'],
        rows: [
          [
            'Single event or period in the past (once)',
            'als',
            'Als ich acht Jahre alt war, zogen wir nach Hamburg.',
          ],
          [
            'Repeated event in the past (immer, jedes Mal, jeden Tag)',
            'wenn',
            'Immer wenn er kam, freute sich der Hund.',
          ],
          [
            'Habitual or general situation in the present',
            'wenn',
            'Wenn ich Zeit habe, gehe ich schwimmen.',
          ],
          [
            'A single event in the future',
            'wenn',
            'Wenn ich in Berlin ankomme, rufe ich dich an.',
          ],
          [
            'A condition ("if"), any time',
            'wenn',
            'Wenn es regnet, bleibe ich zu Hause.',
          ],
        ],
        note: 'als is reserved exclusively for a single, unrepeated stretch of time in the past; wenn covers every other case, including events that repeat entirely within the past.',
      },
      {
        id: 'ch77-table-02',
        title: 'Clause order: subordinate clause first or second',
        columns: [
          'Main clause first (neutral order)',
          'Subordinate clause first (inversion)',
        ],
        rows: [
          [
            'Ich rufe dich an, wenn ich in Berlin ankomme.',
            'Wenn ich in Berlin ankomme, rufe ich dich an.',
          ],
          [
            'Wir zogen nach Hamburg, als ich acht Jahre alt war.',
            'Als ich acht Jahre alt war, zogen wir nach Hamburg.',
          ],
          [
            'Der Hund freute sich, immer wenn er kam.',
            'Immer wenn er kam, freute sich der Hund.',
          ],
        ],
        note: 'Whichever clause comes first, the finite verb of the main clause occupies position 2 of the whole sentence — right after the comma when the subordinate clause leads.',
      },
    ],
    examples: [
      {
        german: 'Wenn ich Zeit habe, gehe ich schwimmen.',
        english: 'When(ever) I have time, I go swimming.',
        highlight: ['Wenn ich Zeit habe'],
        explanation: 'A general, habitual situation in the present uses wenn.',
      },
      {
        german: 'Immer wenn er kam, freute sich der Hund.',
        english: 'Whenever he came, the dog was happy.',
        highlight: ['Immer wenn er kam'],
        explanation:
          'A repeated event, even though it lies entirely in the past, still requires wenn, not als.',
      },
      {
        german: 'Wenn ich in Berlin ankomme, rufe ich dich an.',
        english: "When I arrive in Berlin, I'll call you.",
        highlight: ['Wenn ich in Berlin ankomme'],
        explanation:
          'A single future event still takes wenn; als is reserved for the past.',
      },
      {
        german: 'Als ich acht Jahre alt war, zogen wir nach Hamburg.',
        english: 'When I was eight years old, we moved to Hamburg.',
        highlight: ['Als ich acht Jahre alt war'],
        explanation:
          'Being eight years old happened once, so this single past period takes als.',
      },
      {
        german: 'Als es klingelte, öffnete sie die Tür.',
        english: 'When the doorbell rang, she opened the door.',
        highlight: ['Als es klingelte'],
        explanation:
          'A single, one-time moment in the past — even a very short one — takes als.',
      },
      {
        german: 'Als ich in München wohnte, habe ich oft im Park gejoggt.',
        english: 'When I lived in Munich, I often jogged in the park.',
        highlight: ['Als ich in München wohnte'],
        explanation:
          'als marks the one, unrepeated period of living in Munich, even though the jogging inside it happened repeatedly.',
      },
      {
        german: 'Jedes Mal, wenn es regnete, blieben wir zu Hause.',
        english: 'Every time it rained, we stayed home.',
        highlight: ['Jedes Mal, wenn es regnete'],
        explanation:
          'jedes Mal signals repetition, so wenn is required even though every occurrence is in the past.',
      },
      {
        german: 'Wenn es regnet, bleibe ich zu Hause.',
        english: 'If it rains, I stay home. / Whenever it rains, I stay home.',
        explanation:
          'Out of context, wenn can mean either "if" (a condition) or "whenever" (a repeated time); context decides which.',
      },
      {
        german: 'Als der Film zu Ende war, gingen wir essen.',
        english: 'When the film was over, we went to eat.',
        highlight: ['Als der Film zu Ende war'],
        explanation: 'als introduces the single past moment the film ended.',
      },
      {
        german: 'Wenn das Wetter schön ist, machen wir einen Ausflug.',
        english: 'When the weather is nice, we go on a trip.',
        highlight: ['machen wir'],
        explanation:
          'The wenn-clause fills position 1, so the main-clause verb machen follows immediately after the comma.',
      },
      {
        german: 'Als ich jung war, spielte ich oft Fußball.',
        english: 'When I was young, I often played football.',
        highlight: ['spielte ich'],
        explanation:
          'The als-clause fills position 1, so the verb spielte comes immediately after the comma, before its subject ich.',
      },
      {
        german: 'Als ich die Prüfung bestanden hatte, war ich sehr glücklich.',
        english: 'When I had passed the exam, I was very happy.',
        highlight: ['bestanden hatte'],
        explanation:
          'als works with any past tense, here the Plusquamperfekt; the auxiliary hatte still moves to the very end of the clause.',
      },
      {
        german: 'Wenn ich mehr Geld verdiene, kaufe ich ein neues Auto.',
        english: "When I earn more money, I'll buy a new car.",
        highlight: ['Wenn ich mehr Geld verdiene'],
        explanation: 'A future plan, even a single one, is introduced with wenn.',
      },
      {
        german: 'Wenn wir Kinder waren, spielten wir jeden Tag draußen.',
        english: 'When we were children, we played outside every day.',
        highlight: ['jeden Tag'],
        explanation:
          'A repeated childhood habit uses wenn, not als, despite being entirely in the past — the classic trap for learners.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Als ich Zeit habe, gehe ich schwimmen.',
        correct: 'Wenn ich Zeit habe, gehe ich schwimmen.',
        explanation:
          'als is only ever used for the past; a present habitual action needs wenn.',
      },
      {
        incorrect: 'Wenn ich acht Jahre alt war, zogen wir nach Hamburg.',
        correct: 'Als ich acht Jahre alt war, zogen wir nach Hamburg.',
        explanation: 'A single, one-time past event or period takes als, not wenn.',
      },
      {
        incorrect: 'Als wir Kinder waren, spielten wir jeden Tag draußen.',
        correct: 'Wenn wir Kinder waren, spielten wir jeden Tag draußen.',
        explanation:
          'Repeated childhood actions (jeden Tag) use wenn even though they are entirely in the past; als is reserved for single events.',
      },
      {
        incorrect: 'Als es klingelte, sie öffnete die Tür.',
        correct: 'Als es klingelte, öffnete sie die Tür.',
        explanation:
          'When the subordinate clause comes first, the main-clause verb must come immediately after the comma, before its subject.',
      },
      {
        incorrect: 'Als ich war acht Jahre alt, zogen wir nach Hamburg.',
        correct: 'Als ich acht Jahre alt war, zogen wir nach Hamburg.',
        explanation:
          'als sends the finite verb to the very end of its clause; war belongs after acht Jahre alt, not right after the subject.',
      },
    ],
    remember: [
      'als = one single, unrepeated event or period in the past; wenn = everything else (present, future, and any repetition — even repetition entirely in the past).',
      'A repeated past action (immer, jedes Mal, jeden Tag) still takes wenn, not als — this is the case learners get wrong most often.',
      'wenn also means "if" (a condition); context, not grammar, tells you whether a given wenn-clause is temporal or conditional.',
      'Both als and wenn push the finite verb to the end of their clause, exactly like weil and dass.',
      'A comma always separates the two clauses, whichever order they come in.',
      "When the als- or wenn-clause opens the sentence, the main clause's verb comes immediately after the comma, before its subject.",
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 96,
    requiredCorrectTextInputs: 23,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch77-ex-01',
      chapterNumber: 77,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Choose the connector that fits.',
      prompt:
        '___ ich acht Jahre alt war, zogen wir nach Hamburg. (a single event in the past)',
      options: [
        { id: 'a', text: 'als' },
        { id: 'b', text: 'wenn' },
        { id: 'c', text: 'dass' },
        { id: 'd', text: 'weil' },
      ],
      correctOptionId: 'a',
      explanation:
        'als introduces a single, unrepeated event or period in the past — here, being eight years old happened only once.',
    },
    {
      id: 'ch77-ex-02',
      chapterNumber: 77,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'repeated-past'],
      instruction: 'Choose the connector that fits.',
      prompt:
        'Immer ___ er nach Hause kam, freute sich der Hund. (a repeated event in the past)',
      options: [
        { id: 'a', text: 'als' },
        { id: 'b', text: 'wenn' },
        { id: 'c', text: 'ob' },
        { id: 'd', text: 'dass' },
      ],
      correctOptionId: 'b',
      explanation:
        'Even though this is in the past, the event repeats (immer), so wenn is required, not als.',
    },
    {
      id: 'ch77-ex-03',
      chapterNumber: 77,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction: 'Choose the connector that fits.',
      prompt: '___ ich Zeit habe, gehe ich schwimmen. (a general habit in the present)',
      options: [
        { id: 'a', text: 'wenn' },
        { id: 'b', text: 'als' },
        { id: 'c', text: 'dass' },
        { id: 'd', text: 'ob' },
      ],
      correctOptionId: 'a',
      explanation: 'wenn covers habitual, general, present-time situations.',
    },
    {
      id: 'ch77-ex-04',
      chapterNumber: 77,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'future'],
      instruction: 'Choose the connector that fits.',
      prompt: '___ ich in Berlin ankomme, rufe ich dich an. (a single future event)',
      options: [
        { id: 'a', text: 'als' },
        { id: 'b', text: 'wenn' },
        { id: 'c', text: 'weil' },
        { id: 'd', text: 'dass' },
      ],
      correctOptionId: 'b',
      explanation:
        'als is only ever used for the past; a future event — even a single one — takes wenn.',
    },
    {
      id: 'ch77-ex-05',
      chapterNumber: 77,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Choose the connector that fits.',
      prompt: '___ es klingelte, öffnete sie die Tür. (a single moment in the past)',
      options: [
        { id: 'a', text: 'wenn' },
        { id: 'b', text: 'als' },
        { id: 'c', text: 'dass' },
        { id: 'd', text: 'ob' },
      ],
      correctOptionId: 'b',
      explanation: 'A single past moment — the doorbell ringing once — takes als.',
    },
    {
      id: 'ch77-ex-06',
      chapterNumber: 77,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'timeline-interpretation', 'repeated-past'],
      instruction:
        'Read the sentence and decide which connector is grammatically required.',
      prompt: 'Jedes Mal, ___ es regnete, blieben wir zu Hause. (jedes Mal = every time)',
      options: [
        { id: 'a', text: 'als' },
        { id: 'b', text: 'wenn' },
        { id: 'c', text: 'dass' },
        { id: 'd', text: 'ob' },
      ],
      correctOptionId: 'b',
      explanation:
        'jedes Mal signals repetition; repeated past events always take wenn, never als, no matter how far in the past they are.',
    },
    {
      id: 'ch77-ex-07',
      chapterNumber: 77,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'timeline-interpretation'],
      instruction: 'Read the sentence and choose the correct interpretation.',
      prompt:
        'Als ich in München wohnte, habe ich oft im Park gejoggt. What does als refer to here?',
      options: [
        {
          id: 'a',
          text: 'The single, continuous period of living in Munich (jogging inside it may have happened many times).',
        },
        { id: 'b', text: 'Each individual time the speaker went jogging.' },
        { id: 'c', text: 'A condition: "if I lived in Munich".' },
        { id: 'd', text: 'A future plan to live in Munich.' },
      ],
      correctOptionId: 'a',
      explanation:
        'als marks the one unrepeated life period ("when I lived in Munich"); that jogging happened repeatedly inside that single period does not change the connector.',
    },
    {
      id: 'ch77-ex-08',
      chapterNumber: 77,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-final', 'wenn'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"When I have time, I go swimming." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Wenn ich habe Zeit, gehe ich schwimmen.' },
        { id: 'b', text: 'Wenn ich Zeit habe, gehe ich schwimmen.' },
        { id: 'c', text: 'Wenn habe ich Zeit, gehe ich schwimmen.' },
        { id: 'd', text: 'Wenn Zeit ich habe, gehe ich schwimmen.' },
      ],
      correctOptionId: 'b',
      explanation:
        'wenn sends the finite verb to the end of its clause: Wenn ich Zeit habe, ...',
    },
    {
      id: 'ch77-ex-09',
      chapterNumber: 77,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-final', 'als'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"When the film was over, we went to eat." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Als der Film war zu Ende, gingen wir essen.' },
        { id: 'b', text: 'Als der Film zu Ende war, gingen wir essen.' },
        { id: 'c', text: 'Als war der Film zu Ende, gingen wir essen.' },
        { id: 'd', text: 'Als zu Ende der Film war, gingen wir essen.' },
      ],
      correctOptionId: 'b',
      explanation:
        'als sends the finite verb war to the end of its clause: Als der Film zu Ende war, ...',
    },
    {
      id: 'ch77-ex-10',
      chapterNumber: 77,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inversion', 'wenn', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"When the weather is nice, we go on a trip." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Wenn das Wetter schön ist, machen wir einen Ausflug.' },
        { id: 'b', text: 'Wenn das Wetter schön ist, wir machen einen Ausflug.' },
        { id: 'c', text: 'Wenn das Wetter schön ist, einen Ausflug machen wir.' },
        { id: 'd', text: 'Wenn das Wetter schön ist, wir einen Ausflug machen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The wenn-clause fills position 1, so the main-clause verb machen comes immediately after the comma, before its subject wir.',
    },
    {
      id: 'ch77-ex-11',
      chapterNumber: 77,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inversion', 'als', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"When I was young, I often played football." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Als ich jung war, spielte ich oft Fußball.' },
        { id: 'b', text: 'Als ich jung war, ich spielte oft Fußball.' },
        { id: 'c', text: 'Als ich jung war, oft ich spielte Fußball.' },
        { id: 'd', text: 'Als ich jung war, spielte oft ich Fußball.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The als-clause fills position 1, so the verb spielte comes immediately after the comma, before its subject ich.',
    },
    {
      id: 'ch77-ex-12',
      chapterNumber: 77,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wenn', 'conditional-vs-temporal'],
      instruction: 'Choose the statement that correctly explains the sentence.',
      prompt:
        'Wenn es regnet, bleibe ich zu Hause. — Which is true about this sentence, taken out of context?',
      options: [
        {
          id: 'a',
          text: 'wenn could mean either "if it rains" (a condition) or "whenever it rains" (a repeated time); only context disambiguates.',
        },
        { id: 'b', text: 'wenn can only mean "if" here.' },
        { id: 'c', text: 'wenn can only mean "whenever" here.' },
        {
          id: 'd',
          text: 'This sentence must use als instead, since it refers to weather.',
        },
      ],
      correctOptionId: 'a',
      explanation:
        'Outside of a wider context, wenn is genuinely ambiguous between a condition and a repeated/future time — both readings are grammatical.',
    },
    {
      id: 'ch77-ex-13',
      chapterNumber: 77,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'dialogue', 'connector-choice'],
      instruction: "Choose the connector that correctly completes Lena's sentence.",
      dialogue: [
        {
          speaker: 'Paul',
          german: 'Wie war deine Kindheit?',
          english: 'What was your childhood like?',
        },
        {
          speaker: 'Lena',
          german: 'Schön! ___ wir Kinder waren, spielten wir jeden Tag draußen.',
          english: 'Nice! When we were children, we played outside every day.',
        },
      ],
      prompt: '___ wir Kinder waren, spielten wir jeden Tag draußen.',
      options: [
        { id: 'a', text: 'Als' },
        { id: 'b', text: 'Wenn' },
        { id: 'c', text: 'Dass' },
        { id: 'd', text: 'Ob' },
      ],
      correctOptionId: 'b',
      explanation:
        'jeden Tag shows this childhood activity repeated; a repeated past habit takes wenn, even though "als Kinder" might feel tempting.',
    },
    {
      id: 'ch77-ex-14',
      chapterNumber: 77,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'common-mistake', 'repeated-past'],
      instruction: 'Choose the correct sentence.',
      prompt: 'Which sentence correctly describes a repeated childhood habit?',
      options: [
        { id: 'a', text: 'Als wir Kinder waren, spielten wir jeden Tag draußen.' },
        { id: 'b', text: 'Wenn wir Kinder waren, spielten wir jeden Tag draußen.' },
        { id: 'c', text: 'Als wir Kinder waren, spielen wir jeden Tag draußen.' },
        {
          id: 'd',
          text: 'Wenn wir Kinder gewesen sind, jeden Tag draußen spielten wir.',
        },
      ],
      correctOptionId: 'b',
      explanation:
        'A habitual, repeated action in the past (jeden Tag) takes wenn; als would wrongly suggest this happened only once.',
    },
    {
      id: 'ch77-ex-15',
      chapterNumber: 77,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'error-spotting'],
      instruction:
        'One of these sentences misuses wenn or als. Identify the incorrect sentence.',
      prompt: 'Which sentence is grammatically wrong?',
      options: [
        { id: 'a', text: 'Als ich acht Jahre alt war, zogen wir nach Hamburg.' },
        { id: 'b', text: 'Wenn ich in Berlin ankomme, rufe ich dich an.' },
        { id: 'c', text: 'Als ich morgen ankomme, rufe ich dich an.' },
        { id: 'd', text: 'Immer wenn er kam, freute sich der Hund.' },
      ],
      correctOptionId: 'c',
      explanation:
        'als is reserved for the past; a future event (morgen) must use wenn: Wenn ich morgen ankomme, ...',
    },
    {
      id: 'ch77-ex-16',
      chapterNumber: 77,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt: '___ ich zwölf war, bekam ich mein erstes Fahrrad. (a single past event)',
      acceptedAnswers: ['als'],
      answerMode: 'caseInsensitive',
      placeholder: 'als',
      maxLength: 6,
      explanation:
        'A single event that happened once in the past — receiving the first bike — takes als.',
    },
    {
      id: 'ch77-ex-17',
      chapterNumber: 77,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'repeated-past'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt:
        '___ meine Oma zu Besuch kam, backte sie immer einen Kuchen. (a repeated past event)',
      acceptedAnswers: ['wenn'],
      answerMode: 'caseInsensitive',
      placeholder: 'wenn',
      maxLength: 6,
      explanation: 'immer signals repetition, so this past habit uses wenn, not als.',
    },
    {
      id: 'ch77-ex-18',
      chapterNumber: 77,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt: '___ die Sonne scheint, gehen wir spazieren. (a general present habit)',
      acceptedAnswers: ['wenn'],
      answerMode: 'caseInsensitive',
      placeholder: 'wenn',
      maxLength: 6,
      explanation: 'A general, repeatable present situation takes wenn.',
    },
    {
      id: 'ch77-ex-19',
      chapterNumber: 77,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'future'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt:
        '___ ich nächstes Jahr nach Deutschland fliege, besuche ich dich. (a future event)',
      acceptedAnswers: ['wenn'],
      answerMode: 'caseInsensitive',
      placeholder: 'wenn',
      maxLength: 6,
      explanation: 'als never refers to the future; only wenn does.',
    },
    {
      id: 'ch77-ex-20',
      chapterNumber: 77,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt:
        '___ das Telefon klingelte, war ich gerade unter der Dusche. (a single past moment)',
      acceptedAnswers: ['als'],
      answerMode: 'caseInsensitive',
      placeholder: 'als',
      maxLength: 6,
      explanation: 'A single moment in the past — the phone ringing once — takes als.',
    },
    {
      id: 'ch77-ex-21',
      chapterNumber: 77,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['als', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Als ich acht Jahre alt ___, zogen wir nach Hamburg. (sein, ich-form)',
      acceptedAnswers: ['war'],
      answerMode: 'caseInsensitive',
      placeholder: 'war',
      maxLength: 10,
      explanation:
        'als sends the finite verb to the end; the ich-form of sein in the Präteritum is war.',
    },
    {
      id: 'ch77-ex-22',
      chapterNumber: 77,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt: 'Wenn ich Zeit ___, gehe ich schwimmen. (haben, ich-form)',
      acceptedAnswers: ['habe'],
      answerMode: 'caseInsensitive',
      placeholder: 'habe',
      maxLength: 10,
      explanation:
        'wenn sends the finite verb to the end of its clause: ..., wenn ich Zeit habe.',
    },
    {
      id: 'ch77-ex-23',
      chapterNumber: 77,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['als', 'clause-combination'],
      instruction:
        'Combine the two sentences with als. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich war acht Jahre alt. + Wir zogen nach Hamburg. (als)',
      acceptedAnswers: ['Als ich acht Jahre alt war, zogen wir nach Hamburg.'],
      answerMode: 'normalized',
      placeholder: 'Als ich acht Jahre alt war, ...',
      maxLength: 70,
      explanation:
        'als introduces the single past event; the verb war moves to the end of the first clause, and the main-clause verb zogen follows the comma.',
    },
    {
      id: 'ch77-ex-24',
      chapterNumber: 77,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['wenn', 'clause-combination', 'repeated-past'],
      instruction:
        'Combine the two sentences with immer wenn. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Er kam nach Hause. + Der Hund freute sich immer. (immer wenn)',
      acceptedAnswers: ['Immer wenn er nach Hause kam, freute sich der Hund.'],
      answerMode: 'normalized',
      placeholder: 'Immer wenn er nach Hause kam, ...',
      maxLength: 70,
      explanation:
        'immer wenn marks a repeated past action; the verb kam moves to the end of the subordinate clause, and freute follows directly after the comma.',
    },
    {
      id: 'ch77-ex-25',
      chapterNumber: 77,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['wenn', 'clause-combination', 'future'],
      instruction:
        'Combine the two sentences with wenn. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich komme in Berlin an. + Ich rufe dich an. (wenn)',
      acceptedAnswers: ['Ich rufe dich an, wenn ich in Berlin ankomme.'],
      answerMode: 'normalized',
      placeholder: 'Ich rufe dich an, wenn ...',
      maxLength: 70,
      explanation:
        'wenn introduces this single future event; the separable verb ankomme joins as one word at the end of the clause.',
    },
    {
      id: 'ch77-ex-26',
      chapterNumber: 77,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['inversion', 'als', 'word-order'],
      instruction:
        'Rewrite the sentence starting with the als-clause. Capitalisation and punctuation are checked.',
      prompt: 'Ich war sehr glücklich, als ich die Prüfung bestanden hatte.',
      acceptedAnswers: ['Als ich die Prüfung bestanden hatte, war ich sehr glücklich.'],
      answerMode: 'normalized',
      placeholder: 'Als ich die Prüfung bestanden hatte, ...',
      maxLength: 80,
      explanation:
        'When the als-clause opens the sentence, the main-clause verb war comes immediately after the comma, before its subject ich.',
    },
    {
      id: 'ch77-ex-27',
      chapterNumber: 77,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['inversion', 'wenn', 'word-order'],
      instruction:
        'Rewrite the sentence starting with the wenn-clause. Capitalisation and punctuation are checked.',
      prompt: 'Wir machen einen Ausflug, wenn das Wetter schön ist.',
      acceptedAnswers: ['Wenn das Wetter schön ist, machen wir einen Ausflug.'],
      answerMode: 'normalized',
      placeholder: 'Wenn das Wetter schön ist, ...',
      maxLength: 70,
      explanation:
        'When the wenn-clause opens the sentence, the main-clause verb machen comes immediately after the comma, before its subject wir.',
    },
    {
      id: 'ch77-ex-28',
      chapterNumber: 77,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'wenn-vs-als'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Wenn ich acht Jahre alt war, zogen wir nach Hamburg.',
      acceptedAnswers: ['Als ich acht Jahre alt war, zogen wir nach Hamburg.'],
      answerMode: 'normalized',
      placeholder: 'Als ich acht Jahre alt war, ...',
      maxLength: 70,
      explanation: 'This was a single, unrepeated past event, so it needs als, not wenn.',
    },
    {
      id: 'ch77-ex-29',
      chapterNumber: 77,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'wenn-vs-als', 'repeated-past'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Als wir Kinder waren, spielten wir jeden Tag draußen.',
      acceptedAnswers: ['Wenn wir Kinder waren, spielten wir jeden Tag draußen.'],
      answerMode: 'normalized',
      placeholder: 'Wenn wir Kinder waren, ...',
      maxLength: 70,
      explanation:
        'jeden Tag marks a repeated past habit, which needs wenn even though the whole thing happened in the past.',
    },
    {
      id: 'ch77-ex-30',
      chapterNumber: 77,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'inversion', 'word-order'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Als es klingelte, sie öffnete die Tür.',
      acceptedAnswers: ['Als es klingelte, öffnete sie die Tür.'],
      answerMode: 'normalized',
      placeholder: 'Als es klingelte, ...',
      maxLength: 60,
      explanation:
        'When the als-clause opens the sentence, the main-clause verb öffnete must come immediately after the comma, before its subject sie.',
    },
    {
      id: 'ch77-ex-31',
      chapterNumber: 77,
      order: 31,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past event.',
      templateParts: ['', ' ich in Rom war, habe ich das Kolosseum besucht.'],
      slots: [{ id: 'ch77-ex31-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Dass', 'Weil'],
      explanation: 'A single, unrepeated visit to Rome in the past takes als.',
    },
    {
      id: 'ch77-ex-32',
      chapterNumber: 77,
      order: 32,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a general present habit.',
      templateParts: ['', ' ich müde bin, trinke ich Kaffee.'],
      slots: [{ id: 'ch77-ex32-s1', correctWord: 'Wenn' }],
      wordBank: ['Wenn', 'Als', 'Ob', 'Dass'],
      explanation: 'A general present habit takes wenn.',
    },
    {
      id: 'ch77-ex-33',
      chapterNumber: 77,
      order: 33,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past moment.',
      templateParts: ['', ' das Konzert begann, wurde es plötzlich still.'],
      slots: [{ id: 'ch77-ex33-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Weil', 'Ob'],
      explanation: 'A single past moment — the concert beginning once — takes als.',
    },
    {
      id: 'ch77-ex-34',
      chapterNumber: 77,
      order: 34,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'repeated-past'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a repeated past event.',
      templateParts: ['Jeden Winter, ', ' es schneite, bauten wir einen Schneemann.'],
      slots: [{ id: 'ch77-ex34-s1', correctWord: 'wenn' }],
      wordBank: ['wenn', 'als', 'dass', 'bevor'],
      explanation:
        'jeden Winter shows repetition, so this past habit takes wenn, not als.',
    },
    {
      id: 'ch77-ex-35',
      chapterNumber: 77,
      order: 35,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a daily habit.',
      templateParts: ['', ' ich nach Hause komme, mache ich sofort die Hausaufgaben.'],
      slots: [{ id: 'ch77-ex35-s1', correctWord: 'Wenn' }],
      wordBank: ['Wenn', 'Als', 'Ob', 'Nachdem'],
      explanation: 'A repeatable daily habit takes wenn.',
    },
    {
      id: 'ch77-ex-36',
      chapterNumber: 77,
      order: 36,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past event.',
      templateParts: ['', ' meine Eltern heirateten, war meine Mutter erst 22.'],
      slots: [{ id: 'ch77-ex36-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Dass', 'Weil'],
      explanation: 'The wedding happened once, so this single past event takes als.',
    },
    {
      id: 'ch77-ex-37',
      chapterNumber: 77,
      order: 37,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a general present habit.',
      templateParts: ['', ' ich krank bin, bleibe ich im Bett.'],
      slots: [{ id: 'ch77-ex37-s1', correctWord: 'Wenn' }],
      wordBank: ['Wenn', 'Als', 'Ob', 'Dass'],
      explanation: 'A general present situation takes wenn.',
    },
    {
      id: 'ch77-ex-38',
      chapterNumber: 77,
      order: 38,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'repeated-past'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a repeated past event.',
      templateParts: ['Jedes Mal, ', ' wir uns trafen, erzählten wir uns Neuigkeiten.'],
      slots: [{ id: 'ch77-ex38-s1', correctWord: 'wenn' }],
      wordBank: ['wenn', 'als', 'dass', 'bevor'],
      explanation:
        'Jedes Mal signals repetition, so wenn is required, even though every meeting lies in the past.',
    },
    {
      id: 'ch77-ex-39',
      chapterNumber: 77,
      order: 39,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past moment.',
      templateParts: ['', ' der Zug endlich ankam, war es schon dunkel.'],
      slots: [{ id: 'ch77-ex39-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Dass', 'Nachdem'],
      explanation: 'The train arriving was a single past moment, so als fits.',
    },
    {
      id: 'ch77-ex-40',
      chapterNumber: 77,
      order: 40,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'future'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single future event.',
      templateParts: ['', ' du Zeit hast, können wir uns morgen treffen.'],
      slots: [{ id: 'ch77-ex40-s1', correctWord: 'Wenn' }],
      wordBank: ['Wenn', 'Als', 'Ob', 'Dass'],
      explanation: 'als never refers to the future; a future event takes wenn.',
    },
    {
      id: 'ch77-ex-41',
      chapterNumber: 77,
      order: 41,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past event.',
      templateParts: ['', ' ich das erste Mal Deutsch hörte, verstand ich nichts.'],
      slots: [{ id: 'ch77-ex41-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Dass', 'Weil'],
      explanation: 'das erste Mal marks a single, one-time occurrence, so als fits.',
    },
    {
      id: 'ch77-ex-42',
      chapterNumber: 77,
      order: 42,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'repeated-past'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a repeated past event.',
      templateParts: ['Immer ', ' die Ferien begannen, fuhren wir ans Meer.'],
      slots: [{ id: 'ch77-ex42-s1', correctWord: 'wenn' }],
      wordBank: ['wenn', 'als', 'dass', 'bevor'],
      explanation:
        'Immer signals repetition, so wenn is required, even though the holidays are in the past.',
    },
    {
      id: 'ch77-ex-43',
      chapterNumber: 77,
      order: 43,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past event.',
      templateParts: ['', ' er 18 wurde, zog er in eine eigene Wohnung.'],
      slots: [{ id: 'ch77-ex43-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Dass', 'Weil'],
      explanation: 'Turning 18 happened once, so this single past event takes als.',
    },
    {
      id: 'ch77-ex-44',
      chapterNumber: 77,
      order: 44,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a general present habit.',
      templateParts: ['', ' es dunkel wird, gehen die Straßenlaternen an.'],
      slots: [{ id: 'ch77-ex44-s1', correctWord: 'Wenn' }],
      wordBank: ['Wenn', 'Als', 'Ob', 'Dass'],
      explanation: 'A general, recurring present situation takes wenn.',
    },
    {
      id: 'ch77-ex-45',
      chapterNumber: 77,
      order: 45,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past period.',
      templateParts: [
        '',
        ' wir letztes Jahr in Spanien waren, hat es jeden Tag geregnet.',
      ],
      slots: [{ id: 'ch77-ex45-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Dass', 'Weil'],
      explanation:
        'The trip to Spain last year was a single, unrepeated past period, so als fits — even though it rained every day within that one trip.',
    },
    {
      id: 'ch77-ex-46',
      chapterNumber: 77,
      order: 46,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'future'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single future event.',
      templateParts: ['', ' ich morgen ankomme, hol mich bitte ab.'],
      slots: [{ id: 'ch77-ex46-s1', correctWord: 'Wenn' }],
      wordBank: ['Wenn', 'Als', 'Ob', 'Dass'],
      explanation: 'A future arrival, even a single one, takes wenn, never als.',
    },
    {
      id: 'ch77-ex-47',
      chapterNumber: 77,
      order: 47,
      type: 'dragToSlots',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a single past moment.',
      templateParts: ['', ' der Lehrer die Klasse betrat, wurden alle still.'],
      slots: [{ id: 'ch77-ex47-s1', correctWord: 'Als' }],
      wordBank: ['Als', 'Wenn', 'Dass', 'Nachdem'],
      explanation: 'The teacher entering was a single past moment, so als fits.',
    },
    {
      id: 'ch77-ex-48',
      chapterNumber: 77,
      order: 48,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction: 'Drag the correct connector into the slot.',
      prompt: 'Complete the sentence with the connector for a general present habit.',
      templateParts: ['', ' ich Geld habe, gehe ich einkaufen.'],
      slots: [{ id: 'ch77-ex48-s1', correctWord: 'Wenn' }],
      wordBank: ['Wenn', 'Als', 'Ob', 'Dass'],
      explanation: 'A general present habit takes wenn.',
    },
    {
      id: 'ch77-ex-49',
      chapterNumber: 77,
      order: 49,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'context-clues'],
      instruction: 'Match each context clue with what it signals.',
      prompt: 'Match each clue word or phrase to what it signals about the connector.',
      pairs: [
        {
          id: 'ch77-ex49-p1',
          left: 'jedes Mal',
          right: 'repetition, so wenn is required',
        },
        { id: 'ch77-ex49-p2', left: 'damals', right: 'a single past time, so als fits' },
        {
          id: 'ch77-ex49-p3',
          left: 'jeden Tag',
          right: 'daily repetition, so wenn is required',
        },
        {
          id: 'ch77-ex49-p4',
          left: 'nächstes Jahr',
          right: 'a future event, so wenn is required',
        },
        {
          id: 'ch77-ex49-p5',
          left: 'nur einmal',
          right: 'a single occurrence, so als fits',
        },
      ],
      explanation:
        'Repetition and future-time clues call for wenn; clues pointing to one single past occurrence call for als.',
    },
    {
      id: 'ch77-ex-50',
      chapterNumber: 77,
      order: 50,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'timeline-interpretation'],
      instruction: 'Match each scenario with the connector it requires.',
      prompt: 'Match each scenario to the correct connector.',
      pairs: [
        {
          id: 'ch77-ex50-p1',
          left: 'A single, unrepeated event in the past',
          right: 'als',
        },
        {
          id: 'ch77-ex50-p2',
          left: 'A repeated event, entirely in the past',
          right: 'wenn (repeated past)',
        },
        {
          id: 'ch77-ex50-p3',
          left: 'A general habit in the present',
          right: 'wenn (present habit)',
        },
        {
          id: 'ch77-ex50-p4',
          left: 'A single event in the future',
          right: 'wenn (future event)',
        },
        {
          id: 'ch77-ex50-p5',
          left: 'A condition, with no specific timing',
          right: 'wenn (condition)',
        },
      ],
      explanation:
        'als is reserved for a single past occurrence; wenn covers every other case, including repetition, the present, the future, and conditions.',
    },
    {
      id: 'ch77-ex-51',
      chapterNumber: 77,
      order: 51,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'context-clues'],
      instruction:
        'Match each context clue with the example sentence that correctly uses it.',
      prompt: 'Match each clue word to the sentence it appears in.',
      pairs: [
        {
          id: 'ch77-ex51-p1',
          left: 'jedes Mal',
          right: 'Jedes Mal, wenn es regnete, blieben wir zu Hause.',
        },
        {
          id: 'ch77-ex51-p2',
          left: 'damals',
          right: 'Damals, als ich in München wohnte, war ich Student.',
        },
        {
          id: 'ch77-ex51-p3',
          left: 'letztes Jahr',
          right: 'Letztes Jahr, als wir in Spanien waren, hat es viel geregnet.',
        },
        {
          id: 'ch77-ex51-p4',
          left: 'immer wenn',
          right: 'Immer wenn er kam, freute sich der Hund.',
        },
        {
          id: 'ch77-ex51-p5',
          left: 'gestern',
          right: 'Gestern, als ich nach Hause kam, war niemand da.',
        },
      ],
      explanation:
        'jedes Mal and immer wenn signal repetition (wenn); damals, letztes Jahr, and gestern point to one specific past moment (als).',
    },
    {
      id: 'ch77-ex-52',
      chapterNumber: 77,
      order: 52,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'translation'],
      instruction: 'Match each German sentence with its English translation.',
      prompt: 'Match the German sentences to their English translations.',
      pairs: [
        {
          id: 'ch77-ex52-p1',
          left: 'Als ich acht Jahre alt war, zogen wir nach Hamburg.',
          right: 'When I was eight, we moved to Hamburg.',
        },
        {
          id: 'ch77-ex52-p2',
          left: 'Wenn ich Zeit habe, gehe ich schwimmen.',
          right: 'When(ever) I have time, I go swimming.',
        },
        {
          id: 'ch77-ex52-p3',
          left: 'Immer wenn er kam, freute sich der Hund.',
          right: 'Whenever he came, the dog was happy.',
        },
        {
          id: 'ch77-ex52-p4',
          left: 'Als es klingelte, öffnete sie die Tür.',
          right: 'When the doorbell rang, she opened the door.',
        },
      ],
      explanation:
        'Each als-sentence describes one single past occurrence; each wenn-sentence describes a repeated or habitual event.',
    },
    {
      id: 'ch77-ex-53',
      chapterNumber: 77,
      order: 53,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'context-clues'],
      instruction: 'Match each context clue with what it signals.',
      prompt: 'Match each clue word or phrase to what it signals about the connector.',
      pairs: [
        {
          id: 'ch77-ex53-p1',
          left: 'als kleines Kind',
          right: 'one whole childhood period, so als fits',
        },
        {
          id: 'ch77-ex53-p2',
          left: 'jedes Semester',
          right: 'repetition each semester, so wenn is required',
        },
        {
          id: 'ch77-ex53-p3',
          left: 'in dem Moment',
          right: 'one specific past moment, so als fits',
        },
        {
          id: 'ch77-ex53-p4',
          left: 'morgen früh',
          right: 'a future event, so wenn is required',
        },
        {
          id: 'ch77-ex53-p5',
          left: 'jeden Morgen',
          right: 'daily repetition, so wenn is required',
        },
      ],
      explanation:
        'Clues describing a single defined period or moment call for als; clues describing recurrence or the future call for wenn.',
    },
    {
      id: 'ch77-ex-54',
      chapterNumber: 77,
      order: 54,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'timeline-interpretation'],
      instruction: 'Match each scenario with the connector it requires.',
      prompt: 'Match each scenario to the correct connector.',
      pairs: [
        {
          id: 'ch77-ex54-p1',
          left: 'Being a certain age — a period that happened only once',
          right: 'als',
        },
        {
          id: 'ch77-ex54-p2',
          left: 'Something that happens every time X occurs',
          right: 'wenn (repeated event)',
        },
        {
          id: 'ch77-ex54-p3',
          left: 'Something you plan to do next week',
          right: 'wenn (future event)',
        },
        {
          id: 'ch77-ex54-p4',
          left: 'A rule that is generally true',
          right: 'wenn (general habit)',
        },
        {
          id: 'ch77-ex54-p5',
          left: 'Saying "if" with no past or future marker',
          right: 'wenn (condition)',
        },
      ],
      explanation:
        'Only a single, unrepeated past occurrence takes als; every other timeline — repeated, general, future, or conditional — takes wenn.',
    },
    {
      id: 'ch77-ex-55',
      chapterNumber: 77,
      order: 55,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['als', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Build the sentence: When the rain stopped, we went for a walk.',
      segments: [
        { id: 'ch77-ex55-s1', text: 'Als' },
        { id: 'ch77-ex55-s2', text: 'der' },
        { id: 'ch77-ex55-s3', text: 'Regen' },
        { id: 'ch77-ex55-s4', text: 'aufhörte,' },
        { id: 'ch77-ex55-s5', text: 'gingen' },
        { id: 'ch77-ex55-s6', text: 'wir' },
        { id: 'ch77-ex55-s7', text: 'spazieren.' },
      ],
      explanation:
        'als sends aufhörte to the end of its clause; gingen follows immediately after the comma, before its subject wir.',
    },
    {
      id: 'ch77-ex-56',
      chapterNumber: 77,
      order: 56,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['wenn', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Build the sentence: When the sun sets, it gets cold.',
      segments: [
        { id: 'ch77-ex56-s1', text: 'Wenn' },
        { id: 'ch77-ex56-s2', text: 'die' },
        { id: 'ch77-ex56-s3', text: 'Sonne' },
        { id: 'ch77-ex56-s4', text: 'untergeht,' },
        { id: 'ch77-ex56-s5', text: 'wird' },
        { id: 'ch77-ex56-s6', text: 'es' },
        { id: 'ch77-ex56-s7', text: 'kalt.' },
      ],
      explanation:
        'wenn sends untergeht to the end of its clause; wird follows immediately after the comma, before its subject es.',
    },
    {
      id: 'ch77-ex-57',
      chapterNumber: 77,
      order: 57,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['als', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Build the sentence: When the baby was born, everyone cried with joy.',
      segments: [
        { id: 'ch77-ex57-s1', text: 'Als' },
        { id: 'ch77-ex57-s2', text: 'das' },
        { id: 'ch77-ex57-s3', text: 'Baby' },
        { id: 'ch77-ex57-s4', text: 'geboren' },
        { id: 'ch77-ex57-s5', text: 'wurde,' },
        { id: 'ch77-ex57-s6', text: 'weinten' },
        { id: 'ch77-ex57-s7', text: 'alle' },
        { id: 'ch77-ex57-s8', text: 'vor' },
        { id: 'ch77-ex57-s9', text: 'Freude.' },
      ],
      explanation:
        'The passive auxiliary wurde moves to the end of the als-clause, after the participle geboren; weinten follows directly after the comma.',
    },
    {
      id: 'ch77-ex-58',
      chapterNumber: 77,
      order: 58,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['wenn', 'repeated-past', 'word-order'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Build the sentence: Whenever winter came, the children were happy.',
      segments: [
        { id: 'ch77-ex58-s1', text: 'Immer' },
        { id: 'ch77-ex58-s2', text: 'wenn' },
        { id: 'ch77-ex58-s3', text: 'der' },
        { id: 'ch77-ex58-s4', text: 'Winter' },
        { id: 'ch77-ex58-s5', text: 'kam,' },
        { id: 'ch77-ex58-s6', text: 'freuten' },
        { id: 'ch77-ex58-s7', text: 'sich' },
        { id: 'ch77-ex58-s8', text: 'die' },
        { id: 'ch77-ex58-s9', text: 'Kinder.' },
      ],
      explanation:
        'Immer wenn marks a repeated past event; kam moves to the end of the subordinate clause, and freuten follows directly after the comma.',
    },
    {
      id: 'ch77-ex-59',
      chapterNumber: 77,
      order: 59,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['wenn', 'future', 'word-order'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Build the sentence: If you need help, just call me.',
      segments: [
        { id: 'ch77-ex59-s1', text: 'Wenn' },
        { id: 'ch77-ex59-s2', text: 'du' },
        { id: 'ch77-ex59-s3', text: 'Hilfe' },
        { id: 'ch77-ex59-s4', text: 'brauchst,' },
        { id: 'ch77-ex59-s5', text: 'ruf' },
        { id: 'ch77-ex59-s6', text: 'mich' },
        { id: 'ch77-ex59-s7', text: 'einfach' },
        { id: 'ch77-ex59-s8', text: 'an.' },
      ],
      explanation:
        'wenn sends brauchst to the end of its clause; the separable verb an...ruf splits, with ruf right after the comma and an at the very end of the main clause.',
    },
    {
      id: 'ch77-ex-60',
      chapterNumber: 77,
      order: 60,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['als', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Build the sentence: When the war ended, many soldiers returned.',
      segments: [
        { id: 'ch77-ex60-s1', text: 'Als' },
        { id: 'ch77-ex60-s2', text: 'der' },
        { id: 'ch77-ex60-s3', text: 'Krieg' },
        { id: 'ch77-ex60-s4', text: 'endete,' },
        { id: 'ch77-ex60-s5', text: 'kehrten' },
        { id: 'ch77-ex60-s6', text: 'viele' },
        { id: 'ch77-ex60-s7', text: 'Soldaten' },
        { id: 'ch77-ex60-s8', text: 'zurück.' },
      ],
      explanation:
        'als sends endete to the end of its clause; the separable verb zurückkehren splits, with kehrten right after the comma and zurück at the very end.',
    },
    {
      id: 'ch77-ex-61',
      chapterNumber: 77,
      order: 61,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['wenn', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Build the sentence: When I cook in the evening, my sister helps me.',
      segments: [
        { id: 'ch77-ex61-s1', text: 'Wenn' },
        { id: 'ch77-ex61-s2', text: 'ich' },
        { id: 'ch77-ex61-s3', text: 'abends' },
        { id: 'ch77-ex61-s4', text: 'koche,' },
        { id: 'ch77-ex61-s5', text: 'hilft' },
        { id: 'ch77-ex61-s6', text: 'mir' },
        { id: 'ch77-ex61-s7', text: 'meine' },
        { id: 'ch77-ex61-s8', text: 'Schwester.' },
      ],
      explanation:
        'wenn sends koche to the end of its clause; hilft follows immediately after the comma, before its subject meine Schwester.',
    },
    {
      id: 'ch77-ex-62',
      chapterNumber: 77,
      order: 62,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['als', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt:
        'Build the sentence: When the exam was over, all the students breathed a sigh of relief.',
      segments: [
        { id: 'ch77-ex62-s1', text: 'Als' },
        { id: 'ch77-ex62-s2', text: 'die' },
        { id: 'ch77-ex62-s3', text: 'Prüfung' },
        { id: 'ch77-ex62-s4', text: 'vorbei' },
        { id: 'ch77-ex62-s5', text: 'war,' },
        { id: 'ch77-ex62-s6', text: 'atmeten' },
        { id: 'ch77-ex62-s7', text: 'alle' },
        { id: 'ch77-ex62-s8', text: 'Studenten' },
        { id: 'ch77-ex62-s9', text: 'auf.' },
      ],
      explanation:
        'als sends war to the end of its clause; the separable verb aufatmen splits, with atmeten right after the comma and auf at the very end.',
    },
    {
      id: 'ch77-ex-63',
      chapterNumber: 77,
      order: 63,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['wenn', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt:
        'Build the sentence: When the concert starts, everyone turns off their phones.',
      segments: [
        { id: 'ch77-ex63-s1', text: 'Wenn' },
        { id: 'ch77-ex63-s2', text: 'das' },
        { id: 'ch77-ex63-s3', text: 'Konzert' },
        { id: 'ch77-ex63-s4', text: 'beginnt,' },
        { id: 'ch77-ex63-s5', text: 'schalten' },
        { id: 'ch77-ex63-s6', text: 'alle' },
        { id: 'ch77-ex63-s7', text: 'ihre' },
        { id: 'ch77-ex63-s8', text: 'Handys' },
        { id: 'ch77-ex63-s9', text: 'aus.' },
      ],
      explanation:
        'wenn sends beginnt to the end of its clause; the separable verb ausschalten splits, with schalten right after the comma and aus at the very end.',
    },
    {
      id: 'ch77-ex-64',
      chapterNumber: 77,
      order: 64,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['als', 'word-order', 'verb-final'],
      instruction: 'Drag the segments into the correct order.',
      prompt:
        'Build the sentence: When my grandmother was young, there was no internet yet.',
      segments: [
        { id: 'ch77-ex64-s1', text: 'Als' },
        { id: 'ch77-ex64-s2', text: 'meine' },
        { id: 'ch77-ex64-s3', text: 'Großmutter' },
        { id: 'ch77-ex64-s4', text: 'jung' },
        { id: 'ch77-ex64-s5', text: 'war,' },
        { id: 'ch77-ex64-s6', text: 'gab' },
        { id: 'ch77-ex64-s7', text: 'es' },
        { id: 'ch77-ex64-s8', text: 'noch' },
        { id: 'ch77-ex64-s9', text: 'kein' },
        { id: 'ch77-ex64-s10', text: 'Internet.' },
      ],
      explanation:
        'als sends war to the end of its clause; gab follows immediately after the comma, before its subject es.',
    },
    {
      id: 'ch77-ex-65',
      chapterNumber: 77,
      order: 65,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present', 'common-mistake'],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: ['Als', 'ich', 'müde', 'bin,', 'trinke', 'ich', 'Kaffee.'],
      errorTokenIndex: 0,
      correction: 'Wenn',
      explanation:
        'als is only ever used for the past; a present habitual action needs wenn.',
    },
    {
      id: 'ch77-ex-66',
      chapterNumber: 77,
      order: 66,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: [
        'wenn-vs-als',
        'connector-choice',
        'single-past-event',
        'common-mistake',
      ],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Wenn',
        'ich',
        'zwölf',
        'war,',
        'bekam',
        'ich',
        'mein',
        'erstes',
        'Fahrrad.',
      ],
      errorTokenIndex: 0,
      correction: 'Als',
      explanation:
        'A single, unrepeated past event — receiving the first bike — takes als, not wenn.',
    },
    {
      id: 'ch77-ex-67',
      chapterNumber: 77,
      order: 67,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: [
        'wenn-vs-als',
        'connector-choice',
        'repeated-past',
        'common-mistake',
      ],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Als',
        'wir',
        'Kinder',
        'waren,',
        'gingen',
        'wir',
        'jeden',
        'Sommer',
        'ans',
        'Meer.',
      ],
      errorTokenIndex: 0,
      correction: 'Wenn',
      explanation:
        'jeden Sommer signals repetition, so this childhood habit takes wenn, even though it lies entirely in the past.',
    },
    {
      id: 'ch77-ex-68',
      chapterNumber: 77,
      order: 68,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: [
        'wenn-vs-als',
        'connector-choice',
        'single-past-event',
        'common-mistake',
      ],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: ['Wenn', 'der', 'Zug', 'ankam,', 'war', 'es', 'schon', 'dunkel.'],
      errorTokenIndex: 0,
      correction: 'Als',
      explanation:
        'A single past moment — the train arriving once — takes als, not wenn.',
    },
    {
      id: 'ch77-ex-69',
      chapterNumber: 77,
      order: 69,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'future', 'common-mistake'],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: ['Als', 'ich', 'morgen', 'ankomme,', 'rufe', 'ich', 'dich', 'an.'],
      errorTokenIndex: 0,
      correction: 'Wenn',
      explanation: 'als is reserved for the past; a future event (morgen) needs wenn.',
    },
    {
      id: 'ch77-ex-70',
      chapterNumber: 77,
      order: 70,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: [
        'wenn-vs-als',
        'connector-choice',
        'single-past-event',
        'common-mistake',
      ],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: ['Wenn', 'es', 'klingelte,', 'öffnete', 'sie', 'die', 'Tür.'],
      errorTokenIndex: 0,
      correction: 'Als',
      explanation:
        'A single, one-time past moment — the doorbell ringing once — takes als, not wenn.',
    },
    {
      id: 'ch77-ex-71',
      chapterNumber: 77,
      order: 71,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: [
        'wenn-vs-als',
        'connector-choice',
        'repeated-past',
        'common-mistake',
      ],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Als',
        'die',
        'Ferien',
        'begannen,',
        'fuhren',
        'wir',
        'jedes',
        'Jahr',
        'ans',
        'Meer.',
      ],
      errorTokenIndex: 0,
      correction: 'Wenn',
      explanation:
        'jedes Jahr shows this holiday trip repeated every year, so wenn is required, not als.',
    },
    {
      id: 'ch77-ex-72',
      chapterNumber: 77,
      order: 72,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'timeline-interpretation', 'common-mistake'],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Wenn',
        'ich',
        'in',
        'München',
        'wohnte,',
        'habe',
        'ich',
        'oft',
        'im',
        'Park',
        'gejoggt.',
      ],
      errorTokenIndex: 0,
      correction: 'Als',
      explanation:
        'als marks the one, unrepeated period of living in Munich; that the jogging inside it happened often does not change the connector.',
    },
    {
      id: 'ch77-ex-73',
      chapterNumber: 77,
      order: 73,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['als', 'tense-agreement', 'common-mistake'],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Als',
        'ich',
        'acht',
        'Jahre',
        'alt',
        'bin,',
        'zogen',
        'wir',
        'nach',
        'Hamburg.',
      ],
      errorTokenIndex: 5,
      correction: 'war,',
      explanation:
        'als always refers to the past, so its clause needs a past-tense verb (war), not the present tense (bin).',
    },
    {
      id: 'ch77-ex-74',
      chapterNumber: 77,
      order: 74,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['als', 'tense-agreement', 'common-mistake'],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: ['Als', 'es', 'klingelt,', 'öffnete', 'sie', 'die', 'Tür.'],
      errorTokenIndex: 2,
      correction: 'klingelte,',
      explanation:
        'als always refers to the past; the subordinate-clause verb must match, so klingelt must become the past-tense klingelte.',
    },
    {
      id: 'ch77-ex-75',
      chapterNumber: 77,
      order: 75,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present', 'common-mistake'],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: ['Als', 'ich', 'Geld', 'habe,', 'gehe', 'ich', 'einkaufen.'],
      errorTokenIndex: 0,
      correction: 'Wenn',
      explanation:
        'A general present habit takes wenn; als never appears outside the past.',
    },
    {
      id: 'ch77-ex-76',
      chapterNumber: 77,
      order: 76,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: [
        'wenn-vs-als',
        'connector-choice',
        'single-past-event',
        'common-mistake',
      ],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Wenn',
        'er',
        '18',
        'wurde,',
        'zog',
        'er',
        'in',
        'eine',
        'eigene',
        'Wohnung.',
      ],
      errorTokenIndex: 0,
      correction: 'Als',
      explanation:
        'Turning 18 happened once, so this single past event takes als, not wenn.',
    },
    {
      id: 'ch77-ex-77',
      chapterNumber: 77,
      order: 77,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'future', 'common-mistake'],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Als',
        'du',
        'Zeit',
        'hast,',
        'können',
        'wir',
        'uns',
        'morgen',
        'treffen.',
      ],
      errorTokenIndex: 0,
      correction: 'Wenn',
      explanation:
        'als is reserved for the past; a future condition or event needs wenn.',
    },
    {
      id: 'ch77-ex-78',
      chapterNumber: 77,
      order: 78,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: [
        'wenn-vs-als',
        'connector-choice',
        'repeated-past',
        'common-mistake',
      ],
      instruction: 'One word is wrong. Identify it and give the correction.',
      prompt: 'Find the error in this sentence.',
      tokens: [
        'Als',
        'wir',
        'uns',
        'trafen,',
        'erzählten',
        'wir',
        'uns',
        'immer',
        'Neuigkeiten.',
      ],
      errorTokenIndex: 0,
      correction: 'Wenn',
      explanation:
        'immer signals repetition, so this past habit needs wenn, even though the meetings are entirely in the past.',
    },
    {
      id: 'ch77-ex-79',
      chapterNumber: 77,
      order: 79,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction: 'Choose the connector that fits.',
      prompt:
        '___ ich nur einmal in New York war, hat es geschneit. (a single past event)',
      options: [
        { id: 'a', text: 'als' },
        { id: 'b', text: 'wenn' },
        { id: 'c', text: 'dass' },
        { id: 'd', text: 'ob' },
      ],
      correctOptionId: 'a',
      explanation:
        'nur einmal marks a single, unrepeated occurrence in the past, so als is required.',
    },
    {
      id: 'ch77-ex-80',
      chapterNumber: 77,
      order: 80,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'repeated-past'],
      instruction: 'Choose the connector that fits.',
      prompt:
        'Jedes Mal, ___ meine Schwester zu Besuch kommt, backen wir zusammen Kuchen.',
      options: [
        { id: 'a', text: 'wenn' },
        { id: 'b', text: 'als' },
        { id: 'c', text: 'ob' },
        { id: 'd', text: 'dass' },
      ],
      correctOptionId: 'a',
      explanation: 'Jedes Mal shows repetition, so wenn is required.',
    },
    {
      id: 'ch77-ex-81',
      chapterNumber: 77,
      order: 81,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-final', 'als'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: '"We went to the cinema when the film started." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Wir sind ins Kino gegangen, als der Film anfing.' },
        { id: 'b', text: 'Wir sind ins Kino gegangen, als der Film hat angefangen.' },
        { id: 'c', text: 'Wir sind ins Kino gegangen, als anfing der Film.' },
        { id: 'd', text: 'Wir sind ins Kino gegangen, wenn der Film anfing.' },
      ],
      correctOptionId: 'a',
      explanation:
        'als sends the finite verb anfing to the end of its clause; a single past event needs als, not wenn.',
    },
    {
      id: 'ch77-ex-82',
      chapterNumber: 77,
      order: 82,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['inversion', 'als', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt:
        '"When my grandmother was young, there was no internet yet." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Als meine Großmutter jung war, gab es noch kein Internet.' },
        { id: 'b', text: 'Als meine Großmutter jung war, es gab noch kein Internet.' },
        { id: 'c', text: 'Als war meine Großmutter jung, gab es noch kein Internet.' },
        { id: 'd', text: 'Als meine Großmutter war jung, gab es noch kein Internet.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The als-clause fills position 1, so the main-clause verb gab comes immediately after the comma, before its subject es.',
    },
    {
      id: 'ch77-ex-83',
      chapterNumber: 77,
      order: 83,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'dialogue', 'connector-choice'],
      instruction: "Choose the connector that correctly completes Tom's sentence.",
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Wie hast du deinen Mann kennengelernt?',
          english: 'How did you meet your husband?',
        },
        {
          speaker: 'Tom',
          german: '___ ich in Berlin studierte, habe ich ihn auf einer Party getroffen.',
          english: 'When I was studying in Berlin, I met him at a party.',
        },
      ],
      prompt: '___ ich in Berlin studierte, habe ich ihn auf einer Party getroffen.',
      options: [
        { id: 'a', text: 'Als' },
        { id: 'b', text: 'Wenn' },
        { id: 'c', text: 'Dass' },
        { id: 'd', text: 'Ob' },
      ],
      correctOptionId: 'a',
      explanation: 'The single, unrepeated period of studying in Berlin takes als.',
    },
    {
      id: 'ch77-ex-84',
      chapterNumber: 77,
      order: 84,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'error-spotting'],
      instruction:
        'One of these sentences misuses wenn or als. Identify the incorrect sentence.',
      prompt: 'Which sentence is grammatically wrong?',
      options: [
        { id: 'a', text: 'Als ich jung war, spielte ich oft Fußball.' },
        { id: 'b', text: 'Wenn ich jeden Tag Sport mache, fühle ich mich besser.' },
        { id: 'c', text: 'Als wir jeden Sommer ans Meer fuhren, war das toll.' },
        { id: 'd', text: 'Wenn du Fragen hast, melde dich.' },
      ],
      correctOptionId: 'c',
      explanation:
        'jeden Sommer signals a repeated past habit, which needs wenn, not als: Wenn wir jeden Sommer ans Meer fuhren, ...',
    },
    {
      id: 'ch77-ex-85',
      chapterNumber: 77,
      order: 85,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'future', 'connector-choice'],
      instruction: 'Choose the correct sentence.',
      prompt: 'Which sentence correctly describes a single future event?',
      options: [
        { id: 'a', text: 'Als ich nächste Woche ankomme, rufe ich dich an.' },
        { id: 'b', text: 'Wenn ich nächste Woche ankomme, rufe ich dich an.' },
        { id: 'c', text: 'Als ich nächste Woche ankommen werde, rufe ich dich an.' },
        { id: 'd', text: 'Wenn ich nächste Woche angekommen war, rufe ich dich an.' },
      ],
      correctOptionId: 'b',
      explanation:
        'als never refers to the future; a single future event, even next week, still takes wenn.',
    },
    {
      id: 'ch77-ex-86',
      chapterNumber: 77,
      order: 86,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction: 'Choose the connector that fits.',
      prompt: '___ ich abends nach Hause komme, füttere ich die Katze. (a daily habit)',
      options: [
        { id: 'a', text: 'wenn' },
        { id: 'b', text: 'als' },
        { id: 'c', text: 'dass' },
        { id: 'd', text: 'ob' },
      ],
      correctOptionId: 'a',
      explanation: 'A daily, repeatable present habit takes wenn.',
    },
    {
      id: 'ch77-ex-87',
      chapterNumber: 77,
      order: 87,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['als', 'verb-final', 'participle'],
      instruction: 'Choose the correct form to complete the sentence.',
      prompt:
        'Als ich die Prüfung ___ hatte, war ich sehr glücklich. (bestehen, Partizip II)',
      options: [
        { id: 'a', text: 'bestanden' },
        { id: 'b', text: 'bestehen' },
        { id: 'c', text: 'bestehte' },
        { id: 'd', text: 'bestandet' },
      ],
      correctOptionId: 'a',
      explanation:
        'The Plusquamperfekt needs the participle bestanden together with the auxiliary hatte, which moves to the very end of the clause.',
    },
    {
      id: 'ch77-ex-88',
      chapterNumber: 77,
      order: 88,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['wenn-vs-als', 'inversion', 'word-order'],
      instruction: 'Choose the sentence that is fully correct.',
      prompt: 'Which sentence is fully correct (connector choice AND word order)?',
      options: [
        { id: 'a', text: 'Immer wenn er kam, freute sich der Hund.' },
        { id: 'b', text: 'Immer als er kam, freute sich der Hund.' },
        { id: 'c', text: 'Immer wenn er kam, der Hund freute sich.' },
        { id: 'd', text: 'Immer wenn kam er, freute sich der Hund.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Immer signals repetition, so wenn (not als) is required; the finite verb kam stays at the end of the subordinate clause, and freute follows directly after the comma.',
    },
    {
      id: 'ch77-ex-89',
      chapterNumber: 77,
      order: 89,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'single-past-event'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt: '___ ich zwölf war, bekam ich mein erstes Handy. (a single past event)',
      acceptedAnswers: ['als'],
      answerMode: 'caseInsensitive',
      placeholder: 'als',
      maxLength: 6,
      explanation:
        'A single, unrepeated event in the past — receiving the first phone — takes als.',
    },
    {
      id: 'ch77-ex-90',
      chapterNumber: 77,
      order: 90,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'repeated-past'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt:
        '___ meine Oma uns besuchte, brachte sie immer Kekse mit. (a repeated past event)',
      acceptedAnswers: ['wenn'],
      answerMode: 'caseInsensitive',
      placeholder: 'wenn',
      maxLength: 6,
      explanation: 'immer signals repetition, so this past habit takes wenn, not als.',
    },
    {
      id: 'ch77-ex-91',
      chapterNumber: 77,
      order: 91,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wenn-vs-als', 'connector-choice', 'present'],
      instruction:
        'Write only the missing connector (als or wenn). Capitalisation is not checked.',
      prompt: '___ ich Deutsch lerne, benutze ich eine App. (a general present habit)',
      acceptedAnswers: ['wenn'],
      answerMode: 'caseInsensitive',
      placeholder: 'wenn',
      maxLength: 6,
      explanation: 'A general, repeatable present habit takes wenn.',
    },
    {
      id: 'ch77-ex-92',
      chapterNumber: 77,
      order: 92,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['als', 'verb-final', 'conjugation'],
      instruction: 'Write only the missing word. Capitalisation is not checked.',
      prompt:
        'Als ich die Prüfung bestanden ___, war ich sehr glücklich. (haben, ich-Form, Präteritum)',
      acceptedAnswers: ['hatte'],
      answerMode: 'caseInsensitive',
      placeholder: 'hatte',
      maxLength: 10,
      explanation:
        'als sends the auxiliary to the very end of the clause, after the participle bestanden: ..., als ich die Prüfung bestanden hatte.',
    },
    {
      id: 'ch77-ex-93',
      chapterNumber: 77,
      order: 93,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['als', 'clause-combination'],
      instruction:
        'Combine the two sentences with als. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich war achtzehn. + Ich habe meinen Führerschein gemacht. (als)',
      acceptedAnswers: ['Als ich achtzehn war, habe ich meinen Führerschein gemacht.'],
      answerMode: 'normalized',
      placeholder: 'Als ich achtzehn war, ...',
      maxLength: 70,
      explanation:
        'als introduces the single past event; the verb war moves to the end of the first clause, and the main-clause verb habe follows the comma.',
    },
    {
      id: 'ch77-ex-94',
      chapterNumber: 77,
      order: 94,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['wenn', 'clause-combination', 'repeated-past'],
      instruction:
        'Combine the two sentences with immer wenn. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Meine Oma besuchte uns. + Sie brachte immer Kekse mit. (immer wenn)',
      acceptedAnswers: ['Immer wenn meine Oma uns besuchte, brachte sie Kekse mit.'],
      answerMode: 'normalized',
      placeholder: 'Immer wenn meine Oma uns besuchte, ...',
      maxLength: 80,
      explanation:
        'immer wenn marks a repeated past action; the verb besuchte moves to the end of the subordinate clause, and brachte follows directly after the comma.',
    },
    {
      id: 'ch77-ex-95',
      chapterNumber: 77,
      order: 95,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'wenn-vs-als'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Als ich müde bin, trinke ich Kaffee.',
      acceptedAnswers: ['Wenn ich müde bin, trinke ich Kaffee.'],
      answerMode: 'normalized',
      placeholder: 'Wenn ich müde bin, ...',
      maxLength: 60,
      explanation:
        'A general present habit needs wenn, not als, which is reserved for the past.',
    },
    {
      id: 'ch77-ex-96',
      chapterNumber: 77,
      order: 96,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'inversion', 'word-order'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Als meine Großmutter jung war, es gab noch kein Internet.',
      acceptedAnswers: ['Als meine Großmutter jung war, gab es noch kein Internet.'],
      answerMode: 'normalized',
      placeholder: 'Als meine Großmutter jung war, ...',
      maxLength: 70,
      explanation:
        'When the als-clause opens the sentence, the main-clause verb gab must come immediately after the comma, before its subject es.',
    },
  ],
};
