import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter032: ChapterDefinition = {
  id: 'chapter-032',
  number: 32,
  slug: 'basic-temporal-prepositions',
  title: 'Basic Temporal Prepositions',
  germanTitle: 'Temporale Präpositionen',
  level: 'A1',
  section: 'prepositions-1',
  objective:
    'Choose the correct temporal preposition (um, am, im, von ... bis, ab) for clock times, days, dates, months, seasons, and time spans, and use the contracted forms am and im correctly instead of the uncontracted an dem and in dem.',
  prerequisites: [1, 2],
  estimatedMinutes: 20,
  tags: [
    'prepositions',
    'time expressions',
    'um',
    'am',
    'im',
    'von...bis',
    'ab',
    'contractions',
    'clock time',
    'days and months',
  ],
  explanation: {
    introduction: [
      'German uses a small set of fixed prepositions to talk about time, and each one is tied to a particular type of time expression: a clock time, a day, a date, a month, a season, a time span, or a starting point. Unlike the two-way prepositions you may already have met, these temporal prepositions are not about case government in this chapter — they are idiomatic pairings that you simply learn together with the type of time word they introduce.',
      'This chapter covers five expressions: um for clock times (um acht Uhr), am for days and dates (am Montag, am 3. Mai), im for months and seasons (im April, im Winter), von ... bis for a time span with a clear beginning and end (von Montag bis Freitag), and ab for an open-ended starting point (ab nächster Woche). Two of these, am and im, are contractions — am is short for an dem, and im is short for in dem — so learning them as single words from the start will save you from a common source of mistakes.',
    ],
    rules: [
      {
        id: 'ch32-rule-01',
        heading: 'um for clock times',
        paragraphs: [
          'Use um whenever you name a specific clock time: um acht Uhr (at eight o\'clock), um halb neun (at half past eight), um Mitternacht (at midnight). This is the most common temporal preposition and answers the question wann? (when?) for a precise point on the clock.',
          'Der Unterricht beginnt um neun Uhr. (Class starts at nine o\'clock.) The word Uhr can be dropped in casual speech once the time is clear from context, but um itself is never dropped.',
        ],
      },
      {
        id: 'ch32-rule-02',
        heading: 'am for days and dates — the contraction of an + dem',
        paragraphs: [
          'Use am for days of the week and for dates: am Montag (on Monday), am Freitag (on Friday), am 3. Mai (on 3 May). am is not a separate word to memorise from scratch — it is the fixed contraction of an + dem, which you will also encounter as a general rule with other masculine and neuter dative nouns.',
          'Because the contraction is obligatory here, German never says an dem Montag in everyday speech; it always contracts to am Montag. The same rule covers am Wochenende (at the weekend), even though Wochenende is not a day name, because it behaves the same way in this fixed expression.',
        ],
      },
      {
        id: 'ch32-rule-03',
        heading: 'im for months and seasons — the contraction of in + dem',
        paragraphs: [
          'Use im for months and seasons: im April (in April), im Januar (in January), im Winter (in winter), im Sommer (in summer). Just like am, im is a contraction — this time of in + dem — and it is likewise obligatory: German does not say in dem April in everyday speech, only im April.',
          'A simple way to keep am and im apart: am goes with the smaller, more specific units (a single day or a single date), while im goes with the larger time periods (a whole month or a whole season).',
        ],
      },
      {
        id: 'ch32-rule-04',
        heading: 'von ... bis for a time span',
        paragraphs: [
          'Use the pair von ... bis when a time expression has both a clear start and a clear end: von Montag bis Freitag (from Monday to Friday), von neun bis siebzehn Uhr (from nine to five). von marks the beginning of the span and bis marks the end; the two words always appear together.',
          'Das Geschäft hat von neun bis achtzehn Uhr geöffnet. (The shop is open from nine to six.) Do not insert um or am before the second time in the pair — bis alone is enough to introduce the end point.',
        ],
      },
      {
        id: 'ch32-rule-05',
        heading: 'ab for an open-ended starting point',
        paragraphs: [
          'Use ab when you name a point where something begins and continues onward, with no fixed end mentioned: ab Montag (from Monday onward), ab nächster Woche (from next week on), ab 9 Uhr (from 9 o\'clock onward, e.g. for opening hours that continue all day).',
          'The key difference from von ... bis is the missing end point: Ab Montag arbeite ich in der neuen Firma. (From Monday, I am working at the new company — an ongoing change, not a closed time span.) If you can add "onward" or "from now on" to the English translation, ab is usually the right choice.',
        ],
      },
      {
        id: 'ch32-rule-06',
        heading: 'Choosing the right preposition: a quick decision guide',
        paragraphs: [
          'When you meet a time expression, first ask what type it is. A clock time (a specific hour) takes um. A day of the week or a date takes am. A month or a season takes im. A closed span with both a start and an end takes von ... bis. An open-ended starting point, with no end mentioned, takes ab.',
          'The most frequent confusion is between um and ab with clock times: Der Zug fährt um 14 Uhr (the train departs at 2 pm, one specific event) versus Das Geschäft hat ab 9 Uhr geöffnet (the shop is open from 9 am onward, an ongoing state). Reading the rest of the sentence for a single event versus an ongoing situation usually tells you which one is meant.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch32-table-01',
        title: 'Which preposition for which time expression?',
        columns: ['Time expression type', 'Preposition', 'Example'],
        rows: [
          ['Clock time', 'um', 'um 8 Uhr (at 8 o\'clock)'],
          ['Day of the week', 'am', 'am Montag (on Monday)'],
          ['Date', 'am', 'am 3. Mai (on 3 May)'],
          ['Month', 'im', 'im April (in April)'],
          ['Season', 'im', 'im Winter (in winter)'],
          ['Time span (start and end)', 'von ... bis', 'von Montag bis Freitag (from Monday to Friday)'],
          ['Starting point (open-ended)', 'ab', 'ab 9 Uhr (from 9 o\'clock onward)'],
        ],
      },
      {
        id: 'ch32-table-02',
        title: 'am and im are fixed contractions',
        columns: ['Preposition + article', 'Contraction', 'Example'],
        rows: [
          ['an + dem', 'am', 'am Montag'],
          ['in + dem', 'im', 'im Winter'],
        ],
        note: 'In everyday German, an dem and in dem always contract to am and im in these time expressions.',
      },
      {
        id: 'ch32-table-03',
        title: 'Days of the week with am',
        columns: ['Day', 'With am', 'English'],
        rows: [
          ['Montag', 'am Montag', 'on Monday'],
          ['Dienstag', 'am Dienstag', 'on Tuesday'],
          ['Mittwoch', 'am Mittwoch', 'on Wednesday'],
          ['Donnerstag', 'am Donnerstag', 'on Thursday'],
          ['Freitag', 'am Freitag', 'on Friday'],
          ['Samstag', 'am Samstag', 'on Saturday'],
          ['Sonntag', 'am Sonntag', 'on Sunday'],
        ],
      },
    ],
    examples: [
      {
        german: 'Ich stehe um sieben Uhr auf.',
        english: 'I get up at seven o\'clock.',
        highlight: ['um sieben Uhr'],
        explanation: 'um introduces a specific clock time.',
      },
      {
        german: 'Der Unterricht beginnt um neun Uhr.',
        english: 'Class starts at nine o\'clock.',
        highlight: ['um neun Uhr'],
        explanation: 'Clock times always take um, never am or im.',
      },
      {
        german: 'Am Montag habe ich Deutschkurs.',
        english: 'On Monday I have German class.',
        highlight: ['Am Montag'],
        explanation: 'am (= an + dem) is used with days of the week.',
      },
      {
        german: 'Am 3. Mai hat meine Schwester Geburtstag.',
        english: 'My sister\'s birthday is on 3 May.',
        highlight: ['Am 3. Mai'],
        explanation: 'Dates take am, just like days of the week.',
      },
      {
        german: 'Im April fahren wir nach Berlin.',
        english: 'In April we are going to Berlin.',
        highlight: ['Im April'],
        explanation: 'im (= in + dem) is used with months.',
      },
      {
        german: 'Im Winter ist es hier sehr kalt.',
        english: 'In winter it is very cold here.',
        highlight: ['Im Winter'],
        explanation: 'Seasons take im, the same contraction used for months.',
      },
      {
        german: 'Das Geschäft hat von neun bis achtzehn Uhr geöffnet.',
        english: 'The shop is open from nine to six.',
        highlight: ['von neun bis achtzehn Uhr'],
        explanation: 'von ... bis frames a time span that has both a clear start and a clear end.',
      },
      {
        german: 'Ab Montag arbeite ich in der neuen Firma.',
        english: 'From Monday, I am working at the new company.',
        highlight: ['Ab Montag'],
        explanation: 'ab marks an open-ended starting point, with no end mentioned.',
      },
      {
        german: 'Am Wochenende schlafe ich lange.',
        english: 'At the weekend I sleep in.',
        highlight: ['Am Wochenende'],
        explanation: 'Wochenende behaves like a day expression and also takes am.',
      },
      {
        german: 'Im Sommer fahren viele Leute ans Meer.',
        english: 'In summer many people go to the seaside.',
        highlight: ['Im Sommer'],
        explanation: 'Seasons take im; Sommer is one of the four seasons.',
      },
      {
        german: 'Wir treffen uns um halb acht.',
        english: 'We are meeting at half past seven.',
        highlight: ['um halb acht'],
        explanation: 'Even half-hour clock expressions like halb acht still take um.',
      },
      {
        german: 'Ab nächster Woche lerne ich jeden Tag Vokabeln.',
        english: 'From next week on, I will study vocabulary every day.',
        highlight: ['Ab nächster Woche'],
        explanation: 'ab signals an ongoing change starting from a given point, not a closed time span.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'In Montag habe ich Deutschkurs.',
        correct: 'Am Montag habe ich Deutschkurs.',
        explanation: 'Days of the week take am (the contraction of an + dem), not in.',
      },
      {
        incorrect: 'Am April wird es wärmer.',
        correct: 'Im April wird es wärmer.',
        explanation: 'Months take im (the contraction of in + dem), not am.',
      },
      {
        incorrect: 'Ich stehe am sechs Uhr auf.',
        correct: 'Ich stehe um sechs Uhr auf.',
        explanation: 'Clock times take um, not am.',
      },
      {
        incorrect: 'Das Geschäft hat von neun bis um achtzehn Uhr geöffnet.',
        correct: 'Das Geschäft hat von neun bis achtzehn Uhr geöffnet.',
        explanation: 'The second half of a von ... bis pair does not repeat um; bis alone introduces the end point.',
      },
      {
        incorrect: 'In Winter ist es kalt.',
        correct: 'Im Winter ist es kalt.',
        explanation: 'Seasons take the contracted form im, not the uncontracted in.',
      },
    ],
    remember: [
      'um + clock time (um 8 Uhr); am + day/date (am Montag, am 3. Mai); im + month/season (im April, im Winter).',
      'am and im are fixed contractions: am = an + dem, im = in + dem. Learn them as single words, not as two separate words.',
      'von ... bis frames a closed time span with a start and an end (von Montag bis Freitag); ab marks an open-ended starting point with no end mentioned (ab Montag, ab nächster Woche).',
      'When in doubt with a clock time, ask whether it is one specific event (um) or an ongoing situation starting from that point (ab).',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch32-ex-01',
      chapterNumber: 32,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['um', 'clock-time'],
      instruction: 'Choose the correct temporal preposition.',
      prompt: 'Der Kurs beginnt ___ acht Uhr.',
      options: [
        { id: 'a', text: 'um' },
        { id: 'b', text: 'am' },
        { id: 'c', text: 'im' },
        { id: 'd', text: 'an' },
      ],
      correctOptionId: 'a',
      explanation: 'Clock times always take um: um acht Uhr (at eight o\'clock).',
    },
    {
      id: 'ch32-ex-02',
      chapterNumber: 32,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['am', 'day-of-week'],
      instruction: 'Choose the correct temporal preposition.',
      prompt: '___ Montag habe ich Deutschkurs.',
      options: [
        { id: 'a', text: 'am' },
        { id: 'b', text: 'im' },
        { id: 'c', text: 'um' },
        { id: 'd', text: 'an' },
      ],
      correctOptionId: 'a',
      explanation: 'Days of the week take am (an + dem).',
    },
    {
      id: 'ch32-ex-03',
      chapterNumber: 32,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['im', 'season'],
      instruction: 'Choose the correct temporal preposition.',
      prompt: '___ Winter fahren wir Ski.',
      options: [
        { id: 'a', text: 'im' },
        { id: 'b', text: 'am' },
        { id: 'c', text: 'um' },
        { id: 'd', text: 'in' },
      ],
      correctOptionId: 'a',
      explanation: 'Seasons take im (in + dem), not the uncontracted in.',
    },
    {
      id: 'ch32-ex-04',
      chapterNumber: 32,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['am', 'date'],
      instruction: 'Choose the correct temporal preposition.',
      prompt: '___ 3. Mai hat meine Schwester Geburtstag.',
      options: [
        { id: 'a', text: 'am' },
        { id: 'b', text: 'im' },
        { id: 'c', text: 'um' },
        { id: 'd', text: 'an' },
      ],
      correctOptionId: 'a',
      explanation: 'Dates take am, just like days of the week.',
    },
    {
      id: 'ch32-ex-05',
      chapterNumber: 32,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['contraction', 'an-dem'],
      instruction: 'Choose the correct contraction.',
      prompt: 'an + dem = ___',
      options: [
        { id: 'a', text: 'am' },
        { id: 'b', text: 'im' },
        { id: 'c', text: 'ans' },
        { id: 'd', text: 'vom' },
      ],
      correctOptionId: 'a',
      explanation: 'an + dem contracts to am, used for days and dates.',
    },
    {
      id: 'ch32-ex-06',
      chapterNumber: 32,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['contraction', 'in-dem'],
      instruction: 'Choose the correct contraction.',
      prompt: 'in + dem = ___',
      options: [
        { id: 'a', text: 'im' },
        { id: 'b', text: 'am' },
        { id: 'c', text: 'ins' },
        { id: 'd', text: 'vom' },
      ],
      correctOptionId: 'a',
      explanation: 'in + dem contracts to im, used for months and seasons.',
    },
    {
      id: 'ch32-ex-07',
      chapterNumber: 32,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['im', 'season', 'contraction'],
      instruction: 'Choose the form that is actually used in everyday German.',
      prompt: 'Wir fahren ___ Sommer ans Meer.',
      options: [
        { id: 'a', text: 'im' },
        { id: 'b', text: 'in dem' },
        { id: 'c', text: 'am' },
        { id: 'd', text: 'an dem' },
      ],
      correctOptionId: 'a',
      explanation: 'Seasons use the contracted form im; the uncontracted in dem is not used here in everyday speech.',
    },
    {
      id: 'ch32-ex-08',
      chapterNumber: 32,
      order: 8,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['am', 'day-of-week', 'contraction'],
      instruction: 'Choose the correct temporal preposition.',
      prompt: 'Er kommt ___ Freitag zu Besuch.',
      options: [
        { id: 'a', text: 'am' },
        { id: 'b', text: 'im' },
        { id: 'c', text: 'um' },
        { id: 'd', text: 'an' },
      ],
      correctOptionId: 'a',
      explanation: 'Days of the week take am.',
    },
    {
      id: 'ch32-ex-09',
      chapterNumber: 32,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['von-bis', 'time-span'],
      instruction: 'Choose the word that correctly completes the time span.',
      prompt: 'Die Bibliothek ist von neun ___ siebzehn Uhr geöffnet.',
      options: [
        { id: 'a', text: 'bis' },
        { id: 'b', text: 'am' },
        { id: 'c', text: 'im' },
        { id: 'd', text: 'um' },
      ],
      correctOptionId: 'a',
      explanation: 'von ... bis frames a time span; bis introduces the end point and is never replaced by um.',
    },
    {
      id: 'ch32-ex-10',
      chapterNumber: 32,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ab', 'starting-point'],
      instruction: 'Choose the correct temporal preposition.',
      prompt: '___ nächster Woche arbeite ich in Hamburg.',
      options: [
        { id: 'a', text: 'ab' },
        { id: 'b', text: 'am' },
        { id: 'c', text: 'im' },
        { id: 'd', text: 'von' },
      ],
      correctOptionId: 'a',
      explanation: 'ab marks an open-ended starting point (from next week onward); von would need a matching bis.',
    },
    {
      id: 'ch32-ex-11',
      chapterNumber: 32,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['um', 'clock-time', 'ab-vs-um'],
      instruction: 'Choose the preposition that fits a single, specific departure time.',
      prompt: 'Der Zug fährt ___ 14 Uhr nach München.',
      options: [
        { id: 'a', text: 'um' },
        { id: 'b', text: 'ab' },
        { id: 'c', text: 'am' },
        { id: 'd', text: 'im' },
      ],
      correctOptionId: 'a',
      explanation: 'A single specific departure time takes um; ab would suggest an ongoing state starting from 14 Uhr, not one departure.',
    },
    {
      id: 'ch32-ex-12',
      chapterNumber: 32,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['im', 'season'],
      instruction: 'Choose the correct temporal preposition.',
      prompt: '___ Herbst werden die Tage kürzer.',
      options: [
        { id: 'a', text: 'im' },
        { id: 'b', text: 'am' },
        { id: 'c', text: 'um' },
        { id: 'd', text: 'in' },
      ],
      correctOptionId: 'a',
      explanation: 'Seasons take im, the contraction of in + dem.',
    },
    {
      id: 'ch32-ex-13',
      chapterNumber: 32,
      order: 13,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['am', 'day-of-week'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: 'Ich habe ___ Montag Deutschkurs. (Tag / day)',
      acceptedAnswers: ['am'],
      answerMode: 'caseInsensitive',
      placeholder: 'am',
      maxLength: 10,
      explanation: 'Days of the week take am (an + dem).',
    },
    {
      id: 'ch32-ex-14',
      chapterNumber: 32,
      order: 14,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['im', 'season'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: 'Wir fahren ___ Winter nach Österreich. (Jahreszeit / season)',
      acceptedAnswers: ['im'],
      answerMode: 'caseInsensitive',
      placeholder: 'im',
      maxLength: 10,
      explanation: 'Seasons take im (in + dem).',
    },
    {
      id: 'ch32-ex-15',
      chapterNumber: 32,
      order: 15,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['um', 'clock-time'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: 'Der Film beginnt ___ zwanzig Uhr. (Uhrzeit / clock time)',
      acceptedAnswers: ['um'],
      answerMode: 'caseInsensitive',
      placeholder: 'um',
      maxLength: 10,
      explanation: 'Clock times take um.',
    },
    {
      id: 'ch32-ex-16',
      chapterNumber: 32,
      order: 16,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['ab', 'starting-point'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: '___ nächstem Jahr lerne ich Spanisch. (Startpunkt / starting point)',
      acceptedAnswers: ['ab'],
      answerMode: 'caseInsensitive',
      placeholder: 'ab',
      maxLength: 10,
      explanation: 'ab marks an open-ended starting point: from next year onward.',
    },
    {
      id: 'ch32-ex-17',
      chapterNumber: 32,
      order: 17,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['von-bis', 'time-span'],
      instruction: 'Write the missing word. Capitalisation is not checked.',
      prompt: 'Das Geschäft ist von acht ___ achtzehn Uhr geöffnet.',
      acceptedAnswers: ['bis'],
      answerMode: 'caseInsensitive',
      placeholder: 'bis',
      maxLength: 10,
      explanation: 'von ... bis frames a time span; bis introduces the end point.',
    },
    {
      id: 'ch32-ex-18',
      chapterNumber: 32,
      order: 18,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['am', 'date'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: '___ 3. Oktober ist ein Feiertag in Deutschland.',
      acceptedAnswers: ['am'],
      answerMode: 'caseInsensitive',
      placeholder: 'am',
      maxLength: 10,
      explanation: 'Dates take am, just like days of the week.',
    },
    {
      id: 'ch32-ex-19',
      chapterNumber: 32,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['im', 'season'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: '___ Frühling blühen die Blumen.',
      acceptedAnswers: ['im'],
      answerMode: 'caseInsensitive',
      placeholder: 'im',
      maxLength: 10,
      explanation: 'Seasons take im.',
    },
    {
      id: 'ch32-ex-20',
      chapterNumber: 32,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['um', 'clock-time'],
      instruction: 'Write the correct preposition. Capitalisation is not checked.',
      prompt: 'Wir treffen uns ___ halb sieben vor dem Kino.',
      acceptedAnswers: ['um'],
      answerMode: 'caseInsensitive',
      placeholder: 'um',
      maxLength: 10,
      explanation: 'Clock times, including half-hour expressions like halb sieben, take um.',
    },
    {
      id: 'ch32-ex-21',
      chapterNumber: 32,
      order: 21,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['am', 'error-correction'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: In Montag habe ich frei.',
      acceptedAnswers: ['Am Montag habe ich frei.'],
      answerMode: 'normalized',
      placeholder: 'Am Montag ...',
      maxLength: 60,
      explanation: 'Days of the week take am (an + dem), not in.',
    },
    {
      id: 'ch32-ex-22',
      chapterNumber: 32,
      order: 22,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['im', 'error-correction'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Am April wird es wärmer.',
      acceptedAnswers: ['Im April wird es wärmer.'],
      answerMode: 'normalized',
      placeholder: 'Im April ...',
      maxLength: 60,
      explanation: 'Months take im (in + dem), not am.',
    },
    {
      id: 'ch32-ex-23',
      chapterNumber: 32,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['um', 'error-correction'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich stehe am sechs Uhr auf.',
      acceptedAnswers: ['Ich stehe um sechs Uhr auf.'],
      answerMode: 'normalized',
      placeholder: 'Ich stehe ...',
      maxLength: 60,
      explanation: 'Clock times take um, not am.',
    },
    {
      id: 'ch32-ex-24',
      chapterNumber: 32,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['um', 'sentence-building', 'clock-time'],
      instruction:
        'Write a complete sentence using the cues and the correct temporal preposition. Capitalisation is checked; no full stop is required.',
      prompt: 'das Konzert – beginnen – 21 Uhr (um)',
      acceptedAnswers: ['Das Konzert beginnt um 21 Uhr.', 'Das Konzert beginnt um 21 Uhr'],
      answerMode: 'normalized',
      placeholder: 'Das Konzert beginnt ...',
      maxLength: 60,
      explanation: 'Clock times take um: Das Konzert beginnt um 21 Uhr.',
    },
  ],
};
