import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter081: ChapterDefinition = {
  id: 'chapter-081',
  number: 81,
  slug: 'comparative-constructions-with-je-desto',
  title: 'Comparative Constructions with je ... desto',
  germanTitle: 'Je-desto-Sätze',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Build proportional comparisons with je ... desto (and its interchangeable variant je ... umso): place a comparative form directly after je to open a verb-final subordinate clause, place a matching comparative directly after desto/umso to open a verb-second main clause in which the finite verb immediately follows the desto/umso + comparative unit, and correctly punctuate the comma between the two clauses.',
  prerequisites: [42, 43],
  estimatedMinutes: 30,
  tags: [
    'je-desto',
    'umso',
    'proportional-comparison',
    'comparative',
    'verb-final',
    'verb-second',
    'subordinate-clause',
    'word-order',
    'position-one',
    'punctuation',
  ],
  explanation: {
    introduction: [
      'German expresses a proportional relationship — "the more X, the more Y" — with the two-part construction je ... desto (or je ... umso): Je mehr er lernt, desto besser wird er. (The more he studies, the better he gets.) The first clause states a changing condition; the second clause states the change that results from it.',
      'This construction combines two word-order patterns you already know separately. The je-clause is a subordinate clause, so the finite verb goes to the very end, exactly like after weil or dass. The desto/umso-clause is a main clause in which desto (or umso) plus a comparative fills position 1, so the finite verb comes second, directly after that unit, and the subject follows.',
      'Both clauses always contain a comparative form, reusing exactly the comparative forms from Chapter 42 (regular -er, umlaut, and the five irregulars) — je and desto/umso are never followed by the plain, uncompared form of an adjective or adverb. A comma always separates the two clauses.',
    ],
    rules: [
      {
        id: 'ch81-rule-01',
        heading: 'The basic pattern: je ... desto/umso for proportional comparison',
        paragraphs: [
          'German expresses a proportional relationship — as one thing changes, another changes with it — with the two-part construction je ... desto (or je ... umso): Je mehr er lernt, desto besser wird er. (The more he studies, the better he gets.) The je-clause states the changing condition; the desto/umso-clause states the resulting change.',
          'Unlike the paired conjunctions from Chapter 80, je and desto/umso do not join two parallel elements of equal rank — they link a subordinate clause to a main clause, and each clause has its own distinct word order, covered in the next two rules.',
        ],
      },
      {
        id: 'ch81-rule-02',
        heading: 'Verb-final order after je',
        paragraphs: [
          'je is a subordinating conjunction, so it behaves like weil, dass, or wenn: it pushes the finite verb to the very end of its clause. Je mehr Zeit ich habe, ... (The more time I have, ...) — habe is delayed to the end, exactly as in Ich weiß, dass ich mehr Zeit habe.',
          'The comparative form (mehr, älter, schneller, ...) comes directly after je, at the very front of the clause; the subject and any objects follow, with the finite verb last: Je öfter sie übt, ... — subject sie, then the verb übt at the very end.',
        ],
      },
      {
        id: 'ch81-rule-03',
        heading: 'Verb-second order after desto/umso',
        paragraphs: [
          'desto (or umso) plus its comparative form together occupy position 1 of the second clause, exactly like any other element that opens a German main clause. The finite verb therefore comes second — directly after desto + comparative — and the subject follows the verb: desto besser wird er (desto besser = position 1, wird = verb in position 2, er = subject).',
          'Never separate desto from its comparative, and never insert the verb between them: desto wird er besser is wrong. The verb must come right after the whole desto besser unit, not inside it.',
        ],
      },
      {
        id: 'ch81-rule-04',
        heading: 'The comma before desto/umso',
        paragraphs: [
          'A comma always separates the je-clause from the desto/umso-clause, exactly as a comma separates any subordinate clause from the clause it depends on: Je mehr er lernt, desto besser wird er.',
          'Leaving out the comma is a punctuation mistake even when the sentence is still understandable — the comma is required, not optional, in written German.',
        ],
      },
      {
        id: 'ch81-rule-05',
        heading: 'je and desto/umso must be followed directly by a comparative',
        paragraphs: [
          'Both je and desto/umso require an immediately following comparative form — never the plain (positive) form of the adjective or adverb: je mehr, je besser, je schneller; desto mehr, desto besser, desto schneller. Je viel or desto gut are ungrammatical; the comparative (mehr, besser) must be used instead.',
          'When the comparative modifies a noun, the noun follows the comparative, and the whole phrase still counts as a single unit at the front of the clause: je mehr Geld, desto mehr Zeit.',
        ],
      },
      {
        id: 'ch81-rule-06',
        heading: 'Reusing the comparative forms from Chapter 42',
        paragraphs: [
          'The je ... desto construction uses exactly the same comparative forms you already learned: the irregulars gut/besser, viel/mehr, gern/lieber, hoch/höher, nah/näher, and the umlaut comparatives such as alt/älter, groß/größer, lang/länger, kurz/kürzer, warm/wärmer, kalt/kälter, stark/stärker. No new comparative forms exist for this construction — only the sentence pattern around them is new.',
        ],
      },
      {
        id: 'ch81-rule-07',
        heading: 'umso as an interchangeable alternative to desto',
        paragraphs: [
          'umso can replace desto in any je ... desto sentence with no change in meaning or word order: Je mehr sie übt, umso sicherer wird sie. means exactly the same as ... desto sicherer wird sie. desto is more frequent overall, but umso is common too, especially in written and somewhat more formal German.',
          'umso (not desto) is also occasionally used on its own, without a preceding je-clause, to mean "all the more": Er hat hart gearbeitet — umso verdienter ist sein Erfolg. This standalone use is less common and not the focus of this chapter, but it helps to recognize it.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch81-table-01',
        title: 'The je ... desto sentence pattern',
        columns: ['Clause', 'Opening element (position 1)', 'Verb position', 'Example'],
        rows: [
          [
            'je-clause (subordinate)',
            'je + comparative',
            'verb-final (finite verb at the very end)',
            'Je mehr er lernt',
          ],
          [
            'desto/umso-clause (main)',
            'desto/umso + comparative',
            'verb-second (finite verb right after the position-1 unit)',
            'desto besser wird er',
          ],
        ],
        note: 'Join the two clauses with a comma: Je mehr er lernt, desto besser wird er.',
      },
      {
        id: 'ch81-table-02',
        title: 'Comparative forms reused in je ... desto sentences',
        columns: ['Base form', 'Comparative', 'Example with je ... desto'],
        rows: [
          ['gut', 'besser', 'Je mehr er übt, desto besser wird er.'],
          ['viel', 'mehr', 'Je mehr Geld sie verdient, desto mehr gibt sie aus.'],
          ['gern', 'lieber', 'Je mehr Zeit sie hat, desto lieber liest sie.'],
          ['hoch', 'höher', 'Je höher die Preise steigen, desto weniger kaufen die Leute.'],
          ['nah', 'näher', 'Je näher der Termin rückt, desto nervöser wird er.'],
          ['alt', 'älter', 'Je älter man wird, desto weiser wird man.'],
          ['groß', 'größer', 'Je größer das Haus ist, desto teurer ist die Miete.'],
          ['lang', 'länger', 'Je länger der Winter dauert, desto ungeduldiger werden die Leute.'],
          ['kurz', 'kürzer', 'Je kürzer die Tage werden, desto früher wird es dunkel.'],
          ['warm', 'wärmer', 'Je wärmer es wird, desto mehr Leute gehen schwimmen.'],
          ['kalt', 'kälter', 'Je kälter es draußen ist, desto länger bleiben wir drinnen.'],
          ['stark', 'stärker', 'Je stärker der Wind weht, desto höher werden die Wellen.'],
        ],
        note: 'These are the same comparative forms from Chapter 42 — no new forms exist for the je ... desto construction.',
      },
    ],
    examples: [
      {
        german: 'Je mehr er lernt, desto besser wird er.',
        english: 'The more he studies, the better he gets.',
        highlight: ['Je mehr', 'desto besser'],
        explanation:
          'je mehr er lernt keeps the verb (lernt) at the end; desto besser wird er has the verb (wird) directly after desto besser.',
      },
      {
        german: 'Je älter man wird, desto weiser wird man.',
        english: 'The older one gets, the wiser one becomes.',
        highlight: ['Je älter', 'desto weiser'],
        explanation: 'alt has the umlaut comparative älter; both clauses follow the standard je ... desto word order.',
      },
      {
        german: 'Je schneller du fährst, desto gefährlicher wird es.',
        english: 'The faster you drive, the more dangerous it becomes.',
        highlight: ['Je schneller', 'desto gefährlicher'],
        explanation: 'A regular -er comparative in both clauses; fährst and wird show verb-final and verb-second order.',
      },
      {
        german: 'Je mehr Geld sie verdient, desto mehr gibt sie aus.',
        english: 'The more money she earns, the more she spends.',
        highlight: ['Je mehr Geld', 'desto mehr'],
        explanation:
          'mehr Geld (comparative + noun) forms one unit after je; the separable verb ausgeben splits as gibt ... aus in the verb-second clause.',
      },
      {
        german: 'Je länger der Winter dauert, desto ungeduldiger werden die Leute.',
        english: 'The longer the winter lasts, the more impatient people become.',
        highlight: ['Je länger', 'desto ungeduldiger'],
        explanation: 'lang takes the umlaut comparative länger; the desto-clause subject die Leute follows the verb werden.',
      },
      {
        german: 'Je früher wir aufstehen, desto mehr schaffen wir.',
        english: 'The earlier we get up, the more we get done.',
        highlight: ['Je früher', 'desto mehr'],
        explanation:
          'The separable verb aufstehen stays together at the end of the verb-final je-clause, just as it does after weil or dass.',
      },
      {
        german: 'Je weniger er isst, desto schwächer fühlt er sich.',
        english: 'The less he eats, the weaker he feels.',
        highlight: ['Je weniger', 'desto schwächer'],
        explanation: 'wenig forms its comparative regularly as weniger; the reflexive pronoun sich follows the subject er after inversion.',
      },
      {
        german: 'Je heißer es wird, desto mehr Wasser trinken wir.',
        english: 'The hotter it gets, the more water we drink.',
        highlight: ['Je heißer', 'desto mehr Wasser'],
        explanation: 'desto mehr Wasser (comparative + noun) fills position 1 as a unit; the verb trinken follows directly.',
      },
      {
        german: 'Je besser du Deutsch sprichst, desto leichter findest du einen Job.',
        english: 'The better you speak German, the more easily you will find a job.',
        highlight: ['Je besser', 'desto leichter'],
        explanation: 'gut has the irregular comparative besser, used here adverbially to modify sprichst.',
      },
      {
        german: 'Je öfter sie übt, desto sicherer wird sie.',
        english: 'The more often she practices, the more confident she becomes.',
        highlight: ['Je öfter', 'desto sicherer'],
        explanation: 'A regular comparative of the adverb oft; both clauses follow the standard pattern.',
      },
      {
        german: 'Je näher der Prüfungstermin rückt, desto nervöser wird er.',
        english: 'The closer the exam date gets, the more nervous he becomes.',
        highlight: ['Je näher', 'desto nervöser'],
        explanation: 'nah has the irregular comparative näher, with an inserted h.',
      },
      {
        german: 'Je mehr man hat, desto mehr will man.',
        english: 'The more one has, the more one wants.',
        highlight: ['Je mehr', 'desto mehr'],
        explanation: 'A common proverb-like sentence: the same comparative, mehr, appears in both clauses.',
      },
      {
        german: 'Je mehr sie übt, umso sicherer wird sie.',
        english: 'The more she practices, the more confident she becomes.',
        highlight: ['umso sicherer'],
        explanation: 'umso replaces desto here with no change in meaning or word order.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Je mehr lernt er, desto besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'je opens a subordinate clause, so the finite verb must stand at the very end (lernt), not in second position as in a main clause.',
      },
      {
        incorrect: 'Je mehr er lernt, desto wird er besser.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'desto and its comparative form one inseparable unit in position 1; the finite verb must come directly after desto besser, not be inserted between them.',
      },
      {
        incorrect: 'Je mehr er lernt desto besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation: 'A comma is always required between the je-clause and the desto/umso-clause.',
      },
      {
        incorrect: 'Je er mehr lernt, desto besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'The comparative must come directly after je, not after the subject; je mehr forms a fixed unit at the very start of the clause.',
      },
      {
        incorrect: 'Je viel er arbeitet, desto müder wird er.',
        correct: 'Je mehr er arbeitet, desto müder wird er.',
        explanation: 'viel is irregular; only its comparative form mehr may follow je, never the plain base form viel.',
      },
      {
        incorrect: 'Desto mehr er lernt, je besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'The clause order is fixed: je opens the condition clause and desto/umso opens the result clause; swapping the two conjunctions is incorrect.',
      },
    ],
    remember: [
      'Pattern: je + comparative + verb-final clause, desto/umso + comparative + verb-second clause.',
      'je is a subordinating conjunction: it sends the finite verb to the very end of its clause.',
      'desto (or umso) plus the comparative together fill position 1 of the second clause, so the finite verb comes immediately after them, then the subject.',
      'Always place a comma between the je-clause and the desto/umso-clause.',
      'je and desto/umso must each be followed directly by a comparative — never by the plain base form (je mehr, not je viel).',
      'umso is used exactly like desto and can replace it anywhere; desto is simply more common.',
      'Reuse the comparative forms you already know, including the irregulars (mehr, besser, lieber, höher, näher) and the umlaut forms (älter, größer, länger, kürzer, wärmer, kälter, stärker).',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 26,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch81-ex-01',
      chapterNumber: 81,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'conjunction-choice'],
      instruction: 'Choose the word that opens the subordinate (verb-final) clause.',
      prompt: 'Welches Wort leitet den Nebensatz (Verb am Ende) einer proportionalen Vergleichskonstruktion ein?',
      options: [
        { id: 'a', text: 'je' },
        { id: 'b', text: 'desto' },
        { id: 'c', text: 'wenn' },
        { id: 'd', text: 'als' },
      ],
      correctOptionId: 'a',
      explanation: 'je is the subordinating conjunction that opens the je-clause and sends the finite verb to the end.',
    },
    {
      id: 'ch81-ex-02',
      chapterNumber: 81,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'conjunction-choice'],
      instruction: 'Choose the word that opens the following main (verb-second) clause.',
      prompt: 'Welches Wort leitet den Hauptsatz (Verb an zweiter Stelle) ein, der auf den je-Satz folgt?',
      options: [
        { id: 'a', text: 'desto' },
        { id: 'b', text: 'dass' },
        { id: 'c', text: 'weil' },
        { id: 'd', text: 'obwohl' },
      ],
      correctOptionId: 'a',
      explanation: 'desto (or umso) opens the following main clause, together with a comparative, and triggers verb-second order.',
    },
    {
      id: 'ch81-ex-03',
      chapterNumber: 81,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ er lernt, desto besser wird er.',
      options: [
        { id: 'a', text: 'mehr' },
        { id: 'b', text: 'viel' },
        { id: 'c', text: 'mehrer' },
        { id: 'd', text: 'meister' },
      ],
      correctOptionId: 'a',
      explanation: 'viel is irregular; its comparative form is mehr, not viel or mehrer.',
    },
    {
      id: 'ch81-ex-04',
      chapterNumber: 81,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je mehr er lernt, desto ___ wird er.',
      options: [
        { id: 'a', text: 'besser' },
        { id: 'b', text: 'guter' },
        { id: 'c', text: 'gutier' },
        { id: 'd', text: 'mehr' },
      ],
      correctOptionId: 'a',
      explanation: 'gut has the irregular comparative besser.',
    },
    {
      id: 'ch81-ex-05',
      chapterNumber: 81,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ man wird, desto weiser wird man.',
      options: [
        { id: 'a', text: 'älter' },
        { id: 'b', text: 'alter' },
        { id: 'c', text: 'ältester' },
        { id: 'd', text: 'mehr alt' },
      ],
      correctOptionId: 'a',
      explanation: 'alt takes an umlaut in the comparative: alt -> älter.',
    },
    {
      id: 'ch81-ex-06',
      chapterNumber: 81,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ die Preise steigen, desto weniger kaufen die Leute.',
      options: [
        { id: 'a', text: 'höher' },
        { id: 'b', text: 'hocher' },
        { id: 'c', text: 'höcher' },
        { id: 'd', text: 'hochster' },
      ],
      correctOptionId: 'a',
      explanation: 'hoch is irregular: hoch -> höher (the ch drops).',
    },
    {
      id: 'ch81-ex-07',
      chapterNumber: 81,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ der Prüfungstermin rückt, desto nervöser wird er.',
      options: [
        { id: 'a', text: 'näher' },
        { id: 'b', text: 'naher' },
        { id: 'c', text: 'nächer' },
        { id: 'd', text: 'nährer' },
      ],
      correctOptionId: 'a',
      explanation: 'nah is irregular: nah -> näher (an extra h is inserted).',
    },
    {
      id: 'ch81-ex-08',
      chapterNumber: 81,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-final'],
      instruction: 'Choose the sentence with correct word order in the je-clause.',
      prompt: 'Welcher Satz hat die richtige Wortstellung im je-Satz?',
      options: [
        { id: 'a', text: 'Je mehr er lernt, desto besser wird er.' },
        { id: 'b', text: 'Je mehr lernt er, desto besser wird er.' },
        { id: 'c', text: 'Je er mehr lernt, desto besser wird er.' },
      ],
      correctOptionId: 'a',
      explanation:
        'je introduces a subordinate clause, so the finite verb (lernt) must stand at the very end, directly after the subject er; it cannot appear in second position or before the comparative.',
    },
    {
      id: 'ch81-ex-09',
      chapterNumber: 81,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-second'],
      instruction: 'Choose the sentence with correct word order in the desto-clause.',
      prompt: 'Welcher Satz hat die richtige Wortstellung im desto-Satz?',
      options: [
        { id: 'a', text: 'Je mehr er lernt, desto besser wird er.' },
        { id: 'b', text: 'Je mehr er lernt, desto wird er besser.' },
        { id: 'c', text: 'Je mehr er lernt, desto er wird besser.' },
      ],
      correctOptionId: 'a',
      explanation:
        'desto plus the comparative (desto besser) fills position 1, so the finite verb (wird) must come immediately afterward, then the subject (er).',
    },
    {
      id: 'ch81-ex-10',
      chapterNumber: 81,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['punctuation', 'comma'],
      instruction: 'Choose the sentence with correct comma placement.',
      prompt: 'Welcher Satz ist richtig mit Komma?',
      options: [
        { id: 'a', text: 'Je mehr er lernt, desto besser wird er.' },
        { id: 'b', text: 'Je mehr er lernt desto besser wird er.' },
        { id: 'c', text: 'Je, mehr er lernt, desto besser wird er.' },
      ],
      correctOptionId: 'a',
      explanation: 'A comma always separates the je-clause from the desto/umso-clause; no comma is placed after je itself.',
    },
    {
      id: 'ch81-ex-11',
      chapterNumber: 81,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['umso', 'je-desto-pattern'],
      instruction: 'Choose the word that can replace desto without changing the meaning.',
      prompt: 'Welches Wort kann desto ersetzen, ohne die Bedeutung zu verändern?',
      options: [
        { id: 'a', text: 'umso' },
        { id: 'b', text: 'also' },
        { id: 'c', text: 'dann' },
        { id: 'd', text: 'weil' },
      ],
      correctOptionId: 'a',
      explanation: 'umso is fully interchangeable with desto in this construction.',
    },
    {
      id: 'ch81-ex-12',
      chapterNumber: 81,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'separable-verb'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Welcher Satz hat die richtige Wortstellung?',
      options: [
        { id: 'a', text: 'Je mehr Geld sie verdient, desto mehr gibt sie aus.' },
        { id: 'b', text: 'Je mehr Geld verdient sie, desto mehr gibt sie aus.' },
        { id: 'c', text: 'Je mehr Geld sie verdient, desto sie gibt mehr aus.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The je-clause keeps the finite verb (verdient) at the end; the desto-clause has desto mehr in position 1 followed immediately by the verb (gibt), then the subject (sie), with the separable prefix aus at the end.',
    },
    {
      id: 'ch81-ex-13',
      chapterNumber: 81,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['je-desto-pattern', 'pragmatics'],
      instruction: 'Choose the sentence that matches how Jonas feels as the exam gets closer.',
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Wie fühlst du dich vor der Prüfung?',
          english: 'How do you feel before the exam?',
        },
        {
          speaker: 'Jonas',
          german: 'Ehrlich gesagt panisch: ___',
          english: 'Honestly, panicked: ...',
        },
      ],
      prompt: '___',
      options: [
        { id: 'a', text: 'Je näher der Prüfungstermin rückt, desto nervöser wird er.' },
        { id: 'b', text: 'Je näher rückt der Prüfungstermin, desto wird er nervöser.' },
        { id: 'c', text: 'Näher der Prüfungstermin rückt, je nervöser wird er.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Only option a has verb-final order in the je-clause (rückt at the end) and verb-second order right after desto nervöser in the second clause.',
    },
    {
      id: 'ch81-ex-14',
      chapterNumber: 81,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'word-order', 'separable-verb'],
      instruction: "Choose the German sentence that correctly expresses: 'The earlier we get up, the more we get done.'",
      prompt:
        "Welcher Satz drückt korrekt aus: 'The earlier we get up, the more we get done'?",
      options: [
        { id: 'a', text: 'Je früher wir aufstehen, desto mehr schaffen wir.' },
        { id: 'b', text: 'Je früher stehen wir auf, desto mehr schaffen wir.' },
        { id: 'c', text: 'Je wir früher aufstehen, desto schaffen wir mehr.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Only option a keeps aufstehen together at the end of the verb-final je-clause and puts schaffen directly after desto mehr in the verb-second clause.',
    },
    {
      id: 'ch81-ex-15',
      chapterNumber: 81,
      order: 15,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'conjunction-choice'],
      instruction: 'Fill in the missing first word. Capitalisation is not checked.',
      prompt: '___ mehr er lernt, desto besser wird er.',
      acceptedAnswers: ['je'],
      answerMode: 'caseInsensitive',
      placeholder: 'je',
      maxLength: 10,
      explanation: 'je opens the subordinate clause of this proportional comparison.',
    },
    {
      id: 'ch81-ex-16',
      chapterNumber: 81,
      order: 16,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'umso'],
      instruction: 'Fill in the missing word (desto or umso both work). Capitalisation is not checked.',
      prompt: 'Je mehr er lernt, ___ besser wird er.',
      acceptedAnswers: ['desto', 'umso'],
      answerMode: 'caseInsensitive',
      placeholder: 'desto/umso',
      maxLength: 10,
      explanation: 'Either desto or umso can open the main clause here; both work identically.',
    },
    {
      id: 'ch81-ex-17',
      chapterNumber: 81,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (viel) er arbeitet, desto müder wird er.',
      acceptedAnswers: ['mehr'],
      answerMode: 'caseInsensitive',
      placeholder: 'mehr',
      maxLength: 10,
      explanation: "viel's comparative is mehr.",
    },
    {
      id: 'ch81-ex-18',
      chapterNumber: 81,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je mehr er arbeitet, desto ___ (müde) wird er.',
      acceptedAnswers: ['müder'],
      answerMode: 'caseInsensitive',
      placeholder: 'müder',
      maxLength: 15,
      explanation: 'müde is regular: müde -> müder.',
    },
    {
      id: 'ch81-ex-19',
      chapterNumber: 81,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je frischer die Bohnen sind, desto ___ (gut) schmeckt der Kaffee.',
      acceptedAnswers: ['besser'],
      answerMode: 'caseInsensitive',
      placeholder: 'besser',
      maxLength: 15,
      explanation: "gut's comparative is besser.",
    },
    {
      id: 'ch81-ex-20',
      chapterNumber: 81,
      order: 20,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je mehr Zeit sie hat, desto ___ (gern) liest sie.',
      acceptedAnswers: ['lieber'],
      answerMode: 'caseInsensitive',
      placeholder: 'lieber',
      maxLength: 15,
      explanation: "gern's comparative is lieber.",
    },
    {
      id: 'ch81-ex-21',
      chapterNumber: 81,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (wenig) er isst, desto schwächer fühlt er sich.',
      acceptedAnswers: ['weniger'],
      answerMode: 'caseInsensitive',
      placeholder: 'weniger',
      maxLength: 15,
      explanation: "wenig's comparative is weniger.",
    },
    {
      id: 'ch81-ex-22',
      chapterNumber: 81,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'word-order'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Er lernt viel. Er wird besser.',
      acceptedAnswers: ['Je mehr er lernt, desto besser wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr er lernt, desto ...',
      maxLength: 60,
      explanation:
        'je mehr er lernt keeps the verb (lernt) at the end; desto besser wird er places the verb (wird) directly after desto besser.',
    },
    {
      id: 'ch81-ex-23',
      chapterNumber: 81,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'word-order', 'umlaut-comparative'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Man wird alt. Man wird weise.',
      acceptedAnswers: ['Je älter man wird, desto weiser wird man.'],
      answerMode: 'normalized',
      placeholder: 'Je älter man wird, desto ...',
      maxLength: 60,
      explanation: 'alt has the umlaut comparative älter; both clauses follow the standard je ... desto word order.',
    },
    {
      id: 'ch81-ex-24',
      chapterNumber: 81,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sentence-formation', 'word-order'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Du fährst schnell. Es wird gefährlich.',
      acceptedAnswers: ['Je schneller du fährst, desto gefährlicher wird es.'],
      answerMode: 'normalized',
      placeholder: 'Je schneller du fährst, desto ...',
      maxLength: 70,
      explanation: 'fährst keeps the je-clause verb-final; wird stands directly after desto gefährlicher in the second clause.',
    },
    {
      id: 'ch81-ex-25',
      chapterNumber: 81,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sentence-formation', 'word-order', 'separable-verb'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Wir stehen früh auf. Wir schaffen mehr.',
      acceptedAnswers: ['Je früher wir aufstehen, desto mehr schaffen wir.'],
      answerMode: 'normalized',
      placeholder: 'Je früher wir aufstehen, desto ...',
      maxLength: 70,
      explanation:
        'The separable verb aufstehen stays together at the end of the verb-final je-clause; schaffen follows directly after desto mehr.',
    },
    {
      id: 'ch81-ex-26',
      chapterNumber: 81,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'word-order'],
      instruction: 'Correct the mistake. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Je mehr er lernt, desto wird er besser.',
      acceptedAnswers: ['Je mehr er lernt, desto besser wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr er lernt, desto ...',
      maxLength: 60,
      explanation:
        'desto and its comparative form one inseparable unit in position 1; the finite verb (wird) must come directly after desto besser, not before it.',
    },
    {
      id: 'ch81-ex-27',
      chapterNumber: 81,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'punctuation', 'comma'],
      instruction: 'Correct the mistake. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Je mehr er lernt desto besser wird er.',
      acceptedAnswers: ['Je mehr er lernt, desto besser wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr er lernt, desto ...',
      maxLength: 60,
      explanation: 'A comma is always required between the je-clause and the desto/umso-clause.',
    },
    {
      id: 'ch81-ex-28',
      chapterNumber: 81,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['umso', 'sentence-formation'],
      instruction:
        'Rewrite the sentence using umso instead of desto. Capitalisation and punctuation are checked.',
      prompt: 'Schreibe mit umso statt desto: Je mehr sie übt, desto sicherer wird sie.',
      acceptedAnswers: ['Je mehr sie übt, umso sicherer wird sie.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr sie übt, umso ...',
      maxLength: 60,
      explanation: 'umso replaces desto with no change in meaning or word order.',
    },
  ],
};
