import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter043: ChapterDefinition = {
  id: 'chapter-043',
  number: 43,
  slug: 'superlative-forms',
  title: 'Superlative Forms',
  germanTitle: 'Der Superlativ',
  level: 'A2',
  section: 'adjectives-1',
  objective:
    'Form the German superlative in both its predicative/adverbial form (am schnellsten) and its attributive form (der/die/das schnellste), apply the -est- spelling rule after s/ß/z/d/t and sibilants, use the small set of irregular superlatives (gut/best-, viel/meist-, hoch/höchst-, nah/nächst-), and choose the right construction when comparing three or more things.',
  prerequisites: [40, 41, 42],
  estimatedMinutes: 25,
  tags: [
    'superlative',
    'superlativ',
    'am -sten',
    'adjective endings',
    'irregular superlatives',
    'comparison',
    'adjectives',
  ],
  explanation: {
    introduction: [
      'The comparative (Chapter 42) lets you compare two things: schneller als (faster than). The superlative goes one step further — it picks out the single most extreme item in a group of three or more: Das ist das schnellste Auto. (That is the fastest car.)',
      'German has exactly one superlative form for each adjective, but it appears in two different shapes depending on its job in the sentence: the predicative/adverbial shape am schnellsten (used after sein or with a verb) and the attributive shape der/die/das schnellste (used directly before a noun, with an adjective ending). Learning to recognise which shape a sentence needs is the main skill of this chapter.',
    ],
    rules: [
      {
        id: 'ch43-rule-01',
        heading: 'Two shapes, one job: singling out the extreme',
        paragraphs: [
          'The superlative marks the highest degree of a quality within a group of at least three items. English usually adds "-est" or "most" (fastest, most beautiful); German always adds -st or -est to the adjective stem, then chooses one of two surrounding constructions.',
          'Dieses Auto ist am schnellsten. (This car is the fastest — predicative.) Das ist das schnellste Auto. (That is the fastest car — attributive.) Both sentences say the same thing about the car, but the grammar around the superlative differs.',
        ],
      },
      {
        id: 'ch43-rule-02',
        heading: 'The predicative/adverbial superlative: am ...-sten',
        paragraphs: [
          'When the superlative stands alone after sein (to be), werden (to become), or describes how an action is done (adverbially, after a verb), German uses am + adjective-stem + -sten. This am ...-sten form never changes, no matter the gender or number of the noun it refers to.',
          'Im Winter ist es am kältesten. (In winter it is the coldest.) Er läuft am schnellsten. (He runs the fastest.) In both cases am ...-sten is fixed and uninflected — there is no article agreement to worry about.',
        ],
      },
      {
        id: 'ch43-rule-03',
        heading: 'The attributive superlative: der/die/das ...-ste',
        paragraphs: [
          'When the superlative stands directly before a noun, it needs a definite article (der/die/das, matching the gender, number, and case of the noun) and the normal adjective ending you already know from weak-declension endings after der-words.',
          'Das ist der schnellste Zug. (That is the fastest train — masculine nominative, ending -e.) Ich fahre mit dem schnellsten Zug. (I am travelling with the fastest train — masculine dative, ending -en.) The article and the ending change with case; the superlative stem schnellst- stays the same.',
        ],
      },
      {
        id: 'ch43-rule-04',
        heading: 'Forming the stem: add -st, or -est after certain sounds',
        paragraphs: [
          'Most adjectives simply add -st to the comparative-free stem: schnell → schnellst-, klein → kleinst-, billig → billigst-.',
          'Adjectives ending in -d, -t, -s, -ß, -z, or a sibilant sound (schön with its consonant cluster is fine, but words like laut, heiß, kurz are not) add -est instead, to keep the ending pronounceable: alt → ältest-, laut → lautest-, heiß → heißest-, kurz → kürzest-, intelligent → intelligentest-. Adjectives already ending in -sch also take -est: hübsch → hübschest-.',
          'A small group of one-syllable adjectives with a, o, or u in the stem also add an umlaut in the superlative, exactly as they do in the comparative: alt → älter → ältest-, groß → größer → größt-, jung → jünger → jüngst-, kurz → kürzer → kürzest-.',
        ],
      },
      {
        id: 'ch43-rule-05',
        heading: 'Irregular superlatives',
        paragraphs: [
          'A few very common adjectives and adverbs do not follow the regular pattern at all and must be memorised: gut (good) → besser → best-, viel (much) → mehr → meist-, hoch (high) → höher → höchst- (note: the -ch drops before the ending), and gern (gladly) → lieber → liebst-.',
          'Nah (near) is regular in shape but changes its consonant: nah → näher → nächst-. All of these combine with am ...-en/-sten or der/die/das ...-e exactly like regular superlatives: am besten, der beste; am höchsten, die höchste; am nächsten, das nächste.',
        ],
      },
      {
        id: 'ch43-rule-06',
        heading: 'Comparing three or more things',
        paragraphs: [
          'While the comparative compares exactly two items with als (Peter ist größer als Tom), the superlative is used once you are comparing three or more items and want to name the single extreme one: Peter ist am größten von den dreien. (Peter is the tallest of the three.)',
          'The group being compared is often introduced with von + dative (von den dreien, von allen Schülern) or in + dative (in der Klasse, in der Familie): Peter ist der größte Schüler in der Klasse. (Peter is the tallest student in the class.)',
        ],
      },
    ],
    tables: [
      {
        id: 'ch43-table-01',
        title: 'Attributive vs. predicative/adverbial superlative',
        columns: ['Use', 'Construction', 'Example'],
        rows: [
          [
            'Attributive (before a noun)',
            'der/die/das + stem-ste (+ case ending)',
            'Das ist der schnellste Zug. / Ich fahre mit dem schnellsten Zug.',
          ],
          [
            'Predicative (after sein/werden)',
            'am + stem-sten (never changes)',
            'Dieser Zug ist am schnellsten.',
          ],
          [
            'Adverbial (describing a verb)',
            'am + stem-sten (never changes)',
            'Dieser Zug fährt am schnellsten.',
          ],
        ],
        note: 'The attributive form always needs a definite article and agrees with the noun; the am ...-sten form is fixed and never takes an ending of its own.',
      },
      {
        id: 'ch43-table-02',
        title: 'Irregular superlatives',
        columns: [
          'Base form',
          'Comparative',
          'Predicative superlative',
          'Attributive superlative',
        ],
        rows: [
          ['gut (good)', 'besser', 'am besten', 'der/die/das beste'],
          ['viel (much/many)', 'mehr', 'am meisten', 'der/die/das meiste'],
          ['hoch (high)', 'höher', 'am höchsten', 'der/die/das höchste'],
          ['nah (near)', 'näher', 'am nächsten', 'der/die/das nächste'],
          ['gern (gladly)', 'lieber', 'am liebsten', '—'],
        ],
        note: 'gern has no attributive superlative form because it is an adverb, not an adjective describing a noun.',
      },
    ],
    examples: [
      {
        german: 'Dieser Berg ist am höchsten.',
        english: 'This mountain is the highest.',
        highlight: ['am höchsten'],
        explanation:
          'Predicative superlative after sein; hoch loses its -c- and adds -sten: höchsten.',
      },
      {
        german: 'Das ist der höchste Berg Deutschlands.',
        english: 'That is the highest mountain in Germany.',
        highlight: ['der höchste Berg'],
        explanation:
          'Attributive superlative before a masculine nominative noun: der + höchst + weak ending -e.',
      },
      {
        german: 'Anna läuft am schnellsten.',
        english: 'Anna runs the fastest.',
        highlight: ['am schnellsten'],
        explanation:
          'Adverbial superlative describing how Anna runs; am ...-sten never changes.',
      },
      {
        german: 'Anna ist die schnellste Läuferin im Team.',
        english: 'Anna is the fastest runner on the team.',
        highlight: ['die schnellste Läuferin'],
        explanation:
          'Attributive superlative before a feminine nominative noun: die + schnellst + ending -e.',
      },
      {
        german: 'Im Sommer sind die Tage am längsten.',
        english: 'In summer the days are the longest.',
        highlight: ['am längsten'],
        explanation:
          'lang is a one-syllable adjective that adds an umlaut in the superlative: lang → länger → längst-; plus -est because the stem already ends in -ng, kept simple with -esten here for pronounceability (längsten).',
      },
      {
        german: 'Das ist die beste Idee, die ich je gehört habe.',
        english: 'That is the best idea I have ever heard.',
        highlight: ['die beste Idee'],
        explanation:
          'gut is irregular: gut → besser → best-; attributive feminine nominative ending -e.',
      },
      {
        german: 'Von den drei Brüdern isst Tom am meisten.',
        english: 'Of the three brothers, Tom eats the most.',
        highlight: ['am meisten'],
        explanation:
          'viel is irregular: viel → mehr → meist-; predicative/adverbial superlative with von + dative naming the compared group.',
      },
      {
        german: 'Der Supermarkt ist am nächsten.',
        english: 'The supermarket is the closest.',
        highlight: ['am nächsten'],
        explanation:
          'nah is irregular: nah → näher → nächst-; predicative superlative after sein.',
      },
      {
        german: 'Wir wohnen im nächsten Haus.',
        english: 'We live in the nearest house.',
        highlight: ['im nächsten Haus'],
        explanation:
          'Attributive superlative of nah before a neuter dative noun: im (in + dem) + nächst + ending -en.',
      },
      {
        german: 'Das war der heißeste Tag des Jahres.',
        english: 'That was the hottest day of the year.',
        highlight: ['der heißeste Tag'],
        explanation:
          'heiß ends in -ß, so it takes -est: heiß → heißest-; attributive masculine nominative ending -e.',
      },
      {
        german: 'Ich trinke am liebsten Kaffee.',
        english: 'I like drinking coffee the most.',
        highlight: ['am liebsten'],
        explanation:
          'gern is irregular: gern → lieber → liebst-; only the adverbial am ...-sten form exists for gern.',
      },
      {
        german: 'Das ist das teuerste Restaurant in der Stadt.',
        english: 'That is the most expensive restaurant in the city.',
        highlight: ['das teuerste Restaurant'],
        explanation:
          'Attributive superlative before a neuter nominative noun: das + teuerst + ending -e; "in der Stadt" names the compared group.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Dieser Zug ist der schnellsten.',
        correct: 'Dieser Zug ist am schnellsten.',
        explanation:
          'After sein with no following noun, German needs the predicative am ...-sten form, not an article + adjective ending.',
      },
      {
        incorrect: 'Das ist am schnellste Auto.',
        correct: 'Das ist das schnellste Auto.',
        explanation:
          'Directly before a noun, German needs the attributive der/die/das ...-ste form with a matching article, not am ...-sten.',
      },
      {
        incorrect: 'Das ist der gutste Film.',
        correct: 'Das ist der beste Film.',
        explanation: 'gut is irregular: its superlative stem is best-, not gutst-.',
      },
      {
        incorrect: 'Das ist der höhste Berg.',
        correct: 'Das ist der höchste Berg.',
        explanation:
          'hoch drops its -c- and changes to höch- before adding the superlative ending: höchst-, not höhst-.',
      },
      {
        incorrect: 'Das war der heißste Tag des Jahres.',
        correct: 'Das war der heißeste Tag des Jahres.',
        explanation:
          'Adjectives ending in -ß (and -d, -t, -s, -z, -sch) add -est rather than plain -st, for pronounceability: heißest-, not heißst-.',
      },
      {
        incorrect: 'Peter ist größer in der Klasse.',
        correct: 'Peter ist der größte in der Klasse.',
        explanation:
          'When comparing three or more people (a whole class), German uses the superlative, not the comparative.',
      },
    ],
    remember: [
      'Two shapes for one superlative: am ...-sten (predicative/adverbial, never changes) versus der/die/das ...-ste (attributive, needs an article and a case ending).',
      'Add -est instead of plain -st after d, t, s, ß, z, and sibilant/-sch endings: ältest-, lautest-, heißest-, kürzest-, hübschest-.',
      'One-syllable adjectives with a, o, or u often add an umlaut in the superlative, matching their comparative: alt → ältest-, groß → größt-, jung → jüngst-.',
      'Memorise the irregulars: gut → best-, viel → meist-, hoch → höchst-, nah → nächst-, gern → liebst- (adverbial only).',
      'Use the superlative once you compare three or more things; von + dative or in + dative often names the group being compared.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 80,
    requiredCorrectTextInputs: 12,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch43-ex-01',
      chapterNumber: 43,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'am-sten', 'predicative'],
      instruction: 'Choose the correct superlative form.',
      prompt: 'Im Winter ist es ___ kältesten.',
      options: [
        { id: 'a', text: 'am' },
        { id: 'b', text: 'der' },
        { id: 'c', text: 'die' },
        { id: 'd', text: 'das' },
      ],
      correctOptionId: 'a',
      explanation:
        'After sein with no following noun, German uses the fixed predicative form am kältesten.',
    },
    {
      id: 'ch43-ex-02',
      chapterNumber: 43,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'attributive', 'article-agreement'],
      instruction: 'Choose the correct article for the attributive superlative.',
      prompt: 'Das ist ___ schnellste Auto. (das Auto, neuter)',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
        { id: 'd', text: 'am' },
      ],
      correctOptionId: 'c',
      explanation:
        'Before a noun, the superlative needs a matching article; das Auto is neuter, so das schnellste Auto.',
    },
    {
      id: 'ch43-ex-03',
      chapterNumber: 43,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'attributive', 'article-agreement'],
      instruction: 'Choose the correct article for the attributive superlative.',
      prompt: '___ schnellste Läuferin gewinnt. (die Läuferin, feminine)',
      options: [
        { id: 'a', text: 'Der' },
        { id: 'b', text: 'Die' },
        { id: 'c', text: 'Das' },
        { id: 'd', text: 'Am' },
      ],
      correctOptionId: 'b',
      explanation:
        'die Läuferin is feminine, so the attributive superlative takes the article die: die schnellste Läuferin.',
    },
    {
      id: 'ch43-ex-04',
      chapterNumber: 43,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'irregular', 'gut'],
      instruction: 'Choose the correct irregular superlative stem.',
      prompt: 'Das ist der ___ Film, den ich je gesehen habe. (gut)',
      options: [
        { id: 'a', text: 'gutste' },
        { id: 'b', text: 'guteste' },
        { id: 'c', text: 'beste' },
        { id: 'd', text: 'bester' },
      ],
      correctOptionId: 'c',
      explanation:
        'gut is irregular: gut → besser → best-; attributive masculine nominative ending -e gives beste.',
    },
    {
      id: 'ch43-ex-05',
      chapterNumber: 43,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'irregular', 'hoch'],
      instruction: 'Choose the correct irregular superlative stem.',
      prompt: 'Das ist der ___ Berg Europas. (hoch)',
      options: [
        { id: 'a', text: 'hochste' },
        { id: 'b', text: 'höhste' },
        { id: 'c', text: 'höchste' },
        { id: 'd', text: 'hoheste' },
      ],
      correctOptionId: 'c',
      explanation:
        'hoch drops its -c- and changes to höch- before the ending: höchste, not höhste or hochste.',
    },
    {
      id: 'ch43-ex-06',
      chapterNumber: 43,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'spelling', 'est'],
      instruction: 'Choose the correct superlative spelling.',
      prompt: 'Das war der ___ Tag des Jahres. (heiß)',
      options: [
        { id: 'a', text: 'heißste' },
        { id: 'b', text: 'heißeste' },
        { id: 'c', text: 'heisste' },
        { id: 'd', text: 'heißerste' },
      ],
      correctOptionId: 'b',
      explanation:
        'Adjectives ending in -ß add -est for pronounceability: heißest-, giving heißeste.',
    },
    {
      id: 'ch43-ex-07',
      chapterNumber: 43,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'spelling', 'est'],
      instruction: 'Choose the correct superlative spelling.',
      prompt: 'Er ist der ___ Schüler in der Klasse. (intelligent)',
      options: [
        { id: 'a', text: 'intelligentste' },
        { id: 'b', text: 'intelligenteste' },
        { id: 'c', text: 'intelligentester' },
        { id: 'd', text: 'intelligentst' },
      ],
      correctOptionId: 'b',
      explanation:
        'Adjectives ending in -t add -est: intelligentest-; attributive masculine nominative ending -e gives intelligenteste.',
    },
    {
      id: 'ch43-ex-08',
      chapterNumber: 43,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'umlaut', 'kurz'],
      instruction: 'Choose the correct superlative form.',
      prompt: 'Das ist der ___ Weg zum Bahnhof. (kurz)',
      options: [
        { id: 'a', text: 'kurzeste' },
        { id: 'b', text: 'kürzste' },
        { id: 'c', text: 'kürzeste' },
        { id: 'd', text: 'kurzste' },
      ],
      correctOptionId: 'c',
      explanation:
        'kurz adds an umlaut (kurz → kürzer → kürzest-) and -est because it ends in -z: kürzeste.',
    },
    {
      id: 'ch43-ex-09',
      chapterNumber: 43,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'predicative-vs-attributive'],
      instruction: 'Choose the sentence that uses the superlative correctly.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Dieser Zug ist der schnellsten.' },
        { id: 'b', text: 'Dieser Zug ist am schnellsten.' },
        { id: 'c', text: 'Dieser Zug ist am schnellste.' },
        { id: 'd', text: 'Dieser Zug ist die schnellsten.' },
      ],
      correctOptionId: 'b',
      explanation:
        'After sein with no following noun, the fixed predicative form am schnellsten is required.',
    },
    {
      id: 'ch43-ex-10',
      chapterNumber: 43,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'predicative-vs-attributive'],
      instruction: 'Choose the sentence that uses the superlative correctly.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Das ist am schnellste Auto.' },
        { id: 'b', text: 'Das ist am schnellsten Auto.' },
        { id: 'c', text: 'Das ist das schnellste Auto.' },
        { id: 'd', text: 'Das ist das am schnellsten Auto.' },
      ],
      correctOptionId: 'c',
      explanation:
        'Directly before a noun, the attributive form with an article and ending is required: das schnellste Auto.',
    },
    {
      id: 'ch43-ex-11',
      chapterNumber: 43,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'case-ending', 'dative'],
      instruction: 'Choose the correct case ending for the attributive superlative.',
      prompt: 'Ich fahre mit dem ___ Zug. (schnell, dative after mit)',
      options: [
        { id: 'a', text: 'schnellste' },
        { id: 'b', text: 'schnellsten' },
        { id: 'c', text: 'schnellster' },
        { id: 'd', text: 'schnellstem' },
      ],
      correctOptionId: 'b',
      explanation:
        'After dem (masculine dative), the weak adjective ending is -en: dem schnellsten Zug.',
    },
    {
      id: 'ch43-ex-12',
      chapterNumber: 43,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['superlative', 'irregular', 'viel'],
      instruction: 'Choose the correct irregular superlative.',
      prompt: 'Von den drei Geschwistern isst Tom ___.',
      options: [
        { id: 'a', text: 'am meisten' },
        { id: 'b', text: 'am vielsten' },
        { id: 'c', text: 'am mehrsten' },
        { id: 'd', text: 'der meiste' },
      ],
      correctOptionId: 'a',
      explanation:
        'viel is irregular: viel → mehr → meist-; the adverbial form here is am meisten.',
    },
    {
      id: 'ch43-ex-13',
      chapterNumber: 43,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['superlative', 'irregular', 'nah'],
      instruction: 'Choose the correct irregular superlative.',
      prompt: 'Wir wohnen im ___ Haus zur Schule. (nah)',
      options: [
        { id: 'a', text: 'nahsten' },
        { id: 'b', text: 'näheresten' },
        { id: 'c', text: 'nächsten' },
        { id: 'd', text: 'näherste' },
      ],
      correctOptionId: 'c',
      explanation:
        'nah is irregular: nah → näher → nächst-; attributive neuter dative ending -en gives nächsten.',
    },
    {
      id: 'ch43-ex-14',
      chapterNumber: 43,
      order: 14,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['superlative', 'comparing-groups'],
      instruction: 'Choose the sentence that correctly compares three or more things.',
      prompt:
        'Peter, Anna und Lisa sind Geschwister. Peter ist am größten. Which sentence adds the comparison group correctly?',
      options: [
        { id: 'a', text: 'Peter ist der größte von den dreien.' },
        { id: 'b', text: 'Peter ist größer von den dreien.' },
        { id: 'c', text: 'Peter ist am größer von den dreien.' },
        { id: 'd', text: 'Peter ist die größte von den dreien.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Comparing three or more people requires the superlative; "der" agrees with the masculine Peter, and von den dreien names the group.',
    },
    {
      id: 'ch43-ex-15',
      chapterNumber: 43,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['superlative', 'irregular', 'gern'],
      instruction: 'Choose the correct irregular superlative.',
      prompt: 'Ich trinke ___ Kaffee. (gern)',
      options: [
        { id: 'a', text: 'am liebsten' },
        { id: 'b', text: 'am gernsten' },
        { id: 'c', text: 'der liebste' },
        { id: 'd', text: 'am besten' },
      ],
      correctOptionId: 'a',
      explanation:
        'gern is irregular: gern → lieber → liebst-; only the adverbial form am liebsten exists for this adverb.',
    },
    {
      id: 'ch43-ex-16',
      chapterNumber: 43,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'am-sten', 'predicative'],
      instruction:
        'Write the predicative superlative form. Capitalisation is not checked.',
      prompt: 'Dieser Berg ist sehr hoch, aber jener Berg ist ___. (hoch, am ...-sten)',
      acceptedAnswers: ['am höchsten'],
      answerMode: 'caseInsensitive',
      placeholder: 'am höchsten',
      maxLength: 20,
      explanation:
        'hoch is irregular and drops its -c-: höchst-; the predicative form is am höchsten.',
    },
    {
      id: 'ch43-ex-17',
      chapterNumber: 43,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'attributive', 'nominative'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt:
        'Das ist ___ Auto auf dem Parkplatz. (schnell, das Auto, neuter nominative)',
      acceptedAnswers: ['das schnellste'],
      answerMode: 'caseInsensitive',
      placeholder: 'das schnellste',
      maxLength: 25,
      explanation:
        'das Auto is neuter; the attributive superlative is das schnellste, with the ending -e.',
    },
    {
      id: 'ch43-ex-18',
      chapterNumber: 43,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'spelling', 'est'],
      instruction:
        'Write the predicative superlative form. Capitalisation is not checked.',
      prompt: 'Im August ist es ___. (heiß, am ...-esten)',
      acceptedAnswers: ['am heißesten'],
      answerMode: 'caseInsensitive',
      placeholder: 'am heißesten',
      maxLength: 20,
      explanation:
        'heiß ends in -ß, so it takes -est: heißest-; the predicative form is am heißesten.',
    },
    {
      id: 'ch43-ex-19',
      chapterNumber: 43,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'irregular', 'gut'],
      instruction:
        'Write the predicative superlative form. Capitalisation is not checked.',
      prompt: 'Dieser Kuchen schmeckt ___. (gut, am ...-en)',
      acceptedAnswers: ['am besten'],
      answerMode: 'caseInsensitive',
      placeholder: 'am besten',
      maxLength: 20,
      explanation:
        'gut is irregular: gut → besser → best-; the adverbial form is am besten.',
    },
    {
      id: 'ch43-ex-20',
      chapterNumber: 43,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'attributive', 'dative'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt:
        'Er wohnt in ___ Stadtteil der Stadt. (teuer, der Stadtteil, masculine dative after in + dem)',
      acceptedAnswers: ['dem teuersten', 'im teuersten'],
      answerMode: 'caseInsensitive',
      placeholder: 'dem teuersten',
      maxLength: 25,
      explanation:
        'in + dem contracts to im; the masculine dative attributive ending is -en: (im) teuersten.',
    },
    {
      id: 'ch43-ex-21',
      chapterNumber: 43,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'umlaut', 'attributive'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt:
        'Sie ist ___ Schülerin der Klasse. (jung, die Schülerin, feminine nominative)',
      acceptedAnswers: ['die jüngste'],
      answerMode: 'caseInsensitive',
      placeholder: 'die jüngste',
      maxLength: 25,
      explanation:
        'jung adds an umlaut in the superlative: jung → jünger → jüngst-; feminine nominative ending -e gives die jüngste.',
    },
    {
      id: 'ch43-ex-22',
      chapterNumber: 43,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'sentence-formation'],
      instruction:
        'Write a complete sentence using the predicative superlative for the cue in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'dieser Fluss – lang – Europa (predicative superlative, am ...-sten)',
      acceptedAnswers: [
        'Dieser Fluss ist am längsten in Europa.',
        'Dieser Fluss ist am längsten in Europa',
      ],
      answerMode: 'normalized',
      placeholder: 'Dieser Fluss ist ...',
      maxLength: 60,
      explanation:
        'lang adds an umlaut and -sten: längsten; the predicative form after sein is am längsten.',
    },
    {
      id: 'ch43-ex-23',
      chapterNumber: 43,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'predicative-vs-attributive'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Dieser Zug ist der schnellsten.',
      acceptedAnswers: ['Dieser Zug ist am schnellsten.'],
      answerMode: 'normalized',
      placeholder: 'Dieser Zug ist ...',
      maxLength: 60,
      explanation:
        'After sein with no following noun, the fixed predicative form am schnellsten is needed, not an article-based form.',
    },
    {
      id: 'ch43-ex-24',
      chapterNumber: 43,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'irregular'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Das ist der höhste Berg Europas.',
      acceptedAnswers: ['Das ist der höchste Berg Europas.'],
      answerMode: 'normalized',
      placeholder: 'Das ist der ...',
      maxLength: 60,
      explanation:
        'hoch drops its -c- and changes to höch- before the superlative ending: höchste, not höhste.',
    },
    {
      id: 'ch43-ex-25',
      chapterNumber: 43,
      order: 25,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'spelling'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Das war der heißste Tag des Jahres.',
      acceptedAnswers: ['Das war der heißeste Tag des Jahres.'],
      answerMode: 'normalized',
      placeholder: 'Das war der ...',
      maxLength: 60,
      explanation:
        'Adjectives ending in -ß add -est, not just -st: heißeste, not heißste.',
    },
    {
      id: 'ch43-ex-26',
      chapterNumber: 43,
      order: 26,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'superlative', 'comparing-groups'],
      instruction:
        'Write a complete sentence using the attributive superlative for the cue in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'Peter – der größte Schüler – die Klasse (attributive superlative, groß)',
      acceptedAnswers: [
        'Peter ist der größte Schüler in der Klasse.',
        'Peter ist der größte Schüler in der Klasse',
      ],
      answerMode: 'normalized',
      placeholder: 'Peter ist ...',
      maxLength: 60,
      explanation:
        'groß adds an umlaut: groß → größer → größt-; attributive masculine nominative ending -e gives der größte Schüler in der Klasse.',
    },
    {
      id: 'ch43-ex-27',
      chapterNumber: 43,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['superlative', 'irregular', 'viel', 'attributive'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt:
        'Berlin hat ___ Einwohner von allen deutschen Städten. (viel, die Einwohner, plural accusative)',
      acceptedAnswers: ['die meisten'],
      answerMode: 'caseInsensitive',
      placeholder: 'die meisten',
      maxLength: 20,
      explanation:
        'viel is irregular: viel → mehr → meist-; the plural attributive ending is -en, giving die meisten Einwohner.',
    },
    {
      id: 'ch43-ex-28',
      chapterNumber: 43,
      order: 28,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'am-sten', 'predicative'],
      instruction: 'Choose the correct superlative form.',
      prompt: 'Er läuft ___ schnellsten im ganzen Team.',
      options: [
        { id: 'a', text: 'am' },
        { id: 'b', text: 'der' },
        { id: 'c', text: 'das' },
        { id: 'd', text: 'die' },
      ],
      correctOptionId: 'a',
      explanation:
        'Describing how someone runs (adverbial) always uses the fixed form am schnellsten.',
    },
    {
      id: 'ch43-ex-29',
      chapterNumber: 43,
      order: 29,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'attributive', 'article-agreement'],
      instruction: 'Choose the correct article for the attributive superlative.',
      prompt: '___ billigste Hotel liegt am Stadtrand. (das Hotel, neuter)',
      options: [
        { id: 'a', text: 'Der' },
        { id: 'b', text: 'Die' },
        { id: 'c', text: 'Das' },
        { id: 'd', text: 'Am' },
      ],
      correctOptionId: 'c',
      explanation:
        'das Hotel is neuter, so the attributive superlative needs the article das: das billigste Hotel.',
    },
    {
      id: 'ch43-ex-30',
      chapterNumber: 43,
      order: 30,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'irregular', 'gut'],
      instruction: 'Choose the correct irregular superlative stem.',
      prompt: 'Diese Suppe schmeckt ___. (gut)',
      options: [
        { id: 'a', text: 'am gutsten' },
        { id: 'b', text: 'am besten' },
        { id: 'c', text: 'am bessten' },
        { id: 'd', text: 'der beste' },
      ],
      correctOptionId: 'b',
      explanation:
        'gut is irregular: gut → besser → best-; the adverbial predicative form is am besten.',
    },
    {
      id: 'ch43-ex-31',
      chapterNumber: 43,
      order: 31,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'spelling', 'est'],
      instruction: 'Choose the correct superlative spelling.',
      prompt: 'Das ist der ___ Weg, den ich kenne. (kurz)',
      options: [
        { id: 'a', text: 'kurzste' },
        { id: 'b', text: 'kurzeste' },
        { id: 'c', text: 'kürzeste' },
        { id: 'd', text: 'kürzste' },
      ],
      correctOptionId: 'c',
      explanation:
        'kurz umlauts (kürzer) and takes -est because it ends in -z: kürzeste.',
    },
    {
      id: 'ch43-ex-32',
      chapterNumber: 43,
      order: 32,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'case-ending', 'accusative'],
      instruction: 'Choose the correct case ending for the attributive superlative.',
      prompt: 'Ich kaufe den ___ Laptop im Geschäft. (billig, masculine accusative)',
      options: [
        { id: 'a', text: 'billigste' },
        { id: 'b', text: 'billigsten' },
        { id: 'c', text: 'billigster' },
        { id: 'd', text: 'billigstem' },
      ],
      correctOptionId: 'b',
      explanation:
        'After den (masculine accusative), the weak adjective ending is -en: den billigsten Laptop.',
    },
    {
      id: 'ch43-ex-33',
      chapterNumber: 43,
      order: 33,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'predicative-vs-attributive'],
      instruction: 'Choose the sentence that uses the superlative correctly.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Dieses Restaurant ist das teuersten.' },
        { id: 'b', text: 'Dieses Restaurant ist am teuersten.' },
        { id: 'c', text: 'Dieses Restaurant ist am teuerste.' },
        { id: 'd', text: 'Dieses Restaurant ist der teuerste.' },
      ],
      correctOptionId: 'b',
      explanation:
        'After sein with no following noun, the fixed predicative form am teuersten is required.',
    },
    {
      id: 'ch43-ex-34',
      chapterNumber: 43,
      order: 34,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['superlative', 'irregular', 'hoch'],
      instruction: 'Choose the correct irregular superlative.',
      prompt: 'Der Mount Everest ist der ___ Berg der Welt.',
      options: [
        { id: 'a', text: 'höhste' },
        { id: 'b', text: 'hochste' },
        { id: 'c', text: 'höchste' },
        { id: 'd', text: 'am höchsten' },
      ],
      correctOptionId: 'c',
      explanation:
        'hoch drops its -c- before the ending: höchst-; attributive masculine nominative ending -e gives höchste.',
    },
    {
      id: 'ch43-ex-35',
      chapterNumber: 43,
      order: 35,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['superlative', 'comparing-groups'],
      instruction: 'Choose the sentence that correctly compares three or more things.',
      prompt:
        'In der Familie gibt es drei Kinder. Anna ist am jüngsten. Which sentence names the comparison group correctly?',
      options: [
        { id: 'a', text: 'Anna ist die jüngste in der Familie.' },
        { id: 'b', text: 'Anna ist jünger in der Familie.' },
        { id: 'c', text: 'Anna ist am jünger in der Familie.' },
        { id: 'd', text: 'Anna ist der jüngste in der Familie.' },
      ],
      correctOptionId: 'a',
      explanation:
        'die agrees with the feminine Anna; in der Familie names the group being compared.',
    },
    {
      id: 'ch43-ex-36',
      chapterNumber: 43,
      order: 36,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['superlative', 'irregular', 'viel'],
      instruction: 'Choose the correct irregular superlative.',
      prompt: 'Von allen Schülern lernt Sofia ___.',
      options: [
        { id: 'a', text: 'am meisten' },
        { id: 'b', text: 'am vielsten' },
        { id: 'c', text: 'die meiste' },
        { id: 'd', text: 'am mehrsten' },
      ],
      correctOptionId: 'a',
      explanation:
        'viel is irregular: viel → mehr → meist-; the adverbial form here is am meisten.',
    },
    {
      id: 'ch43-ex-37',
      chapterNumber: 43,
      order: 37,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['superlative', 'umlaut', 'attributive'],
      instruction: 'Choose the correct superlative form.',
      prompt: 'Das ist die ___ Stadt, die ich je besucht habe. (alt)',
      options: [
        { id: 'a', text: 'alteste' },
        { id: 'b', text: 'älteste' },
        { id: 'c', text: 'ältste' },
        { id: 'd', text: 'altste' },
      ],
      correctOptionId: 'b',
      explanation: 'alt umlauts (älter) and takes -est because it ends in -t: älteste.',
    },
    {
      id: 'ch43-ex-38',
      chapterNumber: 43,
      order: 38,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['superlative', 'irregular', 'nah'],
      instruction: 'Choose the correct irregular superlative.',
      prompt: 'Der Supermarkt ist ___. (nah, predicative)',
      options: [
        { id: 'a', text: 'am nahsten' },
        { id: 'b', text: 'am nächsten' },
        { id: 'c', text: 'der nächste' },
        { id: 'd', text: 'am näherigsten' },
      ],
      correctOptionId: 'b',
      explanation:
        'nah is irregular: nah → näher → nächst-; the predicative form after sein is am nächsten.',
    },
    {
      id: 'ch43-ex-39',
      chapterNumber: 43,
      order: 39,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['superlative', 'irregular', 'gern'],
      instruction: 'Choose the correct irregular superlative.',
      prompt: 'Im Sommer spiele ich ___ Tennis. (gern)',
      options: [
        { id: 'a', text: 'am liebsten' },
        { id: 'b', text: 'am gernsten' },
        { id: 'c', text: 'am bessten' },
        { id: 'd', text: 'der liebste' },
      ],
      correctOptionId: 'a',
      explanation:
        'gern is irregular: gern → lieber → liebst-; only the adverbial form am liebsten exists.',
    },
    {
      id: 'ch43-ex-40',
      chapterNumber: 43,
      order: 40,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'am-sten', 'predicative'],
      instruction:
        'Write the predicative superlative form. Capitalisation is not checked.',
      prompt: 'Im Norden ist das Wetter ___. (kalt, am ...-sten)',
      acceptedAnswers: ['am kältesten'],
      answerMode: 'caseInsensitive',
      placeholder: 'am kältesten',
      maxLength: 20,
      explanation: 'kalt umlauts and adds -esten: am kältesten.',
    },
    {
      id: 'ch43-ex-41',
      chapterNumber: 43,
      order: 41,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'attributive', 'nominative'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt:
        'Das ist ___ Restaurant der Stadt. (gut, das Restaurant, neuter nominative)',
      acceptedAnswers: ['das beste'],
      answerMode: 'caseInsensitive',
      placeholder: 'das beste',
      maxLength: 25,
      explanation:
        'gut is irregular: best-; neuter nominative ending -e gives das beste.',
    },
    {
      id: 'ch43-ex-42',
      chapterNumber: 43,
      order: 42,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'spelling', 'est'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt:
        'Er ist ___ Student in der Gruppe. (intelligent, der Student, masculine nominative)',
      acceptedAnswers: ['der intelligenteste'],
      answerMode: 'caseInsensitive',
      placeholder: 'der intelligenteste',
      maxLength: 30,
      explanation:
        'intelligent ends in -t, so it takes -est: intelligentest-; masculine nominative ending -e gives der intelligenteste.',
    },
    {
      id: 'ch43-ex-43',
      chapterNumber: 43,
      order: 43,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['superlative', 'irregular', 'hoch'],
      instruction:
        'Write the predicative superlative form. Capitalisation is not checked.',
      prompt: 'Im Gebirge sind die Preise ___. (hoch, am ...-sten)',
      acceptedAnswers: ['am höchsten'],
      answerMode: 'caseInsensitive',
      placeholder: 'am höchsten',
      maxLength: 20,
      explanation: 'hoch drops its -c-: höchst-; the predicative form is am höchsten.',
    },
    {
      id: 'ch43-ex-44',
      chapterNumber: 43,
      order: 44,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'attributive', 'genitive'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt: 'Das ist das Auto ___ Fahrers. (schnell, der Fahrer, masculine genitive)',
      acceptedAnswers: ['des schnellsten'],
      answerMode: 'caseInsensitive',
      placeholder: 'des schnellsten',
      maxLength: 25,
      explanation:
        'Masculine genitive attributive endings are -en: des schnellsten Fahrers.',
    },
    {
      id: 'ch43-ex-45',
      chapterNumber: 43,
      order: 45,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'umlaut', 'attributive'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt: 'Das ist ___ Turm in Europa. (groß, der Turm, masculine nominative)',
      acceptedAnswers: ['der größte'],
      answerMode: 'caseInsensitive',
      placeholder: 'der größte',
      maxLength: 25,
      explanation:
        'groß umlauts: groß → größer → größt-; masculine nominative ending -e gives der größte.',
    },
    {
      id: 'ch43-ex-46',
      chapterNumber: 43,
      order: 46,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'sentence-formation'],
      instruction:
        'Write a complete sentence using the predicative superlative for the cue in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'diese Suppe – gut – Restaurant (predicative superlative, am ...-en)',
      acceptedAnswers: [
        'Diese Suppe schmeckt am besten im Restaurant.',
        'Diese Suppe schmeckt am besten im Restaurant',
      ],
      answerMode: 'normalized',
      placeholder: 'Diese Suppe schmeckt ...',
      maxLength: 60,
      explanation: 'gut is irregular: best-; the adverbial form here is am besten.',
    },
    {
      id: 'ch43-ex-47',
      chapterNumber: 43,
      order: 47,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'irregular'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Das ist der gutste Film des Jahres.',
      acceptedAnswers: ['Das ist der beste Film des Jahres.'],
      answerMode: 'normalized',
      placeholder: 'Das ist der ...',
      maxLength: 60,
      explanation: 'gut is irregular: its superlative stem is best-, not gutst-.',
    },
    {
      id: 'ch43-ex-48',
      chapterNumber: 43,
      order: 48,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'predicative-vs-attributive'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Das ist am schnellste Auto.',
      acceptedAnswers: ['Das ist das schnellste Auto.'],
      answerMode: 'normalized',
      placeholder: 'Das ist ...',
      maxLength: 60,
      explanation:
        'Directly before a noun, the attributive form with a matching article is required: das schnellste Auto.',
    },
    {
      id: 'ch43-ex-49',
      chapterNumber: 43,
      order: 49,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'superlative', 'comparing-groups'],
      instruction:
        'Write a complete sentence using the attributive superlative for the cue in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'Anna – die jüngste Schülerin – die Klasse (attributive superlative, jung)',
      acceptedAnswers: [
        'Anna ist die jüngste Schülerin in der Klasse.',
        'Anna ist die jüngste Schülerin in der Klasse',
      ],
      answerMode: 'normalized',
      placeholder: 'Anna ist ...',
      maxLength: 60,
      explanation:
        'jung umlauts: jung → jünger → jüngst-; feminine nominative ending -e gives die jüngste Schülerin in der Klasse.',
    },
    {
      id: 'ch43-ex-50',
      chapterNumber: 43,
      order: 50,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'irregular', 'viel', 'predicative'],
      instruction:
        'Write the predicative superlative form. Capitalisation is not checked.',
      prompt: 'Von allen Ländern reist Familie Müller ___. (viel, am ...-en)',
      acceptedAnswers: ['am meisten'],
      answerMode: 'caseInsensitive',
      placeholder: 'am meisten',
      maxLength: 20,
      explanation:
        'viel is irregular: viel → mehr → meist-; the adverbial form is am meisten.',
    },
    {
      id: 'ch43-ex-51',
      chapterNumber: 43,
      order: 51,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['superlative', 'attributive', 'dative'],
      instruction:
        'Write the attributive superlative with its article. Capitalisation is not checked.',
      prompt:
        'Wir wohnen in ___ Haus der Straße. (nah, das Haus, neuter dative after in + dem)',
      acceptedAnswers: ['dem nächsten', 'im nächsten'],
      answerMode: 'caseInsensitive',
      placeholder: 'im nächsten',
      maxLength: 25,
      explanation:
        'nah is irregular: nächst-; in + dem contracts to im, neuter dative ending -en gives im nächsten.',
    },
    {
      id: 'ch43-ex-52',
      chapterNumber: 43,
      order: 52,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['superlative', 'positive-to-superlative'],
      instruction:
        'Match each positive adjective to its predicative superlative form (am ...).',
      prompt: 'Match the positive form to its superlative.',
      pairs: [
        { id: 'p1', left: 'schnell', right: 'am schnellsten' },
        { id: 'p2', left: 'klein', right: 'am kleinsten' },
        { id: 'p3', left: 'billig', right: 'am billigsten' },
        { id: 'p4', left: 'kalt', right: 'am kältesten' },
        { id: 'p5', left: 'laut', right: 'am lautesten' },
      ],
      explanation:
        'Regular adjectives add -sten (or -esten after d/t/s/ß/z) to the stem, following am.',
    },
    {
      id: 'ch43-ex-53',
      chapterNumber: 43,
      order: 53,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['superlative', 'irregular'],
      instruction:
        'Match each base adjective to its irregular predicative superlative form.',
      prompt: 'Match the irregular base form to its superlative.',
      pairs: [
        { id: 'p1', left: 'gut', right: 'am besten' },
        { id: 'p2', left: 'viel', right: 'am meisten' },
        { id: 'p3', left: 'hoch', right: 'am höchsten' },
        { id: 'p4', left: 'nah', right: 'am nächsten' },
        { id: 'p5', left: 'gern', right: 'am liebsten' },
      ],
      explanation:
        'These five adjectives/adverbs form their superlatives irregularly and must be memorised.',
    },
    {
      id: 'ch43-ex-54',
      chapterNumber: 43,
      order: 54,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['superlative', 'umlaut'],
      instruction:
        'Match each base adjective to its umlauted attributive superlative (masculine nominative).',
      prompt: 'Match the base form to its umlauted superlative.',
      pairs: [
        { id: 'p1', left: 'alt', right: 'der älteste' },
        { id: 'p2', left: 'groß', right: 'der größte' },
        { id: 'p3', left: 'jung', right: 'der jüngste' },
        { id: 'p4', left: 'kurz', right: 'der kürzeste' },
        { id: 'p5', left: 'lang', right: 'der längste' },
      ],
      explanation:
        'These one-syllable adjectives with a, o, or u add an umlaut in the superlative stem.',
    },
    {
      id: 'ch43-ex-55',
      chapterNumber: 43,
      order: 55,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['superlative', 'attributive', 'article-agreement'],
      instruction:
        'Match each noun (with its gender) to the article its attributive superlative needs.',
      prompt: 'Match the noun to the correct superlative article.',
      pairs: [
        { id: 'p1', left: 'das Auto (neuter)', right: 'das schnellste Auto' },
        { id: 'p2', left: 'die Läuferin (feminine)', right: 'die schnellste Läuferin' },
        { id: 'p3', left: 'der Zug (masculine)', right: 'der schnellste Zug' },
        { id: 'p4', left: 'die Züge (plural)', right: 'die schnellsten Züge' },
      ],
      explanation:
        'The attributive superlative always agrees in gender and number with the article/noun it precedes.',
    },
    {
      id: 'ch43-ex-56',
      chapterNumber: 43,
      order: 56,
      type: 'matching',
      level: 'production',
      grammarFocus: ['superlative', 'spelling', 'est'],
      instruction:
        'Match each base adjective to its correctly spelled attributive superlative (masculine nominative).',
      prompt: 'Match the base form to the correctly spelled superlative.',
      pairs: [
        { id: 'p1', left: 'heiß', right: 'der heißeste' },
        { id: 'p2', left: 'laut', right: 'der lauteste' },
        { id: 'p3', left: 'intelligent', right: 'der intelligenteste' },
        { id: 'p4', left: 'hübsch', right: 'der hübscheste' },
      ],
      explanation:
        'Adjectives ending in -d, -t, -s, -ß, -z, or -sch add -est instead of plain -st for pronounceability.',
    },
    {
      id: 'ch43-ex-57',
      chapterNumber: 43,
      order: 57,
      type: 'matching',
      level: 'production',
      grammarFocus: ['superlative', 'case-ending'],
      instruction:
        'Match each case/article combination to its correct attributive superlative ending.',
      prompt: 'Match the phrase to its correct case ending (schnell).',
      pairs: [
        { id: 'p1', left: 'der ___ Zug (nominative)', right: 'der schnellste Zug' },
        { id: 'p2', left: 'den ___ Zug (accusative)', right: 'den schnellsten Zug' },
        { id: 'p3', left: 'dem ___ Zug (dative)', right: 'dem schnellsten Zug' },
        { id: 'p4', left: 'des ___ Zuges (genitive)', right: 'des schnellsten Zuges' },
      ],
      explanation:
        'Masculine attributive superlative endings follow the standard weak-adjective pattern: -e (nom.), -en (acc./dat./gen.).',
    },
    {
      id: 'ch43-ex-58',
      chapterNumber: 43,
      order: 58,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['superlative', 'predicative-vs-attributive'],
      instruction:
        'Match each sentence context to the correct superlative construction it needs.',
      prompt: 'Match the context to the correct construction.',
      pairs: [
        { id: 'p1', left: 'after sein, no following noun', right: 'am schnellsten' },
        { id: 'p2', left: 'directly before a noun', right: 'das schnellste Auto' },
        { id: 'p3', left: 'describing how a verb is done', right: 'am besten' },
        {
          id: 'p4',
          left: 'comparing three or more, before noun',
          right: 'der schnellste von allen',
        },
      ],
      explanation:
        'am ...-sten is fixed and never takes an article; der/die/das ...-ste always needs an article and agrees with the noun.',
    },
    {
      id: 'ch43-ex-59',
      chapterNumber: 43,
      order: 59,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['superlative', 'irregular', 'attributive'],
      instruction:
        'Match each base form to its attributive superlative (feminine nominative, die ...).',
      prompt: 'Match the base form to its attributive superlative.',
      pairs: [
        { id: 'p1', left: 'gut', right: 'die beste' },
        { id: 'p2', left: 'viel', right: 'die meiste' },
        { id: 'p3', left: 'hoch', right: 'die höchste' },
        { id: 'p4', left: 'nah', right: 'die nächste' },
      ],
      explanation:
        'gern has no attributive form; the other four irregulars combine with die + stem + -e for feminine nominative.',
    },
    {
      id: 'ch43-ex-60',
      chapterNumber: 43,
      order: 60,
      type: 'matching',
      level: 'production',
      grammarFocus: ['superlative', 'comparing-groups'],
      instruction:
        'Match each sentence half to its correct completion naming the comparison group.',
      prompt: 'Match the sentence beginning to its correct ending.',
      pairs: [
        { id: 'p1', left: 'Peter ist der größte', right: 'von den dreien.' },
        { id: 'p2', left: 'Tom isst am meisten', right: 'von allen Brüdern.' },
        { id: 'p3', left: 'Sie ist die jüngste Schülerin', right: 'in der Klasse.' },
        { id: 'p4', left: 'Das Auto fährt am schnellsten', right: 'in der Familie.' },
      ],
      explanation:
        'von + dative or in + dative typically introduces the group of three or more being compared.',
    },
    {
      id: 'ch43-ex-61',
      chapterNumber: 43,
      order: 61,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['superlative', 'am-sten', 'predicative'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct predicative superlative marker.',
      templateParts: ['Im Winter ist es ', ' kältesten.'],
      slots: [{ id: 's1', correctWord: 'am' }],
      wordBank: ['am', 'der', 'die', 'das'],
      explanation:
        'The fixed predicative superlative form after sein is am + stem-sten: am kältesten.',
    },
    {
      id: 'ch43-ex-62',
      chapterNumber: 43,
      order: 62,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['superlative', 'attributive', 'article-agreement'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct article (das Auto, neuter).',
      templateParts: ['', ' schnellste Auto gehört meinem Bruder.'],
      slots: [{ id: 's1', correctWord: 'Das' }],
      wordBank: ['Das', 'Der', 'Die', 'Am'],
      explanation:
        'das Auto is neuter, so the attributive superlative takes the article Das: Das schnellste Auto.',
    },
    {
      id: 'ch43-ex-63',
      chapterNumber: 43,
      order: 63,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['superlative', 'irregular', 'gut'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct irregular superlative stem (gut).',
      templateParts: ['Das ist der ', ' Film, den ich kenne.'],
      slots: [{ id: 's1', correctWord: 'beste' }],
      wordBank: ['beste', 'gutste', 'guteste', 'bester'],
      explanation:
        'gut is irregular: gut → besser → best-; the masculine nominative attributive ending -e gives beste.',
    },
    {
      id: 'ch43-ex-64',
      chapterNumber: 43,
      order: 64,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['superlative', 'irregular', 'hoch'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct irregular superlative stem (hoch).',
      templateParts: ['Das ist der ', ' Berg Europas.'],
      slots: [{ id: 's1', correctWord: 'höchste' }],
      wordBank: ['höchste', 'hochste', 'höhste', 'hoheste'],
      explanation:
        'hoch drops its -c- and changes to höch- before the ending: höchste, not höhste or hochste.',
    },
    {
      id: 'ch43-ex-65',
      chapterNumber: 43,
      order: 65,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['superlative', 'spelling', 'est'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correctly spelled superlative (heiß).',
      templateParts: ['Das war der ', ' Tag des Jahres.'],
      slots: [{ id: 's1', correctWord: 'heißeste' }],
      wordBank: ['heißeste', 'heißste', 'heisste', 'heißerste'],
      explanation:
        'Adjectives ending in -ß add -est for pronounceability: heißest-, giving heißeste.',
    },
    {
      id: 'ch43-ex-66',
      chapterNumber: 43,
      order: 66,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['superlative', 'umlaut', 'kurz'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct superlative form (kurz).',
      templateParts: ['Das ist der ', ' Weg zum Bahnhof.'],
      slots: [{ id: 's1', correctWord: 'kürzeste' }],
      wordBank: ['kürzeste', 'kurzeste', 'kürzste', 'kurzste'],
      explanation:
        'kurz adds an umlaut (kurz → kürzer → kürzest-) and -est because it ends in -z: kürzeste.',
    },
    {
      id: 'ch43-ex-67',
      chapterNumber: 43,
      order: 67,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['superlative', 'irregular', 'viel'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct irregular superlative (viel).',
      templateParts: ['Von den drei Geschwistern isst Tom ', '.'],
      slots: [{ id: 's1', correctWord: 'am meisten' }],
      wordBank: ['am meisten', 'am vielsten', 'am mehrsten', 'der meiste'],
      explanation:
        'viel is irregular: viel → mehr → meist-; the adverbial form here is am meisten.',
    },
    {
      id: 'ch43-ex-68',
      chapterNumber: 43,
      order: 68,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['superlative', 'irregular', 'nah'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct irregular superlative (nah).',
      templateParts: ['Wir wohnen im ', ' Haus zur Schule.'],
      slots: [{ id: 's1', correctWord: 'nächsten' }],
      wordBank: ['nächsten', 'nahsten', 'näheresten', 'näherste'],
      explanation:
        'nah is irregular: nah → näher → nächst-; attributive neuter dative ending -en gives nächsten.',
    },
    {
      id: 'ch43-ex-69',
      chapterNumber: 43,
      order: 69,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['superlative', 'case-ending', 'dative'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct case ending (schnell).',
      templateParts: ['Ich fahre mit dem ', ' Zug.'],
      slots: [{ id: 's1', correctWord: 'schnellsten' }],
      wordBank: ['schnellsten', 'schnellste', 'schnellster', 'schnellstem'],
      explanation:
        'After dem (masculine dative), the weak adjective ending is -en: dem schnellsten Zug.',
    },
    {
      id: 'ch43-ex-70',
      chapterNumber: 43,
      order: 70,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['superlative', 'comparing-groups'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence naming the comparison group correctly.',
      templateParts: ['Peter ist der größte ', ' den dreien.'],
      slots: [{ id: 's1', correctWord: 'von' }],
      wordBank: ['von', 'in', 'mit', 'zu'],
      explanation:
        'Comparing three or more people is often introduced with von + dative naming the group: von den dreien.',
    },
    {
      id: 'ch43-ex-71',
      chapterNumber: 43,
      order: 71,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['superlative', 'irregular', 'gern'],
      instruction: 'Drag the correct word into the slot.',
      prompt: 'Complete the sentence with the correct irregular superlative (gern).',
      templateParts: ['Ich trinke ', ' Kaffee.'],
      slots: [{ id: 's1', correctWord: 'am liebsten' }],
      wordBank: ['am liebsten', 'am gernsten', 'der liebste', 'am besten'],
      explanation:
        'gern is irregular: gern → lieber → liebst-; only the adverbial form am liebsten exists for gern.',
    },
    {
      id: 'ch43-ex-72',
      chapterNumber: 43,
      order: 72,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['error-correction', 'superlative', 'predicative-vs-attributive'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Dieser', 'Zug', 'ist', 'der', 'schnellsten', '.'],
      errorTokenIndex: 3,
      correction: 'am',
      explanation:
        'After sein with no following noun, German needs the fixed predicative form am schnellsten, not an article.',
    },
    {
      id: 'ch43-ex-73',
      chapterNumber: 43,
      order: 73,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['error-correction', 'superlative', 'predicative-vs-attributive'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Das', 'ist', 'am', 'schnellste', 'Auto', '.'],
      errorTokenIndex: 2,
      correction: 'das',
      explanation:
        'Directly before a noun, German needs the attributive form das schnellste, not am schnellste.',
    },
    {
      id: 'ch43-ex-74',
      chapterNumber: 43,
      order: 74,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'superlative', 'irregular'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Das', 'ist', 'der', 'gutste', 'Film', '.'],
      errorTokenIndex: 3,
      correction: 'beste',
      explanation: 'gut is irregular: its superlative stem is best-, not gutst-.',
    },
    {
      id: 'ch43-ex-75',
      chapterNumber: 43,
      order: 75,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'superlative', 'irregular'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Das', 'ist', 'der', 'höhste', 'Berg', 'Europas', '.'],
      errorTokenIndex: 3,
      correction: 'höchste',
      explanation:
        'hoch drops its -c- and changes to höch- before the superlative ending: höchste, not höhste.',
    },
    {
      id: 'ch43-ex-76',
      chapterNumber: 43,
      order: 76,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'superlative', 'spelling'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Das', 'war', 'der', 'heißste', 'Tag', 'des', 'Jahres', '.'],
      errorTokenIndex: 3,
      correction: 'heißeste',
      explanation:
        'Adjectives ending in -ß add -est, not just -st: heißeste, not heißste.',
    },
    {
      id: 'ch43-ex-77',
      chapterNumber: 43,
      order: 77,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'comparing-groups'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Peter', 'ist', 'größer', 'in', 'der', 'Klasse', '.'],
      errorTokenIndex: 2,
      correction: 'am größten',
      explanation:
        'When comparing three or more people (a whole class), German uses the superlative, not the comparative.',
    },
    {
      id: 'ch43-ex-78',
      chapterNumber: 43,
      order: 78,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'umlaut'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Sie', 'ist', 'die', 'jungste', 'Schülerin', 'der', 'Klasse', '.'],
      errorTokenIndex: 3,
      correction: 'jüngste',
      explanation:
        'jung umlauts in the superlative: jung → jünger → jüngst-; jungste is missing the umlaut.',
    },
    {
      id: 'ch43-ex-79',
      chapterNumber: 43,
      order: 79,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'irregular'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Von', 'allen', 'Ländern', 'reist', 'sie', 'am', 'vielsten', '.'],
      errorTokenIndex: 6,
      correction: 'meisten',
      explanation:
        'viel is irregular: viel → mehr → meist-; the correct adverbial form is am meisten, not am vielsten.',
    },
    {
      id: 'ch43-ex-80',
      chapterNumber: 43,
      order: 80,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'superlative', 'irregular', 'attributive'],
      instruction: 'Click the token that contains the error.',
      prompt: 'Find the mistake in this sentence.',
      tokens: ['Wir', 'wohnen', 'im', 'nahsten', 'Haus', 'zur', 'Schule', '.'],
      errorTokenIndex: 3,
      correction: 'nächsten',
      explanation:
        'nah is irregular: nah → näher → nächst-; nahsten is not a valid form.',
    },
  ],
};
