import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter041: ChapterDefinition = {
  id: 'chapter-041',
  number: 41,
  slug: 'adjective-endings-in-the-nominative-accusative-and-dative',
  title: 'Adjective Endings in the Nominative, Accusative, and Dative',
  germanTitle: 'Adjektivendungen im Nominativ, Akkusativ und Dativ',
  level: 'A2',
  section: 'adjectives-1',
  objective:
    'Extend the adjective-ending pattern from Chapter 40 to the dative singular and to the plural (nominative, accusative, and dative), and use a single "when in doubt, -en" strategy to predict the ending correctly after der-words, ein-words, and their plural forms.',
  prerequisites: [15, 17, 18, 40],
  estimatedMinutes: 26,
  tags: [
    'adjective endings',
    'attributive adjectives',
    'dative',
    'dative plural',
    'plural',
    'der-words',
    'ein-words',
    'adjective declension',
    'pattern recognition',
  ],
  explanation: {
    introduction: [
      'In Chapter 40 you learned that an attributive adjective — one standing directly before a noun — takes -e after der/die/das, and -er, -e, or -es after ein/eine/ein in the nominative, while the accusative changes only the masculine ending to -en. This chapter adds the third case you already know from Chapter 18, the dative, and shows what happens to the ending when the noun is plural.',
      'The good news is that both extensions simplify things rather than complicating them: in the dative, singular adjectives take -en no matter the gender or the article type, and in the plural, adjectives take -en in the nominative, the accusative, and the dative alike. By the end of this chapter you will have one compact strategy that covers almost every attributive adjective ending you will ever need.',
    ],
    rules: [
      {
        id: 'ch41-rule-01',
        heading: 'Recap: nominative and accusative singular (Chapter 40)',
        paragraphs: [
          'Before adding the dative, recall the pattern from Chapter 40. In the nominative, der-words take -e in all three genders (der rote Apfel, die rote Tasche, das rote Auto), while ein-words take -er (masculine), -e (feminine), and -es (neuter), because ein itself does not show the gender. In the accusative, only the masculine changes, to -en, after both den and einen; feminine and neuter stay exactly as in the nominative.',
          'This chapter keeps every one of those rules — it only adds what happens in the dative and in the plural.',
        ],
      },
      {
        id: 'ch41-rule-02',
        heading: 'Recognising the dative: dem, der, dem — einem, einer, einem',
        paragraphs: [
          'The dative marks the indirect object (wem? — to/for whom?), and it also follows dative verbs such as helfen, danken, and gefallen, and dative prepositions such as mit, bei, nach, von, zu, and aus. The definite article in the dative singular is dem (masculine), der (feminine), and dem (neuter); the indefinite article is einem (masculine), einer (feminine), and einem (neuter).',
          'These article forms are the clearest signal that an adjective needs a dative ending — if you see dem, der (before a noun, not a relative pronoun), or einem/einer, the noun phrase is in the dative.',
        ],
      },
      {
        id: 'ch41-rule-03',
        heading: 'Dative singular: -en everywhere',
        paragraphs: [
          'Unlike the nominative and the accusative, the dative singular does not distinguish between genders or between der-words and ein-words at all: the adjective ending is simply -en in every case. Ich helfe dem alten Mann. (masculine) Ich danke der netten Frau. (feminine) Er gibt dem kleinen Kind ein Geschenk. (neuter) — the same -en appears after dem, der, and dem alike.',
          'The same is true after ein-words: Sie hilft einem alten Mann. Wir danken einer freundlichen Frau. Er gibt einem kleinen Kind ein Buch. Because dem/einem and der/einer already carry all the case and gender information the sentence needs, the adjective ending can stay uniform.',
        ],
        notes: [
          'Dative singular in one line: dem/der/dem or einem/einer/einem + adjective-en + noun, regardless of gender.',
        ],
      },
      {
        id: 'ch41-rule-04',
        heading: 'Plural: nominative, accusative, and dative all take -en',
        paragraphs: [
          'German has no gender distinction in the plural, and the adjective ending reflects that simplicity: after the plural definite article die and after plural forms such as keine (no/not any) or meine (my), the adjective ending is -en in the nominative, the accusative, and the dative alike. Die kleinen Kinder spielen im Garten. (nominative) Ich sehe die kleinen Kinder. (accusative) Die Lehrerin hilft den kleinen Kindern. (dative)',
          'So while the singular still distinguishes nominative from accusative from dative, the plural collapses almost all of that variation into a single, predictable -en ending on the adjective.',
        ],
      },
      {
        id: 'ch41-rule-05',
        heading: 'Dative plural: the noun itself also adds -n',
        paragraphs: [
          'In the dative plural specifically, it is not only the adjective that changes — the noun does too. Most plural nouns add -n in the dative unless they already end in -n or in -s: die Kinder → den Kindern, die Freunde → den Freunden, die Nachbarn → den Nachbarn (unchanged, already ends in -n), die Autos → den Autos (unchanged, already ends in -s).',
          'This noun -n is separate from the adjective ending, but the two always travel together in the dative plural: den kleinen Kindern, den netten Nachbarn, mit den neuen Autos.',
        ],
      },
      {
        id: 'ch41-rule-06',
        heading: 'Pattern-recognition strategy: when in doubt, guess -en',
        paragraphs: [
          'Across everything covered in Chapters 40 and 41, -en is by far the most common attributive adjective ending: it appears in the masculine accusative singular, in the entire dative singular (all genders), and in the entire plural (nominative, accusative, and dative). A fast, reliable strategy is therefore to default to -en and only look for an exception in two situations: the nominative singular (any gender) and the feminine or neuter accusative singular — those are the spots where -e, -er, or -es appear instead.',
          'In practice: first decide whether the noun phrase is plural or dative — if either is true, the ending is almost certainly -en. If it is singular and neither accusative-masculine nor dative, check the article type and gender against the Chapter 40 table for -e, -er, or -es.',
        ],
        notes: [
          'The -en pattern: masculine accusative singular + all dative singular + all plural (nom/acc/dat) = -en. Everything else in the singular nominative, and feminine/neuter accusative singular, keeps the Chapter 40 endings.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch41-table-01',
        title: 'Adjective Endings — Dative Singular',
        columns: ['Article type', 'Masculine', 'Feminine', 'Neuter'],
        columnCases: [null, 'dative', 'dative', 'dative'],
        rows: [
          ['dem/der/dem (definite)', '-en (dem roten Apfel)', '-en (der roten Tasche)', '-en (dem roten Auto)'],
          ['einem/einer/einem (indefinite)', '-en (einem roten Apfel)', '-en (einer roten Tasche)', '-en (einem roten Auto)'],
        ],
        note: 'Unlike the nominative and the accusative, the dative singular ending is -en in every gender, after both der-words and ein-words.',
      },
      {
        id: 'ch41-table-02',
        title: 'Adjective Endings — Plural (All Three Cases)',
        columns: ['Article type', 'Nominative', 'Accusative', 'Dative'],
        columnCases: [null, 'nominative', 'accusative', 'dative'],
        rows: [
          ['die (definite plural)', '-en (die roten Äpfel)', '-en (die roten Äpfel)', '-en (den roten Äpfeln)'],
          ['keine/meine (indefinite-type plural)', '-en (keine roten Äpfel)', '-en (keine roten Äpfel)', '-en (keinen roten Äpfeln)'],
        ],
        note: 'In the plural, the adjective ending is -en in all three cases. In the dative plural, the noun itself also adds -n: Äpfel → Äpfeln.',
      },
      {
        id: 'ch41-table-03',
        title: 'The "-en Pattern" at a Glance',
        columns: ['Context', 'Ending', 'Example'],
        rows: [
          ['Nominative singular (any gender)', '-e (der-words); -er/-e/-es (ein-words)', 'der rote Apfel; ein roter Apfel'],
          ['Feminine & neuter accusative singular', '-e (der-words); -e/-es (ein-words)', 'die rote Tasche; ein rotes Auto'],
          ['Masculine accusative singular', '-en', 'den roten Apfel'],
          ['Dative singular (any gender)', '-en', 'dem roten Apfel; der roten Tasche'],
          ['Plural — nominative, accusative, dative', '-en', 'die roten Äpfel; den roten Äpfeln'],
        ],
        note: 'Use this table as a quick self-check: everything except the top two rows takes -en.',
      },
    ],
    examples: [
      {
        german: 'Ich helfe dem alten Mann.',
        english: 'I am helping the old man.',
        highlight: ['dem', 'alten'],
        explanation: 'helfen takes the dative; the masculine dative ending after dem is -en.',
      },
      {
        german: 'Ich danke der netten Frau.',
        english: 'I am thanking the kind woman.',
        highlight: ['der', 'netten'],
        explanation: 'danken takes the dative; the feminine dative ending after der is also -en, not -e as in the nominative.',
      },
      {
        german: 'Er gibt dem kleinen Kind ein Geschenk.',
        english: 'He is giving the small child a present.',
        highlight: ['dem', 'kleinen'],
        explanation: 'geben has a dative indirect object; the neuter dative ending after dem is -en.',
      },
      {
        german: 'Sie hilft einem alten Mann.',
        english: 'She is helping an old man.',
        highlight: ['einem', 'alten'],
        explanation: 'The masculine dative ending after einem is -en, exactly as after dem.',
      },
      {
        german: 'Wir danken einer freundlichen Frau.',
        english: 'We are thanking a friendly woman.',
        highlight: ['einer', 'freundlichen'],
        explanation: 'The feminine dative ending after einer is -en, unlike the feminine nominative/accusative -e.',
      },
      {
        german: 'Er gibt einem kleinen Kind ein Buch.',
        english: 'He is giving a small child a book.',
        highlight: ['einem', 'kleinen'],
        explanation: 'The neuter dative ending after einem is -en, unlike the neuter nominative/accusative -es.',
      },
      {
        german: 'Wir fahren mit dem neuen Zug.',
        english: 'We are traveling on the new train.',
        highlight: ['dem', 'neuen'],
        explanation: 'The preposition mit always takes the dative, so the masculine adjective ending is -en.',
      },
      {
        german: 'Die kleinen Kinder spielen im Garten.',
        english: 'The small children are playing in the garden.',
        highlight: ['kleinen'],
        explanation: 'Plural nominative after die takes -en, unlike any singular nominative ending.',
      },
      {
        german: 'Ich sehe die kleinen Kinder im Garten.',
        english: 'I see the small children in the garden.',
        highlight: ['kleinen'],
        explanation: 'Plural accusative after die also takes -en, the same as the plural nominative.',
      },
      {
        german: 'Die Lehrerin hilft den kleinen Kindern.',
        english: 'The teacher is helping the small children.',
        highlight: ['den', 'kleinen', 'Kindern'],
        explanation: 'Plural dative: den signals the dative plural, the adjective takes -en, and the noun itself adds -n (Kinder → Kindern).',
      },
      {
        german: 'Wir haben keine neuen Bücher.',
        english: 'We do not have any new books.',
        highlight: ['keine', 'neuen'],
        explanation: 'keine is the plural of kein; the plural adjective ending after keine is -en, just as after die.',
      },
      {
        german: 'Er dankt den netten Nachbarn.',
        english: 'He thanks the kind neighbors.',
        highlight: ['den', 'netten', 'Nachbarn'],
        explanation: 'Dative plural: the adjective takes -en; Nachbarn already ends in -n, so the noun form does not change further.',
      },
      {
        german: 'Ich kaufe den roten Apfel, aber ich schenke der roten Tasche keine Beachtung.',
        english: 'I am buying the red apple, but I am paying the red bag no attention.',
        highlight: ['den', 'roten', 'der', 'roten'],
        explanation: 'den roten Apfel is masculine accusative (-en); der roten Tasche is feminine dative after schenken (-en) — both endings are -en, but for different reasons.',
      },
      {
        german: 'Das Kind gibt dem Hund und der Katze Futter.',
        english: 'The child gives the dog and the cat food.',
        highlight: ['dem', 'der'],
        explanation: 'geben with an indirect object needs the dative; both dem (masculine) and der (feminine) here introduce nouns without adjectives, but any adjective inserted here would take -en in both cases.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich helfe dem alte Mann.',
        correct: 'Ich helfe dem alten Mann.',
        explanation: 'The dative singular ending is always -en, never the nominative -e, regardless of gender.',
      },
      {
        incorrect: 'Ich danke der nette Frau.',
        correct: 'Ich danke der netten Frau.',
        explanation: 'Even though der looks like the nominative/dative feminine article family, in the dative the adjective ending is -en, not -e.',
      },
      {
        incorrect: 'Wir danken einer freundliche Frau.',
        correct: 'Wir danken einer freundlichen Frau.',
        explanation: 'After einer in the dative, the adjective ending is -en, not the feminine nominative/accusative -e.',
      },
      {
        incorrect: 'Die Lehrerin hilft die kleinen Kinder.',
        correct: 'Die Lehrerin hilft den kleinen Kindern.',
        explanation: 'helfen requires the dative, so the plural article must be den (not die), and the noun itself adds -n: Kindern.',
      },
      {
        incorrect: 'Die klein Kinder spielen im Garten.',
        correct: 'Die kleinen Kinder spielen im Garten.',
        explanation: 'Plural attributive adjectives always need an ending; the plural ending after die is -en, not a bare adjective form.',
      },
      {
        incorrect: 'Er dankt den netten Nachbarns.',
        correct: 'Er dankt den netten Nachbarn.',
        explanation: 'Nachbarn already ends in -n, so the dative plural does not add a further -s or extra -n; only nouns that do not already end in -n or -s take the extra -n.',
      },
    ],
    remember: [
      'Dative singular: the adjective ending is -en in every gender, after both der-words (dem/der/dem) and ein-words (einem/einer/einem).',
      'Plural: the adjective ending is -en in the nominative, the accusative, and the dative alike, after die as well as after keine/meine and similar words.',
      'Dative plural adds an extra -n to the noun itself, unless the noun already ends in -n or -s (die Kinder → den Kindern, but die Nachbarn → den Nachbarn).',
      'Strategy: if a noun phrase is plural or dative, guess -en first. Only the nominative singular and the feminine/neuter accusative singular use -e, -er, or -es instead.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 62,
    requiredCorrectTextInputs: 11,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch41-ex-01',
      chapterNumber: 41,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dative', 'der-word', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Ich helfe dem ___ Mann. (alt)',
      options: [
        { id: 'a', text: 'alte' },
        { id: 'b', text: 'alter' },
        { id: 'c', text: 'altes' },
        { id: 'd', text: 'alten' },
      ],
      correctOptionId: 'd',
      explanation: 'The dative singular ending is -en after dem, regardless of gender: dem alten Mann.',
    },
    {
      id: 'ch41-ex-02',
      chapterNumber: 41,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dative', 'der-word', 'feminine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Ich danke der ___ Frau. (nett)',
      options: [
        { id: 'a', text: 'nette' },
        { id: 'b', text: 'netter' },
        { id: 'c', text: 'nettes' },
        { id: 'd', text: 'netten' },
      ],
      correctOptionId: 'd',
      explanation: 'The dative singular ending is -en after der, even in the feminine: der netten Frau.',
    },
    {
      id: 'ch41-ex-03',
      chapterNumber: 41,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dative', 'der-word', 'neuter'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Er gibt dem ___ Kind ein Geschenk. (klein)',
      options: [
        { id: 'a', text: 'kleine' },
        { id: 'b', text: 'kleiner' },
        { id: 'c', text: 'kleines' },
        { id: 'd', text: 'kleinen' },
      ],
      correctOptionId: 'd',
      explanation: 'The dative singular ending is -en after dem in the neuter too: dem kleinen Kind.',
    },
    {
      id: 'ch41-ex-04',
      chapterNumber: 41,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dative', 'ein-word', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Sie hilft einem ___ Mann. (alt)',
      options: [
        { id: 'a', text: 'alte' },
        { id: 'b', text: 'alter' },
        { id: 'c', text: 'alten' },
        { id: 'd', text: 'altes' },
      ],
      correctOptionId: 'c',
      explanation: 'After einem, the dative masculine ending is also -en: einem alten Mann.',
    },
    {
      id: 'ch41-ex-05',
      chapterNumber: 41,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dative', 'ein-word', 'feminine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Wir danken einer ___ Frau. (freundlich)',
      options: [
        { id: 'a', text: 'freundliche' },
        { id: 'b', text: 'freundlichen' },
        { id: 'c', text: 'freundlicher' },
        { id: 'd', text: 'freundliches' },
      ],
      correctOptionId: 'b',
      explanation: 'After einer, the dative feminine ending is -en, not the nominative/accusative -e: einer freundlichen Frau.',
    },
    {
      id: 'ch41-ex-06',
      chapterNumber: 41,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dative', 'ein-word', 'neuter'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Er gibt einem ___ Kind ein Buch. (klein)',
      options: [
        { id: 'a', text: 'kleines' },
        { id: 'b', text: 'kleine' },
        { id: 'c', text: 'kleiner' },
        { id: 'd', text: 'kleinen' },
      ],
      correctOptionId: 'd',
      explanation: 'After einem, the dative neuter ending is -en, not the nominative/accusative -es: einem kleinen Kind.',
    },
    {
      id: 'ch41-ex-07',
      chapterNumber: 41,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Wir fahren mit dem ___ Zug. (neu)',
      options: [
        { id: 'a', text: 'neue' },
        { id: 'b', text: 'neuer' },
        { id: 'c', text: 'neuen' },
        { id: 'd', text: 'neues' },
      ],
      correctOptionId: 'c',
      explanation: 'mit always takes the dative, so the masculine adjective ending is -en: mit dem neuen Zug.',
    },
    {
      id: 'ch41-ex-08',
      chapterNumber: 41,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'gender-recognition'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Der Mann gibt der ___ Frau Blumen. (nett)',
      options: [
        { id: 'a', text: 'nette' },
        { id: 'b', text: 'netter' },
        { id: 'c', text: 'nettes' },
        { id: 'd', text: 'netten' },
      ],
      correctOptionId: 'd',
      explanation: 'geben has a dative indirect object here; der netten Frau — the ending is -en, not the feminine nominative -e.',
    },
    {
      id: 'ch41-ex-09',
      chapterNumber: 41,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural', 'nominative', 'der-word'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Die ___ Kinder spielen im Garten. (klein)',
      options: [
        { id: 'a', text: 'kleine' },
        { id: 'b', text: 'kleiner' },
        { id: 'c', text: 'kleines' },
        { id: 'd', text: 'kleinen' },
      ],
      correctOptionId: 'd',
      explanation: 'Plural adjectives after die always take -en, regardless of case: die kleinen Kinder.',
    },
    {
      id: 'ch41-ex-10',
      chapterNumber: 41,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural', 'dative', 'der-word'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Die Lehrerin hilft den ___ Kindern. (klein)',
      options: [
        { id: 'a', text: 'kleine' },
        { id: 'b', text: 'kleiner' },
        { id: 'c', text: 'kleines' },
        { id: 'd', text: 'kleinen' },
      ],
      correctOptionId: 'd',
      explanation: 'Dative plural also takes -en: den kleinen Kindern, with an extra -n on the noun itself.',
    },
    {
      id: 'ch41-ex-11',
      chapterNumber: 41,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['plural', 'ein-word', 'accusative'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Wir haben keine ___ Bücher. (neu)',
      options: [
        { id: 'a', text: 'neue' },
        { id: 'b', text: 'neuer' },
        { id: 'c', text: 'neuen' },
        { id: 'd', text: 'neues' },
      ],
      correctOptionId: 'c',
      explanation: 'keine is the plural of kein; the plural adjective ending after keine is -en, just as after die.',
    },
    {
      id: 'ch41-ex-12',
      chapterNumber: 41,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['case-identification'],
      instruction: 'Which case does the underlined phrase use?',
      prompt: 'Which case is used in: Ich schenke der netten Frau einen Blumenstrauß.?',
      options: [
        { id: 'a', text: 'Nominative' },
        { id: 'b', text: 'Accusative' },
        { id: 'c', text: 'Dative' },
        { id: 'd', text: 'Genitive' },
      ],
      correctOptionId: 'c',
      explanation: 'schenken has both a dative indirect object (der netten Frau) and an accusative direct object (einen Blumenstrauß); der netten Frau is the dative phrase.',
    },
    {
      id: 'ch41-ex-13',
      chapterNumber: 41,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['dative', 'error-recognition'],
      instruction: 'Which sentence is correct?',
      prompt: 'Choose the correctly formed sentence.',
      options: [
        { id: 'a', text: 'Ich helfe dem alte Mann.' },
        { id: 'b', text: 'Ich helfe dem alten Mann.' },
        { id: 'c', text: 'Ich helfe der alten Mann.' },
        { id: 'd', text: 'Ich helfe den alten Mann.' },
      ],
      correctOptionId: 'b',
      explanation: 'helfen takes the dative; Mann is masculine, so the article is dem and the adjective ending is -en: dem alten Mann.',
    },
    {
      id: 'ch41-ex-14',
      chapterNumber: 41,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['dative', 'der-word', 'feminine', 'mixed-case'],
      instruction: 'Choose the phrase that correctly completes the sentence.',
      prompt: 'Er dankt ___. (die nette Frau)',
      options: [
        { id: 'a', text: 'die nette Frau' },
        { id: 'b', text: 'der netten Frau' },
        { id: 'c', text: 'den netten Frau' },
        { id: 'd', text: 'dem netten Frau' },
      ],
      correctOptionId: 'b',
      explanation: 'danken takes the dative; Frau is feminine, so the correct phrase is der netten Frau.',
    },
    {
      id: 'ch41-ex-15',
      chapterNumber: 41,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'der-word', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Ich helfe dem alt___ Mann.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'The dative singular ending is -en after dem: dem alten Mann.',
    },
    {
      id: 'ch41-ex-16',
      chapterNumber: 41,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'der-word', 'feminine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Ich danke der nett___ Frau.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'The dative singular ending is -en after der, even in the feminine: der netten Frau.',
    },
    {
      id: 'ch41-ex-17',
      chapterNumber: 41,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'der-word', 'neuter'],
      instruction: 'Write only the missing ending.',
      prompt: 'Er gibt dem klein___ Kind ein Geschenk.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'The dative singular ending is -en after dem in the neuter too: dem kleinen Kind.',
    },
    {
      id: 'ch41-ex-18',
      chapterNumber: 41,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'ein-word', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Sie hilft einem alt___ Mann.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'The dative singular ending after einem is -en: einem alten Mann.',
    },
    {
      id: 'ch41-ex-19',
      chapterNumber: 41,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'ein-word', 'feminine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Wir danken einer freundlich___ Frau.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'The dative singular ending after einer is -en, not the feminine -e: einer freundlichen Frau.',
    },
    {
      id: 'ch41-ex-20',
      chapterNumber: 41,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'ein-word', 'neuter'],
      instruction: 'Write only the missing ending.',
      prompt: 'Er gibt einem klein___ Kind ein Buch.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'The dative singular ending after einem is -en, not the neuter -es: einem kleinen Kind.',
    },
    {
      id: 'ch41-ex-21',
      chapterNumber: 41,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['plural', 'dative', 'der-word'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Die Lehrerin hilft den ___ Kindern. (klein)',
      acceptedAnswers: ['kleinen'],
      answerMode: 'caseInsensitive',
      placeholder: 'kleinen',
      maxLength: 20,
      explanation: 'Dative plural adjectives take -en: den kleinen Kindern.',
    },
    {
      id: 'ch41-ex-22',
      chapterNumber: 41,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dative', 'preposition', 'masculine'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Wir fahren mit dem ___ Zug. (neu)',
      acceptedAnswers: ['neuen'],
      answerMode: 'caseInsensitive',
      placeholder: 'neuen',
      maxLength: 20,
      explanation: 'mit takes the dative; the masculine dative ending is -en: mit dem neuen Zug.',
    },
    {
      id: 'ch41-ex-23',
      chapterNumber: 41,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['plural', 'nominative', 'der-word'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Die ___ Kinder spielen im Garten. (klein)',
      acceptedAnswers: ['kleinen'],
      answerMode: 'caseInsensitive',
      placeholder: 'kleinen',
      maxLength: 20,
      explanation: 'Plural nominative adjectives after die take -en: die kleinen Kinder.',
    },
    {
      id: 'ch41-ex-24',
      chapterNumber: 41,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['plural', 'dative', 'noun-ending'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Er dankt den ___ Nachbarn. (nett)',
      acceptedAnswers: ['netten'],
      answerMode: 'caseInsensitive',
      placeholder: 'netten',
      maxLength: 20,
      explanation: 'Dative plural adjectives take -en: den netten Nachbarn (Nachbarn already ends in -n, so the noun itself does not change further).',
    },
    {
      id: 'ch41-ex-25',
      chapterNumber: 41,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dative', 'case-transformation', 'masculine'],
      instruction: 'Change the phrase from the nominative to the dative, as in the model.',
      prompt: 'Nominativ: der große Hund. Dativ: Ich helfe ___ Hund.',
      acceptedAnswers: ['dem großen'],
      answerMode: 'normalized',
      placeholder: 'dem großen',
      maxLength: 30,
      explanation: 'The masculine dative article is dem, and the dative adjective ending is -en: dem großen Hund.',
    },
    {
      id: 'ch41-ex-26',
      chapterNumber: 41,
      order: 26,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['dative', 'error-correction', 'masculine'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich helfe dem alte Mann.',
      acceptedAnswers: ['Ich helfe dem alten Mann.'],
      answerMode: 'normalized',
      placeholder: 'Ich helfe dem alten ...',
      maxLength: 60,
      explanation: 'The dative singular ending is -en, not the nominative -e: dem alten Mann.',
    },
    {
      id: 'ch41-ex-27',
      chapterNumber: 41,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['plural', 'dative', 'error-correction'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Die Lehrerin hilft die kleinen Kinder.',
      acceptedAnswers: ['Die Lehrerin hilft den kleinen Kindern.'],
      answerMode: 'normalized',
      placeholder: 'Die Lehrerin hilft den kleinen ...',
      maxLength: 60,
      explanation: 'helfen requires the dative, so the article must be den, and the noun adds -n: den kleinen Kindern.',
    },
    {
      id: 'ch41-ex-28',
      chapterNumber: 41,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['dative', 'der-word', 'masculine', 'sentence-building'],
      instruction: 'Write a complete sentence using the cues. Capitalisation is checked; no full stop is required.',
      prompt: 'ich – danken – der (nett, Freund)',
      acceptedAnswers: ['Ich danke dem netten Freund.', 'Ich danke dem netten Freund'],
      answerMode: 'normalized',
      placeholder: 'Ich danke ...',
      maxLength: 60,
      explanation: 'danken takes the dative; Freund is masculine, so the article is dem and the adjective ending is -en: dem netten Freund.',
    },
    {
      id: 'ch41-ex-29',
      chapterNumber: 41,
      order: 29,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'plural', 'preposition'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Sie fährt mit den ___ Kindern zum Zoo. (klein)',
      options: [
        { id: 'a', text: 'kleine' },
        { id: 'b', text: 'kleiner' },
        { id: 'c', text: 'kleines' },
        { id: 'd', text: 'kleinen' },
      ],
      correctOptionId: 'd',
      explanation: 'mit takes the dative, and the plural adjective ending is -en regardless of case: mit den kleinen Kindern.',
    },
    {
      id: 'ch41-ex-30',
      chapterNumber: 41,
      order: 30,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Ich komme aus dem ___ Haus. (alt)',
      options: [
        { id: 'a', text: 'alte' },
        { id: 'b', text: 'alten' },
        { id: 'c', text: 'alter' },
        { id: 'd', text: 'altes' },
      ],
      correctOptionId: 'b',
      explanation: 'aus always takes the dative, so the masculine adjective ending is -en: aus dem alten Haus.',
    },
    {
      id: 'ch41-ex-31',
      chapterNumber: 41,
      order: 31,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'feminine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Er wohnt bei seiner ___ Tante. (nett)',
      options: [
        { id: 'a', text: 'nette' },
        { id: 'b', text: 'netter' },
        { id: 'c', text: 'netten' },
        { id: 'd', text: 'nettes' },
      ],
      correctOptionId: 'c',
      explanation: 'bei takes the dative, so the feminine adjective ending after seiner is -en, not the nominative -e: bei seiner netten Tante.',
    },
    {
      id: 'ch41-ex-32',
      chapterNumber: 41,
      order: 32,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'neuter'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Nach dem ___ Essen gehen wir spazieren. (gut)',
      options: [
        { id: 'a', text: 'gute' },
        { id: 'b', text: 'guter' },
        { id: 'c', text: 'gutes' },
        { id: 'd', text: 'guten' },
      ],
      correctOptionId: 'd',
      explanation: 'nach takes the dative, so the neuter adjective ending is -en, not the nominative/accusative -es: nach dem guten Essen.',
    },
    {
      id: 'ch41-ex-33',
      chapterNumber: 41,
      order: 33,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'feminine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Ich fahre zu meiner alt___ Oma.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'zu takes the dative, so the feminine adjective ending after meiner is -en: zu meiner alten Oma.',
    },
    {
      id: 'ch41-ex-34',
      chapterNumber: 41,
      order: 34,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'masculine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Wir sprechen von dem neu___ Lehrer.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'von takes the dative, so the masculine adjective ending is -en: von dem neuen Lehrer.',
    },
    {
      id: 'ch41-ex-35',
      chapterNumber: 41,
      order: 35,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['plural', 'dative', 'noun-ending'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Er dankt den ___ Nachbarinnen. (nett)',
      acceptedAnswers: ['netten'],
      answerMode: 'caseInsensitive',
      placeholder: 'netten',
      maxLength: 20,
      explanation: 'Dative plural adjectives take -en: den netten Nachbarinnen.',
    },
    {
      id: 'ch41-ex-36',
      chapterNumber: 41,
      order: 36,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['case-identification'],
      instruction: 'Name the case. Write Nominative, Accusative, Dative, or Genitive.',
      prompt: 'Which case is used in: Sie hilft der alten Frau.?',
      acceptedAnswers: ['Dative'],
      answerMode: 'caseInsensitive',
      placeholder: 'Dative',
      maxLength: 20,
      explanation: 'helfen takes the dative; der alten Frau is the dative phrase.',
    },
    {
      id: 'ch41-ex-37',
      chapterNumber: 41,
      order: 37,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['dative', 'der-word', 'masculine'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Ich helfe dem ', ' Mann.'],
      slots: [{ id: 's1', correctWord: 'alten' }],
      wordBank: ['alten', 'alte', 'alter', 'altes'],
      explanation: 'The dative singular ending is -en after dem, regardless of gender: dem alten Mann.',
    },
    {
      id: 'ch41-ex-38',
      chapterNumber: 41,
      order: 38,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['dative', 'ein-word', 'feminine'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Wir danken einer ', ' Frau.'],
      slots: [{ id: 's1', correctWord: 'freundlichen' }],
      wordBank: ['freundlichen', 'freundliche', 'freundlicher', 'freundliches'],
      explanation: 'After einer, the dative feminine ending is -en, not the nominative/accusative -e: einer freundlichen Frau.',
    },
    {
      id: 'ch41-ex-39',
      chapterNumber: 41,
      order: 39,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['dative', 'der-word', 'neuter'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Er gibt dem ', ' Kind ein Geschenk.'],
      slots: [{ id: 's1', correctWord: 'kleinen' }],
      wordBank: ['kleinen', 'kleine', 'kleiner', 'kleines'],
      explanation: 'The dative singular ending is -en after dem in the neuter too: dem kleinen Kind.',
    },
    {
      id: 'ch41-ex-40',
      chapterNumber: 41,
      order: 40,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['plural', 'nominative', 'der-word'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Die ', ' Kinder spielen im Garten.'],
      slots: [{ id: 's1', correctWord: 'kleinen' }],
      wordBank: ['kleinen', 'kleine', 'kleiner', 'kleines'],
      explanation: 'Plural adjectives after die always take -en, regardless of case: die kleinen Kinder.',
    },
    {
      id: 'ch41-ex-41',
      chapterNumber: 41,
      order: 41,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['plural', 'dative', 'der-word'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Die Lehrerin hilft den ', ' Kindern.'],
      slots: [{ id: 's1', correctWord: 'kleinen' }],
      wordBank: ['kleinen', 'kleine', 'kleiner', 'kleines'],
      explanation: 'Dative plural also takes -en: den kleinen Kindern, with an extra -n on the noun itself.',
    },
    {
      id: 'ch41-ex-42',
      chapterNumber: 41,
      order: 42,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'masculine'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Wir kommen von dem ', ' Bahnhof.'],
      slots: [{ id: 's1', correctWord: 'neuen' }],
      wordBank: ['neuen', 'neue', 'neuer', 'neues'],
      explanation: 'von takes the dative, so the masculine adjective ending is -en: von dem neuen Bahnhof.',
    },
    {
      id: 'ch41-ex-43',
      chapterNumber: 41,
      order: 43,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'feminine'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Ich gehe zu der ', ' Ärztin.'],
      slots: [{ id: 's1', correctWord: 'netten' }],
      wordBank: ['netten', 'nette', 'netter', 'nettes'],
      explanation: 'zu takes the dative, so the feminine adjective ending is -en: zu der netten Ärztin.',
    },
    {
      id: 'ch41-ex-44',
      chapterNumber: 41,
      order: 44,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'neuter'],
      instruction: 'Drag the word with the correct ending into the slot.',
      prompt: 'Complete the sentence.',
      templateParts: ['Der Brief kommt aus dem ', ' Land.'],
      slots: [{ id: 's1', correctWord: 'fernen' }],
      wordBank: ['fernen', 'ferne', 'ferner', 'fernes'],
      explanation: 'aus takes the dative, so the neuter adjective ending is -en, not the nominative/accusative -es: aus dem fernen Land.',
    },
    {
      id: 'ch41-ex-45',
      chapterNumber: 41,
      order: 45,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['dative', 'plural', 'case-recognition'],
      instruction: 'Match each blank phrase with its correctly completed form.',
      prompt: 'Match the phrase to its correct completion.',
      pairs: [
        { id: 'p1', left: 'dem ___ Mann (alt)', right: 'dem alten Mann' },
        { id: 'p2', left: 'der ___ Frau (nett)', right: 'der netten Frau' },
        { id: 'p3', left: 'die ___ Kinder (klein)', right: 'die kleinen Kinder' },
        { id: 'p4', left: 'den ___ Kindern (klein)', right: 'den kleinen Kindern' },
        { id: 'p5', left: 'einem ___ Kind (klein)', right: 'einem kleinen Kind' },
      ],
      explanation: 'Dative singular (any gender) and the entire plural take -en; matching the blank to its filled form checks both patterns at once.',
    },
    {
      id: 'ch41-ex-46',
      chapterNumber: 41,
      order: 46,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition'],
      instruction: 'Match each dative preposition with a correctly formed example phrase.',
      prompt: 'Match the preposition to its example.',
      pairs: [
        { id: 'p1', left: 'mit (+Dativ)', right: 'mit dem neuen Zug' },
        { id: 'p2', left: 'bei (+Dativ)', right: 'bei der netten Nachbarin' },
        { id: 'p3', left: 'nach (+Dativ)', right: 'nach dem guten Essen' },
        { id: 'p4', left: 'von (+Dativ)', right: 'von dem alten Haus' },
        { id: 'p5', left: 'zu (+Dativ)', right: 'zu der freundlichen Ärztin' },
        { id: 'p6', left: 'aus (+Dativ)', right: 'aus dem fernen Land' },
      ],
      explanation: 'mit, bei, nach, von, zu, and aus all take the dative, so any adjective following them takes the dative ending -en.',
    },
    {
      id: 'ch41-ex-47',
      chapterNumber: 41,
      order: 47,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['dative', 'plural', 'noun-ending'],
      instruction: 'Match each nominative plural noun phrase with its dative plural form.',
      prompt: 'Match the nominative plural to the dative plural.',
      pairs: [
        { id: 'p1', left: 'die Kinder', right: 'den Kindern' },
        { id: 'p2', left: 'die Freunde', right: 'den Freunden' },
        { id: 'p3', left: 'die Nachbarn', right: 'den Nachbarn' },
        { id: 'p4', left: 'die Autos', right: 'den Autos' },
        { id: 'p5', left: 'die Bücher', right: 'den Büchern' },
      ],
      explanation: 'In the dative plural, most nouns add -n unless they already end in -n or -s (Nachbarn, Autos stay unchanged).',
    },
    {
      id: 'ch41-ex-48',
      chapterNumber: 41,
      order: 48,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['case-recognition', 'sentence-completion'],
      instruction: 'Match each sentence beginning with the ending that correctly completes it.',
      prompt: 'Match the sentence halves.',
      pairs: [
        { id: 'p1', left: 'Ich sehe...', right: 'den roten Apfel.' },
        { id: 'p2', left: 'Ich helfe...', right: 'dem alten Mann.' },
        { id: 'p3', left: 'Der rote Apfel...', right: 'liegt auf dem Tisch.' },
        { id: 'p4', left: 'Wir danken...', right: 'der netten Frau.' },
        { id: 'p5', left: 'Die kleinen Kinder...', right: 'spielen im Garten.' },
      ],
      explanation: 'Recognising which case each verb requires (accusative, dative, or plain nominative) is the key to choosing the right ending.',
    },
    {
      id: 'ch41-ex-49',
      chapterNumber: 41,
      order: 49,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['pattern-recognition'],
      instruction: 'Match each grammatical context with the ending pattern it takes.',
      prompt: 'Match the context to its ending rule.',
      pairs: [
        { id: 'p1', left: 'Maskulin Akkusativ Singular (den ___)', right: 'den roten Apfel' },
        { id: 'p2', left: 'gesamter Dativ Singular', right: 'dem/der/dem + -en' },
        { id: 'p3', left: 'gesamter Plural (alle Kasus)', right: 'die/den + -en' },
        { id: 'p4', left: 'Nominativ nach der-Wort (alle Genera)', right: 'der rote Apfel / die rote Tasche / das rote Auto' },
        { id: 'p5', left: 'Nominativ nach ein-Wort (alle Genera)', right: 'ein roter Apfel / eine rote Tasche / ein rotes Auto' },
      ],
      explanation: 'This matches the "-en pattern" strategy from this chapter: masculine accusative, all dative singular, and all plural take -en; only the nominative keeps -e/-er/-es distinctions.',
    },
    {
      id: 'ch41-ex-50',
      chapterNumber: 41,
      order: 50,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['dative', 'der-word', 'masculine', 'error-recognition'],
      instruction: 'Click the word with the wrong ending.',
      prompt: 'Find the mistake.',
      tokens: ['Ich', 'helfe', 'dem', 'alte', 'Mann', '.'],
      errorTokenIndex: 3,
      correction: 'alten',
      explanation: 'The dative singular ending is -en after dem, not the nominative -e: dem alten Mann.',
    },
    {
      id: 'ch41-ex-51',
      chapterNumber: 41,
      order: 51,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['dative', 'der-word', 'feminine', 'error-recognition'],
      instruction: 'Click the word with the wrong ending.',
      prompt: 'Find the mistake.',
      tokens: ['Ich', 'danke', 'der', 'nette', 'Frau', '.'],
      errorTokenIndex: 3,
      correction: 'netten',
      explanation: 'The dative singular ending is -en after der, even in the feminine: der netten Frau.',
    },
    {
      id: 'ch41-ex-52',
      chapterNumber: 41,
      order: 52,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['plural', 'dative', 'error-recognition'],
      instruction: 'Click the word that is wrong.',
      prompt: 'Find the mistake.',
      tokens: ['Die', 'Lehrerin', 'hilft', 'die', 'kleinen', 'Kinder', '.'],
      errorTokenIndex: 3,
      correction: 'den',
      explanation: 'helfen requires the dative, so the article must be den, not die: den kleinen Kindern.',
    },
    {
      id: 'ch41-ex-53',
      chapterNumber: 41,
      order: 53,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['dative', 'ein-word', 'feminine', 'error-recognition'],
      instruction: 'Click the word with the wrong ending.',
      prompt: 'Find the mistake.',
      tokens: ['Wir', 'danken', 'einer', 'freundliche', 'Frau', '.'],
      errorTokenIndex: 3,
      correction: 'freundlichen',
      explanation: 'After einer in the dative, the adjective ending is -en, not the feminine -e: einer freundlichen Frau.',
    },
    {
      id: 'ch41-ex-54',
      chapterNumber: 41,
      order: 54,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['dative', 'plural', 'noun-ending', 'error-recognition'],
      instruction: 'Click the word that is wrong.',
      prompt: 'Find the mistake.',
      tokens: ['Er', 'dankt', 'den', 'netten', 'Nachbarns', '.'],
      errorTokenIndex: 4,
      correction: 'Nachbarn',
      explanation: 'Nachbarn already ends in -n, so the dative plural does not add a further -s: den netten Nachbarn.',
    },
    {
      id: 'ch41-ex-55',
      chapterNumber: 41,
      order: 55,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['plural', 'nominative', 'error-recognition'],
      instruction: 'Click the word that is wrong.',
      prompt: 'Find the mistake.',
      tokens: ['Die', 'klein', 'Kinder', 'spielen', 'im', 'Garten', '.'],
      errorTokenIndex: 1,
      correction: 'kleinen',
      explanation: 'Plural attributive adjectives always need an ending; after die the ending is -en, not a bare adjective form.',
    },
    {
      id: 'ch41-ex-56',
      chapterNumber: 41,
      order: 56,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'der-word', 'feminine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Ich spreche mit der ___ Ärztin. (nett)',
      options: [
        { id: 'a', text: 'nette' },
        { id: 'b', text: 'netter' },
        { id: 'c', text: 'nettes' },
        { id: 'd', text: 'netten' },
      ],
      correctOptionId: 'd',
      explanation: 'mit takes the dative, so the feminine adjective ending is -en: mit der netten Ärztin.',
    },
    {
      id: 'ch41-ex-57',
      chapterNumber: 41,
      order: 57,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'ein-word', 'neuter'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Sie kommt aus einem ___ Land. (fern)',
      options: [
        { id: 'a', text: 'ferne' },
        { id: 'b', text: 'ferner' },
        { id: 'c', text: 'fernen' },
        { id: 'd', text: 'fernes' },
      ],
      correctOptionId: 'c',
      explanation: 'aus takes the dative, so the neuter adjective ending after einem is -en, not the nominative/accusative -es: aus einem fernen Land.',
    },
    {
      id: 'ch41-ex-58',
      chapterNumber: 41,
      order: 58,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'preposition', 'masculine'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Nach dem ___ Film gehen wir essen. (lang)',
      options: [
        { id: 'a', text: 'lange' },
        { id: 'b', text: 'langer' },
        { id: 'c', text: 'langes' },
        { id: 'd', text: 'langen' },
      ],
      correctOptionId: 'd',
      explanation: 'nach takes the dative, so the masculine adjective ending is -en: nach dem langen Film.',
    },
    {
      id: 'ch41-ex-59',
      chapterNumber: 41,
      order: 59,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dative', 'plural', 'preposition'],
      instruction: 'Choose the correct adjective ending.',
      prompt: 'Die Kinder spielen mit den ___ Bällen. (bunt)',
      options: [
        { id: 'a', text: 'bunte' },
        { id: 'b', text: 'bunten' },
        { id: 'c', text: 'bunter' },
        { id: 'd', text: 'buntes' },
      ],
      correctOptionId: 'b',
      explanation: 'mit takes the dative, and the plural adjective ending is -en: mit den bunten Bällen.',
    },
    {
      id: 'ch41-ex-60',
      chapterNumber: 41,
      order: 60,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dative', 'der-word', 'feminine'],
      instruction: 'Write only the missing ending.',
      prompt: 'Ich spreche mit der nett___ Ärztin.',
      acceptedAnswers: ['en'],
      answerMode: 'caseInsensitive',
      placeholder: 'e / er / es / en',
      maxLength: 5,
      explanation: 'mit takes the dative, so the feminine adjective ending is -en: mit der netten Ärztin.',
    },
    {
      id: 'ch41-ex-61',
      chapterNumber: 41,
      order: 61,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dative', 'preposition', 'masculine'],
      instruction: 'Complete the sentence with the correct form of the adjective given.',
      prompt: 'Nach dem ___ Film gehen wir essen. (lang)',
      acceptedAnswers: ['langen'],
      answerMode: 'caseInsensitive',
      placeholder: 'langen',
      maxLength: 20,
      explanation: 'nach takes the dative, so the masculine adjective ending is -en: nach dem langen Film.',
    },
    {
      id: 'ch41-ex-62',
      chapterNumber: 41,
      order: 62,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['dative', 'error-correction', 'feminine'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Wir danken einer freundliche Frau.',
      acceptedAnswers: ['Wir danken einer freundlichen Frau.'],
      answerMode: 'normalized',
      placeholder: 'Wir danken einer freundlichen ...',
      maxLength: 60,
      explanation: 'After einer in the dative, the adjective ending is -en, not the feminine -e: einer freundlichen Frau.',
    },
  ],
};
