import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter045: ChapterDefinition = {
  id: 'chapter-045',
  number: 45,
  slug: 'connectors-deshalb-sonst-dann-and-danach',
  title: 'Connectors: deshalb, sonst, dann, danach',
  germanTitle: 'Konnektoren: deshalb, sonst, dann, danach',
  level: 'A2',
  section: 'sentence-connections-1',
  objective:
    'Use deshalb, sonst, dann, and danach to link two main clauses expressing cause and result, warning and consequence, or a sequence of actions, recognising that each connector fills position 1 of its own clause and therefore triggers inversion (connector + verb + subject), and punctuate the two clauses correctly with a comma or a full stop.',
  prerequisites: [12, 13, 44],
  estimatedMinutes: 25,
  tags: [
    'connectors',
    'deshalb',
    'sonst',
    'dann',
    'danach',
    'word order',
    'inversion',
    'cause and result',
    'sequence',
    'sentence-connections',
  ],
  explanation: {
    introduction: [
      'deshalb, sonst, dann, and danach let you connect two separate ideas — a cause and its result, a warning and its consequence, or one action and the next — without a subordinating conjunction like weil or wenn. Each of these words is an adverb that can open the second clause.',
      'The key grammar point is inversion: because these connectors take position 1 of their clause, the finite verb must immediately follow in position 2, and the subject is pushed back to position 3. This is different from coordinating conjunctions like und, aber, oder, denn, and sondern, which do not count as a sentence element and never change the word order that follows them.',
      'Getting comfortable with deshalb, sonst, dann, and danach means learning two things at once: which connector fits the meaning you want (cause-result, warning, or sequence), and how to build the connector + verb + subject word order correctly every time.',
    ],
    rules: [
      {
        id: 'ch45-rule-01',
        heading: 'Connectors that occupy their own sentence position',
        paragraphs: [
          'deshalb, sonst, dann, and danach are adverbial connectors: unlike coordinating conjunctions such as und or aber, each one counts as a single sentence element and can occupy position 1 of its clause.',
          'Because they behave like any other adverb (for example jetzt or heute), placing one at the start of a sentence changes the word order that follows, in a way und and aber never do.',
        ],
      },
      {
        id: 'ch45-rule-02',
        heading: 'The verb stays in position 2 — but the subject moves',
        paragraphs: [
          'German main clauses always keep the finite verb in position 2. When deshalb, sonst, dann, or danach fills position 1, the verb still comes second — which pushes the subject into position 3, right after the verb.',
          'Es regnet. Deshalb bleiben wir zu Hause. (It is raining. That is why we are staying home.) bleiben is in position 2, and wir follows it, not the other way around.',
        ],
      },
      {
        id: 'ch45-rule-03',
        heading: 'deshalb: linking a cause to its result',
        paragraphs: [
          'deshalb ("therefore," "that\'s why") introduces the logical result of a cause named in the previous clause or sentence.',
          'Ich habe die ganze Nacht gearbeitet. Deshalb bin ich müde. (I worked all night. That is why I am tired.)',
        ],
      },
      {
        id: 'ch45-rule-04',
        heading: 'sonst: warning of a negative consequence',
        paragraphs: [
          'sonst ("otherwise") introduces what will happen if an instruction, request, or condition in the previous clause is not followed.',
          "Beeil dich, sonst verpassen wir den Bus. (Hurry up, otherwise we'll miss the bus.) — the second clause states the unwanted result of not hurrying.",
        ],
      },
      {
        id: 'ch45-rule-05',
        heading: 'dann: sequence or conditional result',
        paragraphs: [
          'dann ("then") can either mark the next step in a sequence of actions, or express "in that case" — a consequence that depends on a condition stated just before it.',
          'Wir essen zuerst. Dann gehen wir spazieren. (sequence) versus Wenn du willst, dann kannst du mitkommen. (conditional: "if you want, then you can come along.")',
        ],
      },
      {
        id: 'ch45-rule-06',
        heading: 'danach: strictly "after that" in time',
        paragraphs: [
          'danach ("after that," "afterwards") only marks a temporal sequence — one action following directly after another. Unlike dann, it cannot express a conditional result.',
          'Wir kochen zusammen. Danach räumen wir die Küche auf. (We cook together. After that we clean up the kitchen.)',
        ],
      },
      {
        id: 'ch45-rule-07',
        heading: 'Punctuation between the two main clauses',
        paragraphs: [
          'Both clauses linked by these connectors remain independent main clauses. You may separate them with a comma and continue in the same sentence, or write them as two separate sentences with a full stop — both are correct and equally common.',
          'Es regnet, deshalb bleiben wir zu Hause. and Es regnet. Deshalb bleiben wir zu Hause. are both grammatically correct; the choice is purely stylistic.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch45-table-01',
        title: 'The four connectors: meaning and type',
        columns: ['Connector', 'Meaning', 'Type', 'Example'],
        rows: [
          [
            'deshalb',
            "therefore / that's why",
            'cause → result',
            'Es regnet. Deshalb bleiben wir zu Hause.',
          ],
          [
            'sonst',
            'otherwise',
            'warning → consequence',
            'Beeil dich, sonst verpassen wir den Bus.',
          ],
          [
            'dann',
            'then / in that case',
            'sequence or conditional result',
            'Wir essen zuerst. Dann gehen wir spazieren.',
          ],
          [
            'danach',
            'after that',
            'sequence (strictly temporal)',
            'Wir essen. Danach gehen wir spazieren.',
          ],
        ],
        note: 'dann and danach both translate as "then," but dann also covers a conditional result while danach only marks what comes next in time.',
      },
      {
        id: 'ch45-table-02',
        title: 'Inversion: connector + verb + subject',
        columns: ['Clause 1', 'Connector', 'Verb', 'Subject', 'Rest of clause 2'],
        rows: [
          ['Es regnet.', 'Deshalb', 'bleiben', 'wir', 'zu Hause.'],
          ['Er lernt nicht.', 'Sonst', 'besteht', 'er', 'die Prüfung nicht.'],
          ['Wir kochen.', 'Dann', 'essen', 'wir', 'zusammen.'],
          ['Wir essen.', 'Danach', 'gehen', 'wir', 'spazieren.'],
        ],
        note: 'The connector fills position 1, the finite verb always follows immediately in position 2, and the subject comes right after the verb in position 3.',
      },
    ],
    examples: [
      {
        german: 'Es regnet. Deshalb bleiben wir zu Hause.',
        english: 'It is raining. That is why we are staying home.',
        highlight: ['Deshalb bleiben wir'],
        explanation:
          'deshalb links the cause (rain) to its result; bleiben (verb) comes before wir (subject).',
      },
      {
        german: 'Ich habe keine Zeit. Deshalb kann ich nicht kommen.',
        english: "I don't have time. That's why I can't come.",
        highlight: ['Deshalb kann ich'],
        explanation:
          'deshalb introduces the result (cannot come) of the stated cause (no time); kann precedes ich.',
      },
      {
        german: 'Beeil dich, sonst verpassen wir den Bus.',
        english: "Hurry up, otherwise we'll miss the bus.",
        highlight: ['sonst verpassen wir'],
        explanation:
          'sonst warns of the negative consequence of not hurrying; verpassen comes before wir.',
      },
      {
        german: 'Lern für die Prüfung, sonst fällst du durch.',
        english: "Study for the exam, otherwise you'll fail.",
        highlight: ['sonst fällst du'],
        explanation:
          'sonst introduces what happens if the instruction is ignored; fällst comes before du.',
      },
      {
        german: 'Wir essen zuerst. Dann gehen wir spazieren.',
        english: "We'll eat first. Then we'll go for a walk.",
        highlight: ['Dann gehen wir'],
        explanation:
          'dann marks the next step in a sequence of actions; gehen comes before wir.',
      },
      {
        german: 'Nimm einen Regenschirm mit, dann bleibst du trocken.',
        english: "Take an umbrella with you, then you'll stay dry.",
        highlight: ['dann bleibst du'],
        explanation:
          'Here dann expresses a conditional result ("in that case"), not strictly a time sequence; bleibst comes before du.',
      },
      {
        german: 'Wir kochen zusammen. Danach räumen wir die Küche auf.',
        english: 'We cook together. After that we clean up the kitchen.',
        highlight: ['Danach räumen wir'],
        explanation: 'danach marks a strict temporal sequence; räumen comes before wir.',
      },
      {
        german: 'Er duscht. Danach zieht er sich an.',
        english: 'He showers. After that he gets dressed.',
        highlight: ['Danach zieht er'],
        explanation:
          'danach shows that getting dressed strictly follows showering; zieht comes before er.',
      },
      {
        german: 'Ich bin müde. Deshalb gehe ich früh ins Bett.',
        english: 'I am tired. That is why I am going to bed early.',
        highlight: ['Deshalb gehe ich'],
        explanation:
          'deshalb links tiredness (cause) to going to bed early (result); gehe comes before ich.',
      },
      {
        german: 'Sei leise, sonst weckst du das Baby.',
        english: "Be quiet, otherwise you'll wake the baby.",
        highlight: ['sonst weckst du'],
        explanation:
          'sonst warns of the consequence of not being quiet; weckst comes before du.',
      },
      {
        german: 'Wir treffen uns um acht. Dann gehen wir ins Kino.',
        english: "We'll meet at eight. Then we'll go to the cinema.",
        highlight: ['Dann gehen wir'],
        explanation: 'dann marks the next planned step; gehen comes before wir.',
      },
      {
        german: 'Ich rufe dich an. Danach schreibst du mir eine E-Mail.',
        english: "I'll call you. After that you write me an email.",
        highlight: ['Danach schreibst du'],
        explanation:
          'danach marks the step that strictly follows the phone call; schreibst comes before du.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Es regnet. Deshalb wir bleiben zu Hause.',
        correct: 'Es regnet. Deshalb bleiben wir zu Hause.',
        explanation:
          'deshalb occupies position 1, so the verb bleiben must come immediately after it, before the subject wir.',
      },
      {
        incorrect: 'Beeil dich, sonst wir verpassen den Bus.',
        correct: 'Beeil dich, sonst verpassen wir den Bus.',
        explanation:
          'sonst takes position 1 of its clause, so the verb verpassen must follow it directly, before the subject wir.',
      },
      {
        incorrect: 'Wir essen zuerst, dann wir gehen spazieren.',
        correct: 'Wir essen zuerst, dann gehen wir spazieren.',
        explanation:
          'dann occupies position 1, so the verb gehen comes next, followed by the subject wir.',
      },
      {
        incorrect: 'Wir kochen. Danach wir räumen die Küche auf.',
        correct: 'Wir kochen. Danach räumen wir die Küche auf.',
        explanation:
          'danach occupies position 1, so the verb räumen comes immediately after it, before the subject wir.',
      },
      {
        incorrect: 'Ich habe keine Zeit, und deshalb ich kann nicht kommen.',
        correct: 'Ich habe keine Zeit, deshalb kann ich nicht kommen.',
        explanation:
          'deshalb already functions as the connector and fills position 1 on its own; it should not be combined with und, and the verb kann must directly follow deshalb.',
      },
    ],
    remember: [
      'deshalb, sonst, dann, and danach are adverbial connectors, not conjunctions: each one occupies position 1 of its own clause.',
      'Because they take position 1, the verb moves to position 2 and the subject follows the verb: Connector + Verb + Subject.',
      'deshalb links cause and result; sonst warns of a negative consequence; dann and danach both mean "then," but dann can also express a conditional result while danach is strictly "after that" in time.',
      'Separate the two main clauses with a comma or a full stop — both are correct; do not add und or aber before these connectors.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 81,
    requiredCorrectTextInputs: 16,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch45-ex-01',
      chapterNumber: 45,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['deshalb', 'connector-meaning'],
      instruction: 'Choose the connector with the meaning given.',
      prompt:
        'Which connector means "therefore / that\'s why," showing a cause and its result?',
      options: [
        { id: 'a', text: 'deshalb' },
        { id: 'b', text: 'sonst' },
        { id: 'c', text: 'dann' },
        { id: 'd', text: 'danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb introduces the result of a cause stated in the previous sentence: "therefore/that\'s why."',
    },
    {
      id: 'ch45-ex-02',
      chapterNumber: 45,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sonst', 'connector-meaning'],
      instruction: 'Choose the connector with the meaning given.',
      prompt: 'Which connector means "otherwise," warning of a negative consequence?',
      options: [
        { id: 'a', text: 'sonst' },
        { id: 'b', text: 'deshalb' },
        { id: 'c', text: 'dann' },
        { id: 'd', text: 'danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'sonst warns what will happen if the previous instruction or condition is not fulfilled: "otherwise."',
    },
    {
      id: 'ch45-ex-03',
      chapterNumber: 45,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dann', 'danach', 'connector-meaning'],
      instruction: 'Choose the connector with the meaning given.',
      prompt:
        'Which connector specifically means "after that," describing one action strictly following another in time?',
      options: [
        { id: 'a', text: 'danach' },
        { id: 'b', text: 'dann' },
        { id: 'c', text: 'deshalb' },
        { id: 'd', text: 'sonst' },
      ],
      correctOptionId: 'a',
      explanation:
        'danach means "after that" and marks a strict temporal sequence; dann can also express a looser "then," including a conditional result.',
    },
    {
      id: 'ch45-ex-04',
      chapterNumber: 45,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['deshalb', 'word-order', 'inversion'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt: 'Es regnet. ___',
      options: [
        { id: 'a', text: 'Deshalb bleiben wir zu Hause.' },
        { id: 'b', text: 'Deshalb wir bleiben zu Hause.' },
        { id: 'c', text: 'Wir deshalb bleiben zu Hause.' },
        { id: 'd', text: 'Bleiben deshalb wir zu Hause.' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb occupies position 1, so the verb bleiben must follow immediately in position 2, before the subject wir.',
    },
    {
      id: 'ch45-ex-05',
      chapterNumber: 45,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sonst', 'word-order', 'inversion'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt: 'Lern mehr, ___',
      options: [
        { id: 'a', text: 'sonst fällst du durch.' },
        { id: 'b', text: 'sonst du fällst durch.' },
        { id: 'c', text: 'sonst fällst durch du.' },
        { id: 'd', text: 'sonst du durch fällst.' },
      ],
      correctOptionId: 'a',
      explanation:
        'sonst takes position 1 in its clause, so the verb fällst comes next, followed by the subject du.',
    },
    {
      id: 'ch45-ex-06',
      chapterNumber: 45,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['deshalb', 'word-order', 'verb-position'],
      instruction: 'Choose the correctly ordered continuation.',
      prompt: 'Es ist spät. Deshalb ___',
      options: [
        { id: 'a', text: 'gehen wir jetzt.' },
        { id: 'b', text: 'wir gehen jetzt.' },
        { id: 'c', text: 'jetzt wir gehen.' },
        { id: 'd', text: 'gehen jetzt wir.' },
      ],
      correctOptionId: 'a',
      explanation:
        'After deshalb (position 1), the verb gehen comes in position 2, immediately followed by the subject wir: Deshalb gehen wir jetzt.',
    },
    {
      id: 'ch45-ex-07',
      chapterNumber: 45,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['deshalb', 'connector-meaning', 'cause-result'],
      instruction: 'Choose the connector that fits the meaning of the sentence.',
      prompt: 'Ich habe die ganze Nacht gearbeitet. ___ bin ich sehr müde.',
      options: [
        { id: 'a', text: 'Deshalb' },
        { id: 'b', text: 'Sonst' },
        { id: 'c', text: 'Dann' },
        { id: 'd', text: 'Danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'The second clause states the result of working all night, so deshalb ("therefore") is correct.',
    },
    {
      id: 'ch45-ex-08',
      chapterNumber: 45,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sonst', 'connector-meaning', 'warning'],
      instruction: 'Choose the connector that fits the meaning of the sentence.',
      prompt: 'Zieh dir eine Jacke an, ___ erkältest du dich.',
      options: [
        { id: 'a', text: 'sonst' },
        { id: 'b', text: 'deshalb' },
        { id: 'c', text: 'dann' },
        { id: 'd', text: 'danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'The second clause warns of a negative consequence if the instruction is ignored, so sonst ("otherwise") is correct.',
    },
    {
      id: 'ch45-ex-09',
      chapterNumber: 45,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sonst', 'connector-meaning', 'warning', 'pragmatics'],
      instruction:
        "Read the short exchange, then choose the connector that fits the mother's warning.",
      dialogue: [
        {
          speaker: 'Kind',
          german: 'Ich will keine Mütze anziehen!',
          english: "I don't want to wear a hat!",
        },
        {
          speaker: 'Mutter',
          german: 'Zieh sie trotzdem an!',
          english: 'Put it on anyway!',
        },
      ],
      prompt: 'Wie warnt die Mutter weiter? ___ erkältest du dich noch!',
      options: [
        { id: 'a', text: 'Sonst' },
        { id: 'b', text: 'Deshalb' },
        { id: 'c', text: 'Dann' },
        { id: 'd', text: 'Danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'The mother is warning what will happen if the child does not wear the hat, so sonst ("otherwise") fits the exchange.',
    },
    {
      id: 'ch45-ex-10',
      chapterNumber: 45,
      order: 10,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['deshalb', 'word-order', 'pragmatics'],
      instruction:
        "Read the short exchange, then choose the sentence with the correct word order for Tom's explanation.",
      dialogue: [
        {
          speaker: 'Lisa',
          german: 'Warum bist du so müde?',
          english: 'Why are you so tired?',
        },
        {
          speaker: 'Tom',
          german: 'Ich habe schlecht geschlafen.',
          english: 'I slept badly.',
        },
      ],
      prompt: 'Wie geht Toms Erklärung weiter?',
      options: [
        { id: 'a', text: 'Deshalb bin ich müde.' },
        { id: 'b', text: 'Deshalb ich bin müde.' },
        { id: 'c', text: 'Ich deshalb bin müde.' },
        { id: 'd', text: 'Bin deshalb ich müde.' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb takes position 1, so the verb bin follows immediately, then the subject ich: Deshalb bin ich müde.',
    },
    {
      id: 'ch45-ex-11',
      chapterNumber: 45,
      order: 11,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['dann', 'conditional', 'connector-meaning'],
      instruction: 'Choose the connector that fits the meaning of the sentence.',
      prompt:
        'Wenn du willst, kannst du mitkommen. ___ triffst du uns um acht Uhr vor dem Kino.',
      options: [
        { id: 'a', text: 'Dann' },
        { id: 'b', text: 'Danach' },
        { id: 'c', text: 'Deshalb' },
        { id: 'd', text: 'Sonst' },
      ],
      correctOptionId: 'a',
      explanation:
        'dann here expresses a conditional consequence ("in that case"), not a strict time sequence, so danach would not fit as naturally.',
    },
    {
      id: 'ch45-ex-12',
      chapterNumber: 45,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['dann', 'danach', 'timeline-ordering'],
      instruction: 'Choose the connector that best continues the timeline.',
      prompt:
        'Wir packen zuerst die Koffer. Dann fahren wir zum Flughafen. ___ checken wir ein.',
      options: [
        { id: 'a', text: 'Danach' },
        { id: 'b', text: 'Dann' },
        { id: 'c', text: 'Deshalb' },
        { id: 'd', text: 'Sonst' },
      ],
      correctOptionId: 'a',
      explanation:
        'Since dann already marks the previous step, danach ("after that") continues the sequence naturally, and checking in strictly follows arriving at the airport.',
    },
    {
      id: 'ch45-ex-13',
      chapterNumber: 45,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['deshalb', 'sentence-combination', 'word-order'],
      instruction: 'Choose the correctly combined sentence.',
      prompt: 'Combine: "Es regnet stark." + "Wir bleiben zu Hause." (cause and result)',
      options: [
        { id: 'a', text: 'Es regnet stark, deshalb bleiben wir zu Hause.' },
        { id: 'b', text: 'Es regnet stark, deshalb wir bleiben zu Hause.' },
        { id: 'c', text: 'Es regnet stark, sonst bleiben wir zu Hause.' },
        { id: 'd', text: 'Es regnet stark, bleiben wir deshalb zu Hause.' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb correctly signals cause and result, and after deshalb the verb bleiben comes before the subject wir.',
    },
    {
      id: 'ch45-ex-14',
      chapterNumber: 45,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['deshalb', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Ich bin krank. Deshalb ___ (bleiben – ich) zu Hause.',
      acceptedAnswers: ['bleibe ich'],
      answerMode: 'caseInsensitive',
      placeholder: 'bleibe ich',
      maxLength: 20,
      explanation:
        'After deshalb (position 1), the verb bleibe comes in position 2, followed by the subject ich: Deshalb bleibe ich zu Hause.',
    },
    {
      id: 'ch45-ex-15',
      chapterNumber: 45,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sonst', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Nimm einen Regenschirm mit, sonst ___ (werden – du) nass.',
      acceptedAnswers: ['wirst du'],
      answerMode: 'caseInsensitive',
      placeholder: 'wirst du',
      maxLength: 20,
      explanation:
        'sonst takes position 1, so the verb wirst follows immediately, then the subject du: sonst wirst du nass.',
    },
    {
      id: 'ch45-ex-16',
      chapterNumber: 45,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dann', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Wir packen die Koffer. Dann ___ (fahren – wir) los.',
      acceptedAnswers: ['fahren wir'],
      answerMode: 'caseInsensitive',
      placeholder: 'fahren wir',
      maxLength: 20,
      explanation:
        'dann is in position 1, so the verb fahren comes next, followed by wir: Dann fahren wir los.',
    },
    {
      id: 'ch45-ex-17',
      chapterNumber: 45,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['danach', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Wir kommen am Flughafen an. Danach ___ (suchen – wir) unser Hotel.',
      acceptedAnswers: ['suchen wir'],
      answerMode: 'caseInsensitive',
      placeholder: 'suchen wir',
      maxLength: 20,
      explanation:
        'danach occupies position 1, so the verb suchen comes in position 2, followed by wir: Danach suchen wir unser Hotel.',
    },
    {
      id: 'ch45-ex-18',
      chapterNumber: 45,
      order: 18,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['deshalb', 'connector-meaning'],
      instruction:
        'Write the connector that fits the meaning "therefore / that\'s why." Capitalisation is not checked.',
      prompt: 'Ich habe Kopfschmerzen. ___ nehme ich eine Tablette.',
      acceptedAnswers: ['Deshalb'],
      answerMode: 'caseInsensitive',
      placeholder: 'Deshalb',
      maxLength: 15,
      explanation:
        'The second clause states the result of having a headache, so deshalb ("therefore") is correct.',
    },
    {
      id: 'ch45-ex-19',
      chapterNumber: 45,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sonst', 'connector-meaning', 'pragmatics'],
      instruction:
        "Read the short exchange, then write the connector that fits the boss's warning. Capitalisation is not checked.",
      dialogue: [
        {
          speaker: 'Chef',
          german: 'Sie müssen den Bericht heute abgeben.',
          english: 'You must submit the report today.',
        },
        {
          speaker: 'Mitarbeiterin',
          german: 'Und wenn ich das nicht schaffe?',
          english: "And if I can't manage that?",
        },
      ],
      prompt: '___ bekommen Sie Probleme mit dem Kunden.',
      acceptedAnswers: ['Sonst'],
      answerMode: 'caseInsensitive',
      placeholder: 'Sonst',
      maxLength: 15,
      explanation:
        'The boss warns of a negative consequence if the report is not submitted, so sonst ("otherwise") is correct.',
    },
    {
      id: 'ch45-ex-20',
      chapterNumber: 45,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['deshalb', 'connector-meaning', 'pragmatics'],
      instruction:
        "Read the short exchange, then write the connector that fits Ben's explanation. Capitalisation is not checked.",
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Warum kommst du zu spät?',
          english: 'Why are you late?',
        },
        {
          speaker: 'Ben',
          german: 'Der Bus hatte Verspätung.',
          english: 'The bus was delayed.',
        },
      ],
      prompt: '___ komme ich zu spät.',
      acceptedAnswers: ['Deshalb'],
      answerMode: 'caseInsensitive',
      placeholder: 'Deshalb',
      maxLength: 15,
      explanation:
        'Ben states a cause (the delayed bus) and its result (being late), so deshalb ("therefore") connects the two.',
    },
    {
      id: 'ch45-ex-21',
      chapterNumber: 45,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dann', 'sentence-combination', 'timeline-ordering'],
      instruction:
        'Combine the two sentences into one, using dann. Capitalisation and punctuation are checked.',
      prompt: 'Wir essen zu Abend. + Wir schauen einen Film.',
      acceptedAnswers: [
        'Wir essen zu Abend, dann schauen wir einen Film.',
        'Wir essen zu Abend. Dann schauen wir einen Film.',
      ],
      answerMode: 'normalized',
      placeholder: 'Wir essen zu Abend, dann schauen wir einen Film.',
      maxLength: 70,
      explanation:
        'dann links the two actions in sequence; after dann (position 1) the verb schauen comes before the subject wir.',
    },
    {
      id: 'ch45-ex-22',
      chapterNumber: 45,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['danach', 'sentence-combination', 'timeline-ordering'],
      instruction:
        'Combine the two sentences into one, using danach. Capitalisation and punctuation are checked.',
      prompt: 'Wir duschen. + Wir frühstücken.',
      acceptedAnswers: [
        'Wir duschen, danach frühstücken wir.',
        'Wir duschen. Danach frühstücken wir.',
      ],
      answerMode: 'normalized',
      placeholder: 'Wir duschen, danach frühstücken wir.',
      maxLength: 60,
      explanation:
        'danach marks what happens strictly after the first action; the verb frühstücken follows danach directly, before the subject wir.',
    },
    {
      id: 'ch45-ex-23',
      chapterNumber: 45,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['deshalb', 'error-correction', 'word-order'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Es ist kalt. Deshalb wir tragen einen Mantel.',
      acceptedAnswers: ['Es ist kalt. Deshalb tragen wir einen Mantel.'],
      answerMode: 'normalized',
      placeholder: 'Es ist kalt. Deshalb ...',
      maxLength: 60,
      explanation:
        'deshalb occupies position 1, so the verb tragen must come immediately after it, before the subject wir.',
    },
    {
      id: 'ch45-ex-24',
      chapterNumber: 45,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sonst', 'error-correction', 'word-order'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Sei leise, sonst du weckst das Baby.',
      acceptedAnswers: ['Sei leise, sonst weckst du das Baby.'],
      answerMode: 'normalized',
      placeholder: 'Sei leise, sonst ...',
      maxLength: 60,
      explanation:
        'sonst takes position 1, so the verb weckst comes next, followed by the subject du.',
    },
    {
      id: 'ch45-ex-25',
      chapterNumber: 45,
      order: 25,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['deshalb', 'sentence-formation', 'cause-result'],
      instruction:
        'Write a complete sentence using deshalb for the cues in brackets. Capitalisation and punctuation are checked.',
      prompt: 'er – keine Zeit haben – nicht mitkommen können',
      acceptedAnswers: [
        'Er hat keine Zeit, deshalb kann er nicht mitkommen.',
        'Er hat keine Zeit. Deshalb kann er nicht mitkommen.',
      ],
      answerMode: 'normalized',
      placeholder: 'Er hat keine Zeit, deshalb ...',
      maxLength: 70,
      explanation:
        'The cause (no time) and result (cannot come along) are linked by deshalb, with kann in position 2 right after deshalb.',
    },
    {
      id: 'ch45-ex-26',
      chapterNumber: 45,
      order: 26,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['danach', 'timeline-ordering', 'sentence-combination', 'pragmatics'],
      instruction:
        "Read the short exchange, then write the guide's reply as one sentence using danach. Capitalisation and punctuation are checked.",
      dialogue: [
        {
          speaker: 'Reiseleiter',
          german: 'Wir besuchen zuerst das Museum.',
          english: "First we'll visit the museum.",
        },
        {
          speaker: 'Tourist',
          german: 'Und was machen wir danach?',
          english: 'And what do we do after that?',
        },
      ],
      prompt: 'Antworte mit: Wir besuchen das Museum. + Wir essen zu Mittag.',
      acceptedAnswers: [
        'Wir besuchen das Museum, danach essen wir zu Mittag.',
        'Danach essen wir zu Mittag.',
      ],
      answerMode: 'normalized',
      placeholder: 'Wir besuchen das Museum, danach essen wir zu Mittag.',
      maxLength: 70,
      explanation:
        'danach marks the next step in the timeline; the verb essen follows danach directly, before the subject wir.',
    },
    {
      id: 'ch45-ex-27',
      chapterNumber: 45,
      order: 27,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['deshalb', 'connector-meaning'],
      instruction: 'Choose the connector that fits the meaning of the sentence.',
      prompt: 'Ich bin erkältet. ___ bleibe ich im Bett.',
      options: [
        { id: 'a', text: 'Deshalb' },
        { id: 'b', text: 'Sonst' },
        { id: 'c', text: 'Dann' },
        { id: 'd', text: 'Danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'The second clause states the result of having a cold, so deshalb ("therefore") is correct.',
    },
    {
      id: 'ch45-ex-28',
      chapterNumber: 45,
      order: 28,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sonst', 'connector-meaning'],
      instruction: 'Choose the connector that fits the meaning of the sentence.',
      prompt: 'Trink genug Wasser, ___ bekommst du Kopfschmerzen.',
      options: [
        { id: 'a', text: 'sonst' },
        { id: 'b', text: 'deshalb' },
        { id: 'c', text: 'dann' },
        { id: 'd', text: 'danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'The second clause warns of a negative consequence, so sonst ("otherwise") is correct.',
    },
    {
      id: 'ch45-ex-29',
      chapterNumber: 45,
      order: 29,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['danach', 'connector-meaning', 'timeline-ordering'],
      instruction: 'Choose the connector that fits the meaning of the sentence.',
      prompt: 'Wir duschen. ___ ziehen wir uns an.',
      options: [
        { id: 'a', text: 'Danach' },
        { id: 'b', text: 'Deshalb' },
        { id: 'c', text: 'Sonst' },
        { id: 'd', text: 'Dann' },
      ],
      correctOptionId: 'a',
      explanation:
        'Getting dressed strictly follows showering, so danach ("after that") fits best.',
    },
    {
      id: 'ch45-ex-30',
      chapterNumber: 45,
      order: 30,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['deshalb', 'word-order', 'inversion'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt: 'Es ist Sonntag. ___',
      options: [
        { id: 'a', text: 'Deshalb schlafen wir lange.' },
        { id: 'b', text: 'Deshalb wir schlafen lange.' },
        { id: 'c', text: 'Wir deshalb schlafen lange.' },
        { id: 'd', text: 'Schlafen deshalb wir lange.' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb occupies position 1, so the verb schlafen must follow immediately, before the subject wir.',
    },
    {
      id: 'ch45-ex-31',
      chapterNumber: 45,
      order: 31,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sonst', 'word-order', 'inversion'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt: 'Rutsch nicht aus, ___',
      options: [
        { id: 'a', text: 'sonst fällst du hin.' },
        { id: 'b', text: 'sonst du fällst hin.' },
        { id: 'c', text: 'sonst fällst hin du.' },
        { id: 'd', text: 'sonst du hin fällst.' },
      ],
      correctOptionId: 'a',
      explanation:
        'sonst takes position 1, so the verb fällst comes next, followed by the subject du.',
    },
    {
      id: 'ch45-ex-32',
      chapterNumber: 45,
      order: 32,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['dann', 'word-order', 'inversion'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt: 'Wir räumen auf. ___',
      options: [
        { id: 'a', text: 'Dann kochen wir zusammen.' },
        { id: 'b', text: 'Dann wir kochen zusammen.' },
        { id: 'c', text: 'Wir dann kochen zusammen.' },
        { id: 'd', text: 'Kochen dann wir zusammen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'dann is in position 1, so the verb kochen comes next, followed by the subject wir.',
    },
    {
      id: 'ch45-ex-33',
      chapterNumber: 45,
      order: 33,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['danach', 'word-order', 'inversion'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt: 'Er duscht. ___',
      options: [
        { id: 'a', text: 'Danach frühstückt er.' },
        { id: 'b', text: 'Danach er frühstückt.' },
        { id: 'c', text: 'Er danach frühstückt.' },
        { id: 'd', text: 'Frühstückt danach er.' },
      ],
      correctOptionId: 'a',
      explanation:
        'danach occupies position 1, so the verb frühstückt must follow immediately, before the subject er.',
    },
    {
      id: 'ch45-ex-34',
      chapterNumber: 45,
      order: 34,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['deshalb', 'word-order', 'pragmatics'],
      instruction:
        "Read the short exchange, then choose the sentence with the correct word order for Ben's explanation.",
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Warum bist du so nervös?',
          english: 'Why are you so nervous?',
        },
        {
          speaker: 'Ben',
          german: 'Ich habe morgen eine Prüfung.',
          english: 'I have an exam tomorrow.',
        },
      ],
      prompt: 'Wie geht Bens Erklärung weiter?',
      options: [
        { id: 'a', text: 'Deshalb bin ich nervös.' },
        { id: 'b', text: 'Deshalb ich bin nervös.' },
        { id: 'c', text: 'Ich deshalb bin nervös.' },
        { id: 'd', text: 'Bin deshalb ich nervös.' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb takes position 1, so the verb bin follows immediately, then the subject ich.',
    },
    {
      id: 'ch45-ex-35',
      chapterNumber: 45,
      order: 35,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['sonst', 'word-order', 'pragmatics'],
      instruction:
        "Read the short exchange, then choose the mother's correctly ordered reply.",
      dialogue: [
        {
          speaker: 'Mutter',
          german: 'Zieh dir eine Mütze an!',
          english: 'Put on a hat!',
        },
        {
          speaker: 'Kind',
          german: 'Muss ich wirklich?',
          english: 'Do I really have to?',
        },
      ],
      prompt: 'Wie antwortet die Mutter?',
      options: [
        { id: 'a', text: 'Sonst erkältest du dich.' },
        { id: 'b', text: 'Sonst du erkältest dich.' },
        { id: 'c', text: 'Du sonst erkältest dich.' },
        { id: 'd', text: 'Erkältest sonst du dich.' },
      ],
      correctOptionId: 'a',
      explanation:
        'sonst takes position 1, so the verb erkältest comes next, followed by the subject du.',
    },
    {
      id: 'ch45-ex-36',
      chapterNumber: 45,
      order: 36,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['deshalb', 'sentence-combination', 'word-order'],
      instruction: 'Choose the correctly combined sentence.',
      prompt: 'Combine: "Wir sind müde." + "Wir gehen ins Bett." (cause and result)',
      options: [
        { id: 'a', text: 'Wir sind müde, deshalb gehen wir ins Bett.' },
        { id: 'b', text: 'Wir sind müde, deshalb wir gehen ins Bett.' },
        { id: 'c', text: 'Wir sind müde, sonst gehen wir ins Bett.' },
        { id: 'd', text: 'Wir sind müde, gehen wir deshalb ins Bett.' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb correctly signals cause and result, and the verb gehen follows deshalb directly, before the subject wir.',
    },
    {
      id: 'ch45-ex-37',
      chapterNumber: 45,
      order: 37,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dann', 'danach', 'connector-meaning'],
      instruction: 'Choose the connector that fits the description.',
      prompt:
        'Which connector can express a conditional result ("in that case"), not only a strict time sequence?',
      options: [
        { id: 'a', text: 'dann' },
        { id: 'b', text: 'danach' },
        { id: 'c', text: 'deshalb' },
        { id: 'd', text: 'sonst' },
      ],
      correctOptionId: 'a',
      explanation:
        'dann covers both "next step" and "in that case," while danach is strictly temporal.',
    },
    {
      id: 'ch45-ex-38',
      chapterNumber: 45,
      order: 38,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['dann', 'danach', 'connector-meaning'],
      instruction: 'Choose the pair of connectors described.',
      prompt:
        'Which two connectors both translate as "then," but only one of them can also express a conditional result?',
      options: [
        { id: 'a', text: 'dann and danach' },
        { id: 'b', text: 'deshalb and sonst' },
        { id: 'c', text: 'dann and deshalb' },
        { id: 'd', text: 'sonst and danach' },
      ],
      correctOptionId: 'a',
      explanation:
        'dann and danach both mean "then," but only dann can also express "in that case."',
    },
    {
      id: 'ch45-ex-39',
      chapterNumber: 45,
      order: 39,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['danach', 'word-order', 'punctuation'],
      instruction:
        'Choose the correctly ordered continuation, written as a separate sentence.',
      prompt: 'Wir kochen zusammen. ___',
      options: [
        { id: 'a', text: 'Danach räumen wir auf.' },
        { id: 'b', text: 'Danach wir räumen auf.' },
        { id: 'c', text: 'Wir danach räumen auf.' },
        { id: 'd', text: 'Räumen danach wir auf.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Even as a separate sentence, danach still fills position 1, so the verb räumen follows immediately, before wir.',
    },
    {
      id: 'ch45-ex-40',
      chapterNumber: 45,
      order: 40,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['deshalb', 'common-mistake', 'word-order'],
      instruction:
        'Choose the sentence that correctly follows the rule that deshalb is not combined with und.',
      prompt: 'Ich habe keine Zeit. ___',
      options: [
        { id: 'a', text: 'Ich habe keine Zeit, deshalb kann ich nicht kommen.' },
        { id: 'b', text: 'Ich habe keine Zeit, und deshalb ich kann nicht kommen.' },
        { id: 'c', text: 'Ich habe keine Zeit, und deshalb kann ich nicht kommen.' },
        { id: 'd', text: 'Ich habe keine Zeit deshalb ich kann nicht kommen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'deshalb already functions as the connector, so it should not be combined with und, and kann must directly follow deshalb.',
    },
    {
      id: 'ch45-ex-41',
      chapterNumber: 45,
      order: 41,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['deshalb', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Ich habe Fieber. Deshalb ___ (bleiben – ich) im Bett.',
      acceptedAnswers: ['bleibe ich'],
      answerMode: 'caseInsensitive',
      placeholder: 'bleibe ich',
      maxLength: 20,
      explanation:
        'After deshalb (position 1), the verb bleibe comes in position 2, followed by the subject ich.',
    },
    {
      id: 'ch45-ex-42',
      chapterNumber: 45,
      order: 42,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sonst', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Pass auf, sonst ___ (fallen – du) hin.',
      acceptedAnswers: ['fällst du'],
      answerMode: 'caseInsensitive',
      placeholder: 'fällst du',
      maxLength: 20,
      explanation:
        'sonst takes position 1, so the verb fällst comes next, followed by the subject du.',
    },
    {
      id: 'ch45-ex-43',
      chapterNumber: 45,
      order: 43,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dann', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Wir lernen zusammen. Dann ___ (verstehen – wir) die Grammatik besser.',
      acceptedAnswers: ['verstehen wir'],
      answerMode: 'caseInsensitive',
      placeholder: 'verstehen wir',
      maxLength: 20,
      explanation:
        'dann is in position 1, so the verb verstehen comes next, followed by wir.',
    },
    {
      id: 'ch45-ex-44',
      chapterNumber: 45,
      order: 44,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['danach', 'word-order', 'verb-position'],
      instruction:
        'Write the verb and subject in the correct order. Capitalisation is not checked.',
      prompt: 'Wir essen zu Abend. Danach ___ (spielen – wir) ein Spiel.',
      acceptedAnswers: ['spielen wir'],
      answerMode: 'caseInsensitive',
      placeholder: 'spielen wir',
      maxLength: 20,
      explanation:
        'danach occupies position 1, so the verb spielen comes in position 2, followed by wir.',
    },
    {
      id: 'ch45-ex-45',
      chapterNumber: 45,
      order: 45,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sonst', 'connector-meaning'],
      instruction:
        'Write the connector that fits the meaning "otherwise." Capitalisation is not checked.',
      prompt: 'Fahr langsamer, ___ passiert ein Unfall.',
      acceptedAnswers: ['sonst'],
      answerMode: 'caseInsensitive',
      placeholder: 'sonst',
      maxLength: 15,
      explanation:
        'The second clause warns of a negative consequence, so sonst ("otherwise") is correct.',
    },
    {
      id: 'ch45-ex-46',
      chapterNumber: 45,
      order: 46,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['deshalb', 'connector-meaning'],
      instruction:
        'Write the connector that fits the meaning "therefore / that\'s why." Capitalisation is not checked.',
      prompt: 'Ich bin krank. ___ gehe ich zum Arzt.',
      acceptedAnswers: ['Deshalb'],
      answerMode: 'caseInsensitive',
      placeholder: 'Deshalb',
      maxLength: 15,
      explanation:
        'The second clause states the result of being sick, so deshalb ("therefore") is correct.',
    },
    {
      id: 'ch45-ex-47',
      chapterNumber: 45,
      order: 47,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['deshalb', 'connector-meaning', 'pragmatics'],
      instruction:
        'Read the short exchange, then write the connector that fits your explanation. Capitalisation is not checked.',
      dialogue: [
        {
          speaker: 'Freund',
          german: 'Warum lernst du so viel?',
          english: 'Why do you study so much?',
        },
        {
          speaker: 'Du',
          german: 'Ich will die Prüfung bestehen.',
          english: 'I want to pass the exam.',
        },
      ],
      prompt: '___ lerne ich jeden Tag.',
      acceptedAnswers: ['Deshalb'],
      answerMode: 'caseInsensitive',
      placeholder: 'Deshalb',
      maxLength: 15,
      explanation:
        'You state a cause (wanting to pass) and its result (studying every day), so deshalb connects them.',
    },
    {
      id: 'ch45-ex-48',
      chapterNumber: 45,
      order: 48,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sonst', 'connector-meaning', 'pragmatics'],
      instruction:
        'Read the short exchange, then write the connector that fits the warning. Capitalisation is not checked.',
      dialogue: [
        {
          speaker: 'Chef',
          german: 'Der Kunde wartet schon lange.',
          english: 'The customer has been waiting a long time.',
        },
        {
          speaker: 'Angestellter',
          german: 'Ich rufe ihn sofort an.',
          english: 'I will call him right away.',
        },
      ],
      prompt: 'Sei pünktlich, ___ wartet der Kunde vergeblich.',
      acceptedAnswers: ['sonst'],
      answerMode: 'caseInsensitive',
      placeholder: 'sonst',
      maxLength: 15,
      explanation:
        'The clause warns of a negative consequence if punctuality is ignored, so sonst ("otherwise") fits.',
    },
    {
      id: 'ch45-ex-49',
      chapterNumber: 45,
      order: 49,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dann', 'sentence-combination', 'timeline-ordering'],
      instruction:
        'Combine the two sentences into one, using dann. Capitalisation and punctuation are checked.',
      prompt: 'Wir treffen uns um sieben. + Wir gehen essen.',
      acceptedAnswers: [
        'Wir treffen uns um sieben, dann gehen wir essen.',
        'Wir treffen uns um sieben. Dann gehen wir essen.',
      ],
      answerMode: 'normalized',
      placeholder: 'Wir treffen uns um sieben, dann gehen wir essen.',
      maxLength: 70,
      explanation:
        'dann links the two planned steps; the verb gehen follows dann directly, before the subject wir.',
    },
    {
      id: 'ch45-ex-50',
      chapterNumber: 45,
      order: 50,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['danach', 'sentence-combination', 'timeline-ordering'],
      instruction:
        'Combine the two sentences into one, using danach. Capitalisation and punctuation are checked.',
      prompt: 'Wir packen die Koffer. + Wir fahren zum Flughafen.',
      acceptedAnswers: [
        'Wir packen die Koffer, danach fahren wir zum Flughafen.',
        'Wir packen die Koffer. Danach fahren wir zum Flughafen.',
      ],
      answerMode: 'normalized',
      placeholder: 'Wir packen die Koffer, danach fahren wir zum Flughafen.',
      maxLength: 70,
      explanation:
        'danach marks what strictly follows in time; the verb fahren follows danach directly, before wir.',
    },
    {
      id: 'ch45-ex-51',
      chapterNumber: 45,
      order: 51,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['dann', 'error-correction', 'word-order'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Wir essen zuerst. Dann wir gehen spazieren.',
      acceptedAnswers: ['Wir essen zuerst. Dann gehen wir spazieren.'],
      answerMode: 'normalized',
      placeholder: 'Wir essen zuerst. Dann ...',
      maxLength: 60,
      explanation:
        'dann occupies position 1, so the verb gehen must come immediately after it, before the subject wir.',
    },
    {
      id: 'ch45-ex-52',
      chapterNumber: 45,
      order: 52,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['danach', 'error-correction', 'word-order'],
      instruction:
        'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Wir kochen zusammen. Danach wir räumen die Küche auf.',
      acceptedAnswers: ['Wir kochen zusammen. Danach räumen wir die Küche auf.'],
      answerMode: 'normalized',
      placeholder: 'Wir kochen zusammen. Danach ...',
      maxLength: 60,
      explanation:
        'danach occupies position 1, so the verb räumen must come immediately after it, before the subject wir.',
    },
    {
      id: 'ch45-ex-53',
      chapterNumber: 45,
      order: 53,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sonst', 'sentence-formation', 'warning'],
      instruction:
        'Write a complete sentence using sonst for the cues in brackets. Capitalisation and punctuation are checked.',
      prompt: 'du – schneller laufen müssen – den Zug verpassen',
      acceptedAnswers: ['Du musst schneller laufen, sonst verpasst du den Zug.'],
      answerMode: 'normalized',
      placeholder: 'Du musst schneller laufen, sonst ...',
      maxLength: 70,
      explanation:
        'sonst introduces the negative consequence of not hurrying, with verpasst in position 2 right after sonst.',
    },
    {
      id: 'ch45-ex-54',
      chapterNumber: 45,
      order: 54,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['danach', 'sentence-formation', 'timeline-ordering'],
      instruction:
        'Write a complete sentence using danach for the cues in brackets. Capitalisation and punctuation are checked.',
      prompt: 'wir – zuerst einkaufen – danach kochen',
      acceptedAnswers: [
        'Wir kaufen zuerst ein, danach kochen wir.',
        'Wir kaufen zuerst ein. Danach kochen wir.',
      ],
      answerMode: 'normalized',
      placeholder: 'Wir kaufen zuerst ein, danach kochen wir.',
      maxLength: 70,
      explanation:
        'danach marks the step that strictly follows shopping; kochen comes in position 2 right after danach.',
    },
    {
      id: 'ch45-ex-55',
      chapterNumber: 45,
      order: 55,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['deshalb', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Ich bin krank. + deshalb + gehe + ich + nicht zur Arbeit.',
      segments: [
        { id: 's1', text: 'Ich bin krank.' },
        { id: 's2', text: 'Deshalb' },
        { id: 's3', text: 'gehe' },
        { id: 's4', text: 'ich' },
        { id: 's5', text: 'nicht zur Arbeit.' },
      ],
      explanation:
        'Deshalb fills position 1, so the verb gehe follows immediately, and the subject ich comes after the verb.',
    },
    {
      id: 'ch45-ex-56',
      chapterNumber: 45,
      order: 56,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['deshalb', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Es ist spät. + deshalb + rufe + ich + dich morgen an.',
      segments: [
        { id: 's1', text: 'Es ist spät.' },
        { id: 's2', text: 'Deshalb' },
        { id: 's3', text: 'rufe' },
        { id: 's4', text: 'ich' },
        { id: 's5', text: 'dich morgen an.' },
      ],
      explanation:
        'Deshalb fills position 1, so the verb rufe follows immediately, and the subject ich comes after the verb.',
    },
    {
      id: 'ch45-ex-57',
      chapterNumber: 45,
      order: 57,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['sonst', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Mach das Fenster zu, + sonst + wird + es + kalt.',
      segments: [
        { id: 's1', text: 'Mach das Fenster zu,' },
        { id: 's2', text: 'sonst' },
        { id: 's3', text: 'wird' },
        { id: 's4', text: 'es' },
        { id: 's5', text: 'kalt.' },
      ],
      explanation:
        'sonst fills position 1, so the verb wird follows immediately, and the subject es comes after the verb.',
    },
    {
      id: 'ch45-ex-58',
      chapterNumber: 45,
      order: 58,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['sonst', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Beeil dich, + sonst + kommen + wir + zu spät.',
      segments: [
        { id: 's1', text: 'Beeil dich,' },
        { id: 's2', text: 'sonst' },
        { id: 's3', text: 'kommen' },
        { id: 's4', text: 'wir' },
        { id: 's5', text: 'zu spät.' },
      ],
      explanation:
        'sonst fills position 1, so the verb kommen follows immediately, and the subject wir comes after the verb.',
    },
    {
      id: 'ch45-ex-59',
      chapterNumber: 45,
      order: 59,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['dann', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Wir frühstücken. + dann + fahren + wir + zur Arbeit.',
      segments: [
        { id: 's1', text: 'Wir frühstücken.' },
        { id: 's2', text: 'Dann' },
        { id: 's3', text: 'fahren' },
        { id: 's4', text: 'wir' },
        { id: 's5', text: 'zur Arbeit.' },
      ],
      explanation:
        'Dann fills position 1, so the verb fahren follows immediately, and the subject wir comes after the verb.',
    },
    {
      id: 'ch45-ex-60',
      chapterNumber: 45,
      order: 60,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['dann', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Ruf mich an, + dann + komme + ich + vorbei.',
      segments: [
        { id: 's1', text: 'Ruf mich an,' },
        { id: 's2', text: 'dann' },
        { id: 's3', text: 'komme' },
        { id: 's4', text: 'ich' },
        { id: 's5', text: 'vorbei.' },
      ],
      explanation:
        'dann fills position 1, so the verb komme follows immediately, and the subject ich comes after the verb.',
    },
    {
      id: 'ch45-ex-61',
      chapterNumber: 45,
      order: 61,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['danach', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Wir packen die Taschen. + danach + fahren + wir + zum Bahnhof.',
      segments: [
        { id: 's1', text: 'Wir packen die Taschen.' },
        { id: 's2', text: 'Danach' },
        { id: 's3', text: 'fahren' },
        { id: 's4', text: 'wir' },
        { id: 's5', text: 'zum Bahnhof.' },
      ],
      explanation:
        'Danach fills position 1, so the verb fahren follows immediately, and the subject wir comes after the verb.',
    },
    {
      id: 'ch45-ex-62',
      chapterNumber: 45,
      order: 62,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['danach', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Er wäscht sich. + danach + zieht + er + sich an.',
      segments: [
        { id: 's1', text: 'Er wäscht sich.' },
        { id: 's2', text: 'Danach' },
        { id: 's3', text: 'zieht' },
        { id: 's4', text: 'er' },
        { id: 's5', text: 'sich an.' },
      ],
      explanation:
        'Danach fills position 1, so the verb zieht follows immediately, and the subject er comes after the verb.',
    },
    {
      id: 'ch45-ex-63',
      chapterNumber: 45,
      order: 63,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['deshalb', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Ich habe Hunger. + deshalb + koche + ich + jetzt etwas.',
      segments: [
        { id: 's1', text: 'Ich habe Hunger.' },
        { id: 's2', text: 'Deshalb' },
        { id: 's3', text: 'koche' },
        { id: 's4', text: 'ich' },
        { id: 's5', text: 'jetzt etwas.' },
      ],
      explanation:
        'Deshalb fills position 1, so the verb koche follows immediately, and the subject ich comes after the verb.',
    },
    {
      id: 'ch45-ex-64',
      chapterNumber: 45,
      order: 64,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['sonst', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Lern die Vokabeln, + sonst + verstehst + du + den Text nicht.',
      segments: [
        { id: 's1', text: 'Lern die Vokabeln,' },
        { id: 's2', text: 'sonst' },
        { id: 's3', text: 'verstehst' },
        { id: 's4', text: 'du' },
        { id: 's5', text: 'den Text nicht.' },
      ],
      explanation:
        'sonst fills position 1, so the verb verstehst follows immediately, and the subject du comes after the verb.',
    },
    {
      id: 'ch45-ex-65',
      chapterNumber: 45,
      order: 65,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['dann', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Wir treffen die Freunde. + dann + gehen + wir + ins Kino.',
      segments: [
        { id: 's1', text: 'Wir treffen die Freunde.' },
        { id: 's2', text: 'Dann' },
        { id: 's3', text: 'gehen' },
        { id: 's4', text: 'wir' },
        { id: 's5', text: 'ins Kino.' },
      ],
      explanation:
        'Dann fills position 1, so the verb gehen follows immediately, and the subject wir comes after the verb.',
    },
    {
      id: 'ch45-ex-66',
      chapterNumber: 45,
      order: 66,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['deshalb', 'word-order', 'inversion'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Sie lernt jeden Tag. + deshalb + spricht + sie + schon gut Deutsch.',
      segments: [
        { id: 's1', text: 'Sie lernt jeden Tag.' },
        { id: 's2', text: 'Deshalb' },
        { id: 's3', text: 'spricht' },
        { id: 's4', text: 'sie' },
        { id: 's5', text: 'schon gut Deutsch.' },
      ],
      explanation:
        'Deshalb fills position 1, so the verb spricht follows immediately, and the subject sie comes after the verb.',
    },
    {
      id: 'ch45-ex-67',
      chapterNumber: 45,
      order: 67,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['deshalb', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner erklärt das Wetter. Etwas stimmt nicht.',
      tokens: ['Deshalb', 'wir', 'bleiben', 'zu', 'Hause.'],
      errorTokenIndex: 1,
      correction: 'Deshalb bleiben wir zu Hause.',
      explanation:
        'deshalb occupies position 1, so the verb bleiben must come directly after it, before the subject wir.',
    },
    {
      id: 'ch45-ex-68',
      chapterNumber: 45,
      order: 68,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['sonst', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner warnt einen Freund. Etwas stimmt nicht.',
      tokens: ['Sonst', 'du', 'verpasst', 'den', 'Bus.'],
      errorTokenIndex: 1,
      correction: 'Sonst verpasst du den Bus.',
      explanation:
        'sonst occupies position 1, so the verb verpasst must come directly after it, before the subject du.',
    },
    {
      id: 'ch45-ex-69',
      chapterNumber: 45,
      order: 69,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['dann', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner beschreibt einen Abend. Etwas stimmt nicht.',
      tokens: ['Dann', 'wir', 'gehen', 'ins', 'Kino.'],
      errorTokenIndex: 1,
      correction: 'Dann gehen wir ins Kino.',
      explanation:
        'dann occupies position 1, so the verb gehen must come directly after it, before the subject wir.',
    },
    {
      id: 'ch45-ex-70',
      chapterNumber: 45,
      order: 70,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['danach', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner beschreibt das Kochen. Etwas stimmt nicht.',
      tokens: ['Danach', 'wir', 'räumen', 'die', 'Küche', 'auf.'],
      errorTokenIndex: 1,
      correction: 'Danach räumen wir die Küche auf.',
      explanation:
        'danach occupies position 1, so the verb räumen must come directly after it, before the subject wir.',
    },
    {
      id: 'ch45-ex-71',
      chapterNumber: 45,
      order: 71,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['deshalb', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner erklärt, warum er müde ist. Etwas stimmt nicht.',
      tokens: ['Deshalb', 'ich', 'bin', 'sehr', 'müde.'],
      errorTokenIndex: 1,
      correction: 'Deshalb bin ich sehr müde.',
      explanation:
        'deshalb occupies position 1, so the verb bin must come directly after it, before the subject ich.',
    },
    {
      id: 'ch45-ex-72',
      chapterNumber: 45,
      order: 72,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['sonst', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner warnt eine Gruppe. Etwas stimmt nicht.',
      tokens: ['Sonst', 'ihr', 'kommt', 'zu', 'spät.'],
      errorTokenIndex: 1,
      correction: 'Sonst kommt ihr zu spät.',
      explanation:
        'sonst occupies position 1, so the verb kommt must come directly after it, before the subject ihr.',
    },
    {
      id: 'ch45-ex-73',
      chapterNumber: 45,
      order: 73,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['dann', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner beschreibt die Pläne einer Freundin. Etwas stimmt nicht.',
      tokens: ['Dann', 'sie', 'trifft', 'ihre', 'Freunde.'],
      errorTokenIndex: 1,
      correction: 'Dann trifft sie ihre Freunde.',
      explanation:
        'dann occupies position 1, so the verb trifft must come directly after it, before the subject sie.',
    },
    {
      id: 'ch45-ex-74',
      chapterNumber: 45,
      order: 74,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['danach', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner beschreibt einen Morgen. Etwas stimmt nicht.',
      tokens: ['Danach', 'er', 'zieht', 'sich', 'an.'],
      errorTokenIndex: 1,
      correction: 'Danach zieht er sich an.',
      explanation:
        'danach occupies position 1, so the verb zieht must come directly after it, before the subject er.',
    },
    {
      id: 'ch45-ex-75',
      chapterNumber: 45,
      order: 75,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['deshalb', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner beschreibt Kinder im Kinderzimmer. Etwas stimmt nicht.',
      tokens: ['Deshalb', 'die', 'Kinder', 'schlafen', 'schon.'],
      errorTokenIndex: 1,
      correction: 'Deshalb schlafen die Kinder schon.',
      explanation:
        'deshalb occupies position 1, so the verb schlafen must come directly after it, before the subject die Kinder.',
    },
    {
      id: 'ch45-ex-76',
      chapterNumber: 45,
      order: 76,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['sonst', 'inversion', 'word-order', 'error-correction'],
      instruction:
        'Find the token that breaks the connector-verb-subject word order, and correct it.',
      prompt: 'Ein Lerner warnt vor kaltem Essen. Etwas stimmt nicht.',
      tokens: ['Sonst', 'das', 'Essen', 'wird', 'kalt.'],
      errorTokenIndex: 1,
      correction: 'Sonst wird das Essen kalt.',
      explanation:
        'sonst occupies position 1, so the verb wird must come directly after it, before the subject das Essen.',
    },
    {
      id: 'ch45-ex-77',
      chapterNumber: 45,
      order: 77,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['deshalb', 'word-order', 'verb-position'],
      instruction: 'Drag the correctly conjugated verb into the gap.',
      prompt: 'Es ist kalt. Deshalb ___ wir einen Mantel.',
      templateParts: ['Es ist kalt. Deshalb ', ' wir einen Mantel.'],
      slots: [{ id: 'slot1', correctWord: 'tragen' }],
      wordBank: ['tragen', 'trägt', 'trage', 'trägst'],
      explanation:
        'wir takes the ending -en: tragen. The verb comes right after deshalb, before the subject wir.',
    },
    {
      id: 'ch45-ex-78',
      chapterNumber: 45,
      order: 78,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['danach', 'word-order', 'verb-position'],
      instruction: 'Drag the correctly conjugated verb into the gap.',
      prompt: 'Wir kochen. Danach ___ wir die Küche auf.',
      templateParts: ['Wir kochen. Danach ', ' wir die Küche auf.'],
      slots: [{ id: 'slot1', correctWord: 'räumen' }],
      wordBank: ['räumen', 'räumt', 'räume', 'räumst'],
      explanation:
        'wir takes the ending -en: räumen. The verb comes right after danach, before the subject wir.',
    },
    {
      id: 'ch45-ex-79',
      chapterNumber: 45,
      order: 79,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['sonst', 'word-order', 'verb-position'],
      instruction: 'Drag the correctly conjugated verb into the gap.',
      prompt: 'Lern mehr, sonst ___ du die Prüfung nicht.',
      templateParts: ['Lern mehr, sonst ', ' du die Prüfung nicht.'],
      slots: [{ id: 'slot1', correctWord: 'bestehst' }],
      wordBank: ['bestehst', 'besteht', 'bestehe', 'bestehen'],
      explanation:
        'du takes the ending -st: bestehst. The verb comes right after sonst, before the subject du.',
    },
    {
      id: 'ch45-ex-80',
      chapterNumber: 45,
      order: 80,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['connector-meaning'],
      instruction: 'Match each connector to its meaning.',
      prompt: 'Ordne jedem Konnektor die passende Bedeutung zu.',
      pairs: [
        { id: 'p1', left: 'deshalb', right: "therefore / that's why" },
        { id: 'p2', left: 'sonst', right: 'otherwise' },
        { id: 'p3', left: 'dann', right: 'then / in that case' },
        { id: 'p4', left: 'danach', right: 'after that (strictly time)' },
      ],
      explanation:
        'deshalb links cause and result; sonst warns of a consequence; dann can be sequential or conditional; danach is strictly temporal.',
    },
    {
      id: 'ch45-ex-81',
      chapterNumber: 45,
      order: 81,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['word-order', 'inversion'],
      instruction: 'Match each opening clause to its correctly ordered continuation.',
      prompt: 'Ordne jedem ersten Satzteil die richtige Fortsetzung zu.',
      pairs: [
        { id: 'p1', left: 'Es regnet. Deshalb', right: 'bleiben wir zu Hause.' },
        { id: 'p2', left: 'Beeil dich, sonst', right: 'verpassen wir den Bus.' },
        { id: 'p3', left: 'Wir essen. Dann', right: 'gehen wir spazieren.' },
        { id: 'p4', left: 'Wir duschen. Danach', right: 'frühstücken wir.' },
      ],
      explanation:
        'In every case the connector fills position 1, so the finite verb follows immediately, before the subject.',
    },
  ],
};
