import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter052: ChapterDefinition = {
  id: 'chapter-052',
  number: 52,
  slug: 'negation-expressions',
  title: 'Negation Expressions',
  germanTitle: 'Negationsausdrücke',
  level: 'A2',
  section: 'words-and-word-formation',
  objective:
    'Go beyond nicht and kein to master the fuller German negation system — using nichts, niemand, nie, noch nicht, and nicht mehr to negate exactly the right word, distinguish "not yet" from "no longer", and control the scope of nicht within a sentence.',
  prerequisites: [16, 12, 10],
  estimatedMinutes: 28,
  tags: [
    'negation',
    'nichts',
    'niemand',
    'nie',
    'noch-nicht',
    'nicht-mehr',
    'kein',
    'scope',
    'time-contrast',
  ],
  explanation: {
    introduction: [
      'Chapter 16 introduced the two core negators of German: nicht and kein. But German negation is a whole small system, not just two words. Alongside nicht and kein, German has a set of dedicated negative words, each one the negative counterpart of a specific positive word: nichts (nothing) answers to etwas (something), niemand (nobody) answers to jemand (somebody), and nie (never) answers to immer/oft (always/often). Once you recognize which positive word is being denied, the right negative word usually follows automatically.',
      'German also draws a sharp line between two kinds of "not anymore" in English: noch nicht (not yet) and nicht mehr (no longer). These look similar in English but describe opposite situations in time — one says something has not started, the other says something has ended — and native speakers never confuse them.',
      'Finally, this chapter deepens the idea of scope from Chapter 16: nicht can negate the whole sentence, or it can stand directly before a single word or phrase to narrowly deny just that part, while the rest of the sentence stays true. Learning to place nicht precisely — and to reach for nichts, niemand, or nie instead when the context calls for it — is what makes negation sound natural rather than translated word-for-word from English.',
    ],
    rules: [
      {
        id: 'ch52-rule-01',
        heading: 'From nicht/kein to a full negation system',
        paragraphs: [
          'Besides nicht and kein, German has dedicated negative words that each replace one specific positive word rather than simply adding "not" in front of it: nichts replaces etwas (something/anything), niemand replaces jemand (somebody/anybody), and nie replaces immer or oft (always/often).',
          'Ich sehe etwas. → Ich sehe nichts. Jemand ruft an. → Niemand ruft an. Er ist oft müde. → Er ist nie müde. In each pair, the negative word simply takes the exact grammatical slot — subject, object, adverb — that the positive word occupied.',
          'These words already carry the negation by themselves. Unlike some languages, German never adds nicht in front of nichts, niemand, or nie to reinforce them — that would produce an ungrammatical double negation.',
        ],
      },
      {
        id: 'ch52-rule-02',
        heading: 'nichts — negating things',
        paragraphs: [
          'nichts (nothing/not anything) is an invariable pronoun: it never changes its form for gender or case, whether it is a subject or an object. Ich weiß nichts. Er hat nichts gesagt. Das hat nichts mit dir zu tun.',
          'Because nichts stands for a whole noun phrase, it never appears together with an article or with kein — you use one or the other, never both: not "kein nichts", just nichts on its own.',
          'When an adjective follows nichts, it is capitalized and takes the nominalized neuter ending -es: nichts Neues (nothing new), nichts Besonderes (nothing special).',
        ],
      },
      {
        id: 'ch52-rule-03',
        heading: 'niemand — negating people',
        paragraphs: [
          'niemand (nobody/no one) is the negative counterpart of jemand. Unlike nichts, niemand does decline for case, following almost the same pattern as the question word wer: niemand in the nominative, niemanden in the accusative, niemandem in the dative.',
          'Niemand kommt heute. (nominative, subject) Ich kenne niemanden hier. (accusative, direct object of kennen) Ich habe niemandem geholfen. (dative, because helfen requires a dative object).',
          'In casual spoken German you will sometimes hear niemand left undeclined in the accusative (Ich kenne niemand), but the standard, grammatically correct form is niemanden.',
        ],
      },
      {
        id: 'ch52-rule-04',
        heading: 'nie — negating frequency',
        paragraphs: [
          'nie (never) is the negative counterpart of immer (always) and of oft/manchmal (often/sometimes). It stands in the position a frequency adverb would normally occupy in the sentence.',
          'Er ist nie pünktlich. Ich trinke nie Kaffee am Abend. nie can also combine with noch to intensify the meaning "not even once, up to this point": Ich war noch nie in Japan (I have never been to Japan).',
          'Do not confuse nie with nicht immer (not always): nicht immer means the thing sometimes happens and sometimes does not, while nie rules it out completely, every single time.',
        ],
      },
      {
        id: 'ch52-rule-05',
        heading: 'noch nicht vs. nicht mehr — opposite time directions',
        paragraphs: [
          'noch nicht (not yet) is the negative counterpart of schon (already). It says a situation has not started, but is expected or possible in the future: Bist du schon fertig? – Nein, ich bin noch nicht fertig.',
          'nicht mehr (no longer/not anymore) is the negative counterpart of noch or immer noch (still). It says a situation used to be true and has now ended: Wohnst du noch hier? – Nein, ich wohne nicht mehr hier.',
          'These two phrases point in opposite directions along a timeline: noch nicht looks forward to something that has not begun; nicht mehr looks back at something that has stopped. Swapping them reverses the meaning of the sentence entirely.',
        ],
        notes: [
          'schon → noch nicht (not yet)',
          'noch / immer noch → nicht mehr (no longer)',
        ],
      },
      {
        id: 'ch52-rule-06',
        heading: 'kein revisited, and the scope of nicht',
        paragraphs: [
          'kein still works exactly as in Chapter 16: it negates a following noun that would otherwise take ein/eine or no article at all — Ich habe kein Auto, Wir haben keine Zeit. The difference from nichts and niemand is that kein always attaches to a specific noun, while nichts and niemand stand alone as pronouns, with no noun attached.',
          'nicht can negate the whole sentence, standing near the end of the clause, or it can narrowly negate just one word or phrase by standing directly in front of it: Nicht alle Studenten haben die Prüfung bestanden (Not all students passed — some did). Here nicht attaches only to alle, leaving the rest of the statement true.',
          'This precision is what makes German negation feel different from English: instead of one all-purpose "not", you choose among nicht, kein, nichts, niemand, nie, noch nicht, and nicht mehr depending on exactly what you want to deny and how much of the sentence that denial covers.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch52-table-01',
        title: 'Positive word and its negative counterpart',
        columns: ['Positive', 'Negative', 'Example (positive)', 'Example (negative)'],
        rows: [
          ['etwas', 'nichts', 'Ich sehe etwas.', 'Ich sehe nichts.'],
          ['jemand', 'niemand', 'Jemand ruft an.', 'Niemand ruft an.'],
          ['immer / oft', 'nie', 'Er ist oft müde.', 'Er ist nie müde.'],
          ['schon', 'noch nicht', 'Bist du schon fertig?', 'Ich bin noch nicht fertig.'],
          ['noch / immer noch', 'nicht mehr', 'Wohnst du noch hier?', 'Ich wohne nicht mehr hier.'],
          ['ein/eine / no article', 'kein', 'Ich habe ein Auto.', 'Ich habe kein Auto.'],
        ],
        note: 'Recognizing the positive word behind a sentence tells you exactly which negative word to reach for.',
      },
      {
        id: 'ch52-table-02',
        title: 'niemand declines like wer',
        columns: ['Case', 'wer (question word)', 'niemand', 'Example'],
        rows: [
          ['Nominative', 'wer', 'niemand', 'Niemand ist da.'],
          ['Accusative', 'wen', 'niemanden', 'Ich sehe niemanden.'],
          ['Dative', 'wem', 'niemandem', 'Ich helfe niemandem.'],
        ],
        note: 'nichts, by contrast, never changes its form at all, regardless of case.',
      },
    ],
    examples: [
      {
        german: 'Ich sehe nichts.',
        english: 'I see nothing.',
        highlight: ['nichts'],
        explanation: 'nichts replaces etwas as an invariable negative pronoun — it never changes form for gender or case.',
      },
      {
        german: 'Er hat mir nichts erklärt.',
        english: 'He explained nothing to me.',
        highlight: ['nichts'],
        explanation: 'nichts keeps the same form as an accusative object, regardless of case.',
      },
      {
        german: 'Niemand ist heute zu Hause.',
        english: 'Nobody is home today.',
        highlight: ['Niemand'],
        explanation: 'niemand stands in the nominative here, as the subject of the sentence.',
      },
      {
        german: 'Ich kenne niemanden in dieser Stadt.',
        english: 'I don\'t know anyone in this city.',
        highlight: ['niemanden'],
        explanation: 'kennen takes an accusative object, so niemand takes the accusative ending: niemanden.',
      },
      {
        german: 'Sie hat niemandem von dem Plan erzählt.',
        english: 'She told no one about the plan.',
        highlight: ['niemandem'],
        explanation: 'erzählen takes a dative object for the person told, so niemand becomes niemandem.',
      },
      {
        german: 'Ich war noch nie in Australien.',
        english: 'I have never been to Australia.',
        highlight: ['noch nie'],
        explanation: 'noch nie emphasizes "not even once up to now" — a common combination of noch and nie.',
      },
      {
        german: 'Er raucht nie.',
        english: 'He never smokes.',
        highlight: ['nie'],
        explanation: 'nie negates a habitual action, standing where a frequency adverb like oft or immer would go.',
      },
      {
        german: 'Bist du schon fertig? – Nein, ich bin noch nicht fertig.',
        english: 'Are you done already? – No, I\'m not done yet.',
        highlight: ['noch nicht'],
        explanation: 'noch nicht negates schon: the situation has not started yet, but it is expected to.',
      },
      {
        german: 'Wohnt Frau Klein noch hier? – Nein, sie wohnt nicht mehr hier.',
        english: 'Does Ms. Klein still live here? – No, she doesn\'t live here anymore.',
        highlight: ['nicht mehr'],
        explanation: 'nicht mehr negates noch: the situation used to be true and has now ended.',
      },
      {
        german: 'Ich habe kein Geld für ein neues Handy.',
        english: 'I don\'t have money for a new phone.',
        highlight: ['kein Geld'],
        explanation: 'Geld has no article in the affirmative and is neuter, so kein keeps its unchanged base form.',
      },
      {
        german: 'Wir haben nichts Neues erfahren.',
        english: 'We didn\'t learn anything new.',
        highlight: ['nichts Neues'],
        explanation: 'After nichts, an adjective is capitalized and nominalized with the ending -es: nichts Neues.',
      },
      {
        german: 'Nicht alle Studenten haben die Prüfung bestanden.',
        english: 'Not all students passed the exam.',
        highlight: ['Nicht alle'],
        explanation: 'nicht stands directly before alle to narrowly negate just the quantifier, not the whole sentence — some students did pass.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Er ist nicht mehr da. (gemeint: er ist noch nicht angekommen)',
        correct: 'Er ist noch nicht da.',
        explanation: 'nicht mehr means a situation has ended (he was here and left); noch nicht means it has not started yet (he hasn\'t arrived). Mixing them reverses the timeline.',
      },
      {
        incorrect: 'Ich sehe kein.',
        correct: 'Ich sehe nichts.',
        explanation: 'kein must always accompany a noun and agree with its gender and case; when there is no noun at all — just "nothing" — use the invariable pronoun nichts.',
      },
      {
        incorrect: 'Ich habe niemand geholfen.',
        correct: 'Ich habe niemandem geholfen.',
        explanation: 'helfen takes a dative object, so niemand must take the dative ending -em: niemandem.',
      },
      {
        incorrect: 'Ich habe nicht kein Geld.',
        correct: 'Ich habe kein Geld.',
        explanation: 'German does not stack nicht and kein to negate the same noun — kein already means "not any"; adding nicht in front creates an ungrammatical double negation.',
      },
      {
        incorrect: 'Ich bin nicht immer traurig. (gemeint: ich bin nie traurig)',
        correct: 'Ich bin nie traurig.',
        explanation: 'nicht immer means "not always" (sometimes yes); to say "never," use the dedicated word nie instead.',
      },
    ],
    remember: [
      'nichts, niemand, and nie are dedicated negative words that replace etwas, jemand, and immer/oft — they already carry the negation, so no extra nicht is added.',
      'niemand declines like the question word wer: niemand (nominative), niemanden (accusative), niemandem (dative). nichts never changes form.',
      'noch nicht ("not yet") negates schon and points to a situation that has not started; nicht mehr ("no longer") negates noch and points to one that has ended — opposite time directions.',
      'kein negates a following noun (with an indefinite or zero article); nichts and niemand stand alone as pronouns, with no noun attached.',
      'German never stacks two negation words to negate the same thing — nicht kein, nicht nichts, and nicht niemand are all ungrammatical.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 77,
    requiredCorrectTextInputs: 21,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch52-ex-01',
      chapterNumber: 52,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['nichts', 'pronoun'],
      instruction: 'Choose the negative word that fits.',
      prompt: 'Ich weiß ___.',
      options: [
        { id: 'a', text: 'nichts' },
        { id: 'b', text: 'nicht' },
        { id: 'c', text: 'kein' },
        { id: 'd', text: 'niemand' },
      ],
      correctOptionId: 'a',
      explanation: 'nichts replaces the pronoun etwas here — there is no noun to attach kein to, and nicht alone cannot stand for "nothing".',
    },
    {
      id: 'ch52-ex-02',
      chapterNumber: 52,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['niemand', 'pronoun'],
      instruction: 'Choose the negative word that fits.',
      prompt: '___ ist heute hier.',
      options: [
        { id: 'a', text: 'Niemand' },
        { id: 'b', text: 'Nichts' },
        { id: 'c', text: 'Nie' },
        { id: 'd', text: 'Kein' },
      ],
      correctOptionId: 'a',
      explanation: 'The blank refers to a person ("nobody"), so niemand is needed, not nichts (things) or nie (frequency).',
    },
    {
      id: 'ch52-ex-03',
      chapterNumber: 52,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['nie', 'frequency'],
      instruction: 'Choose the negative word that fits.',
      prompt: 'Er raucht ___.',
      options: [
        { id: 'a', text: 'nie' },
        { id: 'b', text: 'nicht' },
        { id: 'c', text: 'kein' },
        { id: 'd', text: 'niemand' },
      ],
      correctOptionId: 'a',
      explanation: 'nie negates the frequency of the habitual action raucht — "he never smokes".',
    },
    {
      id: 'ch52-ex-04',
      chapterNumber: 52,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['noch-nicht', 'time-contrast'],
      instruction: 'Choose the phrase that fits: "not yet" or "no longer"?',
      prompt: 'Bist du fertig? – Nein, ich bin ___ fertig.',
      options: [
        { id: 'a', text: 'noch nicht' },
        { id: 'b', text: 'nicht mehr' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'The situation has not started yet — the speaker expects to be finished later — so noch nicht ("not yet") is correct.',
    },
    {
      id: 'ch52-ex-05',
      chapterNumber: 52,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['nicht-mehr', 'time-contrast'],
      instruction: 'Choose the phrase that fits: "not yet" or "no longer"?',
      prompt: 'Wohnst du noch hier? – Nein, ich wohne ___ hier.',
      options: [
        { id: 'a', text: 'nicht mehr' },
        { id: 'b', text: 'noch nicht' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'kein' },
      ],
      correctOptionId: 'a',
      explanation: 'The question uses noch ("still"), so the negative answer that the situation has ended is nicht mehr ("no longer").',
    },
    {
      id: 'ch52-ex-06',
      chapterNumber: 52,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['kein', 'noun-negation'],
      instruction: 'Choose the correct negative word for the noun Zeit.',
      prompt: 'Ich habe ___ Zeit.',
      options: [
        { id: 'a', text: 'keine' },
        { id: 'b', text: 'nichts' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'niemand' },
      ],
      correctOptionId: 'a',
      explanation: 'Zeit is a noun (feminine, no article in the affirmative), so it needs kein, declined as keine — not the pronoun nichts.',
    },
    {
      id: 'ch52-ex-07',
      chapterNumber: 52,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['niemand', 'accusative', 'declension'],
      instruction: 'Choose the correct form of niemand.',
      prompt: 'Ich kenne ___ in dieser Stadt.',
      options: [
        { id: 'a', text: 'niemanden' },
        { id: 'b', text: 'niemand' },
        { id: 'c', text: 'niemandem' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'kennen takes an accusative object, so niemand takes the accusative ending: niemanden.',
    },
    {
      id: 'ch52-ex-08',
      chapterNumber: 52,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['niemand', 'dative', 'declension'],
      instruction: 'Choose the correct form of niemand.',
      prompt: 'Ich habe ___ geholfen.',
      options: [
        { id: 'a', text: 'niemandem' },
        { id: 'b', text: 'niemanden' },
        { id: 'c', text: 'niemand' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'helfen takes a dative object, so niemand takes the dative ending: niemandem.',
    },
    {
      id: 'ch52-ex-09',
      chapterNumber: 52,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nichts', 'nominalized-adjective'],
      instruction: 'Choose the correct negative word.',
      prompt: 'Wir haben ___ Neues erfahren.',
      options: [
        { id: 'a', text: 'nichts' },
        { id: 'b', text: 'nicht' },
        { id: 'c', text: 'kein' },
        { id: 'd', text: 'niemand' },
      ],
      correctOptionId: 'a',
      explanation: 'nichts combines with the nominalized adjective Neues ("nothing new"); kein cannot combine with an adjective like this.',
    },
    {
      id: 'ch52-ex-10',
      chapterNumber: 52,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nicht', 'scope', 'narrow-negation'],
      instruction: 'Choose the word that correctly negates only the quantifier alle.',
      prompt: '___ alle Studenten haben die Prüfung bestanden.',
      options: [
        { id: 'a', text: 'Nicht' },
        { id: 'b', text: 'Kein' },
        { id: 'c', text: 'Nichts' },
        { id: 'd', text: 'Nie' },
      ],
      correctOptionId: 'a',
      explanation: 'nicht stands directly before alle to negate only that quantifier — "not all", meaning some did pass.',
    },
    {
      id: 'ch52-ex-11',
      chapterNumber: 52,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nicht-mehr', 'dialogue', 'time-contrast'],
      instruction: 'Read the exchange, then choose the phrase that best completes the final line.',
      prompt: 'Complete: "Nein, ich esse ___ Fleisch, ich bin jetzt Vegetarier."',
      dialogue: [
        { speaker: 'Mia', german: 'Isst du noch Fleisch?', english: 'Do you still eat meat?' },
        {
          speaker: 'Jonas',
          german: 'Nein, ich esse ___ Fleisch, ich bin jetzt Vegetarier.',
          english: 'No, I no longer eat meat, I\'m a vegetarian now.',
        },
      ],
      options: [
        { id: 'a', text: 'nicht mehr' },
        { id: 'b', text: 'noch nicht' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'kein' },
      ],
      correctOptionId: 'a',
      explanation: 'Jonas used to eat meat and has stopped — a situation that has ended is negated with nicht mehr.',
    },
    {
      id: 'ch52-ex-12',
      chapterNumber: 52,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['noch-nicht', 'dialogue', 'time-contrast'],
      instruction: 'Read the exchange, then choose the phrase that best completes the final line.',
      prompt: 'Complete: "Nein, wir haben sie ___ gemacht, wir fangen gleich an."',
      dialogue: [
        { speaker: 'Lehrerin', german: 'Habt ihr die Hausaufgaben schon gemacht?', english: 'Have you done the homework already?' },
        {
          speaker: 'Schüler',
          german: 'Nein, wir haben sie ___ gemacht, wir fangen gleich an.',
          english: 'No, we haven\'t done it yet, we\'re starting soon.',
        },
      ],
      options: [
        { id: 'a', text: 'noch nicht' },
        { id: 'b', text: 'nicht mehr' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'The homework has not been started yet but will be soon, so noch nicht ("not yet") is correct.',
    },
    {
      id: 'ch52-ex-13',
      chapterNumber: 52,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nie', 'dialogue', 'frequency'],
      instruction: 'Read the exchange, then choose the phrase that best completes the final line.',
      prompt: 'Complete: "Nein, ich bin ___ nervös, das stresst mich nicht."',
      dialogue: [
        { speaker: 'Paul', german: 'Bist du manchmal nervös vor Prüfungen?', english: 'Are you sometimes nervous before exams?' },
        {
          speaker: 'Elena',
          german: 'Nein, ich bin ___ nervös, das stresst mich nicht.',
          english: 'No, I\'m never nervous, it doesn\'t stress me.',
        },
      ],
      options: [
        { id: 'a', text: 'nie' },
        { id: 'b', text: 'nicht immer' },
        { id: 'c', text: 'noch nicht' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'Elena rules out nervousness completely, every time — that is nie ("never"), not the weaker nicht immer ("not always").',
    },
    {
      id: 'ch52-ex-14',
      chapterNumber: 52,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['double-negation', 'error-spotting'],
      instruction: 'Choose the sentence that is grammatically correct German.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich habe kein Geld.' },
        { id: 'b', text: 'Ich habe nicht kein Geld.' },
        { id: 'c', text: 'Ich habe nicht Geld.' },
        { id: 'd', text: 'Ich habe niemand Geld.' },
      ],
      correctOptionId: 'a',
      explanation: 'German never stacks nicht and kein to negate the same noun; kein alone already means "not any". Geld also cannot be negated with bare nicht or with niemand.',
    },
    {
      id: 'ch52-ex-15',
      chapterNumber: 52,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['niemand', 'contrast', 'production'],
      instruction: 'Choose the word that best completes the contrast.',
      prompt: 'Er hat mich gestern angerufen, aber heute ruft ___ an.',
      options: [
        { id: 'a', text: 'niemand' },
        { id: 'b', text: 'nichts' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'kein' },
      ],
      correctOptionId: 'a',
      explanation: 'The blank is the subject of the sentence and refers to a person who is not calling today, so niemand (nominative) is needed.',
    },
    {
      id: 'ch52-ex-16',
      chapterNumber: 52,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['nichts', 'pronoun'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Ich sehe ___.',
      acceptedAnswers: ['nichts'],
      answerMode: 'caseInsensitive',
      placeholder: 'nichts',
      maxLength: 12,
      explanation: 'nichts is the invariable pronoun for "nothing", replacing etwas.',
    },
    {
      id: 'ch52-ex-17',
      chapterNumber: 52,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['niemand', 'nominative'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: '___ ruft heute an.',
      acceptedAnswers: ['Niemand', 'niemand'],
      answerMode: 'caseInsensitive',
      placeholder: 'Niemand',
      maxLength: 12,
      explanation: 'niemand is the subject here (nominative), meaning "nobody is calling today".',
    },
    {
      id: 'ch52-ex-18',
      chapterNumber: 52,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['niemand', 'accusative'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Ich sehe ___ im Park.',
      acceptedAnswers: ['niemanden'],
      answerMode: 'caseInsensitive',
      placeholder: 'niemanden',
      maxLength: 12,
      explanation: 'sehen takes an accusative object, so niemand becomes niemanden.',
    },
    {
      id: 'ch52-ex-19',
      chapterNumber: 52,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['niemand', 'dative'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Sie erzählt ___ von dem Geheimnis.',
      acceptedAnswers: ['niemandem'],
      answerMode: 'caseInsensitive',
      placeholder: 'niemandem',
      maxLength: 12,
      explanation: 'erzählen takes a dative object for the person told, so niemand becomes niemandem.',
    },
    {
      id: 'ch52-ex-20',
      chapterNumber: 52,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['nie', 'frequency'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Er lügt ___.',
      acceptedAnswers: ['nie'],
      answerMode: 'caseInsensitive',
      placeholder: 'nie',
      maxLength: 10,
      explanation: 'nie negates the habitual action lügt — "he never lies".',
    },
    {
      id: 'ch52-ex-21',
      chapterNumber: 52,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['noch-nicht', 'time-contrast'],
      instruction: 'Fill in the missing phrase. Capitalisation is not checked.',
      prompt: 'Wir sind ___ zu Hause. (not yet — we\'re still on the way)',
      acceptedAnswers: ['noch nicht'],
      answerMode: 'caseInsensitive',
      placeholder: 'noch nicht',
      maxLength: 15,
      explanation: 'The situation has not started yet, so noch nicht ("not yet") is correct.',
    },
    {
      id: 'ch52-ex-22',
      chapterNumber: 52,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['nicht-mehr', 'time-contrast'],
      instruction: 'Fill in the missing phrase. Capitalisation is not checked.',
      prompt: 'Er arbeitet ___ hier. (no longer — he quit last month)',
      acceptedAnswers: ['nicht mehr'],
      answerMode: 'caseInsensitive',
      placeholder: 'nicht mehr',
      maxLength: 15,
      explanation: 'The situation used to be true and has ended, so nicht mehr ("no longer") is correct.',
    },
    {
      id: 'ch52-ex-23',
      chapterNumber: 52,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'neuter'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Sie hat ___ Auto.',
      acceptedAnswers: ['kein'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein',
      maxLength: 10,
      explanation: 'Auto is neuter and stands in the accusative, so kein keeps its unchanged base form.',
    },
    {
      id: 'ch52-ex-24',
      chapterNumber: 52,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['nichts', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using nichts. Capitalisation and punctuation are checked.',
      prompt: 'Ich habe etwas gesehen.',
      acceptedAnswers: ['Ich habe nichts gesehen.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe ...',
      maxLength: 40,
      explanation: 'etwas is replaced by the negative pronoun nichts, taking the exact same object slot: Ich habe nichts gesehen.',
    },
    {
      id: 'ch52-ex-25',
      chapterNumber: 52,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['niemand', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using niemand. Capitalisation and punctuation are checked.',
      prompt: 'Jemand hat angerufen.',
      acceptedAnswers: ['Niemand hat angerufen.'],
      answerMode: 'normalized',
      placeholder: 'Niemand hat ...',
      maxLength: 40,
      explanation: 'jemand is replaced by niemand in the same nominative subject position: Niemand hat angerufen.',
    },
    {
      id: 'ch52-ex-26',
      chapterNumber: 52,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['nie', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using nie. Capitalisation and punctuation are checked.',
      prompt: 'Er ist oft krank.',
      acceptedAnswers: ['Er ist nie krank.'],
      answerMode: 'normalized',
      placeholder: 'Er ist ...',
      maxLength: 40,
      explanation: 'oft is replaced by nie in the same adverb position: Er ist nie krank.',
    },
    {
      id: 'ch52-ex-27',
      chapterNumber: 52,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['noch-nicht', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using noch nicht. Capitalisation and punctuation are checked.',
      prompt: 'Ich bin schon fertig.',
      acceptedAnswers: ['Ich bin noch nicht fertig.'],
      answerMode: 'normalized',
      placeholder: 'Ich bin ...',
      maxLength: 40,
      explanation: 'schon is negated by its counterpart noch nicht: Ich bin noch nicht fertig.',
    },
    {
      id: 'ch52-ex-28',
      chapterNumber: 52,
      order: 28,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['nicht-mehr', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using nicht mehr. Capitalisation and punctuation are checked.',
      prompt: 'Er wohnt noch hier.',
      acceptedAnswers: ['Er wohnt nicht mehr hier.'],
      answerMode: 'normalized',
      placeholder: 'Er wohnt ...',
      maxLength: 40,
      explanation: 'noch is negated by its counterpart nicht mehr: Er wohnt nicht mehr hier.',
    },
    {
      id: 'ch52-ex-29',
      chapterNumber: 52,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['niemand', 'dative', 'dialogue'],
      instruction: 'Read the exchange and fill in the missing word. Capitalisation is not checked.',
      prompt: 'Complete: "Ich habe es ___ erzählt, es bleibt unser Geheimnis."',
      dialogue: [
        { speaker: 'Chef', german: 'Wer weiß von dem Fehler?', english: 'Who knows about the mistake?' },
        {
          speaker: 'Mitarbeiter',
          german: 'Ich habe es ___ erzählt, es bleibt unser Geheimnis.',
          english: 'I haven\'t told anyone, it stays our secret.',
        },
      ],
      acceptedAnswers: ['niemandem'],
      answerMode: 'caseInsensitive',
      placeholder: 'niemandem',
      maxLength: 12,
      explanation: 'erzählen takes a dative object, so "nobody" here is niemandem — the employee told no one about the mistake.',
    },
    {
      id: 'ch52-ex-30',
      chapterNumber: 52,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'double-negation'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich habe nicht kein Geld.',
      acceptedAnswers: ['Ich habe kein Geld.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe kein Geld.',
      maxLength: 30,
      explanation: 'kein already means "not any"; nicht in front of it creates an ungrammatical double negation, so it must be removed.',
    },
    {
      id: 'ch52-ex-31',
      chapterNumber: 52,
      order: 31,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['negation-pairs', 'vocabulary'],
      instruction: 'Match each positive word to its negative counterpart.',
      prompt: 'Match the positive word to its negative counterpart.',
      pairs: [
        { id: 'ch52-ex31-p1', left: 'etwas', right: 'nichts' },
        { id: 'ch52-ex31-p2', left: 'jemand', right: 'niemand' },
        { id: 'ch52-ex31-p3', left: 'immer', right: 'nie' },
        { id: 'ch52-ex31-p4', left: 'schon', right: 'noch nicht' },
        { id: 'ch52-ex31-p5', left: 'noch', right: 'nicht mehr' },
      ],
      explanation: 'Each positive word has one dedicated negative counterpart: etwas/nichts, jemand/niemand, immer/nie, schon/noch nicht, noch/nicht mehr.',
    },
    {
      id: 'ch52-ex-32',
      chapterNumber: 52,
      order: 32,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['negation-pairs', 'sentence-context'],
      instruction: 'Match each positive sentence to the word that negates it.',
      prompt: 'Match each sentence to the negative word that best completes its negation.',
      pairs: [
        { id: 'ch52-ex32-p1', left: 'Ich sehe etwas.', right: 'nichts' },
        { id: 'ch52-ex32-p2', left: 'Jemand ruft an.', right: 'Niemand' },
        { id: 'ch52-ex32-p3', left: 'Er ist oft müde.', right: 'nie' },
        { id: 'ch52-ex32-p4', left: 'Bist du schon fertig?', right: 'noch nicht' },
        { id: 'ch52-ex32-p5', left: 'Wohnst du noch hier?', right: 'nicht mehr' },
        { id: 'ch52-ex32-p6', left: 'Ich habe ein Auto.', right: 'kein' },
      ],
      explanation: 'Each sentence contains a positive word (etwas, jemand, oft, schon, noch, ein) that is denied by its matching negative counterpart.',
    },
    {
      id: 'ch52-ex-33',
      chapterNumber: 52,
      order: 33,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['negation-vocabulary', 'english-meaning'],
      instruction: 'Match each German negation word or phrase to its English meaning.',
      prompt: 'Match the German negation expression to its English meaning.',
      pairs: [
        { id: 'ch52-ex33-p1', left: 'nichts', right: 'nothing' },
        { id: 'ch52-ex33-p2', left: 'niemand', right: 'nobody' },
        { id: 'ch52-ex33-p3', left: 'nie', right: 'never' },
        { id: 'ch52-ex33-p4', left: 'noch nicht', right: 'not yet' },
        { id: 'ch52-ex33-p5', left: 'nicht mehr', right: 'no longer' },
        { id: 'ch52-ex33-p6', left: 'nirgendwo', right: 'nowhere' },
      ],
      explanation: 'German has a dedicated negation word for each of these meanings, unlike English which often reuses "not" with other words.',
    },
    {
      id: 'ch52-ex-34',
      chapterNumber: 52,
      order: 34,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['kein', 'noun-negation'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: 'Ich habe ___ Geld für ein neues Handy.',
      templateParts: ['Ich habe ', ' Geld für ein neues Handy.'],
      slots: [{ id: 'ch52-ex34-slot1', correctWord: 'kein' }],
      wordBank: ['kein', 'nicht', 'nichts', 'niemand'],
      explanation: 'Geld is a noun with no article in the affirmative, so it is negated with kein, not with nicht or the pronoun nichts.',
    },
    {
      id: 'ch52-ex-35',
      chapterNumber: 52,
      order: 35,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['niemand', 'accusative', 'declension'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: 'Ich kenne ___ in dieser Stadt.',
      templateParts: ['Ich kenne ', ' in dieser Stadt.'],
      slots: [{ id: 'ch52-ex35-slot1', correctWord: 'niemanden' }],
      wordBank: ['niemanden', 'niemand', 'niemandem', 'nichts'],
      explanation: 'kennen takes an accusative object, so niemand must take the accusative ending: niemanden.',
    },
    {
      id: 'ch52-ex-36',
      chapterNumber: 52,
      order: 36,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['nie', 'frequency'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: 'Er ist ___ pünktlich.',
      templateParts: ['Er ist ', ' pünktlich.'],
      slots: [{ id: 'ch52-ex36-slot1', correctWord: 'nie' }],
      wordBank: ['nie', 'nicht', 'kein', 'niemand'],
      explanation: 'nie negates the frequency adverb slot completely — "he is never on time".',
    },
    {
      id: 'ch52-ex-37',
      chapterNumber: 52,
      order: 37,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['noch-nicht', 'time-contrast'],
      instruction: 'Drag the correct phrase into the gap.',
      prompt: 'Bist du schon fertig? – Nein, ich bin ___ fertig.',
      templateParts: ['Bist du schon fertig? – Nein, ich bin ', ' fertig.'],
      slots: [{ id: 'ch52-ex37-slot1', correctWord: 'noch nicht' }],
      wordBank: ['noch nicht', 'nicht mehr', 'nie', 'nichts'],
      explanation: 'The situation has not started yet, so noch nicht ("not yet") is the correct negative counterpart of schon.',
    },
    {
      id: 'ch52-ex-38',
      chapterNumber: 52,
      order: 38,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['nicht-mehr', 'time-contrast'],
      instruction: 'Drag the correct phrase into the gap.',
      prompt: 'Wohnst du noch hier? – Nein, ich wohne ___ hier.',
      templateParts: ['Wohnst du noch hier? – Nein, ich wohne ', ' hier.'],
      slots: [{ id: 'ch52-ex38-slot1', correctWord: 'nicht mehr' }],
      wordBank: ['nicht mehr', 'noch nicht', 'nie', 'kein'],
      explanation: 'The question uses noch ("still"), so the situation has ended and nicht mehr ("no longer") is correct.',
    },
    {
      id: 'ch52-ex-39',
      chapterNumber: 52,
      order: 39,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['nichts', 'nominalized-adjective'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: 'Wir haben ___ Neues erfahren.',
      templateParts: ['Wir haben ', ' Neues erfahren.'],
      slots: [{ id: 'ch52-ex39-slot1', correctWord: 'nichts' }],
      wordBank: ['nichts', 'nicht', 'kein', 'niemand'],
      explanation: 'nichts combines with the nominalized adjective Neues ("nothing new"); kein cannot attach to an adjective like this.',
    },
    {
      id: 'ch52-ex-40',
      chapterNumber: 52,
      order: 40,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['niemand', 'dative', 'declension'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: 'Ich habe ___ geholfen.',
      templateParts: ['Ich habe ', ' geholfen.'],
      slots: [{ id: 'ch52-ex40-slot1', correctWord: 'niemandem' }],
      wordBank: ['niemandem', 'niemanden', 'niemand', 'nichts'],
      explanation: 'helfen takes a dative object, so niemand must take the dative ending: niemandem.',
    },
    {
      id: 'ch52-ex-41',
      chapterNumber: 52,
      order: 41,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['niemand', 'nominative', 'pronoun'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: '___ ist heute zu Hause.',
      templateParts: ['', ' ist heute zu Hause.'],
      slots: [{ id: 'ch52-ex41-slot1', correctWord: 'Niemand' }],
      wordBank: ['Niemand', 'Nichts', 'Nie', 'Kein'],
      explanation: 'The blank refers to a person ("nobody"), so Niemand is needed, not Nichts (things) or Nie (frequency).',
    },
    {
      id: 'ch52-ex-42',
      chapterNumber: 52,
      order: 42,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['nichts', 'pronoun'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: 'Ich sehe ___ am Himmel.',
      templateParts: ['Ich sehe ', ' am Himmel.'],
      slots: [{ id: 'ch52-ex42-slot1', correctWord: 'nichts' }],
      wordBank: ['nichts', 'niemand', 'nie', 'kein'],
      explanation: 'nichts replaces etwas as an invariable negative pronoun for things — there is nothing visible in the sky.',
    },
    {
      id: 'ch52-ex-43',
      chapterNumber: 52,
      order: 43,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['nirgendwo', 'location'],
      instruction: 'Drag the correct negation word into the gap.',
      prompt: 'Ich finde meine Schlüssel ___.',
      templateParts: ['Ich finde meine Schlüssel ', '.'],
      slots: [{ id: 'ch52-ex43-slot1', correctWord: 'nirgendwo' }],
      wordBank: ['nirgendwo', 'nichts', 'niemand', 'nie'],
      explanation: 'nirgendwo negates a place ("nowhere"); the keys are not to be found anywhere, so the location word is needed, not the pronoun nichts.',
    },
    {
      id: 'ch52-ex-44',
      chapterNumber: 52,
      order: 44,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['gar-nicht', 'intensified-negation'],
      instruction: 'Drag the correct phrase into the gap.',
      prompt: 'Das gefällt mir ___.',
      templateParts: ['Das gefällt mir ', '.'],
      slots: [{ id: 'ch52-ex44-slot1', correctWord: 'gar nicht' }],
      wordBank: ['gar nicht', 'nicht mehr', 'noch nicht', 'nichts'],
      explanation: 'gar nicht intensifies nicht to mean "not at all"; gefallen is negated with the adverb nicht, not with the pronoun nichts.',
    },
    {
      id: 'ch52-ex-45',
      chapterNumber: 52,
      order: 45,
      type: 'errorSpotting',
      level: 'recognition',
      grammarFocus: ['nichts', 'kein', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt, was er sieht. Etwas stimmt nicht.',
      tokens: ['Ich', 'sehe', 'heute', 'kein.'],
      errorTokenIndex: 3,
      correction: 'nichts',
      explanation: 'There is no noun to attach kein to — "nothing" as a standalone pronoun requires nichts, not kein.',
    },
    {
      id: 'ch52-ex-46',
      chapterNumber: 52,
      order: 46,
      type: 'errorSpotting',
      level: 'recognition',
      grammarFocus: ['niemand', 'nichts', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt, wer anruft. Etwas stimmt nicht.',
      tokens: ['Nichts', 'ruft', 'heute', 'an.'],
      errorTokenIndex: 0,
      correction: 'Niemand',
      explanation: 'The subject refers to a person who is not calling, so niemand ("nobody") is required, not nichts ("nothing").',
    },
    {
      id: 'ch52-ex-47',
      chapterNumber: 52,
      order: 47,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['nichts', 'niemand', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt, was er hört. Etwas stimmt nicht.',
      tokens: ['Ich', 'höre', 'heute', 'niemand.'],
      errorTokenIndex: 3,
      correction: 'nichts',
      explanation: 'The object refers to a thing being heard, not a person, so nichts is required instead of niemand.',
    },
    {
      id: 'ch52-ex-48',
      chapterNumber: 52,
      order: 48,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['nicht-mehr', 'nie', 'time-contrast', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand erklärt, dass eine Situation beendet ist. Etwas stimmt nicht.',
      tokens: ['Er', 'arbeitet', 'nie', 'hier.'],
      errorTokenIndex: 2,
      correction: 'nicht mehr',
      explanation: 'The situation used to be true and has ended (he worked here before), which requires nicht mehr ("no longer"), not nie ("never").',
    },
    {
      id: 'ch52-ex-49',
      chapterNumber: 52,
      order: 49,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['noch-nicht', 'nie', 'time-contrast', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand erklärt, dass eine Aufgabe noch nicht begonnen hat. Etwas stimmt nicht.',
      tokens: ['Wir', 'haben', 'nie', 'Hausaufgaben', 'gemacht.'],
      errorTokenIndex: 2,
      correction: 'noch nicht',
      explanation: 'The homework simply has not been done yet (but will be), which calls for noch nicht ("not yet"), not nie ("never").',
    },
    {
      id: 'ch52-ex-50',
      chapterNumber: 52,
      order: 50,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['niemand', 'accusative', 'declension', 'error-correction'],
      instruction: 'Find the token with the wrong ending, and correct it.',
      prompt: 'Zwei Freunde sprechen über die neue Stadt. Etwas stimmt nicht.',
      tokens: ['Ich', 'kenne', 'niemand', 'hier.'],
      errorTokenIndex: 2,
      correction: 'niemanden',
      explanation: 'kennen takes an accusative object, so niemand must take the accusative ending: niemanden.',
    },
    {
      id: 'ch52-ex-51',
      chapterNumber: 52,
      order: 51,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['niemand', 'dative', 'declension', 'error-correction'],
      instruction: 'Find the token with the wrong ending, and correct it.',
      prompt: 'Jemand erzählt, wie er einer Person geholfen hat. Etwas stimmt nicht.',
      tokens: ['Ich', 'habe', 'niemand', 'geholfen.'],
      errorTokenIndex: 2,
      correction: 'niemandem',
      explanation: 'helfen takes a dative object, so niemand must take the dative ending: niemandem.',
    },
    {
      id: 'ch52-ex-52',
      chapterNumber: 52,
      order: 52,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['gar-nicht', 'gar-nichts', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt, wie ihm ein Gericht schmeckt. Etwas stimmt nicht.',
      tokens: ['Das', 'gefällt', 'mir', 'gar', 'nichts.'],
      errorTokenIndex: 4,
      correction: 'nicht',
      explanation: 'gefallen needs the adverb nicht for full negation ("not at all" = gar nicht); gar nichts is the pronoun "nothing at all" and does not fit here.',
    },
    {
      id: 'ch52-ex-53',
      chapterNumber: 52,
      order: 53,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['nirgendwo', 'nichts', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt, wo er seine Schlüssel findet. Etwas stimmt nicht.',
      tokens: ['Ich', 'finde', 'meine', 'Schlüssel', 'nichts.'],
      errorTokenIndex: 4,
      correction: 'nirgendwo',
      explanation: 'The sentence describes a place ("nowhere"), not a thing, so the location word nirgendwo is needed instead of the pronoun nichts.',
    },
    {
      id: 'ch52-ex-54',
      chapterNumber: 52,
      order: 54,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['nichts', 'kein', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt, was sie besitzt. Etwas stimmt nicht.',
      tokens: ['Sie', 'hat', 'nichts', 'Auto.'],
      errorTokenIndex: 2,
      correction: 'kein',
      explanation: 'Auto is a noun and needs the determiner kein (agreeing with its gender and case), not the standalone pronoun nichts.',
    },
    {
      id: 'ch52-ex-55',
      chapterNumber: 52,
      order: 55,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['nie', 'niemand', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt eine Angewohnheit. Etwas stimmt nicht.',
      tokens: ['Er', 'ist', 'niemand', 'pünktlich.'],
      errorTokenIndex: 2,
      correction: 'nie',
      explanation: 'The sentence negates frequency ("never on time"), not a person, so nie is needed instead of niemand.',
    },
    {
      id: 'ch52-ex-56',
      chapterNumber: 52,
      order: 56,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nirgendwo', 'location'],
      instruction: 'Choose the negative word that fits.',
      prompt: 'Ich finde meine Brille ___.',
      options: [
        { id: 'a', text: 'nirgendwo' },
        { id: 'b', text: 'nichts' },
        { id: 'c', text: 'niemand' },
        { id: 'd', text: 'nie' },
      ],
      correctOptionId: 'a',
      explanation: 'The sentence negates a place ("nowhere"), so nirgendwo is correct, not the pronoun nichts or niemand.',
    },
    {
      id: 'ch52-ex-57',
      chapterNumber: 52,
      order: 57,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['gar-nicht', 'intensified-negation'],
      instruction: 'Choose the phrase that fits.',
      prompt: 'Das schmeckt mir ___.',
      options: [
        { id: 'a', text: 'gar nicht' },
        { id: 'b', text: 'gar nichts' },
        { id: 'c', text: 'kein' },
        { id: 'd', text: 'nie' },
      ],
      correctOptionId: 'a',
      explanation: 'schmecken is negated with the adverb nicht, intensified to gar nicht ("not at all"); gar nichts would be a pronoun, which does not fit this slot.',
    },
    {
      id: 'ch52-ex-58',
      chapterNumber: 52,
      order: 58,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nichts', 'dialogue', 'pronoun'],
      instruction: 'Read the exchange, then choose the word that best completes the answer.',
      prompt: 'Complete: "___."',
      dialogue: [
        { speaker: 'Anna', german: 'Was hast du gehört?', english: 'What did you hear?' },
        { speaker: 'Ben', german: '___.', english: 'Nothing.' },
      ],
      options: [
        { id: 'a', text: 'Nichts' },
        { id: 'b', text: 'Niemand' },
        { id: 'c', text: 'Nie' },
        { id: 'd', text: 'Kein' },
      ],
      correctOptionId: 'a',
      explanation: 'Ben answers with a thing that was not heard, so Nichts ("nothing") is correct, not Niemand ("nobody").',
    },
    {
      id: 'ch52-ex-59',
      chapterNumber: 52,
      order: 59,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['niemand', 'dialogue', 'pronoun'],
      instruction: 'Read the exchange, then choose the word that best completes the answer.',
      prompt: 'Complete: "___."',
      dialogue: [
        { speaker: 'Chef', german: 'Wer war im Büro?', english: 'Who was in the office?' },
        { speaker: 'Mitarbeiterin', german: '___.', english: 'Nobody.' },
      ],
      options: [
        { id: 'a', text: 'Niemand' },
        { id: 'b', text: 'Nichts' },
        { id: 'c', text: 'Nie' },
        { id: 'd', text: 'Kein' },
      ],
      correctOptionId: 'a',
      explanation: 'The question asks who was in the office, so the answer refers to a person: Niemand ("nobody").',
    },
    {
      id: 'ch52-ex-60',
      chapterNumber: 52,
      order: 60,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['nie', 'nicht-immer', 'frequency'],
      instruction: 'Choose the word that fits the intended meaning: "never", not "not always".',
      prompt: 'Sie ist ___ zu spät gekommen. (meaning: never, not once)',
      options: [
        { id: 'a', text: 'nie' },
        { id: 'b', text: 'nicht immer' },
        { id: 'c', text: 'noch nicht' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'The intended meaning rules out the event completely, every time, which requires nie, not the weaker nicht immer ("not always").',
    },
    {
      id: 'ch52-ex-61',
      chapterNumber: 52,
      order: 61,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['nicht-mehr', 'time-contrast', 'context'],
      instruction: 'Choose the phrase that fits the context.',
      prompt: 'Er hat vor einem Jahr aufgehört zu rauchen. Er raucht ___.',
      options: [
        { id: 'a', text: 'nicht mehr' },
        { id: 'b', text: 'noch nicht' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'kein' },
      ],
      correctOptionId: 'a',
      explanation: 'He used to smoke and stopped a year ago — a situation that has ended is negated with nicht mehr ("no longer").',
    },
    {
      id: 'ch52-ex-62',
      chapterNumber: 52,
      order: 62,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['noch-nicht', 'time-contrast', 'context'],
      instruction: 'Choose the phrase that fits the context.',
      prompt: 'Sie fängt nächste Woche an. Sie arbeitet ___ hier.',
      options: [
        { id: 'a', text: 'noch nicht' },
        { id: 'b', text: 'nicht mehr' },
        { id: 'c', text: 'nie' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'Her job has not started yet but will next week, so noch nicht ("not yet") is correct.',
    },
    {
      id: 'ch52-ex-63',
      chapterNumber: 52,
      order: 63,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['niemand', 'dative', 'declension'],
      instruction: 'Choose the correct form of niemand.',
      prompt: 'Ich vertraue ___.',
      options: [
        { id: 'a', text: 'niemandem' },
        { id: 'b', text: 'niemanden' },
        { id: 'c', text: 'niemand' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'vertrauen takes a dative object, so niemand takes the dative ending: niemandem.',
    },
    {
      id: 'ch52-ex-64',
      chapterNumber: 52,
      order: 64,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['niemand', 'accusative', 'declension'],
      instruction: 'Choose the correct form of niemand.',
      prompt: 'Ich habe ___ gesehen.',
      options: [
        { id: 'a', text: 'niemanden' },
        { id: 'b', text: 'niemandem' },
        { id: 'c', text: 'niemand' },
        { id: 'd', text: 'nichts' },
      ],
      correctOptionId: 'a',
      explanation: 'sehen takes an accusative object, so niemand takes the accusative ending: niemanden.',
    },
    {
      id: 'ch52-ex-65',
      chapterNumber: 52,
      order: 65,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nichts', 'nominalized-adjective'],
      instruction: 'Choose the correct negative word.',
      prompt: 'Er hat ___ Interessantes erzählt.',
      options: [
        { id: 'a', text: 'nichts' },
        { id: 'b', text: 'kein' },
        { id: 'c', text: 'nicht' },
        { id: 'd', text: 'niemand' },
      ],
      correctOptionId: 'a',
      explanation: 'nichts combines with the nominalized adjective Interessantes ("nothing interesting"); kein cannot attach to an adjective like this.',
    },
    {
      id: 'ch52-ex-66',
      chapterNumber: 52,
      order: 66,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['nirgendwo', 'error-spotting', 'grammaticality'],
      instruction: 'Choose the sentence that is grammatically correct German.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich finde meine Schlüssel nirgendwo.' },
        { id: 'b', text: 'Ich finde meine Schlüssel nirgendwo nicht.' },
        { id: 'c', text: 'Ich finde meine Schlüssel gar nichts.' },
        { id: 'd', text: 'Ich finde meine Schlüssel niemand.' },
      ],
      correctOptionId: 'a',
      explanation: 'nirgendwo already carries the negation by itself, so no extra nicht is added; gar nichts and niemand do not fit a place expression.',
    },
    {
      id: 'ch52-ex-67',
      chapterNumber: 52,
      order: 67,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['nirgendwo', 'location'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Ich finde meinen Schlüssel ___.',
      acceptedAnswers: ['nirgendwo', 'nirgends'],
      answerMode: 'caseInsensitive',
      placeholder: 'nirgendwo',
      maxLength: 12,
      explanation: 'nirgendwo (or nirgends) negates a place — the key cannot be found anywhere.',
    },
    {
      id: 'ch52-ex-68',
      chapterNumber: 52,
      order: 68,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['gar-nicht', 'intensified-negation'],
      instruction: 'Fill in the missing phrase. Capitalisation is not checked.',
      prompt: 'Das interessiert mich ___. (not at all)',
      acceptedAnswers: ['gar nicht'],
      answerMode: 'caseInsensitive',
      placeholder: 'gar nicht',
      maxLength: 15,
      explanation: 'gar nicht intensifies nicht to mean "not at all".',
    },
    {
      id: 'ch52-ex-69',
      chapterNumber: 52,
      order: 69,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['niemand', 'dative'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Ich vertraue ___.',
      acceptedAnswers: ['niemandem'],
      answerMode: 'caseInsensitive',
      placeholder: 'niemandem',
      maxLength: 12,
      explanation: 'vertrauen takes a dative object, so niemand becomes niemandem.',
    },
    {
      id: 'ch52-ex-70',
      chapterNumber: 52,
      order: 70,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['niemand', 'accusative'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Ich habe ___ gefragt.',
      acceptedAnswers: ['niemanden'],
      answerMode: 'caseInsensitive',
      placeholder: 'niemanden',
      maxLength: 12,
      explanation: 'fragen takes an accusative object, so niemand becomes niemanden.',
    },
    {
      id: 'ch52-ex-71',
      chapterNumber: 52,
      order: 71,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['nichts', 'nominalized-adjective'],
      instruction: 'Fill in the missing word. Capitalisation is not checked.',
      prompt: 'Er hat ___ Wichtiges gesagt.',
      acceptedAnswers: ['nichts'],
      answerMode: 'caseInsensitive',
      placeholder: 'nichts',
      maxLength: 12,
      explanation: 'nichts combines with the nominalized adjective Wichtiges ("nothing important").',
    },
    {
      id: 'ch52-ex-72',
      chapterNumber: 52,
      order: 72,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['nirgendwo', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using nirgendwo. Capitalisation and punctuation are checked.',
      prompt: 'Ich finde meine Brille irgendwo.',
      acceptedAnswers: ['Ich finde meine Brille nirgendwo.'],
      answerMode: 'normalized',
      placeholder: 'Ich finde meine Brille ...',
      maxLength: 45,
      explanation: 'irgendwo is replaced by nirgendwo in the same location slot: Ich finde meine Brille nirgendwo.',
    },
    {
      id: 'ch52-ex-73',
      chapterNumber: 52,
      order: 73,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['gar-nicht', 'sentence-transformation'],
      instruction: 'Rewrite the sentence to mean "not at all", using gar nicht. Capitalisation and punctuation are checked.',
      prompt: 'Das interessiert mich sehr.',
      acceptedAnswers: ['Das interessiert mich gar nicht.'],
      answerMode: 'normalized',
      placeholder: 'Das interessiert mich ...',
      maxLength: 40,
      explanation: 'sehr ("a lot") is replaced by gar nicht ("not at all") to fully reverse the meaning: Das interessiert mich gar nicht.',
    },
    {
      id: 'ch52-ex-74',
      chapterNumber: 52,
      order: 74,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['nie', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using nie. Capitalisation and punctuation are checked.',
      prompt: 'Sie kommt oft zu spät.',
      acceptedAnswers: ['Sie kommt nie zu spät.'],
      answerMode: 'normalized',
      placeholder: 'Sie kommt ...',
      maxLength: 40,
      explanation: 'oft is replaced by nie in the same frequency-adverb slot: Sie kommt nie zu spät.',
    },
    {
      id: 'ch52-ex-75',
      chapterNumber: 52,
      order: 75,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['niemand', 'dative', 'sentence-transformation'],
      instruction: 'Rewrite the sentence in the negative form using niemandem. Capitalisation and punctuation are checked.',
      prompt: 'Ich habe jemandem geholfen.',
      acceptedAnswers: ['Ich habe niemandem geholfen.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe ...',
      maxLength: 40,
      explanation: 'jemandem is replaced by niemandem in the same dative object slot: Ich habe niemandem geholfen.',
    },
    {
      id: 'ch52-ex-76',
      chapterNumber: 52,
      order: 76,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'nie', 'niemand'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Sie ist niemand pünktlich.',
      acceptedAnswers: ['Sie ist nie pünktlich.'],
      answerMode: 'normalized',
      placeholder: 'Sie ist ...',
      maxLength: 30,
      explanation: 'The sentence negates frequency ("never on time"), not a person, so niemand must be corrected to nie.',
    },
    {
      id: 'ch52-ex-77',
      chapterNumber: 52,
      order: 77,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'niemand', 'dative'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich habe niemand geholfen.',
      acceptedAnswers: ['Ich habe niemandem geholfen.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe ...',
      maxLength: 30,
      explanation: 'helfen takes a dative object, so niemand must be corrected to the dative form niemandem.',
    },
  ],
};
