import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter012: ChapterDefinition = {
  id: 'chapter-012',
  number: 12,
  slug: 'the-verb-in-position-2',
  title: 'The Verb in Position 2',
  germanTitle: 'Das Verb auf Position 2',
  level: 'A1',
  section: 'sentences-and-questions',
  objective:
    'Recognize that a German main-clause statement always keeps the finite verb as the second sentence element, and correctly move the subject after the verb whenever a time, place, or other element is fronted into position 1.',
  prerequisites: [2, 11],
  estimatedMinutes: 25,
  tags: ['word-order', 'verb-position', 'sentence-elements', 'inversion', 'fronting'],
  explanation: {
    introduction: [
      'In a German main-clause statement, the conjugated verb is not simply "the second word" — it is the second sentence element. An element can be a single word, but it can also be a whole phrase (am Montag, in Berlin, meine kleine Schwester) that stays together and moves as one block. Whatever fills position 1, the finite verb always follows immediately in position 2.',
      'This also means the subject does not have to stand first. A time expression, a place expression, an object, or an adverb can take position 1 instead — but then the subject has to move to right after the verb. This chapter trains you to count elements instead of words, to recognize the finite verb wherever it stands, and to reorder sentences correctly when something other than the subject is fronted.',
    ],
    rules: [
      {
        id: 'ch12-rule-01',
        heading: 'The finite verb occupies position 2',
        paragraphs: [
          'In a German main-clause statement, the conjugated (finite) verb is always the second element of the sentence. Grammarians call this the "verb-second rule", or V2 for short.',
          'Position 2 does not mean the second word — it means the second complete sentence element. An element can be one word, or it can be a whole phrase that belongs together and moves as a single block.',
        ],
        notes: [
          'Ich (1) lerne (2) jeden Tag Deutsch. — three elements: Ich, lerne, jeden Tag Deutsch.',
          'Am Montag (1) beginnt (2) der Kurs. — "Am Montag" is a single element, even though it is two words.',
        ],
      },
      {
        id: 'ch12-rule-02',
        heading: 'Counting elements, not words',
        paragraphs: [
          'A sentence element can be a single word (ich, heute, dort) or a phrase that functions as one unit: a prepositional phrase (am Montag, in Berlin, zum Geburtstag), a noun phrase with an article and adjective (meine kleine Schwester), or a multi-word time expression (um acht Uhr, jeden Tag).',
          'To find position 2, first split the sentence into its elements, then look at the second one — not the second word. "Am Montag beginnt der Kurs." has three elements (Am Montag / beginnt / der Kurs), not four separate words in four positions.',
        ],
      },
      {
        id: 'ch12-rule-03',
        heading: 'The subject is not always in position 1',
        paragraphs: [
          'In many German sentences the subject happens to stand in position 1, but it does not have to. Any single sentence element — a time expression, a place expression, a direct object, or an adverb like leider or vielleicht — can be moved to position 1, usually to emphasize it or to connect it to what was said before.',
          'Fronting an element does not change its grammatical function: a fronted object is still the object, and a fronted time expression is still just background information about when something happens — it never becomes the subject.',
        ],
      },
      {
        id: 'ch12-rule-04',
        heading: 'Inversion: the subject moves after the verb',
        paragraphs: [
          'Because the finite verb must stay in position 2, fronting a non-subject element forces the subject to move — it can no longer stand in front of the verb. Instead, the subject appears directly after the verb, usually as the very next element.',
          'This swap is called inversion. It is completely normal and required whenever position 1 is filled by something other than the subject: Heute komme ich später. / In Berlin wohnt meine Schwester. / Den Kuchen backt meine Mutter.',
        ],
        notes: [
          'A frequent mistake for English speakers is to keep the English subject-first order and simply add the new element at the front: Heute ich komme später. — this is wrong in German. The verb must come immediately after the fronted element, not after the subject.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch12-table-01',
        title: 'The verb stays in position 2, whatever fills position 1',
        columns: ['Position 1', 'Position 2 (verb)', 'Rest of the sentence'],
        rows: [
          ['Ich', 'komme', 'heute später nach Hause.'],
          ['Heute', 'komme', 'ich später nach Hause.'],
          ['Meine Schwester', 'wohnt', 'in Berlin.'],
          ['In Berlin', 'wohnt', 'meine Schwester.'],
          ['Der Kurs', 'beginnt', 'am Montag.'],
          ['Am Montag', 'beginnt', 'der Kurs.'],
        ],
        note:
          'Whatever stands in position 1 — a subject, a time phrase, a place phrase — the finite verb always stays fixed in position 2, and the subject moves right after the verb whenever it is not itself in position 1.',
      },
    ],
    examples: [
      {
        german: 'Ich lerne jeden Tag Deutsch.',
        english: 'I learn German every day.',
        highlight: ['Ich', 'lerne'],
        explanation: 'The subject Ich stands in position 1, the finite verb lerne in position 2.',
      },
      {
        german: 'Jeden Tag lerne ich Deutsch.',
        english: 'Every day I learn German.',
        highlight: ['Jeden Tag', 'lerne'],
        explanation:
          'The time phrase "Jeden Tag" now fills position 1, so the subject ich moves after the verb.',
      },
      {
        german: 'Heute komme ich später nach Hause.',
        english: 'Today I am coming home later.',
        highlight: ['Heute', 'komme'],
        explanation: 'The verb komme stays in position 2 even though the subject ich moved to position 3.',
      },
      {
        german: 'In Berlin wohnt meine Schwester.',
        english: 'My sister lives in Berlin.',
        highlight: ['In Berlin', 'wohnt'],
        explanation: 'The place phrase "In Berlin" is one element and occupies position 1.',
      },
      {
        german: 'Meine Schwester wohnt in Berlin.',
        english: 'My sister lives in Berlin.',
        highlight: ['Meine Schwester', 'wohnt'],
        explanation: 'The same information, but here the subject stands in position 1 instead.',
      },
      {
        german: 'Am Montag beginnt der Deutschkurs.',
        english: 'The German course starts on Monday.',
        highlight: ['Am Montag', 'beginnt'],
        explanation: '"Am Montag" is a single time element, so beginnt still follows directly as position 2.',
      },
      {
        german: 'Um acht Uhr frühstückt die Familie.',
        english: 'The family has breakfast at eight.',
        highlight: ['Um acht Uhr', 'frühstückt'],
        explanation: 'The three-word time phrase "Um acht Uhr" counts as a single element in position 1.',
      },
      {
        german: 'Den Kuchen backt meine Mutter.',
        english: 'My mother is baking the cake.',
        highlight: ['Den Kuchen', 'backt'],
        explanation: 'Here the direct object "Den Kuchen", not the subject, has been fronted into position 1.',
      },
      {
        german: 'Morgen fahren wir nach München.',
        english: 'Tomorrow we are driving to Munich.',
        highlight: ['Morgen', 'fahren'],
        explanation: 'The subject wir moves after the verb fahren because morgen fills position 1.',
      },
      {
        german: 'Leider habe ich heute keine Zeit.',
        english: 'Unfortunately I have no time today.',
        highlight: ['Leider', 'habe'],
        explanation: 'Even a single adverb like leider can occupy position 1 and trigger inversion.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Heute ich komme später nach Hause.',
        correct: 'Heute komme ich später nach Hause.',
        explanation:
          'When a time expression is fronted into position 1, the finite verb must still stand in position 2; the subject ich cannot stay in front of it — it moves after the verb.',
      },
      {
        incorrect: 'In Berlin meine Schwester wohnt.',
        correct: 'In Berlin wohnt meine Schwester.',
        explanation:
          'Fronting "In Berlin" does not push the verb to the end; the verb wohnt must remain the second element, immediately after the fronted phrase.',
      },
      {
        incorrect: 'Am Montag der Kurs beginnt.',
        correct: 'Am Montag beginnt der Kurs.',
        explanation:
          'The time phrase "Am Montag" occupies position 1 as a single element, so the finite verb beginnt must come right after it in position 2, before the subject der Kurs.',
      },
      {
        incorrect: 'Um acht Uhr die Familie frühstückt.',
        correct: 'Um acht Uhr frühstückt die Familie.',
        explanation:
          'The three-word time phrase "Um acht Uhr" is still just one element; the verb frühstückt must directly follow it, not the subject.',
      },
      {
        incorrect: 'Den Kuchen meine Mutter backt.',
        correct: 'Den Kuchen backt meine Mutter.',
        explanation:
          'Fronting the object "Den Kuchen" still requires the verb backt in position 2; the subject meine Mutter has to follow the verb, not precede it.',
      },
    ],
    remember: [
      'The finite verb is always the second element of a German main-clause statement — not necessarily the second word.',
      'A sentence element can be a single word or a whole phrase (e.g. "am Montag", "in Berlin") that moves together as one unit.',
      'The subject does not have to stand in position 1; time, place, objects, and other elements can be fronted there instead.',
      'When something other than the subject fills position 1, the subject shifts to directly after the verb (inversion) — the verb itself always stays in position 2.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch12-ex-01',
      chapterNumber: 12,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['verb-position', 'finite-verb'],
      instruction: 'Identify the finite (conjugated) verb in the sentence.',
      prompt: 'Meine Schwester lernt jeden Tag Englisch.',
      options: [
        { id: 'a', text: 'Schwester' },
        { id: 'b', text: 'lernt' },
        { id: 'c', text: 'jeden' },
        { id: 'd', text: 'Englisch' },
      ],
      correctOptionId: 'b',
      explanation: 'lernt is the conjugated verb; it stands in position 2, right after the subject Meine Schwester.',
    },
    {
      id: 'ch12-ex-02',
      chapterNumber: 12,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['verb-position', 'finite-verb'],
      instruction: 'Identify the finite (conjugated) verb in the sentence.',
      prompt: 'Am Wochenende besuchen wir unsere Großeltern.',
      options: [
        { id: 'a', text: 'Wochenende' },
        { id: 'b', text: 'besuchen' },
        { id: 'c', text: 'wir' },
        { id: 'd', text: 'Großeltern' },
      ],
      correctOptionId: 'b',
      explanation:
        'besuchen is the finite verb. It stands in position 2, right after the fronted time phrase "Am Wochenende".',
    },
    {
      id: 'ch12-ex-03',
      chapterNumber: 12,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['verb-position', 'sentence-elements'],
      instruction: 'Which element stands in position 2 of this sentence?',
      prompt: 'Ich komme heute später nach Hause.',
      options: [
        { id: 'a', text: 'Ich' },
        { id: 'b', text: 'komme' },
        { id: 'c', text: 'heute' },
        { id: 'd', text: 'später' },
      ],
      correctOptionId: 'b',
      explanation:
        'Ich is element 1 (the subject) and komme, the finite verb, is element 2.',
    },
    {
      id: 'ch12-ex-04',
      chapterNumber: 12,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['verb-position', 'sentence-elements', 'fronting'],
      instruction: 'Which element stands in position 1 of this sentence?',
      prompt: 'Heute komme ich später nach Hause.',
      options: [
        { id: 'a', text: 'Heute' },
        { id: 'b', text: 'komme' },
        { id: 'c', text: 'ich' },
        { id: 'd', text: 'später' },
      ],
      correctOptionId: 'a',
      explanation:
        'The time expression Heute has been fronted into position 1, pushing the subject ich after the verb komme.',
    },
    {
      id: 'ch12-ex-05',
      chapterNumber: 12,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sentence-elements'],
      instruction: 'Count the sentence elements, not the words.',
      prompt: 'How many sentence elements does "Am Montag beginnt der Kurs." have?',
      options: [
        { id: 'a', text: '2' },
        { id: 'b', text: '3' },
        { id: 'c', text: '4' },
        { id: 'd', text: '5' },
      ],
      correctOptionId: 'b',
      explanation:
        'The sentence has three elements: Am Montag / beginnt / der Kurs — even though it consists of four words.',
    },
    {
      id: 'ch12-ex-06',
      chapterNumber: 12,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sentence-elements'],
      instruction: 'Count the sentence elements, not the words.',
      prompt: 'How many sentence elements does "In Berlin wohnt meine Schwester." have?',
      options: [
        { id: 'a', text: '2' },
        { id: 'b', text: '3' },
        { id: 'c', text: '4' },
        { id: 'd', text: '5' },
      ],
      correctOptionId: 'b',
      explanation:
        'The sentence has three elements: In Berlin / wohnt / meine Schwester — even though it consists of five words.',
    },
    {
      id: 'ch12-ex-07',
      chapterNumber: 12,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['verb-position', 'fronting', 'inversion'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Emphasize "heute" by putting it first.',
      options: [
        { id: 'a', text: 'Heute komme ich später nach Hause.' },
        { id: 'b', text: 'Heute ich komme später nach Hause.' },
        { id: 'c', text: 'Ich heute komme später nach Hause.' },
        { id: 'd', text: 'Komme heute ich später nach Hause.' },
      ],
      correctOptionId: 'a',
      explanation:
        'With "Heute" fronted into position 1, the finite verb komme must directly follow in position 2, then the subject ich.',
    },
    {
      id: 'ch12-ex-08',
      chapterNumber: 12,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['verb-position', 'fronting', 'inversion'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Emphasize "in Hamburg" by putting it first.',
      options: [
        { id: 'a', text: 'In Hamburg wohnt mein Onkel.' },
        { id: 'b', text: 'In Hamburg mein Onkel wohnt.' },
        { id: 'c', text: 'Mein Onkel in Hamburg wohnt.' },
        { id: 'd', text: 'Wohnt in Hamburg mein Onkel.' },
      ],
      correctOptionId: 'a',
      explanation:
        'With "In Hamburg" fronted, the verb wohnt must stand in position 2, and the subject mein Onkel follows it.',
    },
    {
      id: 'ch12-ex-09',
      chapterNumber: 12,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['verb-position', 'fronting', 'inversion'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Emphasize "den Salat" by putting it first.',
      options: [
        { id: 'a', text: 'Den Salat macht mein Vater.' },
        { id: 'b', text: 'Den Salat mein Vater macht.' },
        { id: 'c', text: 'Mein Vater den Salat macht.' },
        { id: 'd', text: 'Macht den Salat mein Vater.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The object "Den Salat" is fronted into position 1, so the verb macht must directly follow it, then the subject mein Vater.',
    },
    {
      id: 'ch12-ex-10',
      chapterNumber: 12,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['fronting', 'sentence-elements'],
      instruction: 'Identify what kind of element has been fronted.',
      prompt: 'What kind of element stands in position 1 of "Am Sonntag besuchen wir unsere Oma."?',
      options: [
        { id: 'a', text: 'a time expression' },
        { id: 'b', text: 'a place expression' },
        { id: 'c', text: 'the subject' },
        { id: 'd', text: 'a direct object' },
      ],
      correctOptionId: 'a',
      explanation:
        '"Am Sonntag" tells us when something happens, so it is a time expression, not the subject (wir).',
    },
    {
      id: 'ch12-ex-11',
      chapterNumber: 12,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sentence-elements', 'fronting'],
      instruction: 'Identify the element in position 1.',
      prompt: 'Zum Geburtstag bekommt er ein neues Fahrrad.',
      options: [
        { id: 'a', text: 'Zum Geburtstag' },
        { id: 'b', text: 'bekommt' },
        { id: 'c', text: 'er' },
        { id: 'd', text: 'ein neues Fahrrad' },
      ],
      correctOptionId: 'a',
      explanation:
        'The prepositional phrase "Zum Geburtstag" counts as one element and fills position 1; the verb bekommt follows in position 2.',
    },
    {
      id: 'ch12-ex-12',
      chapterNumber: 12,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['verb-position', 'inversion'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Emphasize "leider" (unfortunately) by putting it first.',
      options: [
        { id: 'a', text: 'Leider habe ich heute keine Zeit.' },
        { id: 'b', text: 'Leider ich habe heute keine Zeit.' },
        { id: 'c', text: 'Ich leider habe heute keine Zeit.' },
        { id: 'd', text: 'Habe leider ich heute keine Zeit.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Even a single adverb like leider fills position 1 on its own; the verb habe still follows immediately in position 2.',
    },
    {
      id: 'ch12-ex-13',
      chapterNumber: 12,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['verb-position', 'finite-verb'],
      instruction: 'Write the finite verb in this sentence. Capitalisation is not checked.',
      prompt: 'Meine Schwester wohnt in Berlin.',
      acceptedAnswers: ['wohnt'],
      answerMode: 'caseInsensitive',
      placeholder: 'verb',
      maxLength: 15,
      explanation: 'wohnt is the conjugated verb, standing in position 2 after the subject Meine Schwester.',
    },
    {
      id: 'ch12-ex-14',
      chapterNumber: 12,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['verb-position', 'finite-verb', 'fronting'],
      instruction: 'Write the finite verb in this sentence. Capitalisation is not checked.',
      prompt: 'In Berlin wohnt meine Schwester.',
      acceptedAnswers: ['wohnt'],
      answerMode: 'caseInsensitive',
      placeholder: 'verb',
      maxLength: 15,
      explanation:
        'wohnt is still the finite verb and still stands in position 2, even though "In Berlin" now fills position 1.',
    },
    {
      id: 'ch12-ex-15',
      chapterNumber: 12,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-elements'],
      instruction: 'Count the sentence elements, not the words. Write the number as a digit.',
      prompt: 'How many sentence elements does "Um acht Uhr frühstückt die Familie." have?',
      acceptedAnswers: ['3'],
      answerMode: 'caseInsensitive',
      placeholder: 'number',
      maxLength: 3,
      explanation:
        'The sentence has three elements: Um acht Uhr / frühstückt / die Familie — the time phrase counts as one element although it is three words.',
    },
    {
      id: 'ch12-ex-16',
      chapterNumber: 12,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['fronting', 'inversion', 'word-order'],
      instruction:
        'Rewrite the sentence so that the element in brackets stands in position 1. Capitalisation and punctuation are checked.',
      prompt: 'Ich komme heute später nach Hause. (heute)',
      acceptedAnswers: ['Heute komme ich später nach Hause.'],
      answerMode: 'normalized',
      placeholder: 'Heute ...',
      maxLength: 60,
      explanation:
        'Fronting heute pushes it into position 1; the verb komme still follows in position 2, and the subject ich moves after the verb.',
    },
    {
      id: 'ch12-ex-17',
      chapterNumber: 12,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['fronting', 'inversion', 'word-order'],
      instruction:
        'Rewrite the sentence so that the element in brackets stands in position 1. Capitalisation and punctuation are checked.',
      prompt: 'Meine Schwester wohnt in Berlin. (in Berlin)',
      acceptedAnswers: ['In Berlin wohnt meine Schwester.'],
      answerMode: 'normalized',
      placeholder: 'In Berlin ...',
      maxLength: 60,
      explanation:
        'Fronting "in Berlin" moves it to position 1; the verb wohnt stays in position 2, and the subject meine Schwester follows it.',
    },
    {
      id: 'ch12-ex-18',
      chapterNumber: 12,
      order: 18,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['fronting', 'inversion', 'word-order'],
      instruction:
        'Rewrite the sentence so that the element in brackets stands in position 1. Capitalisation and punctuation are checked.',
      prompt: 'Meine Mutter backt den Kuchen. (den Kuchen)',
      acceptedAnswers: ['Den Kuchen backt meine Mutter.'],
      answerMode: 'normalized',
      placeholder: 'Den Kuchen ...',
      maxLength: 60,
      explanation:
        'The object "den Kuchen" is fronted into position 1; the verb backt keeps position 2, and the subject meine Mutter follows it.',
    },
    {
      id: 'ch12-ex-19',
      chapterNumber: 12,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['inversion', 'word-order'],
      instruction: 'Correct the word-order mistake. Capitalisation and punctuation are checked.',
      prompt: 'Heute ich komme später nach Hause.',
      acceptedAnswers: ['Heute komme ich später nach Hause.'],
      answerMode: 'normalized',
      placeholder: 'Heute ...',
      maxLength: 60,
      explanation:
        'The verb komme must stand directly after the fronted "Heute", in position 2; the subject ich has to move after the verb.',
    },
    {
      id: 'ch12-ex-20',
      chapterNumber: 12,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['inversion', 'word-order'],
      instruction: 'Correct the word-order mistake. Capitalisation and punctuation are checked.',
      prompt: 'In Berlin meine Schwester wohnt.',
      acceptedAnswers: ['In Berlin wohnt meine Schwester.'],
      answerMode: 'normalized',
      placeholder: 'In Berlin ...',
      maxLength: 60,
      explanation:
        'The verb wohnt belongs in position 2, right after "In Berlin"; the subject meine Schwester must follow the verb, not precede it.',
    },
    {
      id: 'ch12-ex-21',
      chapterNumber: 12,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['inversion', 'word-order'],
      instruction: 'Correct the word-order mistake. Capitalisation and punctuation are checked.',
      prompt: 'Am Montag der Kurs beginnt.',
      acceptedAnswers: ['Am Montag beginnt der Kurs.'],
      answerMode: 'normalized',
      placeholder: 'Am Montag ...',
      maxLength: 60,
      explanation:
        'The finite verb beginnt must stand in position 2, immediately after "Am Montag"; the subject der Kurs then follows the verb.',
    },
    {
      id: 'ch12-ex-22',
      chapterNumber: 12,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['fronting', 'inversion', 'word-order'],
      instruction:
        'Write a complete sentence from the cue words, fronting the element given in brackets. Capitalisation and punctuation are checked.',
      prompt: 'wir – morgen – nach München – fahren (front: morgen)',
      acceptedAnswers: ['Morgen fahren wir nach München.'],
      answerMode: 'normalized',
      placeholder: 'Morgen ...',
      maxLength: 60,
      explanation:
        'morgen goes into position 1, the finite verb fahren follows in position 2, and the subject wir comes right after the verb.',
    },
    {
      id: 'ch12-ex-23',
      chapterNumber: 12,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['fronting', 'inversion', 'word-order'],
      instruction:
        'Write a complete sentence from the cue words, fronting the element given in brackets and conjugating the verb correctly. Capitalisation and punctuation are checked.',
      prompt: 'die Familie – um acht Uhr – frühstücken (front: um acht Uhr)',
      acceptedAnswers: ['Um acht Uhr frühstückt die Familie.'],
      answerMode: 'normalized',
      placeholder: 'Um acht Uhr ...',
      maxLength: 60,
      explanation:
        '"Um acht Uhr" counts as one element in position 1; frühstückt (die Familie, 3rd person singular) follows in position 2, and the subject comes after the verb.',
    },
    {
      id: 'ch12-ex-24',
      chapterNumber: 12,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-elements', 'word-order'],
      instruction:
        'Rewrite the sentence so that the subject stands in position 1 instead. Capitalisation and punctuation are checked.',
      prompt: 'Zum Geburtstag bekommt er ein neues Fahrrad.',
      acceptedAnswers: ['Er bekommt zum Geburtstag ein neues Fahrrad.'],
      answerMode: 'normalized',
      placeholder: 'Er ...',
      maxLength: 70,
      explanation:
        'With the subject er in position 1, the verb bekommt still stands in position 2, and "zum Geburtstag" simply moves later in the sentence.',
    },
  ],
};
