import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter061: ChapterDefinition = {
  id: 'chapter-061',
  number: 61,
  slug: 'konjunktiv-ii-usage',
  title: 'Konjunktiv II: Usage',
  germanTitle: 'Konjunktiv II: Gebrauch',
  level: 'B1',
  section: 'verbs-3',
  objective:
    'Use the Konjunktiv II forms you already know (wäre, hätte, würde + infinitive, könnte, müsste, sollte, ...) to make polite requests, express wishes, describe hypothetical situations, give advice with sollte, and build unreal wenn-conditions in both possible word orders, with and without wenn.',
  prerequisites: [60],
  estimatedMinutes: 30,
  tags: [
    'konjunktiv-ii',
    'subjunctive-ii-usage',
    'polite-requests',
    'wishes',
    'hypothetical-situations',
    'sollte',
    'unreal-conditions',
    'wenn-clauses',
    'conditional-sentences',
  ],
  explanation: {
    introduction: [
      'Chapter 60 taught you how Konjunktiv II forms are built: the analytic würde + infinitive, and the synthetic one-word forms wäre, hätte, könnte, müsste, wollte, möchte, dürfte, and sollte. This chapter assumes all of that is familiar and asks a different question: what do you actually do with these forms? The answer is that Konjunktiv II has four everyday jobs in German — softening requests, expressing wishes, describing hypothetical or unreal situations, and giving advice — and this chapter works through each one in turn.',
      'The common thread running through all four uses is distance from reality. A polite request pretends, for a moment, that you are not sure whether the other person can or will help, which softens the demand. A wish states something contrary to how things actually are. A hypothetical situation imagines a world that does not exist. Advice with sollte suggests a course of action without insisting on it. In every case, Konjunktiv II signals: this is not simply a fact.',
      'The largest part of this chapter is devoted to unreal wenn-conditions, because they combine everything at once: a wenn-clause and a main clause both in Konjunktiv II, and — as you will see — a genuine choice in word order. German lets you drop wenn entirely and move the verb to the front of the clause instead, without changing the meaning at all. Wenn ich Zeit hätte, würde ich kommen. and Hätte ich Zeit, würde ich kommen. mean exactly the same thing: If I had time, I would come.',
    ],
    rules: [
      {
        id: 'ch61-rule-01',
        heading: 'Softening requests with Konjunktiv II',
        paragraphs: [
          'A direct imperative or a present-tense question can sound blunt, especially to strangers, in shops, offices, or any formal situation: Gib mir das Salz! (Give me the salt!) or Kannst du mir helfen? (Can you help me?) are perfectly fine among close friends but can feel abrupt elsewhere. Konjunktiv II softens the same request into something more careful and polite: Könntest du mir das Salz geben? and Könntest du mir helfen? ask for exactly the same thing, only less directly.',
          'The most common polite-request patterns are built on the synthetic forms you already know: Könnten Sie...? / Könntest du...? (Could you...?), Würden Sie...? / Würdest du...? (Would you...?), Hätten Sie...? (Would you have...?), and Dürfte ich...? (Might I...?). Ich hätte gern... (I would like...) is a fixed, extremely common polite pattern for ordering or requesting something: Ich hätte gern einen Kaffee. (I would like a coffee.)',
          'Formal Sie is the default register for polite requests to strangers, officials, waitstaff, and colleagues you do not know well; the informal du forms (könntest du, würdest du) are used with friends, family, and people you already address informally — the Konjunktiv II softening works identically in both registers, only the pronoun and ending change.',
        ],
      },
      {
        id: 'ch61-rule-02',
        heading: 'Wishes: Ich wünschte, ... and Ich wollte, ...',
        paragraphs: [
          'To wish that reality were different, German uses Ich wünschte, ... or the near-synonymous Ich wollte, ... followed by a clause in Konjunktiv II: Ich wünschte, ich hätte mehr Zeit. and Ich wollte, ich hätte mehr Zeit. both mean I wish I had more time. Despite its shape, wollte here does not mean "wanted" — in this fixed construction it functions exactly like wünschte, and both are common in everyday speech.',
          'The dass that would normally introduce a subordinate clause is optional in this pattern: Ich wünschte, ich wäre reich. and Ich wünschte, dass ich reich wäre. are both correct and mean the same thing, though the version without dass is somewhat more common in speech. Either way, the wished-for clause always uses Konjunktiv II, never the present indicative, because the wish is by definition contrary to fact.',
          'A more emphatic wish can be built without Ich wünschte at all, using wenn plus doch (nur) and an exclamation mark: Wenn ich doch nur mehr Zeit hätte! (If only I had more time!). This pattern, and its verb-first version without wenn — Hätte ich doch nur mehr Zeit! — both work the same way as the unreal conditions covered later in this chapter, just used as a stand-alone exclamation rather than followed by a main clause.',
        ],
      },
      {
        id: 'ch61-rule-03',
        heading: 'Describing hypothetical situations',
        paragraphs: [
          'Beyond fixed request and wish patterns, Konjunktiv II is simply the everyday tool for describing a situation that is not real: something imagined, something proposed, something merely possible. An deiner Stelle würde ich das nicht machen. (In your place, I would not do that.) and Wenn ich du wäre, würde ich das Angebot annehmen. (If I were you, I would accept the offer.) both speculate about an imagined version of events rather than reporting a fact.',
          'These hypothetical statements do not need a wenn-clause at all — An deiner Stelle (In your place) and other similar phrases can introduce the same kind of speculation on their own. What all of them share is that the verb is in Konjunktiv II precisely because the situation being described is not the actual, current state of affairs.',
          'Because so much of everyday hypothetical speech is just this kind of speculation — what someone would do, what would be nice, what would happen — you will meet Konjunktiv II constantly in advice, small talk, and daydreaming alike, not only in formal wenn-conditions.',
        ],
      },
      {
        id: 'ch61-rule-04',
        heading: 'sollte: the everyday way to give advice',
        paragraphs: [
          'sollte, the Konjunktiv II form of sollen, is the standard, everyday way to give advice in German: Du solltest mehr schlafen. (You should sleep more.) It suggests a course of action without insisting on it — the natural equivalent of English should.',
          'sollte sits in a scale of strength alongside the other modal Konjunktiv II forms: könntest offers a mere option or suggestion (Du könntest früher schlafen gehen. — You could go to bed earlier.); solltest gives a recommendation (Du solltest mehr schlafen. — You should sleep more.); müsstest is noticeably stronger, close to an unavoidable obligation (Du müsstest eigentlich früher aufstehen. — You would really have to get up earlier.).',
          'sollte (Konjunktiv II, advice) must not be confused with sollst / sollt / sollen (present-tense indicative), which report an instruction, rule, or order rather than offer advice: Du sollst pünktlich sein. (You are supposed to be on time — someone told you this, or it is a rule.) sounds like a command or a reported obligation, while Du solltest pünktlich sein. (You should be on time.) sounds like a friendly recommendation.',
        ],
      },
      {
        id: 'ch61-rule-05',
        heading: 'Unreal conditions: wenn-clause and main clause both in Konjunktiv II',
        paragraphs: [
          'A wenn-clause describing a real, likely, or open condition stays in the present indicative in both clauses: Wenn es regnet, nehme ich einen Schirm. (If it rains, I take an umbrella.) — this is simply a true, general fact, not a hypothetical. An unreal condition, by contrast, imagines something contrary to fact or merely possible, and both clauses switch to Konjunktiv II: Wenn ich Zeit hätte, würde ich kommen. (If I had time, I would come.) The hätte signals that, in fact, I do not have time; the würde-clause states what would follow if I did.',
          'Both halves of the sentence need Konjunktiv II — using the present indicative in the main clause breaks the unreal meaning and sounds wrong: Wenn ich Zeit hätte, ich komme dich besuchen. is incorrect; it must be Wenn ich Zeit hätte, würde ich dich besuchen. The wenn-clause verb goes to the very end of its clause exactly as with weil or dass (chapters 46-47); the main clause verb takes second position, immediately after the comma.',
          'Any combination of synthetic and analytic Konjunktiv II forms can appear in the same sentence, exactly as chapter 60 predicted: Wenn du mehr üben würdest, würdest du besser sprechen. (If you practiced more, you would speak better.) uses würde in both clauses because üben and sprechen have no natural synthetic forms; Wenn ich mehr Geld hätte, würde ich reisen. (If I had more money, I would travel.) combines the synthetic hätte with the analytic würde reisen.',
        ],
      },
      {
        id: 'ch61-rule-06',
        heading: 'Dropping wenn: verb-first conditional clauses',
        paragraphs: [
          'German allows wenn to be dropped from an unreal condition, provided the conjugated verb of that clause moves all the way to the front, taking the position wenn would otherwise have occupied. Wenn ich Zeit hätte, würde ich kommen. and Hätte ich Zeit, würde ich kommen. mean exactly the same thing: If I had time, I would come. The main clause is unaffected either way and still has würde ich kommen with normal verb-second word order.',
          'This is not a random shortcut — it follows a strict rule. You cannot simply delete wenn and keep the clause in normal subject-verb order: Ich Zeit hätte, würde ich kommen. is ungrammatical. The finite verb (hätte, käme, wäre, würde, and so on) must be the very first word of the clause once wenn is gone, exactly as in a yes/no question, though here it is not a question at all.',
          'The verb-first pattern is common in both speech and writing and often sounds slightly more emphatic or literary than the version with wenn, but the two are fully interchangeable in meaning: Wäre ich reich, würde ich um die Welt reisen. and Wenn ich reich wäre, würde ich um die Welt reisen. (If I were rich, I would travel around the world.) are equally correct, natural German.',
        ],
      },
      {
        id: 'ch61-rule-07',
        heading: 'Meaning distinctions among Konjunktiv II modals',
        paragraphs: [
          'Because German reuses the same small set of Konjunktiv II modal forms for several different jobs, choosing the right one changes the meaning of a sentence in ways that are easy to miss. könnte expresses possibility or ability: Es könnte heute regnen. (It could rain today.) müsste expresses a strong, near-certain probability, closer to "must probably" than to obligation: Er müsste bald hier sein. (He should be here soon — I am fairly sure of it.)',
          'sollte, as already covered, expresses advice or a mild expectation: Du solltest das nicht tun. (You should not do that.) dürfte expresses a cautious, hedged probability, close to "might well": Das dürfte stimmen. (That is probably right.) würde, finally, is the general-purpose hypothetical form for any action or state that has no more specific modal shade of meaning: Ich würde das nicht sagen. (I would not say that.)',
          'These are genuinely different meanings, not stylistic variants of the same idea — swapping müsste for sollte turns a confident prediction into a piece of advice, and swapping könnte for müsste turns a mere possibility into a near-certainty. Paying attention to which modal a sentence uses is just as important as recognizing that it is in Konjunktiv II at all.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch61-table-01',
        title: 'Polite request patterns',
        columns: ['Pattern', 'Example', 'English'],
        rows: [
          ['Könnten Sie...?', 'Könnten Sie mir helfen?', 'Could you help me? (formal)'],
          ['Könntest du...?', 'Könntest du mir helfen?', 'Could you help me? (informal)'],
          ['Würden Sie...?', 'Würden Sie bitte leiser sprechen?', 'Would you please speak more quietly?'],
          ['Hätten Sie...?', 'Hätten Sie einen Moment Zeit?', 'Would you have a moment?'],
          ['Dürfte ich...?', 'Dürfte ich das Fenster öffnen?', 'Might I open the window?'],
          ['Ich hätte gern...', 'Ich hätte gern einen Tisch für zwei.', 'I would like a table for two.'],
        ],
      },
      {
        id: 'ch61-table-02',
        title: 'Wish constructions',
        columns: ['Pattern', 'Example', 'English'],
        rows: [
          ['Ich wünschte, + K2', 'Ich wünschte, ich hätte mehr Zeit.', 'I wish I had more time.'],
          ['Ich wollte, + K2', 'Ich wollte, ich wäre schon zu Hause.', 'I wish I were home already.'],
          ['Ich wünschte, dass + K2', 'Ich wünschte, dass du hier wärest.', 'I wish that you were here.'],
          ['Wenn ich doch nur ... + K2 + !', 'Wenn ich doch nur mehr Geduld hätte!', 'If only I had more patience!'],
          ['Verb-first wish (no wenn) + doch + !', 'Hätte ich doch nur mehr Geduld!', 'If only I had more patience!'],
        ],
        note: 'Ich wünschte and Ich wollte are interchangeable in this construction; wollte does not mean "wanted" here.',
      },
      {
        id: 'ch61-table-03',
        title: 'sollte for advice, compared to other modals',
        columns: ['Form', 'Strength / meaning', 'Example', 'English'],
        rows: [
          ['könntest (du)', 'a mere option or suggestion', 'Du könntest früher schlafen gehen.', 'You could go to bed earlier.'],
          ['solltest (du)', 'a recommendation, everyday advice', 'Du solltest mehr Wasser trinken.', 'You should drink more water.'],
          ['müsstest (du)', 'stronger, near-obligation', 'Du müsstest eigentlich früher aufstehen.', 'You would really have to get up earlier.'],
          ['sollst (present indicative)', 'a reported instruction or rule, not advice', 'Du sollst pünktlich sein.', 'You are supposed to be on time.'],
        ],
      },
      {
        id: 'ch61-table-04',
        title: 'wenn-clause word order: with and without wenn',
        columns: ['With wenn', 'Without wenn (verb-first)', 'English'],
        rows: [
          ['Wenn ich Zeit hätte, würde ich kommen.', 'Hätte ich Zeit, würde ich kommen.', 'If I had time, I would come.'],
          ['Wenn du Zeit hättest, könntest du mitkommen.', 'Hättest du Zeit, könntest du mitkommen.', 'If you had time, you could come along.'],
          ['Wenn es regnen würde, blieben wir zu Hause.', 'Würde es regnen, blieben wir zu Hause.', 'If it rained, we would stay home.'],
          ['Wenn sie mehr Geld hätte, würde sie öfter reisen.', 'Hätte sie mehr Geld, würde sie öfter reisen.', 'If she had more money, she would travel more often.'],
        ],
        note: 'Dropping wenn is only possible if the clause\'s conjugated verb moves to the very front; the meaning never changes.',
      },
      {
        id: 'ch61-table-05',
        title: 'Meaning distinctions among Konjunktiv II modals',
        columns: ['Form', 'Core meaning', 'Example', 'English'],
        rows: [
          ['könnte', 'possibility / ability ("could")', 'Es könnte heute regnen.', 'It could rain today.'],
          ['müsste', 'strong probability, near-certainty ("must probably")', 'Er müsste bald hier sein.', 'He should be here soon.'],
          ['sollte', 'advice, mild expectation ("should")', 'Du solltest das nicht tun.', 'You should not do that.'],
          ['dürfte', 'cautious, hedged probability ("might well")', 'Das dürfte stimmen.', 'That is probably right.'],
          ['würde', 'general hypothetical action ("would")', 'Ich würde das nicht sagen.', 'I would not say that.'],
        ],
      },
    ],
    examples: [
      {
        german: 'Könnten Sie mir bitte helfen?',
        english: 'Could you please help me?',
        highlight: ['Könnten'],
        explanation: 'A formal polite request built on the synthetic Konjunktiv II form of können.',
      },
      {
        german: 'Ich hätte gern einen Tisch für zwei, bitte.',
        english: 'I would like a table for two, please.',
        highlight: ['hätte gern'],
        explanation: 'Ich hätte gern... is a fixed, everyday polite pattern for requesting something.',
      },
      {
        german: 'Ich wünschte, ich hätte mehr Zeit.',
        english: 'I wish I had more time.',
        highlight: ['wünschte', 'hätte'],
        explanation: 'The wish-construction Ich wünschte, ... is always followed by a Konjunktiv II clause.',
      },
      {
        german: 'Ich wollte, ich wäre schon im Urlaub.',
        english: 'I wish I were already on vacation.',
        highlight: ['wollte', 'wäre'],
        explanation: 'Ich wollte, ... functions here exactly like Ich wünschte, ...; it does not mean "I wanted".',
      },
      {
        german: 'Wenn ich reich wäre, würde ich um die Welt reisen.',
        english: 'If I were rich, I would travel around the world.',
        highlight: ['wäre', 'würde'],
        explanation: 'An unreal wenn-condition: both the wenn-clause and the main clause are in Konjunktiv II.',
      },
      {
        german: 'Wäre ich reich, würde ich um die Welt reisen.',
        english: 'If I were rich, I would travel around the world.',
        highlight: ['Wäre'],
        explanation: 'The same meaning as the sentence above, with wenn dropped and wäre moved to the front of the clause.',
      },
      {
        german: 'Du solltest mehr schlafen.',
        english: 'You should sleep more.',
        highlight: ['solltest'],
        explanation: 'sollte is the standard, everyday way to give advice — softer than müsste, and clearly different from present-tense sollst.',
      },
      {
        german: 'An deiner Stelle würde ich das nicht machen.',
        english: 'In your place, I would not do that.',
        highlight: ['würde'],
        explanation: 'A hypothetical statement of advice that does not need a wenn-clause at all.',
      },
      {
        german: 'Wenn du mehr üben würdest, würdest du besser sprechen.',
        english: 'If you practiced more, you would speak better.',
        highlight: ['würdest', 'würdest'],
        explanation: 'üben and sprechen have no natural synthetic Konjunktiv II form, so würde + infinitive is used in both clauses.',
      },
      {
        german: 'Hätten Sie kurz Zeit für mich?',
        english: 'Would you have a moment for me?',
        highlight: ['Hätten'],
        explanation: 'A formal polite request built on the synthetic Konjunktiv II form of haben.',
      },
      {
        german: 'Wenn ich du wäre, würde ich das Angebot annehmen.',
        english: 'If I were you, I would accept the offer.',
        highlight: ['wäre', 'würde'],
        explanation: 'A common hypothetical-advice pattern: Wenn ich du wäre, ... imagines being in someone else\'s position.',
      },
      {
        german: 'Das wäre schön, wenn du mitkommen könntest.',
        english: 'It would be nice if you could come along.',
        highlight: ['wäre', 'könntest'],
        explanation: 'Two synthetic Konjunktiv II forms, wäre and könntest, combine naturally in the same sentence.',
      },
      {
        german: 'Wenn ich doch nur mehr Geduld hätte!',
        english: 'If only I had more patience!',
        highlight: ['doch nur', 'hätte'],
        explanation: 'An emphatic wish exclamation, built the same way as an unreal wenn-clause but standing alone.',
      },
      {
        german: 'Er müsste eigentlich schon zu Hause sein.',
        english: 'He should really be home by now.',
        highlight: ['müsste'],
        explanation: 'müsste expresses a strong probability here, not advice — a meaning distinct from sollte.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich wünsche, ich hätte mehr Zeit.',
        correct: 'Ich wünschte, ich hätte mehr Zeit.',
        explanation: 'The wish-construction always uses wünschte, the Konjunktiv II / simple-past form, even though the wish concerns the present — the present-tense wünsche is not used this way.',
      },
      {
        incorrect: 'Wenn ich Zeit hätte, ich komme dich besuchen.',
        correct: 'Wenn ich Zeit hätte, würde ich dich besuchen.',
        explanation: 'Both clauses of an unreal wenn-condition must be in Konjunktiv II; a present-tense main clause breaks the unreal meaning.',
      },
      {
        incorrect: 'Ich Zeit hätte, würde ich kommen.',
        correct: 'Hätte ich Zeit, würde ich kommen.',
        explanation: 'Dropping wenn requires moving the conjugated verb to the very front of the clause; simply deleting wenn while keeping normal subject-verb order is ungrammatical.',
      },
      {
        incorrect: 'Du sollst mehr Wasser trinken, das wäre gut für dich.',
        correct: 'Du solltest mehr Wasser trinken, das wäre gut für dich.',
        explanation: 'sollst is present-tense sollen and sounds like an order or reported instruction; solltest (Konjunktiv II) is the natural, softer form for giving advice.',
      },
      {
        incorrect: 'Du müsstest das nicht tun, wenn du nicht willst.',
        correct: 'Du solltest das nicht tun, wenn du nicht willst.',
        explanation: 'müsstest signals a strong near-obligation, which is too forceful for gentle advice; solltest is the standard form for a mild recommendation.',
      },
      {
        incorrect: 'Könnten Sie mir bitte das Salz gibt?',
        correct: 'Könnten Sie mir bitte das Salz geben?',
        explanation: 'After a modal in Konjunktiv II (Könnten Sie), the main verb stays as a plain infinitive at the end of the clause, never a conjugated form.',
      },
    ],
    remember: [
      'Konjunktiv II has four everyday jobs: softening requests, expressing wishes, describing hypothetical situations, and giving advice with sollte.',
      'Wishes use Ich wünschte, ... or Ich wollte, ... (both mean "I wish"), followed by a Konjunktiv II clause, with or without dass.',
      'An unreal wenn-condition needs Konjunktiv II in both the wenn-clause and the main clause: Wenn ich Zeit hätte, würde ich kommen.',
      'wenn can be dropped if the conjugated verb of that clause moves to the very front instead: Hätte ich Zeit, würde ich kommen. — identical meaning, slightly more emphatic style.',
      'sollte is the everyday way to give advice ("should"); it is softer than müsste ("would really have to") and clearly different from the present-tense sollst ("is supposed to", a rule or order).',
      'Small differences in which modal you choose change the meaning: könnte = possibility, müsste = strong probability, sollte = advice, dürfte = cautious probability, würde = general hypothetical action.',
      'Real, likely conditions (Wenn es regnet, nehme ich einen Schirm.) stay in the present indicative; only unreal or hypothetical conditions switch to Konjunktiv II.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 28,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch61-ex-01',
      chapterNumber: 61,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'polite-request'],
      instruction: 'Identify what function this sentence performs.',
      prompt: 'Könnten Sie mir bitte helfen?',
      options: [
        { id: 'a', text: 'A polite request' },
        { id: 'b', text: 'A statement of fact' },
        { id: 'c', text: 'A wish' },
        { id: 'd', text: 'A simple-past narrative' },
      ],
      correctOptionId: 'a',
      explanation: 'Könnten Sie...? softens a request into a polite question rather than stating a fact, wishing, or narrating the past.',
    },
    {
      id: 'ch61-ex-02',
      chapterNumber: 61,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'wish-construction'],
      instruction: 'Choose the correct Konjunktiv II form to complete the wish.',
      prompt: 'Ich wünschte, ich ___ mehr Zeit.',
      options: [
        { id: 'a', text: 'hätte' },
        { id: 'b', text: 'habe' },
        { id: 'c', text: 'hatte' },
        { id: 'd', text: 'haben' },
      ],
      correctOptionId: 'a',
      explanation: 'A wish introduced by Ich wünschte, ... always continues with a Konjunktiv II form; hätte is the synthetic Konjunktiv II of haben.',
    },
    {
      id: 'ch61-ex-03',
      chapterNumber: 61,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'wish-construction'],
      instruction: 'Choose the correct Konjunktiv II form to complete the wish.',
      prompt: 'Ich wollte, ich ___ schon zu Hause.',
      options: [
        { id: 'a', text: 'wäre' },
        { id: 'b', text: 'bin' },
        { id: 'c', text: 'war' },
        { id: 'd', text: 'sei' },
      ],
      correctOptionId: 'a',
      explanation: 'Ich wollte, ... functions like Ich wünschte, ... and requires a Konjunktiv II form; wäre is the synthetic Konjunktiv II of sein.',
    },
    {
      id: 'ch61-ex-04',
      chapterNumber: 61,
      order: 4,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'sollte-advice'],
      instruction: 'Choose the correct form for giving advice.',
      prompt: 'Du ___ mehr Wasser trinken.',
      options: [
        { id: 'a', text: 'solltest' },
        { id: 'b', text: 'sollst' },
        { id: 'c', text: 'wolltest' },
        { id: 'd', text: 'könntest' },
      ],
      correctOptionId: 'a',
      explanation: 'solltest is the Konjunktiv II du-form of sollen, the everyday way to give a recommendation.',
    },
    {
      id: 'ch61-ex-05',
      chapterNumber: 61,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'sollte-advice', 'meaning-distinction'],
      instruction: 'Choose the most natural way to say this in German.',
      prompt: 'You should call your mother.',
      options: [
        { id: 'a', text: 'Du solltest deine Mutter anrufen.' },
        { id: 'b', text: 'Du musst deine Mutter anrufen.' },
        { id: 'c', text: 'Du kannst deine Mutter anrufen.' },
        { id: 'd', text: 'Du rufst deine Mutter an.' },
      ],
      correctOptionId: 'a',
      explanation: 'Gentle advice ("should") is expressed with sollte; musst is a stronger obligation, kannst is mere ability, and rufst an is a plain present-tense statement.',
    },
    {
      id: 'ch61-ex-06',
      chapterNumber: 61,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'unreal-condition', 'wenn-clause'],
      instruction: 'Choose the correct form for the main clause of this unreal condition.',
      prompt: 'Wenn ich Zeit hätte, ___ ich dich besuchen.',
      options: [
        { id: 'a', text: 'würde' },
        { id: 'b', text: 'werde' },
        { id: 'c', text: 'wurde' },
        { id: 'd', text: 'würdest' },
      ],
      correctOptionId: 'a',
      explanation: 'An unreal wenn-condition needs Konjunktiv II in both clauses; würde is the correct ich-form of the würde-construction.',
    },
    {
      id: 'ch61-ex-07',
      chapterNumber: 61,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'wenn-clause', 'word-order'],
      instruction: 'Choose the sentence with the same meaning, but without wenn.',
      prompt: 'Wenn ich Geld hätte, würde ich reisen.',
      options: [
        { id: 'a', text: 'Hätte ich Geld, würde ich reisen.' },
        { id: 'b', text: 'Ich hätte Geld, würde ich reisen.' },
        { id: 'c', text: 'Geld hätte ich, würde ich reisen.' },
        { id: 'd', text: 'Würde ich Geld hätte, reisen ich.' },
      ],
      correctOptionId: 'a',
      explanation: 'Dropping wenn moves the conjugated verb hätte to the very front of the clause; the main clause stays unchanged.',
    },
    {
      id: 'ch61-ex-08',
      chapterNumber: 61,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'meaning-distinction'],
      instruction: 'Choose the form that expresses a mere possibility.',
      prompt: 'Es ___ heute regnen.',
      options: [
        { id: 'a', text: 'könnte' },
        { id: 'b', text: 'würde' },
        { id: 'c', text: 'sollte' },
        { id: 'd', text: 'müsste' },
      ],
      correctOptionId: 'a',
      explanation: 'könnte expresses possibility ("it could rain"); würde would need a further condition, sollte would mean advice, and müsste would mean strong probability.',
    },
    {
      id: 'ch61-ex-09',
      chapterNumber: 61,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'meaning-distinction'],
      instruction: 'Choose the form that expresses a strong probability, not advice.',
      prompt: 'Er ___ bald hier sein.',
      options: [
        { id: 'a', text: 'müsste' },
        { id: 'b', text: 'sollte' },
        { id: 'c', text: 'könnte' },
        { id: 'd', text: 'dürfte' },
      ],
      correctOptionId: 'a',
      explanation: 'müsste expresses a near-certain probability ("he should/must be here soon"), distinct from sollte (advice) or könnte (mere possibility).',
    },
    {
      id: 'ch61-ex-10',
      chapterNumber: 61,
      order: 10,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'polite-request', 'register'],
      instruction: 'Choose the most polite way to ask a stranger for the time.',
      prompt: 'You want to politely ask a stranger what time it is.',
      options: [
        { id: 'a', text: 'Könnten Sie mir bitte sagen, wie spät es ist?' },
        { id: 'b', text: 'Wie spät ist es?' },
        { id: 'c', text: 'Sag mir, wie spät es ist!' },
        { id: 'd', text: 'Du musst mir sagen, wie spät es ist.' },
      ],
      correctOptionId: 'a',
      explanation: 'Könnten Sie...? is the formal, polite request pattern appropriate for a stranger; the other options are either too blunt or use the informal du.',
    },
    {
      id: 'ch61-ex-11',
      chapterNumber: 61,
      order: 11,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'polite-request', 'register'],
      dialogue: [
        { speaker: 'Anna', german: 'Gib mir mal das Salz!', english: 'Give me the salt!' },
        { speaker: 'Ben', german: 'Anna, das klingt ziemlich direkt. Frag doch höflicher!', english: 'Anna, that sounds pretty blunt. Ask more politely!' },
      ],
      instruction: 'Choose the more polite reformulation of Anna\'s request.',
      prompt: 'Wie könnte Anna ihre Bitte höflicher formulieren?',
      options: [
        { id: 'a', text: 'Könntest du mir das Salz geben?' },
        { id: 'b', text: 'Du gibst mir das Salz.' },
        { id: 'c', text: 'Ich will das Salz.' },
        { id: 'd', text: 'Salz her!' },
      ],
      correctOptionId: 'a',
      explanation: 'Könntest du...? softens the same request into a polite question, exactly what Ben is asking Anna to do.',
    },
    {
      id: 'ch61-ex-12',
      chapterNumber: 61,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wish-construction'],
      dialogue: [
        { speaker: 'Tim', german: 'Ich habe leider kein Auto.', english: 'Unfortunately, I do not have a car.' },
        { speaker: 'Tim', german: 'Das ist echt mühsam ohne Auto.', english: 'It is really tough without a car.' },
      ],
      instruction: 'Choose the response that expresses a wish.',
      prompt: 'Lea möchte antworten und einen Wunsch ausdrücken (sie hätte auch gern ein Auto). Welche Antwort passt?',
      options: [
        { id: 'a', text: 'Ich wünschte, ich hätte auch ein Auto.' },
        { id: 'b', text: 'Ich habe auch kein Auto.' },
        { id: 'c', text: 'Ich werde ein Auto haben.' },
        { id: 'd', text: 'Ich hatte auch ein Auto.' },
      ],
      correctOptionId: 'a',
      explanation: 'Ich wünschte, ich hätte... is the wish-construction; the other options merely state facts or plans, without expressing a contrary-to-fact wish.',
    },
    {
      id: 'ch61-ex-13',
      chapterNumber: 61,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'real-vs-unreal-condition'],
      instruction: 'Choose the sentence describing a realistic, likely condition, not a hypothetical one.',
      prompt: 'Which sentence describes a realistic, likely condition rather than a hypothetical one?',
      options: [
        { id: 'a', text: 'Wenn es regnet, nehme ich einen Schirm.' },
        { id: 'b', text: 'Wenn ich ein Vogel wäre, würde ich fliegen.' },
        { id: 'c', text: 'Wenn ich reich wäre, würde ich reisen.' },
        { id: 'd', text: 'Wenn ich mehr Zeit hätte, würde ich mehr lesen.' },
      ],
      correctOptionId: 'a',
      explanation: 'Wenn es regnet, nehme ich einen Schirm. is in the present indicative in both clauses — a real, open condition; the other options use Konjunktiv II for unreal or impossible situations.',
    },
    {
      id: 'ch61-ex-14',
      chapterNumber: 61,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'meaning-distinction'],
      instruction: 'Choose the sentence that is a request, not a wish.',
      prompt: 'Which sentence is a request rather than a wish?',
      options: [
        { id: 'a', text: 'Könntest du mir helfen?' },
        { id: 'b', text: 'Ich wünschte, du könntest mir helfen.' },
        { id: 'c', text: 'Ich wollte, du wärst hier.' },
        { id: 'd', text: 'Wäre ich doch nicht so müde!' },
      ],
      correctOptionId: 'a',
      explanation: 'Könntest du mir helfen? directly asks for help; the other sentences all express a wish about a state that is not currently true.',
    },
    {
      id: 'ch61-ex-15',
      chapterNumber: 61,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'sollte-advice', 'register'],
      dialogue: [
        { speaker: 'Patientin', german: 'Ich habe seit Tagen Kopfschmerzen und schlafe schlecht.', english: 'I have had headaches for days and I am sleeping badly.' },
        { speaker: 'Patientin', german: 'Was denken Sie, woran das liegen könnte?', english: 'What do you think could be causing that?' },
      ],
      instruction: 'Choose the doctor\'s most likely piece of advice.',
      prompt: 'Was sagt der Arzt am ehesten als Ratschlag?',
      options: [
        { id: 'a', text: 'Sie sollten mehr trinken und sich ausruhen.' },
        { id: 'b', text: 'Sie müssen sofort operiert werden.' },
        { id: 'c', text: 'Sie können vielleicht mehr trinken.' },
        { id: 'd', text: 'Sie trinken mehr und ruhen sich aus.' },
      ],
      correctOptionId: 'a',
      explanation: 'Sollten (the Sie-form of sollte) is the natural, mild register for medical advice; the other options are either alarmingly strong, too vague, or a plain factual statement.',
    },
    {
      id: 'ch61-ex-16',
      chapterNumber: 61,
      order: 16,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wish-construction', 'word-order'],
      instruction: 'Choose the grammatically correct wish exclamation without wenn.',
      prompt: 'Choose the grammatically correct wish exclamation (no wenn).',
      options: [
        { id: 'a', text: 'Hätte ich doch mehr Geduld!' },
        { id: 'b', text: 'Ich hätte doch mehr Geduld!' },
        { id: 'c', text: 'Doch ich hätte mehr Geduld!' },
        { id: 'd', text: 'Mehr Geduld hätte ich doch!' },
      ],
      correctOptionId: 'a',
      explanation: 'Dropping wenn from a wish exclamation requires the conjugated verb hätte to move to the very front of the clause.',
    },
    {
      id: 'ch61-ex-17',
      chapterNumber: 61,
      order: 17,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'meaning-distinction'],
      instruction: 'Choose what dürfte expresses in this sentence.',
      prompt: '"Das dürfte stimmen." — what does dürfte express here?',
      options: [
        { id: 'a', text: 'cautious probability ("that is probably right")' },
        { id: 'b', text: 'permission ("that is allowed to be right")' },
        { id: 'c', text: 'strong obligation ("that must be right")' },
        { id: 'd', text: 'a polite request' },
      ],
      correctOptionId: 'a',
      explanation: 'In this use, dürfte is a hedged, cautious way of asserting probability, not permission, obligation, or a request.',
    },
    {
      id: 'ch61-ex-18',
      chapterNumber: 61,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'wish-construction'],
      instruction: 'Write the missing Konjunktiv II form. Capitalisation is not checked.',
      prompt: 'Ich wünschte, ich ___ mehr Geld. (haben, Konjunktiv II)',
      acceptedAnswers: ['hätte'],
      answerMode: 'caseInsensitive',
      placeholder: 'hätte',
      maxLength: 15,
      explanation: 'hätte is the synthetic Konjunktiv II form of haben, required after Ich wünschte, ....',
    },
    {
      id: 'ch61-ex-19',
      chapterNumber: 61,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'wish-construction'],
      instruction: 'Write the missing Konjunktiv II form. Capitalisation is not checked.',
      prompt: 'Ich wollte, ich ___ schon fertig. (sein, Konjunktiv II)',
      acceptedAnswers: ['wäre'],
      answerMode: 'caseInsensitive',
      placeholder: 'wäre',
      maxLength: 15,
      explanation: 'wäre is the synthetic Konjunktiv II form of sein, required after Ich wollte, ... in this wish-construction.',
    },
    {
      id: 'ch61-ex-20',
      chapterNumber: 61,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'sollte-advice'],
      instruction: 'Write the correct form of sollen (Konjunktiv II, advice) for du. Capitalisation is not checked.',
      prompt: 'Du ___ mehr schlafen. (sollen, Konjunktiv II)',
      acceptedAnswers: ['solltest'],
      answerMode: 'caseInsensitive',
      placeholder: 'solltest',
      maxLength: 15,
      explanation: 'solltest is the Konjunktiv II du-form of sollen, the standard way to give advice.',
    },
    {
      id: 'ch61-ex-21',
      chapterNumber: 61,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'unreal-condition', 'wenn-clause'],
      instruction: 'Write the missing Konjunktiv II form for the main clause. Capitalisation is not checked.',
      prompt: 'Wenn ich Zeit hätte, ___ ich dich besuchen. (werden, Konjunktiv II)',
      acceptedAnswers: ['würde'],
      answerMode: 'caseInsensitive',
      placeholder: 'würde',
      maxLength: 15,
      explanation: 'würde is the ich-form of the würde-construction, needed because besuchen has no natural synthetic form.',
    },
    {
      id: 'ch61-ex-22',
      chapterNumber: 61,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'unreal-condition', 'wenn-clause'],
      instruction: 'Write the missing Konjunktiv II form for the wenn-clause. Capitalisation is not checked.',
      prompt: 'Wenn ich mehr Geld ___, würde ich reisen. (haben, Konjunktiv II)',
      acceptedAnswers: ['hätte'],
      answerMode: 'caseInsensitive',
      placeholder: 'hätte',
      maxLength: 15,
      explanation: 'hätte is the synthetic Konjunktiv II form of haben, required in the wenn-clause of this unreal condition.',
    },
    {
      id: 'ch61-ex-23',
      chapterNumber: 61,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'polite-request'],
      instruction: 'Write the missing Konjunktiv II form to open a formal polite request. Capitalisation is not checked.',
      prompt: '___ Sie mir bitte das Fenster öffnen? (können, Konjunktiv II, höflich)',
      acceptedAnswers: ['Könnten', 'könnten'],
      answerMode: 'caseInsensitive',
      placeholder: 'Könnten',
      maxLength: 15,
      explanation: 'Könnten Sie...? is the formal polite-request pattern built on the synthetic Konjunktiv II of können.',
    },
    {
      id: 'ch61-ex-24',
      chapterNumber: 61,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'meaning-distinction'],
      instruction: 'Write the Konjunktiv II form expressing a strong probability, not advice. Capitalisation is not checked.',
      prompt: 'Er ___ bald ankommen. (müssen, Konjunktiv II – starke Wahrscheinlichkeit)',
      acceptedAnswers: ['müsste'],
      answerMode: 'caseInsensitive',
      placeholder: 'müsste',
      maxLength: 15,
      explanation: 'müsste expresses a strong, near-certain probability here, distinct from the advice-meaning of sollte.',
    },
    {
      id: 'ch61-ex-25',
      chapterNumber: 61,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'meaning-distinction'],
      instruction: 'Write the Konjunktiv II form expressing a cautious probability. Capitalisation is not checked.',
      prompt: 'Das ___ stimmen. (dürfen, Konjunktiv II – vorsichtige Vermutung)',
      acceptedAnswers: ['dürfte'],
      answerMode: 'caseInsensitive',
      placeholder: 'dürfte',
      maxLength: 15,
      explanation: 'dürfte expresses a cautious, hedged probability: "that is probably right".',
    },
    {
      id: 'ch61-ex-26',
      chapterNumber: 61,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'polite-request'],
      instruction: 'Rewrite the blunt command as a formal polite request using könnten. Capitalisation and punctuation are checked.',
      prompt: 'Öffnen Sie das Fenster! → höfliche Bitte mit könnten',
      acceptedAnswers: ['Könnten Sie das Fenster öffnen?', 'Könnten Sie das Fenster öffnen'],
      answerMode: 'normalized',
      placeholder: 'Könnten Sie ...?',
      maxLength: 50,
      explanation: 'Könnten Sie das Fenster öffnen? softens the imperative into a formal polite request.',
    },
    {
      id: 'ch61-ex-27',
      chapterNumber: 61,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'wish-construction'],
      instruction: 'Rewrite the factual statement as a wish using Ich wünschte. Capitalisation and punctuation are checked.',
      prompt: 'Ich habe kein Auto. → Wunsch mit Ich wünschte',
      acceptedAnswers: ['Ich wünschte, ich hätte ein Auto.', 'Ich wünschte, ich hätte ein Auto'],
      answerMode: 'normalized',
      placeholder: 'Ich wünschte, ich hätte ...',
      maxLength: 50,
      explanation: 'The factual statement Ich habe kein Auto. becomes the contrary-to-fact wish Ich wünschte, ich hätte ein Auto.',
    },
    {
      id: 'ch61-ex-28',
      chapterNumber: 61,
      order: 28,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'sollte-advice'],
      instruction: 'Rewrite the statement as advice using sollte. Capitalisation and punctuation are checked.',
      prompt: 'Er raucht zu viel. → Ratschlag mit sollte',
      acceptedAnswers: ['Er sollte weniger rauchen.', 'Er sollte weniger rauchen'],
      answerMode: 'normalized',
      placeholder: 'Er sollte ...',
      maxLength: 50,
      explanation: 'sollte turns the factual observation into a piece of gentle advice: Er sollte weniger rauchen.',
    },
    {
      id: 'ch61-ex-29',
      chapterNumber: 61,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wenn-clause', 'word-order'],
      instruction: 'Rewrite the sentence without wenn, moving the verb to the front of the clause. Capitalisation and punctuation are checked.',
      prompt: 'Wenn ich Zeit hätte, würde ich kommen. → ohne wenn',
      acceptedAnswers: ['Hätte ich Zeit, würde ich kommen.', 'Hätte ich Zeit, würde ich kommen'],
      answerMode: 'normalized',
      placeholder: 'Hätte ich Zeit, würde ich kommen.',
      maxLength: 50,
      explanation: 'Dropping wenn moves hätte to the very front of the clause; the main clause stays unchanged, and the meaning is identical.',
    },
    {
      id: 'ch61-ex-30',
      chapterNumber: 61,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'sentence-building', 'unreal-condition', 'wenn-clause'],
      instruction: 'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'wenn – sie – mehr Geld – haben (Konjunktiv II) – , – sie – öfter – reisen (Konjunktiv II mit würde)',
      acceptedAnswers: ['Wenn sie mehr Geld hätte, würde sie öfter reisen.'],
      answerMode: 'normalized',
      placeholder: 'Wenn sie mehr Geld hätte, würde sie öfter reisen.',
      maxLength: 70,
      explanation: 'haben becomes the synthetic hätte in the wenn-clause; reisen has no natural synthetic form, so it takes würde + infinitive.',
    },
    {
      id: 'ch61-ex-31',
      chapterNumber: 61,
      order: 31,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wenn-clause', 'word-order'],
      instruction: 'Rewrite the sentence without wenn, moving the verb to the front of the clause. Capitalisation and punctuation are checked.',
      prompt: 'Wenn sie mehr Geld hätte, würde sie öfter reisen. → ohne wenn',
      acceptedAnswers: ['Hätte sie mehr Geld, würde sie öfter reisen.', 'Hätte sie mehr Geld, würde sie öfter reisen'],
      answerMode: 'normalized',
      placeholder: 'Hätte sie mehr Geld, würde sie öfter reisen.',
      maxLength: 70,
      explanation: 'Dropping wenn moves hätte to the very front of the clause; the meaning stays exactly the same.',
    },
    {
      id: 'ch61-ex-32',
      chapterNumber: 61,
      order: 32,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'sentence-building', 'wish-construction'],
      instruction: 'Build a complete wish exclamation from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'wenn – ich – doch nur – mehr Geduld – haben (Konjunktiv II) – !',
      acceptedAnswers: ['Wenn ich doch nur mehr Geduld hätte!'],
      answerMode: 'normalized',
      placeholder: 'Wenn ich doch nur mehr Geduld hätte!',
      maxLength: 50,
      explanation: 'haben becomes the synthetic hätte, and wenn ... doch nur ... ! is the emphatic wish-exclamation pattern.',
    },
    {
      id: 'ch61-ex-33',
      chapterNumber: 61,
      order: 33,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'wish-construction'],
      instruction: 'Combine into a wish using Ich wünschte, dass .... Capitalisation and punctuation are checked.',
      prompt: 'Du bist nicht hier. → Wunsch mit Ich wünschte, dass ...',
      acceptedAnswers: [
        'Ich wünschte, dass du hier wärest.',
        'Ich wünschte, dass du hier wärest',
        'Ich wünschte, dass du hier wärst.',
        'Ich wünschte, dass du hier wärst',
      ],
      answerMode: 'normalized',
      placeholder: 'Ich wünschte, dass du hier wärest.',
      maxLength: 50,
      explanation: 'bist becomes the synthetic Konjunktiv II wärest (or the common contraction wärst), turning the fact into a wish.',
    },
  ],
};
