import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter036: ChapterDefinition = {
  id: 'chapter-036',
  number: 36,
  slug: 'two-way-prepositions-with-dative-or-accusative',
  title: 'Two-Way Prepositions with Dative or Accusative',
  germanTitle: 'Wechselpräpositionen: Dativ oder Akkusativ',
  level: 'A2',
  section: 'prepositions-1',
  objective:
    'Distinguish location from destination with the nine two-way prepositions (an, auf, hinter, in, neben, über, unter, vor, zwischen) by asking wo? or wohin?, choose the dative for a static location and the accusative for a movement or destination, pair the right case with static verbs like stehen/liegen/sitzen versus placement verbs like stellen/legen/setzen, and use contractions such as im/ins and am/ans correctly.',
  prerequisites: [17, 18, 35],
  estimatedMinutes: 25,
  tags: [
    'two-way prepositions',
    'wechselpräpositionen',
    'dative',
    'accusative',
    'wo vs wohin',
    'location vs destination',
    'case',
  ],
  explanation: {
    introduction: [
      'You already know that an, auf, hinter, in, neben, über, unter, vor, and zwischen can take the dative to describe where something is located (Chapter 35). But these same nine prepositions are called "two-way" prepositions because they can also take the accusative — when the sentence describes movement toward a destination instead of a fixed location.',
      'The choice between the two cases is not random: it depends entirely on the question the sentence answers. Wo? (where?) asks about a static location and takes the dative. Wohin? (where to?) asks about a destination or a change of position and takes the accusative. Learning to ask yourself "wo or wohin?" before choosing the case is the single most useful habit this chapter can give you.',
    ],
    rules: [
      {
        id: 'ch36-rule-01',
        heading: 'Nine prepositions, two possible cases',
        paragraphs: [
          'An, auf, hinter, in, neben, über, unter, vor, and zwischen are called two-way (or "Wechsel-") prepositions because, unlike purely dative or purely accusative prepositions, they can govern either case depending on meaning.',
          'The preposition itself never changes; only the case of the article and noun after it changes, signalling whether the sentence describes a fixed position or a movement toward a new position.',
        ],
      },
      {
        id: 'ch36-rule-02',
        heading: 'wo? asks about location — use the dative',
        paragraphs: [
          'When a sentence answers the question wo? (where?), it describes something that is simply in place, with no movement involved, and the two-way preposition takes the dative.',
          'Wo ist die Katze? — Die Katze liegt auf dem Sofa. (Where is the cat? — The cat is lying on the sofa.) The cat is not moving anywhere; it is already there, so dem Sofa is dative.',
        ],
      },
      {
        id: 'ch36-rule-03',
        heading: 'wohin? asks about destination — use the accusative',
        paragraphs: [
          'When a sentence answers the question wohin? (where to?), it describes a movement or a change of position that ends at a particular place, and the two-way preposition takes the accusative.',
          'Wohin legst du die Decke? — Ich lege die Decke auf das Sofa. (Where are you putting the blanket? — I am putting the blanket onto the sofa.) The blanket is moving from somewhere else onto the sofa, so das Sofa is accusative.',
        ],
      },
      {
        id: 'ch36-rule-04',
        heading: 'Static verbs signal location, so they take the dative',
        paragraphs: [
          'Certain verbs describe a fixed position rather than a movement: stehen (to stand), liegen (to lie), sitzen (to sit), hängen (to hang, intransitive: "to be hanging"), and sein (to be). These verbs almost always pair with the wo?/dative reading of a two-way preposition.',
          'Der Teppich liegt vor dem Bett. (The rug is lying in front of the bed.) liegen describes where the rug already is, so vor takes the dative dem Bett.',
        ],
      },
      {
        id: 'ch36-rule-05',
        heading: 'Placement and movement verbs signal destination, so they take the accusative',
        paragraphs: [
          'Other verbs describe placing something somewhere or moving toward a place: stellen (to put/stand something up), legen (to lay something down), setzen (to set/put something, or sich setzen "to sit down"), hängen (transitive: "to hang something up"), gehen (to go), and fahren (to drive/go). These verbs almost always pair with the wohin?/accusative reading.',
          'Sie stellt den Teppich vor das Bett. (She puts the rug in front of the bed.) stellen describes an action that ends with the rug in a new place, so vor takes the accusative das Bett.',
          'Note that hängen has two forms: the intransitive, static hängen (hängt, hing, hat gehangen) meaning "to be hanging" pairs with the dative, while the transitive, active hängen (hängt, hängte, hat gehängt) meaning "to hang something up" pairs with the accusative.',
        ],
      },
      {
        id: 'ch36-rule-06',
        heading: 'The same preposition, two different cases',
        paragraphs: [
          'Because the preposition itself never changes form, the only visible signal of the case is the article (and sometimes a plural noun ending). This is why minimal pairs are the best way to learn this chapter: the same preposition, verb pair, and noun appear twice, once with each case.',
          'Das Bild hängt an der Wand. (The picture is hanging on the wall — location, dative.) versus Ich hänge das Bild an die Wand. (I am hanging the picture on the wall — destination, accusative.) Only the article changes, from der to die, but the meaning shifts from "it is already there" to "it is being moved there".',
        ],
      },
      {
        id: 'ch36-rule-07',
        heading: 'Watch the contractions: im/ins and am/ans',
        paragraphs: [
          'In and an regularly contract with the definite articles dem and das: in + dem = im, in + das = ins, an + dem = am, an + das = ans. These contracted forms are the normal, everyday German — the uncontracted forms sound stiff or overly formal.',
          'Die Kinder spielen im Garten. (in + dem, dative, location) versus Die Kinder laufen in den Garten. (accusative, destination — no contraction, because in does not contract with den or with feminine/plural articles.)',
        ],
      },
    ],
    tables: [
      {
        id: 'ch36-table-01',
        title: 'Two-way prepositions: location (wo? + dative) vs. destination (wohin? + accusative)',
        columns: ['Preposition', 'Location — wo? (dative)', 'Destination — wohin? (accusative)'],
        columnCases: [null, 'dative', 'accusative'],
        rows: [
          ['an', 'am Fenster (at the window)', 'ans Fenster (to the window)'],
          ['auf', 'auf dem Tisch (on the table)', 'auf den Tisch (onto the table)'],
          ['hinter', 'hinter dem Haus (behind the house)', 'hinter das Haus (behind the house)'],
          ['in', 'im Haus (in the house)', 'ins Haus (into the house)'],
          ['neben', 'neben dem Bett (next to the bed)', 'neben das Bett (next to the bed)'],
          ['über', 'über dem Sofa (above the sofa)', 'über das Sofa (over the sofa)'],
          ['unter', 'unter dem Stuhl (under the chair)', 'unter den Stuhl (under the chair)'],
          ['vor', 'vor der Tür (in front of the door)', 'vor die Tür (in front of the door)'],
          ['zwischen', 'zwischen den Büchern (between the books)', 'zwischen die Bücher (between the books)'],
        ],
        note: 'The preposition never changes; only the case of the article (and, in the plural dative, the noun ending) shows whether the sentence describes a location or a destination.',
      },
      {
        id: 'ch36-table-02',
        title: 'Static verbs vs. placement/movement verbs',
        columns: ['Location verb (dative)', 'Movement verb (accusative)', 'English meaning'],
        rows: [
          ['stehen', 'stellen', 'to stand (be standing) / to put something upright'],
          ['liegen', 'legen', 'to lie (be lying) / to lay something down'],
          ['sitzen', 'setzen', 'to sit (be sitting) / to set or put something down'],
          [
            'hängen (hing, hat gehangen)',
            'hängen (hängte, hat gehängt)',
            'to hang (be hanging) / to hang something up',
          ],
          ['sein', 'gehen / fahren', 'to be (somewhere) / to go, drive (to somewhere)'],
        ],
        note: 'Learn each pair together: the left-hand verb describes a fixed position (dative), the right-hand verb describes an action that creates a new position (accusative).',
      },
    ],
    examples: [
      {
        german: 'Das Bild hängt an der Wand.',
        english: 'The picture is hanging on the wall.',
        highlight: ['der Wand'],
        explanation: 'hängen (intransitive) describes a fixed location, so an takes the dative: der Wand.',
      },
      {
        german: 'Ich hänge das Bild an die Wand.',
        english: 'I am hanging the picture on the wall.',
        highlight: ['die Wand'],
        explanation: 'hängen (transitive) describes an action that moves the picture to a new place, so an takes the accusative: die Wand.',
      },
      {
        german: 'Die Katze liegt auf dem Sofa.',
        english: 'The cat is lying on the sofa.',
        highlight: ['dem Sofa'],
        explanation: 'liegen is a static verb, so auf takes the dative dem Sofa.',
      },
      {
        german: 'Die Katze springt auf das Sofa.',
        english: 'The cat jumps onto the sofa.',
        highlight: ['das Sofa'],
        explanation: 'springen describes a movement toward a destination, so auf takes the accusative das Sofa.',
      },
      {
        german: 'Das Auto steht vor dem Haus.',
        english: 'The car is (parked) in front of the house.',
        highlight: ['dem Haus'],
        explanation: 'stehen is a static verb, so vor takes the dative dem Haus.',
      },
      {
        german: 'Er fährt das Auto vor das Haus.',
        english: 'He drives the car up in front of the house.',
        highlight: ['das Haus'],
        explanation: 'The car ends up in a new position, so vor takes the accusative das Haus.',
      },
      {
        german: 'Die Kinder spielen im Garten.',
        english: 'The children are playing in the garden.',
        highlight: ['im Garten'],
        explanation: 'spielen describes a location, so in takes the dative; in + dem contracts to im.',
      },
      {
        german: 'Die Kinder laufen in den Garten.',
        english: 'The children are running into the garden.',
        highlight: ['in den Garten'],
        explanation: 'laufen here describes a movement toward a destination, so in takes the accusative den Garten.',
      },
      {
        german: 'Der Schlüssel liegt unter dem Stuhl.',
        english: 'The key is lying under the chair.',
        highlight: ['dem Stuhl'],
        explanation: 'liegen is a static verb, so unter takes the dative dem Stuhl.',
      },
      {
        german: 'Die Katze läuft unter den Stuhl.',
        english: 'The cat runs under the chair.',
        highlight: ['den Stuhl'],
        explanation: 'laufen describes movement to a new position, so unter takes the accusative den Stuhl.',
      },
      {
        german: 'Wir sitzen zwischen den Bäumen.',
        english: 'We are sitting between the trees.',
        highlight: ['den Bäumen'],
        explanation: 'sitzen is a static verb; the plural dative of die Bäume is den Bäumen, with an added -n.',
      },
      {
        german: 'Stell den Tisch zwischen die Bäume!',
        english: 'Put the table between the trees!',
        highlight: ['die Bäume'],
        explanation: 'stellen describes placing something in a new spot, so zwischen takes the plural accusative die Bäume.',
      },
      {
        german: 'Das Poster hängt über dem Bett.',
        english: 'The poster hangs above the bed.',
        highlight: ['dem Bett'],
        explanation: 'hängen (intransitive) is static here, so über takes the dative dem Bett.',
      },
      {
        german: 'Häng das Poster über das Bett!',
        english: 'Hang the poster above the bed!',
        highlight: ['das Bett'],
        explanation: 'hängen (transitive) describes moving the poster into place, so über takes the accusative das Bett.',
      },
      {
        german: 'Er wartet neben der Tür.',
        english: 'He is waiting next to the door.',
        highlight: ['der Tür'],
        explanation: 'warten describes a fixed position, so neben takes the dative der Tür.',
      },
      {
        german: 'Stell dich neben die Tür!',
        english: 'Stand yourself next to the door!',
        highlight: ['die Tür'],
        explanation: 'sich stellen describes moving into a position, so neben takes the accusative die Tür.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich stelle das Buch auf dem Tisch.',
        correct: 'Ich stelle das Buch auf den Tisch.',
        explanation: 'stellen describes a movement toward a destination (wohin?), so auf takes the accusative den Tisch, not the dative dem Tisch.',
      },
      {
        incorrect: 'Das Buch liegt auf den Tisch.',
        correct: 'Das Buch liegt auf dem Tisch.',
        explanation: 'liegen describes a static location (wo?), so auf takes the dative dem Tisch, not the accusative den Tisch.',
      },
      {
        incorrect: 'Ich gehe in dem Supermarkt.',
        correct: 'Ich gehe in den Supermarkt.',
        explanation: 'gehen describes movement toward a destination (wohin?), so in takes the accusative den Supermarkt, not the dative dem Supermarkt.',
      },
      {
        incorrect: 'Wir hängen das Bild an der Wand.',
        correct: 'Wir hängen das Bild an die Wand.',
        explanation: 'hängen (transitive: placing the picture) describes a destination, so an takes the accusative die Wand, not the dative der Wand.',
      },
    ],
    remember: [
      'Ask wo? for location (dative) and wohin? for destination (accusative) with the nine two-way prepositions: an, auf, hinter, in, neben, über, unter, vor, zwischen.',
      'Static verbs — stehen, liegen, sitzen, hängen (intransitive), sein — usually pair with the wo?/dative reading.',
      'Placement and movement verbs — stellen, legen, setzen, hängen (transitive), gehen, fahren — usually pair with the wohin?/accusative reading.',
      'Watch the contractions: in + dem = im, in + das = ins, an + dem = am, an + das = ans.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch36-ex-01',
      chapterNumber: 36,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wo-vs-wohin', 'dative', 'an'],
      instruction: 'Choose the case that matches the question word wo?.',
      prompt: 'Wo hängt die Lampe? — Die Lampe hängt an ___ Decke. (die Decke, feminine)',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'dem' },
        { id: 'd', text: 'den' },
      ],
      correctOptionId: 'a',
      explanation: 'wo? asks about location, so the dative is needed; die Decke becomes der Decke in the dative.',
    },
    {
      id: 'ch36-ex-02',
      chapterNumber: 36,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wo-vs-wohin', 'accusative', 'auf'],
      instruction: 'Choose the case that matches the question word wohin?.',
      prompt: 'Wohin stellst du die Vase? — Ich stelle die Vase auf ___ Tisch. (der Tisch, masculine)',
      options: [
        { id: 'a', text: 'dem' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'der' },
        { id: 'd', text: 'das' },
      ],
      correctOptionId: 'b',
      explanation: 'wohin? asks about a destination, so the accusative is needed; der Tisch becomes den Tisch in the accusative.',
    },
    {
      id: 'ch36-ex-03',
      chapterNumber: 36,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wo-vs-wohin', 'dative', 'vor'],
      instruction: 'Choose the case that matches the question word wo?.',
      prompt: 'Wo wartet Anna? — Anna wartet vor ___ Tür. (die Tür, feminine)',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'dem' },
        { id: 'd', text: 'den' },
      ],
      correctOptionId: 'a',
      explanation: 'wo? asks about location, so the dative is needed; die Tür becomes der Tür in the dative.',
    },
    {
      id: 'ch36-ex-04',
      chapterNumber: 36,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['wo-vs-wohin', 'accusative', 'unter'],
      instruction: 'Choose the case that matches the question word wohin?.',
      prompt: 'Wohin legt er das Buch? — Er legt das Buch unter ___ Stuhl. (der Stuhl, masculine)',
      options: [
        { id: 'a', text: 'dem' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'der' },
        { id: 'd', text: 'das' },
      ],
      correctOptionId: 'b',
      explanation: 'wohin? asks about a destination, so the accusative is needed; der Stuhl becomes den Stuhl in the accusative.',
    },
    {
      id: 'ch36-ex-05',
      chapterNumber: 36,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['contraction', 'in', 'dative'],
      instruction: 'Choose the correct contracted form.',
      prompt: 'Die Kinder spielen ___ Garten. (in + dem, der Garten, static location)',
      options: [
        { id: 'a', text: 'im' },
        { id: 'b', text: 'ins' },
        { id: 'c', text: 'in den' },
        { id: 'd', text: 'an dem' },
      ],
      correctOptionId: 'a',
      explanation: 'spielen describes a location, so in takes the dative; in + dem contracts to im.',
    },
    {
      id: 'ch36-ex-06',
      chapterNumber: 36,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['contraction', 'in', 'accusative'],
      instruction: 'Choose the correct contracted form.',
      prompt: 'Wirf den Ball nicht ___ Wasser! (in + das, das Wasser, destination)',
      options: [
        { id: 'a', text: 'ins' },
        { id: 'b', text: 'im' },
        { id: 'c', text: 'in dem' },
        { id: 'd', text: 'in der' },
      ],
      correctOptionId: 'a',
      explanation: 'werfen (throw) describes movement into the water, so in takes the accusative; in + das contracts to ins.',
    },
    {
      id: 'ch36-ex-07',
      chapterNumber: 36,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['contraction', 'an', 'accusative'],
      instruction: 'Choose the correct contracted form.',
      prompt: 'Er stellt das Fahrrad ___ Haus. (an + das, das Haus, destination)',
      options: [
        { id: 'a', text: 'ans' },
        { id: 'b', text: 'am' },
        { id: 'c', text: 'an die' },
        { id: 'd', text: 'an der' },
      ],
      correctOptionId: 'a',
      explanation: 'stellen describes placing the bike against the house, so an takes the accusative; an + das contracts to ans.',
    },
    {
      id: 'ch36-ex-08',
      chapterNumber: 36,
      order: 8,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['contraction', 'an', 'dative'],
      instruction: 'Choose the correct contracted form.',
      prompt: 'Die Vögel sitzen ___ Fenster. (an + dem, das Fenster, static location)',
      options: [
        { id: 'a', text: 'am' },
        { id: 'b', text: 'ans' },
        { id: 'c', text: 'an das' },
        { id: 'd', text: 'an den' },
      ],
      correctOptionId: 'a',
      explanation: 'sitzen is a static verb, so an takes the dative; an + dem contracts to am.',
    },
    {
      id: 'ch36-ex-09',
      chapterNumber: 36,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['static-verb', 'dative', 'in'],
      instruction: 'Choose the case that matches the verb.',
      prompt: 'Die Bücher stehen ___ Regal. (das Regal, in + dem/das)',
      options: [
        { id: 'a', text: 'im' },
        { id: 'b', text: 'ins' },
        { id: 'c', text: 'in die' },
        { id: 'd', text: 'in den' },
      ],
      correctOptionId: 'a',
      explanation: 'stehen describes a static location, so in takes the dative; in + dem contracts to im.',
    },
    {
      id: 'ch36-ex-10',
      chapterNumber: 36,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['movement-verb', 'accusative', 'in'],
      instruction: 'Choose the case that matches the verb.',
      prompt: 'Stell die Bücher ___ Regal! (das Regal, in + dem/das)',
      options: [
        { id: 'a', text: 'ins' },
        { id: 'b', text: 'im' },
        { id: 'c', text: 'in dem' },
        { id: 'd', text: 'in der' },
      ],
      correctOptionId: 'a',
      explanation: 'stellen describes placing something in a new spot, so in takes the accusative; in + das contracts to ins.',
    },
    {
      id: 'ch36-ex-11',
      chapterNumber: 36,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['static-verb', 'dative', 'unter'],
      instruction: 'Choose the case that matches the verb.',
      prompt: 'Die Kinder sitzen ___ Baum. (der Baum)',
      options: [
        { id: 'a', text: 'dem' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'der' },
        { id: 'd', text: 'das' },
      ],
      correctOptionId: 'a',
      explanation: 'sitzen is a static verb, so unter takes the dative; der Baum becomes dem Baum in the dative.',
    },
    {
      id: 'ch36-ex-12',
      chapterNumber: 36,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['movement-verb', 'accusative', 'unter'],
      instruction: 'Choose the case that matches the verb.',
      prompt: 'Setz dich ___ Baum, es ist schattig dort! (der Baum)',
      options: [
        { id: 'a', text: 'dem' },
        { id: 'b', text: 'den' },
        { id: 'c', text: 'der' },
        { id: 'd', text: 'das' },
      ],
      correctOptionId: 'b',
      explanation: 'sich setzen describes moving into a position, so unter takes the accusative; der Baum becomes den Baum in the accusative.',
    },
    {
      id: 'ch36-ex-13',
      chapterNumber: 36,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['static-verb', 'dative', 'auf'],
      instruction: 'Write the correct article. Capitalisation is not checked.',
      prompt: 'Wo ist die Katze? Die Katze liegt auf ___ Bett. (das Bett)',
      acceptedAnswers: ['dem'],
      answerMode: 'caseInsensitive',
      placeholder: 'dem/den/der',
      maxLength: 10,
      explanation: 'liegen is a static verb (wo?), so auf takes the dative; das Bett becomes dem Bett in the dative.',
    },
    {
      id: 'ch36-ex-14',
      chapterNumber: 36,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['movement-verb', 'accusative', 'auf'],
      instruction: 'Write the correct article. Capitalisation is not checked.',
      prompt: 'Wohin legst du die Jacke? Ich lege die Jacke auf ___ Bett. (das Bett)',
      acceptedAnswers: ['das'],
      answerMode: 'caseInsensitive',
      placeholder: 'dem/den/das',
      maxLength: 10,
      explanation: 'legen signals a destination (wohin?), so auf takes the accusative; das Bett stays das Bett in the neuter accusative.',
    },
    {
      id: 'ch36-ex-15',
      chapterNumber: 36,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['static-verb', 'dative', 'vor'],
      instruction: 'Write the correct article. Capitalisation is not checked.',
      prompt: 'Wo steht das Auto? Das Auto steht vor ___ Haus. (das Haus)',
      acceptedAnswers: ['dem'],
      answerMode: 'caseInsensitive',
      placeholder: 'dem/das',
      maxLength: 10,
      explanation: 'stehen is a static verb (wo?), so vor takes the dative; das Haus becomes dem Haus in the dative.',
    },
    {
      id: 'ch36-ex-16',
      chapterNumber: 36,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['movement-verb', 'accusative', 'vor'],
      instruction: 'Write the correct article. Capitalisation is not checked.',
      prompt: 'Wohin fährt er das Auto? Er fährt das Auto vor ___ Haus. (das Haus)',
      acceptedAnswers: ['das'],
      answerMode: 'caseInsensitive',
      placeholder: 'dem/das',
      maxLength: 10,
      explanation: 'fahren here describes movement to a new position (wohin?), so vor takes the accusative; das Haus stays das Haus in the neuter accusative.',
    },
    {
      id: 'ch36-ex-17',
      chapterNumber: 36,
      order: 17,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['contraction', 'dative', 'in'],
      instruction: 'Complete the phrase with preposition, article and noun. Capitalisation is not checked.',
      prompt: 'Wo? (in / der Park) — Die Familie macht ein Picknick ___.',
      acceptedAnswers: ['im Park'],
      answerMode: 'caseInsensitive',
      placeholder: 'im Park',
      maxLength: 20,
      explanation: 'der Park is masculine, so its dative form is dem Park; in + dem contracts to im Park (location, wo?).',
    },
    {
      id: 'ch36-ex-18',
      chapterNumber: 36,
      order: 18,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['accusative', 'in', 'destination'],
      instruction: 'Complete the phrase with preposition, article and noun. Capitalisation is not checked.',
      prompt: 'Wohin? (in / der Park) — Die Kinder laufen ___.',
      acceptedAnswers: ['in den Park'],
      answerMode: 'caseInsensitive',
      placeholder: 'in den Park',
      maxLength: 25,
      explanation: 'der Park in the accusative is den Park; in does not contract with den, so the full form in den Park is used (destination, wohin?).',
    },
    {
      id: 'ch36-ex-19',
      chapterNumber: 36,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dative-plural', 'zwischen', 'static-verb'],
      instruction: 'Complete the phrase with preposition, article and noun. Capitalisation is not checked.',
      prompt: 'Wo? (zwischen / die Bäume, plural) — Das Zelt steht ___.',
      acceptedAnswers: ['zwischen den Bäumen'],
      answerMode: 'caseInsensitive',
      placeholder: 'zwischen den Bäumen',
      maxLength: 30,
      explanation: 'stehen is static; the plural die Bäume becomes den Bäumen in the dative, with an added -n on the noun.',
    },
    {
      id: 'ch36-ex-20',
      chapterNumber: 36,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['accusative-plural', 'zwischen', 'movement-verb'],
      instruction: 'Complete the phrase with preposition, article and noun. Capitalisation is not checked.',
      prompt: 'Wohin? (zwischen / die Bäume, plural) — Stell das Zelt ___!',
      acceptedAnswers: ['zwischen die Bäume'],
      answerMode: 'caseInsensitive',
      placeholder: 'zwischen die Bäume',
      maxLength: 30,
      explanation: 'stellen signals a destination; the plural accusative keeps die Bäume, without the extra -n used in the dative.',
    },
    {
      id: 'ch36-ex-21',
      chapterNumber: 36,
      order: 21,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'movement-verb', 'accusative'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich stelle das Buch auf dem Tisch.',
      acceptedAnswers: ['Ich stelle das Buch auf den Tisch.'],
      answerMode: 'normalized',
      placeholder: 'Ich stelle das Buch ...',
      maxLength: 60,
      explanation: 'stellen signals a destination (wohin?), so auf takes the accusative den Tisch, not the dative dem Tisch.',
    },
    {
      id: 'ch36-ex-22',
      chapterNumber: 36,
      order: 22,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'static-verb', 'dative'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Das Bild hängt an die Wand.',
      acceptedAnswers: ['Das Bild hängt an der Wand.'],
      answerMode: 'normalized',
      placeholder: 'Das Bild hängt ...',
      maxLength: 60,
      explanation: 'hängen (intransitive) describes where the picture already is (wo?), so an takes the dative der Wand, not the accusative die Wand.',
    },
    {
      id: 'ch36-ex-23',
      chapterNumber: 36,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'movement-verb', 'accusative'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Wir gehen in dem Supermarkt.',
      acceptedAnswers: ['Wir gehen in den Supermarkt.'],
      answerMode: 'normalized',
      placeholder: 'Wir gehen ...',
      maxLength: 60,
      explanation: 'gehen describes movement toward a destination (wohin?), so in takes the accusative den Supermarkt, not the dative dem Supermarkt.',
    },
    {
      id: 'ch36-ex-24',
      chapterNumber: 36,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'movement-verb', 'accusative'],
      instruction: 'Write a complete sentence using the accusative for the cue in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'er – legen – das Buch – der Tisch (wohin?, Akkusativ)',
      acceptedAnswers: ['Er legt das Buch auf den Tisch.', 'Er legt das Buch auf den Tisch'],
      answerMode: 'normalized',
      placeholder: 'Er legt das Buch ...',
      maxLength: 60,
      explanation: 'legen signals a destination (wohin?), so der Tisch becomes den Tisch in the accusative: Er legt das Buch auf den Tisch.',
    },
  ],
};
