import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter060: ChapterDefinition = {
  id: 'chapter-060',
  number: 60,
  slug: 'konjunktiv-ii-formation',
  title: 'Konjunktiv II: Formation',
  germanTitle: 'Konjunktiv II: Bildung',
  level: 'B1',
  section: 'verbs-3',
  objective:
    'Form Konjunktiv II with würde + infinitive for most verbs, and build and recognize the common synthetic (one-word) forms of sein, haben, and the modal verbs, applying the umlaut pattern (a/o/u → ä/ö/ü) and the -e/-est/-e/-en/-et/-en endings that mark strong-verb Konjunktiv II forms.',
  prerequisites: [5, 25, 54],
  estimatedMinutes: 30,
  tags: [
    'konjunktiv-ii',
    'subjunctive-ii',
    'wuerde-konstruktion',
    'wäre',
    'hätte',
    'modal-verbs',
    'umlaut',
    'verb-morphology',
    'präteritum-vs-konjunktiv',
  ],
  explanation: {
    introduction: [
      'German has a second, less common verb mood alongside the everyday indicative (the mood you have used in almost every sentence so far): the Konjunktiv II. You will meet what it is used for — polite requests, wishes, hypothetical situations, wenn-clauses — in the next chapter. This chapter has one job only: to teach you how the forms themselves are built, so that by the time you study their uses, the forms feel automatic rather than new.',
      'There are two ways to build a Konjunktiv II form. The first is analytic: würde (a conjugated helper form) plus the plain infinitive at the end of the clause, e.g. ich würde kommen (I would come). This pattern works for essentially any German verb and is the safe, everyday default. The second is synthetic: a single word that carries the Konjunktiv II meaning on its own, e.g. wäre (would be), hätte (would have), käme (would come). Synthetic forms exist for every verb historically, but in modern spoken and written German only a small, high-frequency set of them is still commonly used — the rest have been replaced by the würde-construction.',
      'The synthetic forms you do need are closely related to the simple past tense (Präteritum) you learned in chapter 54, but they are not identical to it. For weak verbs the two would look exactly the same, which is precisely why weak verbs switch to würde + infinitive instead. For strong verbs, Konjunktiv II adds its own ending set, -e/-est/-e/-en/-et/-en, to an umlauted version of the simple-past stem — a different set of endings from the plain simple-past endings you already know.',
    ],
    rules: [
      {
        id: 'ch60-rule-01',
        heading: 'würde + infinitive: the everyday default',
        paragraphs: [
          'For the great majority of German verbs, Konjunktiv II is built analytically: a conjugated form of würde plus the plain infinitive of the main verb, sent to the end of the clause — exactly like the modal-verb bracket you already know from chapter 5. Ich würde kommen (I would come). Du würdest arbeiten (You would work). Wir würden helfen (We would help).',
          'würde itself conjugates for person just like any finite verb: würde, würdest, würde, würden, würdet, würden. Only würde changes; the infinitive at the end never changes shape, no matter who the subject is: Er würde das Buch kaufen. Sie würden das Buch kaufen.',
          'This construction is not a shortcut or a simplification — it is the normal, unmarked way modern German expresses Konjunktiv II for verbs without a common one-word form, especially every weak verb: würde machen, würde kaufen, würde spielen, würde lernen. Interestingly, würde is itself nothing other than the synthetic Konjunktiv II form of werden (to become) — the same relationship English has between will and would.',
        ],
      },
      {
        id: 'ch60-rule-02',
        heading:
          'The synthetic forms that everyday German keeps: wäre, hätte, and the modals',
        paragraphs: [
          'A handful of very frequent verbs keep their one-word Konjunktiv II form in everyday German instead of switching to würde: sein → wäre, haben → hätte, and all six modal verbs — können → könnte, müssen → müsste, wollen → wollte, mögen → möchte, dürfen → dürfte, sollen → sollte.',
          'For these verbs, the synthetic form is strongly preferred, and würde + sein / würde + haben / würde + können and so on sound distinctly unnatural or even wrong to a native speaker. Ich wäre müde sounds right; Ich würde müde sein does not. Ich hätte gern einen Kaffee sounds right; Ich würde gern einen Kaffee haben does not.',
          'möchte deserves a special note: it comes historically from mögen, but in modern German it has become its own everyday word for "would like", used constantly in polite requests — Ich möchte einen Tee, bitte. — while the würde-construction with mögen (würde mögen) is essentially never used.',
        ],
      },
      {
        id: 'ch60-rule-03',
        heading: 'Building synthetic forms for strong verbs: umlaut + endings',
        paragraphs: [
          'For strong verbs that still keep a common synthetic Konjunktiv II form (kommen, gehen, geben, and a number of others), the form is built in two steps. First, take the simple-past stem and, if it contains the vowel a, o, or u, add an umlaut: a → ä, o → ö, u → ü. Second, add the personal ending -e / -est / -e / -en / -et / -en.',
          'kommen: simple past kam → umlauted stem käm- → käme, kämest, käme, kämen, kämet, kämen. finden: simple past fand → umlauted stem fänd- → fände, fändest, fände, fänden, fändet, fänden. geben: simple past gab → umlauted stem gäb- → gäbe.',
          'If the simple-past stem has no a, o, or u to umlaut, the stem stays exactly as it is and only the endings are added: gehen: simple past ging → ginge, gingest, ginge, gingen, ginget, gingen (no umlaut possible; i does not umlaut). bleiben: blieb → bliebe. schreiben: schrieb → schriebe.',
        ],
      },
      {
        id: 'ch60-rule-04',
        heading: 'A closed, memorizable list — not a productive rule',
        paragraphs: [
          'It is tempting to think the umlaut-plus-ending pattern can be applied freely to any strong verb, but in practice only a limited set of high-frequency strong verbs still has a synthetic Konjunktiv II form that sounds natural today: sein, haben, werden, gehen, kommen, sehen, geben, nehmen, fahren, bleiben, essen, trinken, lesen, schreiben, sprechen, finden, wissen, stehen, tun, waschen, rufen, and the six modals.',
          'For every other verb — bringen, denken, kennen, laufen, tragen, schlafen, treffen, beginnen, gewinnen, heißen, fliegen, ziehen, and any ordinary weak verb such as machen, kaufen, spielen, or lernen — modern German simply uses würde + infinitive. A synthetic form might technically be constructible, but it would sound archaic, overly literary, or simply wrong in everyday speech, so this course treats würde + infinitive as the only correct option for those verbs.',
          'The safest approach as a learner: actively use the synthetic forms only for the closed list above, and default to würde + infinitive for everything else. Nobody will ever fault you for using würde too often; using an obscure synthetic form will sound strange.',
        ],
      },
      {
        id: 'ch60-rule-05',
        heading: 'Konjunktiv II vs. the simple past: same family, different endings',
        paragraphs: [
          'Because Konjunktiv II grows out of the simple-past stem, the two forms are close relatives — but they are not built with the same endings. The simple past of a strong verb uses no ending at all for ich/er (kam, ging, fand); Konjunktiv II always adds -e for ich/er (käme, ginge, fände). The simple-past du-ending is -st (kamst); the Konjunktiv II du-ending is -est (kämest) — an extra e that chapter 54 did not use.',
          'For weak verbs, this distinction disappears: the simple past of kaufen is kaufte, and a synthetic Konjunktiv II would also come out as kaufte — completely identical in shape. This ambiguity is exactly why weak verbs abandon the synthetic form altogether and use würde kaufen instead, keeping the two moods unmistakably apart.',
          'The modals split down the middle: können, müssen, dürfen, and mögen (as möchte) have an umlautable stem vowel, so their Konjunktiv II clearly differs in shape from their simple past (konnte vs. könnte, musste vs. müsste, durfte vs. dürfte, mochte vs. möchte). wollen and sollen have no umlautable vowel in their stem, so — just like weak verbs — wollte and sollte look exactly the same whether the sentence is simple past or Konjunktiv II; only the surrounding sentence tells you which mood is meant.',
        ],
      },
      {
        id: 'ch60-rule-06',
        heading: 'Recognizing which mood a form belongs to',
        paragraphs: [
          'For strong verbs on the closed list, the umlaut is a reliable visual signal: any form with ä, ö, or ü where the simple past has a, o, or u is Konjunktiv II, not simple past. käme is unmistakably Konjunktiv II because kommen has no ä anywhere in its simple past (kam). The same holds for fände vs. fand, gäbe vs. gab, and so on.',
          'For weak verbs and for wollte/sollte, form alone cannot distinguish the moods — you must rely on context: a würde-construction nearby, a wenn-clause, or a clearly hypothetical, polite, or wishful meaning all point to Konjunktiv II, while a plain narrative context points to the simple past. Chapter 61 develops these contextual signals in full; here it is enough to notice that the ambiguity exists and to know that würde + infinitive is exactly the tool German uses to remove it.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch60-table-01',
        title: 'wäre and hätte — full conjugation',
        columns: ['Person', 'sein → wäre', 'haben → hätte', 'English'],
        rows: [
          ['ich', 'wäre', 'hätte', 'I would be / would have'],
          ['du', 'wärest', 'hättest', 'you would be / would have'],
          ['er/sie/es', 'wäre', 'hätte', 'he/she/it would be / would have'],
          ['wir', 'wären', 'hätten', 'we would be / would have'],
          ['ihr', 'wäret', 'hättet', 'you (pl.) would be / would have'],
          ['sie/Sie', 'wären', 'hätten', 'they/you (formal) would be / would have'],
        ],
      },
      {
        id: 'ch60-table-02',
        title: 'The six modal verbs — Konjunktiv II',
        columns: [
          'Infinitive',
          'ich / er-sie-es',
          'du',
          'wir / sie-Sie',
          'English (ich-form)',
        ],
        rows: [
          ['können', 'könnte', 'könntest', 'könnten', 'I could / would be able to'],
          ['müssen', 'müsste', 'müsstest', 'müssten', 'I would have to'],
          ['wollen', 'wollte', 'wolltest', 'wollten', 'I would want to'],
          ['mögen', 'möchte', 'möchtest', 'möchten', 'I would like to'],
          ['dürfen', 'dürfte', 'dürftest', 'dürften', 'I would be allowed to'],
          ['sollen', 'sollte', 'solltest', 'sollten', 'I should / ought to'],
        ],
        note: 'wollte and sollte look exactly like the simple past of wollen and sollen — their stem vowel cannot take an umlaut, so only context tells the moods apart.',
      },
      {
        id: 'ch60-table-03',
        title: 'Strong verbs with a common synthetic form (er/sie/es)',
        columns: ['Infinitive', 'Simple past (er)', 'Konjunktiv II (er)', 'English (K2)'],
        rows: [
          ['gehen', 'ging', 'ginge', 'would go'],
          ['kommen', 'kam', 'käme', 'would come'],
          ['sehen', 'sah', 'sähe', 'would see'],
          ['geben', 'gab', 'gäbe', 'would give'],
          ['nehmen', 'nahm', 'nähme', 'would take'],
          ['fahren', 'fuhr', 'führe', 'would drive'],
          ['bleiben', 'blieb', 'bliebe', 'would stay'],
          ['essen', 'aß', 'äße', 'would eat'],
          ['trinken', 'trank', 'tränke', 'would drink'],
          ['lesen', 'las', 'läse', 'would read'],
          ['schreiben', 'schrieb', 'schriebe', 'would write'],
          ['sprechen', 'sprach', 'spräche', 'would speak'],
          ['finden', 'fand', 'fände', 'would find'],
          ['stehen', 'stand', 'stünde', 'would stand'],
          ['tun', 'tat', 'täte', 'would do'],
          ['waschen', 'wusch', 'wüsche', 'would wash'],
          ['rufen', 'rief', 'riefe', 'would call'],
        ],
        note: 'Wherever the simple-past stem has a, o, or u, the Konjunktiv II stem umlauts it to ä, ö, or ü; verbs like gehen, bleiben, and schreiben have no umlautable vowel, so only the ending changes.',
      },
      {
        id: 'ch60-table-04',
        title: 'Synthetic form vs. würde-construction, side by side',
        columns: [
          'Verb',
          'Synthetic (ich)',
          'würde-construction (ich)',
          'Everyday preference',
        ],
        rows: [
          ['sein', 'wäre', 'würde sein', 'synthetic (wäre) — würde sein sounds wrong'],
          [
            'haben',
            'hätte',
            'würde haben',
            'synthetic (hätte) — würde haben sounds wrong',
          ],
          [
            'können',
            'könnte',
            'würde können',
            'synthetic (könnte) — würde können sounds wrong',
          ],
          [
            'kommen',
            'käme',
            'würde kommen',
            'either is fine; synthetic is common even in speech',
          ],
          [
            'gehen',
            'ginge',
            'würde gehen',
            'either is fine; würde gehen is more common in speech',
          ],
          [
            'finden',
            'fände',
            'würde finden',
            'either is fine; synthetic is slightly more formal',
          ],
          [
            'machen',
            '— (identical to simple past)',
            'würde machen',
            'würde-construction is the only natural option',
          ],
          [
            'kaufen',
            '— (identical to simple past)',
            'würde kaufen',
            'würde-construction is the only natural option',
          ],
        ],
      },
    ],
    examples: [
      {
        german: 'Ich würde jetzt gern nach Hause gehen.',
        english: 'I would like to go home now.',
        highlight: ['würde', 'gehen'],
        explanation:
          'The würde-construction: würde in position 2, the infinitive gehen at the end of the clause.',
      },
      {
        german: 'Das wäre wirklich toll!',
        english: 'That would be really great!',
        highlight: ['wäre'],
        explanation:
          'wäre is the synthetic Konjunktiv II form of sein — würde sein would sound wrong here.',
      },
      {
        german: 'Ich hätte gern einen Kaffee, bitte.',
        english: 'I would like a coffee, please.',
        highlight: ['hätte'],
        explanation:
          'hätte gern is a fixed, everyday polite pattern built on the synthetic form of haben.',
      },
      {
        german: 'Könntest du mir bitte helfen?',
        english: 'Could you help me, please?',
        highlight: ['Könntest'],
        explanation:
          'könntest is the du-form of the synthetic modal form könnte, from können.',
      },
      {
        german: 'Ich müsste eigentlich noch lernen.',
        english: 'I really ought to be studying still.',
        highlight: ['müsste'],
        explanation: 'müsste is the synthetic Konjunktiv II form of müssen.',
      },
      {
        german: 'Sie käme gern mit, aber sie hat heute keine Zeit.',
        english: 'She would like to come along, but she has no time today.',
        highlight: ['käme'],
        explanation:
          'käme is the synthetic form of kommen: kam → umlauted stem käm- → käme.',
      },
      {
        german: 'Wenn er mehr Geld hätte, würde er öfter reisen.',
        english: 'If he had more money, he would travel more often.',
        highlight: ['hätte', 'würde'],
        explanation:
          'A synthetic form (hätte) and a würde-construction (würde reisen) combine naturally in the same sentence.',
      },
      {
        german: 'Ich würde das Buch kaufen, wenn es billiger wäre.',
        english: 'I would buy the book if it were cheaper.',
        highlight: ['würde', 'kaufen', 'wäre'],
        explanation:
          'kaufen has no common synthetic form, so it takes würde + infinitive; billig-sein takes the synthetic wäre.',
      },
      {
        german: 'Wir fänden bestimmt eine Lösung, wenn wir zusammenarbeiten würden.',
        english: 'We would surely find a solution if we worked together.',
        highlight: ['fänden', 'würden'],
        explanation:
          'fänden is the wir-form of the synthetic form of finden: fand → fänd- → fänden.',
      },
      {
        german: 'Das würde ich so nicht machen.',
        english: 'I would not do it that way.',
        highlight: ['würde', 'machen'],
        explanation:
          'machen is a weak verb, so its Konjunktiv II is always würde + infinitive, never a one-word form.',
      },
      {
        german: 'Er ginge jetzt gern schwimmen, aber es regnet.',
        english: 'He would like to go swimming now, but it is raining.',
        highlight: ['ginge'],
        explanation:
          'ginge is the synthetic form of gehen: ging has no umlautable vowel, so only the ending -e is added.',
      },
      {
        german: 'Ich wüsste gern, wie das funktioniert.',
        english: 'I would like to know how that works.',
        highlight: ['wüsste'],
        explanation:
          'wüsste is the synthetic Konjunktiv II form of wissen: wusst- → wüsst- → wüsste.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich würde müde sein.',
        correct: 'Ich wäre müde.',
        explanation:
          'sein has a strongly preferred synthetic Konjunktiv II form, wäre; combining würde with sein sounds unnatural to native speakers.',
      },
      {
        incorrect: 'Ich würde das Auto haben.',
        correct: 'Ich hätte das Auto.',
        explanation:
          'haben also keeps its own synthetic form, hätte, instead of the würde-construction.',
      },
      {
        incorrect: 'Ich würde das machen können.',
        correct: 'Ich könnte das machen.',
        explanation:
          'Modal verbs use their own synthetic Konjunktiv II forms (könnte, müsste, dürfte, ...), not würde + modal infinitive.',
      },
      {
        incorrect: 'Ich kame gern mit.',
        correct: 'Ich käme gern mit.',
        explanation:
          'The synthetic Konjunktiv II stem of a strong verb needs its umlaut: kam becomes käm-, never kam-, before the -e ending.',
      },
      {
        incorrect: 'Wenn du Zeit hättest, kamst du gern mit.',
        correct: 'Wenn du Zeit hättest, kämest du gern mit.',
        explanation:
          'kamst is the simple-past du-form (indicative); the Konjunktiv II du-form is kämest, with the umlaut and the -est ending.',
      },
    ],
    remember: [
      'Konjunktiv II has two building patterns: würde + infinitive (analytic, works for almost any verb) and a one-word synthetic form (used only for a closed set of high-frequency verbs).',
      'würde + infinitive is the safe default, and the only correct option for weak verbs (würde machen, würde kaufen) and most other verbs outside the closed list.',
      'sein, haben, and the six modal verbs almost always use their synthetic forms instead of würde: wäre, hätte, könnte, müsste, wollte, möchte, dürfte, sollte.',
      'Synthetic strong-verb forms take the umlauted simple-past stem (a/o/u → ä/ö/ü, where possible) plus the endings -e/-est/-e/-en/-et/-en.',
      'This ending set is different from the plain simple-past strong endings: compare kamst (simple past, du) with kämest (Konjunktiv II, du).',
      'For weak verbs, and for wollte/sollte, the Konjunktiv II form looks identical to the simple past — würde + infinitive (or context, for wollte/sollte) is what keeps the two moods apart.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 90,
    requiredCorrectTextInputs: 26,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch60-ex-01',
      chapterNumber: 60,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'kommen'],
      instruction: 'Choose the correct würde-construction for the ich-form.',
      prompt: 'Ich ___ gern mitkommen.',
      options: [
        { id: 'a', text: 'würde' },
        { id: 'b', text: 'werde' },
        { id: 'c', text: 'wurde' },
        { id: 'd', text: 'würdest' },
      ],
      correctOptionId: 'a',
      explanation:
        'The Konjunktiv II ich-form of werden (the würde-helper) is würde; werde is present tense, wurde is simple past, würdest belongs to du.',
    },
    {
      id: 'ch60-ex-02',
      chapterNumber: 60,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sein'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of sein.',
      prompt: 'Ich ___ jetzt gern zu Hause.',
      options: [
        { id: 'a', text: 'wäre' },
        { id: 'b', text: 'war' },
        { id: 'c', text: 'bin' },
        { id: 'd', text: 'würde sein' },
      ],
      correctOptionId: 'a',
      explanation:
        'wäre is the synthetic Konjunktiv II form of sein for ich; war is simple past, bin is present, and würde sein is not used because sein has its own preferred synthetic form.',
    },
    {
      id: 'ch60-ex-03',
      chapterNumber: 60,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'haben'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of haben.',
      prompt: 'Du ___ bestimmt auch gern mehr Zeit.',
      options: [
        { id: 'a', text: 'hättest' },
        { id: 'b', text: 'hattest' },
        { id: 'c', text: 'hast' },
        { id: 'd', text: 'würdest haben' },
      ],
      correctOptionId: 'a',
      explanation:
        'hättest is the synthetic Konjunktiv II du-form of haben; hattest is simple past, hast is present, and würdest haben is avoided in favor of hättest.',
    },
    {
      id: 'ch60-ex-04',
      chapterNumber: 60,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'koennen'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of können.',
      prompt: 'Ich ___ dir morgen helfen.',
      options: [
        { id: 'a', text: 'könnte' },
        { id: 'b', text: 'konnte' },
        { id: 'c', text: 'kann' },
        { id: 'd', text: 'würde können' },
      ],
      correctOptionId: 'a',
      explanation:
        'könnte is the synthetic Konjunktiv II form of können; konnte is simple past, kann is present, and würde können is not used.',
    },
    {
      id: 'ch60-ex-05',
      chapterNumber: 60,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'kommen', 'umlaut'],
      instruction:
        'Choose the correct synthetic Konjunktiv II form of kommen for er/sie/es.',
      prompt: 'Er ___ gern mit, wenn er Zeit hätte.',
      options: [
        { id: 'a', text: 'käme' },
        { id: 'b', text: 'kam' },
        { id: 'c', text: 'kommt' },
        { id: 'd', text: 'kame' },
      ],
      correctOptionId: 'a',
      explanation:
        'käme umlauts the simple-past stem kam- to käm- and adds -e; kam is plain simple past, and kame is missing the required umlaut.',
    },
    {
      id: 'ch60-ex-06',
      chapterNumber: 60,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'finden', 'umlaut'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of finden for wir.',
      prompt: 'Wir ___ sicher eine Lösung.',
      options: [
        { id: 'a', text: 'fänden' },
        { id: 'b', text: 'fanden' },
        { id: 'c', text: 'finden' },
        { id: 'd', text: 'fänden würden' },
      ],
      correctOptionId: 'a',
      explanation:
        'fänden umlauts fand- to fänd- and adds -en; fanden is plain simple past.',
    },
    {
      id: 'ch60-ex-07',
      chapterNumber: 60,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'umlaut-pattern'],
      instruction: 'Choose the correct umlaut change described in this chapter.',
      prompt:
        'Which vowel change turns the simple-past stem kam- into the synthetic Konjunktiv II stem?',
      options: [
        { id: 'a', text: 'a → ä' },
        { id: 'b', text: 'a → au' },
        { id: 'c', text: 'a → e' },
        { id: 'd', text: 'no change' },
      ],
      correctOptionId: 'a',
      explanation:
        'The Konjunktiv II umlaut pattern is a → ä (also o → ö and u → ü): kam- becomes käm-.',
    },
    {
      id: 'ch60-ex-08',
      chapterNumber: 60,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'mood-identification'],
      instruction: 'Identify the mood of the underlined verb form.',
      prompt: 'Which mood is the verb form in: "Er käme gern mit."?',
      options: [
        { id: 'a', text: 'Konjunktiv II' },
        { id: 'b', text: 'simple past (Präteritum)' },
        { id: 'c', text: 'present tense' },
        { id: 'd', text: 'present perfect (Perfekt)' },
      ],
      correctOptionId: 'a',
      explanation:
        'käme has the Konjunktiv II umlaut (ä) that kommen never has in the simple past (kam) — this marks it clearly as Konjunktiv II.',
    },
    {
      id: 'ch60-ex-09',
      chapterNumber: 60,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'simple-past', 'mood-identification'],
      instruction: 'Identify the mood of the underlined verb form.',
      prompt: 'Which mood is the verb form in: "Er kam gestern spät nach Hause."?',
      options: [
        { id: 'a', text: 'simple past (Präteritum)' },
        { id: 'b', text: 'Konjunktiv II' },
        { id: 'c', text: 'present tense' },
        { id: 'd', text: 'present perfect (Perfekt)' },
      ],
      correctOptionId: 'a',
      explanation:
        'kam has no umlaut, and gestern places it in a plain factual narrative — this is the simple past, not Konjunktiv II.',
    },
    {
      id: 'ch60-ex-10',
      chapterNumber: 60,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'weak-verbs', 'ambiguity'],
      instruction: 'Choose the best explanation.',
      prompt:
        'Why does German normally avoid a synthetic Konjunktiv II form for kaufen (e.g. treating "kaufte" as hypothetical)?',
      options: [
        {
          id: 'a',
          text: 'Because kaufte is identical in shape to the simple past, so würde + infinitive is used instead to keep the meaning clear.',
        },
        { id: 'b', text: 'Because kaufen has no simple-past form at all.' },
        { id: 'c', text: 'Because kaufen is one of the six modal verbs.' },
        {
          id: 'd',
          text: 'Because Konjunktiv II does not exist for weak verbs in any form.',
        },
      ],
      correctOptionId: 'a',
      explanation:
        'Weak verbs would produce identical forms for simple past and Konjunktiv II, so würde + infinitive is used to avoid ambiguity, not because the mood does not exist.',
    },
    {
      id: 'ch60-ex-11',
      chapterNumber: 60,
      order: 11,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'natural-choice', 'kaufen'],
      instruction: 'Choose the most natural way to express the meaning.',
      prompt: 'Which is the natural, everyday way to say "I would buy the car"?',
      options: [
        { id: 'a', text: 'Ich würde das Auto kaufen.' },
        { id: 'b', text: 'Ich kaufte das Auto.' },
        { id: 'c', text: 'Ich käufte das Auto.' },
        { id: 'd', text: 'Ich habe das Auto gekauft.' },
      ],
      correctOptionId: 'a',
      explanation:
        'kaufen has no natural synthetic Konjunktiv II form (käufte is not a real word), so würde + infinitive is the only correct option.',
    },
    {
      id: 'ch60-ex-12',
      chapterNumber: 60,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'natural-choice', 'sein'],
      instruction: 'Choose the most natural way to express the meaning.',
      prompt: 'Which is the natural, everyday way to say "That would be nice"?',
      options: [
        { id: 'a', text: 'Das wäre schön.' },
        { id: 'b', text: 'Das würde schön sein.' },
        { id: 'c', text: 'Das ist schön gewesen.' },
        { id: 'd', text: 'Das war schön.' },
      ],
      correctOptionId: 'a',
      explanation:
        'wäre is the strongly preferred synthetic form of sein; würde schön sein is avoided by native speakers.',
    },
    {
      id: 'ch60-ex-13',
      chapterNumber: 60,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'natural-choice', 'koennen'],
      instruction: 'Choose the most natural way to express the meaning.',
      prompt: 'Which is the natural, everyday way to say "I could help you"?',
      options: [
        { id: 'a', text: 'Ich könnte dir helfen.' },
        { id: 'b', text: 'Ich würde dir helfen können.' },
        { id: 'c', text: 'Ich kann dir helfen können.' },
        { id: 'd', text: 'Ich konnte dir helfen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Modal verbs use their own synthetic Konjunktiv II forms; würde + können is not used, and konnte is simple past, not Konjunktiv II.',
    },
    {
      id: 'ch60-ex-14',
      chapterNumber: 60,
      order: 14,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'haben'],
      instruction:
        'Choose the correct Konjunktiv II counterpart of the factual statement.',
      prompt: 'Factual: "Ich habe keine Zeit." — Choose the Konjunktiv II version.',
      options: [
        { id: 'a', text: 'Ich hätte Zeit.' },
        { id: 'b', text: 'Ich habe Zeit gehabt.' },
        { id: 'c', text: 'Ich werde Zeit haben.' },
        { id: 'd', text: 'Ich hatte Zeit.' },
      ],
      correctOptionId: 'a',
      explanation:
        'hätte is the synthetic Konjunktiv II form of haben, turning the factual statement into a hypothetical one.',
    },
    {
      id: 'ch60-ex-15',
      chapterNumber: 60,
      order: 15,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'werden', 'form-recognition'],
      instruction: 'Choose the correct form.',
      prompt: 'What is the Konjunktiv II form of werden for ich?',
      options: [
        { id: 'a', text: 'würde' },
        { id: 'b', text: 'wurde' },
        { id: 'c', text: 'werde' },
        { id: 'd', text: 'war' },
      ],
      correctOptionId: 'a',
      explanation:
        'würde is literally the Konjunktiv II form of werden itself — the same word used as the auxiliary in the würde-construction.',
    },
    {
      id: 'ch60-ex-16',
      chapterNumber: 60,
      order: 16,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'umlaut', 'finden'],
      instruction: 'Choose the correct Konjunktiv II stem.',
      prompt: 'fand → Konjunktiv II stem?',
      options: [
        { id: 'a', text: 'fänd-' },
        { id: 'b', text: 'find-' },
        { id: 'c', text: 'fand-' },
        { id: 'd', text: 'fünd-' },
      ],
      correctOptionId: 'a',
      explanation:
        'The a in fand- umlauts to ä, giving fänd- as the Konjunktiv II stem (fände, fändest, ...).',
    },
    {
      id: 'ch60-ex-17',
      chapterNumber: 60,
      order: 17,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'endings', 'du-form'],
      instruction: 'Choose the correct rule about endings.',
      prompt: 'Which ending do all synthetic Konjunktiv II forms take for du?',
      options: [
        { id: 'a', text: '-est' },
        { id: 'b', text: '-st' },
        { id: 'c', text: '-est or -st, depending on the verb' },
        { id: 'd', text: '-te' },
      ],
      correctOptionId: 'a',
      explanation:
        'The Konjunktiv II du-ending is always -est (kämest, hättest, wärest), unlike the simple-past du-ending -st (kamst).',
    },
    {
      id: 'ch60-ex-18',
      chapterNumber: 60,
      order: 18,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'word-order'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'I would gladly drive to Berlin.',
      options: [
        { id: 'a', text: 'Ich würde gern nach Berlin fahren.' },
        { id: 'b', text: 'Ich würde fahren gern nach Berlin.' },
        { id: 'c', text: 'Ich gern würde nach Berlin fahren.' },
        { id: 'd', text: 'Fahren würde ich gern nach Berlin.' },
      ],
      correctOptionId: 'a',
      explanation:
        'würde stays in position 2, and the infinitive fahren is sent to the very end of the clause, exactly like a modal-verb bracket.',
    },
    {
      id: 'ch60-ex-19',
      chapterNumber: 60,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sein'],
      instruction:
        'Write the synthetic Konjunktiv II form of sein for ich. Capitalisation is not checked.',
      prompt: 'ich → sein (Konjunktiv II)',
      acceptedAnswers: ['wäre'],
      answerMode: 'caseInsensitive',
      placeholder: 'wäre',
      maxLength: 15,
      explanation: 'The ich-form of the synthetic Konjunktiv II of sein is wäre.',
    },
    {
      id: 'ch60-ex-20',
      chapterNumber: 60,
      order: 20,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'haben'],
      instruction:
        'Write the synthetic Konjunktiv II form of haben for du. Capitalisation is not checked.',
      prompt: 'du → haben (Konjunktiv II)',
      acceptedAnswers: ['hättest'],
      answerMode: 'caseInsensitive',
      placeholder: 'hättest',
      maxLength: 15,
      explanation: 'The du-form of the synthetic Konjunktiv II of haben is hättest.',
    },
    {
      id: 'ch60-ex-21',
      chapterNumber: 60,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'koennen'],
      instruction:
        'Write the synthetic Konjunktiv II form of können for wir. Capitalisation is not checked.',
      prompt: 'wir → können (Konjunktiv II)',
      acceptedAnswers: ['könnten'],
      answerMode: 'caseInsensitive',
      placeholder: 'könnten',
      maxLength: 15,
      explanation: 'The wir-form of the synthetic Konjunktiv II of können is könnten.',
    },
    {
      id: 'ch60-ex-22',
      chapterNumber: 60,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'muessen'],
      instruction:
        'Write the synthetic Konjunktiv II form of müssen for ihr. Capitalisation is not checked.',
      prompt: 'ihr → müssen (Konjunktiv II)',
      acceptedAnswers: ['müsstet'],
      answerMode: 'caseInsensitive',
      placeholder: 'müsstet',
      maxLength: 15,
      explanation: 'The ihr-form of the synthetic Konjunktiv II of müssen is müsstet.',
    },
    {
      id: 'ch60-ex-23',
      chapterNumber: 60,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'kommen', 'umlaut'],
      instruction:
        'Write the synthetic Konjunktiv II form of kommen for er/sie/es. Capitalisation is not checked.',
      prompt: 'er/sie/es → kommen (Konjunktiv II)',
      acceptedAnswers: ['käme'],
      answerMode: 'caseInsensitive',
      placeholder: 'käme',
      maxLength: 15,
      explanation: 'kam umlauts to käm-, plus the -e ending: käme.',
    },
    {
      id: 'ch60-ex-24',
      chapterNumber: 60,
      order: 24,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'finden', 'umlaut'],
      instruction:
        'Write the synthetic Konjunktiv II form of finden for sie (plural). Capitalisation is not checked.',
      prompt: 'sie (plural) → finden (Konjunktiv II)',
      acceptedAnswers: ['fänden'],
      answerMode: 'caseInsensitive',
      placeholder: 'fänden',
      maxLength: 15,
      explanation: 'fand umlauts to fänd-, plus the -en ending: fänden.',
    },
    {
      id: 'ch60-ex-25',
      chapterNumber: 60,
      order: 25,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'geben', 'umlaut'],
      instruction:
        'Write the synthetic Konjunktiv II form of geben for ich. Capitalisation is not checked.',
      prompt: 'ich → geben (Konjunktiv II)',
      acceptedAnswers: ['gäbe'],
      answerMode: 'caseInsensitive',
      placeholder: 'gäbe',
      maxLength: 15,
      explanation: 'gab umlauts to gäb-, plus the -e ending: gäbe.',
    },
    {
      id: 'ch60-ex-26',
      chapterNumber: 60,
      order: 26,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'machen'],
      instruction:
        'Write the würde + infinitive form for ich + machen (Konjunktiv II). Capitalisation is not checked.',
      prompt: 'ich → machen (Konjunktiv II, würde-construction)',
      acceptedAnswers: ['würde machen'],
      answerMode: 'normalized',
      placeholder: 'würde machen',
      maxLength: 25,
      explanation:
        'machen is a weak verb with no natural synthetic form, so its Konjunktiv II is würde machen.',
    },
    {
      id: 'ch60-ex-27',
      chapterNumber: 60,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'kaufen'],
      instruction:
        'Write the würde + infinitive form for du + kaufen (Konjunktiv II). Capitalisation is not checked.',
      prompt: 'du → kaufen (Konjunktiv II, würde-construction)',
      acceptedAnswers: ['würdest kaufen'],
      answerMode: 'normalized',
      placeholder: 'würdest kaufen',
      maxLength: 25,
      explanation:
        'kaufen is a weak verb, so its Konjunktiv II is always würde/würdest + infinitive: würdest kaufen.',
    },
    {
      id: 'ch60-ex-28',
      chapterNumber: 60,
      order: 28,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'wissen', 'umlaut'],
      instruction:
        'Write the synthetic Konjunktiv II form of wissen for ich. Capitalisation is not checked.',
      prompt: 'ich → wissen (Konjunktiv II)',
      acceptedAnswers: ['wüsste'],
      answerMode: 'caseInsensitive',
      placeholder: 'wüsste',
      maxLength: 15,
      explanation:
        'The mixed-verb stem wusst- umlauts to wüsst-, plus the -e ending: wüsste.',
    },
    {
      id: 'ch60-ex-29',
      chapterNumber: 60,
      order: 29,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sehen', 'du-ending'],
      instruction:
        'Write the synthetic Konjunktiv II form of sehen for du. Capitalisation is not checked.',
      prompt: 'du → sehen (Konjunktiv II)',
      acceptedAnswers: ['sähest'],
      answerMode: 'caseInsensitive',
      placeholder: 'sähest',
      maxLength: 15,
      explanation: 'sah umlauts to säh-, plus the du-ending -est: sähest.',
    },
    {
      id: 'ch60-ex-30',
      chapterNumber: 60,
      order: 30,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'haben'],
      instruction:
        'Rewrite the statement in Konjunktiv II, using the synthetic form of haben. Capitalisation and punctuation are checked.',
      prompt: 'Ich habe keine Zeit. → Konjunktiv II mit hätte',
      acceptedAnswers: ['Ich hätte Zeit.', 'Ich hätte Zeit'],
      answerMode: 'normalized',
      placeholder: 'Ich hätte ...',
      maxLength: 40,
      explanation:
        'habe becomes hätte, and the factual statement turns into a hypothetical one: Ich hätte Zeit.',
    },
    {
      id: 'ch60-ex-31',
      chapterNumber: 60,
      order: 31,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'sein'],
      instruction:
        'Rewrite the statement in Konjunktiv II, using the synthetic form of sein. Capitalisation and punctuation are checked.',
      prompt: 'Er ist müde. → Konjunktiv II mit wäre',
      acceptedAnswers: ['Er wäre müde.', 'Er wäre müde'],
      answerMode: 'normalized',
      placeholder: 'Er wäre ...',
      maxLength: 40,
      explanation: 'ist becomes wäre: Er wäre müde.',
    },
    {
      id: 'ch60-ex-32',
      chapterNumber: 60,
      order: 32,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'wuerde-konstruktion', 'kaufen'],
      instruction:
        'Rewrite the statement in Konjunktiv II, using würde + infinitive. Capitalisation and punctuation are checked.',
      prompt: 'Sie kauft ein neues Auto. → Konjunktiv II mit würde',
      acceptedAnswers: [
        'Sie würde ein neues Auto kaufen.',
        'Sie würde ein neues Auto kaufen',
      ],
      answerMode: 'normalized',
      placeholder: 'Sie würde ...',
      maxLength: 60,
      explanation:
        'kaufen has no natural synthetic form, so kauft becomes würde ... kaufen: Sie würde ein neues Auto kaufen.',
    },
    {
      id: 'ch60-ex-33',
      chapterNumber: 60,
      order: 33,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'modal-verbs', 'koennen'],
      instruction:
        'Rewrite the statement in Konjunktiv II, using the synthetic form of können. Capitalisation and punctuation are checked.',
      prompt: 'Wir können nicht kommen. → Konjunktiv II mit könnten',
      acceptedAnswers: ['Wir könnten nicht kommen.', 'Wir könnten nicht kommen'],
      answerMode: 'normalized',
      placeholder: 'Wir könnten ...',
      maxLength: 40,
      explanation: 'können becomes könnten: Wir könnten nicht kommen.',
    },
    {
      id: 'ch60-ex-34',
      chapterNumber: 60,
      order: 34,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: [
        'konjunktiv-ii',
        'sentence-building',
        'hätte',
        'wuerde-konstruktion',
      ],
      instruction:
        'Build a complete sentence from the cue words, combining a synthetic form and a würde-construction. Capitalisation and punctuation are checked.',
      prompt:
        'wenn – ich – Zeit – haben (Konjunktiv II) – , – ich – dich – besuchen (Konjunktiv II mit würde)',
      acceptedAnswers: ['Wenn ich Zeit hätte, würde ich dich besuchen.'],
      answerMode: 'normalized',
      placeholder: 'Wenn ich Zeit hätte, würde ich dich besuchen.',
      maxLength: 70,
      explanation:
        'haben becomes the synthetic hätte in the wenn-clause; besuchen has no synthetic form, so it takes würde + infinitive: Wenn ich Zeit hätte, würde ich dich besuchen.',
    },
    {
      id: 'ch60-ex-35',
      chapterNumber: 60,
      order: 35,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sein', 'wir-form'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of sein for wir.',
      prompt: 'Wir ___ gern dabei, wenn wir Zeit hätten.',
      options: [
        { id: 'a', text: 'wären' },
        { id: 'b', text: 'waren' },
        { id: 'c', text: 'sind' },
        { id: 'd', text: 'würden sein' },
      ],
      correctOptionId: 'a',
      explanation:
        'wären is the wir-form of the synthetic Konjunktiv II of sein; waren is simple past, sind is present, and würden sein is avoided because sein keeps its own synthetic form.',
    },
    {
      id: 'ch60-ex-36',
      chapterNumber: 60,
      order: 36,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'haben', 'ihr-form'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of haben for ihr.',
      prompt: 'Ihr ___ sicher auch gern mehr Geld.',
      options: [
        { id: 'a', text: 'hättet' },
        { id: 'b', text: 'hattet' },
        { id: 'c', text: 'habt' },
        { id: 'd', text: 'würdet haben' },
      ],
      correctOptionId: 'a',
      explanation:
        'hättet is the ihr-form of the synthetic Konjunktiv II of haben; hattet is simple past, and würdet haben is avoided since haben keeps its own synthetic form.',
    },
    {
      id: 'ch60-ex-37',
      chapterNumber: 60,
      order: 37,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'werden', 'du-form'],
      instruction: 'Choose the correct Konjunktiv II form of werden for du.',
      prompt: 'Du ___ das bestimmt gut machen.',
      options: [
        { id: 'a', text: 'würdest' },
        { id: 'b', text: 'wurdest' },
        { id: 'c', text: 'wirst' },
        { id: 'd', text: 'würde' },
      ],
      correctOptionId: 'a',
      explanation:
        "würdest is the du-form of werden's Konjunktiv II, used as the helper in the würde-construction; wurdest is simple past and wirst is present.",
    },
    {
      id: 'ch60-ex-38',
      chapterNumber: 60,
      order: 38,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'duerfen'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of dürfen.',
      prompt: 'Ich ___ das doch machen, oder?',
      options: [
        { id: 'a', text: 'dürfte' },
        { id: 'b', text: 'durfte' },
        { id: 'c', text: 'darf' },
        { id: 'd', text: 'würde dürfen' },
      ],
      correctOptionId: 'a',
      explanation:
        'dürfte is the synthetic Konjunktiv II form of dürfen; durfte is simple past, darf is present, and würde dürfen is not used.',
    },
    {
      id: 'ch60-ex-39',
      chapterNumber: 60,
      order: 39,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'sollen', 'du-form'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of sollen for du.',
      prompt: 'Du ___ eigentlich früher aufstehen.',
      options: [
        { id: 'a', text: 'solltest' },
        { id: 'b', text: 'solltet' },
        { id: 'c', text: 'sollst' },
        { id: 'd', text: 'würdest sollen' },
      ],
      correctOptionId: 'a',
      explanation:
        "solltest is the du-form of sollen's Konjunktiv II; it looks identical to the simple past, since sollen has no umlautable vowel.",
    },
    {
      id: 'ch60-ex-40',
      chapterNumber: 60,
      order: 40,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'moegen', 'moechte'],
      instruction: 'Choose the correct everyday Konjunktiv II form of mögen.',
      prompt: 'Ich ___ gern einen Tee, bitte.',
      options: [
        { id: 'a', text: 'möchte' },
        { id: 'b', text: 'mochte' },
        { id: 'c', text: 'mag' },
        { id: 'd', text: 'würde mögen' },
      ],
      correctOptionId: 'a',
      explanation:
        'möchte is the everyday synthetic Konjunktiv II form of mögen, used constantly in polite requests; würde mögen is essentially never used.',
    },
    {
      id: 'ch60-ex-41',
      chapterNumber: 60,
      order: 41,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wollen', 'mood-identification', 'ambiguity'],
      instruction: 'Choose the most likely reading of the underlined form.',
      prompt:
        'Which mood is most likely meant in the polite request "Ich wollte dich etwas fragen."?',
      options: [
        { id: 'a', text: 'Konjunktiv II, softening the request politely' },
        { id: 'b', text: 'Present tense' },
        { id: 'c', text: 'Present perfect (Perfekt)' },
        { id: 'd', text: 'Future tense' },
      ],
      correctOptionId: 'a',
      explanation:
        'wollte looks identical in the simple past and Konjunktiv II because wollen has no umlautable vowel; in a polite, softened request like this, context signals Konjunktiv II.',
    },
    {
      id: 'ch60-ex-42',
      chapterNumber: 60,
      order: 42,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'gehen'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of gehen for ich.',
      prompt: 'Ich ___ jetzt gern nach Hause, aber ich muss noch arbeiten.',
      options: [
        { id: 'a', text: 'ginge' },
        { id: 'b', text: 'ging' },
        { id: 'c', text: 'gehe' },
        { id: 'd', text: 'gehte' },
      ],
      correctOptionId: 'a',
      explanation:
        'ging has no umlautable vowel, so the Konjunktiv II simply adds -e: ginge; gehte is not a real form.',
    },
    {
      id: 'ch60-ex-43',
      chapterNumber: 60,
      order: 43,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'geben', 'du-form', 'umlaut'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of geben for du.',
      prompt: 'Du ___ mir sicher gern etwas ab.',
      options: [
        { id: 'a', text: 'gäbest' },
        { id: 'b', text: 'gabst' },
        { id: 'c', text: 'gibst' },
        { id: 'd', text: 'gäbst' },
      ],
      correctOptionId: 'a',
      explanation:
        'gab umlauts to gäb-, and the Konjunktiv II du-ending is -est, giving gäbest; gäbst is missing the linking e.',
    },
    {
      id: 'ch60-ex-44',
      chapterNumber: 60,
      order: 44,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sehen', 'wir-form'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of sehen for wir.',
      prompt: 'Wir ___ das gern mit eigenen Augen.',
      options: [
        { id: 'a', text: 'sähen' },
        { id: 'b', text: 'sahen' },
        { id: 'c', text: 'sehen' },
        { id: 'd', text: 'würden sehen' },
      ],
      correctOptionId: 'a',
      explanation: 'sah umlauts to säh-, plus the wir-ending -en: sähen.',
    },
    {
      id: 'ch60-ex-45',
      chapterNumber: 60,
      order: 45,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sprechen', 'umlaut'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of sprechen for ich.',
      prompt: 'Ich ___ gern besser Deutsch.',
      options: [
        { id: 'a', text: 'spräche' },
        { id: 'b', text: 'sprach' },
        { id: 'c', text: 'spreche' },
        { id: 'd', text: 'sprache' },
      ],
      correctOptionId: 'a',
      explanation: 'sprach umlauts to spräch-, plus the ich-ending -e: spräche.',
    },
    {
      id: 'ch60-ex-46',
      chapterNumber: 60,
      order: 46,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'fahren', 'du-form', 'umlaut'],
      instruction: 'Choose the correct synthetic Konjunktiv II form of fahren for du.',
      prompt: 'Du ___ bestimmt gern mit dem Zug.',
      options: [
        { id: 'a', text: 'führest' },
        { id: 'b', text: 'fuhrst' },
        { id: 'c', text: 'fährst' },
        { id: 'd', text: 'führst' },
      ],
      correctOptionId: 'a',
      explanation:
        'fuhr umlauts to führ-, and the du-ending is -est, giving führest; führst is missing the linking e.',
    },
    {
      id: 'ch60-ex-47',
      chapterNumber: 60,
      order: 47,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'lesen'],
      instruction:
        'Choose the correct synthetic Konjunktiv II form of lesen for er/sie/es.',
      prompt: 'Er ___ das Buch gern noch einmal.',
      options: [
        { id: 'a', text: 'läse' },
        { id: 'b', text: 'las' },
        { id: 'c', text: 'liest' },
        { id: 'd', text: 'würde lesen' },
      ],
      correctOptionId: 'a',
      explanation: 'las umlauts to läs-, plus the ending -e: läse.',
    },
    {
      id: 'ch60-ex-48',
      chapterNumber: 60,
      order: 48,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'tun', 'sie-plural'],
      instruction:
        'Choose the correct synthetic Konjunktiv II form of tun for sie (plural).',
      prompt: 'Sie ___ das bestimmt gern für dich.',
      options: [
        { id: 'a', text: 'täten' },
        { id: 'b', text: 'taten' },
        { id: 'c', text: 'tun' },
        { id: 'd', text: 'würden tun' },
      ],
      correctOptionId: 'a',
      explanation: 'tat umlauts to tät-, plus the sie-plural ending -en: täten.',
    },
    {
      id: 'ch60-ex-49',
      chapterNumber: 60,
      order: 49,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sein', 'du-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of sein for du. Capitalisation is not checked.',
      prompt: 'du → sein (Konjunktiv II)',
      acceptedAnswers: ['wärest'],
      answerMode: 'caseInsensitive',
      placeholder: 'wärest',
      maxLength: 15,
      explanation: 'The du-form of the synthetic Konjunktiv II of sein is wärest.',
    },
    {
      id: 'ch60-ex-50',
      chapterNumber: 60,
      order: 50,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sein', 'ihr-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of sein for ihr. Capitalisation is not checked.',
      prompt: 'ihr → sein (Konjunktiv II)',
      acceptedAnswers: ['wäret'],
      answerMode: 'caseInsensitive',
      placeholder: 'wäret',
      maxLength: 15,
      explanation: 'The ihr-form of the synthetic Konjunktiv II of sein is wäret.',
    },
    {
      id: 'ch60-ex-51',
      chapterNumber: 60,
      order: 51,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'haben', 'er-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of haben for er/sie/es. Capitalisation is not checked.',
      prompt: 'er/sie/es → haben (Konjunktiv II)',
      acceptedAnswers: ['hätte'],
      answerMode: 'caseInsensitive',
      placeholder: 'hätte',
      maxLength: 15,
      explanation: 'The er/sie/es-form of the synthetic Konjunktiv II of haben is hätte.',
    },
    {
      id: 'ch60-ex-52',
      chapterNumber: 60,
      order: 52,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'haben', 'sie-plural'],
      instruction:
        'Write the synthetic Konjunktiv II form of haben for sie (plural). Capitalisation is not checked.',
      prompt: 'sie (plural) → haben (Konjunktiv II)',
      acceptedAnswers: ['hätten'],
      answerMode: 'caseInsensitive',
      placeholder: 'hätten',
      maxLength: 15,
      explanation:
        'The sie-plural form of the synthetic Konjunktiv II of haben is hätten.',
    },
    {
      id: 'ch60-ex-53',
      chapterNumber: 60,
      order: 53,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'werden', 'wir-form'],
      instruction:
        'Write the Konjunktiv II form of werden for wir. Capitalisation is not checked.',
      prompt: 'wir → werden (Konjunktiv II)',
      acceptedAnswers: ['würden'],
      answerMode: 'caseInsensitive',
      placeholder: 'würden',
      maxLength: 15,
      explanation:
        "The wir-form of werden's Konjunktiv II is würden, used as the helper for wir + infinitive.",
    },
    {
      id: 'ch60-ex-54',
      chapterNumber: 60,
      order: 54,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'werden', 'ihr-form'],
      instruction:
        'Write the Konjunktiv II form of werden for ihr. Capitalisation is not checked.',
      prompt: 'ihr → werden (Konjunktiv II)',
      acceptedAnswers: ['würdet'],
      answerMode: 'caseInsensitive',
      placeholder: 'würdet',
      maxLength: 15,
      explanation: "The ihr-form of werden's Konjunktiv II is würdet.",
    },
    {
      id: 'ch60-ex-55',
      chapterNumber: 60,
      order: 55,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'koennen', 'du-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of können for du. Capitalisation is not checked.',
      prompt: 'du → können (Konjunktiv II)',
      acceptedAnswers: ['könntest'],
      answerMode: 'caseInsensitive',
      placeholder: 'könntest',
      maxLength: 15,
      explanation: 'The du-form of the synthetic Konjunktiv II of können is könntest.',
    },
    {
      id: 'ch60-ex-56',
      chapterNumber: 60,
      order: 56,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'muessen', 'er-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of müssen for er/sie/es. Capitalisation is not checked.',
      prompt: 'er/sie/es → müssen (Konjunktiv II)',
      acceptedAnswers: ['müsste'],
      answerMode: 'caseInsensitive',
      placeholder: 'müsste',
      maxLength: 15,
      explanation:
        'The er/sie/es-form of the synthetic Konjunktiv II of müssen is müsste.',
    },
    {
      id: 'ch60-ex-57',
      chapterNumber: 60,
      order: 57,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'duerfen', 'wir-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of dürfen for wir. Capitalisation is not checked.',
      prompt: 'wir → dürfen (Konjunktiv II)',
      acceptedAnswers: ['dürften'],
      answerMode: 'caseInsensitive',
      placeholder: 'dürften',
      maxLength: 15,
      explanation: 'The wir-form of the synthetic Konjunktiv II of dürfen is dürften.',
    },
    {
      id: 'ch60-ex-58',
      chapterNumber: 60,
      order: 58,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'sollen', 'ihr-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of sollen for ihr. Capitalisation is not checked.',
      prompt: 'ihr → sollen (Konjunktiv II)',
      acceptedAnswers: ['solltet'],
      answerMode: 'caseInsensitive',
      placeholder: 'solltet',
      maxLength: 15,
      explanation:
        "The ihr-form of sollen's Konjunktiv II is solltet, identical in shape to the simple past since sollen has no umlautable vowel.",
    },
    {
      id: 'ch60-ex-59',
      chapterNumber: 60,
      order: 59,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'wollen', 'sie-plural'],
      instruction:
        'Write the synthetic Konjunktiv II form of wollen for sie (plural). Capitalisation is not checked.',
      prompt: 'sie (plural) → wollen (Konjunktiv II)',
      acceptedAnswers: ['wollten'],
      answerMode: 'caseInsensitive',
      placeholder: 'wollten',
      maxLength: 15,
      explanation:
        "The sie-plural form of wollen's Konjunktiv II is wollten, identical in shape to the simple past since wollen has no umlautable vowel.",
    },
    {
      id: 'ch60-ex-60',
      chapterNumber: 60,
      order: 60,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'kommen', 'du-form', 'umlaut'],
      instruction:
        'Write the synthetic Konjunktiv II form of kommen for du. Capitalisation is not checked.',
      prompt: 'du → kommen (Konjunktiv II)',
      acceptedAnswers: ['kämest'],
      answerMode: 'caseInsensitive',
      placeholder: 'kämest',
      maxLength: 15,
      explanation: 'kam umlauts to käm-, and the du-ending is -est: kämest.',
    },
    {
      id: 'ch60-ex-61',
      chapterNumber: 60,
      order: 61,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'gehen', 'wir-form'],
      instruction:
        'Write the synthetic Konjunktiv II form of gehen for wir. Capitalisation is not checked.',
      prompt: 'wir → gehen (Konjunktiv II)',
      acceptedAnswers: ['gingen'],
      answerMode: 'caseInsensitive',
      placeholder: 'gingen',
      maxLength: 15,
      explanation:
        'ging has no umlautable vowel, so only the wir-ending -en is added: gingen.',
    },
    {
      id: 'ch60-ex-62',
      chapterNumber: 60,
      order: 62,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'transformation', 'haben'],
      instruction:
        'Rewrite the statement in Konjunktiv II, using the synthetic form of haben. Capitalisation and punctuation are checked.',
      prompt: 'Er hat kein Geld. → Konjunktiv II mit hätte',
      acceptedAnswers: ['Er hätte kein Geld.', 'Er hätte kein Geld'],
      answerMode: 'normalized',
      placeholder: 'Er hätte ...',
      maxLength: 40,
      explanation:
        'hat becomes hätte, turning the factual statement into a hypothetical one: Er hätte kein Geld.',
    },
    {
      id: 'ch60-ex-63',
      chapterNumber: 60,
      order: 63,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sein', 'er-form'],
      instruction: 'Drag the correct synthetic Konjunktiv II form of sein into the slot.',
      prompt: 'Er ___ jetzt gern zu Hause.',
      templateParts: ['Er ', ' jetzt gern zu Hause.'],
      slots: [{ id: 'slot1', correctWord: 'wäre' }],
      wordBank: ['wäre', 'war', 'ist', 'würde'],
      explanation:
        'wäre is the synthetic Konjunktiv II form of sein for er; war is simple past, ist is present, and würde needs an infinitive to pair with, which sein avoids.',
    },
    {
      id: 'ch60-ex-64',
      chapterNumber: 60,
      order: 64,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'haben', 'ihr-form'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of haben into the slot.',
      prompt: 'Ihr ___ bestimmt auch gern ein Auto.',
      templateParts: ['Ihr ', ' bestimmt auch gern ein Auto.'],
      slots: [{ id: 'slot1', correctWord: 'hättet' }],
      wordBank: ['hättet', 'hattet', 'habt', 'würdet'],
      explanation:
        'hättet is the ihr-form of the synthetic Konjunktiv II of haben; hattet is simple past, habt is present.',
    },
    {
      id: 'ch60-ex-65',
      chapterNumber: 60,
      order: 65,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'koennen'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of können into the slot.',
      prompt: 'Ich ___ dir gern helfen.',
      templateParts: ['Ich ', ' dir gern helfen.'],
      slots: [{ id: 'slot1', correctWord: 'könnte' }],
      wordBank: ['könnte', 'konnte', 'kann', 'würde'],
      explanation:
        'könnte is the synthetic Konjunktiv II form of können; konnte is simple past and kann is present.',
    },
    {
      id: 'ch60-ex-66',
      chapterNumber: 60,
      order: 66,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'duerfen', 'wir-form'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of dürfen into the slot.',
      prompt: 'Wir ___ das doch machen, oder?',
      templateParts: ['Wir ', ' das doch machen, oder?'],
      slots: [{ id: 'slot1', correctWord: 'dürften' }],
      wordBank: ['dürften', 'durften', 'dürfen', 'würden'],
      explanation:
        'dürften is the wir-form of the synthetic Konjunktiv II of dürfen; durften is simple past.',
    },
    {
      id: 'ch60-ex-67',
      chapterNumber: 60,
      order: 67,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs', 'sollen'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of sollen into the slot.',
      prompt: 'Sie ___ eigentlich mehr schlafen.',
      templateParts: ['Sie ', ' eigentlich mehr schlafen.'],
      slots: [{ id: 'slot1', correctWord: 'sollte' }],
      wordBank: ['sollte', 'solltest', 'sollten', 'soll'],
      explanation:
        "sollte is the sie-singular form of sollen's Konjunktiv II, identical in shape to the simple past.",
    },
    {
      id: 'ch60-ex-68',
      chapterNumber: 60,
      order: 68,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'kommen', 'umlaut'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of kommen into the slot.',
      prompt: 'Ich ___ gern mit, wenn ich Zeit hätte.',
      templateParts: ['Ich ', ' gern mit, wenn ich Zeit hätte.'],
      slots: [{ id: 'slot1', correctWord: 'käme' }],
      wordBank: ['käme', 'kam', 'komme', 'kame'],
      explanation:
        'kam umlauts to käm-, plus the ich-ending -e: käme; kame is missing the required umlaut.',
    },
    {
      id: 'ch60-ex-69',
      chapterNumber: 60,
      order: 69,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'geben', 'umlaut'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of geben into the slot.',
      prompt: 'Er ___ mir sicher gern etwas.',
      templateParts: ['Er ', ' mir sicher gern etwas.'],
      slots: [{ id: 'slot1', correctWord: 'gäbe' }],
      wordBank: ['gäbe', 'gab', 'gibt', 'gebe'],
      explanation: 'gab umlauts to gäb-, plus the ending -e: gäbe.',
    },
    {
      id: 'ch60-ex-70',
      chapterNumber: 60,
      order: 70,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'sehen', 'du-form', 'umlaut'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of sehen into the slot.',
      prompt: 'Du ___ das bestimmt gern selbst.',
      templateParts: ['Du ', ' das bestimmt gern selbst.'],
      slots: [{ id: 'slot1', correctWord: 'sähest' }],
      wordBank: ['sähest', 'sahst', 'siehst', 'sähst'],
      explanation:
        'sah umlauts to säh-, and the du-ending is -est, giving sähest; sähst is missing the linking e.',
    },
    {
      id: 'ch60-ex-71',
      chapterNumber: 60,
      order: 71,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'finden', 'wir-form', 'umlaut'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of finden into the slot.',
      prompt: 'Wir ___ bestimmt eine Lösung.',
      templateParts: ['Wir ', ' bestimmt eine Lösung.'],
      slots: [{ id: 'slot1', correctWord: 'fänden' }],
      wordBank: ['fänden', 'fanden', 'finden', 'fändet'],
      explanation: 'fand umlauts to fänd-, plus the wir-ending -en: fänden.',
    },
    {
      id: 'ch60-ex-72',
      chapterNumber: 60,
      order: 72,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'gehen', 'sie-plural'],
      instruction:
        'Drag the correct synthetic Konjunktiv II form of gehen into the slot.',
      prompt: 'Sie ___ jetzt gern schwimmen.',
      templateParts: ['Sie ', ' jetzt gern schwimmen.'],
      slots: [{ id: 'slot1', correctWord: 'gingen' }],
      wordBank: ['gingen', 'gehen', 'würden', 'ginget'],
      explanation:
        'ging has no umlautable vowel, so only the sie-plural ending -en is added: gingen.',
    },
    {
      id: 'ch60-ex-73',
      chapterNumber: 60,
      order: 73,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'kaufen'],
      instruction: 'Drag the correct words to complete the würde-construction.',
      prompt: 'Ich ___ das Buch ___.',
      templateParts: ['Ich ', ' das Buch ', '.'],
      slots: [
        { id: 'slot1', correctWord: 'würde' },
        { id: 'slot2', correctWord: 'kaufen' },
      ],
      wordBank: ['würde', 'würdest', 'kaufen', 'verkaufen'],
      explanation:
        'kaufen has no natural synthetic form, so it takes würde + infinitive: würde ... kaufen, with würde in position 2 and the infinitive at the end.',
    },
    {
      id: 'ch60-ex-74',
      chapterNumber: 60,
      order: 74,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'machen', 'du-form'],
      instruction: 'Drag the correct words to complete the würde-construction.',
      prompt: 'Du ___ das bestimmt gut ___.',
      templateParts: ['Du ', ' das bestimmt gut ', '.'],
      slots: [
        { id: 'slot1', correctWord: 'würdest' },
        { id: 'slot2', correctWord: 'machen' },
      ],
      wordBank: ['würdest', 'würde', 'machen', 'schaffen'],
      explanation:
        'machen is a weak verb, so its Konjunktiv II is always würdest/würde + infinitive; here the subject du needs würdest.',
    },
    {
      id: 'ch60-ex-75',
      chapterNumber: 60,
      order: 75,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'core-verbs'],
      instruction: 'Match each infinitive to its synthetic Konjunktiv II (ich-form).',
      prompt: 'Infinitive → Konjunktiv II (ich)',
      pairs: [
        { id: 'p1', left: 'sein', right: 'wäre' },
        { id: 'p2', left: 'haben', right: 'hätte' },
        { id: 'p3', left: 'werden', right: 'würde' },
        { id: 'p4', left: 'können', right: 'könnte' },
        { id: 'p5', left: 'müssen', right: 'müsste' },
      ],
      explanation:
        'These five verbs keep a strongly preferred synthetic Konjunktiv II form in everyday German instead of the würde-construction.',
    },
    {
      id: 'ch60-ex-76',
      chapterNumber: 60,
      order: 76,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['konjunktiv-ii', 'modal-verbs'],
      instruction: 'Match each modal verb to its synthetic Konjunktiv II (ich-form).',
      prompt: 'Modal infinitive → Konjunktiv II (ich)',
      pairs: [
        { id: 'p1', left: 'wollen', right: 'wollte' },
        { id: 'p2', left: 'mögen', right: 'möchte' },
        { id: 'p3', left: 'dürfen', right: 'dürfte' },
        { id: 'p4', left: 'sollen', right: 'sollte' },
        { id: 'p5', left: 'können', right: 'könnte' },
      ],
      explanation:
        'All six modal verbs keep a synthetic Konjunktiv II form; wollte and sollte happen to look identical to the simple past because their stems have no umlautable vowel.',
    },
    {
      id: 'ch60-ex-77',
      chapterNumber: 60,
      order: 77,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'strong-verbs', 'umlaut'],
      instruction:
        'Match each strong verb to its synthetic Konjunktiv II (er/sie/es-form).',
      prompt: 'Infinitive → Konjunktiv II (er/sie/es)',
      pairs: [
        { id: 'p1', left: 'kommen', right: 'käme' },
        { id: 'p2', left: 'gehen', right: 'ginge' },
        { id: 'p3', left: 'geben', right: 'gäbe' },
        { id: 'p4', left: 'sehen', right: 'sähe' },
        { id: 'p5', left: 'nehmen', right: 'nähme' },
      ],
      explanation:
        'kommen, geben, sehen, and nehmen umlaut their simple-past stem vowel; gehen has no umlautable vowel, so only the ending changes.',
    },
    {
      id: 'ch60-ex-78',
      chapterNumber: 60,
      order: 78,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'strong-verbs', 'umlaut'],
      instruction: 'Match each verb to its synthetic Konjunktiv II (er/sie/es-form).',
      prompt: 'Infinitive → Konjunktiv II (er/sie/es)',
      pairs: [
        { id: 'p1', left: 'finden', right: 'fände' },
        { id: 'p2', left: 'wissen', right: 'wüsste' },
        { id: 'p3', left: 'stehen', right: 'stünde' },
        { id: 'p4', left: 'tun', right: 'täte' },
        { id: 'p5', left: 'waschen', right: 'wüsche' },
      ],
      explanation:
        'All five stems take the umlaut-plus-ending pattern; wissen is a mixed verb but still follows the same umlaut logic (wusst- → wüsst-).',
    },
    {
      id: 'ch60-ex-79',
      chapterNumber: 60,
      order: 79,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'umlaut-pattern', 'simple-past'],
      instruction: 'Match each simple-past stem to its umlauted Konjunktiv II stem.',
      prompt: 'Simple-past stem → Konjunktiv II stem',
      pairs: [
        { id: 'p1', left: 'kam', right: 'käm-' },
        { id: 'p2', left: 'fand', right: 'fänd-' },
        { id: 'p3', left: 'gab', right: 'gäb-' },
        { id: 'p4', left: 'sah', right: 'säh-' },
        { id: 'p5', left: 'sprach', right: 'spräch-' },
      ],
      explanation:
        'Each simple-past stem umlauts its a/o/u vowel to ä/ö/ü to form the Konjunktiv II stem, which then takes the -e/-est/-e/-en/-et/-en endings.',
    },
    {
      id: 'ch60-ex-80',
      chapterNumber: 60,
      order: 80,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'meaning', 'synthetic-form'],
      instruction: 'Match each English meaning to its German Konjunktiv II form.',
      prompt: 'English meaning → German (ich-form)',
      pairs: [
        { id: 'p1', left: 'I would be', right: 'wäre' },
        { id: 'p2', left: 'I would have', right: 'hätte' },
        { id: 'p3', left: 'I would come', right: 'käme' },
        { id: 'p4', left: 'I would go', right: 'ginge' },
        { id: 'p5', left: 'I would like to', right: 'möchte' },
      ],
      explanation:
        'Each English "would ..." meaning maps onto its own synthetic German Konjunktiv II form.',
    },
    {
      id: 'ch60-ex-81',
      chapterNumber: 60,
      order: 81,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'context', 'synthetic-form'],
      instruction: 'Match each sentence gap to the word that correctly completes it.',
      prompt: 'Sentence with gap → correct word',
      pairs: [
        { id: 'p1', left: 'Ich ___ gern mit.', right: 'käme' },
        { id: 'p2', left: 'Du ___ mir helfen.', right: 'könntest' },
        { id: 'p3', left: 'Wir ___ eine Lösung.', right: 'fänden' },
        { id: 'p4', left: 'Er ___ müde.', right: 'wäre' },
        { id: 'p5', left: 'Ihr ___ mehr Zeit.', right: 'hättet' },
      ],
      explanation:
        'Each gap needs the synthetic Konjunktiv II form matching its subject and verb: käme (kommen), könntest (können), fänden (finden), wäre (sein), hättet (haben).',
    },
    {
      id: 'ch60-ex-82',
      chapterNumber: 60,
      order: 82,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'weak-verbs'],
      instruction:
        'Match each weak verb to its Konjunktiv II würde-construction (ich-form).',
      prompt: 'Infinitive → würde-construction (ich)',
      pairs: [
        { id: 'p1', left: 'machen', right: 'würde machen' },
        { id: 'p2', left: 'kaufen', right: 'würde kaufen' },
        { id: 'p3', left: 'spielen', right: 'würde spielen' },
        { id: 'p4', left: 'lernen', right: 'würde lernen' },
        { id: 'p5', left: 'arbeiten', right: 'würde arbeiten' },
      ],
      explanation:
        'Weak verbs have no natural synthetic Konjunktiv II form (it would be identical to the simple past), so they always use würde + infinitive.',
    },
    {
      id: 'ch60-ex-83',
      chapterNumber: 60,
      order: 83,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'kommen', 'umlaut'],
      instruction: 'Find the token with the missing umlaut and correct it.',
      prompt: 'Ich kame gern mit.',
      tokens: ['Ich', 'kame', 'gern', 'mit.'],
      errorTokenIndex: 1,
      correction: 'käme',
      explanation:
        'The synthetic Konjunktiv II stem of kommen needs its umlaut: kam- becomes käm-, so the correct form is käme, not kame.',
    },
    {
      id: 'ch60-ex-84',
      chapterNumber: 60,
      order: 84,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'kommen', 'du-ending'],
      instruction:
        'Find the token that is missing the correct Konjunktiv II du-ending and correct it.',
      prompt: 'Du kämst gern mit.',
      tokens: ['Du', 'kämst', 'gern', 'mit.'],
      errorTokenIndex: 1,
      correction: 'kämest',
      explanation:
        'The Konjunktiv II du-ending is -est, not just -st: the umlauted stem käm- needs kämest, not kämst.',
    },
    {
      id: 'ch60-ex-85',
      chapterNumber: 60,
      order: 85,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'finden', 'umlaut'],
      instruction:
        'Find the token that is missing its Konjunktiv II umlaut and correct it.',
      prompt: 'Wenn wir zusammenarbeiten würden, fanden wir bestimmt eine Lösung.',
      tokens: [
        'Wenn',
        'wir',
        'zusammenarbeiten',
        'würden,',
        'fanden',
        'wir',
        'bestimmt',
        'eine',
        'Lösung.',
      ],
      errorTokenIndex: 4,
      correction: 'fänden',
      explanation:
        'In this hypothetical wenn-sentence, the verb must be Konjunktiv II: fand- umlauts to fänd-, giving fänden, not the plain simple-past fanden.',
    },
    {
      id: 'ch60-ex-86',
      chapterNumber: 60,
      order: 86,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'geben', 'umlaut'],
      instruction:
        'Find the token that is missing its Konjunktiv II umlaut and correct it.',
      prompt: 'Er gabe mir sicher gern etwas.',
      tokens: ['Er', 'gabe', 'mir', 'sicher', 'gern', 'etwas.'],
      errorTokenIndex: 1,
      correction: 'gäbe',
      explanation:
        'The synthetic Konjunktiv II stem of geben needs its umlaut: gab- becomes gäb-, so the correct form is gäbe, not gabe.',
    },
    {
      id: 'ch60-ex-87',
      chapterNumber: 60,
      order: 87,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'fahren', 'umlaut'],
      instruction:
        'Find the token that is missing its Konjunktiv II umlaut and correct it.',
      prompt: 'Du fuhrest bestimmt gern mit dem Zug.',
      tokens: ['Du', 'fuhrest', 'bestimmt', 'gern', 'mit', 'dem', 'Zug.'],
      errorTokenIndex: 1,
      correction: 'führest',
      explanation:
        'The synthetic Konjunktiv II stem of fahren needs its umlaut: fuhr- becomes führ-, so the correct form is führest, not fuhrest.',
    },
    {
      id: 'ch60-ex-88',
      chapterNumber: 60,
      order: 88,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'synthetic-form', 'tun', 'sie-plural'],
      instruction: 'Find the incorrectly formed token and correct it.',
      prompt: 'Sie tuten das bestimmt gern für dich.',
      tokens: ['Sie', 'tuten', 'das', 'bestimmt', 'gern', 'für', 'dich.'],
      errorTokenIndex: 1,
      correction: 'täten',
      explanation:
        "tun's synthetic Konjunktiv II stem is the umlauted simple-past stem tät- plus the sie-plural ending -en, giving täten, not tuten.",
    },
    {
      id: 'ch60-ex-89',
      chapterNumber: 60,
      order: 89,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'wuerde-konstruktion', 'word-order'],
      instruction:
        'Put the words in the correct order to form a natural Konjunktiv II sentence.',
      prompt: 'I would like to go home now.',
      segments: [
        { id: 's1', text: 'Ich' },
        { id: 's2', text: 'würde' },
        { id: 's3', text: 'jetzt' },
        { id: 's4', text: 'gern' },
        { id: 's5', text: 'nach' },
        { id: 's6', text: 'Hause' },
        { id: 's7', text: 'gehen.' },
      ],
      explanation:
        'würde stays in position 2, and the infinitive gehen is sent to the very end of the clause: Ich würde jetzt gern nach Hause gehen.',
    },
    {
      id: 'ch60-ex-90',
      chapterNumber: 60,
      order: 90,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['konjunktiv-ii', 'moegen', 'moechte', 'word-order'],
      instruction:
        'Put the words in the correct order to form a natural Konjunktiv II sentence.',
      prompt: 'I would like to order a coffee.',
      segments: [
        { id: 's1', text: 'Ich' },
        { id: 's2', text: 'möchte' },
        { id: 's3', text: 'gern' },
        { id: 's4', text: 'einen' },
        { id: 's5', text: 'Kaffee' },
        { id: 's6', text: 'bestellen.' },
      ],
      explanation:
        'möchte occupies position 2 as the finite verb, and the infinitive bestellen is sent to the end of the clause: Ich möchte gern einen Kaffee bestellen.',
    },
  ],
};
