import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter082: ChapterDefinition = {
  id: 'chapter-082',
  number: 82,
  slug: 'prepositions-governing-the-genitive',
  title: 'Prepositions Governing the Genitive',
  germanTitle: 'Präpositionen mit Genitiv',
  level: 'B1',
  section: 'prepositions-2',
  objective:
    'Recognise and correctly use the common prepositions that govern the genitive case — trotz, während, wegen, and statt/anstatt — forming the genitive article and noun ending that follow them exactly as learned in Chapter 68, while also recognising the widespread colloquial dative variation as an informal usage note and preferring the genitive in formal writing.',
  prerequisites: [68],
  estimatedMinutes: 30,
  tags: [
    'prepositions',
    'genitive',
    'trotz',
    'waehrend',
    'wegen',
    'statt',
    'anstatt',
    'case-government',
    'register',
    'formal-writing',
  ],
  explanation: {
    introduction: [
      'Chapter 68 introduced the genitive case itself — the articles des and der, and the -s/-es endings on masculine and neuter nouns. This chapter puts that knowledge to work with a small, high-frequency group of prepositions that always govern the genitive: trotz (despite), während (during), wegen (because of), and statt or anstatt (instead of). Whenever one of these words introduces a noun phrase, that noun phrase goes into the genitive, following exactly the same article and ending rules you already know: trotz des Regens, während der Nacht, wegen des Staus, statt eines Autos.',
      'These four prepositions are extremely common in both spoken and written German, but they behave a little unusually compared to the dative and accusative prepositions from earlier chapters: in relaxed everyday speech, German speakers very often use the dative after them instead of the genitive — wegen dem Regen rather than wegen des Regens. This chapter teaches the genitive as the standard, correct form to produce, while also making you aware of the spoken dative variant so you can recognise it and understand why textbooks, teachers, and formal writing still expect the genitive.',
    ],
    rules: [
      {
        id: 'ch82-rule-01',
        heading: 'Four common prepositions that govern the genitive',
        paragraphs: [
          'trotz (despite, in spite of), während (during), wegen (because of, due to), and statt/anstatt (instead of) are the four most frequent prepositions that take the genitive case in standard German. Whatever noun phrase follows one of them must show genitive articles and, where relevant, genitive noun endings.',
          'statt and anstatt are two forms of the same word with the same meaning and the same grammar; anstatt is slightly more formal, but both are used interchangeably before a genitive noun phrase: statt des Autos and anstatt des Autos both mean "instead of the car".',
          'Like all genitive constructions, these prepositional phrases follow the article and ending rules from Chapter 68 exactly: des/eines for masculine and neuter singular nouns (with -s or -es added to the noun itself), der/einer for feminine singular nouns and all plurals (with no added ending on the noun).',
        ],
      },
      {
        id: 'ch82-rule-02',
        heading: 'trotz — despite, in spite of',
        paragraphs: [
          'trotz introduces a fact that does not prevent the main clause from happening, expressing a contrast between an obstacle and an outcome that occurs anyway: Trotz des Regens gehen wir spazieren. (Despite the rain, we are going for a walk.)',
          'The genitive noun phrase after trotz can appear at the start of the sentence, as above, or later in it: Wir gehen trotz des Regens spazieren. Both orders are equally correct; only the position of the finite verb (still in position 2) changes.',
        ],
      },
      {
        id: 'ch82-rule-03',
        heading: 'während — during',
        paragraphs: [
          'während introduces a period of time within which something happens: Während der Ferien fahren wir ans Meer. (During the vacation, we are going to the seaside.)',
          'Note that während also exists as a subordinating conjunction meaning "while", introducing a full clause with the verb at the end (während er arbeitet, ...). As a preposition, however, während is followed by a genitive noun phrase, not a clause: während der Arbeit (during work), not während er arbeitet used as a prepositional phrase.',
        ],
      },
      {
        id: 'ch82-rule-04',
        heading: 'wegen — because of, due to',
        paragraphs: [
          'wegen introduces the reason or cause for something: Wegen der Verspätung mussten wir warten. (Because of the delay, we had to wait.)',
          'wegen is the genitive preposition most frequently affected by the spoken dative variation described later in this chapter, precisely because it is so common in everyday explanations and excuses: wegen des Wetters, wegen der Baustelle, wegen meines Autos.',
        ],
      },
      {
        id: 'ch82-rule-05',
        heading: 'statt / anstatt — instead of',
        paragraphs: [
          'statt and anstatt introduce something that replaces or is chosen over something else: Statt eines Kaffees trinke ich heute einen Tee. (Instead of a coffee, I am drinking a tea today.)',
          'Anstatt des Autos nahmen wir das Fahrrad. (Instead of the car, we took the bike.) Both statt and anstatt take exactly the same genitive endings as trotz, während, and wegen.',
        ],
      },
      {
        id: 'ch82-rule-06',
        heading: 'Genitive forms after these prepositions: the same rules as Chapter 68',
        paragraphs: [
          'No new endings need to be learned here — these prepositions simply trigger the genitive article and noun-ending rules you already know. Masculine and neuter singular nouns take des or eines and add -s or -es to the noun (wegen des Kindes, trotz eines Sturms); feminine singular nouns and all plurals take der or einer and never add an ending to the noun (während der Verspätung, wegen der Kinder).',
          'The hand-picked group of monosyllabic masculine and neuter nouns that add -es also applies here without exception: wegen des Mannes, trotz des Jahres, statt des Wortes — exactly the same nouns and the same -es ending as in Chapter 68.',
        ],
      },
      {
        id: 'ch82-rule-07',
        heading: 'The colloquial dative variation: wegen dem Regen',
        paragraphs: [
          'In everyday spoken German, trotz, während, wegen, and statt/anstatt are very often followed by the dative instead of the genitive: wegen dem Regen, trotz dem Wetter, statt dem Auto. This usage is extremely widespread — you will hear it constantly in casual conversation — but it is still considered informal or non-standard: careful speakers, textbooks, formal writing, and exams expect the genitive.',
          'One practical reason the dative spreads here is that many plural nouns look identical in the genitive and dative when no article distinguishes them, and because the genitive is generally retreating from casual speech in favour of simpler alternatives, exactly as von + dative can replace a possessive genitive (Chapter 68).',
          'For this course, treat the genitive as the form to produce and the target of every exercise; treat the dative variant purely as something to recognise and understand, not as an equally correct alternative to write yourself in formal contexts.',
        ],
      },
      {
        id: 'ch82-rule-08',
        heading: 'Formal written preference',
        paragraphs: [
          'In written German — letters, essays, official documents, news reports, and academic writing — the genitive after trotz, während, wegen, and statt/anstatt remains the expected, correct form. Using the dative in this kind of writing reads as careless or too colloquial for the register.',
          'A useful rule of thumb: the more formal or written the context, the more strongly the genitive is expected; the more casual or spoken the context, the more often you will hear the dative in practice — but "often heard" does not mean "always correct" for careful writing.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch82-table-01',
        title: 'The four genitive prepositions',
        columns: ['Preposition', 'Meaning', 'Example (genitive)'],
        columnCases: [null, null, null],
        rows: [
          ['trotz', 'despite, in spite of', 'Trotz des Regens gehen wir spazieren.'],
          ['während', 'during', 'Während der Ferien fahren wir ans Meer.'],
          ['wegen', 'because of, due to', 'Wegen der Verspätung mussten wir warten.'],
          ['statt / anstatt', 'instead of', 'Statt eines Autos nahmen wir das Fahrrad.'],
        ],
        note: 'All four prepositions govern the genitive in standard, formal German.',
      },
      {
        id: 'ch82-table-02',
        title: 'Genitive noun phrases after these prepositions',
        columns: ['Nominative', 'Genitive noun phrase', 'With preposition'],
        columnCases: [null, 'genitive', null],
        rows: [
          ['der Regen', 'des Regens', 'trotz des Regens'],
          ['die Nacht', 'der Nacht', 'während der Nacht'],
          ['das Kind', 'des Kindes', 'wegen des Kindes'],
          ['die Ferien (pl.)', 'der Ferien', 'während der Ferien'],
          ['ein Auto', 'eines Autos', 'statt eines Autos'],
          ['der Mann', 'des Mannes', 'wegen des Mannes'],
        ],
        note: 'Masculine and neuter singular nouns add -s/-es; feminine and plural nouns take only the article der, with no added noun ending.',
      },
      {
        id: 'ch82-table-03',
        title: 'Formal genitive vs. colloquial dative',
        columns: ['Genitive (formal/written)', 'Dative (colloquial/spoken)', 'English'],
        columnCases: ['genitive', 'dative', null],
        rows: [
          ['wegen des Regens', 'wegen dem Regen', 'because of the rain'],
          ['trotz des Wetters', 'trotz dem Wetter', 'despite the weather'],
          ['während der Pause', 'während der Pause', 'during the break (feminine looks the same)'],
          ['statt des Autos', 'statt dem Auto', 'instead of the car'],
        ],
        note: 'The colloquial dative is widely heard but non-standard; prefer the genitive, especially in writing.',
      },
    ],
    examples: [
      {
        german: 'Trotz des Regens gehen wir spazieren.',
        english: 'Despite the rain, we are going for a walk.',
        highlight: ['Trotz des Regens'],
        explanation: 'Regen is masculine and takes plain -s in the genitive: des Regens.',
      },
      {
        german: 'Wir gehen trotz des schlechten Wetters spazieren.',
        english: 'We are going for a walk despite the bad weather.',
        highlight: ['trotz des schlechten Wetters'],
        explanation: 'Wetter is neuter and takes plain -s; the adjective schlecht takes the genitive ending -en.',
      },
      {
        german: 'Während der Ferien fahren wir ans Meer.',
        english: 'During the vacation, we are going to the seaside.',
        highlight: ['Während der Ferien'],
        explanation: 'Ferien is plural, so the genitive article is der and the noun itself takes no added ending.',
      },
      {
        german: 'Während des Konzerts war es sehr laut.',
        english: 'During the concert, it was very loud.',
        highlight: ['Während des Konzerts'],
        explanation: 'Konzert is neuter and polysyllabic, non-sibilant, so it takes plain -s: des Konzerts.',
      },
      {
        german: 'Wegen der Verspätung mussten wir warten.',
        english: 'Because of the delay, we had to wait.',
        highlight: ['Wegen der Verspätung'],
        explanation: 'Verspätung is feminine, so the genitive article is der and the noun stays unchanged.',
      },
      {
        german: 'Wegen des Staus kamen wir zu spät.',
        english: 'Because of the traffic jam, we arrived too late.',
        highlight: ['Wegen des Staus'],
        explanation: 'Stau is masculine and takes plain -s in the genitive: des Staus.',
      },
      {
        german: 'Statt eines Kaffees trinke ich heute einen Tee.',
        english: 'Instead of a coffee, I am drinking a tea today.',
        highlight: ['Statt eines Kaffees'],
        explanation: 'Kaffee is masculine, so the indefinite genitive article eines is used and the noun adds -s.',
      },
      {
        german: 'Anstatt des Autos nahmen wir das Fahrrad.',
        english: 'Instead of the car, we took the bike.',
        highlight: ['Anstatt des Autos'],
        explanation: 'anstatt is the fuller form of statt, with exactly the same genitive government: des Autos.',
      },
      {
        german: 'Wegen des Kindes musste sie früher gehen.',
        english: 'Because of the child, she had to leave earlier.',
        highlight: ['Wegen des Kindes'],
        explanation: 'Kind is in the hand-picked monosyllabic group that adds -es: des Kindes.',
      },
      {
        german: 'Trotz seiner Krankheit arbeitet er weiter.',
        english: 'Despite his illness, he keeps working.',
        highlight: ['seiner Krankheit'],
        explanation: 'Krankheit is feminine, so the possessive article takes the genitive ending -er: seiner.',
      },
      {
        german: 'Wegen dem Regen bleiben wir zu Hause.',
        english: 'Because of the rain, we are staying home. (colloquial)',
        highlight: ['Wegen dem Regen'],
        explanation: 'This dative form is common in casual speech, but wegen des Regens is the standard, expected form in writing.',
      },
      {
        german: 'Während des Studiums arbeitete er nebenbei.',
        english: 'During his studies, he worked on the side.',
        highlight: ['Während des Studiums'],
        explanation: 'Studium is neuter and takes plain -s in the genitive: des Studiums.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'trotz der Regen',
        correct: 'trotz des Regens',
        explanation: 'Regen is masculine, so the genitive article is des, and the noun itself adds -s: des Regens.',
      },
      {
        incorrect: 'wegen das Kind',
        correct: 'wegen des Kindes',
        explanation: 'wegen governs the genitive, not the accusative; Kind is neuter and in the hand-picked group that adds -es.',
      },
      {
        incorrect: 'während die Ferien',
        correct: 'während der Ferien',
        explanation: 'Ferien is plural, so the genitive article is der, not the nominative/accusative die.',
      },
      {
        incorrect: 'statt einen Kaffee',
        correct: 'statt eines Kaffees',
        explanation: 'statt governs the genitive, so the indefinite article must be eines and the noun adds -s, not the accusative einen Kaffee.',
      },
      {
        incorrect: 'Wegen der Verspätung mussten wir warten wegen der Verspätung.',
        correct: 'Wegen der Verspätung mussten wir warten.',
        explanation: 'A genitive prepositional phrase, like any other sentence element, should appear once, not be repeated.',
      },
      {
        incorrect: 'wegen dem Regen (in a formal essay)',
        correct: 'wegen des Regens',
        explanation: 'The dative after wegen is common in casual speech but is considered non-standard in formal writing, where the genitive is expected.',
      },
    ],
    remember: [
      'trotz (despite), während (during), wegen (because of), and statt/anstatt (instead of) all govern the genitive case.',
      'These prepositions trigger exactly the genitive articles and noun endings from Chapter 68: des/eines with -s or -es for masculine and neuter singular nouns; der/einer with no added ending for feminine singular and all plural nouns.',
      'In casual spoken German, trotz, während, wegen, and statt/anstatt are very often followed by the dative instead (wegen dem Regen); this is widespread but considered informal — the genitive remains the standard, expected form, especially in writing.',
      'statt and anstatt are two equivalent forms of the same word and take identical genitive endings.',
      'While während can also be a subordinating conjunction meaning "while" (with a verb-final clause), as a preposition it is always followed by a genitive noun phrase.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 77,
    requiredCorrectTextInputs: 27,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch82-ex-01',
      chapterNumber: 82,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'trotz'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'despite, in spite of'?",
      options: [
        { id: 'a', text: 'trotz' },
        { id: 'b', text: 'wegen' },
        { id: 'c', text: 'während' },
        { id: 'd', text: 'statt' },
      ],
      correctOptionId: 'a',
      explanation: 'trotz means "despite, in spite of" and governs the genitive.',
    },
    {
      id: 'ch82-ex-02',
      chapterNumber: 82,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'waehrend'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'during'?",
      options: [
        { id: 'a', text: 'während' },
        { id: 'b', text: 'trotz' },
        { id: 'c', text: 'wegen' },
        { id: 'd', text: 'statt' },
      ],
      correctOptionId: 'a',
      explanation: 'während means "during" and governs the genitive.',
    },
    {
      id: 'ch82-ex-03',
      chapterNumber: 82,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'wegen'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'because of, due to'?",
      options: [
        { id: 'a', text: 'wegen' },
        { id: 'b', text: 'trotz' },
        { id: 'c', text: 'während' },
        { id: 'd', text: 'anstatt' },
      ],
      correctOptionId: 'a',
      explanation: 'wegen means "because of, due to" and governs the genitive.',
    },
    {
      id: 'ch82-ex-04',
      chapterNumber: 82,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'statt'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'instead of'?",
      options: [
        { id: 'a', text: 'statt' },
        { id: 'b', text: 'wegen' },
        { id: 'c', text: 'trotz' },
        { id: 'd', text: 'während' },
      ],
      correctOptionId: 'a',
      explanation: 'statt (or anstatt) means "instead of" and governs the genitive.',
    },
    {
      id: 'ch82-ex-05',
      chapterNumber: 82,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'case-government'],
      instruction: 'Choose the case these four prepositions govern in standard German.',
      prompt: 'Welchen Fall verlangen trotz, während, wegen und statt im Standarddeutschen?',
      options: [
        { id: 'a', text: 'Genitiv' },
        { id: 'b', text: 'Dativ' },
        { id: 'c', text: 'Akkusativ' },
        { id: 'd', text: 'Nominativ' },
      ],
      correctOptionId: 'a',
      explanation: 'trotz, während, wegen, and statt/anstatt all govern the genitive case in standard German.',
    },
    {
      id: 'ch82-ex-06',
      chapterNumber: 82,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'masculine', 'trotz'],
      instruction: 'Choose the correct genitive article.',
      prompt: 'Trotz ___ Regens gehen wir spazieren. (der Regen)',
      options: [
        { id: 'a', text: 'des' },
        { id: 'b', text: 'dem' },
        { id: 'c', text: 'den' },
        { id: 'd', text: 'der' },
      ],
      correctOptionId: 'a',
      explanation: 'Regen is masculine, so the genitive definite article is des.',
    },
    {
      id: 'ch82-ex-07',
      chapterNumber: 82,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'feminine', 'waehrend'],
      instruction: 'Choose the correct genitive article.',
      prompt: 'Während ___ Nacht war es sehr kalt. (die Nacht)',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'des' },
        { id: 'c', text: 'dem' },
        { id: 'd', text: 'die' },
      ],
      correctOptionId: 'a',
      explanation: 'Nacht is feminine, so the genitive definite article is der.',
    },
    {
      id: 'ch82-ex-08',
      chapterNumber: 82,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'neuter', 'wegen'],
      instruction: 'Choose the correctly formed genitive noun phrase.',
      prompt: 'Wegen ___ mussten wir früher gehen. (das Kind)',
      options: [
        { id: 'a', text: 'des Kindes' },
        { id: 'b', text: 'des Kind' },
        { id: 'c', text: 'dem Kind' },
        { id: 'd', text: 'der Kindes' },
      ],
      correctOptionId: 'a',
      explanation: 'Kind is neuter and belongs to the hand-picked monosyllabic group that adds -es: des Kindes.',
    },
    {
      id: 'ch82-ex-09',
      chapterNumber: 82,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'plural', 'waehrend'],
      instruction: 'Choose the correctly formed genitive noun phrase.',
      prompt: 'Wir fahren ans Meer ___. (die Ferien)',
      options: [
        { id: 'a', text: 'während der Ferien' },
        { id: 'b', text: 'während des Ferien' },
        { id: 'c', text: 'während den Ferien' },
        { id: 'd', text: 'während die Ferien' },
      ],
      correctOptionId: 'a',
      explanation: 'Ferien is plural, so the genitive article is der and the noun stays unchanged: während der Ferien.',
    },
    {
      id: 'ch82-ex-10',
      chapterNumber: 82,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'indefinite', 'statt'],
      instruction: 'Choose the correctly formed genitive noun phrase.',
      prompt: 'Statt ___ trinke ich heute einen Tee. (ein Kaffee)',
      options: [
        { id: 'a', text: 'eines Kaffees' },
        { id: 'b', text: 'einen Kaffee' },
        { id: 'c', text: 'einem Kaffee' },
        { id: 'd', text: 'einer Kaffee' },
      ],
      correctOptionId: 'a',
      explanation: 'Kaffee is masculine, so the genitive indefinite article eines is used and the noun adds -s: eines Kaffees.',
    },
    {
      id: 'ch82-ex-11',
      chapterNumber: 82,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'sibilant', 'wegen'],
      instruction: 'Choose the correctly formed genitive noun phrase.',
      prompt: 'Wegen ___ kamen wir zu spät. (das Haus, i.e. the traffic near the house)',
      options: [
        { id: 'a', text: 'des Hauses' },
        { id: 'b', text: 'des Haus' },
        { id: 'c', text: 'dem Haus' },
        { id: 'd', text: 'des Hauss' },
      ],
      correctOptionId: 'a',
      explanation: 'Haus is sibilant-final, so it takes -es in the genitive: des Hauses.',
    },
    {
      id: 'ch82-ex-12',
      chapterNumber: 82,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'hand-picked', 'trotz'],
      instruction: 'Choose the correctly formed genitive noun phrase.',
      prompt: 'Trotz ___ arbeitet er weiter. (das Jahr, i.e. despite the difficult year)',
      options: [
        { id: 'a', text: 'des Jahres' },
        { id: 'b', text: 'des Jahrs' },
        { id: 'c', text: 'des Jahr' },
        { id: 'd', text: 'dem Jahr' },
      ],
      correctOptionId: 'a',
      explanation: 'Jahr belongs to the hand-picked monosyllabic group that adds -es: des Jahres.',
    },
    {
      id: 'ch82-ex-13',
      chapterNumber: 82,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'anstatt', 'articles'],
      instruction: 'Choose the correctly formed genitive noun phrase.',
      prompt: 'Anstatt ___ nahmen wir das Fahrrad. (das Auto)',
      options: [
        { id: 'a', text: 'des Autos' },
        { id: 'b', text: 'das Auto' },
        { id: 'c', text: 'dem Auto' },
        { id: 'd', text: 'der Autos' },
      ],
      correctOptionId: 'a',
      explanation: 'Auto is neuter, polysyllabic, and non-sibilant, so it takes plain -s in the genitive: des Autos.',
    },
    {
      id: 'ch82-ex-14',
      chapterNumber: 82,
      order: 14,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['genitive', 'possessive-articles', 'trotz'],
      instruction: 'Choose the correct possessive article ending.',
      prompt: 'Trotz ___ Krankheit arbeitet er weiter. (seine Krankheit)',
      options: [
        { id: 'a', text: 'seiner' },
        { id: 'b', text: 'seines' },
        { id: 'c', text: 'seinem' },
        { id: 'd', text: 'seinen' },
      ],
      correctOptionId: 'a',
      explanation: 'Krankheit is feminine, so the possessive article takes the genitive ending -er: seiner.',
    },
    {
      id: 'ch82-ex-15',
      chapterNumber: 82,
      order: 15,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['genitive', 'preposition-selection', 'wegen'],
      instruction: 'Choose the preposition that best fits the sentence.',
      prompt: '___ des starken Regens fiel das Fußballspiel aus.',
      options: [
        { id: 'a', text: 'Wegen' },
        { id: 'b', text: 'Während' },
        { id: 'c', text: 'Statt' },
        { id: 'd', text: 'Trotzdem' },
      ],
      correctOptionId: 'a',
      explanation: 'wegen introduces a reason or cause, which fits here: because of the heavy rain, the match was cancelled.',
    },
    {
      id: 'ch82-ex-16',
      chapterNumber: 82,
      order: 16,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['genitive', 'preposition-selection', 'waehrend'],
      instruction: 'Choose the preposition that best fits the sentence.',
      prompt: '___ des Konzerts war es sehr laut.',
      options: [
        { id: 'a', text: 'Während' },
        { id: 'b', text: 'Wegen' },
        { id: 'c', text: 'Statt' },
        { id: 'd', text: 'Trotz' },
      ],
      correctOptionId: 'a',
      explanation: 'während indicates a time period during which something happens: during the concert, it was very loud.',
    },
    {
      id: 'ch82-ex-17',
      chapterNumber: 82,
      order: 17,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['genitive', 'preposition-selection', 'trotz'],
      instruction: 'Choose the preposition that best fits the sentence.',
      prompt: '___ des schlechten Wetters gehen wir spazieren.',
      options: [
        { id: 'a', text: 'Trotz' },
        { id: 'b', text: 'Wegen' },
        { id: 'c', text: 'Während' },
        { id: 'd', text: 'Statt' },
      ],
      correctOptionId: 'a',
      explanation: 'trotz signals a contrast — going for a walk anyway despite the bad weather.',
    },
    {
      id: 'ch82-ex-18',
      chapterNumber: 82,
      order: 18,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['register', 'colloquial-dative', 'usage-note'],
      instruction: 'Choose the correct description of this sentence.',
      prompt: 'Wie ist der Satz "Wegen dem Regen bleiben wir zu Hause" einzuordnen?',
      options: [
        { id: 'a', text: 'umgangssprachlich korrekt, aber in formeller Schriftsprache sollte der Genitiv (wegen des Regens) stehen' },
        { id: 'b', text: 'grammatisch falsch in jedem Kontext' },
        { id: 'c', text: 'die einzig richtige Form in geschriebenem Deutsch' },
        { id: 'd', text: 'eine veraltete Form, die niemand mehr benutzt' },
      ],
      correctOptionId: 'a',
      explanation: 'The dative after wegen is widely used in casual speech but is considered informal; formal writing expects the genitive, wegen des Regens.',
    },
    {
      id: 'ch82-ex-19',
      chapterNumber: 82,
      order: 19,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['register', 'formal-written-preference'],
      instruction: 'Choose the sentence more appropriate for a formal written report.',
      prompt: 'Welcher Satz passt besser in einen formellen, schriftlichen Bericht?',
      options: [
        { id: 'a', text: 'Wegen des Staus kamen die Mitarbeiter zu spät zur Besprechung.' },
        { id: 'b', text: 'Wegen dem Stau kamen die Mitarbeiter zu spät zur Besprechung.' },
        { id: 'c', text: 'Wegen der Stau kamen die Mitarbeiter zu spät zur Besprechung.' },
      ],
      correctOptionId: 'a',
      explanation: 'Formal written German expects the genitive after wegen: wegen des Staus, not the colloquial dative wegen dem Stau.',
    },
    {
      id: 'ch82-ex-20',
      chapterNumber: 82,
      order: 20,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['genitive', 'sentence-building', 'statt'],
      instruction: 'Choose the correctly formed sentence.',
      prompt: 'Which sentence correctly expresses: "Instead of a car, we bought a bike."?',
      options: [
        { id: 'a', text: 'Statt eines Autos haben wir ein Fahrrad gekauft.' },
        { id: 'b', text: 'Statt ein Auto haben wir ein Fahrrad gekauft.' },
        { id: 'c', text: 'Statt einem Auto haben wir ein Fahrrad gekauft.' },
        { id: 'd', text: 'Statt der Auto haben wir ein Fahrrad gekauft.' },
      ],
      correctOptionId: 'a',
      explanation: 'Auto is neuter, so the genitive indefinite article eines is required and the noun adds -s: eines Autos.',
    },
    {
      id: 'ch82-ex-21',
      chapterNumber: 82,
      order: 21,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['genitive', 'articles', 'masculine', 'trotz'],
      instruction: 'Write the correct genitive article. Capitalisation is not checked.',
      prompt: 'Trotz ___ Sturms blieben wir draußen. (der Sturm)',
      acceptedAnswers: ['des'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 10,
      explanation: 'Sturm is masculine, so the genitive definite article is des.',
    },
    {
      id: 'ch82-ex-22',
      chapterNumber: 82,
      order: 22,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['genitive', 'articles', 'feminine', 'wegen'],
      instruction: 'Write the correct genitive article. Capitalisation is not checked.',
      prompt: 'Wegen ___ Baustelle mussten wir umfahren. (die Baustelle)',
      acceptedAnswers: ['der'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 10,
      explanation: 'Baustelle is feminine, so the genitive definite article is der.',
    },
    {
      id: 'ch82-ex-23',
      chapterNumber: 82,
      order: 23,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['genitive', 'articles', 'neuter', 'waehrend'],
      instruction: 'Write the correct genitive article. Capitalisation is not checked.',
      prompt: 'Während ___ Studiums arbeitete er nebenbei. (das Studium)',
      acceptedAnswers: ['des'],
      answerMode: 'caseInsensitive',
      placeholder: 'article',
      maxLength: 10,
      explanation: 'Studium is neuter, so the genitive definite article is des.',
    },
    {
      id: 'ch82-ex-24',
      chapterNumber: 82,
      order: 24,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'vocabulary', 'trotz'],
      instruction: 'Write the German preposition. Capitalisation is not checked.',
      prompt: "German for 'despite, in spite of' (governs the genitive):",
      acceptedAnswers: ['trotz'],
      answerMode: 'caseInsensitive',
      placeholder: 'preposition',
      maxLength: 15,
      explanation: 'trotz means "despite, in spite of" and governs the genitive.',
    },
    {
      id: 'ch82-ex-25',
      chapterNumber: 82,
      order: 25,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'vocabulary', 'wegen'],
      instruction: 'Write the German preposition. Capitalisation is not checked.',
      prompt: "German for 'because of, due to' (governs the genitive):",
      acceptedAnswers: ['wegen'],
      answerMode: 'caseInsensitive',
      placeholder: 'preposition',
      maxLength: 15,
      explanation: 'wegen means "because of, due to" and governs the genitive.',
    },
    {
      id: 'ch82-ex-26',
      chapterNumber: 82,
      order: 26,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'sibilant', 'wegen'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'wegen + das Haus →',
      acceptedAnswers: ['des Hauses'],
      answerMode: 'caseInsensitive',
      placeholder: 'des ...',
      maxLength: 25,
      explanation: 'Haus is sibilant-final, so it takes -es in the genitive: des Hauses.',
    },
    {
      id: 'ch82-ex-27',
      chapterNumber: 82,
      order: 27,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'hand-picked', 'trotz'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'trotz + das Kind →',
      acceptedAnswers: ['des Kindes'],
      answerMode: 'caseInsensitive',
      placeholder: 'des ...',
      maxLength: 25,
      explanation: 'Kind is in the hand-picked monosyllabic group, so it takes -es: des Kindes.',
    },
    {
      id: 'ch82-ex-28',
      chapterNumber: 82,
      order: 28,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'plain-s', 'waehrend'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'während + der Sommer →',
      acceptedAnswers: ['des Sommers'],
      answerMode: 'caseInsensitive',
      placeholder: 'des ...',
      maxLength: 25,
      explanation: 'Sommer is masculine, polysyllabic, and non-sibilant, so it takes plain -s: des Sommers.',
    },
    {
      id: 'ch82-ex-29',
      chapterNumber: 82,
      order: 29,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'feminine', 'no-ending', 'wegen'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'wegen + die Verspätung →',
      acceptedAnswers: ['der Verspätung'],
      answerMode: 'caseInsensitive',
      placeholder: 'der ...',
      maxLength: 25,
      explanation: 'Verspätung is feminine, so only the article changes; the noun itself never takes an ending: der Verspätung.',
    },
    {
      id: 'ch82-ex-30',
      chapterNumber: 82,
      order: 30,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'plural', 'no-ending', 'waehrend'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'während + die Ferien →',
      acceptedAnswers: ['der Ferien'],
      answerMode: 'caseInsensitive',
      placeholder: 'der ...',
      maxLength: 25,
      explanation: 'Ferien is plural, so only the article changes to der; the noun stays the same.',
    },
    {
      id: 'ch82-ex-31',
      chapterNumber: 82,
      order: 31,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'indefinite', 'statt'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'statt + ein Kaffee →',
      acceptedAnswers: ['eines Kaffees'],
      answerMode: 'caseInsensitive',
      placeholder: 'eines ...',
      maxLength: 25,
      explanation: 'Kaffee is masculine, so the indefinite genitive article eines is used and the noun adds -s: eines Kaffees.',
    },
    {
      id: 'ch82-ex-32',
      chapterNumber: 82,
      order: 32,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'trotz'],
      instruction: 'Build a complete sentence from the cue words, using the genitive after trotz. Capitalisation and punctuation are checked.',
      prompt: 'wir – gehen – spazieren – trotz – der Regen',
      acceptedAnswers: ['Wir gehen trotz des Regens spazieren.', 'Trotz des Regens gehen wir spazieren.'],
      answerMode: 'normalized',
      placeholder: 'Wir gehen trotz ...',
      maxLength: 60,
      explanation: 'der Regen becomes des Regens in the genitive after trotz.',
    },
    {
      id: 'ch82-ex-33',
      chapterNumber: 82,
      order: 33,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'wegen'],
      instruction: 'Build a complete sentence from the cue words, using the genitive after wegen. Capitalisation and punctuation are checked.',
      prompt: 'wegen – die Verspätung – mussten – wir – warten',
      acceptedAnswers: ['Wegen der Verspätung mussten wir warten.'],
      answerMode: 'normalized',
      placeholder: 'Wegen der Verspätung ...',
      maxLength: 60,
      explanation: 'die Verspätung becomes der Verspätung in the genitive after wegen; only the article changes.',
    },
    {
      id: 'ch82-ex-34',
      chapterNumber: 82,
      order: 34,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'waehrend'],
      instruction: 'Build a complete sentence from the cue words, using the genitive after während. Capitalisation and punctuation are checked.',
      prompt: 'während – die Ferien – fahren – wir – ans Meer',
      acceptedAnswers: ['Während der Ferien fahren wir ans Meer.'],
      answerMode: 'normalized',
      placeholder: 'Während der Ferien ...',
      maxLength: 60,
      explanation: 'die Ferien becomes der Ferien in the genitive after während; the plural noun takes no added ending.',
    },
    {
      id: 'ch82-ex-35',
      chapterNumber: 82,
      order: 35,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'statt'],
      instruction: 'Build a complete sentence from the cue words, using the genitive after statt. Capitalisation and punctuation are checked.',
      prompt: 'statt – das Auto – nahmen – wir – das Fahrrad',
      acceptedAnswers: ['Statt des Autos nahmen wir das Fahrrad.'],
      answerMode: 'normalized',
      placeholder: 'Statt des Autos ...',
      maxLength: 60,
      explanation: 'das Auto becomes des Autos in the genitive after statt; Auto is neuter and takes plain -s.',
    },
    {
      id: 'ch82-ex-36',
      chapterNumber: 82,
      order: 36,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['genitive', 'register', 'transformation', 'wegen'],
      instruction: 'Rewrite the colloquial sentence in standard, formal German using the genitive. Capitalisation and punctuation are checked.',
      prompt: 'Umgangssprachlich: Wegen dem Regen bleiben wir zu Hause. → Standarddeutsch:',
      acceptedAnswers: ['Wegen des Regens bleiben wir zu Hause.'],
      answerMode: 'normalized',
      placeholder: 'Wegen des Regens ...',
      maxLength: 60,
      explanation: 'The formal, written standard replaces the colloquial dative dem Regen with the genitive des Regens.',
    },
    {
      id: 'ch82-ex-37',
      chapterNumber: 82,
      order: 37,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['genitive', 'sentence-building', 'possessive-articles', 'trotz'],
      instruction: 'Build a complete sentence from the cue words, using the genitive possessive article after trotz. Capitalisation and punctuation are checked.',
      prompt: 'trotz – seine Krankheit – arbeitet – er – weiter',
      acceptedAnswers: ['Trotz seiner Krankheit arbeitet er weiter.'],
      answerMode: 'normalized',
      placeholder: 'Trotz seiner Krankheit ...',
      maxLength: 60,
      explanation: 'seine Krankheit is feminine, so the possessive article takes the genitive ending -er: seiner Krankheit.',
    },
    {
      id: 'ch82-ex-38',
      chapterNumber: 82,
      order: 38,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['genitive', 'sentence-building', 'hand-picked', 'wegen'],
      instruction: 'Build a complete sentence from the cue words, using the correct genitive noun ending. Capitalisation and punctuation are checked.',
      prompt: 'wegen – das Jahr – war – der Umsatz – niedriger (i.e. because of the [difficult] year, revenue was lower)',
      acceptedAnswers: ['Wegen des Jahres war der Umsatz niedriger.'],
      answerMode: 'normalized',
      placeholder: 'Wegen des Jahres ...',
      maxLength: 60,
      explanation: 'Jahr is in the hand-picked monosyllabic group that adds -es: wegen des Jahres.',
    },
    {
      id: 'ch82-ex-39',
      chapterNumber: 82,
      order: 39,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'aufgrund'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'on the basis of, due to' (formal, governs the genitive)?",
      options: [
        { id: 'a', text: 'aufgrund' },
        { id: 'b', text: 'angesichts' },
        { id: 'c', text: 'anstelle' },
        { id: 'd', text: 'infolge' },
      ],
      correctOptionId: 'a',
      explanation: 'aufgrund means "on the basis of, due to" and governs the genitive.',
    },
    {
      id: 'ch82-ex-40',
      chapterNumber: 82,
      order: 40,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'angesichts'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'in view of, given, considering'?",
      options: [
        { id: 'a', text: 'angesichts' },
        { id: 'b', text: 'aufgrund' },
        { id: 'c', text: 'infolge' },
        { id: 'd', text: 'anstelle' },
      ],
      correctOptionId: 'a',
      explanation: 'angesichts means "in view of, given, considering" and governs the genitive.',
    },
    {
      id: 'ch82-ex-41',
      chapterNumber: 82,
      order: 41,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'anstelle'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'in place of, instead of' (a formal synonym of statt)?",
      options: [
        { id: 'a', text: 'anstelle' },
        { id: 'b', text: 'aufgrund' },
        { id: 'c', text: 'außerhalb' },
        { id: 'd', text: 'mithilfe' },
      ],
      correctOptionId: 'a',
      explanation: 'anstelle means "in place of, instead of" and governs the genitive, like statt.',
    },
    {
      id: 'ch82-ex-42',
      chapterNumber: 82,
      order: 42,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'ausserhalb'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'outside of'?",
      options: [
        { id: 'a', text: 'außerhalb' },
        { id: 'b', text: 'innerhalb' },
        { id: 'c', text: 'oberhalb' },
        { id: 'd', text: 'unterhalb' },
      ],
      correctOptionId: 'a',
      explanation: 'außerhalb means "outside of" and governs the genitive.',
    },
    {
      id: 'ch82-ex-43',
      chapterNumber: 82,
      order: 43,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'innerhalb'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'within, inside of'?",
      options: [
        { id: 'a', text: 'innerhalb' },
        { id: 'b', text: 'außerhalb' },
        { id: 'c', text: 'diesseits' },
        { id: 'd', text: 'jenseits' },
      ],
      correctOptionId: 'a',
      explanation: 'innerhalb means "within, inside of" and governs the genitive.',
    },
    {
      id: 'ch82-ex-44',
      chapterNumber: 82,
      order: 44,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'meaning', 'infolge'],
      instruction: 'Choose the preposition that matches the English meaning.',
      prompt: "Which preposition means 'as a result of, owing to'?",
      options: [
        { id: 'a', text: 'infolge' },
        { id: 'b', text: 'aufgrund' },
        { id: 'c', text: 'angesichts' },
        { id: 'd', text: 'mithilfe' },
      ],
      correctOptionId: 'a',
      explanation: 'infolge means "as a result of, owing to" and governs the genitive.',
    },
    {
      id: 'ch82-ex-45',
      chapterNumber: 82,
      order: 45,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'neuter', 'oberhalb'],
      instruction: 'Choose the correct genitive article.',
      prompt: 'Oberhalb ___ Dorfes liegt die alte Burg. (das Dorf)',
      options: [
        { id: 'a', text: 'des' },
        { id: 'b', text: 'dem' },
        { id: 'c', text: 'der' },
        { id: 'd', text: 'den' },
      ],
      correctOptionId: 'a',
      explanation: 'Dorf is neuter, so the genitive definite article is des; the noun itself adds -es: des Dorfes.',
    },
    {
      id: 'ch82-ex-46',
      chapterNumber: 82,
      order: 46,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'feminine', 'unterhalb'],
      instruction: 'Choose the correct genitive article.',
      prompt: 'Unterhalb ___ Brücke fließt der Fluss ruhig. (die Brücke)',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'des' },
        { id: 'c', text: 'dem' },
        { id: 'd', text: 'die' },
      ],
      correctOptionId: 'a',
      explanation: 'Brücke is feminine, so the genitive definite article is der.',
    },
    {
      id: 'ch82-ex-47',
      chapterNumber: 82,
      order: 47,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'neuter', 'indefinite', 'mithilfe'],
      instruction: 'Choose the correct genitive article.',
      prompt: 'Mithilfe ___ Wörterbuchs übersetzte sie den Text. (ein Wörterbuch)',
      options: [
        { id: 'a', text: 'eines' },
        { id: 'b', text: 'einer' },
        { id: 'c', text: 'einem' },
        { id: 'd', text: 'ein' },
      ],
      correctOptionId: 'a',
      explanation: 'Wörterbuch is neuter, so the genitive indefinite article is eines: eines Wörterbuchs.',
    },
    {
      id: 'ch82-ex-48',
      chapterNumber: 82,
      order: 48,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['genitive', 'preposition-selection', 'infolge'],
      instruction: 'Choose the preposition that best fits the sentence.',
      prompt: '___ des Unfalls war die Straße mehrere Stunden gesperrt.',
      options: [
        { id: 'a', text: 'Infolge' },
        { id: 'b', text: 'Angesichts' },
        { id: 'c', text: 'Anstelle' },
        { id: 'd', text: 'Innerhalb' },
      ],
      correctOptionId: 'a',
      explanation: 'infolge highlights a direct consequence — the road was closed as a result of the accident.',
    },
    {
      id: 'ch82-ex-49',
      chapterNumber: 82,
      order: 49,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'vocabulary', 'meaning'],
      instruction: 'Match each preposition to its English meaning.',
      prompt: 'Match the genitive prepositions to their meanings.',
      pairs: [
        { id: 'p1', left: 'aufgrund', right: 'on the basis of, due to' },
        { id: 'p2', left: 'angesichts', right: 'in view of, given' },
        { id: 'p3', left: 'anstelle', right: 'in place of, instead of' },
        { id: 'p4', left: 'außerhalb', right: 'outside of' },
        { id: 'p5', left: 'innerhalb', right: 'within, inside of' },
        { id: 'p6', left: 'oberhalb', right: 'above' },
      ],
      explanation: 'All six words are genitive prepositions with distinct, specific meanings used mainly in formal or written German.',
    },
    {
      id: 'ch82-ex-50',
      chapterNumber: 82,
      order: 50,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'vocabulary', 'meaning'],
      instruction: 'Match each preposition to its English meaning.',
      prompt: 'Match the genitive prepositions to their meanings.',
      pairs: [
        { id: 'p1', left: 'unterhalb', right: 'below' },
        { id: 'p2', left: 'diesseits', right: 'on this side of' },
        { id: 'p3', left: 'jenseits', right: 'on the other side of, beyond' },
        { id: 'p4', left: 'mithilfe', right: 'with the help of' },
        { id: 'p5', left: 'infolge', right: 'as a result of, owing to' },
      ],
      explanation: 'diesseits and jenseits form a spatial pair, just like oberhalb/unterhalb and innerhalb/außerhalb.',
    },
    {
      id: 'ch82-ex-51',
      chapterNumber: 82,
      order: 51,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'articles'],
      instruction: 'Match each preposition-plus-noun cue to its correctly formed genitive phrase.',
      prompt: 'Match the cues to the correct genitive noun phrase.',
      pairs: [
        { id: 'p1', left: 'aufgrund + das Wetter', right: 'des Wetters' },
        { id: 'p2', left: 'angesichts + die Lage', right: 'der Lage' },
        { id: 'p3', left: 'anstelle + der Chef', right: 'des Chefs' },
        { id: 'p4', left: 'innerhalb + eine Woche', right: 'einer Woche' },
        { id: 'p5', left: 'jenseits + die Grenze', right: 'der Grenze' },
        { id: 'p6', left: 'mithilfe + ein Wörterbuch', right: 'eines Wörterbuchs' },
      ],
      explanation: 'Masculine and neuter nouns take des/eines with -s or -es; feminine nouns take der/einer with no added ending.',
    },
    {
      id: 'ch82-ex-52',
      chapterNumber: 82,
      order: 52,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'aufgrund'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Aufgrund ___ wurde das Spiel abgesagt. (das Wetter)',
      templateParts: ['Aufgrund ', ' wurde das Spiel abgesagt.'],
      slots: [{ id: 'slot1', correctWord: 'des Wetters' }],
      wordBank: ['des Wetters', 'dem Wetter', 'das Wetter', 'der Wetter'],
      explanation: 'Wetter is neuter and takes plain -s in the genitive: des Wetters.',
    },
    {
      id: 'ch82-ex-53',
      chapterNumber: 82,
      order: 53,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'feminine', 'angesichts'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Angesichts ___ musste die Regierung handeln. (die Lage)',
      templateParts: ['Angesichts ', ' musste die Regierung handeln.'],
      slots: [{ id: 'slot1', correctWord: 'der Lage' }],
      wordBank: ['der Lage', 'die Lage', 'dem Lage', 'des Lage'],
      explanation: 'Lage is feminine, so the genitive article is der and the noun takes no added ending.',
    },
    {
      id: 'ch82-ex-54',
      chapterNumber: 82,
      order: 54,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'masculine', 'anstelle'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Anstelle ___ unterschrieb die Assistentin. (der Chef)',
      templateParts: ['Anstelle ', ' unterschrieb die Assistentin.'],
      slots: [{ id: 'slot1', correctWord: 'des Chefs' }],
      wordBank: ['des Chefs', 'dem Chef', 'den Chef', 'der Chef'],
      explanation: 'Chef is masculine, so the genitive article is des and the noun adds plain -s: des Chefs.',
    },
    {
      id: 'ch82-ex-55',
      chapterNumber: 82,
      order: 55,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'feminine', 'ausserhalb'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Außerhalb ___ ist es viel ruhiger. (die Stadt)',
      templateParts: ['Außerhalb ', ' ist es viel ruhiger.'],
      slots: [{ id: 'slot1', correctWord: 'der Stadt' }],
      wordBank: ['der Stadt', 'die Stadt', 'dem Stadt', 'des Stadt'],
      explanation: 'Stadt is feminine, so the genitive article is der and the noun takes no added ending.',
    },
    {
      id: 'ch82-ex-56',
      chapterNumber: 82,
      order: 56,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'indefinite', 'innerhalb'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Innerhalb ___ muss die Rechnung bezahlt werden. (eine Woche)',
      templateParts: ['Innerhalb ', ' muss die Rechnung bezahlt werden.'],
      slots: [{ id: 'slot1', correctWord: 'einer Woche' }],
      wordBank: ['einer Woche', 'eine Woche', 'einem Woche', 'eines Woche'],
      explanation: 'Woche is feminine, so the genitive indefinite article is einer and the noun takes no added ending.',
    },
    {
      id: 'ch82-ex-57',
      chapterNumber: 82,
      order: 57,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'hand-picked', 'oberhalb'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Oberhalb ___ liegt die alte Burg. (das Dorf)',
      templateParts: ['Oberhalb ', ' liegt die alte Burg.'],
      slots: [{ id: 'slot1', correctWord: 'des Dorfes' }],
      wordBank: ['des Dorfes', 'dem Dorf', 'das Dorf', 'der Dorfes'],
      explanation: 'Dorf belongs to the hand-picked monosyllabic group that adds -es: des Dorfes.',
    },
    {
      id: 'ch82-ex-58',
      chapterNumber: 82,
      order: 58,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'sibilant', 'diesseits'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Diesseits ___ liegt das kleine Dorf. (der Fluss)',
      templateParts: ['Diesseits ', ' liegt das kleine Dorf.'],
      slots: [{ id: 'slot1', correctWord: 'des Flusses' }],
      wordBank: ['des Flusses', 'dem Fluss', 'den Fluss', 'der Flusses'],
      explanation: 'Fluss is sibilant-final, so it takes -es in the genitive: des Flusses.',
    },
    {
      id: 'ch82-ex-59',
      chapterNumber: 82,
      order: 59,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['genitive', 'articles', 'feminine', 'jenseits'],
      instruction: 'Drag the correctly formed genitive noun phrase into the slot.',
      prompt: 'Jenseits ___ beginnt ein anderes Land. (die Grenze)',
      templateParts: ['Jenseits ', ' beginnt ein anderes Land.'],
      slots: [{ id: 'slot1', correctWord: 'der Grenze' }],
      wordBank: ['der Grenze', 'die Grenze', 'dem Grenze', 'des Grenze'],
      explanation: 'Grenze is feminine, so the genitive article is der and the noun takes no added ending.',
    },
    {
      id: 'ch82-ex-60',
      chapterNumber: 82,
      order: 60,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['genitive', 'case-error', 'aufgrund'],
      instruction: 'Find the token that has the wrong case and give its correction.',
      prompt: 'Aufgrund dem Wetters wurde das Spiel abgesagt.',
      tokens: ['Aufgrund', 'dem', 'Wetters', 'wurde', 'das', 'Spiel', 'abgesagt.'],
      errorTokenIndex: 1,
      correction: 'des',
      explanation: 'aufgrund governs the genitive, so the article must be des, not the dative dem.',
    },
    {
      id: 'ch82-ex-61',
      chapterNumber: 82,
      order: 61,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['genitive', 'case-error', 'angesichts'],
      instruction: 'Find the token that has the wrong case and give its correction.',
      prompt: 'Angesichts dem Problems musste die Firma reagieren.',
      tokens: ['Angesichts', 'dem', 'Problems', 'musste', 'die', 'Firma', 'reagieren.'],
      errorTokenIndex: 1,
      correction: 'des',
      explanation: 'angesichts governs the genitive, so the article must be des, not the dative dem.',
    },
    {
      id: 'ch82-ex-62',
      chapterNumber: 82,
      order: 62,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['genitive', 'noun-endings', 'masculine', 'infolge'],
      instruction: 'Find the token that is missing its genitive ending and give its correction.',
      prompt: 'Infolge des Unfall war die Straße gesperrt.',
      tokens: ['Infolge', 'des', 'Unfall', 'war', 'die', 'Straße', 'gesperrt.'],
      errorTokenIndex: 2,
      correction: 'Unfalls',
      explanation: 'Unfall is masculine and polysyllabic, so it takes plain -s in the genitive: des Unfalls.',
    },
    {
      id: 'ch82-ex-63',
      chapterNumber: 82,
      order: 63,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['genitive', 'noun-endings', 'hand-picked', 'unterhalb'],
      instruction: 'Find the token that is missing its genitive ending and give its correction.',
      prompt: 'Unterhalb des Dorf fließt der Fluss ruhig.',
      tokens: ['Unterhalb', 'des', 'Dorf', 'fließt', 'der', 'Fluss', 'ruhig.'],
      errorTokenIndex: 2,
      correction: 'Dorfes',
      explanation: 'Dorf belongs to the hand-picked monosyllabic group that adds -es in the genitive: des Dorfes.',
    },
    {
      id: 'ch82-ex-64',
      chapterNumber: 82,
      order: 64,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['genitive', 'articles', 'gender', 'mithilfe'],
      instruction: 'Find the token with the wrong gendered article and give its correction.',
      prompt: 'Mithilfe einer Wörterbuchs übersetzte sie den Text.',
      tokens: ['Mithilfe', 'einer', 'Wörterbuchs', 'übersetzte', 'sie', 'den', 'Text.'],
      errorTokenIndex: 1,
      correction: 'eines',
      explanation: 'Wörterbuch is neuter, so the genitive indefinite article is eines, not the feminine einer.',
    },
    {
      id: 'ch82-ex-65',
      chapterNumber: 82,
      order: 65,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['genitive', 'case-error', 'infolge'],
      instruction: 'Find the token that has the wrong case and give its correction.',
      prompt: 'Infolge dem Sturms fielen viele Bäume um.',
      tokens: ['Infolge', 'dem', 'Sturms', 'fielen', 'viele', 'Bäume', 'um.'],
      errorTokenIndex: 1,
      correction: 'des',
      explanation: 'infolge governs the genitive, so the article must be des, not the dative dem.',
    },
    {
      id: 'ch82-ex-66',
      chapterNumber: 82,
      order: 66,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'aufgrund'],
      instruction: 'Put the segments into the correct order.',
      prompt: 'Order the segments to form a correct sentence.',
      segments: [
        { id: 'seg1', text: 'Aufgrund des schlechten Wetters' },
        { id: 'seg2', text: 'wurde' },
        { id: 'seg3', text: 'das Spiel' },
        { id: 'seg4', text: 'abgesagt.' },
      ],
      explanation: 'The genitive phrase Aufgrund des schlechten Wetters can open the sentence, with the finite verb wurde in position 2.',
    },
    {
      id: 'ch82-ex-67',
      chapterNumber: 82,
      order: 67,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'ausserhalb'],
      instruction: 'Put the segments into the correct order.',
      prompt: 'Order the segments to form a correct sentence.',
      segments: [
        { id: 'seg1', text: 'Außerhalb der Stadt' },
        { id: 'seg2', text: 'ist' },
        { id: 'seg3', text: 'es' },
        { id: 'seg4', text: 'viel ruhiger.' },
      ],
      explanation: 'Außerhalb der Stadt opens the sentence, with the finite verb ist in position 2.',
    },
    {
      id: 'ch82-ex-68',
      chapterNumber: 82,
      order: 68,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'mithilfe'],
      instruction: 'Put the segments into the correct order.',
      prompt: 'Order the segments to form a correct sentence.',
      segments: [
        { id: 'seg1', text: 'Mithilfe eines Wörterbuchs' },
        { id: 'seg2', text: 'übersetzte' },
        { id: 'seg3', text: 'sie' },
        { id: 'seg4', text: 'den Text.' },
      ],
      explanation: 'Mithilfe eines Wörterbuchs opens the sentence, with the finite verb übersetzte in position 2.',
    },
    {
      id: 'ch82-ex-69',
      chapterNumber: 82,
      order: 69,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'vocabulary', 'angesichts'],
      instruction: 'Write the German preposition. Capitalisation is not checked.',
      prompt: "German for 'in view of, given, considering' (governs the genitive):",
      acceptedAnswers: ['angesichts'],
      answerMode: 'caseInsensitive',
      placeholder: 'preposition',
      maxLength: 15,
      explanation: 'angesichts means "in view of, given, considering" and governs the genitive.',
    },
    {
      id: 'ch82-ex-70',
      chapterNumber: 82,
      order: 70,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['genitive-prepositions', 'vocabulary', 'infolge'],
      instruction: 'Write the German preposition. Capitalisation is not checked.',
      prompt: "German for 'as a result of, owing to' (governs the genitive):",
      acceptedAnswers: ['infolge'],
      answerMode: 'caseInsensitive',
      placeholder: 'preposition',
      maxLength: 15,
      explanation: 'infolge means "as a result of, owing to" and governs the genitive.',
    },
    {
      id: 'ch82-ex-71',
      chapterNumber: 82,
      order: 71,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'noun-endings', 'masculine', 'aufgrund'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'aufgrund + der Unfall →',
      acceptedAnswers: ['des Unfalls'],
      answerMode: 'caseInsensitive',
      placeholder: 'des ...',
      maxLength: 25,
      explanation: 'Unfall is masculine, polysyllabic, and non-sibilant, so it takes plain -s: des Unfalls.',
    },
    {
      id: 'ch82-ex-72',
      chapterNumber: 82,
      order: 72,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'feminine', 'no-ending', 'jenseits'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'jenseits + die Grenze →',
      acceptedAnswers: ['der Grenze'],
      answerMode: 'caseInsensitive',
      placeholder: 'der ...',
      maxLength: 25,
      explanation: 'Grenze is feminine, so only the article changes to der; the noun stays unchanged.',
    },
    {
      id: 'ch82-ex-73',
      chapterNumber: 82,
      order: 73,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['genitive', 'indefinite', 'neuter', 'mithilfe'],
      instruction: 'Write the complete genitive noun phrase (article + noun). Capitalisation is not checked.',
      prompt: 'mithilfe + ein Wörterbuch →',
      acceptedAnswers: ['eines Wörterbuchs'],
      answerMode: 'caseInsensitive',
      placeholder: 'eines ...',
      maxLength: 25,
      explanation: 'Wörterbuch is neuter, so the genitive indefinite article eines is used and the noun adds -s: eines Wörterbuchs.',
    },
    {
      id: 'ch82-ex-74',
      chapterNumber: 82,
      order: 74,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'adjective-endings', 'angesichts'],
      instruction: 'Build a complete sentence from the cue words, using the genitive after angesichts. Capitalisation and punctuation are checked.',
      prompt: 'angesichts – die schwierige Lage – handelte – die Regierung – schnell',
      acceptedAnswers: ['Angesichts der schwierigen Lage handelte die Regierung schnell.'],
      answerMode: 'normalized',
      placeholder: 'Angesichts der schwierigen Lage ...',
      maxLength: 70,
      explanation: 'die schwierige Lage becomes der schwierigen Lage in the genitive: the feminine article changes to der and the adjective takes the genitive ending -en.',
    },
    {
      id: 'ch82-ex-75',
      chapterNumber: 82,
      order: 75,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['genitive', 'sentence-building', 'adjective-endings', 'infolge'],
      instruction: 'Build a complete sentence from the cue words, using the genitive after infolge. Capitalisation and punctuation are checked.',
      prompt: 'infolge – der starke Sturm – fielen – viele Bäume – um',
      acceptedAnswers: ['Infolge des starken Sturms fielen viele Bäume um.'],
      answerMode: 'normalized',
      placeholder: 'Infolge des starken Sturms ...',
      maxLength: 70,
      explanation: 'der starke Sturm becomes des starken Sturms in the genitive: the masculine article changes to des, the noun adds -s, and the adjective takes the genitive ending -en.',
    },
    {
      id: 'ch82-ex-76',
      chapterNumber: 82,
      order: 76,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['genitive', 'register', 'case-government'],
      instruction: 'Complete the sentence about register with one word. Capitalisation is not checked.',
      prompt: 'Anders als wegen und trotz, die in der Umgangssprache oft mit dem Dativ stehen, verlangen aufgrund, infolge und angesichts in formellen Texten immer den ___.',
      acceptedAnswers: ['Genitiv'],
      answerMode: 'caseInsensitive',
      placeholder: 'case',
      maxLength: 15,
      explanation: 'Unlike wegen and trotz, which are frequently heard with the dative in casual speech, formal words like aufgrund, infolge, and angesichts are essentially always used with the genitive.',
    },
    {
      id: 'ch82-ex-77',
      chapterNumber: 82,
      order: 77,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['genitive', 'sentence-building', 'jenseits'],
      instruction: 'Build a complete sentence from the cue words, using the genitive after jenseits. Capitalisation and punctuation are checked.',
      prompt: 'jenseits – die Grenze – beginnt – ein anderes Land',
      acceptedAnswers: ['Jenseits der Grenze beginnt ein anderes Land.'],
      answerMode: 'normalized',
      placeholder: 'Jenseits der Grenze ...',
      maxLength: 60,
      explanation: 'die Grenze becomes der Grenze in the genitive after jenseits; the feminine noun takes no added ending.',
    },
  ],
};
