import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter066: ChapterDefinition = {
  id: 'chapter-066',
  number: 66,
  slug: 'the-verb-lassen',
  title: 'The Verb lassen',
  germanTitle: 'Das Verb lassen',
  level: 'B1',
  section: 'verbs-3',
  objective:
    'Conjugate lassen correctly (including the du/er-sie-es stem change lasse → lässt), use it with a bare infinitive sent to the end of the clause — exactly like a modal verb — to express allowing, causing/arranging for something to be done, and leaving something behind or in place, form sich lassen + infinitive as a passive-like paraphrase for "can be done," and build the perfect tense correctly with the double-infinitive construction when an infinitive follows, versus the plain participle gelassen when lassen stands alone.',
  prerequisites: [5],
  estimatedMinutes: 28,
  tags: [
    'lassen',
    'modal-like-verb',
    'causative',
    'bare-infinitive',
    'sich-lassen',
    'passive-paraphrase',
    'double-infinitive',
    'ersatzinfinitiv',
    'perfect-tense',
    'b1-verbs',
  ],
  explanation: {
    introduction: [
      'lassen is one of the most useful and most flexible verbs in German, and it behaves structurally just like the modal verbs you already know from chapter 5: it conjugates for person, and it sends a bare infinitive — with no zu — to the very end of the clause. Ich lasse mein Auto reparieren (I am having my car repaired) has exactly the same shape as Ich kann mein Auto reparieren (I can repair my car): a conjugated verb in position 2, and an infinitive parked at the end.',
      'What makes lassen tricky is not its grammar but its meaning: depending on context, the same verb can express three quite different ideas in English — allowing someone to do something, arranging or causing someone else to do something for you, and simply leaving something or someone in a place or a state. All three share the same German structure; only the situation tells you which English translation fits.',
      'On top of these three core meanings, lassen has a fourth, very productive use: sich lassen + infinitive, a reflexive construction that works like a passive paraphrase meaning "can be done" — Das Problem lässt sich lösen (The problem can be solved). This pattern connects naturally to the passive voice you may already be studying elsewhere in this course, since both express that something can happen to a subject without naming who does it.',
      'Finally, lassen has a perfect tense with a twist: when it is followed by an infinitive, it forms a double-infinitive construction, just like the modal verbs — ich habe mein Auto reparieren lassen, never "gelassen." But when lassen stands alone, with no infinitive attached, it is a perfectly ordinary weak verb and takes its normal participle gelassen. Telling these two patterns apart is the single most common source of mistakes with this verb.',
    ],
    rules: [
      {
        id: 'ch66-rule-01',
        heading: 'Conjugation: lassen with a stem-vowel change',
        paragraphs: [
          'lassen conjugates in the present tense as: ich lasse, du lässt, er/sie/es lässt, wir lassen, ihr lasst, sie/Sie lassen. Notice that the du- and er/sie/es-forms change the stem vowel from a to ä (lasse → lässt) — the same kind of vowel change you have already seen in strong verbs like fahren (du fährst) or schlafen (du schläfst).',
          'The wir-, ihr-, and sie/Sie-forms keep the plain stem lass- with the regular personal endings: lassen, lasst, lassen. Only du and er/sie/es take the umlaut.',
          'Because the du-form already ends in -ssen → -ss-, no extra -s- is added for the ending: lässt, not lässst. This is the normal spelling simplification you see whenever a verb stem already ends in a sibilant.',
        ],
      },
      {
        id: 'ch66-rule-02',
        heading: 'Structurally a modal verb: bare infinitive at the end',
        paragraphs: [
          'Even though lassen is not one of the six true modal verbs, it behaves exactly like one in the sentence: it occupies position 2, and it sends a plain infinitive — never with zu — to the very end of the clause, forming the same verb bracket (Satzklammer) you already know from können, müssen, wollen, and the rest.',
          'Ich lasse mein Auto reparieren. Er lässt mich fahren. Wir lassen die Kinder spielen. In every case, the infinitive at the end never changes shape, no matter who the subject is — only lassen itself conjugates.',
          'This is worth stating clearly because learners coming from English often want to insert "zu" (mirroring English "to"): Ich lasse mein Auto zu reparieren is wrong. lassen takes a bare infinitive, exactly like a modal verb.',
        ],
      },
      {
        id: 'ch66-rule-03',
        heading: 'Meaning 1: allowing or permitting',
        paragraphs: [
          'The most direct meaning of lassen + infinitive is "to let" or "to allow" someone to do something. Er lässt mich fahren (He lets me drive). Meine Eltern lassen mich nicht lange fernsehen (My parents don\'t let me watch TV for long).',
          'In this meaning, the person who is allowed to act appears as an accusative object of lassen, and the infinitive describes what they are allowed to do. This use is close to English "let" and often overlaps in meaning with dürfen (to be allowed to): Er lässt mich fahren is close in meaning to Ich darf fahren, seen from the other person\'s point of view.',
        ],
      },
      {
        id: 'ch66-rule-04',
        heading: 'Meaning 2: causing or arranging for something to be done',
        paragraphs: [
          'lassen also expresses that the subject arranges for someone else to carry out an action, rather than doing it themselves — the closest English equivalent is "to have something done" or "to get something done." Ich lasse mein Auto reparieren (I am having my car repaired — a mechanic does the work, not me).',
          "This causative meaning is extremely common with services: Ich lasse mir die Haare schneiden (I'm having my hair cut). Wir lassen das Haus renovieren (We're having the house renovated). Notice that when the action is done to or for the subject's own body or belongings, a dative reflexive pronoun (mir, dir, sich, ...) is often added: lässt sich die Haare schneiden (has their hair cut) — this dative sich is a reflexive object, not the sich lassen \"can be done\" pattern from rule 6.",
          'Context is what separates this causative meaning from meaning 1 (allowing): Ich lasse den Elektriker die Lampe reparieren means I am arranging for the electrician to repair the lamp (causing), while Ich lasse den Elektriker in die Wohnung means I am letting the electrician into the apartment (allowing) — the same verb, two different relationships between subject and object.',
        ],
      },
      {
        id: 'ch66-rule-05',
        heading: 'Meaning 3: leaving something or someone in a place or state',
        paragraphs: [
          'The third core meaning of lassen is simply "to leave" — leaving an object behind somewhere, or leaving a person or thing in a particular state. Ich lasse die Tür offen (I\'m leaving the door open). Ich lasse mein Handy zu Hause (I\'m leaving my phone at home).',
          "This meaning frequently appears without any following infinitive at all — just lassen plus a direct object and a location or a state (offen, in Ruhe, allein): Lass mich in Ruhe! (Leave me alone!). Ich lasse dich nicht allein (I won't leave you alone).",
          'Because this "leaving" use has no infinitive complement, it behaves as an ordinary weak verb in the perfect tense: ich habe ... gelassen (see rule 7). This is the clearest signal for telling meaning 3 apart from meanings 1 and 2, which almost always involve a following infinitive.',
        ],
      },
      {
        id: 'ch66-rule-06',
        heading: 'sich lassen + infinitive: a passive-like paraphrase',
        paragraphs: [
          'A very productive fourth pattern combines lassen with the reflexive pronoun sich and a following infinitive to mean "can be done" — the subject undergoes an action that is possible in principle, without saying who would do it. Das Problem lässt sich lösen (The problem can be solved). Diese Tür lässt sich leicht öffnen (This door can be opened easily / opens easily).',
          'This sich lassen pattern is closely related to a können + werden-passive paraphrase: Das Problem lässt sich lösen ≈ Das Problem kann gelöst werden. Both express possibility without an agent, and either is usually acceptable, though sich lassen often sounds a little more compact and idiomatic in everyday speech.',
          'Like every other use of lassen, this pattern takes a bare infinitive with no zu: Das lässt sich nicht ändern (That can\'t be changed), never "Das lässt sich nicht zu ändern."',
        ],
      },
      {
        id: 'ch66-rule-07',
        heading: 'The perfect tense: double infinitive vs. gelassen',
        paragraphs: [
          'When lassen is followed by an infinitive (meanings 1, 2, and the sich lassen pattern), its perfect tense is built with haben plus a double infinitive at the end of the clause — lassen appears in its bare infinitive form instead of the participle gelassen, exactly like the modal verbs you met earlier in this course. Ich habe mein Auto reparieren lassen (I have had my car repaired) — not "Ich habe mein Auto reparieren gelassen."',
          'Er hat mich fahren lassen (He let me drive) shows the same pattern for the allowing meaning: fahren lassen, both infinitives together at the end, with hat in position 2.',
          'When lassen is used alone, with no infinitive complement (meaning 3, "leaving"), it is a completely ordinary weak verb in the perfect tense and takes its normal participle gelassen: Ich habe meinen Schlüssel zu Hause gelassen (I left my key at home). The presence or absence of a following infinitive is exactly what decides which pattern to use.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch66-table-01',
        title: 'lassen — present tense',
        columns: ['Person', 'lassen', 'English'],
        rows: [
          ['ich', 'lasse', 'I let / have done / leave'],
          ['du', 'lässt', 'you let / have done / leave'],
          ['er/sie/es', 'lässt', 'he/she/it lets / has done / leaves'],
          ['wir', 'lassen', 'we let / have done / leave'],
          ['ihr', 'lasst', 'you (pl.) let / have done / leave'],
          ['sie/Sie', 'lassen', 'they/you (formal) let / have done / leave'],
        ],
        note: 'Only du and er/sie/es umlaut the stem vowel (a → ä); the other forms keep the plain stem lass-.',
      },
      {
        id: 'ch66-table-02',
        title: 'The three core meanings of lassen',
        columns: ['Meaning', 'Example (German)', 'English'],
        rows: [
          ['Allowing / permitting', 'Er lässt mich fahren.', 'He lets me drive.'],
          [
            'Causing / arranging for something to be done',
            'Ich lasse mein Auto reparieren.',
            'I am having my car repaired.',
          ],
          [
            'Leaving in a place or state',
            'Ich lasse die Tür offen.',
            "I'm leaving the door open.",
          ],
        ],
      },
      {
        id: 'ch66-table-03',
        title: 'sich lassen + infinitive vs. the werden-passive',
        columns: ['Function', 'sich lassen + infinitive', 'werden-passive', 'English'],
        rows: [
          [
            'expressing possibility',
            'Das Problem lässt sich lösen.',
            'Das Problem kann gelöst werden.',
            'The problem can be solved.',
          ],
          [
            'expressing possibility',
            'Diese Tür lässt sich öffnen.',
            'Diese Tür kann geöffnet werden.',
            'This door can be opened.',
          ],
          [
            'expressing impossibility',
            'Das lässt sich nicht ändern.',
            'Das kann nicht geändert werden.',
            "That can't be changed.",
          ],
        ],
        note: 'Both patterns describe an action that is possible without naming who performs it; sich lassen is often the more compact, everyday-sounding choice.',
      },
      {
        id: 'ch66-table-04',
        title: 'Perfect tense: double infinitive vs. gelassen',
        columns: ['Pattern', 'Perfect tense example', 'English'],
        rows: [
          [
            'lassen + infinitive (causing)',
            'Ich habe mein Auto reparieren lassen.',
            'I have had my car repaired.',
          ],
          [
            'lassen + infinitive (allowing)',
            'Er hat mich fahren lassen.',
            'He let me drive.',
          ],
          [
            'lassen alone (leaving)',
            'Ich habe meinen Schlüssel zu Hause gelassen.',
            'I left my key at home.',
          ],
        ],
        note: 'With a following infinitive, lassen forms a double infinitive (reparieren lassen, fahren lassen) — never gelassen. Alone, it takes the ordinary participle gelassen.',
      },
    ],
    examples: [
      {
        german: 'Er lässt mich fahren.',
        english: 'He lets me drive.',
        highlight: ['lässt', 'fahren'],
        explanation:
          'Meaning 1, allowing: lässt in position 2, the bare infinitive fahren at the end.',
      },
      {
        german: 'Meine Eltern lassen mich nicht lange fernsehen.',
        english: "My parents don't let me watch TV for long.",
        highlight: ['lassen', 'fernsehen'],
        explanation:
          'Allowing (here, negated): lassen sends fernsehen to the end of the clause.',
      },
      {
        german: 'Ich lasse mein Auto reparieren.',
        english: 'I am having my car repaired.',
        highlight: ['lasse', 'reparieren'],
        explanation:
          'Meaning 2, causing/arranging: someone else does the repairing, not the subject.',
      },
      {
        german: 'Ich lasse mir die Haare schneiden.',
        english: "I'm having my hair cut.",
        highlight: ['lasse', 'mir', 'schneiden'],
        explanation:
          "Causative with a dative reflexive pronoun (mir), common for services done to one's own body or belongings.",
      },
      {
        german: 'Ich lasse die Tür offen.',
        english: "I'm leaving the door open.",
        highlight: ['lasse', 'offen'],
        explanation:
          'Meaning 3, leaving something in a state: no infinitive follows, just an adjective describing the resulting state.',
      },
      {
        german: 'Ich habe meinen Schlüssel zu Hause gelassen.',
        english: 'I left my key at home.',
        highlight: ['gelassen'],
        explanation:
          'lassen alone (meaning 3) is a regular weak verb in the perfect, so it takes the participle gelassen.',
      },
      {
        german: 'Ich habe mein Auto reparieren lassen.',
        english: 'I have had my car repaired.',
        highlight: ['reparieren', 'lassen'],
        explanation:
          'With a following infinitive, the perfect tense uses the double-infinitive construction: lassen, not gelassen.',
      },
      {
        german: 'Er hat mich fahren lassen.',
        english: 'He let me drive.',
        highlight: ['fahren', 'lassen'],
        explanation:
          'Same double-infinitive pattern for the allowing meaning: fahren lassen at the end of the clause.',
      },
      {
        german: 'Das Problem lässt sich lösen.',
        english: 'The problem can be solved.',
        highlight: ['lässt', 'sich', 'lösen'],
        explanation:
          'sich lassen + infinitive expresses "can be done" — a passive-like paraphrase without naming who solves it.',
      },
      {
        german: 'Diese Tür lässt sich leicht öffnen.',
        english: 'This door opens easily.',
        highlight: ['lässt', 'sich', 'öffnen'],
        explanation:
          'Another sich lassen example: the door "lets itself" be opened easily, i.e. it can be opened easily.',
      },
      {
        german: 'Das lässt sich nicht ändern.',
        english: "That can't be changed.",
        highlight: ['lässt', 'sich', 'ändern'],
        explanation:
          'Negated sich lassen still takes the bare infinitive: nicht ändern, never "zu ändern."',
      },
      {
        german: 'Lass mich in Ruhe!',
        english: 'Leave me alone!',
        highlight: ['Lass'],
        explanation:
          'Imperative of lassen (meaning 3, leaving someone in a state); du-imperative drops the -t ending: lass, not lässt.',
      },
      {
        german: 'Lass uns gehen!',
        english: "Let's go!",
        highlight: ['Lass', 'gehen'],
        explanation:
          'A very common idiomatic imperative: lass uns + infinitive is the everyday German equivalent of English "let\'s."',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich lasse mein Auto zu reparieren.',
        correct: 'Ich lasse mein Auto reparieren.',
        explanation:
          'lassen takes a bare infinitive with no zu, exactly like a modal verb — zu must never appear before the infinitive.',
      },
      {
        incorrect: 'Ich habe mein Auto reparieren gelassen.',
        correct: 'Ich habe mein Auto reparieren lassen.',
        explanation:
          'When lassen has an infinitive complement, the perfect tense uses the double-infinitive construction (Ersatzinfinitiv): lassen, not gelassen — exactly like können, müssen, and the other modal verbs.',
      },
      {
        incorrect: 'Ich habe meinen Schlüssel zu Hause lassen.',
        correct: 'Ich habe meinen Schlüssel zu Hause gelassen.',
        explanation:
          'When lassen is used alone with no following infinitive (just "leaving" something somewhere), it is a regular weak verb in the perfect and takes its own participle gelassen.',
      },
      {
        incorrect: 'Du lasst mich nicht in Ruhe.',
        correct: 'Du lässt mich nicht in Ruhe.',
        explanation:
          'The du-form of lassen umlauts the stem vowel: lässt, not lasst (lasst is the ihr-form).',
      },
      {
        incorrect: 'Das Problem lässt sich zu lösen.',
        correct: 'Das Problem lässt sich lösen.',
        explanation:
          'sich lassen + infinitive also takes a bare infinitive with no zu — the "can be done" meaning never adds zu before the verb.',
      },
      {
        incorrect: 'Ich lasse reparieren mein Auto.',
        correct: 'Ich lasse mein Auto reparieren.',
        explanation:
          'Like a modal verb, lassen forms a verb bracket: lassen stays in position 2, and the infinitive is sent all the way to the end of the clause, after the object.',
      },
    ],
    remember: [
      'lassen conjugates ich lasse, du lässt, er/sie/es lässt, wir lassen, ihr lasst, sie/Sie lassen — note the a → ä stem change in the du- and er/sie/es-forms.',
      'Like a modal verb, lassen sends a bare infinitive (no zu) to the end of the clause: Ich lasse mein Auto reparieren.',
      'lassen has three core meanings: allowing (Er lässt mich fahren), causing/arranging (Ich lasse mein Auto reparieren), and leaving something or someone in a place or state (Ich lasse die Tür offen).',
      'sich lassen + infinitive is a passive-like paraphrase for "can be done": Das Problem lässt sich lösen ≈ Das Problem kann gelöst werden.',
      'In the perfect tense, when lassen has an infinitive complement, use the double-infinitive construction: ich habe ... reparieren lassen (not gelassen) — exactly like the modal verbs.',
      'When lassen stands alone with no following infinitive (just "leaving" something), it is a regular weak verb in the perfect: ich habe ... gelassen.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 78,
    requiredCorrectTextInputs: 29,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch66-ex-01',
      chapterNumber: 66,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'du-form'],
      instruction: 'Choose the correct form of lassen.',
      prompt: 'Du ___ mich nicht in Ruhe!',
      options: [
        { id: 'a', text: 'lässt' },
        { id: 'b', text: 'lasst' },
        { id: 'c', text: 'lasest' },
        { id: 'd', text: 'lasse' },
      ],
      correctOptionId: 'a',
      explanation:
        'The du-form of lassen umlauts the stem vowel: lässt. lasst is the ihr-form.',
    },
    {
      id: 'ch66-ex-02',
      chapterNumber: 66,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'er-sie-es-form'],
      instruction: 'Choose the correct form of lassen.',
      prompt: 'Er ___ seinen Bruder das Auto fahren.',
      options: [
        { id: 'a', text: 'lässt' },
        { id: 'b', text: 'lasst' },
        { id: 'c', text: 'lassen' },
        { id: 'd', text: 'lässet' },
      ],
      correctOptionId: 'a',
      explanation:
        'The er/sie/es-form of lassen is lässt, with the same umlaut as the du-form.',
    },
    {
      id: 'ch66-ex-03',
      chapterNumber: 66,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'wir-form'],
      instruction: 'Choose the correct form of lassen.',
      prompt: 'Wir ___ das Kind im Garten spielen.',
      options: [
        { id: 'a', text: 'lassen' },
        { id: 'b', text: 'lässt' },
        { id: 'c', text: 'lasst' },
        { id: 'd', text: 'lasen' },
      ],
      correctOptionId: 'a',
      explanation:
        'The wir-form keeps the plain stem with the regular ending: lassen. Only du and er/sie/es umlaut.',
    },
    {
      id: 'ch66-ex-04',
      chapterNumber: 66,
      order: 4,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-allow'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Er lässt mich fahren." mean?',
      options: [
        { id: 'a', text: 'He lets me drive.' },
        { id: 'b', text: 'He drives me somewhere.' },
        { id: 'c', text: 'He leaves me while driving.' },
        { id: 'd', text: 'He makes me drive against my will.' },
      ],
      correctOptionId: 'a',
      explanation:
        'This is the allowing meaning of lassen: the subject permits someone else to do something.',
    },
    {
      id: 'ch66-ex-05',
      chapterNumber: 66,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-cause'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Ich lasse mein Auto reparieren." mean?',
      options: [
        { id: 'a', text: 'I am having my car repaired (someone else does it).' },
        { id: 'b', text: 'I am repairing my car myself.' },
        { id: 'c', text: 'I am leaving my car at the repair shop, unrepaired.' },
        { id: 'd', text: 'I let my car be driven by someone else.' },
      ],
      correctOptionId: 'a',
      explanation:
        'This is the causative meaning: the subject arranges for someone else to carry out the repair.',
    },
    {
      id: 'ch66-ex-06',
      chapterNumber: 66,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-leave'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Ich lasse die Tür offen." mean?',
      options: [
        { id: 'a', text: "I'm leaving the door open." },
        { id: 'b', text: 'I let the door open by itself.' },
        { id: 'c', text: 'I am having the door opened by someone else.' },
        { id: 'd', text: "I'm allowing someone to open the door." },
      ],
      correctOptionId: 'a',
      explanation:
        'With no infinitive following, lassen + object + state describes leaving something in that state.',
    },
    {
      id: 'ch66-ex-07',
      chapterNumber: 66,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'word-order', 'infinitive-placement'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'I am having my car repaired.',
      options: [
        { id: 'a', text: 'Ich lasse mein Auto reparieren.' },
        { id: 'b', text: 'Ich lasse reparieren mein Auto.' },
        { id: 'c', text: 'Ich mein Auto lasse reparieren.' },
        { id: 'd', text: 'Reparieren lasse ich mein Auto.' },
      ],
      correctOptionId: 'a',
      explanation:
        'lassen occupies position 2, the object comes next, and the infinitive reparieren is sent to the end of the clause.',
    },
    {
      id: 'ch66-ex-08',
      chapterNumber: 66,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'bare-infinitive', 'zu'],
      instruction: 'Choose the grammatically correct sentence.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich lasse mein Auto reparieren.' },
        { id: 'b', text: 'Ich lasse mein Auto zu reparieren.' },
        { id: 'c', text: 'Ich lasse zu mein Auto reparieren.' },
        { id: 'd', text: 'Ich lasse reparieren zu mein Auto.' },
      ],
      correctOptionId: 'a',
      explanation:
        'lassen always takes a bare infinitive with no zu, exactly like a modal verb.',
    },
    {
      id: 'ch66-ex-09',
      chapterNumber: 66,
      order: 9,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['lassen', 'sich-lassen', 'meaning'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Das Problem lässt sich lösen." mean?',
      options: [
        { id: 'a', text: 'The problem can be solved.' },
        { id: 'b', text: 'The problem solves itself automatically, without any effort.' },
        { id: 'c', text: 'The problem must be solved immediately.' },
        { id: 'd', text: 'The problem lets someone solve it for free.' },
      ],
      correctOptionId: 'a',
      explanation:
        'sich lassen + infinitive expresses that something can be done — a possibility, not an automatic event or an obligation.',
    },
    {
      id: 'ch66-ex-10',
      chapterNumber: 66,
      order: 10,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['lassen', 'sich-lassen', 'passive-paraphrase'],
      instruction: 'Choose the werden-passive sentence with the same meaning.',
      prompt: 'Diese Tür lässt sich leicht öffnen. ≈ ?',
      options: [
        { id: 'a', text: 'Diese Tür kann leicht geöffnet werden.' },
        { id: 'b', text: 'Diese Tür wird leicht öffnen.' },
        { id: 'c', text: 'Diese Tür hat sich leicht geöffnet.' },
        { id: 'd', text: 'Diese Tür lässt leicht öffnen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'sich lassen + infinitive and können + werden-passive both express that an action is possible without naming who performs it.',
    },
    {
      id: 'ch66-ex-11',
      chapterNumber: 66,
      order: 11,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['lassen', 'perfect-tense', 'double-infinitive'],
      instruction: 'Choose the correct perfect-tense sentence.',
      prompt: 'Perfect tense of: Ich lasse mein Auto reparieren.',
      options: [
        { id: 'a', text: 'Ich habe mein Auto reparieren lassen.' },
        { id: 'b', text: 'Ich habe mein Auto reparieren gelassen.' },
        { id: 'c', text: 'Ich habe mein Auto repariert lassen.' },
        { id: 'd', text: 'Ich habe gelassen mein Auto reparieren.' },
      ],
      correctOptionId: 'a',
      explanation:
        'With a following infinitive, lassen forms a double infinitive in the perfect: reparieren lassen, not gelassen.',
    },
    {
      id: 'ch66-ex-12',
      chapterNumber: 66,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['lassen', 'perfect-tense', 'gelassen'],
      instruction: 'Choose the correct perfect-tense sentence.',
      prompt: 'Perfect tense of: Ich lasse den Schlüssel zu Hause.',
      options: [
        { id: 'a', text: 'Ich habe den Schlüssel zu Hause gelassen.' },
        { id: 'b', text: 'Ich habe den Schlüssel zu Hause lassen.' },
        { id: 'c', text: 'Ich habe den Schlüssel zu Hause gelasst.' },
        { id: 'd', text: 'Ich bin den Schlüssel zu Hause gelassen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'With no following infinitive, lassen is a regular weak verb in the perfect: gelassen, with haben as the auxiliary.',
    },
    {
      id: 'ch66-ex-13',
      chapterNumber: 66,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['lassen', 'meaning-allow', 'context'],
      instruction:
        'Read the exchange and choose the correct meaning of the underlined idea.',
      dialogue: [
        {
          speaker: 'Tim',
          german: 'Mama, darf ich mit Tim ins Kino gehen?',
          english: 'Mum, may I go to the cinema with Tim?',
        },
        {
          speaker: 'Mama',
          german: 'Ja, ich lasse dich gehen, aber sei um 22 Uhr zu Hause.',
          english: "Yes, I'll let you go, but be home by 10 pm.",
        },
      ],
      prompt: 'What does "ich lasse dich gehen" mean here?',
      options: [
        { id: 'a', text: "I'm letting you go (giving permission)." },
        { id: 'b', text: "I'm going with you." },
        { id: 'c', text: "I'm leaving you at the cinema." },
        { id: 'd', text: 'I am having someone take you there.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The context (a request for permission with dürfen) shows this is the allowing meaning of lassen.',
    },
    {
      id: 'ch66-ex-14',
      chapterNumber: 66,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['lassen', 'meaning-cause', 'context'],
      instruction:
        'Read the exchange and choose the correct meaning of the underlined idea.',
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Dein Auto sieht ja neu aus!',
          english: 'Your car looks brand new!',
        },
        {
          speaker: 'Ben',
          german: 'Ja, ich habe es letzte Woche lackieren lassen.',
          english: 'Yes, I had it repainted last week.',
        },
      ],
      prompt: 'What does "ich habe es lackieren lassen" mean here?',
      options: [
        { id: 'a', text: 'I had it repainted (someone else did the work).' },
        { id: 'b', text: 'I repainted it myself.' },
        { id: 'c', text: 'I let it get painted by accident.' },
        { id: 'd', text: 'I left it unpainted.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The double-infinitive perfect (lackieren lassen) with a paint shop context signals the causative meaning: arranging for someone else to do it.',
    },
    {
      id: 'ch66-ex-15',
      chapterNumber: 66,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['lassen', 'meaning-leave', 'context'],
      instruction:
        'Read the exchange and choose the correct meaning of the underlined idea.',
      dialogue: [
        {
          speaker: 'Lena',
          german: 'Wo ist deine Jacke?',
          english: 'Where is your jacket?',
        },
        {
          speaker: 'Paul',
          german: 'Ich habe sie im Büro gelassen.',
          english: 'I left it at the office.',
        },
      ],
      prompt: 'What does "ich habe sie im Büro gelassen" mean here?',
      options: [
        { id: 'a', text: 'I left it at the office (it stayed behind there).' },
        { id: 'b', text: 'I had someone bring it to the office.' },
        { id: 'c', text: 'I let it be taken from the office.' },
        { id: 'd', text: 'I am leaving for the office now.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The plain participle gelassen with no following infinitive marks the "leaving something behind" meaning.',
    },
    {
      id: 'ch66-ex-16',
      chapterNumber: 66,
      order: 16,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['lassen', 'paraphrase', 'modal-verb', 'duerfen'],
      instruction: 'Choose the modal-verb paraphrase with the same meaning.',
      prompt: 'Er lässt mich hier warten. ≈ ?',
      options: [
        { id: 'a', text: 'Ich darf hier warten.' },
        { id: 'b', text: 'Ich muss hier warten.' },
        { id: 'c', text: 'Ich soll hier warten.' },
        { id: 'd', text: 'Ich will hier warten.' },
      ],
      correctOptionId: 'a',
      explanation:
        "The allowing meaning of lassen corresponds to dürfen (permission) seen from the other person's perspective: darf, not muss/soll/will.",
    },
    {
      id: 'ch66-ex-17',
      chapterNumber: 66,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'ich-form'],
      instruction:
        'Write the correct form of lassen for ich. Capitalisation is not checked.',
      prompt: 'ich → lassen (Präsens)',
      acceptedAnswers: ['lasse'],
      answerMode: 'caseInsensitive',
      placeholder: 'lasse',
      maxLength: 15,
      explanation: 'The ich-form of lassen is lasse, with no stem change.',
    },
    {
      id: 'ch66-ex-18',
      chapterNumber: 66,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'du-form', 'umlaut'],
      instruction:
        'Write the correct form of lassen for du. Capitalisation is not checked.',
      prompt: 'du → lassen (Präsens)',
      acceptedAnswers: ['lässt'],
      answerMode: 'caseInsensitive',
      placeholder: 'lässt',
      maxLength: 15,
      explanation: 'The du-form of lassen umlauts the stem vowel: lässt.',
    },
    {
      id: 'ch66-ex-19',
      chapterNumber: 66,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'er-sie-es-form', 'umlaut'],
      instruction:
        'Write the correct form of lassen for er/sie/es. Capitalisation is not checked.',
      prompt: 'er/sie/es → lassen (Präsens)',
      acceptedAnswers: ['lässt'],
      answerMode: 'caseInsensitive',
      placeholder: 'lässt',
      maxLength: 15,
      explanation: 'The er/sie/es-form of lassen also umlauts the stem vowel: lässt.',
    },
    {
      id: 'ch66-ex-20',
      chapterNumber: 66,
      order: 20,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'ihr-form'],
      instruction:
        'Write the correct form of lassen for ihr. Capitalisation is not checked.',
      prompt: 'ihr → lassen (Präsens)',
      acceptedAnswers: ['lasst'],
      answerMode: 'caseInsensitive',
      placeholder: 'lasst',
      maxLength: 15,
      explanation:
        'The ihr-form keeps the plain stem lass- with the regular ending: lasst.',
    },
    {
      id: 'ch66-ex-21',
      chapterNumber: 66,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['lassen', 'sentence-building', 'meaning-allow'],
      instruction:
        'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'er – lassen (Präsens) – mich – fahren',
      acceptedAnswers: ['Er lässt mich fahren.', 'Er lässt mich fahren'],
      answerMode: 'normalized',
      placeholder: 'Er lässt mich fahren.',
      maxLength: 40,
      explanation:
        'lassen conjugates to lässt for er, and the bare infinitive fahren goes to the end: Er lässt mich fahren.',
    },
    {
      id: 'ch66-ex-22',
      chapterNumber: 66,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['lassen', 'sentence-building', 'meaning-cause'],
      instruction:
        'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'ich – lassen (Präsens) – mein Auto – reparieren',
      acceptedAnswers: [
        'Ich lasse mein Auto reparieren.',
        'Ich lasse mein Auto reparieren',
      ],
      answerMode: 'normalized',
      placeholder: 'Ich lasse mein Auto reparieren.',
      maxLength: 45,
      explanation:
        'lassen conjugates to lasse for ich, and reparieren goes to the end of the clause: Ich lasse mein Auto reparieren.',
    },
    {
      id: 'ch66-ex-23',
      chapterNumber: 66,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['lassen', 'sentence-building', 'meaning-leave'],
      instruction:
        'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'ich – lassen (Präsens) – die Tür – offen',
      acceptedAnswers: ['Ich lasse die Tür offen.', 'Ich lasse die Tür offen'],
      answerMode: 'normalized',
      placeholder: 'Ich lasse die Tür offen.',
      maxLength: 40,
      explanation:
        'No infinitive is needed here: lassen + object + state describes leaving something in that state.',
    },
    {
      id: 'ch66-ex-24',
      chapterNumber: 66,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'word-order', 'infinitive-placement', 'unscramble'],
      instruction:
        'Unscramble the words into a correct sentence. Capitalisation and punctuation are checked.',
      prompt: 'reparieren / lässt / er / sein Fahrrad',
      acceptedAnswers: [
        'Er lässt sein Fahrrad reparieren.',
        'Er lässt sein Fahrrad reparieren',
      ],
      answerMode: 'normalized',
      placeholder: 'Er lässt sein Fahrrad reparieren.',
      maxLength: 45,
      explanation:
        'lässt takes position 2, the object sein Fahrrad follows, and the infinitive reparieren is sent to the end.',
    },
    {
      id: 'ch66-ex-25',
      chapterNumber: 66,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'translation', 'meaning-allow'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: 'He lets me drive.',
      acceptedAnswers: ['Er lässt mich fahren.', 'Er lässt mich fahren'],
      answerMode: 'normalized',
      placeholder: 'Er lässt mich fahren.',
      maxLength: 40,
      explanation:
        'lassen expresses allowing here: Er lässt mich fahren, with the bare infinitive fahren at the end.',
    },
    {
      id: 'ch66-ex-26',
      chapterNumber: 66,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'translation', 'meaning-cause', 'reflexive-dative'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: "I'm having my hair cut.",
      acceptedAnswers: [
        'Ich lasse mir die Haare schneiden.',
        'Ich lasse mir die Haare schneiden',
      ],
      answerMode: 'normalized',
      placeholder: 'Ich lasse mir die Haare schneiden.',
      maxLength: 45,
      explanation:
        'The causative meaning with a dative reflexive pronoun mir: Ich lasse mir die Haare schneiden.',
    },
    {
      id: 'ch66-ex-27',
      chapterNumber: 66,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'translation', 'meaning-leave', 'perfect-tense'],
      instruction:
        'Translate into German, using the perfect tense. Capitalisation and punctuation are checked.',
      prompt: 'I left my key at home.',
      acceptedAnswers: [
        'Ich habe meinen Schlüssel zu Hause gelassen.',
        'Ich habe meinen Schlüssel zu Hause gelassen',
      ],
      answerMode: 'normalized',
      placeholder: 'Ich habe meinen Schlüssel zu Hause gelassen.',
      maxLength: 55,
      explanation:
        'lassen alone (no infinitive) is a regular weak verb in the perfect: gelassen.',
    },
    {
      id: 'ch66-ex-28',
      chapterNumber: 66,
      order: 28,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'perfect-tense', 'double-infinitive', 'fill-in'],
      instruction:
        'Complete the sentence with the correct verb form. Capitalisation is not checked.',
      prompt: 'Ich habe mein Auto reparieren ___. (Perfekt von lassen)',
      acceptedAnswers: ['lassen'],
      answerMode: 'caseInsensitive',
      placeholder: 'lassen',
      maxLength: 15,
      explanation:
        'With a following infinitive, the perfect tense of lassen is the double infinitive lassen, not gelassen.',
    },
    {
      id: 'ch66-ex-29',
      chapterNumber: 66,
      order: 29,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'perfect-tense', 'gelassen', 'fill-in'],
      instruction:
        'Complete the sentence with the correct verb form. Capitalisation is not checked.',
      prompt: 'Ich habe den Schlüssel zu Hause ___. (Perfekt von lassen)',
      acceptedAnswers: ['gelassen'],
      answerMode: 'caseInsensitive',
      placeholder: 'gelassen',
      maxLength: 15,
      explanation:
        'With no following infinitive, lassen is a regular weak verb in the perfect: gelassen.',
    },
    {
      id: 'ch66-ex-30',
      chapterNumber: 66,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['lassen', 'sich-lassen', 'translation'],
      instruction:
        'Translate into German, using sich lassen + infinitive. Capitalisation and punctuation are checked.',
      prompt: 'This problem can be solved.',
      acceptedAnswers: [
        'Das Problem lässt sich lösen.',
        'Dieses Problem lässt sich lösen.',
      ],
      answerMode: 'normalized',
      placeholder: 'Das Problem lässt sich lösen.',
      maxLength: 40,
      explanation:
        'sich lassen + infinitive expresses "can be done": Das Problem lässt sich lösen.',
    },
    {
      id: 'ch66-ex-31',
      chapterNumber: 66,
      order: 31,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['lassen', 'paraphrase', 'passive'],
      instruction:
        'Rewrite the sentence using the werden-passive with können, keeping the same meaning. Capitalisation and punctuation are checked.',
      prompt: 'Diese Tür lässt sich leicht öffnen. → werden-Passiv mit können',
      acceptedAnswers: [
        'Diese Tür kann leicht geöffnet werden.',
        'Diese Tür kann leicht geöffnet werden',
      ],
      answerMode: 'normalized',
      placeholder: 'Diese Tür kann leicht geöffnet werden.',
      maxLength: 50,
      explanation:
        'sich lassen + infinitive and können + werden-passive both express possibility without an agent: Diese Tür kann leicht geöffnet werden.',
    },
    {
      id: 'ch66-ex-32',
      chapterNumber: 66,
      order: 32,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['lassen', 'paraphrase', 'modal-verb', 'duerfen'],
      instruction:
        "Rewrite the sentence using dürfen, keeping the same meaning from the speaker's perspective. Capitalisation and punctuation are checked.",
      prompt: 'Er lässt mich hier warten. → Satz mit dürfen (ich)',
      acceptedAnswers: ['Ich darf hier warten.', 'Ich darf hier warten'],
      answerMode: 'normalized',
      placeholder: 'Ich darf hier warten.',
      maxLength: 35,
      explanation:
        'Being let (lassen) to do something corresponds to being allowed (dürfen) to do it: Ich darf hier warten.',
    },
    {
      id: 'ch66-ex-33',
      chapterNumber: 66,
      order: 33,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['lassen', 'meaning-cause', 'waschen'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Ich lasse mein Auto waschen." mean?',
      options: [
        { id: 'a', text: 'I am having my car washed (someone else does it).' },
        { id: 'b', text: 'I am washing my car myself.' },
        { id: 'c', text: 'I am leaving my car unwashed.' },
        { id: 'd', text: 'I let someone borrow my car to wash theirs.' },
      ],
      correctOptionId: 'a',
      explanation:
        'This is the causative meaning: the subject arranges for someone else to wash the car.',
    },
    {
      id: 'ch66-ex-34',
      chapterNumber: 66,
      order: 34,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'ihr-form'],
      instruction: 'Choose the correct form of lassen.',
      prompt: 'Ihr ___ die Kinder zu lange fernsehen.',
      options: [
        { id: 'a', text: 'lasst' },
        { id: 'b', text: 'lässt' },
        { id: 'c', text: 'lassen' },
        { id: 'd', text: 'lasset' },
      ],
      correctOptionId: 'a',
      explanation:
        'The ihr-form keeps the plain stem lass- with the regular ending: lasst.',
    },
    {
      id: 'ch66-ex-35',
      chapterNumber: 66,
      order: 35,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['lassen', 'meaning-allow', 'kommen'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Lass ihn herein kommen." mean?',
      options: [
        { id: 'a', text: 'Let him come in.' },
        { id: 'b', text: 'Make him come in against his will.' },
        { id: 'c', text: 'Leave him outside.' },
        { id: 'd', text: 'He is coming in by himself.' },
      ],
      correctOptionId: 'a',
      explanation:
        'This is the allowing meaning: the subject permits the person to come in.',
    },
    {
      id: 'ch66-ex-36',
      chapterNumber: 66,
      order: 36,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-cause', 'bringen'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Ich lasse das Essen bringen." mean?',
      options: [
        { id: 'a', text: 'I am having the food brought (delivered by someone else).' },
        { id: 'b', text: 'I am bringing the food myself.' },
        { id: 'c', text: 'I am leaving the food behind.' },
        { id: 'd', text: 'I am allowed to bring the food.' },
      ],
      correctOptionId: 'a',
      explanation:
        'This is the causative meaning: the subject arranges for someone else to bring the food.',
    },
    {
      id: 'ch66-ex-37',
      chapterNumber: 66,
      order: 37,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-cause', 'bauen'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Wir lassen ein Haus bauen." mean?',
      options: [
        { id: 'a', text: 'We are having a house built (by a construction company).' },
        { id: 'b', text: 'We are building a house ourselves.' },
        { id: 'c', text: 'We are leaving a house unfinished.' },
        { id: 'd', text: 'We are allowed to build a house.' },
      ],
      correctOptionId: 'a',
      explanation:
        'This is the causative meaning: the subject arranges for a construction company to build the house.',
    },
    {
      id: 'ch66-ex-38',
      chapterNumber: 66,
      order: 38,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-leave', 'idiom'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Lass mich in Ruhe!" mean?',
      options: [
        { id: 'a', text: 'Leave me alone!' },
        { id: 'b', text: 'Let me help you!' },
        { id: 'c', text: 'Bring me some peace and quiet food!' },
        { id: 'd', text: "I'm leaving in a hurry!" },
      ],
      correctOptionId: 'a',
      explanation:
        'in Ruhe lassen is the idiomatic "leaving" meaning: to leave someone alone, undisturbed.',
    },
    {
      id: 'ch66-ex-39',
      chapterNumber: 66,
      order: 39,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['lassen', 'imperative', 'du-form'],
      instruction: 'Choose the correct du-imperative of lassen.',
      prompt: '___ mich in Ruhe!',
      options: [
        { id: 'a', text: 'Lass' },
        { id: 'b', text: 'Lässt' },
        { id: 'c', text: 'Lasst' },
        { id: 'd', text: 'Lasse' },
      ],
      correctOptionId: 'a',
      explanation:
        'The du-imperative of lassen drops the -t ending and the umlaut: lass, not lässt.',
    },
    {
      id: 'ch66-ex-40',
      chapterNumber: 66,
      order: 40,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['lassen', 'sich-lassen', 'waschen'],
      instruction: 'Choose the correct meaning.',
      prompt: 'What does "Diese Jacke lässt sich waschen." mean?',
      options: [
        { id: 'a', text: 'This jacket can be washed.' },
        { id: 'b', text: 'This jacket washes itself automatically.' },
        { id: 'c', text: 'This jacket must be washed immediately.' },
        { id: 'd', text: 'This jacket lets someone wash it for free.' },
      ],
      correctOptionId: 'a',
      explanation:
        'sich lassen + infinitive expresses that something can be done — a possibility, not an automatic event or obligation.',
    },
    {
      id: 'ch66-ex-41',
      chapterNumber: 66,
      order: 41,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['lassen', 'idiom', 'wissen'],
      instruction:
        'Read the exchange and choose the correct meaning of the underlined idea.',
      dialogue: [
        {
          speaker: 'Sofia',
          german: 'Kommst du morgen zur Party?',
          english: 'Are you coming to the party tomorrow?',
        },
        {
          speaker: 'Max',
          german: 'Ich bin nicht sicher. Ich lasse dich wissen, wann ich Bescheid weiß.',
          english: "I'm not sure. I'll let you know once I find out.",
        },
      ],
      prompt: 'What does "ich lasse dich wissen" mean here?',
      options: [
        { id: 'a', text: 'I will let you know / inform you.' },
        { id: 'b', text: 'I will let you decide.' },
        { id: 'c', text: 'I will leave you uninformed.' },
        { id: 'd', text: 'I will ask you to know.' },
      ],
      correctOptionId: 'a',
      explanation:
        'jemanden etwas wissen lassen is an idiomatic use of the allowing meaning: to let someone know / inform them.',
    },
    {
      id: 'ch66-ex-42',
      chapterNumber: 66,
      order: 42,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['lassen', 'meaning-allow', 'meaning-cause', 'context'],
      instruction:
        'Read the exchange and choose the correct meaning of the underlined idea.',
      dialogue: [
        {
          speaker: 'Chef',
          german: 'Was macht der Elektriker hier?',
          english: 'What is the electrician doing here?',
        },
        {
          speaker: 'Mitarbeiter',
          german: 'Ich lasse den Elektriker die Lampe reparieren.',
          english: "I'm having the electrician repair the lamp.",
        },
      ],
      prompt:
        'Which meaning of lassen is used in "Ich lasse den Elektriker die Lampe reparieren"?',
      options: [
        {
          id: 'a',
          text: 'Causing/arranging: the speaker arranges for the electrician to do the repair.',
        },
        { id: 'b', text: 'Allowing: the speaker permits the electrician to enter.' },
        { id: 'c', text: 'Leaving: the speaker leaves the lamp broken.' },
        { id: 'd', text: 'sich lassen: the lamp can repair itself.' },
      ],
      correctOptionId: 'a',
      explanation:
        'With a skilled tradesperson and a task, this is the causative meaning: arranging for the electrician to carry out the repair.',
    },
    {
      id: 'ch66-ex-43',
      chapterNumber: 66,
      order: 43,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'sie-Sie-form'],
      instruction:
        'Write the correct form of lassen for sie/Sie. Capitalisation is not checked.',
      prompt: 'sie/Sie (Plural/formal) → lassen (Präsens)',
      acceptedAnswers: ['lassen'],
      answerMode: 'caseInsensitive',
      placeholder: 'lassen',
      maxLength: 15,
      explanation:
        'The sie/Sie-form of lassen keeps the plain stem with the regular ending: lassen.',
    },
    {
      id: 'ch66-ex-44',
      chapterNumber: 66,
      order: 44,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['lassen', 'conjugation', 'wir-form'],
      instruction:
        'Write the correct form of lassen for wir. Capitalisation is not checked.',
      prompt: 'wir → lassen (Präsens)',
      acceptedAnswers: ['lassen'],
      answerMode: 'caseInsensitive',
      placeholder: 'lassen',
      maxLength: 15,
      explanation: 'The wir-form keeps the plain stem with the regular ending: lassen.',
    },
    {
      id: 'ch66-ex-45',
      chapterNumber: 66,
      order: 45,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['lassen', 'sentence-building', 'meaning-cause', 'waschen'],
      instruction:
        'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'ich – lassen (Präsens) – mein Auto – waschen',
      acceptedAnswers: ['Ich lasse mein Auto waschen.', 'Ich lasse mein Auto waschen'],
      answerMode: 'normalized',
      placeholder: 'Ich lasse mein Auto waschen.',
      maxLength: 40,
      explanation:
        'lassen conjugates to lasse for ich, and waschen goes to the end of the clause: Ich lasse mein Auto waschen.',
    },
    {
      id: 'ch66-ex-46',
      chapterNumber: 66,
      order: 46,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['lassen', 'sentence-building', 'meaning-cause', 'bauen'],
      instruction:
        'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'wir – lassen (Präsens) – ein Haus – bauen',
      acceptedAnswers: ['Wir lassen ein Haus bauen.', 'Wir lassen ein Haus bauen'],
      answerMode: 'normalized',
      placeholder: 'Wir lassen ein Haus bauen.',
      maxLength: 40,
      explanation:
        'lassen conjugates to lassen for wir, and bauen goes to the end of the clause: Wir lassen ein Haus bauen.',
    },
    {
      id: 'ch66-ex-47',
      chapterNumber: 66,
      order: 47,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['lassen', 'sentence-building', 'meaning-cause', 'bringen'],
      instruction:
        'Build a complete sentence from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'sie (sg.) – lassen (Präsens) – das Essen – bringen',
      acceptedAnswers: ['Sie lässt das Essen bringen.', 'Sie lässt das Essen bringen'],
      answerMode: 'normalized',
      placeholder: 'Sie lässt das Essen bringen.',
      maxLength: 40,
      explanation:
        'lassen conjugates to lässt for sie (singular), and bringen goes to the end: Sie lässt das Essen bringen.',
    },
    {
      id: 'ch66-ex-48',
      chapterNumber: 66,
      order: 48,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'translation', 'idiom'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: "Let's go!",
      acceptedAnswers: ['Lass uns gehen!', 'Lass uns gehen'],
      answerMode: 'normalized',
      placeholder: 'Lass uns gehen!',
      maxLength: 25,
      explanation:
        'lass uns + infinitive is the everyday German equivalent of English "let\'s": Lass uns gehen!',
    },
    {
      id: 'ch66-ex-49',
      chapterNumber: 66,
      order: 49,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'translation', 'idiom', 'meaning-leave'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: 'Leave me alone!',
      acceptedAnswers: ['Lass mich in Ruhe!', 'Lass mich in Ruhe'],
      answerMode: 'normalized',
      placeholder: 'Lass mich in Ruhe!',
      maxLength: 25,
      explanation: 'in Ruhe lassen means "to leave alone": Lass mich in Ruhe!',
    },
    {
      id: 'ch66-ex-50',
      chapterNumber: 66,
      order: 50,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'perfect-tense', 'double-infinitive', 'fill-in', 'bauen'],
      instruction:
        'Complete the sentence with the correct verb form. Capitalisation is not checked.',
      prompt: 'Wir haben ein Haus bauen ___. (Perfekt von lassen)',
      acceptedAnswers: ['lassen'],
      answerMode: 'caseInsensitive',
      placeholder: 'lassen',
      maxLength: 15,
      explanation:
        'With a following infinitive, the perfect tense of lassen is the double infinitive lassen, not gelassen.',
    },
    {
      id: 'ch66-ex-51',
      chapterNumber: 66,
      order: 51,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['lassen', 'perfect-tense', 'gelassen', 'fill-in'],
      instruction:
        'Complete the sentence with the correct verb form. Capitalisation is not checked.',
      prompt: 'Ich habe die Tür offen ___. (Perfekt von lassen)',
      acceptedAnswers: ['gelassen'],
      answerMode: 'caseInsensitive',
      placeholder: 'gelassen',
      maxLength: 15,
      explanation:
        'With no following infinitive, lassen is a regular weak verb in the perfect: gelassen.',
    },
    {
      id: 'ch66-ex-52',
      chapterNumber: 66,
      order: 52,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['lassen', 'sich-lassen', 'translation', 'waschen'],
      instruction:
        'Translate into German, using sich lassen + infinitive. Capitalisation and punctuation are checked.',
      prompt: 'This jacket can be washed.',
      acceptedAnswers: [
        'Diese Jacke lässt sich waschen.',
        'Diese Jacke lässt sich waschen',
      ],
      answerMode: 'normalized',
      placeholder: 'Diese Jacke lässt sich waschen.',
      maxLength: 40,
      explanation:
        'sich lassen + infinitive expresses "can be done": Diese Jacke lässt sich waschen.',
    },
    {
      id: 'ch66-ex-53',
      chapterNumber: 66,
      order: 53,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['lassen', 'translation', 'idiom', 'wissen'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: 'Let me know when you arrive.',
      acceptedAnswers: [
        'Lass mich wissen, wann du ankommst.',
        'Lass mich wissen, wann du ankommst',
      ],
      answerMode: 'normalized',
      placeholder: 'Lass mich wissen, wann du ankommst.',
      maxLength: 45,
      explanation:
        'jemanden etwas wissen lassen means "to let someone know": Lass mich wissen, wann du ankommst.',
    },
    {
      id: 'ch66-ex-54',
      chapterNumber: 66,
      order: 54,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: [
        'lassen',
        'word-order',
        'infinitive-placement',
        'unscramble',
        'waschen',
      ],
      instruction:
        'Unscramble the words into a correct sentence. Capitalisation and punctuation are checked.',
      prompt: 'waschen / lässt / er / sein Auto',
      acceptedAnswers: ['Er lässt sein Auto waschen.', 'Er lässt sein Auto waschen'],
      answerMode: 'normalized',
      placeholder: 'Er lässt sein Auto waschen.',
      maxLength: 40,
      explanation:
        'lässt takes position 2, the object sein Auto follows, and the infinitive waschen is sent to the end.',
    },
    {
      id: 'ch66-ex-55',
      chapterNumber: 66,
      order: 55,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['lassen', 'translation', 'meaning-cause', 'machen'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: 'I am having the bed made.',
      acceptedAnswers: ['Ich lasse das Bett machen.', 'Ich lasse das Bett machen'],
      answerMode: 'normalized',
      placeholder: 'Ich lasse das Bett machen.',
      maxLength: 40,
      explanation:
        'The causative meaning: someone else makes the bed for the subject: Ich lasse das Bett machen.',
    },
    {
      id: 'ch66-ex-56',
      chapterNumber: 66,
      order: 56,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['lassen', 'translation', 'idiom'],
      instruction: 'Translate into German. Capitalisation and punctuation are checked.',
      prompt: "Let's go to the cinema!",
      acceptedAnswers: ['Lass uns ins Kino gehen!', 'Lass uns ins Kino gehen'],
      answerMode: 'normalized',
      placeholder: 'Lass uns ins Kino gehen!',
      maxLength: 35,
      explanation: 'lass uns + infinitive expresses "let\'s": Lass uns ins Kino gehen!',
    },
    {
      id: 'ch66-ex-57',
      chapterNumber: 66,
      order: 57,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['lassen', 'word-order', 'meaning-cause'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Ich – lasse – mein Auto – reparieren.',
      segments: [
        { id: 'ch66-ex57-s1', text: 'Ich' },
        { id: 'ch66-ex57-s2', text: 'lasse' },
        { id: 'ch66-ex57-s3', text: 'mein Auto' },
        { id: 'ch66-ex57-s4', text: 'reparieren.' },
      ],
      explanation:
        'lassen occupies position 2, and the bare infinitive reparieren is sent to the end: Ich lasse mein Auto reparieren.',
    },
    {
      id: 'ch66-ex-58',
      chapterNumber: 66,
      order: 58,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['lassen', 'word-order', 'meaning-allow'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Er – lässt – mich – fahren.',
      segments: [
        { id: 'ch66-ex58-s1', text: 'Er' },
        { id: 'ch66-ex58-s2', text: 'lässt' },
        { id: 'ch66-ex58-s3', text: 'mich' },
        { id: 'ch66-ex58-s4', text: 'fahren.' },
      ],
      explanation:
        'lässt occupies position 2, mich is the accusative object, and fahren is the bare infinitive at the end.',
    },
    {
      id: 'ch66-ex-59',
      chapterNumber: 66,
      order: 59,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['lassen', 'word-order', 'meaning-cause', 'bauen'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Wir – lassen – ein Haus – bauen.',
      segments: [
        { id: 'ch66-ex59-s1', text: 'Wir' },
        { id: 'ch66-ex59-s2', text: 'lassen' },
        { id: 'ch66-ex59-s3', text: 'ein Haus' },
        { id: 'ch66-ex59-s4', text: 'bauen.' },
      ],
      explanation:
        'lassen occupies position 2, and bauen is sent to the end of the clause: Wir lassen ein Haus bauen.',
    },
    {
      id: 'ch66-ex-60',
      chapterNumber: 66,
      order: 60,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: [
        'lassen',
        'word-order',
        'meaning-cause',
        'reflexive-dative',
        'schneiden',
      ],
      instruction: 'Put the words in the correct order.',
      prompt: 'Ich – lasse – mir – die Haare – schneiden.',
      segments: [
        { id: 'ch66-ex60-s1', text: 'Ich' },
        { id: 'ch66-ex60-s2', text: 'lasse' },
        { id: 'ch66-ex60-s3', text: 'mir' },
        { id: 'ch66-ex60-s4', text: 'die Haare' },
        { id: 'ch66-ex60-s5', text: 'schneiden.' },
      ],
      explanation:
        'The dative reflexive mir follows lasse, then the object die Haare, then the bare infinitive schneiden at the end.',
    },
    {
      id: 'ch66-ex-61',
      chapterNumber: 66,
      order: 61,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['lassen', 'perfect-tense', 'double-infinitive', 'word-order'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Ich – habe – mein Auto – reparieren – lassen.',
      segments: [
        { id: 'ch66-ex61-s1', text: 'Ich' },
        { id: 'ch66-ex61-s2', text: 'habe' },
        { id: 'ch66-ex61-s3', text: 'mein Auto' },
        { id: 'ch66-ex61-s4', text: 'reparieren' },
        { id: 'ch66-ex61-s5', text: 'lassen.' },
      ],
      explanation:
        'The perfect tense with a following infinitive uses the double infinitive at the end: reparieren lassen, with habe in position 2.',
    },
    {
      id: 'ch66-ex-62',
      chapterNumber: 66,
      order: 62,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['lassen', 'word-order', 'meaning-cause', 'machen'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Ich – lasse – das Bett – machen.',
      segments: [
        { id: 'ch66-ex62-s1', text: 'Ich' },
        { id: 'ch66-ex62-s2', text: 'lasse' },
        { id: 'ch66-ex62-s3', text: 'das Bett' },
        { id: 'ch66-ex62-s4', text: 'machen.' },
      ],
      explanation:
        'lasse occupies position 2, and the bare infinitive machen is sent to the end: Ich lasse das Bett machen.',
    },
    {
      id: 'ch66-ex-63',
      chapterNumber: 66,
      order: 63,
      type: 'sentenceOrdering',
      level: 'controlled',
      grammarFocus: ['lassen', 'imperative', 'idiom'],
      instruction: 'Put the words in the correct order.',
      prompt: 'Lass – mich – in Ruhe!',
      segments: [
        { id: 'ch66-ex63-s1', text: 'Lass' },
        { id: 'ch66-ex63-s2', text: 'mich' },
        { id: 'ch66-ex63-s3', text: 'in Ruhe!' },
      ],
      explanation:
        'The du-imperative lass comes first, followed by the object mich and the idiom in Ruhe.',
    },
    {
      id: 'ch66-ex-64',
      chapterNumber: 66,
      order: 64,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: [
        'lassen',
        'perfect-tense',
        'double-infinitive',
        'meaning-allow',
        'word-order',
      ],
      instruction: 'Put the words in the correct order.',
      prompt: 'Er – hat – mich – fahren – lassen.',
      segments: [
        { id: 'ch66-ex64-s1', text: 'Er' },
        { id: 'ch66-ex64-s2', text: 'hat' },
        { id: 'ch66-ex64-s3', text: 'mich' },
        { id: 'ch66-ex64-s4', text: 'fahren' },
        { id: 'ch66-ex64-s5', text: 'lassen.' },
      ],
      explanation:
        'The perfect tense of the allowing meaning also uses the double infinitive: fahren lassen, with hat in position 2.',
    },
    {
      id: 'ch66-ex-65',
      chapterNumber: 66,
      order: 65,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-cause', 'reparieren'],
      instruction: 'Fill in the correct bare infinitive.',
      prompt: 'Ich lasse mein Auto ___.',
      templateParts: ['Ich lasse mein Auto ', '.'],
      slots: [{ id: 'ch66-ex65-slot1', correctWord: 'reparieren' }],
      wordBank: ['reparieren', 'waschen', 'repariert', 'fahren'],
      explanation:
        'The causative meaning here calls for the bare infinitive reparieren, not the participle repariert.',
    },
    {
      id: 'ch66-ex-66',
      chapterNumber: 66,
      order: 66,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-allow', 'fahren'],
      instruction: 'Fill in the correct bare infinitive.',
      prompt: 'Er lässt mich ___.',
      templateParts: ['Er lässt mich ', '.'],
      slots: [{ id: 'ch66-ex66-slot1', correctWord: 'fahren' }],
      wordBank: ['fahren', 'fährt', 'gefahren', 'kommen'],
      explanation:
        'The allowing meaning here calls for the bare infinitive fahren, not the conjugated fährt or the participle gefahren.',
    },
    {
      id: 'ch66-ex-67',
      chapterNumber: 66,
      order: 67,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-cause', 'bauen'],
      instruction: 'Fill in the correct bare infinitive.',
      prompt: 'Wir lassen das Haus ___.',
      templateParts: ['Wir lassen das Haus ', '.'],
      slots: [{ id: 'ch66-ex67-slot1', correctWord: 'bauen' }],
      wordBank: ['bauen', 'gebaut', 'baut', 'machen'],
      explanation:
        'The causative meaning here calls for the bare infinitive bauen, not the participle gebaut or the conjugated baut.',
    },
    {
      id: 'ch66-ex-68',
      chapterNumber: 66,
      order: 68,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-cause', 'reflexive-dative', 'schneiden'],
      instruction: 'Fill in the correct bare infinitive.',
      prompt: 'Ich lasse mir die Haare ___.',
      templateParts: ['Ich lasse mir die Haare ', '.'],
      slots: [{ id: 'ch66-ex68-slot1', correctWord: 'schneiden' }],
      wordBank: ['schneiden', 'geschnitten', 'schneidet', 'waschen'],
      explanation:
        'The causative meaning here calls for the bare infinitive schneiden, not the participle geschnitten.',
    },
    {
      id: 'ch66-ex-69',
      chapterNumber: 66,
      order: 69,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning-cause', 'bringen'],
      instruction: 'Fill in the correct bare infinitive.',
      prompt: 'Ich lasse das Essen ___.',
      templateParts: ['Ich lasse das Essen ', '.'],
      slots: [{ id: 'ch66-ex69-slot1', correctWord: 'bringen' }],
      wordBank: ['bringen', 'gebracht', 'bringt', 'kommen'],
      explanation:
        'The causative meaning here calls for the bare infinitive bringen, not the participle gebracht.',
    },
    {
      id: 'ch66-ex-70',
      chapterNumber: 66,
      order: 70,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['lassen', 'sich-lassen', 'öffnen'],
      instruction: 'Fill in the correct bare infinitive.',
      prompt: 'Diese Tür lässt sich leicht ___.',
      templateParts: ['Diese Tür lässt sich leicht ', '.'],
      slots: [{ id: 'ch66-ex70-slot1', correctWord: 'öffnen' }],
      wordBank: ['öffnen', 'geöffnet', 'öffnet', 'schließen'],
      explanation:
        'sich lassen + infinitive takes the bare infinitive öffnen, not the participle geöffnet.',
    },
    {
      id: 'ch66-ex-71',
      chapterNumber: 66,
      order: 71,
      type: 'matching',
      level: 'controlled',
      grammarFocus: ['lassen', 'meaning', 'translation'],
      instruction: 'Match each German sentence to its English meaning.',
      prompt: 'Match the sentence with the correct meaning.',
      pairs: [
        { id: 'ch66-ex71-p1', left: 'Er lässt mich fahren.', right: 'He lets me drive.' },
        {
          id: 'ch66-ex71-p2',
          left: 'Ich lasse mein Auto reparieren.',
          right: 'I am having my car repaired.',
        },
        {
          id: 'ch66-ex71-p3',
          left: 'Ich lasse die Tür offen.',
          right: "I'm leaving the door open.",
        },
        {
          id: 'ch66-ex71-p4',
          left: 'Wir lassen ein Haus bauen.',
          right: 'We are having a house built.',
        },
        { id: 'ch66-ex71-p5', left: 'Lass mich in Ruhe!', right: 'Leave me alone!' },
      ],
      explanation:
        'Each sentence illustrates one of the three core meanings of lassen: allowing, causing/arranging, and leaving.',
    },
    {
      id: 'ch66-ex-72',
      chapterNumber: 66,
      order: 72,
      type: 'matching',
      level: 'production',
      grammarFocus: ['lassen', 'perfect-tense', 'translation'],
      instruction: 'Match each German sentence to its English meaning.',
      prompt: 'Match the perfect-tense sentence with the correct meaning.',
      pairs: [
        {
          id: 'ch66-ex72-p1',
          left: 'Ich habe mein Auto reparieren lassen.',
          right: 'I have had my car repaired.',
        },
        {
          id: 'ch66-ex72-p2',
          left: 'Er hat mich fahren lassen.',
          right: 'He let me drive.',
        },
        {
          id: 'ch66-ex72-p3',
          left: 'Ich habe meinen Schlüssel zu Hause gelassen.',
          right: 'I left my key at home.',
        },
        {
          id: 'ch66-ex72-p4',
          left: 'Wir haben das Haus bauen lassen.',
          right: 'We had the house built.',
        },
      ],
      explanation:
        'A following infinitive gives the double infinitive lassen; no infinitive gives the ordinary participle gelassen.',
    },
    {
      id: 'ch66-ex-73',
      chapterNumber: 66,
      order: 73,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['lassen', 'sich-lassen', 'passive-paraphrase'],
      instruction: 'Match each sich lassen sentence to its werden-passive equivalent.',
      prompt:
        'Match the sich lassen sentence with the equivalent werden-passive sentence.',
      pairs: [
        {
          id: 'ch66-ex73-p1',
          left: 'Das Problem lässt sich lösen.',
          right: 'Das Problem kann gelöst werden.',
        },
        {
          id: 'ch66-ex73-p2',
          left: 'Diese Tür lässt sich öffnen.',
          right: 'Diese Tür kann geöffnet werden.',
        },
        {
          id: 'ch66-ex73-p3',
          left: 'Das lässt sich nicht ändern.',
          right: 'Das kann nicht geändert werden.',
        },
        {
          id: 'ch66-ex73-p4',
          left: 'Diese Jacke lässt sich waschen.',
          right: 'Diese Jacke kann gewaschen werden.',
        },
      ],
      explanation:
        'sich lassen + infinitive and können + werden-passive both express possibility without naming an agent.',
    },
    {
      id: 'ch66-ex-74',
      chapterNumber: 66,
      order: 74,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['lassen', 'paraphrase', 'modal-verb', 'duerfen'],
      instruction: 'Match each lassen sentence to its dürfen paraphrase.',
      prompt: 'Match the lassen sentence with the equivalent dürfen sentence.',
      pairs: [
        { id: 'ch66-ex74-p1', left: 'Er lässt mich fahren.', right: 'Ich darf fahren.' },
        {
          id: 'ch66-ex74-p2',
          left: 'Sie lässt mich hier warten.',
          right: 'Ich darf hier warten.',
        },
        {
          id: 'ch66-ex74-p3',
          left: 'Meine Eltern lassen mich ins Kino gehen.',
          right: 'Ich darf ins Kino gehen.',
        },
        {
          id: 'ch66-ex74-p4',
          left: 'Der Lehrer lässt uns früher gehen.',
          right: 'Wir dürfen früher gehen.',
        },
      ],
      explanation:
        "The allowing meaning of lassen corresponds to dürfen (permission) seen from the other person's perspective.",
    },
    {
      id: 'ch66-ex-75',
      chapterNumber: 66,
      order: 75,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['lassen', 'idiom', 'imperative'],
      instruction: 'Match each idiomatic lassen expression to its English meaning.',
      prompt: 'Match the expression with the correct meaning.',
      pairs: [
        { id: 'ch66-ex75-p1', left: 'Lass mich in Ruhe!', right: 'Leave me alone!' },
        { id: 'ch66-ex75-p2', left: 'Lass uns gehen!', right: "Let's go!" },
        {
          id: 'ch66-ex75-p3',
          left: 'Lass mich wissen, wann du kommst.',
          right: 'Let me know when you arrive.',
        },
        { id: 'ch66-ex75-p4', left: 'Lass ihn hereinkommen.', right: 'Let him come in.' },
      ],
      explanation:
        'These are common idiomatic imperatives built on the three core meanings of lassen.',
    },
    {
      id: 'ch66-ex-76',
      chapterNumber: 66,
      order: 76,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['lassen', 'perfect-tense', 'double-infinitive', 'error-correction'],
      instruction: 'Find the token that uses the wrong form, and correct it.',
      prompt:
        'Ein Freund erzählt, warum er nicht selbst gefahren ist. Etwas stimmt nicht.',
      tokens: ['Er', 'hat', 'mich', 'fahren', 'gelassen', '.'],
      errorTokenIndex: 4,
      correction: 'lassen',
      explanation:
        'With a following infinitive, the perfect tense of lassen uses the double infinitive lassen, not the participle gelassen.',
    },
    {
      id: 'ch66-ex-77',
      chapterNumber: 66,
      order: 77,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['lassen', 'conjugation', 'du-form', 'error-correction'],
      instruction: 'Find the token that uses the wrong form, and correct it.',
      prompt: 'Ein Kind beschwert sich bei seinem Bruder. Etwas stimmt nicht.',
      tokens: ['Du', 'lasst', 'mich', 'nicht', 'in', 'Ruhe', '.'],
      errorTokenIndex: 1,
      correction: 'lässt',
      explanation:
        'The du-form of lassen umlauts the stem vowel: lässt, not lasst (lasst is the ihr-form).',
    },
    {
      id: 'ch66-ex-78',
      chapterNumber: 66,
      order: 78,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['lassen', 'perfect-tense', 'gelassen', 'error-correction'],
      instruction: 'Find the token that uses the wrong form, and correct it.',
      prompt: 'Jemand erklärt, warum er ohne Schlüssel dasteht. Etwas stimmt nicht.',
      tokens: ['Ich', 'habe', 'den', 'Schlüssel', 'zu', 'Hause', 'lassen', '.'],
      errorTokenIndex: 6,
      correction: 'gelassen',
      explanation:
        'With no following infinitive, lassen is a regular weak verb in the perfect and takes the participle gelassen, not the bare infinitive lassen.',
    },
  ],
};
