import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter081: ChapterDefinition = {
  id: 'chapter-081',
  number: 81,
  slug: 'comparative-constructions-with-je-desto',
  title: 'Comparative Constructions with je ... desto',
  germanTitle: 'Je-desto-Sätze',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Build proportional comparisons with je ... desto (and its interchangeable variant je ... umso): place a comparative form directly after je to open a verb-final subordinate clause, place a matching comparative directly after desto/umso to open a verb-second main clause in which the finite verb immediately follows the desto/umso + comparative unit, and correctly punctuate the comma between the two clauses.',
  prerequisites: [42, 43],
  estimatedMinutes: 30,
  tags: [
    'je-desto',
    'umso',
    'proportional-comparison',
    'comparative',
    'verb-final',
    'verb-second',
    'subordinate-clause',
    'word-order',
    'position-one',
    'punctuation',
  ],
  explanation: {
    introduction: [
      'German expresses a proportional relationship — "the more X, the more Y" — with the two-part construction je ... desto (or je ... umso): Je mehr er lernt, desto besser wird er. (The more he studies, the better he gets.) The first clause states a changing condition; the second clause states the change that results from it.',
      'This construction combines two word-order patterns you already know separately. The je-clause is a subordinate clause, so the finite verb goes to the very end, exactly like after weil or dass. The desto/umso-clause is a main clause in which desto (or umso) plus a comparative fills position 1, so the finite verb comes second, directly after that unit, and the subject follows.',
      'Both clauses always contain a comparative form, reusing exactly the comparative forms from Chapter 42 (regular -er, umlaut, and the five irregulars) — je and desto/umso are never followed by the plain, uncompared form of an adjective or adverb. A comma always separates the two clauses.',
    ],
    rules: [
      {
        id: 'ch81-rule-01',
        heading: 'The basic pattern: je ... desto/umso for proportional comparison',
        paragraphs: [
          'German expresses a proportional relationship — as one thing changes, another changes with it — with the two-part construction je ... desto (or je ... umso): Je mehr er lernt, desto besser wird er. (The more he studies, the better he gets.) The je-clause states the changing condition; the desto/umso-clause states the resulting change.',
          'Unlike the paired conjunctions from Chapter 80, je and desto/umso do not join two parallel elements of equal rank — they link a subordinate clause to a main clause, and each clause has its own distinct word order, covered in the next two rules.',
        ],
      },
      {
        id: 'ch81-rule-02',
        heading: 'Verb-final order after je',
        paragraphs: [
          'je is a subordinating conjunction, so it behaves like weil, dass, or wenn: it pushes the finite verb to the very end of its clause. Je mehr Zeit ich habe, ... (The more time I have, ...) — habe is delayed to the end, exactly as in Ich weiß, dass ich mehr Zeit habe.',
          'The comparative form (mehr, älter, schneller, ...) comes directly after je, at the very front of the clause; the subject and any objects follow, with the finite verb last: Je öfter sie übt, ... — subject sie, then the verb übt at the very end.',
        ],
      },
      {
        id: 'ch81-rule-03',
        heading: 'Verb-second order after desto/umso',
        paragraphs: [
          'desto (or umso) plus its comparative form together occupy position 1 of the second clause, exactly like any other element that opens a German main clause. The finite verb therefore comes second — directly after desto + comparative — and the subject follows the verb: desto besser wird er (desto besser = position 1, wird = verb in position 2, er = subject).',
          'Never separate desto from its comparative, and never insert the verb between them: desto wird er besser is wrong. The verb must come right after the whole desto besser unit, not inside it.',
        ],
      },
      {
        id: 'ch81-rule-04',
        heading: 'The comma before desto/umso',
        paragraphs: [
          'A comma always separates the je-clause from the desto/umso-clause, exactly as a comma separates any subordinate clause from the clause it depends on: Je mehr er lernt, desto besser wird er.',
          'Leaving out the comma is a punctuation mistake even when the sentence is still understandable — the comma is required, not optional, in written German.',
        ],
      },
      {
        id: 'ch81-rule-05',
        heading: 'je and desto/umso must be followed directly by a comparative',
        paragraphs: [
          'Both je and desto/umso require an immediately following comparative form — never the plain (positive) form of the adjective or adverb: je mehr, je besser, je schneller; desto mehr, desto besser, desto schneller. Je viel or desto gut are ungrammatical; the comparative (mehr, besser) must be used instead.',
          'When the comparative modifies a noun, the noun follows the comparative, and the whole phrase still counts as a single unit at the front of the clause: je mehr Geld, desto mehr Zeit.',
        ],
      },
      {
        id: 'ch81-rule-06',
        heading: 'Reusing the comparative forms from Chapter 42',
        paragraphs: [
          'The je ... desto construction uses exactly the same comparative forms you already learned: the irregulars gut/besser, viel/mehr, gern/lieber, hoch/höher, nah/näher, and the umlaut comparatives such as alt/älter, groß/größer, lang/länger, kurz/kürzer, warm/wärmer, kalt/kälter, stark/stärker. No new comparative forms exist for this construction — only the sentence pattern around them is new.',
        ],
      },
      {
        id: 'ch81-rule-07',
        heading: 'umso as an interchangeable alternative to desto',
        paragraphs: [
          'umso can replace desto in any je ... desto sentence with no change in meaning or word order: Je mehr sie übt, umso sicherer wird sie. means exactly the same as ... desto sicherer wird sie. desto is more frequent overall, but umso is common too, especially in written and somewhat more formal German.',
          'umso (not desto) is also occasionally used on its own, without a preceding je-clause, to mean "all the more": Er hat hart gearbeitet — umso verdienter ist sein Erfolg. This standalone use is less common and not the focus of this chapter, but it helps to recognize it.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch81-table-01',
        title: 'The je ... desto sentence pattern',
        columns: ['Clause', 'Opening element (position 1)', 'Verb position', 'Example'],
        rows: [
          [
            'je-clause (subordinate)',
            'je + comparative',
            'verb-final (finite verb at the very end)',
            'Je mehr er lernt',
          ],
          [
            'desto/umso-clause (main)',
            'desto/umso + comparative',
            'verb-second (finite verb right after the position-1 unit)',
            'desto besser wird er',
          ],
        ],
        note: 'Join the two clauses with a comma: Je mehr er lernt, desto besser wird er.',
      },
      {
        id: 'ch81-table-02',
        title: 'Comparative forms reused in je ... desto sentences',
        columns: ['Base form', 'Comparative', 'Example with je ... desto'],
        rows: [
          ['gut', 'besser', 'Je mehr er übt, desto besser wird er.'],
          ['viel', 'mehr', 'Je mehr Geld sie verdient, desto mehr gibt sie aus.'],
          ['gern', 'lieber', 'Je mehr Zeit sie hat, desto lieber liest sie.'],
          ['hoch', 'höher', 'Je höher die Preise steigen, desto weniger kaufen die Leute.'],
          ['nah', 'näher', 'Je näher der Termin rückt, desto nervöser wird er.'],
          ['alt', 'älter', 'Je älter man wird, desto weiser wird man.'],
          ['groß', 'größer', 'Je größer das Haus ist, desto teurer ist die Miete.'],
          ['lang', 'länger', 'Je länger der Winter dauert, desto ungeduldiger werden die Leute.'],
          ['kurz', 'kürzer', 'Je kürzer die Tage werden, desto früher wird es dunkel.'],
          ['warm', 'wärmer', 'Je wärmer es wird, desto mehr Leute gehen schwimmen.'],
          ['kalt', 'kälter', 'Je kälter es draußen ist, desto länger bleiben wir drinnen.'],
          ['stark', 'stärker', 'Je stärker der Wind weht, desto höher werden die Wellen.'],
        ],
        note: 'These are the same comparative forms from Chapter 42 — no new forms exist for the je ... desto construction.',
      },
    ],
    examples: [
      {
        german: 'Je mehr er lernt, desto besser wird er.',
        english: 'The more he studies, the better he gets.',
        highlight: ['Je mehr', 'desto besser'],
        explanation:
          'je mehr er lernt keeps the verb (lernt) at the end; desto besser wird er has the verb (wird) directly after desto besser.',
      },
      {
        german: 'Je älter man wird, desto weiser wird man.',
        english: 'The older one gets, the wiser one becomes.',
        highlight: ['Je älter', 'desto weiser'],
        explanation: 'alt has the umlaut comparative älter; both clauses follow the standard je ... desto word order.',
      },
      {
        german: 'Je schneller du fährst, desto gefährlicher wird es.',
        english: 'The faster you drive, the more dangerous it becomes.',
        highlight: ['Je schneller', 'desto gefährlicher'],
        explanation: 'A regular -er comparative in both clauses; fährst and wird show verb-final and verb-second order.',
      },
      {
        german: 'Je mehr Geld sie verdient, desto mehr gibt sie aus.',
        english: 'The more money she earns, the more she spends.',
        highlight: ['Je mehr Geld', 'desto mehr'],
        explanation:
          'mehr Geld (comparative + noun) forms one unit after je; the separable verb ausgeben splits as gibt ... aus in the verb-second clause.',
      },
      {
        german: 'Je länger der Winter dauert, desto ungeduldiger werden die Leute.',
        english: 'The longer the winter lasts, the more impatient people become.',
        highlight: ['Je länger', 'desto ungeduldiger'],
        explanation: 'lang takes the umlaut comparative länger; the desto-clause subject die Leute follows the verb werden.',
      },
      {
        german: 'Je früher wir aufstehen, desto mehr schaffen wir.',
        english: 'The earlier we get up, the more we get done.',
        highlight: ['Je früher', 'desto mehr'],
        explanation:
          'The separable verb aufstehen stays together at the end of the verb-final je-clause, just as it does after weil or dass.',
      },
      {
        german: 'Je weniger er isst, desto schwächer fühlt er sich.',
        english: 'The less he eats, the weaker he feels.',
        highlight: ['Je weniger', 'desto schwächer'],
        explanation: 'wenig forms its comparative regularly as weniger; the reflexive pronoun sich follows the subject er after inversion.',
      },
      {
        german: 'Je heißer es wird, desto mehr Wasser trinken wir.',
        english: 'The hotter it gets, the more water we drink.',
        highlight: ['Je heißer', 'desto mehr Wasser'],
        explanation: 'desto mehr Wasser (comparative + noun) fills position 1 as a unit; the verb trinken follows directly.',
      },
      {
        german: 'Je besser du Deutsch sprichst, desto leichter findest du einen Job.',
        english: 'The better you speak German, the more easily you will find a job.',
        highlight: ['Je besser', 'desto leichter'],
        explanation: 'gut has the irregular comparative besser, used here adverbially to modify sprichst.',
      },
      {
        german: 'Je öfter sie übt, desto sicherer wird sie.',
        english: 'The more often she practices, the more confident she becomes.',
        highlight: ['Je öfter', 'desto sicherer'],
        explanation: 'A regular comparative of the adverb oft; both clauses follow the standard pattern.',
      },
      {
        german: 'Je näher der Prüfungstermin rückt, desto nervöser wird er.',
        english: 'The closer the exam date gets, the more nervous he becomes.',
        highlight: ['Je näher', 'desto nervöser'],
        explanation: 'nah has the irregular comparative näher, with an inserted h.',
      },
      {
        german: 'Je mehr man hat, desto mehr will man.',
        english: 'The more one has, the more one wants.',
        highlight: ['Je mehr', 'desto mehr'],
        explanation: 'A common proverb-like sentence: the same comparative, mehr, appears in both clauses.',
      },
      {
        german: 'Je mehr sie übt, umso sicherer wird sie.',
        english: 'The more she practices, the more confident she becomes.',
        highlight: ['umso sicherer'],
        explanation: 'umso replaces desto here with no change in meaning or word order.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Je mehr lernt er, desto besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'je opens a subordinate clause, so the finite verb must stand at the very end (lernt), not in second position as in a main clause.',
      },
      {
        incorrect: 'Je mehr er lernt, desto wird er besser.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'desto and its comparative form one inseparable unit in position 1; the finite verb must come directly after desto besser, not be inserted between them.',
      },
      {
        incorrect: 'Je mehr er lernt desto besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation: 'A comma is always required between the je-clause and the desto/umso-clause.',
      },
      {
        incorrect: 'Je er mehr lernt, desto besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'The comparative must come directly after je, not after the subject; je mehr forms a fixed unit at the very start of the clause.',
      },
      {
        incorrect: 'Je viel er arbeitet, desto müder wird er.',
        correct: 'Je mehr er arbeitet, desto müder wird er.',
        explanation: 'viel is irregular; only its comparative form mehr may follow je, never the plain base form viel.',
      },
      {
        incorrect: 'Desto mehr er lernt, je besser wird er.',
        correct: 'Je mehr er lernt, desto besser wird er.',
        explanation:
          'The clause order is fixed: je opens the condition clause and desto/umso opens the result clause; swapping the two conjunctions is incorrect.',
      },
    ],
    remember: [
      'Pattern: je + comparative + verb-final clause, desto/umso + comparative + verb-second clause.',
      'je is a subordinating conjunction: it sends the finite verb to the very end of its clause.',
      'desto (or umso) plus the comparative together fill position 1 of the second clause, so the finite verb comes immediately after them, then the subject.',
      'Always place a comma between the je-clause and the desto/umso-clause.',
      'je and desto/umso must each be followed directly by a comparative — never by the plain base form (je mehr, not je viel).',
      'umso is used exactly like desto and can replace it anywhere; desto is simply more common.',
      'Reuse the comparative forms you already know, including the irregulars (mehr, besser, lieber, höher, näher) and the umlaut forms (älter, größer, länger, kürzer, wärmer, kälter, stärker).',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 100,
    requiredCorrectTextInputs: 22,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch81-ex-01',
      chapterNumber: 81,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'conjunction-choice'],
      instruction: 'Choose the word that opens the subordinate (verb-final) clause.',
      prompt: 'Welches Wort leitet den Nebensatz (Verb am Ende) einer proportionalen Vergleichskonstruktion ein?',
      options: [
        { id: 'a', text: 'je' },
        { id: 'b', text: 'desto' },
        { id: 'c', text: 'wenn' },
        { id: 'd', text: 'als' },
      ],
      correctOptionId: 'a',
      explanation: 'je is the subordinating conjunction that opens the je-clause and sends the finite verb to the end.',
    },
    {
      id: 'ch81-ex-02',
      chapterNumber: 81,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'conjunction-choice'],
      instruction: 'Choose the word that opens the following main (verb-second) clause.',
      prompt: 'Welches Wort leitet den Hauptsatz (Verb an zweiter Stelle) ein, der auf den je-Satz folgt?',
      options: [
        { id: 'a', text: 'desto' },
        { id: 'b', text: 'dass' },
        { id: 'c', text: 'weil' },
        { id: 'd', text: 'obwohl' },
      ],
      correctOptionId: 'a',
      explanation: 'desto (or umso) opens the following main clause, together with a comparative, and triggers verb-second order.',
    },
    {
      id: 'ch81-ex-03',
      chapterNumber: 81,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ er lernt, desto besser wird er.',
      options: [
        { id: 'a', text: 'mehr' },
        { id: 'b', text: 'viel' },
        { id: 'c', text: 'mehrer' },
        { id: 'd', text: 'meister' },
      ],
      correctOptionId: 'a',
      explanation: 'viel is irregular; its comparative form is mehr, not viel or mehrer.',
    },
    {
      id: 'ch81-ex-04',
      chapterNumber: 81,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je mehr er lernt, desto ___ wird er.',
      options: [
        { id: 'a', text: 'besser' },
        { id: 'b', text: 'guter' },
        { id: 'c', text: 'gutier' },
        { id: 'd', text: 'mehr' },
      ],
      correctOptionId: 'a',
      explanation: 'gut has the irregular comparative besser.',
    },
    {
      id: 'ch81-ex-05',
      chapterNumber: 81,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ man wird, desto weiser wird man.',
      options: [
        { id: 'a', text: 'älter' },
        { id: 'b', text: 'alter' },
        { id: 'c', text: 'ältester' },
        { id: 'd', text: 'mehr alt' },
      ],
      correctOptionId: 'a',
      explanation: 'alt takes an umlaut in the comparative: alt -> älter.',
    },
    {
      id: 'ch81-ex-06',
      chapterNumber: 81,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ die Preise steigen, desto weniger kaufen die Leute.',
      options: [
        { id: 'a', text: 'höher' },
        { id: 'b', text: 'hocher' },
        { id: 'c', text: 'höcher' },
        { id: 'd', text: 'hochster' },
      ],
      correctOptionId: 'a',
      explanation: 'hoch is irregular: hoch -> höher (the ch drops).',
    },
    {
      id: 'ch81-ex-07',
      chapterNumber: 81,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ der Prüfungstermin rückt, desto nervöser wird er.',
      options: [
        { id: 'a', text: 'näher' },
        { id: 'b', text: 'naher' },
        { id: 'c', text: 'nächer' },
        { id: 'd', text: 'nährer' },
      ],
      correctOptionId: 'a',
      explanation: 'nah is irregular: nah -> näher (an extra h is inserted).',
    },
    {
      id: 'ch81-ex-08',
      chapterNumber: 81,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-final'],
      instruction: 'Choose the sentence with correct word order in the je-clause.',
      prompt: 'Welcher Satz hat die richtige Wortstellung im je-Satz?',
      options: [
        { id: 'a', text: 'Je mehr er lernt, desto besser wird er.' },
        { id: 'b', text: 'Je mehr lernt er, desto besser wird er.' },
        { id: 'c', text: 'Je er mehr lernt, desto besser wird er.' },
      ],
      correctOptionId: 'a',
      explanation:
        'je introduces a subordinate clause, so the finite verb (lernt) must stand at the very end, directly after the subject er; it cannot appear in second position or before the comparative.',
    },
    {
      id: 'ch81-ex-09',
      chapterNumber: 81,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-second'],
      instruction: 'Choose the sentence with correct word order in the desto-clause.',
      prompt: 'Welcher Satz hat die richtige Wortstellung im desto-Satz?',
      options: [
        { id: 'a', text: 'Je mehr er lernt, desto besser wird er.' },
        { id: 'b', text: 'Je mehr er lernt, desto wird er besser.' },
        { id: 'c', text: 'Je mehr er lernt, desto er wird besser.' },
      ],
      correctOptionId: 'a',
      explanation:
        'desto plus the comparative (desto besser) fills position 1, so the finite verb (wird) must come immediately afterward, then the subject (er).',
    },
    {
      id: 'ch81-ex-10',
      chapterNumber: 81,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['punctuation', 'comma'],
      instruction: 'Choose the sentence with correct comma placement.',
      prompt: 'Welcher Satz ist richtig mit Komma?',
      options: [
        { id: 'a', text: 'Je mehr er lernt, desto besser wird er.' },
        { id: 'b', text: 'Je mehr er lernt desto besser wird er.' },
        { id: 'c', text: 'Je, mehr er lernt, desto besser wird er.' },
      ],
      correctOptionId: 'a',
      explanation: 'A comma always separates the je-clause from the desto/umso-clause; no comma is placed after je itself.',
    },
    {
      id: 'ch81-ex-11',
      chapterNumber: 81,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['umso', 'je-desto-pattern'],
      instruction: 'Choose the word that can replace desto without changing the meaning.',
      prompt: 'Welches Wort kann desto ersetzen, ohne die Bedeutung zu verändern?',
      options: [
        { id: 'a', text: 'umso' },
        { id: 'b', text: 'also' },
        { id: 'c', text: 'dann' },
        { id: 'd', text: 'weil' },
      ],
      correctOptionId: 'a',
      explanation: 'umso is fully interchangeable with desto in this construction.',
    },
    {
      id: 'ch81-ex-12',
      chapterNumber: 81,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'separable-verb'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Welcher Satz hat die richtige Wortstellung?',
      options: [
        { id: 'a', text: 'Je mehr Geld sie verdient, desto mehr gibt sie aus.' },
        { id: 'b', text: 'Je mehr Geld verdient sie, desto mehr gibt sie aus.' },
        { id: 'c', text: 'Je mehr Geld sie verdient, desto sie gibt mehr aus.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The je-clause keeps the finite verb (verdient) at the end; the desto-clause has desto mehr in position 1 followed immediately by the verb (gibt), then the subject (sie), with the separable prefix aus at the end.',
    },
    {
      id: 'ch81-ex-13',
      chapterNumber: 81,
      order: 13,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['je-desto-pattern', 'pragmatics'],
      instruction: 'Choose the sentence that matches how Jonas feels as the exam gets closer.',
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Wie fühlst du dich vor der Prüfung?',
          english: 'How do you feel before the exam?',
        },
        {
          speaker: 'Jonas',
          german: 'Ehrlich gesagt panisch: ___',
          english: 'Honestly, panicked: ...',
        },
      ],
      prompt: '___',
      options: [
        { id: 'a', text: 'Je näher der Prüfungstermin rückt, desto nervöser wird er.' },
        { id: 'b', text: 'Je näher rückt der Prüfungstermin, desto wird er nervöser.' },
        { id: 'c', text: 'Näher der Prüfungstermin rückt, je nervöser wird er.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Only option a has verb-final order in the je-clause (rückt at the end) and verb-second order right after desto nervöser in the second clause.',
    },
    {
      id: 'ch81-ex-14',
      chapterNumber: 81,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'word-order', 'separable-verb'],
      instruction: "Choose the German sentence that correctly expresses: 'The earlier we get up, the more we get done.'",
      prompt:
        "Welcher Satz drückt korrekt aus: 'The earlier we get up, the more we get done'?",
      options: [
        { id: 'a', text: 'Je früher wir aufstehen, desto mehr schaffen wir.' },
        { id: 'b', text: 'Je früher stehen wir auf, desto mehr schaffen wir.' },
        { id: 'c', text: 'Je wir früher aufstehen, desto schaffen wir mehr.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Only option a keeps aufstehen together at the end of the verb-final je-clause and puts schaffen directly after desto mehr in the verb-second clause.',
    },
    {
      id: 'ch81-ex-15',
      chapterNumber: 81,
      order: 15,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'conjunction-choice'],
      instruction: 'Fill in the missing first word. Capitalisation is not checked.',
      prompt: '___ mehr er lernt, desto besser wird er.',
      acceptedAnswers: ['je'],
      answerMode: 'caseInsensitive',
      placeholder: 'je',
      maxLength: 10,
      explanation: 'je opens the subordinate clause of this proportional comparison.',
    },
    {
      id: 'ch81-ex-16',
      chapterNumber: 81,
      order: 16,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['je-desto-pattern', 'umso'],
      instruction: 'Fill in the missing word (desto or umso both work). Capitalisation is not checked.',
      prompt: 'Je mehr er lernt, ___ besser wird er.',
      acceptedAnswers: ['desto', 'umso'],
      answerMode: 'caseInsensitive',
      placeholder: 'desto/umso',
      maxLength: 10,
      explanation: 'Either desto or umso can open the main clause here; both work identically.',
    },
    {
      id: 'ch81-ex-17',
      chapterNumber: 81,
      order: 17,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (viel) er arbeitet, desto müder wird er.',
      acceptedAnswers: ['mehr'],
      answerMode: 'caseInsensitive',
      placeholder: 'mehr',
      maxLength: 10,
      explanation: "viel's comparative is mehr.",
    },
    {
      id: 'ch81-ex-18',
      chapterNumber: 81,
      order: 18,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je mehr er arbeitet, desto ___ (müde) wird er.',
      acceptedAnswers: ['müder'],
      answerMode: 'caseInsensitive',
      placeholder: 'müder',
      maxLength: 15,
      explanation: 'müde is regular: müde -> müder.',
    },
    {
      id: 'ch81-ex-19',
      chapterNumber: 81,
      order: 19,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je frischer die Bohnen sind, desto ___ (gut) schmeckt der Kaffee.',
      acceptedAnswers: ['besser'],
      answerMode: 'caseInsensitive',
      placeholder: 'besser',
      maxLength: 15,
      explanation: "gut's comparative is besser.",
    },
    {
      id: 'ch81-ex-20',
      chapterNumber: 81,
      order: 20,
      type: 'textInput',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je mehr Zeit sie hat, desto ___ (gern) liest sie.',
      acceptedAnswers: ['lieber'],
      answerMode: 'caseInsensitive',
      placeholder: 'lieber',
      maxLength: 15,
      explanation: "gern's comparative is lieber.",
    },
    {
      id: 'ch81-ex-21',
      chapterNumber: 81,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (wenig) er isst, desto schwächer fühlt er sich.',
      acceptedAnswers: ['weniger'],
      answerMode: 'caseInsensitive',
      placeholder: 'weniger',
      maxLength: 15,
      explanation: "wenig's comparative is weniger.",
    },
    {
      id: 'ch81-ex-22',
      chapterNumber: 81,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'word-order'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Er lernt viel. Er wird besser.',
      acceptedAnswers: ['Je mehr er lernt, desto besser wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr er lernt, desto ...',
      maxLength: 60,
      explanation:
        'je mehr er lernt keeps the verb (lernt) at the end; desto besser wird er places the verb (wird) directly after desto besser.',
    },
    {
      id: 'ch81-ex-23',
      chapterNumber: 81,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-formation', 'word-order', 'umlaut-comparative'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Man wird alt. Man wird weise.',
      acceptedAnswers: ['Je älter man wird, desto weiser wird man.'],
      answerMode: 'normalized',
      placeholder: 'Je älter man wird, desto ...',
      maxLength: 60,
      explanation: 'alt has the umlaut comparative älter; both clauses follow the standard je ... desto word order.',
    },
    {
      id: 'ch81-ex-24',
      chapterNumber: 81,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sentence-formation', 'word-order'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Du fährst schnell. Es wird gefährlich.',
      acceptedAnswers: ['Je schneller du fährst, desto gefährlicher wird es.'],
      answerMode: 'normalized',
      placeholder: 'Je schneller du fährst, desto ...',
      maxLength: 70,
      explanation: 'fährst keeps the je-clause verb-final; wird stands directly after desto gefährlicher in the second clause.',
    },
    {
      id: 'ch81-ex-25',
      chapterNumber: 81,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sentence-formation', 'word-order', 'separable-verb'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Wir stehen früh auf. Wir schaffen mehr.',
      acceptedAnswers: ['Je früher wir aufstehen, desto mehr schaffen wir.'],
      answerMode: 'normalized',
      placeholder: 'Je früher wir aufstehen, desto ...',
      maxLength: 70,
      explanation:
        'The separable verb aufstehen stays together at the end of the verb-final je-clause; schaffen follows directly after desto mehr.',
    },
    {
      id: 'ch81-ex-26',
      chapterNumber: 81,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'word-order'],
      instruction: 'Correct the mistake. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Je mehr er lernt, desto wird er besser.',
      acceptedAnswers: ['Je mehr er lernt, desto besser wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr er lernt, desto ...',
      maxLength: 60,
      explanation:
        'desto and its comparative form one inseparable unit in position 1; the finite verb (wird) must come directly after desto besser, not before it.',
    },
    {
      id: 'ch81-ex-27',
      chapterNumber: 81,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'punctuation', 'comma'],
      instruction: 'Correct the mistake. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Je mehr er lernt desto besser wird er.',
      acceptedAnswers: ['Je mehr er lernt, desto besser wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr er lernt, desto ...',
      maxLength: 60,
      explanation: 'A comma is always required between the je-clause and the desto/umso-clause.',
    },
    {
      id: 'ch81-ex-28',
      chapterNumber: 81,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['umso', 'sentence-formation'],
      instruction:
        'Rewrite the sentence using umso instead of desto. Capitalisation and punctuation are checked.',
      prompt: 'Schreibe mit umso statt desto: Je mehr sie übt, desto sicherer wird sie.',
      acceptedAnswers: ['Je mehr sie übt, umso sicherer wird sie.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr sie übt, umso ...',
      maxLength: 60,
      explanation: 'umso replaces desto with no change in meaning or word order.',
    },
    {
      id: 'ch81-ex-29',
      chapterNumber: 81,
      order: 29,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je größer die Stadt ist, desto ___ sind die Wohnungen.',
      options: [
        { id: 'a', text: 'teurer' },
        { id: 'b', text: 'teuer' },
        { id: 'c', text: 'teuerer' },
        { id: 'd', text: 'mehr teuer' },
      ],
      correctOptionId: 'a',
      explanation: 'teuer forms its comparative regularly: teuer -> teurer.',
    },
    {
      id: 'ch81-ex-30',
      chapterNumber: 81,
      order: 30,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ das Auto ist, desto weniger Benzin braucht es.',
      options: [
        { id: 'a', text: 'kleiner' },
        { id: 'b', text: 'klein' },
        { id: 'c', text: 'kleinerer' },
        { id: 'd', text: 'minder' },
      ],
      correctOptionId: 'a',
      explanation: 'klein forms its comparative regularly: klein -> kleiner.',
    },
    {
      id: 'ch81-ex-31',
      chapterNumber: 81,
      order: 31,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je klüger man ist, desto ___ Fragen stellt man.',
      options: [
        { id: 'a', text: 'mehr' },
        { id: 'b', text: 'viel' },
        { id: 'c', text: 'mehrere' },
        { id: 'd', text: 'meister' },
      ],
      correctOptionId: 'a',
      explanation: 'viel is irregular; its comparative form is mehr.',
    },
    {
      id: 'ch81-ex-32',
      chapterNumber: 81,
      order: 32,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['word-order', 'verb-second'],
      instruction: 'Choose the sentence with correct word order.',
      prompt: 'Welcher Satz hat die richtige Wortstellung?',
      options: [
        { id: 'a', text: 'Je wärmer es wird, desto mehr Eis essen die Kinder.' },
        { id: 'b', text: 'Je wärmer wird es, desto mehr Eis essen die Kinder.' },
        { id: 'c', text: 'Je es wärmer wird, desto die Kinder mehr Eis essen.' },
      ],
      correctOptionId: 'a',
      explanation:
        'The je-clause keeps the finite verb (wird) at the end; the desto-clause has desto mehr Eis in position 1 followed by the verb (essen), then the subject (die Kinder).',
    },
    {
      id: 'ch81-ex-33',
      chapterNumber: 81,
      order: 33,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['punctuation', 'comma'],
      instruction: 'Choose the sentence with correct comma placement.',
      prompt: 'Welcher Satz ist richtig mit Komma?',
      options: [
        { id: 'a', text: 'Je teurer das Restaurant ist, desto besser sollte das Essen sein.' },
        { id: 'b', text: 'Je teurer das Restaurant ist desto besser sollte das Essen sein.' },
        { id: 'c', text: 'Je, teurer das Restaurant ist, desto besser sollte das Essen sein.' },
      ],
      correctOptionId: 'a',
      explanation: 'A comma always separates the je-clause from the desto-clause; no comma is placed after je itself.',
    },
    {
      id: 'ch81-ex-34',
      chapterNumber: 81,
      order: 34,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['je-desto-pattern', 'pragmatics'],
      instruction: 'Choose the sentence that matches how Tom drinks his coffee.',
      dialogue: [
        { speaker: 'Lisa', german: 'Wie trinkst du deinen Kaffee?', english: 'How do you drink your coffee?' },
        { speaker: 'Tom', german: 'Immer sehr stark: ___', english: 'Always very strong: ...' },
      ],
      prompt: '___',
      options: [
        { id: 'a', text: 'Je stärker der Kaffee ist, desto wacher fühle ich mich.' },
        { id: 'b', text: 'Je stärker ist der Kaffee, desto ich fühle wacher.' },
        { id: 'c', text: 'Stärker der Kaffee ist, je wacher fühle ich mich.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Only option a keeps the je-clause verb-final (ist at the end) and places the verb (fühle) directly after desto wacher.',
    },
    {
      id: 'ch81-ex-35',
      chapterNumber: 81,
      order: 35,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ der Berg ist, desto kälter wird es.',
      options: [
        { id: 'a', text: 'höher' },
        { id: 'b', text: 'hocher' },
        { id: 'c', text: 'höcher' },
        { id: 'd', text: 'hochster' },
      ],
      correctOptionId: 'a',
      explanation: 'hoch is irregular: hoch -> höher (the ch drops).',
    },
    {
      id: 'ch81-ex-36',
      chapterNumber: 81,
      order: 36,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Choose the correct comparative form.',
      prompt: 'Je ___ wir dem Ziel kommen, desto aufgeregter werden wir.',
      options: [
        { id: 'a', text: 'näher' },
        { id: 'b', text: 'naher' },
        { id: 'c', text: 'nächer' },
        { id: 'd', text: 'nährer' },
      ],
      correctOptionId: 'a',
      explanation: 'nah is irregular: nah -> näher (an extra h is inserted).',
    },
    {
      id: 'ch81-ex-37',
      chapterNumber: 81,
      order: 37,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['umso', 'je-desto-pattern'],
      instruction: 'Choose the sentence that correctly uses umso in place of desto.',
      prompt: 'Welcher Satz verwendet umso richtig anstelle von desto?',
      options: [
        { id: 'a', text: 'Je mehr sie übt, umso sicherer wird sie.' },
        { id: 'b', text: 'Je mehr sie übt, umso wird sie sicherer.' },
        { id: 'c', text: 'Umso mehr sie übt, je sicherer wird sie.' },
      ],
      correctOptionId: 'a',
      explanation: 'umso behaves exactly like desto: umso sicherer fills position 1, and the verb (wird) follows immediately.',
    },
    {
      id: 'ch81-ex-38',
      chapterNumber: 81,
      order: 38,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['sentence-formation', 'word-order', 'umlaut-comparative'],
      instruction:
        "Choose the German sentence that correctly expresses: 'The colder the winter is, the higher the heating costs become.'",
      prompt: "Welcher Satz drückt korrekt aus: 'The colder the winter is, the higher the heating costs become'?",
      options: [
        { id: 'a', text: 'Je kälter der Winter ist, desto höher werden die Heizkosten.' },
        { id: 'b', text: 'Je kälter ist der Winter, desto höher werden die Heizkosten.' },
        { id: 'c', text: 'Je der Winter kälter ist, desto Heizkosten werden höher.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Only option a keeps ist verb-final in the je-clause and places werden directly after desto höher in the verb-second clause.',
    },
    {
      id: 'ch81-ex-39',
      chapterNumber: 81,
      order: 39,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of groß.',
      templateParts: ['Je ', ' die Stadt ist, desto teurer sind die Wohnungen.'],
      slots: [{ id: 'slot1', correctWord: 'größer' }],
      wordBank: ['größer', 'groß', 'größte', 'breiter'],
      explanation: 'groß takes an umlaut in the comparative: groß -> größer.',
    },
    {
      id: 'ch81-ex-40',
      chapterNumber: 81,
      order: 40,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the desto-clause with the correct comparative of teuer.',
      templateParts: ['Je größer die Stadt ist, desto ', ' sind die Wohnungen.'],
      slots: [{ id: 'slot1', correctWord: 'teurer' }],
      wordBank: ['teurer', 'teuer', 'teuerer', 'billiger'],
      explanation: 'teuer is regular: teuer -> teurer.',
    },
    {
      id: 'ch81-ex-41',
      chapterNumber: 81,
      order: 41,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of klein.',
      templateParts: ['Je ', ' das Auto ist, desto weniger Benzin braucht es.'],
      slots: [{ id: 'slot1', correctWord: 'kleiner' }],
      wordBank: ['kleiner', 'klein', 'kleinste', 'kürzer'],
      explanation: 'klein is regular: klein -> kleiner.',
    },
    {
      id: 'ch81-ex-42',
      chapterNumber: 81,
      order: 42,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of schnell.',
      templateParts: ['Je ', ' er läuft, desto schneller kommt er an.'],
      slots: [{ id: 'slot1', correctWord: 'schneller' }],
      wordBank: ['schneller', 'schnell', 'schnellste', 'langsamer'],
      explanation: 'schnell is regular: schnell -> schneller.',
    },
    {
      id: 'ch81-ex-43',
      chapterNumber: 81,
      order: 43,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the desto-clause with the correct comparative of gut.',
      templateParts: ['Je langsamer du sprichst, desto ', ' verstehe ich dich.'],
      slots: [{ id: 'slot1', correctWord: 'besser' }],
      wordBank: ['besser', 'gut', 'guter', 'mehr'],
      explanation: "gut's comparative is besser.",
    },
    {
      id: 'ch81-ex-44',
      chapterNumber: 81,
      order: 44,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of alt.',
      templateParts: ['Je ', ' der Wein ist, desto teurer wird er.'],
      slots: [{ id: 'slot1', correctWord: 'älter' }],
      wordBank: ['älter', 'alt', 'ältester', 'alter'],
      explanation: 'alt takes an umlaut in the comparative: alt -> älter.',
    },
    {
      id: 'ch81-ex-45',
      chapterNumber: 81,
      order: 45,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the desto-clause with the correct comparative of viel.',
      templateParts: ['Je klüger man ist, desto ', ' Fragen stellt man.'],
      slots: [{ id: 'slot1', correctWord: 'mehr' }],
      wordBank: ['mehr', 'viel', 'mehrere', 'meiste'],
      explanation: "viel's comparative is mehr.",
    },
    {
      id: 'ch81-ex-46',
      chapterNumber: 81,
      order: 46,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of teuer.',
      templateParts: ['Je ', ' das Restaurant ist, desto besser sollte das Essen sein.'],
      slots: [{ id: 'slot1', correctWord: 'teurer' }],
      wordBank: ['teurer', 'teuer', 'teuerste', 'billiger'],
      explanation: 'teuer is regular: teuer -> teurer.',
    },
    {
      id: 'ch81-ex-47',
      chapterNumber: 81,
      order: 47,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of schön.',
      templateParts: ['Je ', ' das Wetter ist, desto mehr Menschen gehen spazieren.'],
      slots: [{ id: 'slot1', correctWord: 'schöner' }],
      wordBank: ['schöner', 'schön', 'schönste', 'wärmer'],
      explanation: 'schön is regular: schön -> schöner.',
    },
    {
      id: 'ch81-ex-48',
      chapterNumber: 81,
      order: 48,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of warm.',
      templateParts: ['Je ', ' es draußen ist, desto mehr Eis essen die Kinder.'],
      slots: [{ id: 'slot1', correctWord: 'wärmer' }],
      wordBank: ['wärmer', 'warm', 'wärmste', 'heißer'],
      explanation: 'warm takes an umlaut in the comparative: warm -> wärmer.',
    },
    {
      id: 'ch81-ex-49',
      chapterNumber: 81,
      order: 49,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of kalt.',
      templateParts: ['Je ', ' der Winter ist, desto höher werden die Heizkosten.'],
      slots: [{ id: 'slot1', correctWord: 'kälter' }],
      wordBank: ['kälter', 'kalt', 'kälteste', 'kühler'],
      explanation: 'kalt takes an umlaut in the comparative: kalt -> kälter.',
    },
    {
      id: 'ch81-ex-50',
      chapterNumber: 81,
      order: 50,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the desto-clause with the correct comparative of hoch.',
      templateParts: ['Je kälter der Winter ist, desto ', ' werden die Heizkosten.'],
      slots: [{ id: 'slot1', correctWord: 'höher' }],
      wordBank: ['höher', 'hoch', 'höchste', 'hocher'],
      explanation: 'hoch is irregular: hoch -> höher.',
    },
    {
      id: 'ch81-ex-51',
      chapterNumber: 81,
      order: 51,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Drag the correct words into the blanks.',
      prompt: 'Complete both clauses with the correct comparatives of viel and leicht.',
      templateParts: ['Je ', ' Sprachen man spricht, desto ', ' findet man Freunde im Ausland.'],
      slots: [
        { id: 'slot1', correctWord: 'mehr' },
        { id: 'slot2', correctWord: 'leichter' },
      ],
      wordBank: ['mehr', 'leichter', 'viel', 'leicht'],
      explanation: "viel's comparative is mehr; leicht is regular: leicht -> leichter.",
    },
    {
      id: 'ch81-ex-52',
      chapterNumber: 81,
      order: 52,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of nah.',
      templateParts: ['Je ', ' wir dem Ziel kommen, desto aufgeregter werden wir.'],
      slots: [{ id: 'slot1', correctWord: 'näher' }],
      wordBank: ['näher', 'nah', 'nächste', 'naher'],
      explanation: 'nah is irregular: nah -> näher.',
    },
    {
      id: 'ch81-ex-53',
      chapterNumber: 81,
      order: 53,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of lang.',
      templateParts: ['Je ', ' die Warteschlange ist, desto ungeduldiger werden die Kunden.'],
      slots: [{ id: 'slot1', correctWord: 'länger' }],
      wordBank: ['länger', 'lang', 'längste', 'kürzer'],
      explanation: 'lang takes an umlaut in the comparative: lang -> länger.',
    },
    {
      id: 'ch81-ex-54',
      chapterNumber: 81,
      order: 54,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Drag the correct word into the blank.',
      prompt: 'Complete the je-clause with the correct comparative of oft.',
      templateParts: ['Je ', ' du übst, desto sicherer wirst du.'],
      slots: [{ id: 'slot1', correctWord: 'öfter' }],
      wordBank: ['öfter', 'oft', 'häufiger', 'mehrer'],
      explanation: 'oft is regular: oft -> öfter.',
    },
    {
      id: 'ch81-ex-55',
      chapterNumber: 81,
      order: 55,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je – mehr – man – übt, – desto – besser – wird – man.',
      segments: [
        { id: 's1', text: 'Je' },
        { id: 's2', text: 'mehr' },
        { id: 's3', text: 'man' },
        { id: 's4', text: 'übt,' },
        { id: 's5', text: 'desto' },
        { id: 's6', text: 'besser' },
        { id: 's7', text: 'wird' },
        { id: 's8', text: 'man.' },
      ],
      explanation: 'übt keeps the je-clause verb-final; wird stands directly after desto besser in the verb-second clause.',
    },
    {
      id: 'ch81-ex-56',
      chapterNumber: 81,
      order: 56,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation', 'umlaut-comparative'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je – größer – die Stadt – ist, – desto – teurer – sind – die Wohnungen.',
      segments: [
        { id: 's1', text: 'Je' },
        { id: 's2', text: 'größer' },
        { id: 's3', text: 'die Stadt' },
        { id: 's4', text: 'ist,' },
        { id: 's5', text: 'desto' },
        { id: 's6', text: 'teurer' },
        { id: 's7', text: 'sind' },
        { id: 's8', text: 'die Wohnungen.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; sind stands directly after desto teurer in the verb-second clause.',
    },
    {
      id: 'ch81-ex-57',
      chapterNumber: 81,
      order: 57,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je – kleiner – das Auto – ist, – desto – weniger Benzin – braucht – es.',
      segments: [
        { id: 's1', text: 'Je' },
        { id: 's2', text: 'kleiner' },
        { id: 's3', text: 'das Auto' },
        { id: 's4', text: 'ist,' },
        { id: 's5', text: 'desto' },
        { id: 's6', text: 'weniger Benzin' },
        { id: 's7', text: 'braucht' },
        { id: 's8', text: 'es.' },
      ],
      explanation:
        'ist keeps the je-clause verb-final; braucht stands directly after desto weniger Benzin in the verb-second clause.',
    },
    {
      id: 'ch81-ex-58',
      chapterNumber: 81,
      order: 58,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je schneller – er läuft, – desto schneller – kommt – er – an.',
      segments: [
        { id: 's1', text: 'Je schneller' },
        { id: 's2', text: 'er läuft,' },
        { id: 's3', text: 'desto schneller' },
        { id: 's4', text: 'kommt' },
        { id: 's5', text: 'er' },
        { id: 's6', text: 'an.' },
      ],
      explanation:
        'läuft keeps the je-clause verb-final; kommt stands directly after desto schneller, with the separable prefix an at the end.',
    },
    {
      id: 'ch81-ex-59',
      chapterNumber: 81,
      order: 59,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je langsamer – du sprichst, – desto besser – verstehe – ich – dich.',
      segments: [
        { id: 's1', text: 'Je langsamer' },
        { id: 's2', text: 'du sprichst,' },
        { id: 's3', text: 'desto besser' },
        { id: 's4', text: 'verstehe' },
        { id: 's5', text: 'ich' },
        { id: 's6', text: 'dich.' },
      ],
      explanation:
        'sprichst keeps the je-clause verb-final; verstehe stands directly after desto besser in the verb-second clause.',
    },
    {
      id: 'ch81-ex-60',
      chapterNumber: 81,
      order: 60,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation', 'umlaut-comparative'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je älter – der Wein – ist, – desto teurer – wird – er.',
      segments: [
        { id: 's1', text: 'Je älter' },
        { id: 's2', text: 'der Wein' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto teurer' },
        { id: 's5', text: 'wird' },
        { id: 's6', text: 'er.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; wird stands directly after desto teurer in the verb-second clause.',
    },
    {
      id: 'ch81-ex-61',
      chapterNumber: 81,
      order: 61,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je klüger – man ist, – desto mehr Fragen – stellt – man.',
      segments: [
        { id: 's1', text: 'Je klüger' },
        { id: 's2', text: 'man ist,' },
        { id: 's3', text: 'desto mehr Fragen' },
        { id: 's4', text: 'stellt' },
        { id: 's5', text: 'man.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; stellt stands directly after desto mehr Fragen.',
    },
    {
      id: 'ch81-ex-62',
      chapterNumber: 81,
      order: 62,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je teurer – das Restaurant – ist, – desto besser – sollte das Essen – sein.',
      segments: [
        { id: 's1', text: 'Je teurer' },
        { id: 's2', text: 'das Restaurant' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto besser' },
        { id: 's5', text: 'sollte das Essen' },
        { id: 's6', text: 'sein.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; sollte stands directly after desto besser.',
    },
    {
      id: 'ch81-ex-63',
      chapterNumber: 81,
      order: 63,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je schöner – das Wetter – ist, – desto mehr Menschen – gehen – spazieren.',
      segments: [
        { id: 's1', text: 'Je schöner' },
        { id: 's2', text: 'das Wetter' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto mehr Menschen' },
        { id: 's5', text: 'gehen' },
        { id: 's6', text: 'spazieren.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; gehen stands directly after desto mehr Menschen.',
    },
    {
      id: 'ch81-ex-64',
      chapterNumber: 81,
      order: 64,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation', 'umlaut-comparative'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je wärmer – es draußen – ist, – desto mehr Eis – essen – die Kinder.',
      segments: [
        { id: 's1', text: 'Je wärmer' },
        { id: 's2', text: 'es draußen' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto mehr Eis' },
        { id: 's5', text: 'essen' },
        { id: 's6', text: 'die Kinder.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; essen stands directly after desto mehr Eis.',
    },
    {
      id: 'ch81-ex-65',
      chapterNumber: 81,
      order: 65,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['word-order', 'sentence-formation', 'umlaut-comparative'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je kälter – der Winter – ist, – desto höher – werden – die Heizkosten.',
      segments: [
        { id: 's1', text: 'Je kälter' },
        { id: 's2', text: 'der Winter' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto höher' },
        { id: 's5', text: 'werden' },
        { id: 's6', text: 'die Heizkosten.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; werden stands directly after desto höher.',
    },
    {
      id: 'ch81-ex-66',
      chapterNumber: 81,
      order: 66,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je mehr Sprachen – man spricht, – desto leichter – findet man – Freunde im Ausland.',
      segments: [
        { id: 's1', text: 'Je mehr Sprachen' },
        { id: 's2', text: 'man spricht,' },
        { id: 's3', text: 'desto leichter' },
        { id: 's4', text: 'findet man' },
        { id: 's5', text: 'Freunde im Ausland.' },
      ],
      explanation: 'spricht keeps the je-clause verb-final; findet stands directly after desto leichter.',
    },
    {
      id: 'ch81-ex-67',
      chapterNumber: 81,
      order: 67,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je näher – wir dem Ziel – kommen, – desto aufgeregter – werden wir.',
      segments: [
        { id: 's1', text: 'Je näher' },
        { id: 's2', text: 'wir dem Ziel' },
        { id: 's3', text: 'kommen,' },
        { id: 's4', text: 'desto aufgeregter' },
        { id: 's5', text: 'werden wir.' },
      ],
      explanation: 'kommen keeps the je-clause verb-final; werden stands directly after desto aufgeregter.',
    },
    {
      id: 'ch81-ex-68',
      chapterNumber: 81,
      order: 68,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation', 'umlaut-comparative'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je länger – die Warteschlange – ist, – desto ungeduldiger – werden – die Kunden.',
      segments: [
        { id: 's1', text: 'Je länger' },
        { id: 's2', text: 'die Warteschlange' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto ungeduldiger' },
        { id: 's5', text: 'werden' },
        { id: 's6', text: 'die Kunden.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; werden stands directly after desto ungeduldiger.',
    },
    {
      id: 'ch81-ex-69',
      chapterNumber: 81,
      order: 69,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je öfter – du übst, – desto sicherer – wirst – du.',
      segments: [
        { id: 's1', text: 'Je öfter' },
        { id: 's2', text: 'du übst,' },
        { id: 's3', text: 'desto sicherer' },
        { id: 's4', text: 'wirst' },
        { id: 's5', text: 'du.' },
      ],
      explanation: 'übst keeps the je-clause verb-final; wirst stands directly after desto sicherer.',
    },
    {
      id: 'ch81-ex-70',
      chapterNumber: 81,
      order: 70,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je weniger – er schläft, – desto müder – wird – er.',
      segments: [
        { id: 's1', text: 'Je weniger' },
        { id: 's2', text: 'er schläft,' },
        { id: 's3', text: 'desto müder' },
        { id: 's4', text: 'wird' },
        { id: 's5', text: 'er.' },
      ],
      explanation: 'schläft keeps the je-clause verb-final; wird stands directly after desto müder.',
    },
    {
      id: 'ch81-ex-71',
      chapterNumber: 81,
      order: 71,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation', 'irregular-comparative'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je höher – der Berg – ist, – desto kälter – wird – es.',
      segments: [
        { id: 's1', text: 'Je höher' },
        { id: 's2', text: 'der Berg' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto kälter' },
        { id: 's5', text: 'wird' },
        { id: 's6', text: 'es.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; wird stands directly after desto kälter.',
    },
    {
      id: 'ch81-ex-72',
      chapterNumber: 81,
      order: 72,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je stärker – der Kaffee – ist, – desto wacher – fühle ich – mich.',
      segments: [
        { id: 's1', text: 'Je stärker' },
        { id: 's2', text: 'der Kaffee' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto wacher' },
        { id: 's5', text: 'fühle ich' },
        { id: 's6', text: 'mich.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; fühle stands directly after desto wacher.',
    },
    {
      id: 'ch81-ex-73',
      chapterNumber: 81,
      order: 73,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je billiger – das Hotel – ist, – desto einfacher – ist – das Zimmer.',
      segments: [
        { id: 's1', text: 'Je billiger' },
        { id: 's2', text: 'das Hotel' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto einfacher' },
        { id: 's5', text: 'ist' },
        { id: 's6', text: 'das Zimmer.' },
      ],
      explanation: 'The first ist keeps the je-clause verb-final; the second ist stands directly after desto einfacher.',
    },
    {
      id: 'ch81-ex-74',
      chapterNumber: 81,
      order: 74,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['word-order', 'sentence-formation'],
      instruction: 'Put the segments in the correct order.',
      prompt: 'Je besser – die Note – ist, – desto stolzer – sind – die Eltern.',
      segments: [
        { id: 's1', text: 'Je besser' },
        { id: 's2', text: 'die Note' },
        { id: 's3', text: 'ist,' },
        { id: 's4', text: 'desto stolzer' },
        { id: 's5', text: 'sind' },
        { id: 's6', text: 'die Eltern.' },
      ],
      explanation: 'ist keeps the je-clause verb-final; sind stands directly after desto stolzer.',
    },
    {
      id: 'ch81-ex-75',
      chapterNumber: 81,
      order: 75,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['je-desto-pattern', 'sentence-formation'],
      instruction: 'Match each je-clause with the desto-clause that logically completes it.',
      prompt: 'Match the je-clauses with the correct desto-clauses.',
      pairs: [
        { id: 'p1', left: 'Je mehr man spart,', right: 'desto sicherer fühlt man sich.' },
        { id: 'p2', left: 'Je dunkler es wird,', right: 'desto schwerer sieht man die Straße.' },
        { id: 'p3', left: 'Je ruhiger die Umgebung ist,', right: 'desto besser schläft man.' },
        { id: 'p4', left: 'Je größer das Problem ist,', right: 'desto mehr Zeit braucht die Lösung.' },
        { id: 'p5', left: 'Je billiger das Hotel ist,', right: 'desto einfacher ist das Zimmer.' },
      ],
      explanation: 'Each je-clause names a changing condition; its matching desto-clause names the proportional result.',
    },
    {
      id: 'ch81-ex-76',
      chapterNumber: 81,
      order: 76,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['comparative-formation'],
      instruction: 'Match each base adjective with its regular comparative form.',
      prompt: 'Match the base forms with their comparatives.',
      pairs: [
        { id: 'p1', left: 'groß', right: 'größer' },
        { id: 'p2', left: 'klein', right: 'kleiner' },
        { id: 'p3', left: 'teuer', right: 'teurer' },
        { id: 'p4', left: 'schön', right: 'schöner' },
        { id: 'p5', left: 'warm', right: 'wärmer' },
      ],
      explanation: 'groß and warm take an umlaut in the comparative; klein, teuer and schön are fully regular.',
    },
    {
      id: 'ch81-ex-77',
      chapterNumber: 81,
      order: 77,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'irregular-comparative'],
      instruction: 'Match each base adjective/adverb with its irregular comparative form.',
      prompt: 'Match the base forms with their irregular comparatives.',
      pairs: [
        { id: 'p1', left: 'gut', right: 'besser' },
        { id: 'p2', left: 'viel', right: 'mehr' },
        { id: 'p3', left: 'gern', right: 'lieber' },
        { id: 'p4', left: 'hoch', right: 'höher' },
        { id: 'p5', left: 'nah', right: 'näher' },
      ],
      explanation: 'These five are the classic irregular comparatives that je and desto/umso must be followed by.',
    },
    {
      id: 'ch81-ex-78',
      chapterNumber: 81,
      order: 78,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['je-desto-pattern', 'sentence-formation'],
      instruction: 'Match each je-clause with the desto-clause that logically completes it.',
      prompt: 'Match the je-clauses with the correct desto-clauses.',
      pairs: [
        { id: 'p1', left: 'Je älter der Wein ist,', right: 'desto teurer wird er.' },
        { id: 'p2', left: 'Je klüger man ist,', right: 'desto mehr Fragen stellt man.' },
        { id: 'p3', left: 'Je teurer das Restaurant ist,', right: 'desto besser sollte das Essen sein.' },
        { id: 'p4', left: 'Je öfter du übst,', right: 'desto sicherer wirst du.' },
        { id: 'p5', left: 'Je weniger er schläft,', right: 'desto müder wird er.' },
      ],
      explanation: 'Each je-clause names a changing condition; its matching desto-clause names the proportional result.',
    },
    {
      id: 'ch81-ex-79',
      chapterNumber: 81,
      order: 79,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Match each base adjective with its umlaut comparative form.',
      prompt: 'Match the base forms with their comparatives.',
      pairs: [
        { id: 'p1', left: 'alt', right: 'älter' },
        { id: 'p2', left: 'lang', right: 'länger' },
        { id: 'p3', left: 'kurz', right: 'kürzer' },
        { id: 'p4', left: 'kalt', right: 'kälter' },
        { id: 'p5', left: 'stark', right: 'stärker' },
      ],
      explanation: 'All five take an umlaut on the stressed vowel when forming the comparative.',
    },
    {
      id: 'ch81-ex-80',
      chapterNumber: 81,
      order: 80,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['je-desto-pattern', 'sentence-formation'],
      instruction: 'Match each je-clause with the desto-clause that logically completes it.',
      prompt: 'Match the je-clauses with the correct desto-clauses.',
      pairs: [
        { id: 'p1', left: 'Je höher der Berg ist,', right: 'desto kälter wird es.' },
        { id: 'p2', left: 'Je stärker der Kaffee ist,', right: 'desto wacher fühle ich mich.' },
        { id: 'p3', left: 'Je besser die Note ist,', right: 'desto stolzer sind die Eltern.' },
        { id: 'p4', left: 'Je näher wir dem Ziel kommen,', right: 'desto aufgeregter werden wir.' },
        { id: 'p5', left: 'Je länger die Warteschlange ist,', right: 'desto ungeduldiger werden die Kunden.' },
      ],
      explanation: 'Each je-clause names a changing condition; its matching desto-clause names the proportional result.',
    },
    {
      id: 'ch81-ex-81',
      chapterNumber: 81,
      order: 81,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['comparative-formation', 'vocabulary'],
      instruction: 'Match each German comparative with its English meaning.',
      prompt: 'Match the comparatives with their English meanings.',
      pairs: [
        { id: 'p1', left: 'mehr', right: 'more' },
        { id: 'p2', left: 'besser', right: 'better' },
        { id: 'p3', left: 'lieber', right: 'rather / preferably' },
        { id: 'p4', left: 'näher', right: 'closer' },
        { id: 'p5', left: 'höher', right: 'higher' },
      ],
      explanation: 'These five irregular comparatives are the ones most often used in je ... desto sentences.',
    },
    {
      id: 'ch81-ex-82',
      chapterNumber: 81,
      order: 82,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['je-desto-pattern', 'sentence-formation'],
      instruction: 'Match each je-clause with the desto-clause that logically completes it.',
      prompt: 'Match the je-clauses with the correct desto-clauses.',
      pairs: [
        { id: 'p1', left: 'Je mehr Sprachen man spricht,', right: 'desto leichter findet man Freunde im Ausland.' },
        { id: 'p2', left: 'Je schöner das Wetter ist,', right: 'desto mehr Menschen gehen spazieren.' },
        { id: 'p3', left: 'Je wärmer es draußen ist,', right: 'desto mehr Eis essen die Kinder.' },
        { id: 'p4', left: 'Je kälter der Winter ist,', right: 'desto höher werden die Heizkosten.' },
        { id: 'p5', left: 'Je kleiner das Auto ist,', right: 'desto weniger Benzin braucht es.' },
      ],
      explanation: 'Each je-clause names a changing condition; its matching desto-clause names the proportional result.',
    },
    {
      id: 'ch81-ex-83',
      chapterNumber: 81,
      order: 83,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation'],
      instruction: 'Find the token with the mistake.',
      prompt: 'A colleague talks about workload and tiredness. Find the mistake.',
      tokens: ['Je', 'viel', 'er', 'arbeitet,', 'desto', 'müder', 'wird', 'er.'],
      errorTokenIndex: 1,
      correction: 'mehr',
      explanation: 'viel is irregular; only its comparative form mehr may follow je, never the plain base form viel.',
    },
    {
      id: 'ch81-ex-84',
      chapterNumber: 81,
      order: 84,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'irregular-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone describes how practice improves a skill. Find the mistake.',
      tokens: ['Je', 'mehr', 'er', 'übt,', 'desto', 'guter', 'wird', 'er.'],
      errorTokenIndex: 5,
      correction: 'besser',
      explanation: 'gut is irregular; the comparative is besser, never the regular form guter.',
    },
    {
      id: 'ch81-ex-85',
      chapterNumber: 81,
      order: 85,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'umlaut-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone shares a proverb about age and wisdom. Find the mistake.',
      tokens: ['Je', 'alter', 'man', 'wird,', 'desto', 'weiser', 'wird', 'man.'],
      errorTokenIndex: 1,
      correction: 'älter',
      explanation: 'alt takes an umlaut in the comparative: alt -> älter, not alter.',
    },
    {
      id: 'ch81-ex-86',
      chapterNumber: 81,
      order: 86,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'irregular-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone comments on prices going up. Find the mistake.',
      tokens: ['Je', 'hocher', 'die', 'Preise', 'steigen,', 'desto', 'weniger', 'kaufen', 'die', 'Leute.'],
      errorTokenIndex: 1,
      correction: 'höher',
      explanation: 'hoch is irregular: hoch -> höher (the ch drops), not hocher.',
    },
    {
      id: 'ch81-ex-87',
      chapterNumber: 81,
      order: 87,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'irregular-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone talks about nerves before an appointment. Find the mistake.',
      tokens: ['Je', 'naher', 'der', 'Termin', 'rückt,', 'desto', 'nervöser', 'wird', 'er.'],
      errorTokenIndex: 1,
      correction: 'näher',
      explanation: 'nah is irregular: nah -> näher (an extra h is inserted), not naher.',
    },
    {
      id: 'ch81-ex-88',
      chapterNumber: 81,
      order: 88,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'irregular-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone describes free time and reading habits. Find the mistake.',
      tokens: ['Je', 'mehr', 'Zeit', 'sie', 'hat,', 'desto', 'gerner', 'liest', 'sie.'],
      errorTokenIndex: 6,
      correction: 'lieber',
      explanation: 'gern is irregular; the comparative is lieber, never the regular form gerner.',
    },
    {
      id: 'ch81-ex-89',
      chapterNumber: 81,
      order: 89,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'umlaut-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone talks about city size and rent. Find the mistake.',
      tokens: ['Je', 'großer', 'die', 'Stadt', 'ist,', 'desto', 'teurer', 'sind', 'die', 'Wohnungen.'],
      errorTokenIndex: 1,
      correction: 'größer',
      explanation: 'groß takes an umlaut in the comparative: groß -> größer, not großer.',
    },
    {
      id: 'ch81-ex-90',
      chapterNumber: 81,
      order: 90,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'umlaut-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone complains about waiting in line. Find the mistake.',
      tokens: ['Je', 'langer', 'die', 'Warteschlange', 'ist,', 'desto', 'ungeduldiger', 'werden', 'die', 'Kunden.'],
      errorTokenIndex: 1,
      correction: 'länger',
      explanation: 'lang takes an umlaut in the comparative: lang -> länger, not langer.',
    },
    {
      id: 'ch81-ex-91',
      chapterNumber: 81,
      order: 91,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'umlaut-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone talks about winter and heating costs. Find the mistake.',
      tokens: ['Je', 'kalter', 'der', 'Winter', 'ist,', 'desto', 'höher', 'werden', 'die', 'Heizkosten.'],
      errorTokenIndex: 1,
      correction: 'kälter',
      explanation: 'kalt takes an umlaut in the comparative: kalt -> kälter, not kalter.',
    },
    {
      id: 'ch81-ex-92',
      chapterNumber: 81,
      order: 92,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['error-correction', 'comparative-formation', 'umlaut-comparative'],
      instruction: 'Find the token with the mistake.',
      prompt: 'Someone talks about coffee strength and feeling awake. Find the mistake.',
      tokens: ['Je', 'starker', 'der', 'Kaffee', 'ist,', 'desto', 'wacher', 'fühle', 'ich', 'mich.'],
      errorTokenIndex: 1,
      correction: 'stärker',
      explanation: 'stark takes an umlaut in the comparative: stark -> stärker, not starker.',
    },
    {
      id: 'ch81-ex-93',
      chapterNumber: 81,
      order: 93,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (groß) die Stadt ist, desto teurer sind die Wohnungen.',
      acceptedAnswers: ['größer'],
      answerMode: 'caseInsensitive',
      placeholder: 'größer',
      maxLength: 15,
      explanation: 'groß takes an umlaut in the comparative: groß -> größer.',
    },
    {
      id: 'ch81-ex-94',
      chapterNumber: 81,
      order: 94,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (klein) das Auto ist, desto weniger Benzin braucht es.',
      acceptedAnswers: ['kleiner'],
      answerMode: 'caseInsensitive',
      placeholder: 'kleiner',
      maxLength: 15,
      explanation: 'klein is regular: klein -> kleiner.',
    },
    {
      id: 'ch81-ex-95',
      chapterNumber: 81,
      order: 95,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['comparative-formation'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (schön) das Wetter ist, desto mehr Menschen gehen spazieren.',
      acceptedAnswers: ['schöner'],
      answerMode: 'caseInsensitive',
      placeholder: 'schöner',
      maxLength: 15,
      explanation: 'schön is regular: schön -> schöner.',
    },
    {
      id: 'ch81-ex-96',
      chapterNumber: 81,
      order: 96,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['comparative-formation', 'umlaut-comparative'],
      instruction: 'Write the comparative of the adjective in brackets. Capitalisation is not checked.',
      prompt: 'Je ___ (warm) es draußen ist, desto mehr Eis essen die Kinder.',
      acceptedAnswers: ['wärmer'],
      answerMode: 'caseInsensitive',
      placeholder: 'wärmer',
      maxLength: 15,
      explanation: 'warm takes an umlaut in the comparative: warm -> wärmer.',
    },
    {
      id: 'ch81-ex-97',
      chapterNumber: 81,
      order: 97,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sentence-formation', 'word-order', 'umlaut-comparative'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Der Wein wird alt. Der Wein wird teuer.',
      acceptedAnswers: ['Je älter der Wein wird, desto teurer wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je älter der Wein wird, desto ...',
      maxLength: 60,
      explanation: 'wird keeps the je-clause verb-final; wird stands directly after desto teurer in the second clause.',
    },
    {
      id: 'ch81-ex-98',
      chapterNumber: 81,
      order: 98,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sentence-formation', 'word-order'],
      instruction:
        'Combine the two sentences into one je ... desto sentence. Capitalisation and punctuation are checked.',
      prompt: 'Der Kaffee ist stark. Ich fühle mich wach.',
      acceptedAnswers: ['Je stärker der Kaffee ist, desto wacher fühle ich mich.'],
      answerMode: 'normalized',
      placeholder: 'Je stärker der Kaffee ist, desto ...',
      maxLength: 70,
      explanation: 'ist keeps the je-clause verb-final; fühle stands directly after desto wacher in the second clause.',
    },
    {
      id: 'ch81-ex-99',
      chapterNumber: 81,
      order: 99,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'word-order'],
      instruction: 'Correct the mistake. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Je mehr er lernt, desto er wird besser.',
      acceptedAnswers: ['Je mehr er lernt, desto besser wird er.'],
      answerMode: 'normalized',
      placeholder: 'Je mehr er lernt, desto ...',
      maxLength: 60,
      explanation:
        'desto and its comparative form one inseparable unit in position 1; the finite verb (wird) must come directly after desto besser, and the subject (er) follows the verb.',
    },
    {
      id: 'ch81-ex-100',
      chapterNumber: 81,
      order: 100,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['error-correction', 'comparative-formation', 'umlaut-comparative'],
      instruction: 'Correct the mistake. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Je alter man wird, desto weiser wird man.',
      acceptedAnswers: ['Je älter man wird, desto weiser wird man.'],
      answerMode: 'normalized',
      placeholder: 'Je älter man wird, desto ...',
      maxLength: 60,
      explanation: 'alt takes an umlaut in the comparative: alt -> älter, not alter.',
    },
  ],
};
