import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter011: ChapterDefinition = {
  id: 'chapter-011',
  number: 11,
  slug: 'yes-no-questions-and-answers',
  title: 'Yes/No Questions and Answers',
  germanTitle: 'Ja/Nein-Fragen und Antworten',
  level: 'A1',
  section: 'sentences-and-questions',
  objective:
    'Build yes/no questions by putting the finite verb first, give short and full answers, and choose correctly between ja, nein, and doch.',
  prerequisites: [2, 10],
  estimatedMinutes: 25,
  tags: ['questions', 'yes-no-questions', 'ja-nein-doch', 'word-order', 'negation'],
  explanation: {
    introduction: [
      'A yes/no question (Ja/Nein-Frage) is a question that can be answered with ja, nein, or sometimes doch. Unlike a W-question, it has no question word at all: instead, the finite verb itself moves into position 1, right where a question word would otherwise stand, and the subject follows in position 2.',
      'This chapter shows you how to build a yes/no question by putting the verb first, how to answer it briefly or in a full sentence, and — the trickiest part for English speakers — when to use doch instead of ja to contradict a negative question. It also gives you a short note on how these questions sound in spoken German.',
    ],
    rules: [
      {
        id: 'ch11-rule-01',
        heading: 'Verb-first word order in yes/no questions',
        paragraphs: [
          'In a yes/no question, the finite (conjugated) verb stands in position 1. There is no question word.',
          'The subject moves to position 2, directly after the verb. Everything else in the sentence follows in the same order as in the statement.',
          'Compare the statement Du kommst heute mit. (subject before verb) with the question Kommst du heute mit? (verb before subject): only the word order changes, not the words themselves.',
        ],
        notes: [
          'A yes/no question always ends with a question mark, just like a W-question.',
          'To turn any simple statement into a yes/no question, move the finite verb to the very front and put the subject right after it.',
        ],
      },
      {
        id: 'ch11-rule-02',
        heading: 'Short answers and full answers',
        paragraphs: [
          'You can answer a yes/no question with just ja or nein, but German speakers very often add a full sentence as well, especially in writing or careful speech.',
          'In a full answer, ja, nein, or doch stands outside the sentence, followed by a comma; the sentence itself keeps normal statement word order (usually subject before verb).',
        ],
        notes: [
          'Short answer: Kommst du mit? – Ja. / Nein.',
          'Full answer: Kommst du mit? – Ja, ich komme mit. / Nein, ich komme nicht mit.',
        ],
      },
      {
        id: 'ch11-rule-03',
        heading: 'ja, nein, and doch',
        paragraphs: [
          'ja confirms a positive question with "yes", and nein rejects a positive question with "no": Isst du Fleisch? – Ja, ich esse Fleisch. / Nein, ich esse kein Fleisch.',
          'doch is used only to contradict a negative question — to say "yes" when the question itself contained nicht or kein. English has no separate word for this and just says "yes" more emphatically; German requires doch.',
          'If you answer a negative question with nein, you are agreeing with the negative: you confirm that the thing is indeed not the case.',
        ],
      },
      {
        id: 'ch11-rule-04',
        heading: 'Answering negated questions',
        paragraphs: [
          'A negated question contains nicht or kein: Kommst du nicht mit? (Aren\'t you coming along?)',
          'If the true situation is negative (you are in fact not coming), you answer with nein: Nein, ich komme nicht mit.',
          'If the true situation is positive (you actually are coming, contradicting the negative question), you must answer with doch, not ja: Doch, ich komme mit.',
        ],
      },
      {
        id: 'ch11-rule-05',
        heading: 'Question intonation in speech',
        paragraphs: [
          'In spoken German, a yes/no question is also marked by rising intonation at the end of the sentence, even though the word order already signals a question by itself.',
          'This is a useful listening clue: if you hear a sentence with the verb first and the pitch rising toward the end, you can be sure it is a yes/no question, not a statement.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch11-table-01',
        title: 'Statement vs. yes/no question word order',
        columns: ['Position 1', 'Position 2', 'Rest of sentence', 'Type'],
        rows: [
          ['Du', 'kommst', 'heute mit.', 'statement'],
          ['Kommst', 'du', 'heute mit?', 'yes/no question'],
          ['Er', 'spricht', 'gut Deutsch.', 'statement'],
          ['Spricht', 'er', 'gut Deutsch?', 'yes/no question'],
        ],
      },
      {
        id: 'ch11-table-02',
        title: 'ja, nein, or doch?',
        columns: ['Question', 'Fact', 'Answer word'],
        rows: [
          ['Kommst du mit? (positive)', 'you are coming', 'Ja'],
          ['Kommst du mit? (positive)', 'you are not coming', 'Nein'],
          ['Kommst du nicht mit? (negative)', 'you are not coming', 'Nein'],
          ['Kommst du nicht mit? (negative)', 'you are coming', 'Doch'],
        ],
        note: 'The question decides whether ja/nein or nein/doch is the matching pair — always check whether the question itself was positive or negative first.',
      },
    ],
    examples: [
      {
        german: 'Kommst du heute Abend mit?',
        english: 'Are you coming along this evening?',
        highlight: ['Kommst'],
        explanation: 'The finite verb kommst stands in position 1; there is no question word.',
      },
      {
        german: 'Wohnt ihr in Berlin?',
        english: 'Do you live in Berlin?',
        highlight: ['Wohnt'],
      },
      {
        german: 'Isst du gern Pizza? – Ja, ich esse sehr gern Pizza.',
        english: 'Do you like eating pizza? – Yes, I really like eating pizza.',
        highlight: ['Ja'],
        explanation: 'The question is positive, and the answer confirms it, so ja is used.',
      },
      {
        german: 'Trinkst du Kaffee? – Nein, ich trinke keinen Kaffee.',
        english: "Do you drink coffee? – No, I don't drink coffee.",
        highlight: ['Nein'],
        explanation: 'The question is positive, and the answer rejects it, so nein is used.',
      },
      {
        german: 'Kommst du nicht mit? – Doch, ich komme mit.',
        english: "Aren't you coming along? – Yes, I am coming along.",
        highlight: ['nicht mit', 'Doch'],
        explanation: 'The question is negative, but the fact is positive, so doch contradicts it.',
      },
      {
        german: 'Hast du keine Zeit? – Doch, ich habe Zeit.',
        english: "Don't you have time? – Yes, I do have time.",
        highlight: ['keine Zeit', 'Doch'],
      },
      {
        german: 'Regnet es morgen? – Nein, morgen scheint die Sonne.',
        english: 'Will it rain tomorrow? – No, the sun will shine tomorrow.',
        highlight: ['Regnet'],
      },
      {
        german: 'Sprichst du Englisch? – Ja, ein bisschen.',
        english: 'Do you speak English? – Yes, a little.',
        highlight: ['Sprichst'],
      },
      {
        german: 'Ist das dein Bruder? – Ja, das ist mein Bruder.',
        english: 'Is that your brother? – Yes, that is my brother.',
        highlight: ['Ist'],
      },
      {
        german: 'Fährst du morgen nicht zur Arbeit? – Doch, ich fahre um acht Uhr.',
        english: "Aren't you going to work tomorrow? – Yes, I'm going at eight o'clock.",
        highlight: ['nicht zur Arbeit', 'Doch'],
        explanation: 'The question is negative, but the true situation is positive, so doch contradicts it.',
      },
      {
        german: 'Kauft ihr heute Brot? – Nein, wir haben noch genug Brot.',
        english: 'Are you buying bread today? – No, we still have enough bread.',
        highlight: ['Kauft'],
      },
      {
        german: 'Wollen wir zusammen kochen?',
        english: 'Shall we cook together?',
        highlight: ['Wollen'],
        explanation: 'Even with a modal verb, the finite verb wollen still stands in position 1.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Kommst du nicht mit? – Ja, ich komme mit.',
        correct: 'Kommst du nicht mit? – Doch, ich komme mit.',
        explanation:
          'To contradict a negative question, German uses doch, not ja; ja would confusingly seem to confirm the negative.',
      },
      {
        incorrect: 'Du hast Zeit?',
        correct: 'Hast du Zeit?',
        explanation:
          'A yes/no question needs the finite verb in position 1, before the subject, not after it.',
      },
      {
        incorrect: 'Ja ich komme mit.',
        correct: 'Ja, ich komme mit.',
        explanation: 'ja and nein are set off from the rest of the sentence with a comma.',
      },
      {
        incorrect: 'Isst du kein Fleisch? – Nein, ich esse Fleisch.',
        correct: 'Isst du kein Fleisch? – Doch, ich esse Fleisch.',
        explanation:
          'Since the fact is positive (you do eat meat) but the question was negative, the contradiction requires doch; nein would wrongly confirm that you eat no meat.',
      },
      {
        incorrect: 'Du stehst früh auf?',
        correct: 'Stehst du früh auf?',
        explanation:
          'Even with separable verbs, the finite verb part moves to position 1 in a yes/no question; the prefix (auf) stays at the end.',
      },
    ],
    remember: [
      'A yes/no question has no question word: the finite verb stands in position 1, the subject in position 2.',
      'Short answers (Ja. / Nein.) are fine, but full answers repeat the verb: Ja, ich komme mit.',
      'Use doch, not ja, to contradict a negative question; use nein to agree with it.',
      'In speech, rising intonation at the end confirms a yes/no question.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch11-ex-01',
      chapterNumber: 11,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['yes-no-questions', 'word-order'],
      instruction: 'Choose the sentence that is a correctly formed yes/no question.',
      prompt: 'Which sentence is a correctly formed yes/no question?',
      options: [
        { id: 'a', text: 'Kommst du mit?' },
        { id: 'b', text: 'Du kommst mit?' },
        { id: 'c', text: 'Mit du kommst?' },
        { id: 'd', text: 'Kommst mit du?' },
      ],
      correctOptionId: 'a',
      explanation:
        'In a yes/no question the finite verb kommst stands in position 1 and the subject du follows immediately in position 2: Kommst du mit?',
    },
    {
      id: 'ch11-ex-02',
      chapterNumber: 11,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['yes-no-questions', 'word-order'],
      instruction: 'Choose the yes/no question that matches the statement.',
      prompt: 'Statement: "Sie wohnt in Hamburg." Which is the matching yes/no question?',
      options: [
        { id: 'a', text: 'Wohnt sie in Hamburg?' },
        { id: 'b', text: 'Sie wohnt in Hamburg?' },
        { id: 'c', text: 'In Hamburg wohnt sie?' },
        { id: 'd', text: 'Wo wohnt sie?' },
      ],
      correctOptionId: 'a',
      explanation:
        'To build the yes/no question, move the finite verb wohnt to position 1: Wohnt sie in Hamburg? Option d asks with a question word (wo), which makes it a W-question, not a yes/no question.',
    },
    {
      id: 'ch11-ex-03',
      chapterNumber: 11,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['ja-nein-doch'],
      instruction: 'Choose ja, nein, or doch to complete the answer correctly.',
      prompt: 'Isst du gern Fisch? – ___, ich esse sehr gern Fisch.',
      options: [
        { id: 'a', text: 'Ja' },
        { id: 'b', text: 'Nein' },
        { id: 'c', text: 'Doch' },
      ],
      correctOptionId: 'a',
      explanation:
        'The question is positive (no nicht or kein), and the answer confirms it, so ja is correct.',
    },
    {
      id: 'ch11-ex-04',
      chapterNumber: 11,
      order: 4,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Choose ja, nein, or doch to complete the answer correctly.',
      prompt: 'Kommst du nicht mit ins Kino? – ___, ich komme mit.',
      options: [
        { id: 'a', text: 'Ja' },
        { id: 'b', text: 'Nein' },
        { id: 'c', text: 'Doch' },
      ],
      correctOptionId: 'c',
      explanation:
        'The question is negative (nicht), but the fact is positive (you are coming), so you must contradict it with doch, not ja.',
    },
    {
      id: 'ch11-ex-05',
      chapterNumber: 11,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Choose ja, nein, or doch to complete the answer correctly.',
      prompt: 'Hast du kein Geld dabei? – ___, ich habe kein Geld dabei.',
      options: [
        { id: 'a', text: 'Ja' },
        { id: 'b', text: 'Nein' },
        { id: 'c', text: 'Doch' },
      ],
      correctOptionId: 'b',
      explanation:
        'The question is negative and the fact agrees with it (you really have no money), so nein confirms the negative question.',
    },
    {
      id: 'ch11-ex-06',
      chapterNumber: 11,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ja-nein-doch'],
      instruction: 'Choose ja, nein, or doch to complete the answer correctly.',
      prompt: 'Spielst du Fußball? – ___, ich spiele nicht gern Fußball.',
      options: [
        { id: 'a', text: 'Ja' },
        { id: 'b', text: 'Nein' },
        { id: 'c', text: 'Doch' },
      ],
      correctOptionId: 'b',
      explanation:
        'The question is positive, and the answer rejects it, so nein is correct; doch is only used to contradict a negative question.',
    },
    {
      id: 'ch11-ex-07',
      chapterNumber: 11,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['yes-no-questions', 'w-questions'],
      instruction: 'Choose the sentence that is a yes/no question rather than a W-question.',
      prompt: 'Which of these is a yes/no question rather than a W-question?',
      options: [
        { id: 'a', text: 'Warum lernst du Deutsch?' },
        { id: 'b', text: 'Lernst du Deutsch?' },
        { id: 'c', text: 'Wann lernst du Deutsch?' },
        { id: 'd', text: 'Wie lernst du Deutsch?' },
      ],
      correctOptionId: 'b',
      explanation:
        'Lernst du Deutsch? has no question word — the finite verb lernst simply stands first — so it is a yes/no question. The others begin with a question word and are W-questions.',
    },
    {
      id: 'ch11-ex-08',
      chapterNumber: 11,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['short-full-answers'],
      instruction: 'Choose the correctly formed full answer.',
      prompt: 'Regnet es heute? Which sentence correctly means "Yes, it is raining"?',
      options: [
        { id: 'a', text: 'Ja, es regnet.' },
        { id: 'b', text: 'Ja es regnet.' },
        { id: 'c', text: 'Ja, regnet es.' },
        { id: 'd', text: 'Es ja regnet.' },
      ],
      correctOptionId: 'a',
      explanation:
        'ja is set off with a comma, and the sentence that follows keeps normal statement word order: Ja, es regnet.',
    },
    {
      id: 'ch11-ex-09',
      chapterNumber: 11,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Choose ja, nein, or doch to complete the answer correctly.',
      prompt: 'Bist du nicht müde? – ___, ich bin überhaupt nicht müde.',
      options: [
        { id: 'a', text: 'Ja' },
        { id: 'b', text: 'Nein' },
        { id: 'c', text: 'Doch' },
      ],
      correctOptionId: 'b',
      explanation:
        'The question is negative and the fact agrees with it (you are indeed not tired), so nein confirms the negative question; doch would wrongly claim you are tired.',
    },
    {
      id: 'ch11-ex-10',
      chapterNumber: 11,
      order: 10,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Choose the answer that fits the situation described.',
      prompt:
        'Frage: "Trinkt ihr keinen Tee?" Ihr trinkt aber sehr gern Tee. Welche Antwort passt?',
      options: [
        { id: 'a', text: 'Ja, wir trinken gern Tee.' },
        { id: 'b', text: 'Nein, wir trinken gern Tee.' },
        { id: 'c', text: 'Doch, wir trinken gern Tee.' },
        { id: 'd', text: 'Doch, wir trinken keinen Tee.' },
      ],
      correctOptionId: 'c',
      explanation:
        'The question is negative, but the fact is positive (you do like tea), so the contradiction requires doch, and the sentence itself states the true, positive fact.',
    },
    {
      id: 'ch11-ex-11',
      chapterNumber: 11,
      order: 11,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Choose the answer that fits the situation described.',
      prompt:
        'A friend asks: "Fährst du nicht mit dem Auto zur Arbeit?" You actually walk to work. Which answer is correct?',
      options: [
        { id: 'a', text: 'Doch, ich fahre mit dem Auto.' },
        { id: 'b', text: 'Nein, ich gehe zu Fuß.' },
        { id: 'c', text: 'Ja, ich gehe zu Fuß.' },
        { id: 'd', text: 'Doch, ich gehe zu Fuß.' },
      ],
      correctOptionId: 'b',
      explanation:
        'The question is negative and the fact agrees with it (you really do not drive), so nein confirms the negative question, followed by the true information.',
    },
    {
      id: 'ch11-ex-12',
      chapterNumber: 11,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['yes-no-questions'],
      instruction: 'Choose the question that fits the given answer.',
      prompt: 'Which question fits this answer? "Nein, wir haben morgen keine Zeit."',
      options: [
        { id: 'a', text: 'Habt ihr morgen Zeit?' },
        { id: 'b', text: 'Wann habt ihr Zeit?' },
        { id: 'c', text: 'Warum habt ihr keine Zeit?' },
        { id: 'd', text: 'Wer hat morgen Zeit?' },
      ],
      correctOptionId: 'a',
      explanation:
        'The answer Nein, wir haben keine Zeit responds to a yes/no question about having time: Habt ihr morgen Zeit?',
    },
    {
      id: 'ch11-ex-13',
      chapterNumber: 11,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['yes-no-questions', 'word-order'],
      instruction:
        'Turn the statement into a yes/no question. Write the complete question, including the question mark.',
      prompt: 'Du sprichst gut Deutsch.',
      acceptedAnswers: ['Sprichst du gut Deutsch?'],
      answerMode: 'normalized',
      placeholder: 'Sprichst ...',
      maxLength: 40,
      explanation:
        'Move the finite verb sprichst to position 1 and put the subject du in position 2: Sprichst du gut Deutsch?',
    },
    {
      id: 'ch11-ex-14',
      chapterNumber: 11,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['yes-no-questions', 'word-order'],
      instruction:
        'Turn the statement into a yes/no question. Write the complete question, including the question mark.',
      prompt: 'Ihr kauft heute Obst.',
      acceptedAnswers: ['Kauft ihr heute Obst?'],
      answerMode: 'normalized',
      placeholder: 'Kauft ...',
      maxLength: 40,
      explanation:
        'The finite verb kauft moves to position 1, and the subject ihr follows in position 2: Kauft ihr heute Obst?',
    },
    {
      id: 'ch11-ex-15',
      chapterNumber: 11,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['yes-no-questions', 'word-order'],
      instruction:
        'Turn the statement into a yes/no question. Write the complete question, including the question mark.',
      prompt: 'Er hat morgen Zeit.',
      acceptedAnswers: ['Hat er morgen Zeit?'],
      answerMode: 'normalized',
      placeholder: 'Hat ...',
      maxLength: 30,
      explanation: 'hat moves to position 1 and er to position 2: Hat er morgen Zeit?',
    },
    {
      id: 'ch11-ex-16',
      chapterNumber: 11,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['ja-nein-doch'],
      instruction: 'Complete the answer with ja, nein, or doch. Capitalisation is not checked.',
      prompt: 'Wohnst du in München? – ___, ich wohne in München.',
      acceptedAnswers: ['ja'],
      answerMode: 'caseInsensitive',
      placeholder: 'ja / nein / doch',
      maxLength: 10,
      explanation: 'The question is positive and the answer confirms it, so ja is correct.',
    },
    {
      id: 'ch11-ex-17',
      chapterNumber: 11,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Complete the answer with ja, nein, or doch. Capitalisation is not checked.',
      prompt: 'Isst du kein Gemüse? – ___, ich esse sehr gern Gemüse.',
      acceptedAnswers: ['doch'],
      answerMode: 'caseInsensitive',
      placeholder: 'ja / nein / doch',
      maxLength: 10,
      explanation:
        'The question is negative, but the fact is positive, so doch is needed to contradict it.',
    },
    {
      id: 'ch11-ex-18',
      chapterNumber: 11,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Complete the answer with ja, nein, or doch. Capitalisation is not checked.',
      prompt: 'Kommt Anna heute nicht zur Party? – ___, sie kommt nicht.',
      acceptedAnswers: ['nein'],
      answerMode: 'caseInsensitive',
      placeholder: 'ja / nein / doch',
      maxLength: 10,
      explanation:
        'The question is negative and the fact agrees with it, so nein confirms the negative question.',
    },
    {
      id: 'ch11-ex-19',
      chapterNumber: 11,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['short-full-answers', 'ja-nein-doch'],
      instruction:
        'Answer the question with a full sentence, using ja and the cue words. Capitalisation and punctuation are checked.',
      prompt: 'Frage: Machst du heute deine Hausaufgaben? (ja – ich – machen – heute – meine Hausaufgaben)',
      acceptedAnswers: ['Ja, ich mache heute meine Hausaufgaben.'],
      answerMode: 'normalized',
      placeholder: 'Ja, ...',
      maxLength: 60,
      explanation:
        'Start with Ja, add a comma, then keep normal statement word order: subject ich, verb mache, then the rest of the sentence.',
    },
    {
      id: 'ch11-ex-20',
      chapterNumber: 11,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['short-full-answers', 'ja-nein-doch'],
      instruction:
        'Answer the question with a full sentence, using nein and the cue words. Capitalisation and punctuation are checked.',
      prompt: 'Frage: Trinkst du Kaffee am Abend? (nein – ich – trinken – keinen Kaffee – am Abend)',
      acceptedAnswers: ['Nein, ich trinke keinen Kaffee am Abend.'],
      answerMode: 'normalized',
      placeholder: 'Nein, ...',
      maxLength: 60,
      explanation:
        'Nein confirms the positive question negatively; the sentence then states the negative fact with kein.',
    },
    {
      id: 'ch11-ex-21',
      chapterNumber: 11,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction:
        'Answer the question with a full sentence, using doch and the cue words. Capitalisation and punctuation are checked.',
      prompt: 'Frage: Hilfst du deiner Schwester nicht? (doch – ich – helfen – meiner Schwester)',
      acceptedAnswers: ['Doch, ich helfe meiner Schwester.'],
      answerMode: 'normalized',
      placeholder: 'Doch, ...',
      maxLength: 50,
      explanation:
        'The question is negative, but you do help her, so the contradiction requires doch, followed by the positive statement.',
    },
    {
      id: 'ch11-ex-22',
      chapterNumber: 11,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['yes-no-questions', 'negation', 'word-order'],
      instruction:
        'Build a negated yes/no question from the cue words. Capitalisation and punctuation are checked.',
      prompt: 'du – heute – nicht – kommen – mit',
      acceptedAnswers: ['Kommst du heute nicht mit?'],
      answerMode: 'normalized',
      placeholder: 'Kommst ...',
      maxLength: 40,
      explanation:
        'The finite verb kommst stands first, then the subject du, then the rest of the sentence including the negation nicht: Kommst du heute nicht mit?',
    },
    {
      id: 'ch11-ex-23',
      chapterNumber: 11,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['ja-nein-doch', 'negation'],
      instruction: 'Answer with a full sentence. Capitalisation and punctuation are checked.',
      prompt:
        'Deine Freundin fragt: "Wohnst du nicht mehr in Köln?" Du wohnst aber immer noch in Köln. Antworte mit einem vollständigen Satz.',
      acceptedAnswers: [
        'Doch, ich wohne immer noch in Köln.',
        'Doch, ich wohne noch in Köln.',
      ],
      answerMode: 'normalized',
      placeholder: 'Doch, ...',
      maxLength: 60,
      explanation:
        'The question is negative, but the fact is positive (you still live in Cologne), so the answer must open with doch, not ja.',
    },
    {
      id: 'ch11-ex-24',
      chapterNumber: 11,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['yes-no-questions', 'word-order'],
      instruction:
        'Turn the statement into a yes/no question. Write the complete question, including the question mark.',
      prompt: 'Statement: "Du stehst jeden Tag um sechs Uhr auf."',
      acceptedAnswers: ['Stehst du jeden Tag um sechs Uhr auf?'],
      answerMode: 'normalized',
      placeholder: 'Stehst ...',
      maxLength: 60,
      explanation:
        'With separable verbs, only the finite part (stehst) moves to position 1; the separable prefix auf stays at the end of the sentence: Stehst du jeden Tag um sechs Uhr auf?',
    },
  ],
};
