import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter055: ChapterDefinition = {
  id: 'chapter-055',
  number: 55,
  slug: 'the-past-perfect',
  title: 'The Past Perfect',
  germanTitle: 'Plusquamperfekt',
  level: 'B1',
  section: 'verbs-3',
  objective:
    'Form the past perfect (Plusquamperfekt) with hatte/war (the simple past of haben/sein) plus a past participle, using the same auxiliary rule as the present perfect, to express an earlier past event relative to another past event — and use nachdem, bevor, and als to sequence two past-tense clauses correctly.',
  prerequisites: [25, 26, 27, 28, 54],
  estimatedMinutes: 28,
  tags: [
    'plusquamperfekt',
    'past-perfect',
    'hatte',
    'war',
    'nachdem',
    'bevor',
    'als',
    'word-order',
    'temporal-connectors',
    'narrative-past',
  ],
  explanation: {
    introduction: [
      'The past perfect (Plusquamperfekt) is the tense German uses to talk about something that had already happened before another point in the past. If the simple past and the present perfect describe "what happened", the past perfect describes "what had already happened by then" — it always needs a second past-tense event or moment to relate to.',
      'You already know both building blocks. Chapter 25 taught you the simple past of haben and sein (hatte, war); Chapters 26-28 taught you the present perfect, built from a conjugated haben/sein plus a past participle. The past perfect simply combines them: instead of the present-tense habe/bin, it uses the simple-past hatte/war, followed by exactly the same past participle you already know how to form. Ich hatte gegessen. (I had eaten.) Ich war gegangen. (I had gone.)',
      'Because the past perfect always looks backward from another past moment, it appears constantly in narratives and stories, and very often together with the connectors nachdem (after), bevor (before), and als (when), which this chapter also covers: they tell you which of two past events came first, and therefore which one needs the past perfect.',
    ],
    rules: [
      {
        id: 'ch55-rule-01',
        heading: 'Two parts: hatte/war + past participle',
        paragraphs: [
          'Just like the present perfect, the past perfect has two parts: an auxiliary and a past participle. The only difference is that the auxiliary is in the simple past instead of the present tense: hatte or war instead of habe/hat or bin/ist. Ich hatte das Buch gelesen. (I had read the book.) Er war schon angekommen. (He had already arrived.)',
          'The participle itself never changes — it is exactly the same form you learned for the present perfect (gelesen, gegessen, gefahren, gegangen ...). Only the auxiliary changes, and only its tense changes, from present to simple past.',
        ],
      },
      {
        id: 'ch55-rule-02',
        heading: 'Auxiliary choice: the same rule as the present perfect',
        paragraphs: [
          'Whether a verb takes hatte or war in the past perfect follows exactly the rule you already learned for haben vs. sein in Chapter 27: verbs of movement to a destination (gehen, fahren, fliegen, kommen, laufen) and verbs of change of state (werden, and others) take sein — so their past perfect is built with war. The exception verbs sein, bleiben, and passieren also take sein. Every other verb takes haben, so its past perfect is built with hatte.',
          "Sie war schon nach Berlin gefahren. (She had already travelled to Berlin — fahren to a destination, sein.) Wir hatten den Kuchen schon gegessen. (We had already eaten the cake — essen, haben.) If you already know a verb's auxiliary from the present perfect, you know it for the past perfect too — nothing changes there.",
        ],
      },
      {
        id: 'ch55-rule-03',
        heading: 'Meaning: an earlier past — the event before the event',
        paragraphs: [
          'The past perfect places one action or state before another action or state that is also in the past. It answers the question "what had already happened by the time X happened?" On its own, without a second past-tense reference point, the past perfect sounds incomplete — it is a relative tense, defined by its relationship to another past event.',
          'Ich hatte schon gegessen, als meine Freunde ankamen. (I had already eaten when my friends arrived.) Here, eating happened first (past perfect); the friends arriving happened second (simple past). Compare this with a plain past-tense statement, Ich aß um sieben Uhr (I ate at seven), which only reports one event with no explicit "before/after" relationship to another.',
          'A useful mental picture: the simple past or present perfect tells the main story in chronological order; the past perfect is a flashback, a step back in time to something that was already finished before the main story\'s "now".',
        ],
      },
      {
        id: 'ch55-rule-04',
        heading: 'Past perfect vs. simple past and present perfect',
        paragraphs: [
          'In a narrative, the past perfect and the simple past (or present perfect, in spoken German) typically work as a pair: the simple past/present perfect carries the story forward, event by event, while the past perfect steps back to fill in something that happened earlier. Once that earlier event has been mentioned, the story usually returns to the simple past to continue.',
          'Nachdem sie die Prüfung bestanden hatte, feierte sie mit ihren Freunden. (After she had passed the exam, she celebrated with her friends.) bestanden hatte is the flashback (the exam, finished earlier); feierte carries the story forward in the simple past.',
          'Using the past perfect where a simple past would do (with no earlier event in sight) makes a sentence sound like it is missing its other half — German listeners will expect you to say what happened after, or what it was earlier than.',
        ],
      },
      {
        id: 'ch55-rule-05',
        heading: 'Word order in a main clause: the familiar verb bracket',
        paragraphs: [
          'In a main clause, the past perfect follows the same verb-bracket pattern as the present perfect: the conjugated auxiliary (hatte/war) stands in position 2, and the past participle closes the clause at the very end. Ich hatte gestern schon meine Hausaufgaben gemacht. (I had already done my homework yesterday.)',
          'In a yes/no question, hatte/war moves to position 1: Hattest du das schon gesehen? (Had you already seen that?) In a W-question, the question word comes first and hatte/war follows in position 2: Wann warst du angekommen? (When had you arrived?)',
        ],
      },
      {
        id: 'ch55-rule-06',
        heading: 'Temporal connectors: nachdem, bevor, als',
        paragraphs: [
          'nachdem ("after"), bevor ("before"), and als ("when") are the connectors most often used to link a past perfect clause with a simple-past clause, because they explicitly state the order of two past events. Whichever clause describes the earlier event needs the past perfect; the clause describing the later event stays in the simple past — this is true no matter which connector is used.',
          'With nachdem, the nachdem-clause itself names the earlier event, so it takes the past perfect, and the main clause (the later event) takes the simple past: Nachdem ich gegessen hatte, ging ich spazieren. (After I had eaten, I went for a walk.) With bevor, it is the other way around: the bevor-clause names the later event and stays in the simple past, while the main clause names the earlier event and takes the past perfect: Bevor ich schlafen ging, hatte ich noch aufgeräumt. (Before I went to sleep, I had tidied up.)',
          'als introduces a single completed moment in the past, in the simple past; if something else had already finished by that moment, that other event is expressed with the past perfect, wherever it appears in the sentence: Als ich ankam, hatte der Film schon begonnen. (When I arrived, the film had already begun.)',
        ],
        notes: [
          'Rule of thumb: find the earlier event first — that clause gets the past perfect. The connector (nachdem/bevor/als) then tells you which clause that is.',
        ],
      },
      {
        id: 'ch55-rule-07',
        heading: 'Word order in a subordinate clause with nachdem, bevor, als',
        paragraphs: [
          'Subordinate clauses send the finite verb to the very end. In a past-perfect subordinate clause, that means the past participle comes first and the conjugated hatte/war follows it, right at the end of the clause: Nachdem ich gegessen hatte, ... (participle gegessen, then hatte). Bevor sie schlafen ging, ... uses the simple past instead, so only one verb (ging) sits at the end.',
          "The main clause keeps its normal verb-second order even when the subordinate clause comes first: the whole subordinate clause counts as position 1, so the main clause's conjugated verb must follow immediately after the comma, in position 2. Nachdem ich gegessen hatte, ging ich spazieren. — ging stands right after the comma, not ich.",
        ],
      },
    ],
    tables: [
      {
        id: 'ch55-table-01',
        title: 'hatte — simple past of haben (past-perfect auxiliary)',
        columns: ['Person', 'Form'],
        rows: [
          ['ich', 'hatte'],
          ['du', 'hattest'],
          ['er/sie/es', 'hatte'],
          ['wir', 'hatten'],
          ['ihr', 'hattet'],
          ['sie/Sie', 'hatten'],
        ],
      },
      {
        id: 'ch55-table-02',
        title: 'war — simple past of sein (past-perfect auxiliary)',
        columns: ['Person', 'Form'],
        rows: [
          ['ich', 'war'],
          ['du', 'warst'],
          ['er/sie/es', 'war'],
          ['wir', 'waren'],
          ['ihr', 'wart'],
          ['sie/Sie', 'waren'],
        ],
      },
      {
        id: 'ch55-table-03',
        title: 'Past perfect: worked examples',
        columns: ['Infinitive', 'Auxiliary', 'Past Perfect (er/sie/es)'],
        rows: [
          ['sein', 'war', 'war gewesen'],
          ['haben', 'hatte', 'hatte gehabt'],
          ['gehen', 'war', 'war gegangen'],
          ['kommen', 'war', 'war gekommen'],
          ['sehen', 'hatte', 'hatte gesehen'],
          ['essen', 'hatte', 'hatte gegessen'],
          ['fahren', 'war', 'war gefahren'],
          ['bleiben', 'war', 'war geblieben'],
        ],
        note: 'The auxiliary is exactly the one each verb already takes in the present perfect (Chapters 26-27); only its tense changes, from present to simple past.',
      },
      {
        id: 'ch55-table-04',
        title: 'Temporal connectors: nachdem, bevor, als',
        columns: ['Connector', 'Tense sequencing', 'Example'],
        rows: [
          [
            'nachdem (after)',
            'subordinate clause (earlier event) = past perfect; main clause (later event) = simple past',
            'Nachdem ich gegessen hatte, ging ich spazieren.',
          ],
          [
            'bevor (before)',
            'subordinate clause (later event) = simple past; main clause (earlier event) = past perfect',
            'Bevor ich schlafen ging, hatte ich noch aufgeräumt.',
          ],
          [
            'als (when)',
            'subordinate clause = simple past, single reference moment; the already-finished event = past perfect',
            'Als ich ankam, hatte der Film schon begonnen.',
          ],
        ],
        note: 'In every case, the earlier of the two events is the one that takes the past perfect — the connector just tells you which clause that is.',
      },
      {
        id: 'ch55-table-05',
        title: 'The verb bracket in the past perfect',
        columns: [
          'Position 1',
          'Position 2 (hatte/war)',
          'Middle field',
          'End (participle)',
        ],
        rows: [
          ['Ich', 'hatte', 'das Buch schon', 'gelesen.'],
          ['Wir', 'waren', 'schon', 'gegangen.'],
          ['Hattest', 'du', 'das schon', 'gesehen?'],
        ],
        note: 'The third row shows a question, where hatte itself moves to position 1; the participle still stays at the very end.',
      },
    ],
    examples: [
      {
        german: 'Ich hatte das Buch schon gelesen, bevor der Film begann.',
        english: 'I had already read the book before the film began.',
        highlight: ['hatte', 'gelesen'],
        explanation:
          'hatte + gelesen forms the past perfect of lesen; the reading was already finished before the film started.',
      },
      {
        german: 'Nachdem wir gegessen hatten, gingen wir spazieren.',
        english: 'After we had eaten, we went for a walk.',
        highlight: ['gegessen hatten', 'gingen'],
        explanation:
          'The nachdem-clause names the earlier event with the past perfect; the main clause names the later event with the simple past.',
      },
      {
        german: 'Er war schon nach Hause gefahren, als ich ankam.',
        english: 'He had already driven home when I arrived.',
        highlight: ['war', 'gefahren'],
        explanation:
          'fahren with a destination takes sein, so the past perfect is war + gefahren, exactly as in the present perfect.',
      },
      {
        german: 'Bevor sie schlafen ging, hatte sie noch ihre E-Mails geschrieben.',
        english: 'Before she went to sleep, she had still written her emails.',
        highlight: ['hatte', 'geschrieben'],
        explanation:
          'The main clause names the earlier event (writing emails) with the past perfect; the bevor-clause names the later event (going to sleep) with the simple past.',
      },
      {
        german: 'Als ich ankam, hatte der Film schon begonnen.',
        english: 'When I arrived, the film had already begun.',
        highlight: ['hatte', 'begonnen'],
        explanation:
          'als introduces a single past moment (ankam, simple past); the past perfect hatte begonnen shows the film started even earlier.',
      },
      {
        german: 'Ich hatte meinen Schlüssel nicht gefunden.',
        english: 'I had not found my key.',
        highlight: ['hatte', 'nicht', 'gefunden'],
        explanation:
          'nicht stands directly before the participle, exactly as in the present perfect.',
      },
      {
        german: 'Bevor wir das Haus kauften, hatten wir lange gespart.',
        english: 'Before we bought the house, we had saved for a long time.',
        highlight: ['hatten', 'gespart'],
        explanation:
          'The earlier event (saving) is expressed with the past perfect; the later event (buying) is expressed with the simple past kauften.',
      },
      {
        german: 'Wir waren zu Hause geblieben, weil es den ganzen Tag geregnet hatte.',
        english: 'We had stayed home because it had rained all day.',
        highlight: ['waren', 'geblieben'],
        explanation:
          'bleiben is one of the sein-exception verbs, exactly as in the present perfect, so its past perfect is war/waren, not hatte/hatten.',
      },
      {
        german: 'Hattest du den Brief schon geschrieben?',
        english: 'Had you already written the letter?',
        highlight: ['Hattest', 'geschrieben'],
        explanation:
          'In a yes/no question, the conjugated hatte moves to position 1; the participle still closes the sentence.',
      },
      {
        german: 'Warst du schon gegangen, als ich anrief?',
        english: 'Had you already left when I called?',
        highlight: ['Warst', 'gegangen'],
        explanation:
          'gehen takes sein; in this question warst moves to position 1 and gegangen closes the sentence.',
      },
      {
        german: 'Nachdem er den Kaffee getrunken hatte, fühlte er sich wacher.',
        english: 'After he had drunk the coffee, he felt more awake.',
        highlight: ['getrunken hatte', 'fühlte'],
        explanation:
          'trinken forms its past perfect with hatte + getrunken; in the subordinate clause the participle comes first and hatte stands at the very end.',
      },
      {
        german: 'Bevor sie berühmt wurde, hatte sie jahrelang hart gearbeitet.',
        english: 'Before she became famous, she had worked hard for years.',
        highlight: ['hatte', 'gearbeitet'],
        explanation:
          'The main clause names the earlier event (years of work) with the past perfect; the bevor-clause names the later event (becoming famous) with the simple past wurde.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Nachdem ich gegessen habe, ging ich spazieren.',
        correct: 'Nachdem ich gegessen hatte, ging ich spazieren.',
        explanation:
          'When the main clause is in the simple past, the earlier event in a nachdem-clause needs the past perfect (hatte + participle), not the present perfect (habe + participle).',
      },
      {
        incorrect: 'Ich hatte nach Hause gegangen.',
        correct: 'Ich war nach Hause gegangen.',
        explanation:
          'gehen takes sein as its auxiliary, exactly as in the present perfect (ich bin gegangen) — the past perfect uses war, not hatte.',
      },
      {
        incorrect: 'Nachdem ich hatte gegessen, ging ich spazieren.',
        correct: 'Nachdem ich gegessen hatte, ging ich spazieren.',
        explanation:
          'In a subordinate clause, the conjugated auxiliary hatte/war moves to the very end, after the participle, not directly after the subject.',
      },
      {
        incorrect: 'Bevor ich ankam, der Film hatte schon begonnen.',
        correct: 'Bevor ich ankam, hatte der Film schon begonnen.',
        explanation:
          'The main clause keeps normal verb-second word order even when a subordinate clause opens the sentence: hatte must stand immediately after the comma, before the subject der Film.',
      },
      {
        incorrect: 'Wir haben zu Hause geblieben, weil es geregnet hatte.',
        correct: 'Wir waren zu Hause geblieben, weil es geregnet hatte.',
        explanation:
          'bleiben is one of the sein-exception verbs, just like in the present perfect; its past perfect is formed with war/waren, not hatte/hatten.',
      },
    ],
    remember: [
      'The past perfect (Plusquamperfekt) is built from the simple past of haben or sein (hatte/war) plus the past participle: hatte gemacht, war gegangen.',
      'The auxiliary choice (hatte vs. war) is exactly the same as in the present perfect: movement/change-of-state verbs and the exceptions sein, bleiben, werden, passieren take war; everything else takes hatte.',
      'Use the past perfect for an event that had already happened before another past event or moment — the "earlier past". The later event is normally told in the simple past.',
      'nachdem, bevor, and als connect two past events: whichever clause names the earlier event takes the past perfect, and whichever names the later event stays in the simple past, no matter which connector is used.',
      'Word order: hatte/war stands in position 2 in a main clause (or position 1 in a question); in a subordinate clause, the participle comes first and hatte/war moves to the very end.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 76,
    requiredCorrectTextInputs: 15,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch55-ex-01',
      chapterNumber: 55,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['past-perfect', 'auxiliary', 'recognition'],
      instruction:
        'Identify the auxiliary verb that forms the past perfect in this sentence.',
      prompt:
        'Ich hatte das Buch schon gelesen, bevor ich den Film sah. Which word is the past-perfect auxiliary?',
      options: [
        { id: 'a', text: 'hatte' },
        { id: 'b', text: 'gelesen' },
        { id: 'c', text: 'Buch' },
        { id: 'd', text: 'bevor' },
      ],
      correctOptionId: 'a',
      explanation:
        'hatte is the simple-past form of haben, the auxiliary that combines with the past participle to form the past perfect (Plusquamperfekt).',
    },
    {
      id: 'ch55-ex-02',
      chapterNumber: 55,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['past-perfect', 'participle', 'recognition'],
      instruction: 'Identify the past participle in this sentence.',
      prompt:
        'Er war schon nach Hause gefahren, als ich ankam. Which word is the past participle?',
      options: [
        { id: 'a', text: 'war' },
        { id: 'b', text: 'gefahren' },
        { id: 'c', text: 'ankam' },
        { id: 'd', text: 'schon' },
      ],
      correctOptionId: 'b',
      explanation:
        'gefahren is the past participle of fahren; together with war it forms the past perfect.',
    },
    {
      id: 'ch55-ex-03',
      chapterNumber: 55,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['past-perfect', 'meaning', 'recognition'],
      instruction:
        'Choose the correct description of what the past perfect (Plusquamperfekt) expresses.',
      prompt: 'What does the past perfect express?',
      options: [
        {
          id: 'a',
          text: 'An action that had already happened before another past action or moment',
        },
        { id: 'b', text: 'An action happening right now' },
        { id: 'c', text: 'An action that will happen in the future' },
        { id: 'd', text: 'A general truth with no specific time' },
      ],
      correctOptionId: 'a',
      explanation:
        'The past perfect marks the earlier of two past events — something that was already completed before another past action or moment.',
    },
    {
      id: 'ch55-ex-04',
      chapterNumber: 55,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['event-ordering', 'nachdem', 'recognition'],
      instruction: 'Read the sentence and identify which event happened first.',
      prompt:
        'Nachdem ich gegessen hatte, ging ich spazieren. Which event happened first?',
      options: [
        { id: 'a', text: 'Eating (ich hatte gegessen)' },
        { id: 'b', text: 'Going for a walk (ich ging spazieren)' },
        { id: 'c', text: 'Both happened at exactly the same time' },
        { id: 'd', text: 'Neither is in the past' },
      ],
      correctOptionId: 'a',
      explanation:
        'The past perfect (hatte gegessen) marks the earlier event; the simple past (ging) marks the event that followed it.',
    },
    {
      id: 'ch55-ex-05',
      chapterNumber: 55,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['word-order', 'recognition'],
      instruction: 'Choose the sentence with the correct past-perfect word order.',
      prompt: 'Which sentence follows the verb bracket rule correctly?',
      options: [
        { id: 'a', text: 'Ich hatte gelesen das Buch.' },
        { id: 'b', text: 'Ich hatte das Buch gelesen.' },
        { id: 'c', text: 'Ich gelesen hatte das Buch.' },
        { id: 'd', text: 'Das Buch ich hatte gelesen.' },
      ],
      correctOptionId: 'b',
      explanation:
        'hatte stands in position 2 and the participle gelesen closes the clause at the very end, exactly as in the present perfect.',
    },
    {
      id: 'ch55-ex-06',
      chapterNumber: 55,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['past-perfect', 'formation', 'recognition'],
      instruction: 'Choose the correct description of how the past perfect is formed.',
      prompt: 'How is the German past perfect (Plusquamperfekt) built?',
      options: [
        {
          id: 'a',
          text: 'the simple past of haben or sein (hatte/war) + past participle',
        },
        {
          id: 'b',
          text: 'the present tense of haben or sein (habe/bin) + past participle',
        },
        { id: 'c', text: 'only a past participle, no auxiliary' },
        { id: 'd', text: 'würde + infinitive' },
      ],
      correctOptionId: 'a',
      explanation:
        'The past perfect uses the simple-past auxiliary hatte or war, not the present-tense habe or bin, together with the past participle.',
    },
    {
      id: 'ch55-ex-07',
      chapterNumber: 55,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'war', 'gehen', 'controlled'],
      instruction: 'Choose the correct auxiliary.',
      prompt: 'Ich ___ schon nach Hause gegangen, bevor der Regen begann.',
      options: [
        { id: 'a', text: 'hatte' },
        { id: 'b', text: 'habe' },
        { id: 'c', text: 'war' },
        { id: 'd', text: 'bin' },
      ],
      correctOptionId: 'c',
      explanation:
        'gehen takes sein, exactly as in the present perfect; the past-perfect auxiliary here is war.',
    },
    {
      id: 'ch55-ex-08',
      chapterNumber: 55,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'hatte', 'essen', 'controlled'],
      instruction: 'Choose the correct auxiliary.',
      prompt: 'Wir ___ schon gegessen, als sie ankamen.',
      options: [
        { id: 'a', text: 'waren' },
        { id: 'b', text: 'hatten' },
        { id: 'c', text: 'sind' },
        { id: 'd', text: 'haben' },
      ],
      correctOptionId: 'b',
      explanation:
        'essen takes haben, exactly as in the present perfect; the past-perfect auxiliary here is hatten.',
    },
    {
      id: 'ch55-ex-09',
      chapterNumber: 55,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['conjugation', 'hatte', 'du', 'controlled'],
      instruction: 'Choose the correct form of haben (simple past) for the subject.',
      prompt: 'Du ___ den Film schon gesehen, bevor wir ins Kino gingen.',
      options: [
        { id: 'a', text: 'hatte' },
        { id: 'b', text: 'hattest' },
        { id: 'c', text: 'hattet' },
        { id: 'd', text: 'hatten' },
      ],
      correctOptionId: 'b',
      explanation: 'The du-form of haben in the simple past is hattest.',
    },
    {
      id: 'ch55-ex-10',
      chapterNumber: 55,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['conjugation', 'war', 'wir', 'controlled'],
      instruction: 'Choose the correct form of sein (simple past) for the subject.',
      prompt: 'Wir ___ schon nach Hause gefahren, als es zu regnen begann.',
      options: [
        { id: 'a', text: 'waren' },
        { id: 'b', text: 'hatten' },
        { id: 'c', text: 'sind' },
        { id: 'd', text: 'haben' },
      ],
      correctOptionId: 'a',
      explanation:
        'The wir-form of sein in the simple past is waren; fahren with a destination takes sein.',
    },
    {
      id: 'ch55-ex-11',
      chapterNumber: 55,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['nachdem', 'connectors', 'controlled'],
      instruction: 'Choose the connector that correctly links the two past events.',
      prompt:
        'Complete: "___ ich gegessen hatte, ging ich spazieren." (After I had eaten, I went for a walk.)',
      options: [
        { id: 'a', text: 'Nachdem' },
        { id: 'b', text: 'Bevor' },
        { id: 'c', text: 'Als' },
        { id: 'd', text: 'Während' },
      ],
      correctOptionId: 'a',
      explanation:
        'nachdem ("after") introduces the earlier event, which is why it is paired here with the past perfect hatte gegessen.',
    },
    {
      id: 'ch55-ex-12',
      chapterNumber: 55,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['bevor', 'connectors', 'controlled'],
      instruction: 'Choose the connector that correctly links the two past events.',
      prompt:
        'Complete: "___ sie schlafen ging, hatte sie noch ihre E-Mails geschrieben." (Before she went to sleep, she had written her emails.)',
      options: [
        { id: 'a', text: 'Nachdem' },
        { id: 'b', text: 'Bevor' },
        { id: 'c', text: 'Als' },
        { id: 'd', text: 'Weil' },
      ],
      correctOptionId: 'b',
      explanation:
        'bevor ("before") introduces the later event (schlafen ging, simple past); the earlier event (writing emails) is in the main clause with the past perfect.',
    },
    {
      id: 'ch55-ex-13',
      chapterNumber: 55,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['als', 'connectors', 'controlled'],
      instruction: 'Choose the connector that correctly links the two past events.',
      prompt:
        'Complete: "___ ich ankam, hatte der Film schon begonnen." (When I arrived, the film had already begun.)',
      options: [
        { id: 'a', text: 'Als' },
        { id: 'b', text: 'Bevor' },
        { id: 'c', text: 'Nachdem' },
        { id: 'd', text: 'Ob' },
      ],
      correctOptionId: 'a',
      explanation:
        'als introduces a single completed moment in the past (ich ankam); the past perfect hatte begonnen shows the film started even earlier.',
    },
    {
      id: 'ch55-ex-14',
      chapterNumber: 55,
      order: 14,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['event-ordering', 'bevor', 'transfer'],
      instruction: 'Read the sentence and identify which event happened first.',
      prompt:
        'Bevor wir das Haus kauften, hatten wir lange gespart. Which event happened first?',
      options: [
        { id: 'a', text: 'Saving money (hatten gespart)' },
        { id: 'b', text: 'Buying the house (kauften)' },
        { id: 'c', text: 'Both happened at the same time' },
        { id: 'd', text: 'It cannot be determined' },
      ],
      correctOptionId: 'a',
      explanation:
        'The main clause carries the past perfect (hatten gespart), marking the earlier event; the bevor-clause (kauften) is in the simple past and happened later.',
    },
    {
      id: 'ch55-ex-15',
      chapterNumber: 55,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['word-order', 'nachdem', 'transfer'],
      instruction:
        'Choose the sentence with the correct word order in the nachdem-clause.',
      prompt: 'Which sentence has the correct word order?',
      options: [
        { id: 'a', text: 'Nachdem ich hatte gegessen, ging ich spazieren.' },
        { id: 'b', text: 'Nachdem ich gegessen hatte, ging ich spazieren.' },
        { id: 'c', text: 'Nachdem hatte ich gegessen, ging ich spazieren.' },
        { id: 'd', text: 'Nachdem gegessen ich hatte, ging ich spazieren.' },
      ],
      correctOptionId: 'b',
      explanation:
        'In a subordinate clause, the participle comes first and the conjugated auxiliary hatte moves to the very end: gegessen hatte.',
    },
    {
      id: 'ch55-ex-16',
      chapterNumber: 55,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['conjugation', 'hatte', 'ich', 'controlled'],
      instruction:
        'Write only the correct form of haben (simple past) that belongs in the gap. Capitalisation is not checked.',
      prompt: 'Ich ___ ihm das Geld schon gegeben, bevor er fragte.',
      acceptedAnswers: ['hatte'],
      answerMode: 'caseInsensitive',
      placeholder: 'hatte / hattest / hatten ...',
      maxLength: 10,
      explanation:
        'The ich-form of haben in the simple past is hatte; geben takes haben.',
    },
    {
      id: 'ch55-ex-17',
      chapterNumber: 55,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['conjugation', 'war', 'er-sie-es', 'controlled'],
      instruction:
        'Write only the correct form of sein (simple past) that belongs in the gap. Capitalisation is not checked.',
      prompt: 'Sie (she) ___ schon gekommen, als das Meeting begann.',
      acceptedAnswers: ['war'],
      answerMode: 'caseInsensitive',
      placeholder: 'war / warst / waren ...',
      maxLength: 10,
      explanation:
        'The er/sie/es-form of sein in the simple past is war; kommen takes sein.',
    },
    {
      id: 'ch55-ex-18',
      chapterNumber: 55,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['participle', 'nehmen', 'controlled'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'Er hatte den Bus schon ___. (nehmen)',
      acceptedAnswers: ['genommen'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...en',
      maxLength: 15,
      explanation: 'The past participle of nehmen is genommen.',
    },
    {
      id: 'ch55-ex-19',
      chapterNumber: 55,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['participle', 'fliegen', 'controlled'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'Wir waren schon nach Rom ___. (fliegen)',
      acceptedAnswers: ['geflogen'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...en',
      maxLength: 15,
      explanation: 'The past participle of fliegen is geflogen.',
    },
    {
      id: 'ch55-ex-20',
      chapterNumber: 55,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-completion', 'hatte', 'trinken', 'controlled'],
      instruction:
        'Complete the sentence with the correct auxiliary and past participle of the verb in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'Ich ___ den Kaffee schon ___, bevor er kalt wurde. (trinken)',
      acceptedAnswers: ['hatte getrunken'],
      answerMode: 'normalized',
      placeholder: 'hatte/war ... ge...',
      maxLength: 25,
      explanation:
        'trinken takes haben; with ich the correct completion is hatte getrunken.',
    },
    {
      id: 'ch55-ex-21',
      chapterNumber: 55,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-completion', 'war', 'laufen', 'controlled'],
      instruction:
        'Complete the sentence with the correct auxiliary and past participle of the verb in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'Sie (she) ___ schon zehn Kilometer ___, bevor die Sonne aufging. (laufen)',
      acceptedAnswers: ['war gelaufen'],
      answerMode: 'normalized',
      placeholder: 'hatte/war ... ge...',
      maxLength: 25,
      explanation:
        'laufen takes sein; with sie (she) the correct completion is war gelaufen.',
    },
    {
      id: 'ch55-ex-22',
      chapterNumber: 55,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['nachdem', 'connectors', 'controlled'],
      instruction: 'Fill in the missing connector. Capitalisation is not checked.',
      prompt: '___ wir gegessen hatten, gingen wir ins Kino. (After)',
      acceptedAnswers: ['Nachdem', 'nachdem'],
      answerMode: 'caseInsensitive',
      placeholder: 'Nachdem',
      maxLength: 15,
      explanation:
        'nachdem ("after") introduces the earlier event, marked here with the past perfect gegessen hatten.',
    },
    {
      id: 'ch55-ex-23',
      chapterNumber: 55,
      order: 23,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['nachdem', 'sentence-building', 'production'],
      instruction:
        'Write a complete sentence using nachdem: the earlier event in the past perfect, the later event in the simple past. Capitalisation and punctuation are checked.',
      prompt: 'nachdem – ich (essen) – ich (spazieren gehen)',
      acceptedAnswers: ['Nachdem ich gegessen hatte, ging ich spazieren.'],
      answerMode: 'normalized',
      placeholder: 'Nachdem ich ..., ging ich ...',
      maxLength: 60,
      explanation:
        'The nachdem-clause carries the earlier event in the past perfect (gegessen hatte); the main clause carries the later event in the simple past (ging).',
    },
    {
      id: 'ch55-ex-24',
      chapterNumber: 55,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['bevor', 'sentence-building', 'production'],
      instruction:
        'Write a complete sentence using bevor: the later event in the simple past (bevor-clause), the earlier event in the past perfect (main clause). Capitalisation and punctuation are checked.',
      prompt: 'bevor – sie (schlafen gehen) – sie (E-Mails schreiben)',
      acceptedAnswers: [
        'Bevor sie schlafen ging, hatte sie E-Mails geschrieben.',
        'Bevor sie schlafen ging, hatte sie ihre E-Mails geschrieben.',
      ],
      answerMode: 'normalized',
      placeholder: 'Bevor sie ..., hatte sie ...',
      maxLength: 70,
      explanation:
        'The bevor-clause names the later event in the simple past (ging); the main clause names the earlier event in the past perfect (hatte geschrieben).',
    },
    {
      id: 'ch55-ex-25',
      chapterNumber: 55,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['als', 'sentence-building', 'production'],
      instruction:
        'Write a complete sentence using als: a single past moment in the simple past, plus an even earlier event in the past perfect. Capitalisation and punctuation are checked.',
      prompt: 'als – ich (kommen) – der Film (schon beginnen)',
      acceptedAnswers: ['Als ich kam, hatte der Film schon begonnen.'],
      answerMode: 'normalized',
      placeholder: 'Als ich kam, hatte der Film ...',
      maxLength: 60,
      explanation:
        'als introduces the reference moment in the simple past (kam); the past perfect (hatte ... begonnen) shows the film started even earlier.',
    },
    {
      id: 'ch55-ex-26',
      chapterNumber: 55,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['narrative', 'hatte', 'war', 'production'],
      instruction:
        'Complete the short narrative with the correct past-perfect forms. Write the two missing verb groups in order, separated by a space. Capitalisation is not checked.',
      prompt:
        'Bevor Emma nach Hause kam, ___ ihr Bruder schon den Film ___. (sehen) Er ___ danach noch schnell einkaufen ___. (gehen)',
      acceptedAnswers: ['hatte gesehen war gegangen'],
      answerMode: 'caseInsensitive',
      placeholder: 'hatte gesehen war gegangen',
      maxLength: 40,
      explanation:
        'sehen takes haben (hatte gesehen); gehen takes sein (war gegangen) — the same auxiliary rule as in the present perfect.',
    },
    {
      id: 'ch55-ex-27',
      chapterNumber: 55,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'nachdem', 'transfer'],
      instruction:
        'Correct the mistake in tense. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Nachdem ich gegessen habe, ging ich spazieren.',
      acceptedAnswers: ['Nachdem ich gegessen hatte, ging ich spazieren.'],
      answerMode: 'normalized',
      placeholder: 'Nachdem ich gegessen hatte, ...',
      maxLength: 60,
      explanation:
        'With a simple-past main clause, the earlier event in the nachdem-clause needs the past perfect (hatte gegessen), not the present perfect (habe gegessen).',
    },
    {
      id: 'ch55-ex-28',
      chapterNumber: 55,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'word-order', 'transfer'],
      instruction:
        'Correct the mistake in word order. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Nachdem ich hatte gegessen, ging ich spazieren.',
      acceptedAnswers: ['Nachdem ich gegessen hatte, ging ich spazieren.'],
      answerMode: 'normalized',
      placeholder: 'Nachdem ich gegessen hatte, ...',
      maxLength: 60,
      explanation:
        'In a subordinate clause, the participle comes first and the conjugated auxiliary hatte moves to the very end.',
    },
    {
      id: 'ch55-ex-29',
      chapterNumber: 55,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'aux-choice', 'transfer'],
      instruction:
        'Correct the mistake in auxiliary choice. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich hatte nach Hause gegangen.',
      acceptedAnswers: ['Ich war nach Hause gegangen.'],
      answerMode: 'normalized',
      placeholder: 'Ich war ...',
      maxLength: 40,
      explanation:
        'gehen takes sein, exactly as in the present perfect (ich bin gegangen); the past perfect is war gegangen, not hatte gegangen.',
    },
    {
      id: 'ch55-ex-30',
      chapterNumber: 55,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['event-ordering', 'nachdem', 'transfer'],
      instruction:
        'Read the sentence, then answer in German with a short infinitive phrase naming the action that happened first. Capitalisation is not checked.',
      prompt:
        'Nachdem ich meine Arbeit beendet hatte, rief ich meinen Freund an. Was geschah zuerst?',
      acceptedAnswers: [
        'die Arbeit beenden',
        'meine Arbeit beenden',
        'die arbeit beenden',
        'arbeit beenden',
      ],
      answerMode: 'normalized',
      placeholder: 'die Arbeit beenden',
      maxLength: 40,
      explanation:
        'The past perfect (Arbeit beendet hatte) marks the earlier event: finishing the work happened before calling the friend.',
    },
    {
      id: 'ch55-ex-31',
      chapterNumber: 55,
      order: 31,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['past-perfect', 'auxiliary', 'recognition'],
      instruction:
        'Identify the auxiliary verb that forms the past perfect in this sentence.',
      prompt:
        'Sie hatte den Brief schon geschrieben, bevor die Post kam. Which word is the past-perfect auxiliary?',
      options: [
        { id: 'a', text: 'hatte' },
        { id: 'b', text: 'geschrieben' },
        { id: 'c', text: 'Brief' },
        { id: 'd', text: 'kam' },
      ],
      correctOptionId: 'a',
      explanation:
        'hatte is the simple-past form of haben, the auxiliary that combines with geschrieben to form the past perfect.',
    },
    {
      id: 'ch55-ex-32',
      chapterNumber: 55,
      order: 32,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'war', 'ankommen', 'controlled'],
      instruction: 'Choose the correct auxiliary.',
      prompt: 'Wir ___ schon angekommen, bevor der Regen begann.',
      options: [
        { id: 'a', text: 'hatten' },
        { id: 'b', text: 'waren' },
        { id: 'c', text: 'haben' },
        { id: 'd', text: 'sind' },
      ],
      correctOptionId: 'b',
      explanation:
        'ankommen takes sein, exactly as in the present perfect; the past-perfect auxiliary here is waren.',
    },
    {
      id: 'ch55-ex-33',
      chapterNumber: 55,
      order: 33,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['als', 'event-ordering', 'controlled'],
      instruction:
        'Choose the sentence that correctly shows the film starting before the arrival.',
      prompt:
        'Which sentence correctly says the film had already started when the speaker arrived?',
      options: [
        { id: 'a', text: 'Als ich ankam, hatte der Film schon begonnen.' },
        { id: 'b', text: 'Als ich ankam, habe der Film schon begonnen.' },
        { id: 'c', text: 'Als ich ankam, der Film hatte schon begonnen.' },
        { id: 'd', text: 'Als ich hatte angekommen, begann der Film schon.' },
      ],
      correctOptionId: 'a',
      explanation:
        'als introduces the simple-past reference moment (ankam); the earlier event (the film starting) needs the past perfect hatte begonnen, with hatte in position 2 of the main clause.',
    },
    {
      id: 'ch55-ex-34',
      chapterNumber: 55,
      order: 34,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['past-perfect', 'present-perfect', 'tense-choice', 'transfer'],
      instruction: 'Choose the sentence that correctly sequences two past events.',
      prompt:
        'Which sentence correctly shows that the eating happened before the walk, with the walk told in the simple past?',
      options: [
        { id: 'a', text: 'Nachdem ich gegessen habe, ging ich spazieren.' },
        { id: 'b', text: 'Nachdem ich gegessen hatte, ging ich spazieren.' },
        { id: 'c', text: 'Nachdem ich esse, ging ich spazieren.' },
        { id: 'd', text: 'Nachdem ich gegessen hatte, gehe ich spazieren.' },
      ],
      correctOptionId: 'b',
      explanation:
        'With a simple-past main clause (ging), the earlier event in the nachdem-clause needs the past perfect (gegessen hatte), not the present perfect (gegessen habe).',
    },
    {
      id: 'ch55-ex-35',
      chapterNumber: 55,
      order: 35,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['word-order', 'bevor', 'transfer'],
      instruction: 'Choose the sentence with the correct word order.',
      prompt:
        'Which sentence follows the verb-second rule correctly when a subordinate clause opens the sentence?',
      options: [
        { id: 'a', text: 'Bevor ich ankam, der Film hatte schon begonnen.' },
        { id: 'b', text: 'Bevor ich ankam, hatte der Film schon begonnen.' },
        { id: 'c', text: 'Bevor ich ankam, schon hatte der Film begonnen.' },
        { id: 'd', text: 'Bevor ich ankam, der Film schon begonnen hatte.' },
      ],
      correctOptionId: 'b',
      explanation:
        'The subordinate clause counts as position 1, so hatte must stand immediately after the comma, in position 2 of the main clause, before the subject der Film.',
    },
    {
      id: 'ch55-ex-36',
      chapterNumber: 55,
      order: 36,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['conjugation', 'hatte', 'sie-plural', 'controlled'],
      instruction:
        'Write only the correct form of haben (simple past) that belongs in the gap. Capitalisation is not checked.',
      prompt: 'Sie (they) ___ das Auto schon repariert, bevor wir ankamen.',
      acceptedAnswers: ['hatten'],
      answerMode: 'caseInsensitive',
      placeholder: 'hatte / hattest / hatten ...',
      maxLength: 10,
      explanation:
        'The sie (plural)-form of haben in the simple past is hatten; reparieren takes haben.',
    },
    {
      id: 'ch55-ex-37',
      chapterNumber: 55,
      order: 37,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['conjugation', 'war', 'ihr', 'controlled'],
      instruction:
        'Write only the correct form of sein (simple past) that belongs in the gap. Capitalisation is not checked.',
      prompt: 'Ihr ___ schon angekommen, als der Bus abfuhr.',
      acceptedAnswers: ['wart'],
      answerMode: 'caseInsensitive',
      placeholder: 'war / warst / wart ...',
      maxLength: 10,
      explanation:
        'The ihr-form of sein in the simple past is wart; ankommen takes sein.',
    },
    {
      id: 'ch55-ex-38',
      chapterNumber: 55,
      order: 38,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['participle', 'verlieren', 'controlled'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'Ich hatte meinen Schlüssel schon ___. (verlieren)',
      acceptedAnswers: ['verloren'],
      answerMode: 'caseInsensitive',
      placeholder: 'ge...en',
      maxLength: 15,
      explanation: 'The past participle of verlieren is verloren.',
    },
    {
      id: 'ch55-ex-39',
      chapterNumber: 55,
      order: 39,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['participle', 'aufwachen', 'controlled'],
      instruction: 'Write the past participle. Capitalisation is not checked.',
      prompt: 'Er war schon ___, als das Telefon klingelte. (aufwachen)',
      acceptedAnswers: ['aufgewacht'],
      answerMode: 'caseInsensitive',
      placeholder: 'auf...',
      maxLength: 15,
      explanation:
        'The past participle of aufwachen is aufgewacht; aufwachen takes sein.',
    },
    {
      id: 'ch55-ex-40',
      chapterNumber: 55,
      order: 40,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-completion', 'hatte', 'aufraeumen', 'controlled'],
      instruction:
        'Complete the sentence with the correct auxiliary and past participle of the verb in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'Wir ___ das Zimmer schon ___, bevor die Gäste kamen. (aufräumen)',
      acceptedAnswers: ['hatten aufgeräumt'],
      answerMode: 'normalized',
      placeholder: 'hatte/war ... ge...',
      maxLength: 25,
      explanation:
        'aufräumen takes haben; with wir the correct completion is hatten aufgeräumt.',
    },
    {
      id: 'ch55-ex-41',
      chapterNumber: 55,
      order: 41,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sentence-completion', 'war', 'aufstehen', 'controlled'],
      instruction:
        'Complete the sentence with the correct auxiliary and past participle of the verb in brackets. Capitalisation is checked; no full stop is required.',
      prompt: 'Sie (she) ___ schon ___, als der Wecker klingelte. (aufstehen)',
      acceptedAnswers: ['war aufgestanden'],
      answerMode: 'normalized',
      placeholder: 'hatte/war ... ge...',
      maxLength: 25,
      explanation:
        'aufstehen takes sein; with sie (she) the correct completion is war aufgestanden.',
    },
    {
      id: 'ch55-ex-42',
      chapterNumber: 55,
      order: 42,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['nachdem', 'connectors', 'controlled'],
      instruction: 'Fill in the missing connector. Capitalisation is not checked.',
      prompt: '___ er den Kaffee getrunken hatte, fühlte er sich wacher. (After)',
      acceptedAnswers: ['Nachdem', 'nachdem'],
      answerMode: 'caseInsensitive',
      placeholder: 'Nachdem',
      maxLength: 15,
      explanation:
        'nachdem ("after") introduces the earlier event, marked here with the past perfect getrunken hatte.',
    },
    {
      id: 'ch55-ex-43',
      chapterNumber: 55,
      order: 43,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['bevor', 'connectors', 'controlled'],
      instruction: 'Fill in the missing connector. Capitalisation is not checked.',
      prompt: '___ ich schlafen ging, hatte ich noch aufgeräumt. (Before)',
      acceptedAnswers: ['Bevor', 'bevor'],
      answerMode: 'caseInsensitive',
      placeholder: 'Bevor',
      maxLength: 15,
      explanation:
        'bevor ("before") introduces the later event (schlafen ging); the main clause names the earlier event with the past perfect.',
    },
    {
      id: 'ch55-ex-44',
      chapterNumber: 55,
      order: 44,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['als', 'connectors', 'controlled'],
      instruction: 'Fill in the missing connector. Capitalisation is not checked.',
      prompt: '___ ich ankam, hatte der Zug schon abgefahren. (When)',
      acceptedAnswers: ['Als', 'als'],
      answerMode: 'caseInsensitive',
      placeholder: 'Als',
      maxLength: 15,
      explanation:
        'als introduces the single reference moment (ich ankam); the past perfect hatte abgefahren shows the train left even earlier.',
    },
    {
      id: 'ch55-ex-45',
      chapterNumber: 55,
      order: 45,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['nachdem', 'sentence-building', 'production'],
      instruction:
        'Write a complete sentence using nachdem: the earlier event in the past perfect, the later event in the simple past. Capitalisation and punctuation are checked.',
      prompt: 'nachdem – er (aufstehen) – er (frühstücken)',
      acceptedAnswers: ['Nachdem er aufgestanden war, frühstückte er.'],
      answerMode: 'normalized',
      placeholder: 'Nachdem er ..., frühstückte er.',
      maxLength: 60,
      explanation:
        'aufstehen takes sein, so the earlier event is aufgestanden war; frühstückte carries the story forward in the simple past.',
    },
    {
      id: 'ch55-ex-46',
      chapterNumber: 55,
      order: 46,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['bevor', 'sentence-building', 'production'],
      instruction:
        'Write a complete sentence using bevor: the later event in the simple past (bevor-clause), the earlier event in the past perfect (main clause). Capitalisation and punctuation are checked.',
      prompt: 'bevor – wir (das Haus verlassen) – wir (die Fenster schließen)',
      acceptedAnswers: [
        'Bevor wir das Haus verließen, hatten wir die Fenster geschlossen.',
      ],
      answerMode: 'normalized',
      placeholder: 'Bevor wir ..., hatten wir ...',
      maxLength: 70,
      explanation:
        'The bevor-clause names the later event in the simple past (verließen); the main clause names the earlier event in the past perfect (hatten geschlossen).',
    },
    {
      id: 'ch55-ex-47',
      chapterNumber: 55,
      order: 47,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['als', 'sentence-building', 'production'],
      instruction:
        'Write a complete sentence using als: a single past moment in the simple past, plus an even earlier event in the past perfect. Capitalisation and punctuation are checked.',
      prompt: 'als – sie (ankommen) – die Party (schon beginnen)',
      acceptedAnswers: ['Als sie ankam, hatte die Party schon begonnen.'],
      answerMode: 'normalized',
      placeholder: 'Als sie ankam, hatte die Party ...',
      maxLength: 60,
      explanation:
        'als introduces the reference moment in the simple past (ankam); the past perfect (hatte ... begonnen) shows the party started even earlier.',
    },
    {
      id: 'ch55-ex-48',
      chapterNumber: 55,
      order: 48,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['narrative', 'hatte', 'war', 'production'],
      instruction:
        'Complete the short narrative with the correct past-perfect forms. Write the two missing verb groups in order, separated by a space. Capitalisation is not checked.',
      prompt:
        'Bevor Lisa im Büro ankam, ___ ihr Kollege schon die E-Mails ___. (lesen) Er ___ dann noch kurz Kaffee holen ___. (gehen)',
      acceptedAnswers: ['hatte gelesen war gegangen'],
      answerMode: 'caseInsensitive',
      placeholder: 'hatte gelesen war gegangen',
      maxLength: 40,
      explanation:
        'lesen takes haben (hatte gelesen); gehen takes sein (war gegangen) — the same auxiliary rule as in the present perfect.',
    },
    {
      id: 'ch55-ex-49',
      chapterNumber: 55,
      order: 49,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'aux-choice', 'transfer'],
      instruction:
        'Correct the mistake in auxiliary choice. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Sie hatte nach Berlin gefahren.',
      acceptedAnswers: ['Sie war nach Berlin gefahren.'],
      answerMode: 'normalized',
      placeholder: 'Sie war ...',
      maxLength: 40,
      explanation:
        'fahren with a destination takes sein, exactly as in the present perfect (sie ist gefahren); the past perfect is war gefahren, not hatte gefahren.',
    },
    {
      id: 'ch55-ex-50',
      chapterNumber: 55,
      order: 50,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'word-order', 'transfer'],
      instruction:
        'Correct the mistake in word order. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Bevor ich ankam, der Film hatte schon begonnen.',
      acceptedAnswers: ['Bevor ich ankam, hatte der Film schon begonnen.'],
      answerMode: 'normalized',
      placeholder: 'Bevor ich ankam, hatte der Film ...',
      maxLength: 60,
      explanation:
        'The main clause keeps normal verb-second word order even when a subordinate clause opens the sentence: hatte must stand immediately after the comma, before the subject der Film.',
    },
    {
      id: 'ch55-ex-51',
      chapterNumber: 55,
      order: 51,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'past-perfect', 'present-perfect', 'transfer'],
      instruction:
        'Correct the mistake in tense. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Nachdem sie gegessen hat, ging sie spazieren.',
      acceptedAnswers: ['Nachdem sie gegessen hatte, ging sie spazieren.'],
      answerMode: 'normalized',
      placeholder: 'Nachdem sie gegessen hatte, ...',
      maxLength: 60,
      explanation:
        'With a simple-past main clause, the earlier event in the nachdem-clause needs the past perfect (hatte gegessen), not the present perfect (hat gegessen).',
    },
    {
      id: 'ch55-ex-52',
      chapterNumber: 55,
      order: 52,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['error-correction', 'aux-choice', 'sterben', 'transfer'],
      instruction:
        'Correct the mistake in auxiliary choice. Write the full corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Der Hund hatte gestorben, bevor der Tierarzt kam.',
      acceptedAnswers: ['Der Hund war gestorben, bevor der Tierarzt kam.'],
      answerMode: 'normalized',
      placeholder: 'Der Hund war gestorben, ...',
      maxLength: 60,
      explanation:
        'sterben takes sein, exactly as in the present perfect (der Hund ist gestorben); the past perfect is war gestorben, not hatte gestorben.',
    },
    {
      id: 'ch55-ex-53',
      chapterNumber: 55,
      order: 53,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['event-ordering', 'nachdem', 'transfer'],
      instruction:
        'Read the sentence, then answer in German with a short infinitive phrase naming the action that happened first. Capitalisation is not checked.',
      prompt:
        'Nachdem die Sonne untergegangen war, gingen wir nach Hause. Was geschah zuerst?',
      acceptedAnswers: [
        'die Sonne untergehen',
        'die sonne untergehen',
        'sonne untergehen',
      ],
      answerMode: 'normalized',
      placeholder: 'die Sonne untergehen',
      maxLength: 40,
      explanation:
        'The past perfect (untergegangen war) marks the earlier event: the sun setting happened before we went home.',
    },
    {
      id: 'ch55-ex-54',
      chapterNumber: 55,
      order: 54,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'hatte', 'reparieren', 'controlled'],
      instruction: 'Drag the correct auxiliary into the gap.',
      prompt: 'Ich ___ das Auto schon repariert, bevor er kam.',
      templateParts: ['Ich ', ' das Auto schon repariert, bevor er kam.'],
      slots: [{ id: 'ch55-ex54-slot1', correctWord: 'hatte' }],
      wordBank: ['hatte', 'war', 'habe', 'bin'],
      explanation:
        'reparieren takes haben, so the past-perfect auxiliary with ich is hatte.',
    },
    {
      id: 'ch55-ex-55',
      chapterNumber: 55,
      order: 55,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'participle', 'gehen', 'controlled'],
      instruction: 'Drag the correct auxiliary and participle into the gaps.',
      prompt: 'Wir ___ schon nach Hause ___, als der Regen begann.',
      templateParts: ['Wir ', ' schon nach Hause ', ', als der Regen begann.'],
      slots: [
        { id: 'ch55-ex55-slot1', correctWord: 'waren' },
        { id: 'ch55-ex55-slot2', correctWord: 'gegangen' },
      ],
      wordBank: ['waren', 'gegangen', 'hatten', 'gefahren'],
      explanation: 'gehen takes sein, so the past perfect with wir is waren gegangen.',
    },
    {
      id: 'ch55-ex-56',
      chapterNumber: 55,
      order: 56,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['participle', 'schreiben', 'controlled'],
      instruction: 'Drag the correct past participle into the gap.',
      prompt: 'Sie hatte den Brief schon ___, bevor die Post kam.',
      templateParts: ['Sie hatte den Brief schon ', ', bevor die Post kam.'],
      slots: [{ id: 'ch55-ex56-slot1', correctWord: 'geschrieben' }],
      wordBank: ['geschrieben', 'gesehen', 'gemacht', 'gelesen'],
      explanation: 'The past participle of schreiben is geschrieben.',
    },
    {
      id: 'ch55-ex-57',
      chapterNumber: 55,
      order: 57,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'war', 'ankommen', 'controlled'],
      instruction: 'Drag the correct auxiliary into the gap.',
      prompt: 'Er ___ schon angekommen, als wir ihn suchten.',
      templateParts: ['Er ', ' schon angekommen, als wir ihn suchten.'],
      slots: [{ id: 'ch55-ex57-slot1', correctWord: 'war' }],
      wordBank: ['war', 'hatte', 'ist', 'hat'],
      explanation: 'ankommen takes sein, so the past-perfect auxiliary with er is war.',
    },
    {
      id: 'ch55-ex-58',
      chapterNumber: 55,
      order: 58,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['word-order', 'subordinate-clause', 'nachdem', 'controlled'],
      instruction:
        'Drag the correct auxiliary into the gap at the end of the subordinate clause.',
      prompt: 'Nachdem wir gegessen ___, gingen wir spazieren.',
      templateParts: ['Nachdem wir gegessen ', ', gingen wir spazieren.'],
      slots: [{ id: 'ch55-ex58-slot1', correctWord: 'hatten' }],
      wordBank: ['hatten', 'hatte', 'waren', 'war'],
      explanation:
        'essen takes haben, and in a subordinate clause the conjugated auxiliary follows the participle, right at the end: gegessen hatten.',
    },
    {
      id: 'ch55-ex-59',
      chapterNumber: 55,
      order: 59,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['question', 'hattest', 'packen', 'controlled'],
      instruction: 'Drag the correct question form into the gap.',
      prompt: '___ du schon gepackt, bevor der Bus kam?',
      templateParts: ['', ' du schon gepackt, bevor der Bus kam?'],
      slots: [{ id: 'ch55-ex59-slot1', correctWord: 'Hattest' }],
      wordBank: ['Hattest', 'Warst', 'Hatte', 'War'],
      explanation:
        'packen takes haben; in a yes/no question the conjugated auxiliary moves to position 1: Hattest du ...?',
    },
    {
      id: 'ch55-ex-60',
      chapterNumber: 55,
      order: 60,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'participle', 'sterben', 'controlled'],
      instruction: 'Drag the correct auxiliary and participle into the gaps.',
      prompt: 'Der Hund ___ schon ___, bevor der Tierarzt kam.',
      templateParts: ['Der Hund ', ' schon ', ', bevor der Tierarzt kam.'],
      slots: [
        { id: 'ch55-ex60-slot1', correctWord: 'war' },
        { id: 'ch55-ex60-slot2', correctWord: 'gestorben' },
      ],
      wordBank: ['war', 'gestorben', 'hatte', 'gelebt'],
      explanation: 'sterben takes sein, so the past perfect is war gestorben.',
    },
    {
      id: 'ch55-ex-61',
      chapterNumber: 55,
      order: 61,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['participle', 'vergessen', 'controlled'],
      instruction: 'Drag the correct past participle into the gap.',
      prompt: 'Ich hatte meinen Regenschirm ___.',
      templateParts: ['Ich hatte meinen Regenschirm ', '.'],
      slots: [{ id: 'ch55-ex61-slot1', correctWord: 'vergessen' }],
      wordBank: ['vergessen', 'verloren', 'gefunden', 'gekauft'],
      explanation:
        'The past participle of vergessen is vergessen itself, unchanged, since ver- verbs do not take the ge- prefix.',
    },
    {
      id: 'ch55-ex-62',
      chapterNumber: 55,
      order: 62,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['aux-choice', 'war', 'reisen', 'controlled'],
      instruction: 'Drag the correct auxiliary into the gap.',
      prompt: 'Wir ___ schon nach Spanien gereist, bevor wir umzogen.',
      templateParts: ['Wir ', ' schon nach Spanien gereist, bevor wir umzogen.'],
      slots: [{ id: 'ch55-ex62-slot1', correctWord: 'waren' }],
      wordBank: ['waren', 'hatten', 'sind', 'haben'],
      explanation: 'reisen takes sein, so the past-perfect auxiliary with wir is waren.',
    },
    {
      id: 'ch55-ex-63',
      chapterNumber: 55,
      order: 63,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['aux-choice', 'participle', 'ankommen', 'transfer'],
      instruction: 'Drag the correct auxiliary and participle into the gaps.',
      prompt: 'Bevor der Film begann, ___ wir schon ___.',
      templateParts: ['Bevor der Film begann, ', ' wir schon ', '.'],
      slots: [
        { id: 'ch55-ex63-slot1', correctWord: 'waren' },
        { id: 'ch55-ex63-slot2', correctWord: 'angekommen' },
      ],
      wordBank: ['waren', 'angekommen', 'hatten', 'gekommen'],
      explanation:
        'ankommen takes sein, so the past perfect is waren angekommen — the earlier event, before the film began.',
    },
    {
      id: 'ch55-ex-64',
      chapterNumber: 55,
      order: 64,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['nachdem', 'word-order', 'production'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Nachdem ich gegessen hatte, + ging + ich + spazieren.',
      segments: [
        { id: 's1', text: 'Nachdem ich gegessen hatte,' },
        { id: 's2', text: 'ging' },
        { id: 's3', text: 'ich' },
        { id: 's4', text: 'spazieren.' },
      ],
      explanation:
        'The nachdem-clause names the earlier event with the past perfect; the main clause follows with verb-second order: ging comes right after the comma.',
    },
    {
      id: 'ch55-ex-65',
      chapterNumber: 55,
      order: 65,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['bevor', 'word-order', 'production'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Bevor sie schlafen ging, + hatte + sie + ihre E-Mails geschrieben.',
      segments: [
        { id: 's1', text: 'Bevor sie schlafen ging,' },
        { id: 's2', text: 'hatte' },
        { id: 's3', text: 'sie' },
        { id: 's4', text: 'ihre E-Mails geschrieben.' },
      ],
      explanation:
        'The bevor-clause names the later event in the simple past; the main clause names the earlier event with the past perfect, hatte in position 2.',
    },
    {
      id: 'ch55-ex-66',
      chapterNumber: 55,
      order: 66,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['als', 'word-order', 'production'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Als der Zug ankam, + hatten + wir + schon unsere Plätze gefunden.',
      segments: [
        { id: 's1', text: 'Als der Zug ankam,' },
        { id: 's2', text: 'hatten' },
        { id: 's3', text: 'wir' },
        { id: 's4', text: 'schon unsere Plätze gefunden.' },
      ],
      explanation:
        'als introduces the reference moment in the simple past; the main clause shows the earlier event with the past perfect, hatten in position 2.',
    },
    {
      id: 'ch55-ex-67',
      chapterNumber: 55,
      order: 67,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['nachdem', 'word-order', 'production'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Nachdem wir das Museum besucht hatten, + aßen + wir + zu Mittag.',
      segments: [
        { id: 's1', text: 'Nachdem wir das Museum besucht hatten,' },
        { id: 's2', text: 'aßen' },
        { id: 's3', text: 'wir' },
        { id: 's4', text: 'zu Mittag.' },
      ],
      explanation:
        'The nachdem-clause names the earlier event (visiting the museum) with the past perfect; aßen carries the story forward in the simple past.',
    },
    {
      id: 'ch55-ex-68',
      chapterNumber: 55,
      order: 68,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['bevor', 'word-order', 'transfer'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Bevor der Lehrer kam, + hatten + die Schüler + ihre Hausaufgaben gemacht.',
      segments: [
        { id: 's1', text: 'Bevor der Lehrer kam,' },
        { id: 's2', text: 'hatten' },
        { id: 's3', text: 'die Schüler' },
        { id: 's4', text: 'ihre Hausaufgaben gemacht.' },
      ],
      explanation:
        'The bevor-clause names the later event in the simple past; the main clause names the earlier event with the past perfect, hatten in position 2.',
    },
    {
      id: 'ch55-ex-69',
      chapterNumber: 55,
      order: 69,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['als', 'word-order', 'transfer'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Als ich das Fenster öffnete, + war + die Katze + schon verschwunden.',
      segments: [
        { id: 's1', text: 'Als ich das Fenster öffnete,' },
        { id: 's2', text: 'war' },
        { id: 's3', text: 'die Katze' },
        { id: 's4', text: 'schon verschwunden.' },
      ],
      explanation:
        'als introduces the reference moment in the simple past; the past perfect (war verschwunden) shows the cat had already vanished by then — verschwinden takes sein.',
    },
    {
      id: 'ch55-ex-70',
      chapterNumber: 55,
      order: 70,
      type: 'sentenceOrdering',
      level: 'transfer',
      grammarFocus: ['nachdem', 'word-order', 'transfer'],
      instruction: 'Drag the segments into the correct order.',
      prompt: 'Nachdem sie ihre Koffer gepackt hatte, + rief + sie + ein Taxi.',
      segments: [
        { id: 's1', text: 'Nachdem sie ihre Koffer gepackt hatte,' },
        { id: 's2', text: 'rief' },
        { id: 's3', text: 'sie' },
        { id: 's4', text: 'ein Taxi.' },
      ],
      explanation:
        'The nachdem-clause names the earlier event (packing) with the past perfect; rief carries the story forward in the simple past.',
    },
    {
      id: 'ch55-ex-71',
      chapterNumber: 55,
      order: 71,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'aux-choice', 'gehen', 'production'],
      instruction: 'Find the token with the wrong auxiliary, and correct it.',
      prompt: 'Ein Lerner beschreibt seinen Abend. Etwas stimmt nicht.',
      tokens: ['Ich', 'hatte', 'nach', 'Hause', 'gegangen.'],
      errorTokenIndex: 1,
      correction: 'Ich war nach Hause gegangen.',
      explanation:
        'gehen takes sein, exactly as in the present perfect (ich bin gegangen); the past perfect is war gegangen, not hatte gegangen.',
    },
    {
      id: 'ch55-ex-72',
      chapterNumber: 55,
      order: 72,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'aux-choice', 'bleiben', 'production'],
      instruction: 'Find the token with the wrong auxiliary, and correct it.',
      prompt: 'Ein Lerner erklärt, warum niemand ausging. Etwas stimmt nicht.',
      tokens: ['Wir', 'haben', 'zu', 'Hause', 'geblieben.'],
      errorTokenIndex: 1,
      correction: 'Wir waren zu Hause geblieben.',
      explanation:
        'bleiben is one of the sein-exception verbs, just like in the present perfect; its past perfect is formed with waren, not haben.',
    },
    {
      id: 'ch55-ex-73',
      chapterNumber: 55,
      order: 73,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'past-perfect', 'present-perfect', 'production'],
      instruction: 'Find the token with the wrong tense, and correct it.',
      prompt: 'Ein Lerner erzählt, was nach dem Essen geschah. Etwas stimmt nicht.',
      tokens: ['Nachdem', 'ich', 'gegessen', 'habe,', 'ging', 'ich', 'spazieren.'],
      errorTokenIndex: 3,
      correction: 'Nachdem ich gegessen hatte, ging ich spazieren.',
      explanation:
        'With a simple-past main clause (ging), the earlier event in the nachdem-clause needs the past perfect (hatte), not the present perfect (habe).',
    },
    {
      id: 'ch55-ex-74',
      chapterNumber: 55,
      order: 74,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: [
        'error-correction',
        'word-order',
        'subordinate-clause',
        'production',
      ],
      instruction:
        'Find the token that breaks the subordinate-clause word order, and correct it.',
      prompt: 'Ein Lerner erzählt dieselbe Geschichte noch einmal. Etwas stimmt nicht.',
      tokens: ['Nachdem', 'ich', 'hatte', 'gegessen,', 'ging', 'ich', 'spazieren.'],
      errorTokenIndex: 2,
      correction: 'Nachdem ich gegessen hatte, ging ich spazieren.',
      explanation:
        'In a subordinate clause, the participle comes first and the conjugated auxiliary hatte moves to the very end, not directly after the subject.',
    },
    {
      id: 'ch55-ex-75',
      chapterNumber: 55,
      order: 75,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['error-correction', 'word-order', 'main-clause', 'production'],
      instruction:
        'Find the token that breaks the main-clause word order, and correct it.',
      prompt: 'Ein Lerner erzählt vom Kinobesuch. Etwas stimmt nicht.',
      tokens: ['Bevor', 'ich', 'ankam,', 'der', 'Film', 'hatte', 'schon', 'begonnen.'],
      errorTokenIndex: 3,
      correction: 'Bevor ich ankam, hatte der Film schon begonnen.',
      explanation:
        'The main clause keeps verb-second order even after a subordinate clause: hatte must stand immediately after the comma, before the subject der Film.',
    },
    {
      id: 'ch55-ex-76',
      chapterNumber: 55,
      order: 76,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['connectors', 'past-perfect', 'recognition'],
      instruction: 'Match each connector or form to how it works with the past perfect.',
      prompt: 'Ordne jedem Element die passende Beschreibung zu.',
      pairs: [
        {
          id: 'p1',
          left: 'nachdem',
          right: 'its own clause names the earlier event, in the past perfect',
        },
        {
          id: 'p2',
          left: 'bevor',
          right: 'its own clause names the later event, in the simple past',
        },
        {
          id: 'p3',
          left: 'als',
          right: 'introduces one single reference moment in the simple past',
        },
        {
          id: 'p4',
          left: 'hatte/war + participle',
          right: 'the two building blocks of the past perfect itself',
        },
      ],
      explanation:
        'nachdem and bevor point at different clauses for the earlier event, while als always names the reference moment; the past perfect itself is always built from hatte/war plus a past participle.',
    },
  ],
};
