import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter049: ChapterDefinition = {
  id: 'chapter-049',
  number: 49,
  slug: 'rules-for-grammatical-gender',
  title: 'Rules for Grammatical Gender',
  germanTitle: 'Regeln für das grammatische Geschlecht',
  level: 'A2',
  section: 'words-and-word-formation',
  objective:
    'Predict the grammatical gender of German nouns using natural gender, semantic groups (days, months, seasons, weather, metals), and reliable noun-forming suffixes (-er, -ling, -ismus; -ung, -heit, -keit, -schaft, -ion, -tät, -in; -chen, -lein, -ment), while recognizing well-known exceptions and building a personal memorization strategy.',
  prerequisites: [14, 15],
  estimatedMinutes: 30,
  tags: ['gender', 'noun-gender', 'suffixes', 'der-die-das', 'semantic-groups', 'diminutives', 'exceptions'],
  explanation: {
    introduction: [
      'Every German noun has one of three grammatical genders — masculine (der), feminine (die), or neuter (das) — and that gender determines the article, adjective endings, and pronouns that go with it. Unlike plural formation, gender cannot be looked up from a single master rule, but it is far from random: a large share of German nouns belong to predictable groups, either because of what they mean (semantic groups) or because of how they are built (noun-forming suffixes).',
      'This chapter collects the most useful of these patterns: natural gender for people and animals, semantic groups such as days, months, seasons, and metals, and a set of suffixes that mark masculine, feminine, or neuter gender almost without exception. It also looks at the handful of very common nouns that break these patterns — because those exceptions are exactly the words worth memorizing individually — and closes with practical strategies for storing gender in memory alongside each new noun.',
    ],
    rules: [
      {
        id: 'ch49-rule-01',
        heading: 'Natural gender for people and animals',
        paragraphs: [
          'For nouns referring to people and many animals, grammatical gender usually matches natural sex: der Mann, der Vater, and der Sohn are masculine; die Frau, die Mutter, and die Tochter are feminine. This is the most intuitive part of the gender system, and it works reliably for the great majority of family members, professions, and animal names that have distinct male and female forms (der Löwe / die Löwin).',
          'Female occupational and animal nouns are very often derived from the masculine form with the suffix -in: der Lehrer → die Lehrerin, der Löwe → die Löwin, der Student → die Studentin. This -in suffix is one of the most reliable feminine markers in the whole language.',
          'Natural gender breaks down for a handful of very common nouns whose grammatical gender is fixed by their form rather than by sex: das Kind (a child of either sex), das Mädchen (a girl — neuter because of the diminutive suffix -chen), der Mensch (a human being of either sex, always masculine), and die Person (a person of either sex, always feminine). These words behave grammatically like any other noun of their gender, regardless of who they refer to.',
        ],
      },
      {
        id: 'ch49-rule-02',
        heading: 'Semantic groups with a predictable gender',
        paragraphs: [
          'Beyond natural gender, whole categories of nouns share the same grammatical gender almost without exception. Days of the week, months, and seasons are masculine: der Montag, der Dienstag, der Januar, der Mai, der Sommer, der Winter. Most weather phenomena are also masculine: der Regen, der Schnee, der Wind, der Nebel, der Sturm.',
          'Cardinal points and many alcoholic drinks are masculine too: der Norden, der Süden, der Wein, der Sekt. Numbers used as nouns, most trees, and most flowers are typically feminine: die Eins, die Million, die Tanne, die Eiche, die Rose, die Tulpe — though der Ahorn ("maple") is a well-known exception among trees.',
          'Metals and chemical elements are typically neuter: das Gold, das Silber, das Kupfer, das Eisen — though der Stahl ("steel", not a pure element) is a notable masculine exception. Letters of the alphabet and colors used as nouns are also neuter: das A, das Rot, das Blau.',
          'These semantic groups are a useful first guess whenever you meet a new noun that belongs to one of these categories, but — as with the suffix rules below — a handful of well-known exceptions exist in each group, so it is still worth confirming gender in a dictionary.',
        ],
      },
      {
        id: 'ch49-rule-03',
        heading: 'Suffixes that (almost) always signal masculine',
        paragraphs: [
          'Certain noun-forming suffixes are strong, reliable predictors of masculine gender. The agent suffix -er, which turns a verb stem into "someone or something that does X", is masculine: lehren → der Lehrer, fahren → der Fahrer, backen → der Bäcker. The same -er suffix also forms many nationality and instrument nouns: der Amerikaner, der Computer.',
          'The suffix -ling forms masculine nouns from adjectives or verb stems, often naming a person or a stage of development: der Frühling ("spring"), der Schmetterling ("butterfly"), der Lehrling ("apprentice"), der Feigling ("coward").',
          'Loanword suffixes borrowed from Latin and Greek that end in -ismus, -or, and -us are masculine: der Tourismus, der Kapitalismus, der Motor, der Doktor, der Kurs. These suffixes are especially common in international and technical vocabulary, which makes them easy to recognize even without knowing the word.',
        ],
      },
      {
        id: 'ch49-rule-04',
        heading: 'Suffixes that (almost) always signal feminine',
        paragraphs: [
          'A larger and even more reliable group of suffixes marks feminine gender. Nouns ending in -ung (from verbs: die Zeitung, die Wohnung, die Übung), -heit and -keit (from adjectives: die Freiheit, die Gesundheit, die Möglichkeit), and -schaft (die Freundschaft, die Mannschaft, die Wissenschaft) are feminine essentially without exception.',
          'Loanword suffixes -ion, -tät, -ur, and -enz are also feminine: die Nation, die Situation, die Universität, die Realität, die Kultur, die Konsequenz. Because these suffixes are shared with English (-tion, -ty, -ure, -ence), they are usually easy to recognize and remember.',
          'The suffix -in, discussed above for people and animals, is likewise always feminine: die Lehrerin, die Ärztin, die Freundin. As a much softer tendency, nouns ending in an unstressed -e are frequently — but by no means always — feminine (die Blume, die Lampe, die Katze); der Junge ("boy") is the most commonly cited exception to this weaker pattern.',
        ],
      },
      {
        id: 'ch49-rule-05',
        heading: 'Suffixes that (almost) always signal neuter',
        paragraphs: [
          'Diminutive suffixes give the strongest gender rule in German: any noun ending in -chen or -lein is neuter, no matter what gender the base word had and no matter what the noun refers to. Das Haus (neuter) gives das Häuschen; der Tisch (masculine) gives das Tischchen; die Frau (feminine) gives das Fräulein; and even a word for a female person becomes neuter once -chen is added: die Magd → das Mädchen.',
          'The Latin/French loanword suffix -ment is neuter: das Dokument, das Instrument, das Element. Nouns formed by prefixing Ge- to a verb or noun stem, often naming a collection or a repeated activity, are typically neuter: das Gebirge ("mountain range", from der Berg), das Gebäude, das Geschenk, das Gerede.',
          'Infinitives used as nouns are always neuter, and this is one of the most productive noun-forming patterns in the language: essen → das Essen, leben → das Leben, rauchen → das Rauchen. Because any verb can be turned into a neuter noun this way, this pattern is worth learning as a rule rather than case by case.',
        ],
      },
      {
        id: 'ch49-rule-06',
        heading: 'Exceptions and how to memorize gender',
        paragraphs: [
          'No rule above is completely exception-free, and a few high-frequency nouns are famous for breaking them: das Mädchen looks like it should be feminine (it means "girl") but is neuter because of -chen; der Junge ("boy") looks like it should follow the weak "-e = feminine" pattern but is masculine; das Auto is neuter even though der Wagen ("car") is masculine. These specific words are worth memorizing individually, precisely because they are exceptions.',
          'The single most effective memorization strategy is to never learn a noun without its article: store "die Zeitung", not "Zeitung", in your vocabulary list from the very first time you meet the word. Many learners use color-coding (for example, blue for der, red for die, green for das) in their notes or flashcards to reinforce the article as part of the word\'s identity.',
          'When a new noun matches one of the suffix or semantic-group rules above, use that rule as a fast first guess — it will be right the overwhelming majority of the time. When it does not match any rule, or when you already know it is an exception, add it to a short personal "exception list" and review that list regularly; a handful of repeated exceptions is far easier to memorize than trying to find a pattern that does not exist.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch49-table-01',
        title: 'Masculine: suffixes and semantic groups',
        columns: ['Suffix / group', 'Example', 'English'],
        rows: [
          ['-er (agent nouns)', 'der Lehrer', 'the teacher'],
          ['-ling', 'der Frühling', 'the spring'],
          ['-ismus / -or / -us', 'der Tourismus, der Motor', 'tourism, the motor'],
          ['days, months, seasons', 'der Montag, der Mai, der Sommer', 'Monday, May, summer'],
          ['weather phenomena', 'der Regen, der Wind', 'rain, wind'],
        ],
      },
      {
        id: 'ch49-table-02',
        title: 'Feminine: suffixes and semantic groups',
        columns: ['Suffix / group', 'Example', 'English'],
        rows: [
          ['-ung', 'die Zeitung', 'the newspaper'],
          ['-heit / -keit', 'die Freiheit, die Möglichkeit', 'freedom, possibility'],
          ['-schaft', 'die Freundschaft', 'friendship'],
          ['-ion / -tät', 'die Nation, die Universität', 'the nation, the university'],
          ['-in (female persons/animals)', 'die Lehrerin', 'the (female) teacher'],
        ],
      },
      {
        id: 'ch49-table-03',
        title: 'Neuter: suffixes and semantic groups',
        columns: ['Suffix / group', 'Example', 'English'],
        rows: [
          ['-chen / -lein (diminutives)', 'das Mädchen, das Fräulein', 'the girl, the young lady'],
          ['-ment', 'das Dokument', 'the document'],
          ['Ge- nouns', 'das Gebirge', 'the mountain range'],
          ['infinitives used as nouns', 'das Essen, das Leben', 'eating/food, life'],
          ['metals & elements', 'das Gold, das Eisen', 'gold, iron'],
        ],
      },
      {
        id: 'ch49-table-04',
        title: 'Notable exceptions to the rules above',
        columns: ['Noun', 'What the rule would predict', 'Actual gender', 'Reason'],
        rows: [
          ['Mädchen (girl)', 'feminine (refers to a female)', 'das Mädchen', 'the diminutive suffix -chen always makes a noun neuter'],
          ['Junge (boy)', 'feminine (ends in unstressed -e)', 'der Junge', 'natural gender (male) overrides the weak -e tendency'],
          ['Auto (car)', 'masculine (like its synonym der Wagen)', 'das Auto', 'gender must be learned per noun, not per synonym'],
          ['Stahl (steel)', 'neuter (like other metals)', 'der Stahl', 'not a pure chemical element, so it does not follow the neuter-metal pattern'],
        ],
        note: 'These four nouns are among the most frequently confused in the whole language — memorize them individually rather than trying to force them into a rule.',
      },
    ],
    examples: [
      {
        german: 'der Lehrer',
        english: 'the teacher',
        highlight: ['der Lehrer'],
        explanation: 'Agent noun with -er: masculine.',
      },
      {
        german: 'der Frühling',
        english: 'spring',
        highlight: ['der Frühling'],
        explanation: 'The -ling suffix is masculine.',
      },
      {
        german: 'der Tourismus',
        english: 'tourism',
        highlight: ['der Tourismus'],
        explanation: 'The -ismus suffix is masculine.',
      },
      {
        german: 'der Montag',
        english: 'Monday',
        highlight: ['der Montag'],
        explanation: 'Days of the week are masculine as a semantic group.',
      },
      {
        german: 'der Regen',
        english: 'the rain',
        highlight: ['der Regen'],
        explanation: 'Weather phenomena are typically masculine.',
      },
      {
        german: 'die Zeitung',
        english: 'the newspaper',
        highlight: ['die Zeitung'],
        explanation: 'The -ung suffix is feminine.',
      },
      {
        german: 'die Freiheit',
        english: 'freedom',
        highlight: ['die Freiheit'],
        explanation: 'The -heit suffix is feminine.',
      },
      {
        german: 'die Freundschaft',
        english: 'friendship',
        highlight: ['die Freundschaft'],
        explanation: 'The -schaft suffix is feminine.',
      },
      {
        german: 'die Universität',
        english: 'the university',
        highlight: ['die Universität'],
        explanation: 'The -tät suffix is feminine.',
      },
      {
        german: 'die Lehrerin',
        english: 'the (female) teacher',
        highlight: ['die Lehrerin'],
        explanation: 'The -in suffix marks a female person and is always feminine.',
      },
      {
        german: 'das Mädchen',
        english: 'the girl',
        highlight: ['das Mädchen'],
        explanation: 'The diminutive suffix -chen always makes a noun neuter, even though the noun refers to a female.',
      },
      {
        german: 'das Fräulein',
        english: 'the young lady',
        highlight: ['das Fräulein'],
        explanation: 'The diminutive suffix -lein always makes a noun neuter.',
      },
      {
        german: 'das Dokument',
        english: 'the document',
        highlight: ['das Dokument'],
        explanation: 'The -ment suffix is neuter.',
      },
      {
        german: 'das Gebirge',
        english: 'the mountain range',
        highlight: ['das Gebirge'],
        explanation: 'A Ge- noun formed from der Berg: neuter.',
      },
      {
        german: 'das Leben',
        english: 'life',
        highlight: ['das Leben'],
        explanation: 'An infinitive used as a noun is always neuter.',
      },
      {
        german: 'der Junge',
        english: 'the boy',
        highlight: ['der Junge'],
        explanation: 'Natural gender (male) overrides the weak tendency for nouns ending in -e to be feminine.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'die Mädchen',
        correct: 'das Mädchen',
        explanation:
          'Even though Mädchen refers to a girl, the diminutive suffix -chen always makes the noun neuter, so the article is das, not die.',
      },
      {
        incorrect: 'die Junge',
        correct: 'der Junge',
        explanation:
          'Junge ends in unstressed -e like many feminine nouns, but because it refers to a male person, natural gender wins and the noun is masculine.',
      },
      {
        incorrect: 'der Zeitung',
        correct: 'die Zeitung',
        explanation: 'Nouns ending in -ung are (almost) always feminine, so the article must be die.',
      },
      {
        incorrect: 'das Freiheit',
        correct: 'die Freiheit',
        explanation: 'Nouns ending in -heit are always feminine, so the article must be die, not das.',
      },
      {
        incorrect: 'der Tischchen',
        correct: 'das Tischchen',
        explanation:
          'Adding the diminutive suffix -chen always makes a noun neuter, even though Tisch itself is masculine (der Tisch).',
      },
      {
        incorrect: 'die Tourismus',
        correct: 'der Tourismus',
        explanation: 'Nouns ending in -ismus are always masculine, so the article must be der, not die.',
      },
    ],
    remember: [
      'Suffixes are the most reliable gender clue: -chen/-lein/-ment are always neuter; -ung/-heit/-keit/-schaft/-ion/-tät/-in are always feminine; -er (agent nouns), -ling, and -ismus are (almost) always masculine.',
      'Diminutive endings -chen and -lein always make a noun neuter, regardless of the base noun\'s own gender or the natural sex of the person it refers to (das Mädchen, das Fräulein).',
      'Days of the week, months, seasons, and most weather terms are masculine (der Montag, der Mai, der Winter, der Regen); metals and chemical elements are typically neuter (das Gold, das Eisen).',
      'Learn every new noun together with its article, and keep a written list of the exceptions that break the suffix and semantic-group rules (der Junge, das Mädchen, das Auto).',
      'No rule in this chapter is 100% exception-free — when in doubt, check a dictionary rather than guessing from the ending or meaning alone.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 30,
    requiredCorrectTextInputs: 4,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch49-ex-01',
      chapterNumber: 49,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['suffix-ung', 'feminine-suffix'],
      instruction: 'Choose the gender that this suffix almost always signals.',
      prompt: 'Welches Geschlecht hat die Endung -ung (z. B. die Zeitung, die Wohnung)?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'b',
      explanation: 'Nouns ending in -ung are almost always feminine: die Zeitung, die Wohnung, die Übung.',
    },
    {
      id: 'ch49-ex-02',
      chapterNumber: 49,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['suffix-heit-keit', 'feminine-suffix'],
      instruction: 'Choose the gender that this suffix almost always signals.',
      prompt: 'Welches Geschlecht haben Nomen mit den Endungen -heit und -keit (z. B. die Freiheit, die Möglichkeit)?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'b',
      explanation: '-heit and -keit are adjective-to-noun suffixes that are always feminine.',
    },
    {
      id: 'ch49-ex-03',
      chapterNumber: 49,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['diminutive', 'neuter-suffix'],
      instruction: 'Choose the gender that this suffix always signals.',
      prompt: 'Welches Geschlecht haben Diminutive mit -chen oder -lein IMMER — unabhängig vom Geschlecht des Grundworts?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'c',
      explanation:
        'The diminutive suffixes -chen and -lein always make a noun neuter, no matter what gender the base word had.',
    },
    {
      id: 'ch49-ex-04',
      chapterNumber: 49,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['suffix-ismus', 'masculine-suffix'],
      instruction: 'Choose the gender that this suffix almost always signals.',
      prompt: 'Welches Geschlecht hat die Endung -ismus (z. B. der Tourismus, der Kapitalismus)?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'a',
      explanation: 'Loanword nouns ending in -ismus are masculine.',
    },
    {
      id: 'ch49-ex-05',
      chapterNumber: 49,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['suffix-schaft', 'feminine-suffix'],
      instruction: 'Choose the gender that this suffix almost always signals.',
      prompt: 'Welches Geschlecht hat die Endung -schaft (z. B. die Freundschaft, die Mannschaft)?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'b',
      explanation: '-schaft is a feminine noun-forming suffix.',
    },
    {
      id: 'ch49-ex-06',
      chapterNumber: 49,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['suffix-ion', 'feminine-suffix'],
      instruction: 'Choose the gender that this suffix almost always signals.',
      prompt: 'Welches Geschlecht hat die Endung -ion (z. B. die Nation, die Situation)?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'b',
      explanation: 'Loanwords ending in -ion are feminine.',
    },
    {
      id: 'ch49-ex-07',
      chapterNumber: 49,
      order: 7,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['suffix-tät', 'feminine-suffix'],
      instruction: 'Choose the gender that this suffix almost always signals.',
      prompt: 'Welches Geschlecht hat die Endung -tät (z. B. die Universität, die Realität)?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'b',
      explanation: '-tät corresponds to English -ty and is always feminine.',
    },
    {
      id: 'ch49-ex-08',
      chapterNumber: 49,
      order: 8,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['suffix-ling', 'masculine-suffix'],
      instruction: 'Choose the gender that this suffix almost always signals.',
      prompt: 'Welches Geschlecht hat die Endung -ling (z. B. der Frühling, der Schmetterling)?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'a',
      explanation: '-ling is a masculine noun-forming suffix.',
    },
    {
      id: 'ch49-ex-09',
      chapterNumber: 49,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['suffix-in', 'feminine-suffix'],
      instruction: 'Choose the gender that this suffix always signals.',
      prompt: '"der Lehrer" + die Endung -in ergibt "die Lehrerin". Welches Geschlecht hat -in immer?',
      options: [
        { id: 'a', text: 'maskulin (der)' },
        { id: 'b', text: 'feminin (die)' },
        { id: 'c', text: 'neutrum (das)' },
      ],
      correctOptionId: 'b',
      explanation:
        'The suffix -in forms the feminine counterpart of a masculine person or animal noun and is always feminine.',
    },
    {
      id: 'ch49-ex-10',
      chapterNumber: 49,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['semantic-group', 'days-months-seasons'],
      instruction: 'Choose the article that fits this whole semantic group.',
      prompt: 'Welcher Artikel passt zu Wochentagen, Monaten und Jahreszeiten (___ Montag, ___ Januar, ___ Sommer)?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
      ],
      correctOptionId: 'a',
      explanation: 'Days of the week, months, and seasons are (almost) always masculine.',
    },
    {
      id: 'ch49-ex-11',
      chapterNumber: 49,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['semantic-group', 'weather'],
      instruction: 'Choose the article that fits this whole semantic group.',
      prompt: 'Welcher Artikel passt zu Wetterphänomenen (___ Regen, ___ Schnee, ___ Wind)?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
      ],
      correctOptionId: 'a',
      explanation: 'Most weather phenomena are masculine.',
    },
    {
      id: 'ch49-ex-12',
      chapterNumber: 49,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['semantic-group', 'metals'],
      instruction: 'Choose the article that fits this whole semantic group.',
      prompt: 'Welcher Artikel passt zu Metallen und chemischen Elementen (___ Gold, ___ Silber, ___ Eisen)?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
      ],
      correctOptionId: 'c',
      explanation: 'Metals and chemical elements are typically neuter (though der Stahl is a well-known exception).',
    },
    {
      id: 'ch49-ex-13',
      chapterNumber: 49,
      order: 13,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['ge-noun', 'neuter-prefix'],
      instruction: 'Choose the article that fits this word-formation pattern.',
      prompt: 'Welcher Artikel passt zu Ge-Nomen wie "Gebirge" und "Gebäude"?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
      ],
      correctOptionId: 'c',
      explanation: 'Nouns formed by prefixing Ge- to a verb or noun stem are typically neuter.',
    },
    {
      id: 'ch49-ex-14',
      chapterNumber: 49,
      order: 14,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['infinitive-as-noun', 'neuter-suffix'],
      instruction: 'Choose the article that fits this word-formation pattern.',
      prompt: 'Welcher Artikel passt zu einem substantivierten Infinitiv wie "Leben" oder "Essen"?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
      ],
      correctOptionId: 'c',
      explanation: 'An infinitive used as a noun is always neuter: das Leben, das Essen.',
    },
    {
      id: 'ch49-ex-15',
      chapterNumber: 49,
      order: 15,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['exception', 'diminutive', 'natural-gender'],
      instruction: 'This noun is a well-known exception. Choose its correct article.',
      prompt: 'Welcher Artikel gehört zu "Mädchen", obwohl es ein weibliches Kind bezeichnet?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
      ],
      correctOptionId: 'c',
      explanation:
        'Even though Mädchen means "girl", the diminutive suffix -chen always overrides natural gender and makes the noun neuter.',
    },
    {
      id: 'ch49-ex-16',
      chapterNumber: 49,
      order: 16,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['exception', 'suffix-e', 'natural-gender'],
      instruction: 'This noun is a well-known exception. Choose its correct article.',
      prompt: 'Welcher Artikel gehört zu "Junge", obwohl das Wort auf unbetontes -e endet (wie viele feminine Nomen)?',
      options: [
        { id: 'a', text: 'der' },
        { id: 'b', text: 'die' },
        { id: 'c', text: 'das' },
      ],
      correctOptionId: 'a',
      explanation:
        'Junge refers to a male person, so natural gender wins over the weak "-e is often feminine" tendency: der Junge.',
    },
    {
      id: 'ch49-ex-17',
      chapterNumber: 49,
      order: 17,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['exception-risk', 'suffix-e'],
      instruction: 'Identify which noun breaks the usual pattern.',
      prompt: 'Welches dieser Nomen widerspricht der Tendenz, dass Wörter auf unbetontes -e meist feminin sind?',
      options: [
        { id: 'a', text: 'die Blume' },
        { id: 'b', text: 'die Lampe' },
        { id: 'c', text: 'der Junge' },
        { id: 'd', text: 'die Katze' },
      ],
      correctOptionId: 'c',
      explanation:
        'Blume, Lampe, and Katze all follow the -e tendency and are feminine; Junge is masculine because it refers to a male person.',
    },
    {
      id: 'ch49-ex-18',
      chapterNumber: 49,
      order: 18,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['sorting', 'diminutive', 'exception-risk'],
      instruction: 'Sort this noun: which one does NOT belong with the neuter diminutives?',
      prompt: 'Welches Nomen passt NICHT in die Gruppe der neutralen Diminutive (-chen/-lein)?',
      options: [
        { id: 'a', text: 'das Mädchen' },
        { id: 'b', text: 'das Häuschen' },
        { id: 'c', text: 'das Bändchen' },
        { id: 'd', text: 'die Zeitung' },
      ],
      correctOptionId: 'd',
      explanation:
        'Mädchen, Häuschen, and Bändchen are all diminutives ending in -chen and are neuter; Zeitung is not a diminutive and is feminine (-ung).',
    },
    {
      id: 'ch49-ex-19',
      chapterNumber: 49,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-ung', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Zeitung → ___',
      acceptedAnswers: ['die', 'die Zeitung'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: 'Zeitung ends in -ung, a suffix that is always feminine: die Zeitung.',
    },
    {
      id: 'ch49-ex-20',
      chapterNumber: 49,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-heit', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Freiheit → ___',
      acceptedAnswers: ['die', 'die Freiheit'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: 'Freiheit ends in -heit, always feminine: die Freiheit.',
    },
    {
      id: 'ch49-ex-21',
      chapterNumber: 49,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-schaft', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Freundschaft → ___',
      acceptedAnswers: ['die', 'die Freundschaft'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: '-schaft is always feminine: die Freundschaft.',
    },
    {
      id: 'ch49-ex-22',
      chapterNumber: 49,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-ion', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Nation → ___',
      acceptedAnswers: ['die', 'die Nation'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: '-ion is always feminine: die Nation.',
    },
    {
      id: 'ch49-ex-23',
      chapterNumber: 49,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-tät', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Universität → ___',
      acceptedAnswers: ['die', 'die Universität'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: '-tät is always feminine: die Universität.',
    },
    {
      id: 'ch49-ex-24',
      chapterNumber: 49,
      order: 24,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-ling', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Frühling → ___',
      acceptedAnswers: ['der', 'der Frühling'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: '-ling is always masculine: der Frühling.',
    },
    {
      id: 'ch49-ex-25',
      chapterNumber: 49,
      order: 25,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-ismus', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Tourismus → ___',
      acceptedAnswers: ['der', 'der Tourismus'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: '-ismus is always masculine: der Tourismus.',
    },
    {
      id: 'ch49-ex-26',
      chapterNumber: 49,
      order: 26,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['suffix-ment', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Dokument → ___',
      acceptedAnswers: ['das', 'das Dokument'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: '-ment is always neuter: das Dokument.',
    },
    {
      id: 'ch49-ex-27',
      chapterNumber: 49,
      order: 27,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['exception', 'diminutive', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Mädchen → ___',
      acceptedAnswers: ['das', 'das Mädchen'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: 'Despite referring to a girl, the diminutive suffix -chen makes Mädchen neuter: das Mädchen.',
    },
    {
      id: 'ch49-ex-28',
      chapterNumber: 49,
      order: 28,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['ge-noun', 'article-choice'],
      instruction: 'Write the correct definite article (der, die, or das) for this noun.',
      prompt: 'Gebirge → ___',
      acceptedAnswers: ['das', 'das Gebirge'],
      answerMode: 'caseInsensitive',
      placeholder: 'der/die/das',
      maxLength: 20,
      explanation: 'Gebirge is a Ge- noun formed from der Berg and is neuter: das Gebirge.',
    },
    {
      id: 'ch49-ex-29',
      chapterNumber: 49,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-writing', 'suffix-heit'],
      instruction: 'Complete the sentence with the correct article. Capitalisation and punctuation are checked.',
      prompt: '___ Freiheit ist ein hohes Gut.',
      acceptedAnswers: ['Die Freiheit ist ein hohes Gut.'],
      answerMode: 'normalized',
      placeholder: 'Die ...',
      maxLength: 40,
      explanation: 'Freiheit ends in -heit, always feminine, so the sentence begins with Die Freiheit ist ein hohes Gut.',
    },
    {
      id: 'ch49-ex-30',
      chapterNumber: 49,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sentence-writing', 'suffix-schaft'],
      instruction:
        'Write a complete German sentence using the noun given, with its correct article. Capitalisation and punctuation are checked.',
      prompt: 'Write: "The friendship is important." (die Freundschaft – wichtig)',
      acceptedAnswers: ['Die Freundschaft ist wichtig.'],
      answerMode: 'normalized',
      placeholder: 'Die ...',
      maxLength: 40,
      explanation: '-schaft is always feminine: Die Freundschaft ist wichtig.',
    },
  ],
};
