import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter016: ChapterDefinition = {
  id: 'chapter-016',
  number: 16,
  slug: 'negation-with-nicht-and-kein',
  title: 'Negation with nicht and kein',
  germanTitle: 'Verneinung mit nicht und kein',
  level: 'A1',
  section: 'pronouns-nouns-articles',
  objective:
    'Choose correctly between nicht and kein to negate a German sentence, decline kein in the nominative and accusative, and place nicht in the right position depending on what it negates.',
  prerequisites: [15],
  estimatedMinutes: 25,
  tags: ['negation', 'nicht', 'kein', 'kein-declension', 'word-order'],
  explanation: {
    introduction: [
      'German has two main words for "not": nicht and kein. They are not interchangeable — which one you need depends on what you are negating. Nouns that would take the indefinite article (ein, eine) or no article at all are negated with kein. Everything else — verbs, adjectives, adverbs, names, and nouns that already have a definite article or a possessive — is negated with nicht.',
      'This chapter shows you how to choose between nicht and kein, how kein changes its ending depending on the gender and case of the noun (just like ein does), and where nicht goes in the sentence depending on whether it negates the whole sentence or just one specific part of it.',
    ],
    rules: [
      {
        id: 'ch16-rule-01',
        heading: 'kein negates a noun without a definite article',
        paragraphs: [
          'Use kein when the noun you are negating would otherwise take the indefinite article ein/eine, or no article at all: Ich habe ein Auto. → Ich habe kein Auto. Ich trinke Kaffee. → Ich trinke keinen Kaffee.',
          'kein simply takes the place of ein — you never use both together. It also negates plural nouns and nouns with no article in the singular (mass nouns like Zeit, Geld, Milch).',
        ],
        notes: [
          'Ich habe kein Auto. (a car, no article word without kein)',
          'Ich habe keine Zeit. (Zeit normally has no article at all)',
        ],
      },
      {
        id: 'ch16-rule-02',
        heading: 'nicht negates verbs, adjectives, adverbs, names, and definite nouns',
        paragraphs: [
          'Use nicht to negate a verb: Ich komme nicht.',
          'Use nicht to negate an adjective or an adverb: Das Auto ist nicht neu. Er singt nicht gut.',
          'Use nicht to negate a proper name: Ich kenne Anna nicht.',
          'Use nicht to negate a noun that already has a definite article (der/die/das) or a possessive (mein, dein, sein …), because kein cannot combine with those: Ich mag das Auto nicht. Das ist nicht mein Buch.',
        ],
      },
      {
        id: 'ch16-rule-03',
        heading: 'Declining kein: nominative and accusative',
        paragraphs: [
          'kein takes exactly the same endings as ein, so it changes according to the gender, number, and case of the noun it belongs to.',
          'In the nominative, kein stays unchanged before masculine and neuter nouns (kein) and adds -e before feminine nouns (keine).',
          'In the accusative, masculine nouns need keinen, feminine and neuter nouns stay the same as in the nominative (keine, kein).',
          'Unlike ein, kein also has a plural form: keine, used for all genders in both the nominative and accusative plural.',
        ],
      },
      {
        id: 'ch16-rule-04',
        heading: 'Where does nicht go?',
        paragraphs: [
          'When nicht negates the whole sentence (general, "not at all" negation), it usually stands near the end of the clause, after the verb, objects, and most other elements: Ich verstehe das nicht. Er kommt heute nicht.',
          'When nicht negates only one specific word or phrase (narrow negation), it stands directly in front of that word or phrase, not at the end: Er kommt nicht mit dem Auto, sondern mit dem Bus. Nicht Maria kommt heute, sondern Paul.',
          'This difference in placement changes the meaning: Maria kommt heute nicht (she is not coming at all today) is different from Nicht Maria kommt heute (someone else is coming today, not Maria).',
        ],
        notes: [
          'A narrow negation with nicht is often followed by a correction introduced with sondern (but rather).',
        ],
      },
    ],
    tables: [
      {
        id: 'ch16-table-01',
        title: 'kein in the nominative and accusative',
        columns: ['Gender/Number', 'Example noun', 'Nominative', 'Accusative'],
        rows: [
          ['masculine', 'der Hund', 'kein Hund', 'keinen Hund'],
          ['feminine', 'die Zeit', 'keine Zeit', 'keine Zeit'],
          ['neuter', 'das Auto', 'kein Auto', 'kein Auto'],
          ['plural (all genders)', 'die Kinder', 'keine Kinder', 'keine Kinder'],
        ],
        note: 'kein follows exactly the same pattern as ein, plus a plural form keine that ein does not have.',
      },
    ],
    examples: [
      {
        german: 'Ich verstehe das nicht.',
        english: 'I don’t understand that.',
        highlight: ['nicht'],
        explanation: 'nicht negates the verb verstehe — a general, whole-sentence negation.',
      },
      {
        german: 'Der Kaffee ist nicht heiß.',
        english: 'The coffee is not hot.',
        highlight: ['nicht heiß'],
        explanation: 'nicht negates the adjective heiß.',
      },
      {
        german: 'Er trinkt keine Milch.',
        english: 'He doesn’t drink milk.',
        highlight: ['keine Milch'],
        explanation: 'Milch has no article, so it is negated with kein, not nicht.',
      },
      {
        german: 'Ich kenne Tom nicht.',
        english: 'I don’t know Tom.',
        highlight: ['nicht'],
        explanation: 'Proper names are always negated with nicht, never kein.',
      },
      {
        german: 'Ich mag den Film nicht.',
        english: 'I don’t like the film.',
        highlight: ['den Film nicht'],
        explanation: 'den Film already has a definite article, so kein cannot be used here — only nicht.',
      },
      {
        german: 'Das ist nicht mein Fahrrad.',
        english: 'That is not my bicycle.',
        highlight: ['nicht mein Fahrrad'],
        explanation: 'kein cannot combine with a possessive like mein, so nicht is used instead.',
      },
      {
        german: 'Ich habe keinen Hund.',
        english: 'I don’t have a dog.',
        highlight: ['keinen Hund'],
        explanation: 'Hund is masculine and in the accusative, so kein becomes keinen.',
      },
      {
        german: 'Sie trinkt keinen Kaffee.',
        english: 'She doesn’t drink coffee.',
        highlight: ['keinen Kaffee'],
        explanation: 'Kaffee is masculine and stands in the accusative, so kein becomes keinen.',
      },
      {
        german: 'Wir haben heute keine Zeit.',
        english: 'We don’t have time today.',
        highlight: ['keine Zeit'],
        explanation: 'Zeit is feminine, so kein becomes keine both in the nominative and the accusative.',
      },
      {
        german: 'Er kommt nicht mit dem Auto, sondern mit dem Bus.',
        english: 'He is not coming by car, but by bus.',
        highlight: ['nicht mit dem Auto'],
        explanation: 'nicht stands directly before the phrase it negates (mit dem Auto), not at the end of the sentence, because only that part is being denied and corrected with sondern.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich habe nicht ein Auto.',
        correct: 'Ich habe kein Auto.',
        explanation: 'A noun with the indefinite article ein is negated by replacing ein with kein, not by adding nicht in front of it.',
      },
      {
        incorrect: 'Ich habe ein keinen Bruder.',
        correct: 'Ich habe keinen Bruder.',
        explanation: 'kein already takes the place of the indefinite article — ein and kein are never used together.',
      },
      {
        incorrect: 'Das ist keine mein Auto.',
        correct: 'Das ist nicht mein Auto.',
        explanation: 'kein cannot combine with a possessive like mein; a noun that already has a possessive determiner is negated with nicht.',
      },
      {
        incorrect: 'Ich kenne nicht Anna.',
        correct: 'Ich kenne Anna nicht.',
        explanation: 'For a whole-sentence negation of a name, nicht follows the object rather than standing directly in front of it.',
      },
    ],
    remember: [
      'kein negates a noun that would otherwise take ein/eine or no article at all.',
      'nicht negates verbs, adjectives, adverbs, proper names, and nouns that already have a definite article or a possessive.',
      'kein declines like ein: kein, keine, kein in the nominative; keinen, keine, kein in the accusative; keine for all plural nouns.',
      'For whole-sentence negation, nicht usually stands near the end of the clause; for narrow negation of one specific word or phrase, nicht stands directly before it.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 57,
    requiredCorrectTextInputs: 19,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch16-ex-01',
      chapterNumber: 16,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'nicht', 'verb'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Ich verstehe das ___.',
      options: [
        { id: 'a', text: 'nicht' },
        { id: 'b', text: 'kein' },
        { id: 'c', text: 'keine' },
        { id: 'd', text: 'keinen' },
      ],
      correctOptionId: 'a',
      explanation: 'nicht negates the verb verstehe, so this is a whole-sentence negation, not a noun negation.',
    },
    {
      id: 'ch16-ex-02',
      chapterNumber: 16,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'nicht', 'adjective'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Der Kaffee ist ___ heiß.',
      options: [
        { id: 'a', text: 'nicht' },
        { id: 'b', text: 'kein' },
        { id: 'c', text: 'keine' },
        { id: 'd', text: 'keinen' },
      ],
      correctOptionId: 'a',
      explanation: 'heiß is an adjective, and adjectives are negated with nicht, never kein.',
    },
    {
      id: 'ch16-ex-03',
      chapterNumber: 16,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'kein', 'no-article-noun'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Er trinkt ___ Milch.',
      options: [
        { id: 'a', text: 'keine' },
        { id: 'b', text: 'nicht' },
        { id: 'c', text: 'kein' },
        { id: 'd', text: 'keinen' },
      ],
      correctOptionId: 'a',
      explanation: 'Milch has no article at all in the affirmative sentence, so it is negated with kein; Milch is feminine, so kein becomes keine.',
    },
    {
      id: 'ch16-ex-04',
      chapterNumber: 16,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'nicht', 'proper-noun'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Ich kenne ___ Tom.',
      options: [
        { id: 'a', text: 'nicht' },
        { id: 'b', text: 'kein' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keine' },
      ],
      correctOptionId: 'a',
      explanation: 'Tom is a proper name. Names are always negated with nicht, never kein.',
    },
    {
      id: 'ch16-ex-05',
      chapterNumber: 16,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'nicht', 'definite-article'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Ich mag ___ den Film.',
      options: [
        { id: 'a', text: 'nicht' },
        { id: 'b', text: 'kein' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keine' },
      ],
      correctOptionId: 'a',
      explanation: 'den Film already has the definite article der, and kein can never combine with a definite article — only nicht works here.',
    },
    {
      id: 'ch16-ex-06',
      chapterNumber: 16,
      order: 6,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'nicht', 'possessive'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Das ist ___ mein Fahrrad.',
      options: [
        { id: 'a', text: 'nicht' },
        { id: 'b', text: 'kein' },
        { id: 'c', text: 'keine' },
        { id: 'd', text: 'keinen' },
      ],
      correctOptionId: 'a',
      explanation: 'mein is a possessive determiner, and kein cannot combine with a possessive, so nicht is used instead.',
    },
    {
      id: 'ch16-ex-07',
      chapterNumber: 16,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'masculine'],
      instruction: 'Choose the correct form of kein.',
      prompt: 'Ich habe ___ Bruder.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'keine' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keinem' },
      ],
      correctOptionId: 'c',
      explanation: 'Bruder is masculine and is the accusative object of habe, so kein takes the accusative masculine ending: keinen.',
    },
    {
      id: 'ch16-ex-08',
      chapterNumber: 16,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'feminine'],
      instruction: 'Choose the correct form of kein.',
      prompt: 'Sie hat ___ Schwester.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'keine' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keinem' },
      ],
      correctOptionId: 'b',
      explanation: 'Schwester is feminine, and feminine nouns take keine in both the nominative and the accusative.',
    },
    {
      id: 'ch16-ex-09',
      chapterNumber: 16,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'nominative', 'masculine'],
      instruction: 'Choose the correct form of kein.',
      prompt: 'Das ist ___ Fehler.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'keine' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keinem' },
      ],
      correctOptionId: 'a',
      explanation: 'Fehler (der Fehler) is masculine and stands in the nominative here, so kein keeps its unchanged base form.',
    },
    {
      id: 'ch16-ex-10',
      chapterNumber: 16,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'neuter'],
      instruction: 'Choose the correct form of kein.',
      prompt: 'Wir haben ___ Auto.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'keine' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keinem' },
      ],
      correctOptionId: 'a',
      explanation: 'Auto is neuter, and neuter nouns keep the unchanged form kein in both the nominative and the accusative.',
    },
    {
      id: 'ch16-ex-11',
      chapterNumber: 16,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['negation', 'nicht', 'placement', 'narrow-negation'],
      instruction: 'Read the sentence and decide which part nicht negates.',
      prompt: 'Er kommt nicht mit dem Auto, sondern mit dem Bus. — What does nicht negate here?',
      options: [
        { id: 'a', text: 'mit dem Auto' },
        { id: 'b', text: 'kommt' },
        { id: 'c', text: 'Er' },
        { id: 'd', text: 'mit dem Bus' },
      ],
      correctOptionId: 'a',
      explanation: 'nicht stands directly before mit dem Auto and is corrected by sondern mit dem Bus, so it negates only that phrase, not the whole sentence.',
    },
    {
      id: 'ch16-ex-12',
      chapterNumber: 16,
      order: 12,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['negation', 'nicht', 'placement', 'whole-sentence-negation'],
      instruction: 'Choose the sentence in which nicht negates the whole sentence rather than just one part.',
      prompt: 'Which sentence means that she simply is not singing at all today?',
      options: [
        { id: 'a', text: 'Sie singt nicht gut.' },
        { id: 'b', text: 'Sie singt heute nicht.' },
        { id: 'c', text: 'Nicht sie singt, sondern er.' },
        { id: 'd', text: 'Sie singt nicht heute, sondern morgen.' },
      ],
      correctOptionId: 'b',
      explanation: 'In Sie singt heute nicht, nicht stands at the end of the clause and negates the whole action, not just one word — she is not singing at all today.',
    },
    {
      id: 'ch16-ex-13',
      chapterNumber: 16,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'masculine'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Ich trinke ___ Kaffee.',
      acceptedAnswers: ['keinen'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein-form',
      maxLength: 12,
      explanation: 'Kaffee is masculine and is the accusative object of trinke, so kein becomes keinen.',
    },
    {
      id: 'ch16-ex-14',
      chapterNumber: 16,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'feminine'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Er hat ___ Idee.',
      acceptedAnswers: ['keine'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein-form',
      maxLength: 12,
      explanation: 'Idee is feminine, so kein takes the feminine ending keine in the accusative.',
    },
    {
      id: 'ch16-ex-15',
      chapterNumber: 16,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'nominative', 'neuter'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Das ist ___ Problem.',
      acceptedAnswers: ['kein'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein-form',
      maxLength: 12,
      explanation: 'Problem is neuter and stands in the nominative, so kein keeps its unchanged base form.',
    },
    {
      id: 'ch16-ex-16',
      chapterNumber: 16,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'plural'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Wir haben ___ Freunde hier.',
      acceptedAnswers: ['keine'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein-form',
      maxLength: 12,
      explanation: 'Freunde is plural, and kein uses keine for all plural nouns regardless of gender.',
    },
    {
      id: 'ch16-ex-17',
      chapterNumber: 16,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['negation', 'kein', 'no-article-noun'],
      instruction: 'Fill in nicht or the correct form of kein. Capitalisation is not checked.',
      prompt: 'Ich habe ___ Geld.',
      acceptedAnswers: ['kein'],
      answerMode: 'caseInsensitive',
      placeholder: 'nicht / kein-form',
      maxLength: 12,
      explanation: 'Geld is a noun with no article, so it is negated with kein; Geld is neuter, so kein keeps its base form.',
    },
    {
      id: 'ch16-ex-18',
      chapterNumber: 16,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['negation', 'nicht', 'adjective'],
      instruction: 'Fill in nicht or the correct form of kein. Capitalisation is not checked.',
      prompt: 'Das Wetter ist heute ___ schön.',
      acceptedAnswers: ['nicht'],
      answerMode: 'caseInsensitive',
      placeholder: 'nicht / kein-form',
      maxLength: 12,
      explanation: 'schön is an adjective, and adjectives are always negated with nicht, not kein.',
    },
    {
      id: 'ch16-ex-19',
      chapterNumber: 16,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['negation', 'kein', 'accusative', 'masculine'],
      instruction: 'Rewrite the sentence in the negative form using kein. Capitalisation and punctuation are checked.',
      prompt: 'Ich habe einen Hund.',
      acceptedAnswers: ['Ich habe keinen Hund.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe ...',
      maxLength: 40,
      explanation: 'The indefinite article einen is replaced by keinen (Hund is masculine, accusative), giving Ich habe keinen Hund.',
    },
    {
      id: 'ch16-ex-20',
      chapterNumber: 16,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['negation', 'kein', 'accusative', 'masculine'],
      instruction: 'Rewrite the sentence in the negative form using kein. Capitalisation and punctuation are checked.',
      prompt: 'Sie trinkt Kaffee.',
      acceptedAnswers: ['Sie trinkt keinen Kaffee.'],
      answerMode: 'normalized',
      placeholder: 'Sie trinkt ...',
      maxLength: 40,
      explanation: 'Kaffee has no article in the affirmative sentence, so it is negated with kein; Kaffee is masculine and accusative, so kein becomes keinen.',
    },
    {
      id: 'ch16-ex-21',
      chapterNumber: 16,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['negation', 'nicht', 'adjective'],
      instruction: 'Rewrite the sentence in the negative form using nicht. Capitalisation and punctuation are checked.',
      prompt: 'Das Auto ist neu.',
      acceptedAnswers: ['Das Auto ist nicht neu.'],
      answerMode: 'normalized',
      placeholder: 'Das Auto ist ...',
      maxLength: 40,
      explanation: 'neu is an adjective, so it is negated with nicht, placed directly before it: Das Auto ist nicht neu.',
    },
    {
      id: 'ch16-ex-22',
      chapterNumber: 16,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['negation', 'nicht', 'definite-article', 'placement'],
      instruction: 'Rewrite the sentence in the negative form using nicht. Capitalisation and punctuation are checked.',
      prompt: 'Ich kenne den Mann.',
      acceptedAnswers: ['Ich kenne den Mann nicht.'],
      answerMode: 'normalized',
      placeholder: 'Ich kenne ...',
      maxLength: 40,
      explanation: 'den Mann already has a definite article, so kein cannot be used; nicht negates the whole sentence and stands at the end, after the object: Ich kenne den Mann nicht.',
    },
    {
      id: 'ch16-ex-23',
      chapterNumber: 16,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['negation', 'nicht', 'placement', 'narrow-negation'],
      instruction:
        'Write a sentence saying that he does not want the red car (implying he wants a different one), using the cue words and placing nicht directly before the phrase it negates. Capitalisation and punctuation are checked.',
      prompt: 'er – wollen – das rote Auto',
      acceptedAnswers: ['Er will nicht das rote Auto.'],
      answerMode: 'normalized',
      placeholder: 'Er will ...',
      maxLength: 45,
      explanation: 'To negate only das rote Auto (not the wanting itself), nicht stands directly before that phrase: Er will nicht das rote Auto.',
    },
    {
      id: 'ch16-ex-24',
      chapterNumber: 16,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['negation', 'kein', 'accusative', 'feminine'],
      instruction:
        'Write a complete negative sentence using the cue words and the correct form of kein. Capitalisation and punctuation are checked.',
      prompt: 'wir – heute – Zeit – haben',
      acceptedAnswers: ['Wir haben heute keine Zeit.'],
      answerMode: 'normalized',
      placeholder: 'Wir haben ...',
      maxLength: 45,
      explanation: 'Zeit has no article and is feminine, so it is negated with keine: Wir haben heute keine Zeit.',
    },
    {
      id: 'ch16-ex-25',
      chapterNumber: 16,
      order: 25,
      type: 'errorSpotting',
      level: 'recognition',
      grammarFocus: ['negation', 'kein', 'no-article-noun', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Ein Student beschreibt, was er besitzt. Etwas stimmt nicht.',
      tokens: ['Ich', 'habe', 'nicht', 'Auto.'],
      errorTokenIndex: 2,
      correction: 'kein',
      explanation: 'Auto has no article in the affirmative sentence, so it must be negated with kein (kein Auto), not nicht.',
    },
    {
      id: 'ch16-ex-26',
      chapterNumber: 16,
      order: 26,
      type: 'errorSpotting',
      level: 'recognition',
      grammarFocus: ['negation', 'kein-declension', 'accusative', 'masculine', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt seine Trinkgewohnheiten. Etwas stimmt nicht.',
      tokens: ['Er', 'trinkt', 'nicht', 'Kaffee.'],
      errorTokenIndex: 2,
      correction: 'keinen',
      explanation: 'Kaffee has no article, so it needs kein rather than nicht; Kaffee is masculine and accusative here, so kein becomes keinen.',
    },
    {
      id: 'ch16-ex-27',
      chapterNumber: 16,
      order: 27,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'feminine', 'error-correction'],
      instruction: 'Find the token with the wrong ending, and correct it.',
      prompt: 'Zwei Kollegen sprechen über ihren Terminkalender. Etwas stimmt nicht.',
      tokens: ['Wir', 'haben', 'kein', 'Zeit.'],
      errorTokenIndex: 2,
      correction: 'keine',
      explanation: 'Zeit is feminine, so kein must take the feminine ending keine, not the unchanged base form kein.',
    },
    {
      id: 'ch16-ex-28',
      chapterNumber: 16,
      order: 28,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['negation', 'nicht', 'proper-noun', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand sagt, dass er eine Person nicht kennt. Etwas stimmt nicht.',
      tokens: ['Ich', 'kenne', 'kein', 'Anna.'],
      errorTokenIndex: 2,
      correction: 'nicht',
      explanation: 'Anna is a proper name, and proper names are always negated with nicht — kein can never combine with a name.',
    },
    {
      id: 'ch16-ex-29',
      chapterNumber: 16,
      order: 29,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['negation', 'nicht', 'possessive', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand widerspricht, wem ein Gegenstand gehört. Etwas stimmt nicht.',
      tokens: ['Das', 'ist', 'kein', 'mein', 'Auto.'],
      errorTokenIndex: 2,
      correction: 'nicht',
      explanation: 'mein is a possessive, and kein can never combine with a possessive determiner — nicht is required instead.',
    },
    {
      id: 'ch16-ex-30',
      chapterNumber: 16,
      order: 30,
      type: 'errorSpotting',
      level: 'controlled',
      grammarFocus: ['negation', 'nicht', 'definite-article', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand sagt, dass ihm ein bestimmter Film nicht gefällt. Etwas stimmt nicht.',
      tokens: ['Ich', 'mag', 'kein', 'den', 'Film.'],
      errorTokenIndex: 2,
      correction: 'nicht',
      explanation: 'den Film already has a definite article, so kein cannot be used — only nicht is possible before a noun with der/die/das.',
    },
    {
      id: 'ch16-ex-31',
      chapterNumber: 16,
      order: 31,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['kein-declension', 'accusative', 'masculine', 'error-correction'],
      instruction: 'Find the token with the wrong ending, and correct it.',
      prompt: 'Jemand spricht über seine Geschwister. Etwas stimmt nicht.',
      tokens: ['Ich', 'habe', 'kein', 'Bruder.'],
      errorTokenIndex: 2,
      correction: 'keinen',
      explanation: 'Bruder is masculine and is the accusative object of habe, so kein must take the accusative masculine ending keinen.',
    },
    {
      id: 'ch16-ex-32',
      chapterNumber: 16,
      order: 32,
      type: 'errorSpotting',
      level: 'production',
      grammarFocus: ['kein-declension', 'feminine', 'error-correction'],
      instruction: 'Find the token with the wrong ending, and correct it.',
      prompt: 'Jemand spricht über seine Geschwister. Etwas stimmt nicht.',
      tokens: ['Sie', 'hat', 'kein', 'Schwester.'],
      errorTokenIndex: 2,
      correction: 'keine',
      explanation: 'Schwester is feminine, so kein must take the feminine ending keine in both the nominative and the accusative.',
    },
    {
      id: 'ch16-ex-33',
      chapterNumber: 16,
      order: 33,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['negation', 'nicht', 'adjective', 'error-correction'],
      instruction: 'Find the token that uses the wrong negation word, and correct it.',
      prompt: 'Jemand beschreibt den Zustand eines Autos. Etwas stimmt nicht.',
      tokens: ['Das', 'Auto', 'ist', 'kein', 'neu.'],
      errorTokenIndex: 3,
      correction: 'nicht',
      explanation: 'neu is an adjective, and adjectives are always negated with nicht — kein only negates nouns.',
    },
    {
      id: 'ch16-ex-34',
      chapterNumber: 16,
      order: 34,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'feminine'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Ich habe ___ Katze."',
      templateParts: ['Ich habe ', ' Katze.'],
      slots: [{ id: 'ch16-ex34-slot1', correctWord: 'keine' }],
      wordBank: ['keine', 'kein', 'keinen', 'nicht'],
      explanation: 'Katze is feminine and has no article in the affirmative sentence, so kein becomes keine.',
    },
    {
      id: 'ch16-ex-35',
      chapterNumber: 16,
      order: 35,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'masculine', 'no-article-noun'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Er trinkt ___ Tee."',
      templateParts: ['Er trinkt ', ' Tee.'],
      slots: [{ id: 'ch16-ex35-slot1', correctWord: 'keinen' }],
      wordBank: ['keinen', 'keine', 'kein', 'nicht'],
      explanation: 'Tee has no article and is masculine, standing in the accusative, so kein becomes keinen.',
    },
    {
      id: 'ch16-ex-36',
      chapterNumber: 16,
      order: 36,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'nominative', 'neuter'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Das ist ___ Handy."',
      templateParts: ['Das ist ', ' Handy.'],
      slots: [{ id: 'ch16-ex36-slot1', correctWord: 'kein' }],
      wordBank: ['kein', 'keine', 'keinen', 'nicht'],
      explanation: 'Handy is neuter and stands in the nominative, so kein keeps its unchanged base form.',
    },
    {
      id: 'ch16-ex-37',
      chapterNumber: 16,
      order: 37,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['negation', 'kein', 'no-article-noun', 'feminine'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Ich mag ___ Suppe."',
      templateParts: ['Ich mag ', ' Suppe.'],
      slots: [{ id: 'ch16-ex37-slot1', correctWord: 'keine' }],
      wordBank: ['keine', 'kein', 'keinen', 'nicht'],
      explanation: 'Suppe has no article and is feminine, so it is negated with keine, not nicht.',
    },
    {
      id: 'ch16-ex-38',
      chapterNumber: 16,
      order: 38,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['negation', 'nicht', 'adjective'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Er ist heute ___ müde."',
      templateParts: ['Er ist heute ', ' müde.'],
      slots: [{ id: 'ch16-ex38-slot1', correctWord: 'nicht' }],
      wordBank: ['nicht', 'kein', 'keine', 'keinen'],
      explanation: 'müde is an adjective, and adjectives are always negated with nicht, never with a form of kein.',
    },
    {
      id: 'ch16-ex-39',
      chapterNumber: 16,
      order: 39,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['negation', 'nicht', 'proper-noun'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Ich kenne ___ Peter."',
      templateParts: ['Ich kenne ', ' Peter.'],
      slots: [{ id: 'ch16-ex39-slot1', correctWord: 'nicht' }],
      wordBank: ['nicht', 'kein', 'keine', 'keinen'],
      explanation: 'Peter is a proper name, so it is negated with nicht — kein can never combine with a name.',
    },
    {
      id: 'ch16-ex-40',
      chapterNumber: 16,
      order: 40,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['kein-declension', 'plural'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Wir haben ___ Kinder."',
      templateParts: ['Wir haben ', ' Kinder.'],
      slots: [{ id: 'ch16-ex40-slot1', correctWord: 'keine' }],
      wordBank: ['keine', 'kein', 'keinen', 'nicht'],
      explanation: 'Kinder is plural, and kein uses keine for all plural nouns regardless of gender.',
    },
    {
      id: 'ch16-ex-41',
      chapterNumber: 16,
      order: 41,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['negation', 'nicht', 'possessive'],
      instruction: 'Choose nicht or the correct form of kein to fill the gap.',
      prompt: 'Vervollständige den Satz: "Das ist ___ mein Buch."',
      templateParts: ['Das ist ', ' mein Buch.'],
      slots: [{ id: 'ch16-ex41-slot1', correctWord: 'nicht' }],
      wordBank: ['nicht', 'kein', 'keine', 'keinen'],
      explanation: 'mein is a possessive determiner, and kein cannot combine with a possessive, so nicht is used instead.',
    },
    {
      id: 'ch16-ex-42',
      chapterNumber: 16,
      order: 42,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'kein', 'no-article-noun', 'neuter'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Ich esse ___ Brot.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'nicht' },
        { id: 'c', text: 'keine' },
        { id: 'd', text: 'keinen' },
      ],
      correctOptionId: 'a',
      explanation: 'Brot has no article at all in the affirmative sentence and is neuter, so it is negated with the unchanged form kein.',
    },
    {
      id: 'ch16-ex-43',
      chapterNumber: 16,
      order: 43,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['negation', 'kein', 'no-article-noun', 'feminine'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Ich sehe heute ___ Sonne.',
      options: [
        { id: 'a', text: 'keine' },
        { id: 'b', text: 'nicht' },
        { id: 'c', text: 'kein' },
        { id: 'd', text: 'keinen' },
      ],
      correctOptionId: 'a',
      explanation: 'Sonne has no article and is feminine, so it is negated with kein in its feminine form: keine.',
    },
    {
      id: 'ch16-ex-44',
      chapterNumber: 16,
      order: 44,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'masculine'],
      instruction: 'Choose the correct form of kein.',
      prompt: 'Wir kaufen ___ Tisch.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'keine' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keinem' },
      ],
      correctOptionId: 'c',
      explanation: 'Tisch is masculine and is the accusative object of kaufen, so kein takes the accusative masculine ending: keinen.',
    },
    {
      id: 'ch16-ex-45',
      chapterNumber: 16,
      order: 45,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'neuter'],
      instruction: 'Choose the correct form of kein.',
      prompt: 'Sie hat ___ Kind.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'keine' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keinem' },
      ],
      correctOptionId: 'a',
      explanation: 'Kind is neuter, and neuter nouns keep the unchanged form kein in both the nominative and the accusative.',
    },
    {
      id: 'ch16-ex-46',
      chapterNumber: 16,
      order: 46,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['negation', 'nicht', 'placement', 'narrow-negation'],
      instruction: 'Choose the sentence that says he is not coming by bike, implying he is coming some other way.',
      prompt: 'Which sentence correctly expresses a narrow negation of "mit dem Fahrrad"?',
      options: [
        { id: 'a', text: 'Er kommt nicht mit dem Fahrrad, sondern mit dem Zug.' },
        { id: 'b', text: 'Er kommt mit dem Fahrrad nicht.' },
        { id: 'c', text: 'Er kommt kein Fahrrad, sondern mit dem Zug.' },
        { id: 'd', text: 'Er kommt nicht.' },
      ],
      correctOptionId: 'a',
      explanation: 'To negate only mit dem Fahrrad, nicht stands directly in front of that phrase, followed by the correction with sondern.',
    },
    {
      id: 'ch16-ex-47',
      chapterNumber: 16,
      order: 47,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['negation', 'nicht', 'adjective'],
      instruction: 'Choose nicht or kein to complete the sentence correctly.',
      prompt: 'Er ist mit dem Ergebnis ___ zufrieden.',
      options: [
        { id: 'a', text: 'nicht' },
        { id: 'b', text: 'kein' },
        { id: 'c', text: 'keine' },
        { id: 'd', text: 'keinen' },
      ],
      correctOptionId: 'a',
      explanation: 'zufrieden is an adjective, and adjectives are negated with nicht, never with a form of kein.',
    },
    {
      id: 'ch16-ex-48',
      chapterNumber: 16,
      order: 48,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['kein-declension', 'accusative', 'masculine'],
      instruction: 'Choose the correct form of kein.',
      prompt: 'Ich habe ___ Schlüssel dabei.',
      options: [
        { id: 'a', text: 'kein' },
        { id: 'b', text: 'keine' },
        { id: 'c', text: 'keinen' },
        { id: 'd', text: 'keinem' },
      ],
      correctOptionId: 'c',
      explanation: 'Schlüssel is masculine and is the accusative object of habe, so kein becomes keinen.',
    },
    {
      id: 'ch16-ex-49',
      chapterNumber: 16,
      order: 49,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['negation', 'kein', 'no-article-noun', 'common-mistake'],
      instruction: 'Choose the correctly negated sentence.',
      prompt: 'Which sentence correctly negates "Ich habe ein Auto."?',
      options: [
        { id: 'a', text: 'Ich habe kein Auto.' },
        { id: 'b', text: 'Ich habe nicht ein Auto.' },
        { id: 'c', text: 'Ich habe ein keinen Auto.' },
        { id: 'd', text: 'Ich habe nicht Auto.' },
      ],
      correctOptionId: 'a',
      explanation: 'The indefinite article ein is simply replaced by kein — nicht is never added in front of ein, and ein and kein are never combined.',
    },
    {
      id: 'ch16-ex-50',
      chapterNumber: 16,
      order: 50,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'feminine'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Ich habe ___ Katze.',
      acceptedAnswers: ['keine'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein-form',
      maxLength: 12,
      explanation: 'Katze is feminine and has no article in the affirmative sentence, so kein becomes keine.',
    },
    {
      id: 'ch16-ex-51',
      chapterNumber: 16,
      order: 51,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'nominative', 'neuter'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Das ist ___ Buch von mir.',
      acceptedAnswers: ['kein'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein-form',
      maxLength: 12,
      explanation: 'Buch is neuter and stands in the nominative, so kein keeps its unchanged base form.',
    },
    {
      id: 'ch16-ex-52',
      chapterNumber: 16,
      order: 52,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['kein-declension', 'accusative', 'plural'],
      instruction: 'Fill in the correct form of kein. Capitalisation is not checked.',
      prompt: 'Sie haben ___ Kinder.',
      acceptedAnswers: ['keine'],
      answerMode: 'caseInsensitive',
      placeholder: 'kein-form',
      maxLength: 12,
      explanation: 'Kinder is plural, and kein uses keine for all plural nouns regardless of gender.',
    },
    {
      id: 'ch16-ex-53',
      chapterNumber: 16,
      order: 53,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['negation', 'kein', 'no-article-noun', 'neuter'],
      instruction: 'Fill in nicht or the correct form of kein. Capitalisation is not checked.',
      prompt: 'Ich trinke ___ Wasser.',
      acceptedAnswers: ['kein'],
      answerMode: 'caseInsensitive',
      placeholder: 'nicht / kein-form',
      maxLength: 12,
      explanation: 'Wasser has no article and is neuter, so it is negated with the unchanged form kein, not nicht.',
    },
    {
      id: 'ch16-ex-54',
      chapterNumber: 16,
      order: 54,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['negation', 'nicht', 'adjective'],
      instruction: 'Fill in nicht or the correct form of kein. Capitalisation is not checked.',
      prompt: 'Er ist heute ___ müde.',
      acceptedAnswers: ['nicht'],
      answerMode: 'caseInsensitive',
      placeholder: 'nicht / kein-form',
      maxLength: 12,
      explanation: 'müde is an adjective, and adjectives are always negated with nicht, never with a form of kein.',
    },
    {
      id: 'ch16-ex-55',
      chapterNumber: 16,
      order: 55,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['negation', 'kein', 'accusative', 'feminine'],
      instruction: 'Rewrite the sentence in the negative form using kein. Capitalisation and punctuation are checked.',
      prompt: 'Ich habe eine Schwester.',
      acceptedAnswers: ['Ich habe keine Schwester.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe ...',
      maxLength: 40,
      explanation: 'The indefinite article eine is replaced by keine (Schwester is feminine), giving Ich habe keine Schwester.',
    },
    {
      id: 'ch16-ex-56',
      chapterNumber: 16,
      order: 56,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['negation', 'nicht', 'proper-noun'],
      instruction: 'Rewrite the sentence in the negative form using nicht. Capitalisation and punctuation are checked.',
      prompt: 'Er kennt Maria.',
      acceptedAnswers: ['Er kennt Maria nicht.'],
      answerMode: 'normalized',
      placeholder: 'Er kennt ...',
      maxLength: 40,
      explanation: 'Maria is a proper name, so it is negated with nicht, placed at the end of the clause for a whole-sentence negation: Er kennt Maria nicht.',
    },
    {
      id: 'ch16-ex-57',
      chapterNumber: 16,
      order: 57,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['negation', 'kein', 'nominative', 'neuter'],
      instruction:
        'Write a complete negative sentence using the cue words and the correct form of kein. Capitalisation and punctuation are checked.',
      prompt: 'sie (Einzahl) – Handy – haben',
      acceptedAnswers: ['Sie hat kein Handy.'],
      answerMode: 'normalized',
      placeholder: 'Sie hat ...',
      maxLength: 45,
      explanation: 'Handy has no article and is neuter, so kein keeps its unchanged form: Sie hat kein Handy.',
    },
  ],
};
