import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter003: ChapterDefinition = {
  id: 'chapter-003',
  number: 3,
  slug: 'sein-haben-and-special-irregular-verbs',
  title: 'sein, haben, and Special Irregular Verbs',
  germanTitle: 'sein, haben und weitere unregelmäßige Verben',
  level: 'A1',
  section: 'verbs-1',
  objective:
    'Conjugate sein and haben correctly in all persons, recognise a few other essential irregular verbs (werden, wissen, tun), and choose correctly between sein and haben to express identity, state, and possession.',
  prerequisites: [2],
  estimatedMinutes: 25,
  tags: ['sein', 'haben', 'irregular-verbs', 'present-tense', 'identity', 'possession'],
  explanation: {
    introduction: [
      'sein (to be) and haben (to have) are the two most important verbs in German. They are used constantly on their own, and later they also help build other tenses, so it is essential to know their forms by heart from the very beginning.',
      'Both verbs are irregular (unregelmäßig): unlike the regular verbs from the previous chapter, their forms do not simply follow the stem-plus-ending pattern. A few other very common verbs — werden (to become), wissen (to know a fact), and tun (to do) — are irregular in similar ways and are introduced here too.',
    ],
    rules: [
      {
        id: 'ch03-rule-01',
        heading: 'sein: the most irregular verb',
        paragraphs: [
          'sein has a different form for almost every person, so it cannot be built from one stem with regular endings: ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind.',
          'There is no shortcut here — these six forms simply need to be memorised as a set, just like in most other languages.',
        ],
        notes: [
          'Despite its irregularity, sein is one of the most frequent words in German, so the forms quickly become automatic with practice.',
        ],
      },
      {
        id: 'ch03-rule-02',
        heading: 'haben: irregular in du and er/sie/es',
        paragraphs: [
          'haben mostly follows the familiar ending pattern, but the du- and er/sie/es-forms drop the b of the stem: ich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie/Sie haben.',
          'Compare habe (ich) with hast and hat: everywhere else the stem hab- stays intact, but before -st and -t the b disappears.',
        ],
      },
      {
        id: 'ch03-rule-03',
        heading: 'Other important irregular verbs: werden, wissen, tun',
        paragraphs: [
          'werden (to become) changes its stem vowel from e to i in the du- and er/sie/es-forms: ich werde, du wirst, er/sie/es wird, wir werden, ihr werdet, sie/Sie werden.',
          'wissen (to know a fact) has no ending at all in the singular, and its stem vowel changes from i to ei throughout the singular: ich weiß, du weißt, er/sie/es weiß. The plural returns to the regular stem wiss- with normal endings: wir wissen, ihr wisst, sie/Sie wissen.',
          'tun (to do) has an unusually short infinitive (only -n, not -en), but once you know the stem tu-, its endings follow the normal pattern: ich tue, du tust, er/sie/es tut, wir tun, ihr tut, sie/Sie tun.',
        ],
        notes: [
          'Do not confuse wissen (to know facts or information) with kennen (to know or be familiar with a person or place) — kennen is a regular verb and is not covered in this chapter.',
        ],
      },
      {
        id: 'ch03-rule-04',
        heading: 'When to use sein and when to use haben',
        paragraphs: [
          'Use sein to say what someone or something is, or what state it is in: identity (Ich bin Lehrer), nationality (Sie ist Deutsche), a quality (Er ist müde), or where someone is.',
          'Use haben to say what someone possesses: objects (Wir haben ein Auto), family (Sie hat zwei Brüder), or time (Habt ihr Zeit?).',
          'A number of everyday feelings and needs that English expresses with "to be" are expressed with haben in German: Hunger haben (to be hungry), Durst haben (to be thirsty), Angst haben (to be afraid), Zeit haben (to have time). These are fixed expressions and must simply be learned with haben.',
        ],
        notes: [
          'When translating from English, watch out especially for "I am hungry/thirsty/afraid" — German never uses sein for these expressions.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch03-table-01',
        title: 'sein and haben in the present tense',
        columns: ['Person', 'Pronoun', 'sein', 'haben'],
        rows: [
          ['1st singular', 'ich', 'bin', 'habe'],
          ['2nd singular, informal', 'du', 'bist', 'hast'],
          ['3rd singular', 'er/sie/es', 'ist', 'hat'],
          ['1st plural', 'wir', 'sind', 'haben'],
          ['2nd plural, informal', 'ihr', 'seid', 'habt'],
          ['3rd plural / formal', 'sie/Sie', 'sind', 'haben'],
        ],
        note: 'These six forms of sein and haben should be memorised together, since they do not follow the regular ending pattern from the previous chapter.',
      },
      {
        id: 'ch03-table-02',
        title: 'werden, wissen, and tun in the present tense',
        columns: ['Pronoun', 'werden', 'wissen', 'tun'],
        rows: [
          ['ich', 'werde', 'weiß', 'tue'],
          ['du', 'wirst', 'weißt', 'tust'],
          ['er/sie/es', 'wird', 'weiß', 'tut'],
          ['wir', 'werden', 'wissen', 'tun'],
          ['ihr', 'werdet', 'wisst', 'tut'],
          ['sie/Sie', 'werden', 'wissen', 'tun'],
        ],
        note: 'wissen changes its vowel from i to ei in all three singular forms; werden changes e to i only in the du- and er/sie/es-forms; tun keeps the same vowel throughout.',
      },
    ],
    examples: [
      {
        german: 'Ich bin Studentin.',
        english: 'I am a student.',
        highlight: ['bin'],
        explanation: 'sein is used here for identity/profession.',
      },
      {
        german: 'Du bist sehr nett.',
        english: 'You are very nice.',
        highlight: ['bist'],
      },
      {
        german: 'Er ist mein Bruder.',
        english: 'He is my brother.',
        highlight: ['ist'],
      },
      {
        german: 'Wir sind aus Österreich.',
        english: 'We are from Austria.',
        highlight: ['sind'],
      },
      {
        german: 'Ihr seid heute spät.',
        english: 'You (all) are late today.',
        highlight: ['seid'],
      },
      {
        german: 'Sie sind sehr freundlich.',
        english: 'They are very friendly.',
        highlight: ['sind'],
        explanation: 'Plural sie always pairs with sind.',
      },
      {
        german: 'Ich habe eine Schwester.',
        english: 'I have a sister.',
        highlight: ['habe'],
      },
      {
        german: 'Du hast keine Zeit.',
        english: 'You have no time.',
        highlight: ['hast'],
      },
      {
        german: 'Sie hat blaue Augen.',
        english: 'She has blue eyes.',
        highlight: ['hat'],
      },
      {
        german: 'Wir haben zwei Kinder.',
        english: 'We have two children.',
        highlight: ['haben'],
      },
      {
        german: 'Habt ihr Hunger?',
        english: 'Are you (all) hungry?',
        highlight: ['Habt'],
        explanation:
          'German uses haben for Hunger, even though the English translation uses "to be".',
      },
      {
        german: 'Er wird jetzt müde.',
        english: 'He is getting tired now.',
        highlight: ['wird'],
      },
      {
        german: 'Ich weiß die Antwort nicht.',
        english: 'I do not know the answer.',
        highlight: ['weiß'],
      },
      {
        german: 'Was tust du gerade?',
        english: 'What are you doing right now?',
        highlight: ['tust'],
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich habe 20 Jahre alt.',
        correct: 'Ich bin 20 Jahre alt.',
        explanation:
          'Age is expressed with sein in German, not haben, even though some other languages use "to have" for age.',
      },
      {
        incorrect: 'Ich bin Hunger.',
        correct: 'Ich habe Hunger.',
        explanation:
          'Hunger, Durst, and Angst are used with haben in German, even though English says "I am hungry/thirsty/afraid".',
      },
      {
        incorrect: 'Du bin müde.',
        correct: 'Du bist müde.',
        explanation: 'bin belongs only to ich; du always takes bist.',
      },
      {
        incorrect: 'Er hat Lehrer.',
        correct: 'Er ist Lehrer.',
        explanation: 'Profession and identity are expressed with sein, not haben.',
      },
      {
        incorrect: 'Wir habt einen Garten.',
        correct: 'Wir haben einen Garten.',
        explanation: 'habt belongs to ihr; wir always takes haben.',
      },
      {
        incorrect: 'Er weißt die Antwort.',
        correct: 'Er weiß die Antwort.',
        explanation:
          'weißt is the du-form; er/sie/es also uses weiß, without any extra ending.',
      },
    ],
    remember: [
      'sein (bin, bist, ist, sind, seid, sind) and haben (habe, hast, hat, haben, habt, haben) must be memorised as full sets — they do not follow the regular ending pattern.',
      'werden, wissen, and tun are also irregular: werden and wissen change their stem vowel in the singular, and wissen has no ending at all in the singular.',
      'Use sein for identity, nationality, qualities, and states; use haben for possession.',
      'Fixed expressions like Hunger haben, Durst haben, and Angst haben always use haben in German, even where English uses "to be".',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 24,
    requiredCorrectTextInputs: 8,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch03-ex-01',
      chapterNumber: 3,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sein-conjugation'],
      instruction: 'Choose the correct form of sein.',
      prompt: 'Ich ___ müde.',
      options: [
        { id: 'a', text: 'bin' },
        { id: 'b', text: 'bist' },
        { id: 'c', text: 'ist' },
        { id: 'd', text: 'sind' },
      ],
      correctOptionId: 'a',
      explanation: 'ich always takes the form bin; sein is irregular in every person.',
    },
    {
      id: 'ch03-ex-02',
      chapterNumber: 3,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['sein-conjugation'],
      instruction: 'Choose the correct form of sein.',
      prompt: 'Wir ___ zu Hause.',
      options: [
        { id: 'a', text: 'sind' },
        { id: 'b', text: 'seid' },
        { id: 'c', text: 'ist' },
        { id: 'd', text: 'bin' },
      ],
      correctOptionId: 'a',
      explanation: 'wir takes sind. seid belongs to ihr, ist to er/sie/es, bin to ich.',
    },
    {
      id: 'ch03-ex-03',
      chapterNumber: 3,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['haben-conjugation'],
      instruction: 'Choose the correct form of haben.',
      prompt: 'Du ___ ein Auto.',
      options: [
        { id: 'a', text: 'hast' },
        { id: 'b', text: 'hat' },
        { id: 'c', text: 'habt' },
        { id: 'd', text: 'habe' },
      ],
      correctOptionId: 'a',
      explanation: 'du takes hast. The b of the stem hab- drops before the -st ending.',
    },
    {
      id: 'ch03-ex-04',
      chapterNumber: 3,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['haben-conjugation', 'sein-vs-haben'],
      instruction: 'Choose the correct form.',
      prompt: 'Er ___ viel Geld.',
      options: [
        { id: 'a', text: 'hat' },
        { id: 'b', text: 'hast' },
        { id: 'c', text: 'habt' },
        { id: 'd', text: 'ist' },
      ],
      correctOptionId: 'a',
      explanation:
        'Possession is expressed with haben: er/sie/es hat. ist would be the wrong verb for possession.',
    },
    {
      id: 'ch03-ex-05',
      chapterNumber: 3,
      order: 5,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sein-vs-haben', 'fixed-expressions'],
      instruction: 'Choose the correct verb form for talking about age.',
      prompt: 'Ich ___ 20 Jahre alt.',
      options: [
        { id: 'a', text: 'bin' },
        { id: 'b', text: 'habe' },
        { id: 'c', text: 'bist' },
        { id: 'd', text: 'hast' },
      ],
      correctOptionId: 'a',
      explanation:
        'German expresses age with sein (Jahre alt sein), not with haben, even though other languages sometimes use "to have" here.',
    },
    {
      id: 'ch03-ex-06',
      chapterNumber: 3,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sein-vs-haben', 'fixed-expressions'],
      instruction: 'Choose the correct verb form.',
      prompt: 'Ich ___ Hunger.',
      options: [
        { id: 'a', text: 'habe' },
        { id: 'b', text: 'bin' },
        { id: 'c', text: 'hast' },
        { id: 'd', text: 'ist' },
      ],
      correctOptionId: 'a',
      explanation:
        'Hunger haben is a fixed expression that always uses haben, even though English says "I am hungry".',
    },
    {
      id: 'ch03-ex-07',
      chapterNumber: 3,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sein-vs-haben', 'identity'],
      instruction: 'Choose the correct verb form.',
      prompt: 'Er ___ Lehrer.',
      options: [
        { id: 'a', text: 'ist' },
        { id: 'b', text: 'hat' },
        { id: 'c', text: 'sind' },
        { id: 'd', text: 'bist' },
      ],
      correctOptionId: 'a',
      explanation: 'Profession and identity are expressed with sein: er ist Lehrer.',
    },
    {
      id: 'ch03-ex-08',
      chapterNumber: 3,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['sein-vs-haben', 'possession'],
      instruction: 'Choose the correct verb form.',
      prompt: 'Wir ___ zwei Kinder.',
      options: [
        { id: 'a', text: 'haben' },
        { id: 'b', text: 'sind' },
        { id: 'c', text: 'habt' },
        { id: 'd', text: 'seid' },
      ],
      correctOptionId: 'a',
      explanation: 'Possession is expressed with haben: wir haben, not sind (sein).',
    },
    {
      id: 'ch03-ex-09',
      chapterNumber: 3,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['werden-conjugation'],
      instruction: 'Choose the correct form of werden.',
      prompt: 'Du ___ (werden) langsam müde.',
      options: [
        { id: 'a', text: 'wirst' },
        { id: 'b', text: 'wird' },
        { id: 'c', text: 'werdest' },
        { id: 'd', text: 'werde' },
      ],
      correctOptionId: 'a',
      explanation:
        'du takes wirst. werden changes its stem vowel from e to i in the du- and er/sie/es-forms.',
    },
    {
      id: 'ch03-ex-10',
      chapterNumber: 3,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wissen-conjugation'],
      instruction: 'Choose the correct form of wissen.',
      prompt: 'Ich ___ (wissen) die Antwort nicht.',
      options: [
        { id: 'a', text: 'weiß' },
        { id: 'b', text: 'weißt' },
        { id: 'c', text: 'wisst' },
        { id: 'd', text: 'wissen' },
      ],
      correctOptionId: 'a',
      explanation:
        'ich weiß has no ending at all in the singular; weißt is the du-form, wisst the ihr-form, wissen the wir/sie/Sie-form.',
    },
    {
      id: 'ch03-ex-11',
      chapterNumber: 3,
      order: 11,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['sein-vs-haben', 'error-correction'],
      instruction: 'Choose the correctly written sentence.',
      prompt: 'Which sentence is correct?',
      options: [
        { id: 'a', text: 'Er hat Angst.' },
        { id: 'b', text: 'Er ist Angst.' },
        { id: 'c', text: 'Er sind Angst.' },
        { id: 'd', text: 'Er bist Angst.' },
      ],
      correctOptionId: 'a',
      explanation:
        'Angst haben is a fixed expression with haben. Er hat is also the only grammatically correct er-form among the options.',
    },
    {
      id: 'ch03-ex-12',
      chapterNumber: 3,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['haben-conjugation', 'error-correction'],
      instruction: 'Choose the correct wir-form of haben.',
      prompt: 'Welche Form ist richtig?',
      options: [
        { id: 'a', text: 'wir haben' },
        { id: 'b', text: 'wir habt' },
        { id: 'c', text: 'wir habet' },
        { id: 'd', text: 'wir hat' },
      ],
      correctOptionId: 'a',
      explanation:
        'wir takes haben. habt belongs to ihr, hat to er/sie/es, and habet does not exist.',
    },
    {
      id: 'ch03-ex-13',
      chapterNumber: 3,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sein-conjugation'],
      instruction: 'Write the missing form of sein. Capitalisation is not checked.',
      prompt: 'Ich ___ Student.',
      acceptedAnswers: ['bin'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation: 'ich always takes bin.',
    },
    {
      id: 'ch03-ex-14',
      chapterNumber: 3,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['sein-conjugation'],
      instruction: 'Write the missing form of sein. Capitalisation is not checked.',
      prompt: 'Ihr ___ pünktlich.',
      acceptedAnswers: ['seid'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation: 'ihr always takes seid.',
    },
    {
      id: 'ch03-ex-15',
      chapterNumber: 3,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['haben-conjugation'],
      instruction: 'Write the missing form of haben. Capitalisation is not checked.',
      prompt: 'Du ___ Zeit?',
      acceptedAnswers: ['hast'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation: 'du always takes hast.',
    },
    {
      id: 'ch03-ex-16',
      chapterNumber: 3,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['haben-conjugation'],
      instruction: 'Write the missing form of haben. Capitalisation is not checked.',
      prompt: 'Sie (die Nachbarn) ___ ein Haus.',
      acceptedAnswers: ['haben'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation: 'Plural sie (they) takes haben.',
    },
    {
      id: 'ch03-ex-17',
      chapterNumber: 3,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['werden-conjugation'],
      instruction: 'Write the missing form of werden. Capitalisation is not checked.',
      prompt: 'Er (werden) ___ müde.',
      acceptedAnswers: ['wird'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation:
        'er/sie/es takes wird; werden changes its stem vowel from e to i here.',
    },
    {
      id: 'ch03-ex-18',
      chapterNumber: 3,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wissen-conjugation'],
      instruction: 'Write the missing form of wissen. Capitalisation is not checked.',
      prompt: 'Wir (wissen) ___ das nicht.',
      acceptedAnswers: ['wissen'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation: 'wir returns to the regular stem wiss- with the ending -en: wissen.',
    },
    {
      id: 'ch03-ex-19',
      chapterNumber: 3,
      order: 19,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sein-vs-haben', 'fixed-expressions'],
      instruction: 'Write the missing verb form. Capitalisation is not checked.',
      prompt: 'Ich ___ 30 Jahre alt.',
      acceptedAnswers: ['bin'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation: 'Age is expressed with sein: ich bin ... Jahre alt.',
    },
    {
      id: 'ch03-ex-20',
      chapterNumber: 3,
      order: 20,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sein-vs-haben', 'fixed-expressions'],
      instruction: 'Write the missing verb form. Capitalisation is not checked.',
      prompt: 'Ich ___ Durst.',
      acceptedAnswers: ['habe'],
      answerMode: 'caseInsensitive',
      placeholder: 'form',
      maxLength: 10,
      explanation: 'Durst haben is a fixed expression that always uses haben.',
    },
    {
      id: 'ch03-ex-21',
      chapterNumber: 3,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sein-vs-haben', 'identity', 'sentence-formation'],
      instruction:
        'Translate the sentence into German. Capitalisation and the full stop are checked.',
      prompt: 'He is a doctor.',
      acceptedAnswers: ['Er ist Arzt.'],
      answerMode: 'normalized',
      placeholder: 'Er ...',
      maxLength: 60,
      explanation: 'A profession is expressed with sein: Er ist Arzt.',
    },
    {
      id: 'ch03-ex-22',
      chapterNumber: 3,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['sein-vs-haben', 'possession', 'sentence-formation'],
      instruction:
        'Translate the sentence into German. Capitalisation and the full stop are checked.',
      prompt: 'We have a cat.',
      acceptedAnswers: ['Wir haben eine Katze.'],
      answerMode: 'normalized',
      placeholder: 'Wir ...',
      maxLength: 60,
      explanation: 'Possession is expressed with haben: Wir haben eine Katze.',
    },
    {
      id: 'ch03-ex-23',
      chapterNumber: 3,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sein-vs-haben', 'error-correction'],
      instruction: 'Correct the sentence and write it out completely.',
      prompt: 'Du bist Hunger.',
      acceptedAnswers: ['Du hast Hunger.'],
      answerMode: 'normalized',
      placeholder: 'Du ...',
      maxLength: 60,
      explanation: 'Hunger haben always uses haben, not sein: Du hast Hunger.',
    },
    {
      id: 'ch03-ex-24',
      chapterNumber: 3,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['sein-vs-haben', 'error-correction'],
      instruction: 'Correct the sentence and write it out completely.',
      prompt: 'Wir haben müde.',
      acceptedAnswers: ['Wir sind müde.'],
      answerMode: 'normalized',
      placeholder: 'Wir ...',
      maxLength: 60,
      explanation:
        'A state such as being tired is expressed with sein, not haben: Wir sind müde.',
    },
  ],
};
