import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter006: ChapterDefinition = {
  id: 'chapter-006',
  number: 6,
  slug: 'modal-verbs-usage-part-1',
  title: 'Modal Verbs: Usage, Part 1',
  germanTitle: 'Modalverben: Gebrauch, Teil 1',
  level: 'A1',
  section: 'verbs-1',
  objective:
    'Choose the correct modal verb — können, müssen, dürfen, wollen, or möchten — according to its meaning: ability, necessity, permission, intention, or a polite request.',
  prerequisites: [5],
  estimatedMinutes: 25,
  tags: ['modal-verbs', 'permission', 'ability', 'requests', 'everyday-german'],
  explanation: {
    introduction: [
      'Modal verbs (Modalverben) add meaning to a main verb: they say whether something is possible, necessary, allowed, or wanted. This chapter focuses on what each modal verb means and when to use it — the conjugation patterns were covered in the previous chapter.',
      'You will meet five modal verbs here: können (ability), müssen (necessity), dürfen (permission), wollen (desire or intention), and möchten (a polite way of saying "would like"). Choosing the right one is often about the situation, not just the grammar.',
    ],
    rules: [
      {
        id: 'ch06-rule-01',
        heading: 'The five modal verbs and their core meanings',
        paragraphs: [
          'können expresses ability or capability: what someone is physically or mentally able to do. Ich kann Deutsch sprechen. (I can speak German.)',
          'müssen expresses necessity or obligation: something that has to happen, with no real alternative. Wir müssen jetzt gehen. (We have to go now.)',
          'dürfen expresses permission: what someone is allowed to do because a rule or another person allows it. Darf ich reinkommen? (May I come in?)',
          'wollen expresses a wish or a firm intention: what someone wants or plans to do. Ich will Ärztin werden. (I want to become a doctor.)',
        ],
        notes: [
          'All five are modal verbs: the modal itself is conjugated, while the main verb stays in the infinitive at the end of the clause.',
        ],
      },
      {
        id: 'ch06-rule-02',
        heading: 'können vs. dürfen: ability vs. permission',
        paragraphs: [
          'können answers the question "Is this person capable of it?" — a matter of skill, strength, or circumstance.',
          'dürfen answers a different question: "Is this person allowed to do it?" — a matter of rules, laws, or someone else\'s permission.',
          'Compare: Er kann sehr schnell laufen. (He is able to run very fast — ability.) Er darf im Unterricht nicht laufen. (He is not allowed to run during class — permission.)',
        ],
        notes: [
          'In relaxed spoken German, kann is sometimes used loosely where dürfen would be more precise ("Kann ich mal kurz raus?"). For clear, correct usage, keep the two apart: ability = können, permission = dürfen.',
        ],
      },
      {
        id: 'ch06-rule-03',
        heading: 'wollen vs. möchten: a blunt wish vs. a polite request',
        paragraphs: [
          'wollen states a wish or intention directly and can sound forceful or even rude, especially towards people you do not know well: Ich will einen Kaffee. (I want a coffee — sounds demanding.)',
          'möchten softens the same wish and is the normal, polite choice for requests, orders, and offers: Ich möchte einen Kaffee, bitte. (I would like a coffee, please.)',
          'möchten is historically the subjunctive form of mögen ("to like"), which is why it feels gentler than wollen — but today it is simply the everyday polite way to say "would like".',
        ],
      },
      {
        id: 'ch06-rule-04',
        heading: 'Where the modal verb and the main verb go in the sentence',
        paragraphs: [
          'In a statement, the conjugated modal verb takes the second position, and the infinitive of the main verb moves to the very end of the clause: Ich muss heute arbeiten. (I have to work today.)',
          'In a yes/no question, the modal verb moves to the front, and the infinitive still stays at the end: Darfst du heute Abend ausgehen? (Are you allowed to go out tonight?)',
          'This split between the modal verb and the infinitive is called the verb bracket (Satzklammer); everything else in the sentence sits inside it.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch06-table-01',
        title: 'Modal verbs and their core meanings',
        columns: ['Modal verb', 'Core meaning', 'Example'],
        rows: [
          ['können', 'ability / capability', 'Ich kann gut kochen.'],
          ['müssen', 'necessity / obligation', 'Ich muss früh aufstehen.'],
          ['dürfen', 'permission', 'Ich darf hier bleiben.'],
          ['wollen', 'desire / firm intention', 'Ich will nach Berlin fahren.'],
          ['möchten', 'polite "would like"', 'Ich möchte einen Tee, bitte.'],
        ],
        note: 'möchten is used far more often than wollen in polite everyday requests.',
      },
      {
        id: 'ch06-table-02',
        title: 'möchten: the polite form of mögen',
        columns: ['Person', 'Form'],
        rows: [
          ['ich', 'möchte'],
          ['du', 'möchtest'],
          ['er / sie / es', 'möchte'],
          ['wir', 'möchten'],
          ['ihr', 'möchtet'],
          ['sie / Sie', 'möchten'],
        ],
        note: 'Unlike regular verbs, möchten adds no extra ending in the er/sie/es form.',
      },
    ],
    examples: [
      {
        german: 'Ich kann gut schwimmen.',
        english: 'I can swim well.',
        highlight: ['kann'],
        explanation: 'können expresses physical ability.',
      },
      {
        german: 'Kannst du mir bitte helfen?',
        english: 'Can you help me, please?',
        highlight: ['Kannst'],
        explanation:
          "A question with können, asking about someone's ability or willingness to help.",
      },
      {
        german: 'Wir müssen jetzt gehen, der Zug fährt gleich.',
        english: 'We have to go now, the train is leaving soon.',
        highlight: ['müssen'],
        explanation: 'müssen expresses necessity — there is no real alternative.',
      },
      {
        german: 'Du musst deine Hausaufgaben machen, bevor du spielst.',
        english: 'You have to do your homework before you play.',
        highlight: ['musst'],
      },
      {
        german: 'Darf ich hier parken?',
        english: 'May I park here?',
        highlight: ['Darf'],
        explanation: 'dürfen asks for permission, not ability.',
      },
      {
        german: 'Ihr dürft heute früher nach Hause gehen.',
        english: 'You are allowed to go home earlier today.',
        highlight: ['dürft'],
      },
      {
        german: 'Ich will dieses Jahr noch ein neues Auto kaufen.',
        english: 'I want to buy a new car this year.',
        highlight: ['will'],
        explanation: 'wollen expresses a firm intention or strong wish.',
      },
      {
        german: 'Er will Arzt werden.',
        english: 'He wants to become a doctor.',
        highlight: ['will'],
      },
      {
        german: 'Ich möchte einen Kaffee, bitte.',
        english: 'I would like a coffee, please.',
        highlight: ['möchte'],
        explanation: 'möchte is the polite way to order or request something.',
      },
      {
        german: 'Möchten Sie noch etwas bestellen?',
        english: 'Would you like to order anything else?',
        highlight: ['Möchten'],
        explanation: 'The formal, polite question a waiter asks a guest.',
      },
      {
        german: 'Wir möchten das Zimmer bis Freitag behalten.',
        english: 'We would like to keep the room until Friday.',
        highlight: ['möchten'],
      },
      {
        german: 'Darf ich Sie kurz etwas fragen?',
        english: 'May I ask you something briefly?',
        highlight: ['Darf'],
        explanation:
          "A polite way to ask for someone's attention, using permission rather than ability.",
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich kann hier parken?',
        correct: 'Darf ich hier parken?',
        explanation: 'können asks about ability; asking for permission needs dürfen.',
      },
      {
        incorrect: 'Ich will einen Kaffee.',
        correct: 'Ich möchte einen Kaffee, bitte.',
        explanation:
          'wollen can sound blunt or demanding in a request; möchte is the polite equivalent.',
      },
      {
        incorrect: 'Ich will zur Schule gehen, weil es Pflicht ist.',
        correct: 'Ich muss zur Schule gehen, weil es Pflicht ist.',
        explanation:
          'An obligation is expressed with müssen, not wollen — wollen describes a wish, not a duty.',
      },
      {
        incorrect: 'Ich kann schwimmen gut.',
        correct: 'Ich kann gut schwimmen.',
        explanation:
          'The infinitive that belongs to the modal verb goes to the very end of the clause, not right after the modal.',
      },
      {
        incorrect: 'Er möchtet ein Eis.',
        correct: 'Er möchte ein Eis.',
        explanation:
          'The er/sie/es form of möchten is möchte, without an extra -t ending.',
      },
    ],
    remember: [
      'können = ability ("can do"); dürfen = permission ("am allowed to") — do not mix them up.',
      'müssen = necessity or obligation; wollen = desire or firm intention.',
      'möchten is the polite way to say "would like": ich möchte, du möchtest, er/sie/es möchte, wir möchten, ihr möchtet, sie/Sie möchten.',
      'The modal verb takes second position in the sentence, and the main verb stays in its infinitive form at the very end.',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 53,
    requiredCorrectTextInputs: 18,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch06-ex-01',
      chapterNumber: 6,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['modal-meaning', 'können'],
      instruction: 'Choose the modal verb that expresses this meaning.',
      prompt: 'Which modal verb expresses being capable of doing something (ability)?',
      options: [
        { id: 'a', text: 'müssen' },
        { id: 'b', text: 'können' },
        { id: 'c', text: 'dürfen' },
        { id: 'd', text: 'wollen' },
      ],
      correctOptionId: 'b',
      explanation:
        'können expresses ability or capability — what someone is physically or mentally able to do.',
    },
    {
      id: 'ch06-ex-02',
      chapterNumber: 6,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['modal-meaning', 'müssen'],
      instruction: 'Choose the modal verb that expresses this meaning.',
      prompt:
        'Which modal verb expresses that something is necessary, with no other choice?',
      options: [
        { id: 'a', text: 'müssen' },
        { id: 'b', text: 'dürfen' },
        { id: 'c', text: 'wollen' },
        { id: 'd', text: 'möchten' },
      ],
      correctOptionId: 'a',
      explanation: 'müssen expresses necessity or obligation — something you have to do.',
    },
    {
      id: 'ch06-ex-03',
      chapterNumber: 6,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['modal-meaning', 'dürfen'],
      instruction: 'Choose the modal verb that expresses this meaning.',
      prompt:
        'Which modal verb expresses permission — that someone is allowed to do something?',
      options: [
        { id: 'a', text: 'können' },
        { id: 'b', text: 'wollen' },
        { id: 'c', text: 'dürfen' },
        { id: 'd', text: 'müssen' },
      ],
      correctOptionId: 'c',
      explanation:
        'dürfen expresses permission — what someone is allowed to do, according to a rule or another person.',
    },
    {
      id: 'ch06-ex-04',
      chapterNumber: 6,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['modal-meaning', 'wollen'],
      instruction: 'Choose the modal verb that expresses this meaning.',
      prompt: 'Which modal verb expresses a strong desire or a firm intention?',
      options: [
        { id: 'a', text: 'dürfen' },
        { id: 'b', text: 'wollen' },
        { id: 'c', text: 'müssen' },
        { id: 'd', text: 'können' },
      ],
      correctOptionId: 'b',
      explanation: 'wollen expresses what someone wants or intends to do.',
    },
    {
      id: 'ch06-ex-05',
      chapterNumber: 6,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['modal-meaning', 'möchten'],
      instruction: 'Choose the modal verb that expresses this meaning.',
      prompt:
        'Which word is the polite way of saying "would like", used for requests and orders?',
      options: [
        { id: 'a', text: 'wollen' },
        { id: 'b', text: 'müssen' },
        { id: 'c', text: 'möchten' },
        { id: 'd', text: 'dürfen' },
      ],
      correctOptionId: 'c',
      explanation:
        'möchten is the polite form related to mögen and is used to make requests sound courteous rather than blunt.',
    },
    {
      id: 'ch06-ex-06',
      chapterNumber: 6,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['permission-vs-ability', 'können'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: 'Meine Oma ist 85 Jahre alt, aber sie ___ noch sehr gut zu Fuß gehen.',
      hint: 'This is about what she is physically capable of.',
      options: [
        { id: 'a', text: 'darf' },
        { id: 'b', text: 'kann' },
        { id: 'c', text: 'muss' },
        { id: 'd', text: 'will' },
      ],
      correctOptionId: 'b',
      explanation:
        'Physical ability is expressed with können, not dürfen. Grandma is capable of walking well.',
    },
    {
      id: 'ch06-ex-07',
      chapterNumber: 6,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['permission-vs-ability', 'dürfen'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: '___ ich bitte kurz mit Ihnen sprechen? (asking your boss for permission)',
      options: [
        { id: 'a', text: 'Kann' },
        { id: 'b', text: 'Will' },
        { id: 'c', text: 'Darf' },
        { id: 'd', text: 'Muss' },
      ],
      correctOptionId: 'c',
      explanation:
        "Asking for someone's permission uses dürfen: Darf ich...? — not können, which asks about ability.",
    },
    {
      id: 'ch06-ex-08',
      chapterNumber: 6,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['permission-vs-ability', 'dürfen'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: 'Der Schüler hebt die Hand und fragt: "___ ich auf die Toilette gehen?"',
      options: [
        { id: 'a', text: 'Darf' },
        { id: 'b', text: 'Kann' },
        { id: 'c', text: 'Will' },
        { id: 'd', text: 'Muss' },
      ],
      correctOptionId: 'a',
      explanation:
        'Asking permission from a teacher uses dürfen. Kann would ask whether the student is physically able to go — not the intended meaning.',
    },
    {
      id: 'ch06-ex-09',
      chapterNumber: 6,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['permission-vs-ability', 'dürfen'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: 'In diesem Museum ___ man leider nicht fotografieren.',
      hint: 'This is a rule, not a question of skill.',
      options: [
        { id: 'a', text: 'kann' },
        { id: 'b', text: 'muss' },
        { id: 'c', text: 'darf' },
        { id: 'd', text: 'will' },
      ],
      correctOptionId: 'c',
      explanation:
        'A rule that forbids something is expressed with nicht dürfen — it is not permitted, regardless of whether one is able to.',
    },
    {
      id: 'ch06-ex-10',
      chapterNumber: 6,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['möchten', 'requests'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: 'Der Kellner fragt höflich: "___ Sie schon bestellen?"',
      options: [
        { id: 'a', text: 'Wollen' },
        { id: 'b', text: 'Müssen' },
        { id: 'c', text: 'Können' },
        { id: 'd', text: 'Möchten' },
      ],
      correctOptionId: 'd',
      explanation:
        'A waiter politely asking whether guests are ready to order uses möchten, the courteous form, not the blunt wollen.',
    },
    {
      id: 'ch06-ex-11',
      chapterNumber: 6,
      order: 11,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['möchten', 'wollen', 'register'],
      instruction: 'Choose the sentence that sounds more polite.',
      prompt: 'Which sentence sounds politer when ordering in a café?',
      options: [
        { id: 'a', text: 'Ich will einen Kaffee.' },
        { id: 'b', text: 'Ich möchte einen Kaffee, bitte.' },
        { id: 'c', text: 'Ich muss einen Kaffee.' },
        { id: 'd', text: 'Ich darf einen Kaffee.' },
      ],
      correctOptionId: 'b',
      explanation:
        'Ich möchte..., bitte is the polite, softened way to order; Ich will can sound demanding, and muss/darf do not fit the meaning of a request.',
    },
    {
      id: 'ch06-ex-12',
      chapterNumber: 6,
      order: 12,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['sentence-completion', 'wollen'],
      instruction: 'Choose the modal verb that best completes the sentence.',
      prompt: 'Wir ___ heute Abend ins Kino gehen, wenn wir Zeit haben.',
      options: [
        { id: 'a', text: 'müssen' },
        { id: 'b', text: 'dürfen' },
        { id: 'c', text: 'wollen' },
        { id: 'd', text: 'können' },
      ],
      correctOptionId: 'c',
      explanation:
        'Wanting or planning to do something is expressed with wollen: we intend to go to the cinema tonight.',
    },
    {
      id: 'ch06-ex-13',
      chapterNumber: 6,
      order: 13,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['können', 'ability'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Ich ___ sehr gut Klavier spielen.',
      acceptedAnswers: ['kann'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'Ability is expressed with kann (from können): Ich kann sehr gut Klavier spielen.',
    },
    {
      id: 'ch06-ex-14',
      chapterNumber: 6,
      order: 14,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['müssen', 'necessity'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Du ___ jetzt ins Bett gehen, es ist schon spät.',
      acceptedAnswers: ['musst'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'musst (from müssen) expresses that there is no other option — it is necessary.',
    },
    {
      id: 'ch06-ex-15',
      chapterNumber: 6,
      order: 15,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dürfen', 'permission-vs-ability'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: '___ ich das Fenster öffnen? Es ist so warm hier.',
      acceptedAnswers: ['darf'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'Asking for permission is expressed with the modal dürfen (darf), not können.',
    },
    {
      id: 'ch06-ex-16',
      chapterNumber: 6,
      order: 16,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['dürfen', 'permission-vs-ability'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Er ___ nicht rauchen; seine Eltern erlauben es nicht.',
      acceptedAnswers: ['darf'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'darf nicht means "is not allowed to" — a rule set by his parents, i.e. permission, not ability.',
    },
    {
      id: 'ch06-ex-17',
      chapterNumber: 6,
      order: 17,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['wollen', 'intention'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Meine Schwester ___ Ärztin werden.',
      acceptedAnswers: ['will'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'will (from wollen) expresses an intention or a strong wish for the future.',
    },
    {
      id: 'ch06-ex-18',
      chapterNumber: 6,
      order: 18,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['möchten', 'conjugation'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Er ___ ein Eis.',
      acceptedAnswers: ['möchte'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'The er/sie/es form of möchten is möchte — with no extra ending, unlike regular verbs.',
    },
    {
      id: 'ch06-ex-19',
      chapterNumber: 6,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['möchten', 'conjugation'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Wir ___ einen Tisch für zwei Personen, bitte.',
      acceptedAnswers: ['möchten'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'The wir form of möchten is möchten, identical to the infinitive — used here to make a polite request at a restaurant.',
    },
    {
      id: 'ch06-ex-20',
      chapterNumber: 6,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['möchten', 'requests'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: '___ Sie noch etwas trinken?',
      acceptedAnswers: ['möchten'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'Möchten Sie ...? is the standard polite way to offer something to a guest.',
    },
    {
      id: 'ch06-ex-21',
      chapterNumber: 6,
      order: 21,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['können', 'word-order'],
      instruction:
        'Write the complete sentence in German. Capitalisation and punctuation are checked.',
      prompt: 'Say that you can speak German. Use können.',
      acceptedAnswers: ['Ich kann Deutsch sprechen.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'können expresses ability, and the infinitive sprechen goes to the end of the clause: Ich kann Deutsch sprechen.',
    },
    {
      id: 'ch06-ex-22',
      chapterNumber: 6,
      order: 22,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['möchten', 'requests'],
      instruction:
        'Write the complete sentence in German. Capitalisation and punctuation are checked.',
      prompt: 'Politely ask for a coffee in a café. Use möchten and bitte.',
      acceptedAnswers: ['Ich möchte einen Kaffee, bitte.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'möchte + bitte makes the request sound polite: Ich möchte einen Kaffee, bitte.',
    },
    {
      id: 'ch06-ex-23',
      chapterNumber: 6,
      order: 23,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['möchten', 'wollen', 'error-correction'],
      instruction:
        'Rewrite the sentence politely, using möchten. Capitalisation and punctuation are checked.',
      prompt: 'Ich will einen Tee.',
      acceptedAnswers: ['Ich möchte einen Tee.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'wollen can sound blunt or demanding; möchte is the polite alternative for the same wish.',
    },
    {
      id: 'ch06-ex-24',
      chapterNumber: 6,
      order: 24,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['müssen', 'word-order'],
      instruction:
        'Write the complete sentence in German. Capitalisation and punctuation are checked.',
      prompt: 'we / must / now / leave',
      acceptedAnswers: ['Wir müssen jetzt gehen.'],
      answerMode: 'normalized',
      placeholder: 'Wir ...',
      maxLength: 60,
      explanation:
        'müssen expresses necessity; the finite modal takes second position and the infinitive gehen goes to the end: Wir müssen jetzt gehen.',
    },
    {
      id: 'ch06-ex-25',
      chapterNumber: 6,
      order: 25,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['permission-vs-ability', 'können'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt:
        'Mein Kollege ___ drei Sprachen fließend sprechen: Deutsch, Englisch und Spanisch.',
      options: [
        { id: 'a', text: 'darf' },
        { id: 'b', text: 'kann' },
        { id: 'c', text: 'muss' },
        { id: 'd', text: 'will' },
      ],
      correctOptionId: 'b',
      explanation:
        'können expresses ability: speaking three languages fluently is a skill, not a rule or an obligation.',
    },
    {
      id: 'ch06-ex-26',
      chapterNumber: 6,
      order: 26,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['können', 'ability'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Meine Schwester ___ sehr gut Ski fahren.',
      acceptedAnswers: ['kann'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation: 'kann (from können) expresses ability — skiing well is a skill.',
    },
    {
      id: 'ch06-ex-27',
      chapterNumber: 6,
      order: 27,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['permission-vs-ability', 'dürfen'],
      instruction: 'Choose the correct modal verb for the context.',
      hint: 'This is a company rule, not a question of skill.',
      prompt:
        'In unserer Firma ___ man nach 16 Uhr das Büro verlassen, wenn die Arbeit fertig ist.',
      options: [
        { id: 'a', text: 'muss' },
        { id: 'b', text: 'kann' },
        { id: 'c', text: 'darf' },
        { id: 'd', text: 'will' },
      ],
      correctOptionId: 'c',
      explanation:
        'A workplace rule that permits leaving early is about permission, expressed with dürfen — not ability or necessity.',
    },
    {
      id: 'ch06-ex-28',
      chapterNumber: 6,
      order: 28,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['möchten', 'requests'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Ich ___ dieses Hemd in Größe M, bitte. (in einem Geschäft)',
      acceptedAnswers: ['möchte'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation: 'möchte is the polite way to ask for something in a shop.',
    },
    {
      id: 'ch06-ex-29',
      chapterNumber: 6,
      order: 29,
      type: 'matching',
      level: 'recognition',
      grammarFocus: ['modal-meaning'],
      instruction: 'Match each meaning to the modal verb that expresses it.',
      prompt: 'Match the meaning with the correct modal verb.',
      pairs: [
        { id: 'ch06-ex29-p1', left: 'You are physically able to do something.', right: 'können' },
        { id: 'ch06-ex29-p2', left: 'Something is required, with no real choice.', right: 'müssen' },
        { id: 'ch06-ex29-p3', left: 'A rule or person allows you to do something.', right: 'dürfen' },
        { id: 'ch06-ex29-p4', left: 'You have a strong wish or firm plan.', right: 'wollen' },
        { id: 'ch06-ex29-p5', left: 'You politely ask for or offer something.', right: 'möchten' },
      ],
      explanation:
        'Each modal verb has one core meaning: können = ability, müssen = necessity, dürfen = permission, wollen = a strong wish or plan, möchten = a polite request.',
    },
    {
      id: 'ch06-ex-30',
      chapterNumber: 6,
      order: 30,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['wollen', 'intention'],
      instruction: 'Choose the correct modal verb for the context.',
      dialogue: [
        {
          speaker: 'Anna',
          german: 'Was sind deine Pläne für nächstes Jahr?',
          english: 'What are your plans for next year?',
        },
        {
          speaker: 'Ben',
          german: 'Ich habe schon alles entschieden.',
          english: "I've already decided everything.",
        },
      ],
      prompt: 'Nächstes Jahr ___ ich nach Australien reisen; das ist mein großer Plan.',
      options: [
        { id: 'a', text: 'muss' },
        { id: 'b', text: 'darf' },
        { id: 'c', text: 'will' },
        { id: 'd', text: 'kann' },
      ],
      correctOptionId: 'c',
      explanation:
        'wollen expresses a firm personal plan or intention — Ben has already decided on this big goal.',
    },
    {
      id: 'ch06-ex-31',
      chapterNumber: 6,
      order: 31,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['müssen', 'necessity'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Wir ___ den Bericht bis Freitag abgeben, sonst gibt es Probleme.',
      acceptedAnswers: ['müssen'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation: 'müssen expresses necessity — the deadline leaves no other option.',
    },
    {
      id: 'ch06-ex-32',
      chapterNumber: 6,
      order: 32,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['permission-vs-ability', 'dürfen', 'error-correction'],
      instruction: 'Find the token that uses the wrong modal verb, and correct it.',
      prompt: 'Ein Fahrlehrer erklärt einem Schüler die Parkregeln. Etwas stimmt nicht.',
      tokens: ['Hier', 'kannst', 'du', 'nicht', 'parken!'],
      errorTokenIndex: 1,
      correction: 'darfst',
      explanation:
        'A parking rule is about permission, not ability — the sentence needs darfst (dürfen), not kannst (können).',
    },
    {
      id: 'ch06-ex-33',
      chapterNumber: 6,
      order: 33,
      type: 'dragToSlots',
      level: 'controlled',
      grammarFocus: ['dürfen', 'permission-vs-ability'],
      instruction: 'Fill in the correct modal verb for the situation.',
      hint: 'A library rule is about permission, not ability.',
      prompt: 'Vervollständige die Bibliotheksregel: "Hier ___ man nicht laut sprechen."',
      templateParts: ['Hier ', ' man nicht laut sprechen.'],
      slots: [{ id: 'ch06-ex33-slot1', correctWord: 'darf' }],
      wordBank: ['darf', 'kann', 'muss', 'will'],
      explanation:
        'A library rule about noise is a matter of permission: darf, not kann, muss, or will.',
    },
    {
      id: 'ch06-ex-34',
      chapterNumber: 6,
      order: 34,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['müssen', 'necessity'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: 'Vor der Prüfung ___ alle Studenten ihren Ausweis zeigen.',
      options: [
        { id: 'a', text: 'dürfen' },
        { id: 'b', text: 'müssen' },
        { id: 'c', text: 'können' },
        { id: 'd', text: 'möchten' },
      ],
      correctOptionId: 'b',
      explanation:
        'Showing an ID before an exam is a required rule — necessity, expressed with müssen.',
    },
    {
      id: 'ch06-ex-35',
      chapterNumber: 6,
      order: 35,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dürfen', 'permission-vs-ability'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Mit 15 Jahren ___ man in Deutschland nicht bis Mitternacht draußen bleiben.',
      acceptedAnswers: ['darf'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'A legal curfew for teenagers is about permission (or its absence): darf ... nicht, not kann or muss.',
    },
    {
      id: 'ch06-ex-36',
      chapterNumber: 6,
      order: 36,
      type: 'matching',
      level: 'production',
      grammarFocus: ['modal-meaning', 'sentence-completion'],
      instruction: 'Match each situation to the sentence that fits it.',
      prompt: 'Match the situation with the correctly formed sentence.',
      pairs: [
        {
          id: 'ch06-ex36-p1',
          left: 'A gym trainer describes what a member is physically capable of.',
          right: 'Er kann zehn Kilometer laufen.',
        },
        {
          id: 'ch06-ex36-p2',
          left: 'A sign at passport control states a requirement.',
          right: 'Sie müssen Ihren Reisepass zeigen.',
        },
        {
          id: 'ch06-ex36-p3',
          left: 'A teacher gives permission to leave the room.',
          right: 'Du darfst jetzt gehen.',
        },
        {
          id: 'ch06-ex36-p4',
          left: 'A friend states a firm plan for the weekend.',
          right: 'Ich will das ganze Wochenende wandern.',
        },
        {
          id: 'ch06-ex36-p5',
          left: 'A guest politely asks for the menu.',
          right: 'Ich möchte die Speisekarte, bitte.',
        },
      ],
      explanation:
        'Each sentence expresses a different core meaning: ability (können), necessity (müssen), permission (dürfen), intention (wollen), or a polite request (möchten).',
    },
    {
      id: 'ch06-ex-37',
      chapterNumber: 6,
      order: 37,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['möchten', 'wollen', 'register', 'error-correction'],
      instruction: 'Find the token that sounds too blunt, and correct it.',
      prompt: 'Ein Gast bittet den Kellner höflich um die Rechnung. Etwas stimmt nicht.',
      tokens: ['Ich', 'will', 'die', 'Rechnung,', 'bitte.'],
      errorTokenIndex: 1,
      correction: 'möchte',
      explanation:
        'wollen sounds blunt for a polite request in a restaurant; möchte is the courteous choice.',
    },
    {
      id: 'ch06-ex-38',
      chapterNumber: 6,
      order: 38,
      type: 'dragToSlots',
      level: 'production',
      grammarFocus: ['wollen', 'intention'],
      instruction: 'Fill in the correct modal verb for the situation.',
      prompt:
        'Vervollständige den Satz über Toms Zukunftsplan: "Tom ___ nach dem Studium ein eigenes Unternehmen gründen."',
      templateParts: ['Tom ', ' nach dem Studium ein eigenes Unternehmen gründen.'],
      slots: [{ id: 'ch06-ex38-slot1', correctWord: 'will' }],
      wordBank: ['will', 'muss', 'darf', 'kann'],
      explanation:
        'A firm personal plan is expressed with wollen (will), not necessity, permission, or ability.',
    },
    {
      id: 'ch06-ex-39',
      chapterNumber: 6,
      order: 39,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['permission-vs-ability', 'können'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: 'Der Torwart ___ hervorragend fangen — das ist sein großes Talent.',
      options: [
        { id: 'a', text: 'darf' },
        { id: 'b', text: 'kann' },
        { id: 'c', text: 'muss' },
        { id: 'd', text: 'möchte' },
      ],
      correctOptionId: 'b',
      explanation:
        "A goalkeeper's catching skill is a talent — ability, expressed with können.",
    },
    {
      id: 'ch06-ex-40',
      chapterNumber: 6,
      order: 40,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['dürfen', 'permission-vs-ability'],
      instruction: 'Write the missing modal verb form. Capitalisation is not checked.',
      prompt: 'Rauchen ist in diesem Gebäude verboten. Hier ___ man nicht rauchen.',
      acceptedAnswers: ['darf'],
      answerMode: 'caseInsensitive',
      placeholder: 'modal verb',
      maxLength: 15,
      explanation:
        'A smoking ban is a rule about what is (not) permitted — dürfen, not können or müssen.',
    },
    {
      id: 'ch06-ex-41',
      chapterNumber: 6,
      order: 41,
      type: 'matching',
      level: 'production',
      grammarFocus: ['modal-meaning', 'sentence-completion'],
      instruction: 'Match each situation to the sentence that fits it.',
      prompt: 'Match the situation with the correctly formed sentence.',
      pairs: [
        {
          id: 'ch06-ex41-p1',
          left: 'A doctor tells a patient a strict requirement before surgery.',
          right: 'Sie müssen vor der Operation nüchtern bleiben.',
        },
        {
          id: 'ch06-ex41-p2',
          left: 'A museum sign grants permission about photos.',
          right: 'Hier darf man ohne Blitz fotografieren.',
        },
        {
          id: 'ch06-ex41-p3',
          left: 'A child boasts about a skill.',
          right: 'Ich kann schon rückwärts zählen.',
        },
        {
          id: 'ch06-ex41-p4',
          left: 'A party host states a firm intention.',
          right: 'Wir wollen bis Mitternacht feiern.',
        },
        {
          id: 'ch06-ex41-p5',
          left: 'A customer at a bakery makes a polite request.',
          right: 'Ich möchte zwei Brötchen, bitte.',
        },
      ],
      explanation:
        'Each sentence expresses a different core meaning: necessity (müssen), permission (dürfen), ability (können), intention (wollen), or a polite request (möchten).',
    },
    {
      id: 'ch06-ex-42',
      chapterNumber: 6,
      order: 42,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['permission-vs-ability', 'dürfen', 'error-correction'],
      instruction: 'Find the token that uses the wrong modal verb, and correct it.',
      hint: 'A pool sign states a rule, not a question of ability.',
      prompt: 'Ein Schild am Schwimmbad erklärt eine Regel. Etwas stimmt nicht.',
      tokens: ['Kinder', 'müssen', 'hier', 'ohne', 'Aufsicht', 'nicht', 'schwimmen.'],
      errorTokenIndex: 1,
      correction: 'dürfen',
      explanation:
        'A rule about what is not permitted uses dürfen nicht, not müssen — this is about permission, not obligation.',
    },
    {
      id: 'ch06-ex-43',
      chapterNumber: 6,
      order: 43,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['möchten', 'requests'],
      instruction: 'Fill in the correct modal verb for the situation.',
      dialogue: [
        {
          speaker: 'Rezeptionist',
          german: 'Guten Tag! Wie kann ich Ihnen helfen?',
          english: 'Good afternoon! How can I help you?',
        },
        {
          speaker: 'Gast',
          german: 'Guten Tag!',
          english: 'Good afternoon!',
        },
      ],
      prompt:
        'Vervollständige die höfliche Bitte des Gastes an der Rezeption: "Wir ___ bitte ein Doppelzimmer für zwei Nächte."',
      templateParts: ['Wir ', ' bitte ein Doppelzimmer für zwei Nächte.'],
      slots: [{ id: 'ch06-ex43-slot1', correctWord: 'möchten' }],
      wordBank: ['möchten', 'wollen', 'müssen', 'können'],
      explanation:
        'möchten is the polite way to state a wish at a hotel reception — wollen would sound too blunt here.',
    },
    {
      id: 'ch06-ex-44',
      chapterNumber: 6,
      order: 44,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['müssen', 'necessity'],
      instruction: 'Choose the correct modal verb for the context.',
      prompt: 'Für die Einreise in dieses Land ___ Touristen ein gültiges Visum haben.',
      options: [
        { id: 'a', text: 'dürfen' },
        { id: 'b', text: 'müssen' },
        { id: 'c', text: 'können' },
        { id: 'd', text: 'wollen' },
      ],
      correctOptionId: 'b',
      explanation:
        'A visa requirement for entry is a necessity, not a matter of permission or ability.',
    },
    {
      id: 'ch06-ex-45',
      chapterNumber: 6,
      order: 45,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['wollen', 'word-order'],
      instruction:
        'Write the complete sentence in German. Capitalisation and punctuation are checked.',
      prompt: 'Say that your parents want to sell the house. Use wollen.',
      acceptedAnswers: ['Meine Eltern wollen das Haus verkaufen.'],
      answerMode: 'normalized',
      placeholder: 'Meine Eltern ...',
      maxLength: 60,
      explanation:
        'wollen expresses the firm intention to sell, and the infinitive verkaufen goes to the end of the clause: Meine Eltern wollen das Haus verkaufen.',
    },
    {
      id: 'ch06-ex-46',
      chapterNumber: 6,
      order: 46,
      type: 'sentenceOrdering',
      level: 'production',
      grammarFocus: ['dürfen', 'word-order'],
      instruction: 'Arrange the segments to form a correct question.',
      prompt: 'Ask your teacher for permission to leave early today.',
      segments: [
        { id: 'ch06-ex46-s1', text: 'Darf' },
        { id: 'ch06-ex46-s2', text: 'ich' },
        { id: 'ch06-ex46-s3', text: 'heute' },
        { id: 'ch06-ex46-s4', text: 'früher' },
        { id: 'ch06-ex46-s5', text: 'gehen?' },
      ],
      explanation:
        'A yes/no question with a modal verb puts the modal first, then the subject, then the rest of the sentence, with the infinitive at the end: Darf ich heute früher gehen?',
    },
    {
      id: 'ch06-ex-47',
      chapterNumber: 6,
      order: 47,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['permission-vs-ability', 'dürfen', 'error-correction'],
      instruction: 'Find the token that uses the wrong modal verb, and correct it.',
      hint: 'A membership rule is about permission, not physical ability.',
      prompt: 'Ein Mitarbeiter im Fitnessstudio erklärt eine Regel. Etwas stimmt nicht.',
      tokens: ['Sie', 'können', 'hier', 'ohne', 'Mitgliedskarte', 'nicht', 'trainieren.'],
      errorTokenIndex: 1,
      correction: 'dürfen',
      explanation:
        'A membership rule is about what is permitted, not about physical ability — it needs dürfen, not können.',
    },
    {
      id: 'ch06-ex-48',
      chapterNumber: 6,
      order: 48,
      type: 'dragToSlots',
      level: 'transfer',
      grammarFocus: ['müssen', 'dürfen', 'sentence-completion'],
      instruction: 'Fill in both correct modal verbs for the situation.',
      prompt:
        'Vervollständige den Satz: "Wir ___ den Vertrag heute unterschreiben, aber wir ___ noch Fragen stellen."',
      templateParts: [
        'Wir ',
        ' den Vertrag heute unterschreiben, aber wir ',
        ' noch Fragen stellen.',
      ],
      slots: [
        { id: 'ch06-ex48-slot1', correctWord: 'müssen' },
        { id: 'ch06-ex48-slot2', correctWord: 'dürfen' },
      ],
      wordBank: ['müssen', 'dürfen', 'können', 'wollen', 'möchten'],
      explanation:
        'The first blank is a necessity (müssen: we have to sign today) and the second is a permission (dürfen: we are still allowed to ask questions).',
    },
    {
      id: 'ch06-ex-49',
      chapterNumber: 6,
      order: 49,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['permission-vs-ability', 'dürfen', 'können'],
      instruction: 'Choose the correct sentence for the context.',
      prompt: 'Welcher Satz drückt eine Erlaubnis aus, keine Fähigkeit?',
      options: [
        { id: 'a', text: 'Sie kann gut malen.' },
        { id: 'b', text: 'Er darf das Auto benutzen.' },
        { id: 'c', text: 'Wir können schnell laufen.' },
        { id: 'd', text: 'Ich kann Klavier spielen.' },
      ],
      correctOptionId: 'b',
      explanation:
        'Only option b uses dürfen, expressing permission; the others use können to describe abilities.',
    },
    {
      id: 'ch06-ex-50',
      chapterNumber: 6,
      order: 50,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['möchten', 'wollen', 'register'],
      instruction:
        'Rewrite the sentence politely, using möchten. Capitalisation and punctuation are checked.',
      prompt: 'Ich will das Zimmer wechseln.',
      acceptedAnswers: ['Ich möchte das Zimmer wechseln.'],
      answerMode: 'normalized',
      placeholder: 'Ich ...',
      maxLength: 60,
      explanation:
        'wollen can sound demanding when asking hotel staff for something; möchte softens the same request.',
    },
    {
      id: 'ch06-ex-51',
      chapterNumber: 6,
      order: 51,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['modal-meaning'],
      instruction: 'Match each sentence to the meaning it expresses.',
      prompt: 'Match the sentence with the meaning it expresses.',
      pairs: [
        {
          id: 'ch06-ex51-p1',
          left: 'Ich kann heute leider nicht kommen, ich bin krank.',
          right: 'ability / inability',
        },
        {
          id: 'ch06-ex51-p2',
          left: 'Du musst deinen Vertrag bis morgen unterschreiben.',
          right: 'necessity',
        },
        {
          id: 'ch06-ex51-p3',
          left: 'Ihr dürft während der Pause das Gebäude verlassen.',
          right: 'permission',
        },
        {
          id: 'ch06-ex51-p4',
          left: 'Sie will unbedingt die Prüfung bestehen.',
          right: 'intention',
        },
        {
          id: 'ch06-ex51-p5',
          left: 'Möchten Sie noch einen Nachtisch?',
          right: 'polite request',
        },
      ],
      explanation:
        'Even without an obvious keyword, context reveals the meaning: illness limits ability, a deadline creates necessity, a break allows permission, determination shows intention, and offering dessert is a polite request.',
    },
    {
      id: 'ch06-ex-52',
      chapterNumber: 6,
      order: 52,
      type: 'errorSpotting',
      level: 'transfer',
      grammarFocus: ['möchten', 'wollen', 'register', 'error-correction'],
      instruction: 'Find the token that sounds too blunt, and correct it.',
      prompt: 'Eine Angestellte schreibt ihrem Chef eine Nachricht. Etwas stimmt nicht.',
      tokens: ['Ich', 'will', 'morgen', 'freinehmen.'],
      errorTokenIndex: 1,
      correction: 'möchte',
      explanation:
        'Asking a boss for a day off should sound polite; möchte is more appropriate than the blunt will.',
    },
    {
      id: 'ch06-ex-53',
      chapterNumber: 6,
      order: 53,
      type: 'matching',
      level: 'transfer',
      grammarFocus: ['modal-meaning'],
      instruction: 'Match each situation to the sentence that fits it.',
      prompt: 'Match the travel situation with the correctly formed sentence.',
      pairs: [
        {
          id: 'ch06-ex53-p1',
          left: 'An airport sign states a security requirement.',
          right: 'Passagiere müssen ihre Schuhe ausziehen.',
        },
        {
          id: 'ch06-ex53-p2',
          left: 'A gate sign grants permission to board early.',
          right: 'Familien mit Kindern dürfen zuerst einsteigen.',
        },
        {
          id: 'ch06-ex53-p3',
          left: 'A traveler describes a language skill.',
          right: 'Ich kann ein bisschen Italienisch sprechen.',
        },
        {
          id: 'ch06-ex53-p4',
          left: 'A traveler states a firm travel goal.',
          right: 'Wir wollen jedes Land in Europa besuchen.',
        },
        {
          id: 'ch06-ex53-p5',
          left: 'A traveler politely asks a flight attendant for water.',
          right: 'Ich möchte bitte etwas Wasser.',
        },
      ],
      explanation:
        'Across these travel situations, the same five core meanings apply: müssen = requirement, dürfen = permission, können = ability, wollen = firm goal, möchten = polite request.',
    },
  ],
};
