import type { ChapterDefinition } from '../../schemas/chapterSchema';

export const chapter073: ChapterDefinition = {
  id: 'chapter-073',
  number: 73,
  slug: 'infinitive-constructions-with-zu',
  title: 'Infinitive Constructions with zu',
  germanTitle: 'Infinitivsätze mit zu',
  level: 'B1',
  section: 'sentence-connections-2',
  objective:
    'Form zu-infinitive constructions after verbs, adjectives, and nouns; place zu correctly before a normal infinitive and inside a separable verb; punctuate extended zu-infinitive clauses with a comma; and recognise when the implied subject genuinely matches the main clause so a zu-construction is possible at all.',
  prerequisites: [8, 46],
  estimatedMinutes: 30,
  tags: [
    'zu-infinitive',
    'infinitivsatz',
    'separable-verbs',
    'comma-rules',
    'clause-combination',
    'sentence-connections',
    'word-order',
    'shared-subject',
  ],
  explanation: {
    introduction: [
      'German often links a second action to a main clause not with a full subordinate clause (weil, wenn, dass — Chapter 46) but with a compact zu-infinitive construction: Ich versuche, pünktlich zu kommen. Here zu plus the bare infinitive (zu kommen) stands in for a whole clause, because the person doing the trying and the person coming are the same: ich. This chapter shows you when this shortcut is possible, exactly where zu goes, and how to punctuate the result.',
      'The key condition is a shared subject: a zu-infinitive clause never has its own subject, so it only works when its implied subject is identical to the subject of the main clause. Ich hoffe, pünktlich anzukommen works because ich is doing both the hoping and the arriving. But "I hope that he arrives on time" cannot become a zu-construction, because the hoper (ich) and the arriver (er) are different people — German must keep the full dass-clause there: Ich hoffe, dass er pünktlich ankommt. Recognising this mismatch is just as important as building the construction correctly.',
      'Beyond verbs like versuchen, beginnen, anfangen, vergessen, and hoffen, zu-infinitives also follow adjective-plus-sein expressions (es ist wichtig/schwierig/möglich, ... zu ...) and nouns (die Möglichkeit, die Idee, die Zeit + zu ...). In every case the same two mechanical rules apply: zu sits directly before a normal infinitive, but splits a separable verb in two, sitting between the prefix and the stem (an + zu + fangen → anzufangen); and a comma is required before an extended zu-infinitive clause (one with more than just the bare infinitive itself), while a single bare infinitive may go without one.',
    ],
    rules: [
      {
        id: 'ch73-rule-01',
        heading: 'What a zu-infinitive construction is',
        paragraphs: [
          'A zu-infinitive construction (Infinitivsatz mit zu) replaces a subordinate clause with zu plus the infinitive of the second verb, placed at the end of its own clause. It has no subject of its own and no finite (conjugated) verb — the infinitive itself never changes form for person or number.',
          'Ich versuche, pünktlich zu kommen. (I am trying to arrive on time.) The infinitive clause zu kommen depends on versuche and shares its subject ich; it is not a separate sentence and cannot stand alone.',
        ],
      },
      {
        id: 'ch73-rule-02',
        heading: 'The shared-subject condition',
        paragraphs: [
          "A zu-infinitive clause is only possible when its implied subject is exactly the subject of the main clause. Er vergisst, seine Tasche mitzunehmen works because er both forgets and (fails to) take the bag — one and the same person doing both actions.",
          "When the two actions have different subjects, German cannot use zu — it must fall back on a dass-clause instead: Ich hoffe, dass er die Prüfung besteht (I hope that he passes the exam) — not *Ich hoffe, ihn die Prüfung zu bestehen. Always check who is doing the second action before reaching for zu.",
        ],
      },
      {
        id: 'ch73-rule-03',
        heading: 'zu before a normal (non-separable) infinitive',
        paragraphs: [
          'With a normal or inseparably-prefixed verb, zu is simply written as its own word directly in front of the infinitive: zu kommen, zu lernen, zu verstehen, zu bezahlen.',
          'Sie hofft, die Prüfung zu bestehen. Er versucht, das Problem zu verstehen. In both cases zu and the infinitive remain two clearly separate words, with zu immediately in front.',
        ],
      },
      {
        id: 'ch73-rule-04',
        heading: 'zu inside a separable verb',
        paragraphs: [
          'With a separable verb, zu is inserted between the separable prefix and the verb stem, and the whole thing is written as one word: an + zu + fangen → anzufangen, ein + zu + kaufen → einzukaufen, auf + zu + stehen → aufzustehen, vor + zu + schlagen → vorzuschlagen.',
          'Er hat vergessen, das Licht auszumachen. (aus + zu + machen → auszumachen) Ich habe keine Lust, heute einzukaufen. This is the same "verb bracket" idea you already know from Chapter 8 — only now zu itself sits inside the bracket, glued between prefix and stem instead of a separate word.',
        ],
      },
      {
        id: 'ch73-rule-05',
        heading: 'The comma: required for extended clauses',
        paragraphs: [
          'A comma is required before a zu-infinitive clause as soon as it is "extended" — that is, it contains more than just the bare infinitive itself (an object, an adverb, a separable prefix, and so on). Ich versuche, heute pünktlich zu kommen needs the comma because heute pünktlich zu kommen is more than one word.',
          'For a single bare infinitive with nothing attached to it, the comma is generally optional: Er verspricht(,) zu helfen. In this course, always write the comma for extended clauses — the far more common case — and treat the bare-infinitive comma as optional, not wrong either way.',
        ],
      },
      {
        id: 'ch73-rule-06',
        heading: 'Common triggers: verbs, adjectives, and nouns',
        paragraphs: [
          'Many verbs regularly introduce a zu-infinitive clause: versuchen, beginnen, anfangen, vergessen, hoffen, vorschlagen, sich freuen auf, sich entscheiden, aufhören, and more. Adjective-plus-sein expressions do too: es ist wichtig/schwierig/möglich/notwendig, ... zu .... And so do certain nouns: die Möglichkeit, die Idee, die Zeit, die Lust + zu ....',
          'Es ist wichtig, jeden Tag Deutsch zu üben. Ich habe die Möglichkeit, im Ausland zu studieren. In each case the zu-infinitive clause explains or completes the verb, adjective, or noun it depends on, just as versuchen does in the opening example.',
        ],
      },
    ],
    tables: [
      {
        id: 'ch73-table-01',
        title: 'Placement of zu: normal/inseparable verbs vs. separable verbs',
        columns: ['Verb type', 'Infinitive', 'zu-infinitive', 'Example clause'],
        rows: [
          ['Normal', 'kommen', 'zu kommen', 'Ich versuche, pünktlich zu kommen.'],
          ['Normal', 'helfen', 'zu helfen', 'Er verspricht, morgen zu helfen.'],
          ['Inseparable prefix', 'bestehen', 'zu bestehen', 'Sie hofft, die Prüfung zu bestehen.'],
          ['Separable prefix', 'anfangen', 'anzufangen', 'Wir beginnen, mit der Arbeit anzufangen.'],
          ['Separable prefix', 'einkaufen', 'einzukaufen', 'Ich habe vergessen, einzukaufen.'],
          ['Separable prefix', 'aufstehen', 'aufzustehen', 'Es ist schwierig, früh aufzustehen.'],
          ['Separable prefix', 'vorschlagen', 'vorzuschlagen', 'Er hat vor, ein Restaurant vorzuschlagen.'],
        ],
        note: 'With normal and inseparable verbs, zu stays a separate word directly before the infinitive. With separable verbs, zu is inserted between the prefix and the stem and the result is written as one word.',
      },
      {
        id: 'ch73-table-02',
        title: 'Common verbs, adjectives, and nouns that take a zu-infinitive',
        columns: ['Type', 'Word', 'English', 'Example'],
        rows: [
          ['Verb', 'versuchen', 'to try', 'Ich versuche, gesünder zu leben.'],
          ['Verb', 'beginnen / anfangen', 'to begin/start', 'Sie beginnt, Deutsch zu lernen.'],
          ['Verb', 'vergessen', 'to forget', 'Er vergisst, die Tür abzuschließen.'],
          ['Verb', 'hoffen', 'to hope', 'Wir hoffen, dich bald zu sehen.'],
          ['Verb', 'sich freuen auf', 'to look forward to', 'Ich freue mich darauf, dich zu sehen.'],
          ['Adjective + sein', 'es ist wichtig', "it's important", 'Es ist wichtig, viel zu üben.'],
          ['Adjective + sein', 'es ist schwierig', "it's difficult", 'Es ist schwierig, früh aufzustehen.'],
          ['Adjective + sein', 'es ist möglich', "it's possible", 'Es ist möglich, den Kurs zu wechseln.'],
          ['Noun', 'die Möglichkeit', 'the possibility/chance', 'Ich habe die Möglichkeit, im Ausland zu studieren.'],
          ['Noun', 'die Idee', 'the idea', 'Das war die Idee, ein Picknick zu machen.'],
        ],
      },
      {
        id: 'ch73-table-03',
        title: 'Comma rule: bare infinitive vs. extended infinitive clause',
        columns: ['Type', 'Example', 'Comma?'],
        rows: [
          ['Bare infinitive (nothing attached)', 'Er verspricht zu helfen.', 'Optional'],
          ['Extended clause (object, adverb, prefix, etc.)', 'Er verspricht, seiner Schwester zu helfen.', 'Required'],
          ['Extended clause with a separable verb', 'Ich habe vergessen, einzukaufen.', 'Required'],
        ],
        note: 'This course always writes the comma before an extended zu-infinitive clause, since that is by far the more common case in real sentences.',
      },
    ],
    examples: [
      {
        german: 'Ich versuche, pünktlich zu kommen.',
        english: 'I am trying to arrive on time.',
        highlight: ['zu kommen'],
        explanation: 'versuchen introduces the zu-infinitive; the comma marks the extended clause pünktlich zu kommen.',
      },
      {
        german: 'Er hat vergessen, das Licht auszumachen.',
        english: 'He forgot to turn off the light.',
        highlight: ['auszumachen'],
        explanation: 'ausmachen is separable, so zu is inserted between aus and machen: auszumachen.',
      },
      {
        german: 'Wir beginnen, mit der Arbeit anzufangen.',
        english: 'We are starting to begin the work.',
        highlight: ['anzufangen'],
        explanation: 'anfangen is separable: an + zu + fangen → anzufangen, written as one word.',
      },
      {
        german: 'Es ist wichtig, jeden Tag Deutsch zu üben.',
        english: 'It is important to practise German every day.',
        highlight: ['zu üben'],
        explanation: 'The adjective expression es ist wichtig introduces a zu-infinitive clause, just like a verb can.',
      },
      {
        german: 'Ich habe die Möglichkeit, im Ausland zu studieren.',
        english: 'I have the chance to study abroad.',
        highlight: ['zu studieren'],
        explanation: 'The noun die Möglichkeit is followed by a zu-infinitive clause explaining what the chance is.',
      },
      {
        german: 'Sie freut sich darauf, ihre Familie zu besuchen.',
        english: 'She is looking forward to visiting her family.',
        highlight: ['zu besuchen'],
        explanation: 'sich freuen auf uses the placeholder darauf before the comma, then the zu-infinitive clause explains what darauf refers to.',
      },
      {
        german: 'Er hat vor, ein Restaurant vorzuschlagen.',
        english: 'He intends to suggest a restaurant.',
        highlight: ['vorzuschlagen'],
        explanation: 'vorschlagen is separable: vor + zu + schlagen → vorzuschlagen.',
      },
      {
        german: 'Ich hoffe, dass er pünktlich ankommt.',
        english: 'I hope that he arrives on time.',
        highlight: ['dass er pünktlich ankommt'],
        explanation: 'The subject of ankommt (er) differs from the subject of hoffe (ich), so a zu-construction is impossible here; a dass-clause is required instead.',
      },
      {
        german: 'Ich hoffe, pünktlich anzukommen.',
        english: 'I hope to arrive on time.',
        highlight: ['anzukommen'],
        explanation: 'Here the hoper and the arriver are the same person (ich), so the zu-infinitive is possible: an + zu + kommen → anzukommen.',
      },
      {
        german: 'Er verspricht zu helfen.',
        english: 'He promises to help.',
        highlight: ['zu helfen'],
        explanation: 'A single bare infinitive with nothing attached to it may go without a comma.',
      },
      {
        german: 'Er verspricht, seiner Schwester bei den Hausaufgaben zu helfen.',
        english: 'He promises to help his sister with the homework.',
        highlight: ['zu helfen'],
        explanation: 'Once the infinitive clause is extended with an object and a prepositional phrase, the comma is required.',
      },
      {
        german: 'Es ist möglich, den Kurs zu wechseln.',
        english: 'It is possible to switch the course.',
        highlight: ['zu wechseln'],
        explanation: 'es ist möglich is another adjective-plus-sein expression that takes a zu-infinitive clause.',
      },
      {
        german: 'Ich habe keine Zeit, heute einzukaufen.',
        english: 'I have no time to shop today.',
        highlight: ['einzukaufen'],
        explanation: 'die Zeit + zu introduces the clause; einkaufen is separable, so zu sits inside it: einzukaufen.',
      },
    ],
    commonMistakes: [
      {
        incorrect: 'Ich versuche, zuanfangen.',
        correct: 'Ich versuche, anzufangen.',
        explanation: 'zu is never simply glued in front of a separable verb; it must be inserted between the prefix and the stem: an + zu + fangen → anzufangen.',
      },
      {
        incorrect: 'Er hat vergessen, zu ausmachen das Licht.',
        correct: 'Er hat vergessen, das Licht auszumachen.',
        explanation: 'zu splits the separable verb ausmachen into auszumachen, and the whole infinitive clause stands at the end: das Licht auszumachen.',
      },
      {
        incorrect: 'Ich hoffe, ihn die Prüfung zu bestehen.',
        correct: 'Ich hoffe, dass er die Prüfung besteht.',
        explanation: 'The subject of hoffe (ich) and the subject of besteht (er) are different people, so a zu-infinitive is impossible — a dass-clause with its own subject is required.',
      },
      {
        incorrect: 'Ich versuche pünktlich zu kommen ohne Komma.',
        correct: 'Ich versuche, pünktlich zu kommen.',
        explanation: 'An extended zu-infinitive clause (more than the bare infinitive) always needs a comma before it, here before pünktlich.',
      },
      {
        incorrect: 'Es ist wichtig, dass zu üben jeden Tag.',
        correct: 'Es ist wichtig, jeden Tag zu üben.',
        explanation: 'A zu-infinitive clause never uses dass and never has its own conjugated verb; the infinitive with zu goes at the end of the clause.',
      },
      {
        incorrect: 'Sie beginnt Deutsch lernen zu.',
        correct: 'Sie beginnt, Deutsch zu lernen.',
        explanation: 'zu always comes directly before the infinitive it belongs to (zu lernen), never after it, and the clause needs its comma.',
      },
    ],
    remember: [
      'A zu-infinitive clause replaces a subordinate clause when the implied subject of the second action is identical to the subject of the main clause.',
      'If the two actions have different subjects, use a dass-clause instead — a zu-infinitive clause can never have its own subject.',
      'With normal and inseparable verbs, zu stays a separate word right before the infinitive: zu kommen, zu bestehen.',
      'With separable verbs, zu is inserted between the prefix and the stem and written as one word: anzufangen, einzukaufen, aufzustehen, vorzuschlagen.',
      'A comma is required before an extended zu-infinitive clause (more than the bare infinitive); it is optional for a single bare infinitive alone.',
      'Common triggers include verbs (versuchen, beginnen, vergessen, hoffen, sich freuen auf), adjective expressions (es ist wichtig/schwierig/möglich), and nouns (die Möglichkeit, die Idee, die Zeit).',
    ],
  },
  mastery: {
    passingPercent: 80,
    minimumAnswered: 30,
    requiredCorrectTextInputs: 10,
    maxOpenReviewFlags: 3,
  },
  exercises: [
    {
      id: 'ch73-ex-01',
      chapterNumber: 73,
      order: 1,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['zu-infinitive', 'basic-pattern'],
      instruction: 'Choose the sentence with correctly placed zu.',
      prompt: '"I am trying to arrive on time." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich versuche, pünktlich zu kommen.' },
        { id: 'b', text: 'Ich versuche, pünktlich kommen zu.' },
        { id: 'c', text: 'Ich versuche zu, pünktlich kommen.' },
        { id: 'd', text: 'Ich versuche, zu pünktlich kommen.' },
      ],
      correctOptionId: 'a',
      explanation: 'zu stands directly before the infinitive kommen, and the extended clause needs a comma: ..., pünktlich zu kommen.',
    },
    {
      id: 'ch73-ex-02',
      chapterNumber: 73,
      order: 2,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Choose the correctly formed zu-infinitive.',
      prompt: 'anfangen → ?',
      options: [
        { id: 'a', text: 'anzufangen' },
        { id: 'b', text: 'zuanfangen' },
        { id: 'c', text: 'an zu fangen' },
        { id: 'd', text: 'fangenzu an' },
      ],
      correctOptionId: 'a',
      explanation: 'zu is inserted between the separable prefix an and the stem fangen, and the whole thing is written as one word: anzufangen.',
    },
    {
      id: 'ch73-ex-03',
      chapterNumber: 73,
      order: 3,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Choose the correctly formed zu-infinitive.',
      prompt: 'einkaufen → ?',
      options: [
        { id: 'a', text: 'einzukaufen' },
        { id: 'b', text: 'zueinkaufen' },
        { id: 'c', text: 'ein zu kaufen' },
        { id: 'd', text: 'kaufenzu ein' },
      ],
      correctOptionId: 'a',
      explanation: 'ein + zu + kaufen combine into a single word: einzukaufen.',
    },
    {
      id: 'ch73-ex-04',
      chapterNumber: 73,
      order: 4,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Choose the correctly formed zu-infinitive.',
      prompt: 'aufstehen → ?',
      options: [
        { id: 'a', text: 'aufzustehen' },
        { id: 'b', text: 'zuaufstehen' },
        { id: 'c', text: 'auf zu stehen' },
        { id: 'd', text: 'stehenzu auf' },
      ],
      correctOptionId: 'a',
      explanation: 'auf + zu + stehen combine into a single word: aufzustehen.',
    },
    {
      id: 'ch73-ex-05',
      chapterNumber: 73,
      order: 5,
      type: 'singleChoice',
      level: 'recognition',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Choose the correctly formed zu-infinitive.',
      prompt: 'vorschlagen → ?',
      options: [
        { id: 'a', text: 'vorzuschlagen' },
        { id: 'b', text: 'zuvorschlagen' },
        { id: 'c', text: 'vor zu schlagen' },
        { id: 'd', text: 'schlagenzu vor' },
      ],
      correctOptionId: 'a',
      explanation: 'vor + zu + schlagen combine into a single word: vorzuschlagen.',
    },
    {
      id: 'ch73-ex-06',
      chapterNumber: 73,
      order: 6,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'normal-verb'],
      instruction: 'Choose the sentence with correctly placed zu.',
      prompt: '"She hopes to pass the exam." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Sie hofft, die Prüfung zu bestehen.' },
        { id: 'b', text: 'Sie hofft, die Prüfung bestehen zu.' },
        { id: 'c', text: 'Sie hofft, zu die Prüfung bestehen.' },
        { id: 'd', text: 'Sie hofft zu, die Prüfung bestehen.' },
      ],
      correctOptionId: 'a',
      explanation: 'bestehen is a normal (inseparable) verb, so zu stands right before it: zu bestehen.',
    },
    {
      id: 'ch73-ex-07',
      chapterNumber: 73,
      order: 7,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'comma'],
      instruction: 'Choose the correctly punctuated sentence.',
      prompt: '"He promises to help his sister." Which sentence is correctly punctuated?',
      options: [
        { id: 'a', text: 'Er verspricht, seiner Schwester zu helfen.' },
        { id: 'b', text: 'Er verspricht seiner Schwester, zu helfen.' },
        { id: 'c', text: 'Er verspricht seiner Schwester zu helfen ohne Komma.' },
        { id: 'd', text: 'Er, verspricht seiner Schwester zu helfen.' },
      ],
      correctOptionId: 'a',
      explanation: 'The comma marks the start of the extended zu-infinitive clause seiner Schwester zu helfen, before the object, not in the middle of it.',
    },
    {
      id: 'ch73-ex-08',
      chapterNumber: 73,
      order: 8,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'shared-subject'],
      instruction: 'Choose the sentence that is grammatically possible.',
      prompt: '"I hope that he arrives on time." Which German sentence is correct?',
      options: [
        { id: 'a', text: 'Ich hoffe, dass er pünktlich ankommt.' },
        { id: 'b', text: 'Ich hoffe, ihn pünktlich anzukommen.' },
        { id: 'c', text: 'Ich hoffe, er pünktlich anzukommen.' },
        { id: 'd', text: 'Ich hoffe, pünktlich ihn anzukommen.' },
      ],
      correctOptionId: 'a',
      explanation: 'The subject of ankommt (er) differs from the subject of hoffe (ich), so a zu-infinitive is impossible; a dass-clause is required.',
    },
    {
      id: 'ch73-ex-09',
      chapterNumber: 73,
      order: 9,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'shared-subject'],
      instruction: 'Choose the sentence that is grammatically possible.',
      prompt: '"I hope to arrive on time." Which German sentence is correct?',
      options: [
        { id: 'a', text: 'Ich hoffe, pünktlich anzukommen.' },
        { id: 'b', text: 'Ich hoffe, dass ich pünktlich anzukommen.' },
        { id: 'c', text: 'Ich hoffe, mich pünktlich anzukommen.' },
        { id: 'd', text: 'Ich hoffe pünktlich, anzukommen ich.' },
      ],
      correctOptionId: 'a',
      explanation: 'Here the hoper and the arriver are the same person (ich), so the zu-infinitive anzukommen is correct.',
    },
    {
      id: 'ch73-ex-10',
      chapterNumber: 73,
      order: 10,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'adjective-expression'],
      instruction: 'Choose the sentence with correctly placed zu.',
      prompt: '"It is important to practise German every day." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Es ist wichtig, jeden Tag Deutsch zu üben.' },
        { id: 'b', text: 'Es ist wichtig, jeden Tag Deutsch üben zu.' },
        { id: 'c', text: 'Es ist wichtig zu, jeden Tag Deutsch üben.' },
        { id: 'd', text: 'Es ist wichtig, dass jeden Tag Deutsch zu üben.' },
      ],
      correctOptionId: 'a',
      explanation: 'es ist wichtig introduces a zu-infinitive clause; zu stands right before üben at the end.',
    },
    {
      id: 'ch73-ex-11',
      chapterNumber: 73,
      order: 11,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'noun-expression'],
      instruction: 'Choose the sentence with correctly placed zu.',
      prompt: '"I have the chance to study abroad." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Ich habe die Möglichkeit, im Ausland zu studieren.' },
        { id: 'b', text: 'Ich habe die Möglichkeit, im Ausland studieren zu.' },
        { id: 'c', text: 'Ich habe die Möglichkeit zu, im Ausland studieren.' },
        { id: 'd', text: 'Ich habe, die Möglichkeit im Ausland zu studieren.' },
      ],
      correctOptionId: 'a',
      explanation: 'die Möglichkeit introduces the zu-infinitive clause; the comma comes right after Möglichkeit, before the extended clause.',
    },
    {
      id: 'ch73-ex-12',
      chapterNumber: 73,
      order: 12,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['zu-infinitive', 'separable-verb', 'dialogue'],
      instruction: 'Choose the grammatically correct way for Tom to finish his sentence.',
      dialogue: [
        { speaker: 'Anna', german: 'Was hast du heute noch vor?', english: 'What else are you planning today?' },
        {
          speaker: 'Tom',
          german: 'Ich habe vor, ...',
          english: 'I intend to ...',
        },
      ],
      prompt: 'Ich habe vor, ___ (heute noch / einkaufen)',
      options: [
        { id: 'a', text: 'heute noch einzukaufen.' },
        { id: 'b', text: 'heute noch zueinkaufen.' },
        { id: 'c', text: 'heute noch ein zu kaufen.' },
        { id: 'd', text: 'heute noch einkaufen zu.' },
      ],
      correctOptionId: 'a',
      explanation: 'einkaufen is separable: ein + zu + kaufen → einzukaufen, written as one word at the end of the clause.',
    },
    {
      id: 'ch73-ex-13',
      chapterNumber: 73,
      order: 13,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['zu-infinitive', 'comma', 'bare-infinitive'],
      instruction: 'Choose the sentence that follows the comma rule correctly.',
      prompt: 'Which of these sentences uses a single bare infinitive, where the comma is optional?',
      options: [
        { id: 'a', text: 'Er verspricht zu helfen.' },
        { id: 'b', text: 'Er verspricht, seiner Schwester bei den Hausaufgaben zu helfen.' },
        { id: 'c', text: 'Er verspricht, morgen früh zu kommen.' },
        { id: 'd', text: 'Er verspricht, das Geschirr zu spülen.' },
      ],
      correctOptionId: 'a',
      explanation: 'Er verspricht zu helfen has only the bare infinitive zu helfen with nothing attached, so the comma is optional; the others are extended clauses that require it.',
    },
    {
      id: 'ch73-ex-14',
      chapterNumber: 73,
      order: 14,
      type: 'singleChoice',
      level: 'production',
      grammarFocus: ['zu-infinitive', 'clause-combination'],
      instruction: 'Choose the sentence that correctly combines the two ideas with a zu-infinitive.',
      prompt: 'Ich beginne. + Ich lerne Deutsch. → ?',
      options: [
        { id: 'a', text: 'Ich beginne, Deutsch zu lernen.' },
        { id: 'b', text: 'Ich beginne, dass ich Deutsch zu lernen.' },
        { id: 'c', text: 'Ich beginne, Deutsch lernen zu.' },
        { id: 'd', text: 'Ich beginne zu, Deutsch lernen.' },
      ],
      correctOptionId: 'a',
      explanation: 'Both clauses share the subject ich, so they combine into one zu-infinitive clause: Ich beginne, Deutsch zu lernen.',
    },
    {
      id: 'ch73-ex-15',
      chapterNumber: 73,
      order: 15,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'shared-subject', 'clause-combination'],
      instruction: 'Choose the correct combination, or the correct fallback if a zu-construction is impossible.',
      prompt: 'Ich freue mich. + Meine Eltern besuchen mich. → ?',
      options: [
        { id: 'a', text: 'Ich freue mich darauf, dass meine Eltern mich besuchen.' },
        { id: 'b', text: 'Ich freue mich darauf, meine Eltern zu besuchen.' },
        { id: 'c', text: 'Ich freue mich darauf, meine Eltern besuchen zu.' },
        { id: 'd', text: 'Ich freue mich, meine Eltern zu besuchen mich.' },
      ],
      correctOptionId: 'a',
      explanation: 'The subject of "freue mich" (ich) differs from the subject of "besuchen" (meine Eltern), so a zu-infinitive is impossible; a dass-clause is required.',
    },
    {
      id: 'ch73-ex-16',
      chapterNumber: 73,
      order: 16,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'error-correction'],
      instruction: 'Choose the correction of the mistake.',
      prompt: 'Falsch: Ich versuche, zuanfangen. Richtig?',
      options: [
        { id: 'a', text: 'Ich versuche, anzufangen.' },
        { id: 'b', text: 'Ich versuche, an zu fangen.' },
        { id: 'c', text: 'Ich versuche, zu anfangen.' },
        { id: 'd', text: 'Ich versuche zu, anfangen.' },
      ],
      correctOptionId: 'a',
      explanation: 'zu must split the separable verb from inside, not simply attach in front of it: anzufangen, not zuanfangen.',
    },
    {
      id: 'ch73-ex-17',
      chapterNumber: 73,
      order: 17,
      type: 'singleChoice',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'verb-choice'],
      instruction: 'Choose the verb that correctly completes the sentence.',
      prompt: 'Er hat ___, die Tür abzuschließen. (forgot)',
      options: [
        { id: 'a', text: 'vergessen' },
        { id: 'b', text: 'vergisst' },
        { id: 'c', text: 'vergaß zu' },
        { id: 'd', text: 'vergisst zu' },
      ],
      correctOptionId: 'a',
      explanation: 'This is the present perfect: Er hat vergessen, die Tür abzuschließen — hat vergessen is the finite verb phrase, and the zu-infinitive clause follows.',
    },
    {
      id: 'ch73-ex-18',
      chapterNumber: 73,
      order: 18,
      type: 'singleChoice',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Choose the sentence with correctly placed zu.',
      prompt: '"It is difficult to get up early." Which sentence is correct?',
      options: [
        { id: 'a', text: 'Es ist schwierig, früh aufzustehen.' },
        { id: 'b', text: 'Es ist schwierig, früh auf zu stehen.' },
        { id: 'c', text: 'Es ist schwierig, früh zuaufstehen.' },
        { id: 'd', text: 'Es ist schwierig aufzustehen, früh.' },
      ],
      correctOptionId: 'a',
      explanation: 'aufstehen is separable: auf + zu + stehen → aufzustehen, one word at the end of the clause.',
    },
    {
      id: 'ch73-ex-19',
      chapterNumber: 73,
      order: 19,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Write only the missing zu-infinitive. Capitalisation is not checked.',
      prompt: 'Ich versuche, morgen früh ___. (aufstehen)',
      acceptedAnswers: ['aufzustehen'],
      answerMode: 'caseInsensitive',
      placeholder: 'aufzustehen',
      maxLength: 20,
      explanation: 'aufstehen is separable: zu is inserted between auf and stehen: aufzustehen.',
    },
    {
      id: 'ch73-ex-20',
      chapterNumber: 73,
      order: 20,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Write only the missing zu-infinitive. Capitalisation is not checked.',
      prompt: 'Er hat vor, ein neues Restaurant ___. (vorschlagen)',
      acceptedAnswers: ['vorzuschlagen'],
      answerMode: 'caseInsensitive',
      placeholder: 'vorzuschlagen',
      maxLength: 20,
      explanation: 'vorschlagen is separable: vor + zu + schlagen → vorzuschlagen.',
    },
    {
      id: 'ch73-ex-21',
      chapterNumber: 73,
      order: 21,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'normal-verb'],
      instruction: 'Write only the missing zu-infinitive. Capitalisation is not checked.',
      prompt: 'Sie hofft, die Prüfung ___. (bestehen)',
      acceptedAnswers: ['zu bestehen'],
      answerMode: 'caseInsensitive',
      placeholder: 'zu bestehen',
      maxLength: 20,
      explanation: 'bestehen is a normal verb, so zu stays a separate word right before it: zu bestehen.',
    },
    {
      id: 'ch73-ex-22',
      chapterNumber: 73,
      order: 22,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Write only the missing zu-infinitive. Capitalisation is not checked.',
      prompt: 'Ich habe keine Lust, heute ___. (einkaufen)',
      acceptedAnswers: ['einzukaufen'],
      answerMode: 'caseInsensitive',
      placeholder: 'einzukaufen',
      maxLength: 20,
      explanation: 'einkaufen is separable: ein + zu + kaufen → einzukaufen.',
    },
    {
      id: 'ch73-ex-23',
      chapterNumber: 73,
      order: 23,
      type: 'textInput',
      level: 'controlled',
      grammarFocus: ['zu-infinitive', 'separable-verb'],
      instruction: 'Write only the missing zu-infinitive. Capitalisation is not checked.',
      prompt: 'Wir beginnen, mit dem Projekt ___. (anfangen)',
      acceptedAnswers: ['anzufangen'],
      answerMode: 'caseInsensitive',
      placeholder: 'anzufangen',
      maxLength: 20,
      explanation: 'anfangen is separable: an + zu + fangen → anzufangen.',
    },
    {
      id: 'ch73-ex-24',
      chapterNumber: 73,
      order: 24,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['zu-infinitive', 'clause-combination'],
      instruction: 'Combine the two sentences into one zu-infinitive construction. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich versuche. + Ich komme pünktlich. (versuchen)',
      acceptedAnswers: ['Ich versuche, pünktlich zu kommen.'],
      answerMode: 'normalized',
      placeholder: 'Ich versuche, ...',
      maxLength: 60,
      explanation: 'Both clauses share the subject ich, so they combine: Ich versuche, pünktlich zu kommen.',
    },
    {
      id: 'ch73-ex-25',
      chapterNumber: 73,
      order: 25,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['zu-infinitive', 'clause-combination', 'separable-verb'],
      instruction: 'Combine the two sentences into one zu-infinitive construction. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Er hat vergessen. + Er macht das Licht aus. (vergessen)',
      acceptedAnswers: ['Er hat vergessen, das Licht auszumachen.'],
      answerMode: 'normalized',
      placeholder: 'Er hat vergessen, ...',
      maxLength: 60,
      explanation: 'ausmachen is separable, so zu splits it: auszumachen. Full sentence: Er hat vergessen, das Licht auszumachen.',
    },
    {
      id: 'ch73-ex-26',
      chapterNumber: 73,
      order: 26,
      type: 'textInput',
      level: 'production',
      grammarFocus: ['zu-infinitive', 'clause-combination', 'noun-expression'],
      instruction: 'Combine the two sentences into one zu-infinitive construction. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Ich habe die Möglichkeit. + Ich studiere im Ausland. (die Möglichkeit)',
      acceptedAnswers: ['Ich habe die Möglichkeit, im Ausland zu studieren.'],
      answerMode: 'normalized',
      placeholder: 'Ich habe die Möglichkeit, ...',
      maxLength: 60,
      explanation: 'Both clauses share the subject ich, so they combine: Ich habe die Möglichkeit, im Ausland zu studieren.',
    },
    {
      id: 'ch73-ex-27',
      chapterNumber: 73,
      order: 27,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'shared-subject', 'clause-combination'],
      instruction: 'Decide whether the two sentences can combine with zu. If the subjects match, write the zu-construction; if not, write a dass-clause instead. Capitalisation and punctuation are checked.',
      prompt: 'Ich hoffe. + Er kommt pünktlich an. (hoffen)',
      acceptedAnswers: ['Ich hoffe, dass er pünktlich ankommt.'],
      answerMode: 'normalized',
      placeholder: 'Ich hoffe, ...',
      maxLength: 60,
      explanation: 'The subjects differ (ich hofft, er kommt an), so a zu-infinitive is impossible; a dass-clause is required instead.',
    },
    {
      id: 'ch73-ex-28',
      chapterNumber: 73,
      order: 28,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'shared-subject', 'clause-combination'],
      instruction: 'Decide whether the two sentences can combine with zu. If the subjects match, write the zu-construction; if not, write a dass-clause instead. Capitalisation and punctuation are checked.',
      prompt: 'Ich hoffe. + Ich komme pünktlich an. (hoffen)',
      acceptedAnswers: ['Ich hoffe, pünktlich anzukommen.'],
      answerMode: 'normalized',
      placeholder: 'Ich hoffe, ...',
      maxLength: 60,
      explanation: 'Both clauses share the subject ich, so a zu-infinitive is possible: ankommen is separable, so zu splits it: anzukommen.',
    },
    {
      id: 'ch73-ex-29',
      chapterNumber: 73,
      order: 29,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'error-correction', 'separable-verb'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich versuche, zuanfangen.',
      acceptedAnswers: ['Ich versuche, anzufangen.'],
      answerMode: 'normalized',
      placeholder: 'Ich versuche, ...',
      maxLength: 40,
      explanation: 'zu must be inserted between the prefix and the stem of a separable verb, not glued in front of it: anzufangen, not zuanfangen.',
    },
    {
      id: 'ch73-ex-30',
      chapterNumber: 73,
      order: 30,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'error-correction', 'comma'],
      instruction: 'Correct the mistake. Write the full, corrected sentence. Capitalisation and punctuation are checked.',
      prompt: 'Falsch: Ich versuche pünktlich zu kommen ohne Komma.',
      acceptedAnswers: ['Ich versuche, pünktlich zu kommen.'],
      answerMode: 'normalized',
      placeholder: 'Ich versuche, ...',
      maxLength: 40,
      explanation: 'An extended zu-infinitive clause (pünktlich zu kommen) requires a comma before it.',
    },
    {
      id: 'ch73-ex-31',
      chapterNumber: 73,
      order: 31,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'dialogue', 'separable-verb'],
      instruction: "Complete Lea's answer using a zu-infinitive. Write only the missing words. Capitalisation is not checked.",
      dialogue: [
        { speaker: 'Ben', german: 'Was schlägst du für den Abend vor?', english: 'What do you suggest for the evening?' },
        {
          speaker: 'Lea',
          german: 'Ich habe vor, ein Kino ___.',
          english: 'I intend to suggest a cinema.',
        },
      ],
      prompt: 'Ich habe vor, ein Kino ___. (vorschlagen)',
      acceptedAnswers: ['vorzuschlagen'],
      answerMode: 'caseInsensitive',
      placeholder: 'vorzuschlagen',
      maxLength: 20,
      explanation: 'vorschlagen is separable: vor + zu + schlagen → vorzuschlagen.',
    },
    {
      id: 'ch73-ex-32',
      chapterNumber: 73,
      order: 32,
      type: 'textInput',
      level: 'transfer',
      grammarFocus: ['zu-infinitive', 'adjective-expression', 'clause-combination'],
      instruction: 'Combine the two sentences into one zu-infinitive construction. Write the full sentence. Capitalisation and punctuation are checked.',
      prompt: 'Es ist wichtig. + Man übt jeden Tag Deutsch. (es ist wichtig)',
      acceptedAnswers: ['Es ist wichtig, jeden Tag Deutsch zu üben.'],
      answerMode: 'normalized',
      placeholder: 'Es ist wichtig, ...',
      maxLength: 60,
      explanation: 'The implied subject of üben matches the general subject man of the first clause, so they combine into one zu-infinitive clause.',
    },
  ],
};
